### ISSUE TITLE
Status of controller?

### ISSUE THREAD

**Issue by jasonchester** [Kong/kubernetes-ingress-controller#1]
Great to see the code in the wild. 

I was just curious if this is something we should consider ready for production and/or development purposes?

**Comment by aledbf** [comment]
@jasonchester for now, consider the state of the ingress controller for development environments only.
Before considering this for production we need feedback from users and implement some of the items present in the [roadmap](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/roadmap.md)

**Comment by aledbf** [comment]
Closing. Please reopen if you have more questions.
