### ISSUE TITLE
If a plugin is missing, log entry should include plugin name

### ISSUE THREAD

**Issue by wheestermans31** [Kong/kubernetes-ingress-controller#1002]
We have upgrade the Kong Ingress controller from version 0.8.1 to 1.0.0, and we see some difference in error reporting for non found plugin info.

Version 0.8.1	

E0107 21:02:23.092573       1 parser.go:1331] fetching KongPlugin 'tme-ns-cms-uat/oidc-auth-acc': no KongPlugin or KongClusterPlugin was found

Version 1.0.0

time="2021-01-07T21:04:29Z" level=error msg="failed to fetch KongPlugin: no KongPlugin or KongClusterPlugin was found"

We are running Kong Enterprise 2.1.4.3

**Comment by mflendrich** [comment]
Hi @wheestermans31,

This change is intentional. KIC 0.10.0 introduced structured logging.
Why is the difference important for you?

**Comment by wheestermans31** [comment]
The info we miss is the name of the KongPlugin that is not found

**Comment by mflendrich** [comment]
> The info we miss is the name of the KongPlugin that is not found

Oh, I see. This is a regression indeed.

Would you be interested in contributing a patch adding a log field with the plugin name back? We'd appreciate your help!
