### ISSUE TITLE
Certificate expired     https://kong-docker-kubernetes-ingress-controller.bintray.io/

### ISSUE THREAD

**Issue by aogg** [Kong/kubernetes-ingress-controller#1004]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**

**Kong or Kong Enterprise version**

### Kubernetes version

**paste `kubectl version` output**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### Steps To Reproduce

1. https://kong-docker-kubernetes-ingress-controller.bintray.io/
2.
3.
4.

![image](https://user-images.githubusercontent.com/8998031/104428914-fefc6380-55bf-11eb-9164-8f63d42a4b0c.png)

**Comment by mflendrich** [comment]
Bintray is an external service. We don't control their TLS certificates.

It seems that the certificate served by Bintray today is a different one than your screenshot (DigiCert, not GeoTrust; valid from 2020-12-29 until 2022-01-04), which implies that Bintray rotated their server certificate and the issue no longer persists.

Closing as resolved.

**Comment by aogg** [comment]
Failed to pull image "kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.1": rpc error: code = Unknown desc = Error response from daemon: Get https://kong-docker-kubernetes-ingress-controller.bintray.io/v2/: x509: certificate has expired or is not yet valid

**Comment by aogg** [comment]
pull error

**Comment by NICK-DUAN** [comment]
same error.

**Comment by mflendrich** [comment]
Further discussion on Kong/charts#257

**Comment by liuzhenji** [comment]
> same error.

same again

**Comment by vinisants** [comment]
same error here with error 403 forbidden
