### ISSUE TITLE
structured logging: extract errors to a separate field

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1013]
KIC utilizes structured logging (#748) but still records errors (among other things) in the log entry message (instead of dedicated fields).

A quick (and very incomplete) search  `rgrep 'log\..*Errorf(.*%v'` identifies ~20 such locations.
The scope of this issue is to replace uses of format strings with [`WithError()`](https://godoc.org/gopkg.in/Sirupsen/logrus.v0#WithError) and [`WithField()`](https://godoc.org/gopkg.in/Sirupsen/logrus.v0#WithField).

**Comment by mflendrich** [comment]
Promoting this to higher importance than "nice-to-have". I do feel that this is an important usability factor for users of structured logging systems, and also makes alerting easier.

**Comment by randmonkey** [comment]
All `log.*.Errorf("blah blah, %v",err)` should be replaced with `log.*.WithError(err).Error("blah blah")`?

**Comment by randmonkey** [comment]
searched for `log.*` in the repo, and found 12 files(including a generated file `internal/controllers/configuration/zz_generated_controllers.go`) using `github.com/go-logr/logr` which does not support structured logging. Is it needed to change all these `logr` to `logrus` for structured logging?
