### ISSUE TITLE
Support KIC on ARM64

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1019]
Challenges:
- ensure that our image registry supports multi-arch
- ensure that we guarantee the same quality level (regression testing, perf testing)

Opportunities:
- blog about support for Ingress on Raspberry PIs to get extra community attention

@shaneutt says that GH Actions can test ARM64

**Comment by shaneutt** [comment]
Just a clarification, currently you need to use [self hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners) for ARM64 builds in github actions:

https://github.com/actions/virtual-environments/issues/2536

The [actions documentation](https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow#using-default-labels-to-route-jobs) provides more information.

**Comment by hutchic** [comment]
self-hosted runners is how we currently build our ARM64 builds.

**Comment by tydra-wang** [comment]
> ensure that we guarantee the same quality level (regression testing, perf testing)

Any progress?

**Comment by shaneutt** [comment]
> > ensure that we guarantee the same quality level (regression testing, perf testing)
> 
> Any progress?

No progress yet, we're still grooming this. Hearing people's use cases and desire for this platform support here is welcome, as we would like a better understanding of how important this is to our community.

**Comment by adasauce** [comment]
definitely interested in this here, working on configuring a multi-arch cluster with multiple ARM edges and I was really hoping on being able to use this.

Is anyone already using an ARM image unofficially that can confirm whether or not it works as expected?

**Comment by shaneutt** [comment]
The maintainers are still working through this, we're not ready to add the support for ARM64 just yet as several open questions about maintenance remain.

**Comment by shaneutt** [comment]
Given other priorities and a lack of engagement we're not moving forward with arm64 at this time. However if anyone feels strongly and wants go advocate further for arm64 support please don't hesitate to comment and reopen this issue.

**Comment by kevarr-vg** [comment]
Hello, I know this issue has been closed for some time but wanted to ask if the maintainers could consider to re-reviewing this request. For a use case I would like to use Kong's Gateway Discovery feature and isolate the Gateway Pods to Amazon EC2 A1 instances which have ARM processors. Since the Gateway Pods use Nginx under the hood I would assume that we could see similar performance improvements as noted in this [blog post](https://aws.amazon.com/blogs/compute/optimizing-nginx-load-balancing-on-amazon-ec2-a1-instances/) if we did the same type of tuning.

CC: @shaneutt

**Comment by pmalek** [comment]
Hi @kevarr-vg

We might have not explicitly linked it here but arm64 images are available for a while now. You can for example see it here in 2.10 image https://hub.docker.com/layers/kong/kubernetes-ingress-controller/2.10/images/sha256-8712a241d1ceb03bd1e0049f8fe21bc649569d74821362f764776b5b3a9c22f3?context=explore
