### ISSUE TITLE
Upstream deletion returning a 500

### ISSUE THREAD

**Issue by irons** [Kong/kubernetes-ingress-controller#1024]
### Summary

Kong API commands to list upstreams and upstream targets return expected data, but attempting to delete an upstream consistently returns 500.

**Kong Ingress controller version**

1.0

**Kong or Kong Enterprise version**

2.2

### Kubernetes version

1.18.8

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"c86ad89b8715ed17fd55b87cbb2888ccc6fa9878", GitTreeState:"clean", BuildDate:"2020-09-25T01:53:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

AKS 1.18.8. OS is ubuntu, but I don't have the necessary cluster access to run `uname -a` at the node level. Kong is db-less, installed via the helm chart.

### What happened

I've been trying to troubleshoot a ring-balancer error ([forum link](https://discuss.konghq.com/t/troubleshooting-a-ring-balancer-failure/7802/4), [slack link](https://kubernetes.slack.com/archives/CDCA87FRD/p1611852431014200)). Because this kong ingress controller is working with other helm releases, and the misbehaving helm release is working with kong ICs in another tier, that's been difficult. 

Deleting the service's helm release doesn't remove the Kong upstream responsible for this load balancer, so I'd like to delete and recreate the upstream, as well as a few other upstreams for defunct test services. 

With port-forwarding open to the admin server API, this lists all seven known upstreams:
```curl -k "https://localhost:18444/upstreams"```

And this fetches details about the target pods belonging to one upstream:
```curl -k "https://localhost:18444/upstreams/echo.namespace.80.svc/targets"```

Per [the docs](docs.konghq.com/2.0.x/admin-api/#delete-upstream), this should delete the upstream associated with this ring-balancer:
```
$ curl -k -X "DELETE" "https://localhost:18444/upstreams/echo.namespace.80.svc"
{"message":"An unexpected error occurred"}
```

That’s a 500, and I get the same if I pass this upstream’s UUID, or a different upstream’s name or ID.

### Expected behavior

I should receive a 204, and the upstream should be deleted.

### Steps To Reproduce

1. `curl -k -X "DELETE" "https://localhost:18444/upstreams/echo.namespace.80.svc"`

**Comment by rainest** [comment]
Apologies for the redirection again, but this should also go upstream to the Kong repo rather than to the controller repo: https://github.com/Kong/kong/issues

The 500 possibly indicates something more interesting than the unexpected 503, or at least may provide some data that's easier to trace down a possible root cause. Any of those that return the "unexpected error" admin API response should correspond to a traceback in your error logs, so check for those.
