### ISSUE TITLE
Ingress controller does not alter the Service object properties from custom Ingress configuration

### ISSUE THREAD

**Issue by xwrs** [Kong/kubernetes-ingress-controller#103]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.13

### Kubernetes version

1.11.1

### Environment

- Azure AKS

### What happened
Ingress controller does not alter the Service object properties from custom Ingress configuration

### Expected behvaior
Once I change for instance read_timeout in KongIngress custom resource, all ingresses which are referencing it through configuration.konghq.com annotation should all get their Service records updated with appropriate value of read_timeout

### Steps To Reproduce

1. Deploy Ingress object referencing KongIngress through configuration.konghq.com annotation
2. Deploy or change KongIngress object setting proxy section attributes
3. Check corresponding Service object attributes in Admin API. Attribute values are default

**Comment by hbagdi** [comment]
Hi @xwrs 
Thank you for opening this issue.
Could you post `Ingress` and `KongIngress` specs to reproduce?
This will help us addressing this issue faster.

**Comment by xwrs** [comment]
@hbagdi 

`apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-ingress-config
proxy:
  connect_timeout: 120000
  read_timeout: 120000
  retries: 3
  write_timeout: 120000`

`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    configuration.konghq.com: kong-ingress-config
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: identity
spec:
  rules:
  - host: xxx
    http:
      paths:
      - backend:
          serviceName: identity
          servicePort: 80
        path: /identity`

**Comment by hbagdi** [comment]
I can't reproduce this locally on k8s v1.10.0.
Do you see any errors on the ingress controller?

Also, the following annotation will not have any effect in Kong. It is something specific to Nginx ingress.
```
nginx.ingress.kubernetes.io/rewrite-target: /
```

**Comment by jaygorrell** [comment]
The issue lists `0.13` as the ingress version but that's the kong version. Is this not similar to https://github.com/Kong/kubernetes-ingress-controller/issues/91, which was fixed in 0.1.0?

**Comment by hbagdi** [comment]
@jaygorrell Indeed. That could be the case.
@xwrs Could you share the version of the ingress controller?
You can get that from the deployment spec of your ingress controller.

**Comment by xwrs** [comment]
Ingress Controller is of version 0.0.4. Tried on Kubernetes 1.10.1 and issue is the same.

**Comment by hbagdi** [comment]
@xwrs Please try with Ingress controller 0.1.0.

**Comment by xwrs** [comment]
@jaygorrell @hbagdi 0.1.0 works perfectly. thanks
