### ISSUE TITLE
Support MTLS auth credentials

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1038]
MTLS auth credentials did not originally support tags, so the controller could not manage them. As of [2.3.2.0](https://docs.konghq.com/enterprise/changelog/#2320), they do:

> Mutual TLS Authentication(mtls-auth) plugin has added support for tags in the DAO and now ensures the existence of any provided CAs when creating the plugin entry.

We should add a credential type for them in KIC for parity with our other standard auth plugin credentials. We already have support for them in [go-kong](https://github.com/Kong/go-kong/commit/be289a064d7ff9ed62d0b6a65e8e81f011767830).

[Custom entities](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/guides/configuring-custom-entities/) can support MTLS auth credentials in the interim.

**Comment by shaneutt** [comment]
Just for reference there would seem to be some relation here to #702

**Comment by rainest** [comment]
It's independent of that. We need to add another case to https://github.com/Kong/kubernetes-ingress-controller/blob/1033deeabc5f6a49aad5b1a740570f6610c337b2/pkg/kongstate/consumer.go#L27-L109 and several other places that have logic for the different credential types (grepping across the codebase for `key-auth` will find all of them). We'd still perform credential translation and validation with the single controller.

**Comment by mflendrich** [comment]
Incompatible with Kong <2.3.

**Comment by mflendrich** [comment]
Blocked by #1041

**Comment by rainest** [comment]
We are aware of the Kong version, and should be able to gate handling these credentials on that as an alternative to making a hard compatibility break. Will explore that first.

**Comment by mflendrich** [comment]
@rainest what can we do to get this support done?

**Comment by rainest** [comment]
Version gating is a bit annoying as we have that information, but don't yet make it available where we'd need it. It's stored in the controller config, but not passed down anywhere else I know of. There are two places we can exclude these:

- We will add a new [SetCredential case](https://github.com/Kong/kubernetes-ingress-controller/blob/be5f8fd5f8809baf8314d651224da6f0c0e5efdb/pkg/kongstate/consumer.go#L97-L102), and return an error if the version is insufficient. `kongstate.FillConsumersAndCredentials()` [skips over any credentials it cannot set](https://github.com/Kong/kubernetes-ingress-controller/blob/next/pkg/kongstate/kongstate.go#L101-L105) and logs why, along with the Secret containing the failed credential. This probably means adding `Version` to `KongState`, setting it after the [parser builds state](https://github.com/Kong/kubernetes-ingress-controller/blob/next/internal/ingress/controller/controller.go#L103), and passing a  new argument to `SetCredential()`
- We will add a [ToDeckContent credential populator](https://github.com/Kong/kubernetes-ingress-controller/blob/next/pkg/deckgen/generate.go#L140-L142), but skip over mTLS auths entirely and log an error if any exist. We can pass version information in an argument to `ToDeckContent()` [from `controller.OnUpdate()`](https://github.com/Kong/kubernetes-ingress-controller/blob/be5f8fd5f8809baf8314d651224da6f0c0e5efdb/internal/ingress/controller/kong.go#L47)
- Option 3 is that we ignore the gating entirely. You don't have to create mTLS auth credentials, so simply adding support for them doesn't break anything unless you try to. The onus is on the user to read docs and be aware of this limitation.

First option is a longer path, but seems more correct. Skipping over content that we added to the state (option 2) seems wrong.
