### ISSUE TITLE
Updates kong services on each synchronization check when not necessary

### ISSUE THREAD

**Issue by jaygorrell** [Kong/kubernetes-ingress-controller#104]
### Summary

The ingress controller is issuing a `PATCH` to Kong for each service in the environment on each synchronization check. This doesn't necessarily sound bad, but when you have 200+ services and they all issue a `PATCH` at the same time, you get contention on the database that can manifest as errors in the kong-proxy logs and 5XX errors for consumers.

**Kong Ingress controller version**
0.1.0

### Kubernetes version

1.9.3

### What happened
Users experience service outages using kong-ingress with a large number of services due to unnecessary database writes every 10 minutes.

### Expected behvaior
Services in k8s with no changes needed in Kong should detect that no change is necessary and avoid sending a `PATCH`, similar to how plugins function.

**Comment by hbagdi** [comment]
Hi @jaygorrell,

Thank you for opening this issue.
This problem arises in combination due to Kong rebuilding router, https://github.com/Kong/kong/pull/3423, and Ingress Controller sending PATCH requests even when not necessary.

We will be addressing this issue soon.
