### ISSUE TITLE
KIC 2.0 - 2.x integration tests also set up to test 1.x

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1040]
The [Kong Kubernetes Testing Framework (KTF)][ktf] was created to provide integration testing for Kong Kubernetes components using [Go][go] tests.

The purpose of this issue is to migrate our existing bash tests to the KTF in `main` in preparation for our eventual transition onto the new architecture demonstrated with `railgun/`.

These tests should pass on both `v1.x` AND `v2.0` prior to `v2.0` release to help demonstrate protection against regressions.

[ktf]:https://github.com/kong/kubernetes-testing-framework
[go]:https://go.dev

**Comment by mflendrich** [comment]
Pending team review.

**Comment by shaneutt** [comment]
blocked on https://github.com/Kong/keps/issues/13

**Comment by shaneutt** [comment]
now blocked on the following:

- https://github.com/Kong/kubernetes-testing-framework/pull/3
- https://github.com/Kong/kubernetes-ingress-controller/pull/1102

**Comment by shaneutt** [comment]
I'm not sure this is going to resemble a "port" of the code when I implement it: I'm intending to make the testing framework run-able with either controller manager (`v1.x` or `v2.x`) and then have CI run them BOTH on any PR, the intention is from now until 2.0 all tests will test both controllers, so that until we release we have higher assurance that they're (ultimately) functioning the same way.
