### ISSUE TITLE
Bump Kong to 2.3 in deploy manifests

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1041]

**Comment by mflendrich** [comment]
Blocked: pending verification that Kong `2.3` has the loosened version check that allows 2.2 DPs with a 2.3 CP.

**Comment by rainest** [comment]
We'll also need to consider how to handle Enterprise free (unlicensed) mode in the generated manifests (see DOCS-1605 for some additional discussion). We may want to remove the pre-set `KONG_LICENSE_DATA` environment variable and provide instructions for licensed users to add their license after creating the Deployment.

**Comment by mflendrich** [comment]
Blocked by Kong/team-k8s#34

**Comment by shaneutt** [comment]
Do we need this with https://github.com/Kong/team-k8s/issues/41 inbound? can we simply skip forward to 2.4?

**Comment by mflendrich** [comment]
An intermediate upgrade to 2.3 won't hurt even if 2.4 comes in a few days.
