### ISSUE TITLE
Spike: Identify what's needed for Railgun to reach KIC feature parity

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1043]
Spike for KIC 2.0 GA bringing railgun to feature parity with the existing 1.x releases of KIC.

To resolve this issue we should spin off several new issues which represent the work that needs to be done to reach parity and associate them with the KIC 2.0 milestone.

[KEP5](https://github.com/Kong/keps/pull/15) provides much of the contextual starting points for this spike.

**Comment by shaneutt** [comment]
Followup: our generators for examples, crds, e.t.c. are not 100% yet and we need to include this in our considerations.

**Comment by shaneutt** [comment]
@Kong/team-k8s I have added several issues to the [KIC 2.0 Milestone](https://github.com/Kong/kubernetes-ingress-controller/milestone/12) as a result of this spike. These are prioritized and ordered in the order it's expected they should be approached.
Please review and add any new issues or updates you feel are needed to complete the scope of this project.
