### ISSUE TITLE
KIC 2.0 - Integration/E2E Testing Happy Path

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1044]
The purpose of this task is to provide a "happy path" for KIC testing using the [Kong Kubernetes Testing Framework (KTF)](https://github.com/kong/kubernetes-testing-framework) in order to provide a simple and automated testing environment for production Golang integration tests for KIC components.

**Comment by shaneutt** [comment]
Working through some bugs and issues which are slowing this down more than originally anticipated, but intending to have a demo up for this within the next couple of days once that's sorted out.

**Comment by shaneutt** [comment]
This is blocked on https://github.com/Kong/kubernetes-ingress-controller/issues/1100
