### ISSUE TITLE
Benchmarking number of ingress objects

### ISSUE THREAD

**Issue by vivekanandg** [Kong/kubernetes-ingress-controller#1049]
### Max number of ingress objects

Is there a rough estimate on number of "Ingress" objects an instance of KIC supports? (on a 4 core, 16G pod)
Also can we scale it horizontally?

**Comment by shaneutt** [comment]
Additional context: @vivekanandg and I talked about this in Slack, it seems as though we either need to improve our documentation for core & KIC scaling characteristics and stats, and/or make them more visible to end-users looking to plan deployments. cc @hbagdi

**Comment by mflendrich** [comment]
@eskibars says that we might try to implement a benchmark, publish the benchmark code, and put it on CI. The benchmark would plot a graph of appropriate relationships

@mflendrich says an example relationship is between config size and load (e.g. memory).

**Comment by shaneutt** [comment]
Closing this as stale, and also partially a duplicate of https://github.com/Kong/kubernetes-ingress-controller/issues/1197 which we ultimately decided not to implement at this time. If there's still a strong need from end-users for this functionality please comment here and let us know your use cases and needs and we'll be happy to re-open and re-assess.
