### ISSUE TITLE
Implement regression tests for the entire constellation of supported configs 

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1053]
Including various images, various k8s versions, etc.

**Comment by mflendrich** [comment]
TBD: the set of configurations that we test.

I'm thinking:
Kong version X <-> KIC at HEAD <-> Kubernetex version Y
Kong Enterprise version X <-> KIC at HEAD <-> Kubernetex version Y

where "Y" should cover all minor versions we announce as "supported" in the [version compat matrix](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/references/version-compatibility/#kubernetes)

**Comment by mflendrich** [comment]
TBD: the set of configurations that we test.

I'm thinking:
Kong version X <-> KIC at HEAD <-> Kubernetex version Y
Kong Enterprise version X <-> KIC at HEAD <-> Kubernetex version Y

where "Y" would (ideally) cover all minor versions we announce as "supported" in the [version compat matrix](https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/references/version-compatibility/#kubernetes)

@eskibars anything to add here?

**Comment by eskibars** [comment]
A few things:
1) We should be testing the latest patch version on X and Y and expect to re-test any time the patch version changes
2) We need to get to testing X and Y before they're released, not after, so that we can alert those teams if they've broken KIC prior to releasing and make adjustments upstream.  We can phase that in though over time
3) It seems to me that we should have at least some rudimentary testing across different K8s distributions so we can

**Comment by shaneutt** [comment]
blocked by https://github.com/Kong/kubernetes-ingress-controller/pull/1163

**Comment by shaneutt** [comment]
I'm going to close this issue and open several issues for very specific APIs and testing domains in its place, see the relevant milestone: https://github.com/Kong/kubernetes-ingress-controller/milestone/16

**Comment by mflendrich** [comment]
Following team discussion, this requirement (to test the supported versions of components KIC integrates with) still holds. Therefore reopening this issue as a part of the aforementioned milestone.

**Comment by mflendrich** [comment]
@shaneutt can we consider this done with our current integration tests?

**Comment by shaneutt** [comment]
Yes, this has been covered by all the other efforts to add tests to our testing suite, and test matrices to our release CI.
