### ISSUE TITLE
Kong is unable to detect ingress resource

### ISSUE THREAD

**Issue by vishpat** [Kong/kubernetes-ingress-controller#108]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

The Kong ingress controller does not detect the *ingress* resource for a service.

**Kong Ingress controller version**
 0.14.0 

### Kubernetes version

Kubernetes v1.9.5

### Environment

- **Cloud provider or hardware configuration**: Local setup using kubespray
- **OS** (e.g. from /etc/os-release): CentOS Linux 7
- **Kernel** (e.g. `uname -a`): Linux node1 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**:  helm install --name kongssl stable/kong
- **Others**:

### What happened

I have a grafana service running in my k8s cluster and am able to access it without any issues using NodePort. 

I installed kong using helm as follows
<pre>
helm install --name kongssl stable/kong
</pre>

And added the following ingress
<pre>
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - foo.bar
    secretName: foo-cert 
  rules:
  - host: foo.bar 
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000 
</pre>

The ingress gets added without issues however Kong does not pick up the ingress and add it to the list of it's services

<pre>
curl -k https://ADMIN_IP:ADMIN_PORT/apis
{"total":0,"data":[]}

curl -k https://ADMIN_IP:ADMIN_PORT/services
{"next":null,"data":[]}
</pre>

### Expected behvaior
Kong should have picked up the new ingress and added the services for proxying the traffic to it

### Steps To Reproduce

Same as what happened

**Comment by hbagdi** [comment]
Hello @vishpat,

`stable/kong` Helm chart deploys Kong as an application on k8s and not as an Ingress controller, so it won't pick up ingress resources.

Please follow our [getting started
](https://github.com/Kong/kubernetes-ingress-controller/tree/master/deploy) guide to understand how to setup Kong as an Ingress controller.

There is an kong-ingress chart in works and will be released soon!

**Comment by vishpat** [comment]
Many thanks @hbagdi
