### ISSUE TITLE
Configmap `kong-ingress-controller-leader` has not been deleted after uninstall Kong

### ISSUE THREAD

**Issue by liyanwei93** [Kong/kubernetes-ingress-controller#1083]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

After I uninstall Kong, I noticed the configmap `kong-ingress-controller-leader` has not been deleted, Is this due to a design, or just a bug ？ 

**Kong Ingress controller version**

0.8.1

**Kong or Kong Enterprise version**

2.0.4

### Kubernetes version

**paste `kubectl version` output**
```
[root@mcmsf3-inf ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"02c110006bfef4ba53fa5042bb9eae170dd3dc1c", GitTreeState:"clean", BuildDate:"2020-12-16T08:02:27Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```
### Environment

- **Cloud provider or hardware configuration**: IBM Cloud
- **OS** (e.g. from /etc/os-release): Red Hat Enterprise Linux 8
- **Kernel** (e.g. `uname -a`): GNU/Linux
- **Install tools**: kong operator
- **Others**:

### What happened

After I uninstall Kong, I noticed the configmap `kong-ingress-controller-leader` has not been deleted.

### Expected behavior

After uninstall Kong, I can get a clean env.

### Steps To Reproduce

1. Install Kong
2. Unstall Kong
3.
4.

**Comment by mflendrich** [comment]
Hi @liyanwei93,

Thanks for flagging this problem.
This leader election mechanism is going away with KIC 1.x. Closing this issue because it will no longer be a part of KIC as of 2.0.
