### ISSUE TITLE
KIC doesn't fail properly when a Service referred to by an Ingress is not available in the storer cache when running the Kong configuration parser

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1087]
While testing in `next` I found that missing `K8sServices` in the storer cache can result in broken `kong.Services` which will be deployed in a broken state to the Kong Admin API.

The purpose of this issue is to cause a hard failure instead of a logged error but continuing with the POST update in these cases.

**Comment by mflendrich** [comment]
Today, if this happens, KIC will try to push corrupted state into Kong.
Possible implementations:
- if KIC detects a missing service in its Storer cache, fail loudly and prevent a faulty sync from happening
- if KIC detects a missing service in its Storer cache, try to repair corrupted internal state by pulling the missing service from the k8s api

**Comment by shaneutt** [comment]
Due to the theoretical nature of this issue we don't have priority for it at the moment so we'll close it for the time being. If anyone starts running into this issue please feel free to comment here and we'll be happy to re-open it and re-assess.
