### ISSUE TITLE
Provide a means to test code that requires a Kong client

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1088]
Originally from https://github.com/Kong/kubernetes-ingress-controller/pull/1034#discussion_r585127600

We use a Kong API client in several locations in the controller code, namely:

- When [sending a config to the DB-less configuration endpoint](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/internal/ingress/controller/kong.go#L212-L229).
- Indirectly, when [using decK functions to apply configuration changes in DB-backed mode](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/internal/ingress/controller/kong.go#L245-L278).
- In some types of admission validation checks, e.g. to check [whether a proposed consumer would collide with an existing consumer](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/internal/admission/validator.go#L38) and [confirming that a plugin configuration conforms to its schema](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.1.1/internal/admission/validator.go#L73-L81).

This code lacks unit test coverage because an actual Kong client requires a Kong instance to function. All its requests fail otherwise. A mock client that can provide an approximation of Kong client behavior without actually communicating with a Kong instance would allow us to add coverage for this code.

We've identified some possible obstacles to this from initial discussion:

- We use a mixture of raw endpoints (e.g. `Client.NewRequest("POST", "/schemas/plugins/validate")`) and dedicated functions (e.g. `Client.Consumers.Get(ctx, &consumer.Username)` for `GET /consumers/<USERNAME>`).
- The response we expect varies depending on what's calling it: for avoiding consumer conflicts in validation, we want `GET /consumers/<USERNAME>` to return a 404, whereas in the context of the decK solver we expect either a 404 or 200, but take different actions depending on the response status (we create a new consumer or diff against an existing consumer, respectively).

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-ingress-controller/pull/1166 handles this in the admission controller.

**Comment by shaneutt** [comment]
Closing as it appears to be resolved. Please re-open if there's still more we need to accomplish here.
