### ISSUE TITLE
<Feature Request> Provide a means to add global plugin configurations

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#109]
### Summary
Provide a means to configure plugins globally.
Not implemented as of **Kong Ingress controller version 0.1.0**, the current latest version.
Not specific to K8S version or platform. 

### Background
Kong can [add plugins globally](https://docs.konghq.com/0.14.x/admin-api/#add-plugin) that then apply to any request that [does not match a more specific plugin configuration](https://docs.konghq.com/0.14.x/admin-api/#precedence).

At present, the `KongPlugin` object does not provide any means to configure global plugins, and it is not possible to configure them via `Ingress` metadata, as all `Ingress` objects must apply to specific routes.

### Implementation considerations
- `KongPlugin` will need an annotation to specify that the plugin should be applied globally, similar to `consumerRef` for applying on a per-consumer basis. `global: true` or similar would work.
- Conflicting or ambiguous configuration (e.g. setting both `global: true` and `consumerRef: yoda` on the same `KongPlugin`) must be handled in some way. The IC could either reject this configuration and return an error when attempting to create the object, or it could attempt to infer the user's intent (creating both a global and consumer-specific plugin configuration with the same settings).

**Comment by hbagdi** [comment]
Hello @rainest,

#112 just got merged into master. This will be available in our next release. Documentation will be updated before the release process. Thanks!
