### ISSUE TITLE
Test & Document Kubernetes Version and API Support

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1095]
# Problem Statement

We need an authoritative source of truth as to which k8s versions are "supported" by which version of KIC.

# Proposed solution

 We call a version supported if:
- tests defined in #1542 for that version pass
- there are no known API incompatibilities between the respective: KIC version and the k8s version

The version compatibility matrix lives [here](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/#kubernetes).

# Acceptance Criteria
- [x] e2e testing added to verify versions 1.17-1.21 on production quality cluster deployment (GKE)
- [x] starting with KIC 2.0, each version marked as "supported" is covered by automated integration tests (#1542)
- [x] Releases are blocked (by manual process or by CI/automation) if the criteria above are not met.
    - Possible solutions: add an entry to the release checklist, or add CI/automation that blocks a release if the criteria are not met.
- [x] optional: expose the compatibility test results in a visible place to end-users
    - Possible solution: link from changelog/release notes to the CI results page

# Issues

- https://github.com/Kong/kubernetes-testing-framework/issues/32
- https://github.com/Kong/kubernetes-testing-framework/issues/66
- https://github.com/Kong/kubernetes-testing-framework/issues/68
- https://github.com/Kong/kubernetes-ingress-controller/issues/1617
- https://github.com/Kong/kubernetes-ingress-controller/issues/1617
- https://github.com/Kong/kubernetes-ingress-controller/issues/1614

# Pull Requests

- https://github.com/Kong/kubernetes-testing-framework/pull/59
- https://github.com/Kong/kubernetes-testing-framework/pull/64
- https://github.com/Kong/kubernetes-testing-framework/pull/67
- https://github.com/Kong/kubernetes-ingress-controller/pull/1610
- https://github.com/Kong/kubernetes-ingress-controller/pull/1618

# NOTES

Original spike: https://github.com/Kong/kubernetes-ingress-controller/issues/1043

**Comment by mflendrich** [comment]
Instead of targetting 2.0 specifically, maybe we could do it once and for all by:
- introducing automated testing for the k8s versions promised to be supported #1053 
- updating our release procedure to always update docs
?

I don't see why we'd need to treat the 2.0 release in any special manner.

**Comment by shaneutt** [comment]
> Instead of targetting 2.0 specifically, maybe we could do it once and for all by:
> 
>     * introducing automated testing for the k8s versions promised to be supported #1053
> 
>     * updating our release procedure to always update docs
>       ?
> 
> 
> I don't see why we'd need to treat the 2.0 release in any special manner.

Ok I'm persuaded we don't need to do this specifically in 2.0 scope (though I would like to for documentation's sake). I've moved this out fo the milestone and reworded it for later grooming, and we can add it as a stretch goal for 2.0 later if we like.

**Comment by shaneutt** [comment]
actually for now I'll just close this and bookmark it for myself and perhaps we can come back to it at a later time if we feel so inclined.

**Comment by shaneutt** [comment]
Re-open context: we're going to check requirements with @eskibars and then groom this for a later scope.

**Comment by mflendrich** [comment]
@mflendrich to deduplicate version support issues we have (they exist in several places)

**Comment by shaneutt** [comment]
While it doesn't _resolve_ this, the following commit does add the version options we need for this in the KTF: https://github.com/Kong/kubernetes-testing-framework/pull/40/commits/b45df3e00df576a4afa5a1d85310fc33dc42872c

**Comment by shaneutt** [comment]
With the above changes to KTF we can _prove_ version compatibility using our integration testing suite, I would like to see this be the way in which we move forward, and document results. Additionally I think we should make some hard calls to NOT support Kubernetes older than v1.16

**Comment by shaneutt** [comment]
The `v2.0.0-alpha.3` release and the successful workflow thereof is the validation of the CI portions of this PR:

- https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v2.0.0-alpha.3
- https://hub.docker.com/layers/kong/kubernetes-ingress-controller/2.0.0-alpha.3/images/sha256-94e68bc67ae1003011f7b016b2c511c98c849dfb4241d487afac578ad35acac0?context=explore
- https://github.com/Kong/kubernetes-ingress-controller/actions/runs/1092174311

Now https://github.com/Kong/docs.konghq.com/pull/3081 has been made to be the last PR needed to finally resolve this issue by adding the relevant documentation.

I'm considering the optional part of the AC resolved by virtue of our CI workflows being publicly available for releases.

**Comment by shaneutt** [comment]
As per a recent @Kong/team-k8s discussion the remaining work (which is all documentation) does not need to block the beta release here. I'm separating the remaining documentation work into its own issue.
