### ISSUE TITLE
Automated `examples/` tests on CI

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1096]
The purpose of this task is to make sure examples are correct, e.t.c.

Acceptance Criteria
- [ ] automated tests exist and validate that our `example/` configurations actually work, and protect against regressions to these later
- [ ] the tests mentioned above run on CI

**Comment by mflendrich** [comment]
This sounds great.

Maybe these acceptance criteria could be borrowed by #1053 ? In that case, we could fix both issues at once in preparation for 2.0.

**Comment by shaneutt** [comment]
> This sounds great.
> 
> Maybe these acceptance criteria could be borrowed by #1053 ? In that case, we could fix both issues at once in preparation for 2.0.

I'm open to that, please feel free to make edits as you see fit.

**Comment by shaneutt** [comment]
The RBAC components to this have been moved into their own scope and are now part of their own scope via #1785.

**Comment by mflendrich** [comment]
Is there anything here that #756 doesn't cover, other than `samples/example` which I don't see clear value for?

**Comment by shaneutt** [comment]
> Is there anything here that #756 doesn't cover

Needs investigation to be sure.

> other than `samples/example` which I don't see clear value for?

I personally use the examples from time to time and would like to keep them.
