### ISSUE TITLE
KIC 2.0 - Controller Manager CLI - Options Parity

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1097]
[Spike](https://github.com/Kong/kubernetes-ingress-controller/issues/1043)

For KIC 2.0 we are expecting to keep backwards compatibility in our APIs.

However we expect when it comes to our controller manager / CLI we wont be able to keep 100% feature and flag backwards compatibility.

The purpose of this task is to try to ensure CLI backwards compatibility with `v1.x` releases, and document places where we're not able.

Acceptance Criteria
- [x] import historical controller CLI flags from `v1.x` into `v2.0 and aim for feature parity
- [x] remove the comment https://github.com/Kong/kubernetes-ingress-controller/blob/cd6eac2687078fd9e0f4c6b13385fefbdfb798ac/railgun/manager/manager.go#L32
- [x] ~provide user documentation on any flag differences between the versions~ superseded by https://github.com/Kong/kubernetes-ingress-controller/issues/1348
- [x] write 2.0 release notes pointing to documentation on flag differences and any backwards incompatibilities
- [x] ~check that the [Helm Chart](https://github.com/kong/charts) works verbatim with KIC 2.0 (if it doesn't, document incompatibilities and put them in the beta milestone)~ handled by https://github.com/Kong/kubernetes-ingress-controller/issues/1352

Additional Requirements:

- [x] in the prototype we [made an internal variable for the Kong ingress class](https://github.com/Kong/kubernetes-ingress-controller/pull/1102/files#r596622683), before we release 2.0 we need to switch this back to using a CLI flag as is done in `v1.x.`
- [x] in the prototype we started [using an ENV var to manage the secret controller's default secret namespace](https://github.com/Kong/kubernetes-ingress-controller/pull/1102#discussion_r596615605), we need to ensure this is converted to a CLI flag as it is in `v1.x` releases of KIC.

**Comment by mflendrich** [comment]
All the remaining concerns have been split into issues of their own.
