### ISSUE TITLE
Spike: Resolve Railgun TODOs and FIXMEs

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1114]
This is just a reminder that we need to grep for and resolve all `TODO` and `FIXME` items in `railgun/` prior to RC1 of KIC 2.0.

**Comment by mflendrich** [comment]
Marked as "spike" - let's try doing that, and create issues for issues less important or more complex than anticipated.

**Comment by shaneutt** [comment]
I'm going to clean out the easy ones, and then the more complex ones will get their own issues (if they don't already have them)
