### ISSUE TITLE
KIC 2.0 - Technical Blog Post

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1124]
The purpose of this issue is to have @Kong/team-k8s produce a blog post that will land when KIC 2.0 has it's initial preview release.

This blog post should be predominantly technical and cover the following topics:

- [x] history of the Kong Kubernetes Ingress Controller (KIC)
- [x] overview of the Kubebuilder SDK
- [x] deep dive in the re-architecture of KIC using Kubebuilder
- [ ] examples of how to contribute new APIs and other functionality to the KIC post 2.0

Additionally:
- [ ] make sure to reference the blog post in the release notes
- [ ] make sure to share the blog post in `#kong` on Kubernetes Slack

**Comment by mflendrich** [comment]
The blog post is out: https://konghq.com/blog/kong-ingress-controller-2-beta/
