### ISSUE TITLE
KIC 2.0 - Integration Testing - Cleanup Our Controller Runner

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1128]
A [hack](https://github.com/Kong/kubernetes-ingress-controller/blob/next/railgun/test/integration/suite_test.go#L57) was introduced in our KIC 2.0 Integration Tests to run the controller-manager as an `exec.Command`, where in the future we should be able to run this as a library in goroutines and shut it down cleanly in the `suite_test.go`.

Acceptance Criteria:
- [ ] run our controller manager via goroutine
- [ ] enable test coverage for the controller manager in the integration tests

**Comment by mflendrich** [comment]
https://github.com/Kong/kubernetes-ingress-controller/pull/1175 attempts at making the controller manager runnable as a function

**Comment by shaneutt** [comment]
#1175 took care of this :vulcan_salute:
