### ISSUE TITLE
KIC 2.0 - CRD Migration

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1133]
We need to ensure that `v1.x` upgrades cleanly to `v2.0`, particularly when using a `helm upgrade`.

Acceptance Criteria:
- [x] all CRDs from `v1.x` releases can upgrade to the new kubebuilder generated CRDs
- [x] ~OR we drop the kubebuilder generated CRDs for now to save time, use the originals, and create a follow up issue.~
- [ ] Helm Chart can deploy v1 CRDs

**Comment by mflendrich** [comment]
Possibility: define a new API version with appropriate conversions.

**Comment by rainest** [comment]
K8S does provide a standard mechanism for indicating how it should conversions between one version and another in https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion. That requires a new API version and that we write some helper service to handle the actual translation.

**Comment by shaneutt** [comment]
> K8S does provide a standard mechanism for indicating how it should conversions between one version and another in https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion. That requires a new API version and that we write some helper service to handle the actual translation.

This makes sense to me, I don't have any qualms with this approach when we spike this.

**Comment by mflendrich** [comment]
I would like to bring up the following for discussion:
- The change between the "legacy CRDs" and the "Railgun CRDs" is purely technical and not semantic. We're just moving from one way of generating CRDs from schema definitions to another.
- We want the change above to be transparent and non-breaking.

That said, I believe that the upgrade to railgun does not deserve a new APIVersion of our manfiests (so we should IMO withdraw from the idea I pitched above about a new API version), and we should strive for:
- making the new CRDs a viable in-place replacement for the old CRDs.
- KIC 2.0 being drop-in compatible with KIC 1.x manifests

**Comment by shaneutt** [comment]
> That said, I believe that the upgrade to railgun does not deserve a new APIVersion of our manfiests (so we should IMO withdraw from the idea I pitched above about a new API version), and we should strive for:
>     * making the new CRDs a viable in-place replacement for the old CRDs.
>     * KIC 2.0 being drop-in compatible with KIC 1.x manifests

This all sounds good to me, I have no comments just :+1:

**Comment by ccfishk** [comment]
A couple of alternative options:
- come up with not-supported-resources.yaml (including CRDs, etc), user execute "helm uninstall ..." or  "kubectl delete -f not-supported-resources.yaml" before install latest KIC version.
- implement CRD upgrade as part of controller - V1 is expected, v1beta1/v1alpha1 is expired, delete associated resource before upgrading to latest version

Let me know if we have offline discussion about the feasibilities.
