### ISSUE TITLE
Bintray discontinues its service

### ISSUE THREAD

**Issue by MrKrabat** [Kong/kubernetes-ingress-controller#1136]
Hello,
you may have already heard, but Bintray is discontinuing its service:
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

As of May 1, you will no longer be able to update your `kong-ingress-controller` image.
Are there any plans to migrate to another registry yet?

**Comment by rainest** [comment]
We're aware, yes. Work is underway to migrate our artifacts elsewhere.

**Comment by zarelit** [comment]
If you're here because of this and you're using version 1.2 you should be able to just redeploy by changing the image from:
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:1.2
to
kong/kubernetes-ingress-controller:1.2
which is the official place now
