### ISSUE TITLE
KIC 2.0 - Reconcilation Timing Loop Issue

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1142]
While working on https://github.com/Kong/kubernetes-ingress-controller/pull/1137 I observed some timing issues that could occur wherein configuration posted by the secret controller to the admin API could be lost if the proxy deployment was updating Kong (in this case, to add a UDP port to serve DNS).

We should look into making the secret controller aware of the state of the proxy deployment and pods so that configurations can be re-applied if changes are made to the proxy.

**Comment by mflendrich** [comment]
Maybe the solution could be running the secret controller as a sidecar to the proxy, with the general direction of moving logic away from the secret controller - so that, eventually, the secret controller remains a simple configuration applier?
