### ISSUE TITLE
Add categories to CRDs

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#1147]
Add categories to CRDs to improve kubectl experience
See https://github.com/kubernetes-sigs/gateway-api/issues/589

## Acceptance criteria

- [ ] All CRDs installed by the helm chart & deploy manifests include a common category (e.g. `kong-ingress-controller`). TBD what category name makes sense and would be consistent with other ingress controllers.
- [ ] If autogeneration is used for CRDs, the generation source is updated appropriately
- [ ] Helm chart & deploy manifests updated to include the CRD changes

**Comment by pmalek** [comment]
Looking at other ingress controllers:

- [istio's manifests](https://githubc.om/istio/istio/tree/master/manifests/charts) - couldn't find categories being used
- [gloo](https://github.com/solo-io/gloo/tree/master/install/helm/gloo/crds) - couldn't find categories being used
- [haproxy](https://github.com/haproxytech/kubernetes-ingress/tree/master/crs) - couldn't find categories being used

The conclusion is then that we won't be trying to adhere to a convention as there is none yet.
