### ISSUE TITLE
KIC 2.0 - TCPIngress & UDPIngress status

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1153]
The purpose of this task is to follow up on some pre `v2.x` technical debt regarding the statuses of `TCPIngress` (and also extend the improvements to the similar `UDPIngress`, which at the time of writing is only `v1alpha1`. If the `UDPIngress` portion of this work needs to be moved out into another scope, that's fine).

The status of a `TCPIngress` object or `UDPIngress` object should reflect whether the proxy has been configured, but also if the proxy is actually able to serve the route. The reason for singling out `TCPIngress` and `UDPIngress` for this is because these APIs require some special behavior where the proxy pods themselves have to be reconfigured to support these ingress rules as they are added.

**Comment by mflendrich** [comment]
@shaneutt to propose the degree to which this issue needs to be covered in KIC 2.0, and what can be done in 2.1 and beyond.

**Comment by shaneutt** [comment]
This can be pulled out into a later scope, it doesn't need to be part of the KIC 2.0 release as it will be additive/backwards compatible.

**Comment by shaneutt** [comment]
Status updates for these resources are not available for v2.
