### ISSUE TITLE
railgun: take all configuration input via struct Config

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1182]
Context: https://github.com/Kong/kubernetes-ingress-controller/pull/1175/files#r613233978

Ensure that Railgun's controllers no longer read configuration from anywhere else (like environment variables) but `struct Config`, and remove the `BUG: ` comment on `type Config`.

**Comment by rainest** [comment]
Do we recall what we were pulling direct from the environment specifically? Not sure on the original (anchor in the link appears broken, doesn't go to a specific part of the diffAs of current next, doesn't look like there's much anything we pull directly from the environment outside of tests:

```
$ git grep -ri getenv 
cli/ingress-controller/main_test.go:    home := os.Getenv("HOME")
cli/ingress-controller/main_test.go:    home := os.Getenv("HOME")
pkg/util/k8s.go:        podName := os.Getenv("POD_NAME")
pkg/util/k8s.go:        podNs := os.Getenv("POD_NAMESPACE")
railgun/test/integration/suite_test.go: dbmode = os.Getenv("TEST_DATABASE_MODE")
railgun/test/integration/suite_test.go: if existingClusterName := os.Getenv("KIND_CLUSTER"); existingClusterName != "" {
railgun/test/integration/suite_test.go:         if name := os.Getenv("KIND_CLUSTER_NAME"); name != "" {
railgun/test/integration/suite_test.go: if err := deployControllers(ctx, ready, cluster, os.Getenv("KONG_CONTROLLER_TEST_IMAGE"), controllerNamespace); err != nil {
railgun/test/integration/suite_test.go: return os.Getenv(LegacyControllerEnvVar) != ""
```
There was this in the diff:

```
// TODO: we might want to change how this works in the future, rather than just assuming the default ns
    	if v := os.Getenv(controllers.CtrlNamespaceEnv); v == "" {
    		os.Setenv(controllers.CtrlNamespaceEnv, controllers.DefaultNamespace)
```
But that has since been reworked to use something from Cobra.

**Comment by shaneutt** [comment]
Since this was originally posted we've moved in a significantly different direction which makes this issue no longer relevant, we can safely close this.
