### ISSUE TITLE
[spike] Performance Testing

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1197]
We want to create a performance testing tool that can be applied generically with any particular Kubernetes cluster backend.

Testing should cover:

* number of ingress (`netv1.Ingress`, `TCPIngress`, `UDPIngress`, `knative.Ingress`) updates (to `/config` in the Kong Admin API) per second
  * with CPU, Memory & Networking utilization results over time(seconds)
  * processing time per ingress resource, the processing time includes generating kong state, and update the states to kong
  * how well kic react to service that have many endpoints
  * number of kong consumers

Here are the metrics we want to gather for each of the benchmarks:
```
+---------------------------------------+----+-----+------+-------+-------+--------+
|           # of ingresses              | 10 | 100 | 1000 | 10000 | 50000 | 100000 |
+---------------------------------------+----+-----+------+-------+-------+--------+
| time in parser [s]                    |    |     |      |       |       |        |
| time in cache [s]                     |    |     |      |       |       |        |
| time in deck sync (DB mode) [s]       |    |     |      |       |       |        |
| time in POST /config (DBless mode) [s]|    |     |      |       |       |        |
| total time [s]                        |    |     |      |       |       |        |
| memory consumption MB                 |    |     |      |       |       |        |
+---------------------------------------+----+-----+------+-------+-------+--------+
```

Acceptance Criteria:
- [x] ~releases now include a release artifact which is the result of performance testing for the release tag, graphs~ split out to #1491
- [ ] performance tests run at least once against 1.x to create a baseline for the older version
- [ ] for each of the following: Ingress V1, Ingress V1beta1, knative ingress, TCPIngress, UDPIngress, Consumers, Endpoints - generate the metrics as outlined in the table above.
- [ ]  Performance tests are able to run in an isolated/reproducible environment, and provide test results.

[alpha]:https://github.com/Kong/kubernetes-ingress-controller/milestone/15

**Comment by mflendrich** [comment]
A tiny subset of this issue is being taken care of in https://github.com/Kong/kubernetes-ingress-controller/issues/1465

**Comment by shaneutt** [comment]
The description of this task has been changed a lot, and there's been confusion and contention about the way forward with this issue.

To clear this up and find consensus and a way forward @ccfishk has added a KEP to propose how we move forward with performance testing, and what our goals should be:

https://github.com/Kong/kubernetes-ingress-controller/pull/1640

This effectively replaces this "spike" and should be where new follow up issues stem from.

**Comment by scseanchow** [comment]
@scseanchow to investigate creqs
