### ISSUE TITLE
KIC 2.0 - additional watcher flexibility (e.g. namespaces)

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1204]
The scope of this issue is to identify what other (potentially useful) knobs we might expose to the user to configure watching behavior, and implement them.

KIC 1.x was capable of watching all namespaces or a single namespace. It looks like a low hanging fruit to make it possible to watch multiple namespaces.

**Comment by rainest** [comment]
The 1.x behavior stems from a limitation in go-client, and the maintainers have indicated that they do not intend to change it.

controller-runtime provides a wrapper to automate (AFAIK) management of multiple go-client instances and aggregation of their results: https://github.com/kubernetes/kubernetes/issues/74415#issuecomment-662448739

**Comment by mflendrich** [comment]
> make it possible to watch multiple namespaces

this part of the scope resolved by https://github.com/Kong/kubernetes-ingress-controller/pull/1317
