### ISSUE TITLE
Spike: see how knative should fit into the Gateway API story

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1207]
KIC 2.0 is to come with knative support matching KIC 1.x, as per https://github.com/Kong/kubernetes-ingress-controller/issues/1148

The scope of this issue is to ensure that we have a convincing story as to how knative support should fit into our Gateway API support plans.

**Comment by ccfishk** [comment]
Knative Ingress represents generic integration ingress that GateWay API support, generic CRD/CR monitor and status update is required for this type of integration work.
