### ISSUE TITLE
KIC update all routes & upsteam because some attributes not set to default value

### ISSUE THREAD

**Issue by w313062006** [Kong/kubernetes-ingress-controller#1212]
### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version** 0.9.1

**Kong or Kong Enterprise version** 1.5.1

### Kubernetes version

**paste `kubectl version` output** 1.13.5

### Environment

-  kong on kubernetes 
- debian
- https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-postgres.yaml

### What happened
first, I notice our kong on kubernetes cpu load is abnormal, cpu load will periodic increase to 40%~60%
![image](https://user-images.githubusercontent.com/1832550/115489545-ebcbf480-a28e-11eb-9321-27b888fd3966.png)
![image](https://user-images.githubusercontent.com/1832550/115489621-1027d100-a28f-11eb-8576-13628cc883d7.png)
periodicity is related to the network io, I found the most of  the network io package is from postgresql server to kong. 

![image](https://user-images.githubusercontent.com/1832550/115489721-42d1c980-a28f-11eb-8c2e-628277765891.png)
maybe is kong configurations, why kong load so many configuration to update? 

I check proxy container log in kic, I found many(2000+) PUT request for upstream & route every 1-5s
![image](https://user-images.githubusercontent.com/1832550/115490223-3dc14a00-a290-11eb-86a3-d3210ffadd4d.png)

so I check kic source code, I found some defaut value logic in upstream or route is miss, include PathHandling(default is "v1" in kong https://docs.konghq.com/enterprise/1.5.x/admin-api/#add-route) in route resource, https_verify_certificate(default is true in kong https://docs.konghq.com/enterprise/1.5.x/admin-api/#add-upstream) in upstream resource, because the default logic is miss, kic check route & upstream currentState and targetState will always update resource, so PUT request for route & upstream resources

![image](https://user-images.githubusercontent.com/1832550/115491137-08b5f700-a292-11eb-87f7-5335b257e6d0.png)
above pic show the same route in kic currentState param and  targetState param is different, current is "v1", but targetState is nil. the same as HTTPSVerifyCertificate in upstream.Healthcheck.ActiveHealthcheck, the current is true, but target is nil.

when I add hard code(I don't use these two attributes) before code

https://github.com/Kong/kubernetes-ingress-controller/blob/2caa5240c2f10ade2781b0edf37250e3f38ab927/internal/ingress/controller/kong.go#L256-L262

![image](https://user-images.githubusercontent.com/1832550/115491729-16b84780-a293-11eb-9c9f-31c10d817a97.png)

the cpu load is normal
![image](https://user-images.githubusercontent.com/1832550/115492052-9e05bb00-a293-11eb-8777-a37701e4e29c.png)

I think it's a bug, will fix future?  maybe we can fix this bug by add default value in https://github.com/Kong/deck/blob/main/utils/constants.go

**Comment by hbagdi** [comment]
>  maybe we can fix this bug by add default value in https://github.com/Kong/deck/blob/main/utils/constants.go

Yes, we can add the necessary defaults to fix this problem.
PR welcome.
One thing we will need to test: default by true can lead to a problem where it is not possible to set a value to false due to limitations of reflection in Go. Some testing can verify if this is a problem or not.

**Comment by w313062006** [comment]
> > maybe we can fix this bug by add default value in https://github.com/Kong/deck/blob/main/utils/constants.go
> 
> Yes, we can add the necessary defaults to fix this problem.
> PR welcome.
> One thing we will need to test: default by true can lead to a problem where it is not possible to set a value to false due to limitations of reflection in Go. Some testing can verify if this is a problem or not.

pr https://github.com/Kong/deck/pull/343, plz review

**Comment by shaneutt** [comment]
I appears this was resolved as part of https://github.com/Kong/deck/pull/573. If this is not accurate, or if there's simply more follow up you're looking for on this problem please feel free to comment here and we'll be happy to re-open.
