### ISSUE TITLE
KIC 2.0: customizable ingress class

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1220]
Make it possible to specify the ingress class that Railgun will be watching - currently it's hardcoded as "kong"

Acceptance Criteria:
- [x] the `IngressClassName` should be configurable via the manager CLI
- [x] the `IngressClassName` should be plugged into each controller via the controller manager.
- [x] all controllers which cover `Ingress` and "ingress like" objects supporting the `kubernetes.io/ingress.class` and/or `spec.IngressClassName` field should have logic added to properly handle this

Acceptance Criteria (Tests):
- [x] prove that removing the `ingress.class` removes the backend configuration
- [x] prove that adding the `ingress.class` to an existing object results in that object thereafter being configured in the proxy

**Comment by mflendrich** [comment]
@hbagdi's comment:
> Constants.go: KongIngressClass-> confusing name. DefaultIngressClassName is probably a better name. Stylistic minor comment.

**Comment by shaneutt** [comment]
Blocked on #1251 as this will have a large bearing on how this functions.

**Comment by shaneutt** [comment]
Acceptance Criteria:
- [x] the `IngressClassName` should be configurable via the manager CLI
- [ ] the `IngressClassName` should be plugged into each controller via the controller manager.
- [ ] all controllers which cover `Ingress` and "ingress like" objects supporting the `kubernetes.io/ingress.class` and/or `spec.IngressClassName` field should have logic added to properly handle this

Acceptance Criteria (Tests):
- [ ] Ingress with no annotation and with no IngressClassName
- [ ] Ingress with an annotation not-kongtests
- [ ] Ingress with an annotation kongtests
- [ ] Ingress with a spec.IngressClassName not-kongtests
- [ ] Ingress with a spec.IngressClassName kongtests

**Comment by shaneutt** [comment]
This is resolved, however there is follow up that needed to be split off to ultimately remove support for classless ingress:

https://github.com/Kong/kubernetes-ingress-controller/issues/1293

This has been added to the same milestone.
