### ISSUE TITLE
KIC 2.0: Test Admin API connection with and without mtls/headers

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1234]
https://github.com/Kong/kubernetes-ingress-controller/pull/1232 introduced mTLS and headers support (ported from KIC 1.x) without automated tests.

The scope of this issue is to test the Admin API connection between KIC 2.x and Kong Admin API, to the extent of options available in `struct HTTPClientParams`.

**Comment by shaneutt** [comment]
Closing as stale, there doesn't appear to be any specific driver for this issue but we can re-open if there is still a need.
