### ISSUE TITLE
Spike: Feature gates

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1237]
Spin-off from #1089 

#1089 ended up being about a specific type of feature gating: enabling and disabling individual controllers.

This spike is (as a follow up to [KEP5](https://github.com/Kong/keps/pull/15)) to reach a decision whether (and how) we want to:
- implement an analog to [upstream feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) in the KIC such as to:
    - ~make all user-facing Kubernetes APIs optional~ _(this is covered by #1089)_, and to 
    - improve communication with our end-users and community on the maturity and longevity of the ~APIs~ functionality we maintain going forward.

**Comment by mflendrich** [comment]
I'm requesting that we carefully consider:
- the use cases for which we need feature gating,
- the alternative of using the `IngressClass` `parameters` field as a potentially more suitable alternative to feature gating (see #1131)

**Comment by shaneutt** [comment]
Feature gates are now used by KIC and the documentation lives at FEATURE_GATES.md
