### ISSUE TITLE
kong ingress controller sync config too frequently leading to Kong high cpu and latency

### ISSUE THREAD

**Issue by jiachinzhao** [Kong/kubernetes-ingress-controller#1244]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.9.0

**Kong or Kong Enterprise version**
2.1.4

### Kubernetes version
**paste `kubectl version` output**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
we found that our kong  cpu  and latency increase much。
from kong ingress controller logs, we found logs that sync config too frequently,  sync config to Kong on every 3s, and before the probelem occured, the  sync config logs were  just  avg 3 ~ 4 times  every 1 minute  during no ingress rule apply。

I0425 07:29:32.820899       1 kong.go:81] successfully synced configuration to Kong
I0425 07:29:36.323279       1 kong.go:81] successfully synced configuration to Kong
I0425 07:29:39.063368       1 kong.go:81] successfully synced configuration to Kong
I0425 07:29:42.975222       1 kong.go:81] successfully synced configuration to Kong
I0425 07:29:45.959983       1 kong.go:81] successfully synced configuration to Kong
I0425 07:29:49.239770       1 kong.go:81] successfully synced configuration to Kong
I0425 07:29:50.099267       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:29:56.008263       1 kong.go:81] successfully synced configuration to Kong
I0425 07:29:56.746249       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:30:02.683603       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:03.429530       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:30:08.877147       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:12.323348       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:15.672855       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:19.187818       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:23.222010       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:25.582016       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:29.175048       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:32.595798       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:35.505834       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:39.015165       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:42.749677       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:45.578335       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:49.169610       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:52.123154       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:55.696939       1 kong.go:81] successfully synced configuration to Kong
I0425 07:30:58.955116       1 kong.go:81] successfully synced configuration to Kong
I0425 07:31:02.443526       1 kong.go:81] successfully synced configuration to Kong
I0425 07:31:05.372858       1 kong.go:81] successfully synced configuration to Kong
I0425 07:31:09.428784       1 kong.go:81] successfully synced configuration to Kong
I0425 07:31:16.753634       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:31:23.503732       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:31:43.416638       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:32:10.091917       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:32:13.418591       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:32:19.403006       1 kong.go:81] successfully synced configuration to Kong
I0425 07:32:22.298885       1 kong.go:81] successfully synced configuration to Kong
I0425 07:32:26.292184       1 kong.go:81] successfully synced configuration to Kong
I0425 07:32:29.511063       1 kong.go:81] successfully synced configuration to Kong
I0425 07:32:30.177935       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:32:33.442987       1 kong.go:68] no configuration change, skipping sync to Kong
I0425 07:32:39.105393       1 kong.go:81] successfully synced configuration to Kong
I0425 07:32:41.891060       1 kong.go:81] successfully synced configuration to Kong

I opend --v=3 flags to watch  what update events  we watch， there are too many Endpoints, Service, Ingress, Secret Events, it takes some time to figure what happened。

I found that some pods in k8s are changed frequently due to restart, and there are also many hpa, this may lead to Endpoints event update  high  frequency。

from the configuration https://docs.konghq.com/kubernetes-ingress-controller/1.2.x/references/cli-arguments/,
my only solution is  to adjust   –sync-rate-limit=0.3(default)    ->   0.1,  slow down sync frequency, this is a temporary effective method, but increase time to sync ingress rule。

### Expected behavior
update frequency should not affect  kong's  request processing too much。

### Steps To Reproduce

1.
2.
3.
4.

**Comment by w313062006** [comment]
hi, maybe relate to #1212

**Comment by jiachinzhao** [comment]
I 'm  using Kong db-less mode,  from the source code, maybe not the same issue。
I 'm using ingress nginx to compare  ingress rule sync frequency,  I found that ingress nginx  controller is always skipping backend reload,   which means  Service, Endpoints and Ingress are not change。 
Now still working on figure out the difference of sync ingress rule between kong ingress controller and  ingress nginx controller。

**Comment by rainest** [comment]
DB versus DB-less mode should behave the same here. They both populate defaults.

https://github.com/Kong/deck/issues/196#issuecomment-819768166 covers the settings I saw flapping when I checked most recently, but [as mentioned by Harry](https://github.com/Kong/deck/pull/343#issuecomment-826957572), some of these settings aren't available in all versions, and adding a universal default for them would break compatibility.

The controller can set its own defaults independent of decK, and does have the ability to handle version-aware defaults, so handling these in the controller for now is more viable than handling them via decK's constants.go (which isn't version-aware).

**Comment by jiachinzhao** [comment]
After upgrade controller  to latest 1.2.0  and dump generated configuration  several times to compare,  two certificate 
 differences are found。
one issue is 
a certificate with fixed tls host changed between two certificate。
we checked our ingress rules, we found this tls ingress rule with same host are configured in two different namespaces。
kong ingress controller can not handle this situation properly。

https://github.com/Kong/kubernetes-ingress-controller/blob/fa0afebe1ccd19551305c89008d829a10790a1a0/pkg/parser/parser.go#L267     go map iterate unorder lead to the result。



another issues is  SNIs Slice compare。
a certificate with many hosts, sometimes return
["xxx.com", "yyy.com"] 
["yyy.com", "xxxx.com"]


certificate snis should be sorted before DeepEqual here
https://github.com/Kong/kubernetes-ingress-controller/blob/fa0afebe1ccd19551305c89008d829a10790a1a0/pkg/deckgen/generate.go#L104

```golang
sort.SliceStable(cert.SNIs, func(i, j int) bool {
			return strings.Compare(*cert.SNIs[i].Name, *cert.SNIs[j].Name)	> 0
})
```

**Comment by shaneutt** [comment]
Closing as stale. If any users are still having this issue on modern supported versions of the ingress controller (e.g. v2) please feel free to comment here with the versions where you're experiencing the problem and we'll be happy to re-open and re-assess.

**Comment by ebarped** [comment]
This is happening to me:
```
ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:18:59Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:18:59Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:01Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:02Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:04Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:08Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:10Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:11Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:16Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:17Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:20Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:22Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:23Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:28Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:29Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
```
Info:
- KIC: 2.2.1
- Kong: 2.7.1
- 2 Replicas

**Comment by shaneutt** [comment]
> This is happening to me:
> 
> ```
> ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:18:59Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:18:59Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:01Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:02Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:04Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:08Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:10Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:11Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:16Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:17Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:20Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:22Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:23Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-l6xzk ingress-controller time="2022-05-13T08:19:28Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ingress-kong-75f7667f87-bgg2l ingress-controller time="2022-05-13T08:19:29Z" level=info msg="successfully synced configuration to kong." subsystem=proxy-cache-resolver
> ```
> 
> Info:
> 
>     * KIC: 2.2.1
> 
>     * Kong: 2.7.1
> 
>     * 2 Replicas

It is possible on version `v2.2.1` to configure the frequency of config synchronization using the following flag:

```
--proxy-sync-seconds
```

Please see the [documentation for this](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/cli-arguments/) and note that the default is 3 (seconds) and you can increase this to see if it helps reduce problems you are having. Please note that increasing this does inherently increase the time it takes for new configuration to take effect which in a lot of cases may not be a problem, but in cases where routes are constantly changing and need to be up quickly you may want to consider other options like deploying multiple copies of the KIC+Gateway and segmenting namespaces between those.

Given the age and context of this issue we would ask that if the above is not helpful and you continue to run into trouble, please open a new issue and fill out all the issue template details OR start a discussion if you're looking for something more like a place to ask informal questions.

**Comment by ebarped** [comment]
Thank you very much!

I increased the loop sync interval to 30s, and it seems that many random errors that i had have gone away.

```
- name: CONTROLLER_PROXY_SYNC_SECONDS # slow down the sync rate to 30s
  value: "30"
```
