### ISSUE TITLE
feature: ensure timeouts are set in the controller for all requests outbound to Kong's Admin API

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#1250]
The controller doesn't set any timeouts (TCP, TLS, HTTP) when it should be doing so rather than relying on kernel level settings.

The scope here is to hardcode a timeout of 10seconds.
This can be made configurable in future if there are users who ask for it, the probability of that happening is currently low given the level of detail this involves.

**Comment by hbagdi** [comment]
See https://github.com/Kong/deck/pull/353 for reuse and prior art.

**Comment by rainest** [comment]
Ah, wrote https://github.com/Kong/go-kong/pull/51#pullrequestreview-645168730 before seeing this.

If we do intend to break from the current no-timeout behavior in the controller and not just in go-kong, I think configurable timeouts should be a prerequisite for this, for the same reason mentioned in the other comment (DB-less config posts can take a while with larger config).

**Comment by shaneutt** [comment]
Closing as stale as it doesn't appear that we've had any specific issues come up, and no updates on this in about a year. However if anyone still feels there's more followup to do here then please feel free to comment and we can re-open/re-assess.
