### ISSUE TITLE
KIC 2.0 DB mode support + integration tests

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1253]
Railgun as of today only supports Kong DB-less.

This issues is to introduce decK (DB-mode) as well.

Acceptance criteria:
- [x] reuse the existing KIC 1.x functionality that triggers a deck sync (possibly refactoring it into a function), as opposed to writing new code for it
- [x] integration tests now run against a postgres backed proxy for each PR

**Comment by shaneutt** [comment]
blocked on https://github.com/Kong/kubernetes-testing-framework/pull/23

**Comment by shaneutt** [comment]
We wont be able to add support for `v1alpha1.UDPIngress` in Postgres DBMODE due to a lack of support for configurations of Services without related K8s services under these conditions, this will be resolved by https://github.com/Kong/kubernetes-ingress-controller/issues/1080 in a later iteration.
