### ISSUE TITLE
KIC 2.0 - Deployment Manifests Roundup

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1256]
As it relates to https://github.com/Kong/kubernetes-ingress-controller/issues/1215 the purpose of this issue is to ensure that we review and resolve any issues with the deployment manifests for all of our components, CRDs, and sample configurations.

Acceptance Criteria:
- [x] all deployment manifests for the controller manager and related components are functional and don't require cleanup
- [x] all manifests and related service accounts have proper RBAC roles associated, none of them use `ClusterAdmin` permissions
- [x] CRDs are deployable, and running `make` to generate them does not result in changes when no code changes occur
- [x] Samples are all functional, based on some of the integration test cases and do something meaningful as an example of API usage
- [x] CRD and RBAC resources are deployable using the the ~Helm chart~ Kustomize manifests. The Helm chart part is handled by #1209.

**Comment by mflendrich** [comment]
Similar to #1464

**Comment by mflendrich** [comment]
blocked by #1498

**Comment by rainest** [comment]
Some other things uncovered during my initial attempt:

- [ ] the ServiceAccount in `railgun/config/rbac/role_binding.yaml` uses a different name than 1.x. Looks like this file was added manually and should be modified directly.
- [ ] ditto `leader_election_role_binding.yaml`
- [ ] 2.x patches should modify probes to use the new readyz endpoint.
