### ISSUE TITLE
failed to retrieve PostgreSQL server_version_num

### ISSUE THREAD

**Issue by huangyonghome** [Kong/kubernetes-ingress-controller#1273]
HI
I am using this manifest to deploy kong ingress on my k8s cluster:
https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml

I make a little changes to the manifest by using `DaemonSet` to deploy `ingress-kong` . Because I need to pass the client actual IP address to the ultimate Pod. 

After executing the command `kubeclt apply -f all-in-one-postgres.yaml`  I noticed the kong ingress Pods remained at the stage of Init:
```
[root@sim-k8s-master kong]$kubectl get pods -n kong
NAME                    READY   STATUS      RESTARTS   AGE
ingress-kong-hcn6j      0/2     Init:0/1    0          11m
ingress-kong-m96gs      0/2     Init:0/1    0          11m
ingress-kong-tzptp      0/2     Init:0/1    0          11m
kong-migrations-ln9gz   0/1     Completed   0          11m
postgres-0              1/1     Running     0          11m
```

So I checked the logs of Init container ,and saw a lot of error information,It seemed that the Postgre Pod couldn't to be reachable
```
[root@sim-k8s-master kong]$kubectl logs ingress-kong-hcn6j wait-for-migrations  -n kong
Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: host or service not provided, or not known

  Run with --v (verbose) or --vv (debug) for more details
Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: host or service not provided, or not known

  Run with --v (verbose) or --vv (debug) for more details
Error: [PostgreSQL error] failed to retrieve PostgreSQL server_version_num: host or service not provided, or not known
```
To verify the network connection,I temporarily created and login to a Pod in `kong` namespace. obviously the network was working fine 
   
```
[root@sim-k8s-master kong]$kubectl exec -it test-wfwfr -n kong -- bash

#resolving the SVC of postgres
[root@test-wfwfr /]# dig postgres.kong.svc.cluster.local

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;postgres.kong.svc.cluster.local. IN	A

;; ANSWER SECTION:
postgres.kong.svc.cluster.local. 30 IN	A	10.96.205.172

#telnet the port of postgres
[root@test-wfwfr /]# telnet postgres.kong.svc.cluster.local 5432
Trying 10.96.205.172...
Connected to postgres.kong.svc.cluster.local.
Escape character is '^]'.

```

Below is the logs of `postgres-0` container:
```
[root@sim-k8s-master pgdata]$kubectl logs postgres-0 -n kong
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start


WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....LOG:  database system was shut down at 2021-04-30 09:37:52 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down...LOG:  received fast shutdown request
LOG:  aborting any active transactions
LOG:  autovacuum launcher shutting down
.LOG:  shutting down
LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

LOG:  incomplete startup packet
LOG:  database system was shut down at 2021-04-30 09:37:57 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```

I once suspected the Postgres database rejected the remote access. So I modified the `pg_hba.conf` file by adding below two row of contents.

```
host    all             all             0.0.0.0/0           trust
host    all             all             0.0.0.0/0           md5
```

But, unfortunately, all tries were failed.this problem still remained.

Could anyone give me a few clues ?

Thank you in advance!

### Kubernetes version

```
[root@sim-k8s-master pgdata]$kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by uzxmx** [comment]
According to [this](https://github.com/Kong/kong/blob/50b8405d02a3bcdf070033632ef0521db1219371/kong/db/strategies/postgres/connector.lua#L280), Kong tries to get the db version first, so the error happens when it cannot find the PostgreSQL.

IMO, there may be something wrong with your PostgreSQL related environment variables specified in the  `env` section. Please compare the environment variables specified in `kong-migrations` as shown [here](https://github.com/Kong/kubernetes-ingress-controller/blob/cf23618b3547dd39e27919c93fe43b8fde3b77ca/deploy/single/all-in-one-postgres.yaml#L823) with the ones in `ingress-kong` [here](https://github.com/Kong/kubernetes-ingress-controller/blob/cf23618b3547dd39e27919c93fe43b8fde3b77ca/deploy/single/all-in-one-postgres.yaml#L754).

You can also try to connect into the failed pod (by updating the container command, e.g. `sleep infinity`, and check if the desired environment variables are correctly specified.

You can find the supported environment variables here:

* https://docs.konghq.com/gateway-oss/2.3.x/configuration/#environment-variables
* https://docs.konghq.com/gateway-oss/2.3.x/configuration/#postgres-settings

**Comment by huangyonghome** [comment]
@uzxmx Thank you for reply...I defined the environment follow by the document:
https://docs.konghq.com/enterprise/2.3.x/deployment/installation/docker/
```
docker run --rm --network=kong-ee-net \
  -e "KONG_DATABASE=postgres" \
  -e "KONG_PG_HOST=kong-ee-database" \
  -e "KONG_PG_PASSWORD=kong" \
  -e "KONG_PASSWORD=<SOMETHING-YOU-KNOW>" \
  kong-ee kong migrations bootstrap

```

bellow is the segment of the init container in my yaml file:
```
  initContainers:
      - command:
        - /bin/sh
        - -c
        - while true; do kong migrations list; if [[ 0 -eq $? ]]; then exit 0; fi; sleep 2;  done;
        env:
        - name: KONG_PG_HOST
          value: postgres
        - name: KONG_PG_PASSWORD
          value: kong
        - name: KONG_DATABASE
          value: postgres
        - name: KONG_PASSWORD
          value: kong
        image: kong:2.3
        name: wait-for-migrations
```
did I miss some key environment or type the environment name wrong?

**Comment by rainest** [comment]
Any change if you set `KONG_PG_HOST=postgres.kong.svc.cluster.local`?

Not clear why this would happen, but possibly there's some issue with the DNS search path not getting set correctly. Weird that the migrations Job completed successfully though--it should exhibit the same issue.

**Comment by shaneutt** [comment]
Closing as stale as we have not heard back on this issue in some time. Please update us if this continues to be a problem on modern supported versions of the ingress controller, let us know what versions are in use and we'll be happy to re-open and re-assess.
