### ISSUE TITLE
Metrics for cache and proxy resolution

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1278]
In KIC 2.0 we added the concept of a `Proxy` interface which is responsible for resolving Kubernetes objects to Kong DSL and the upstream Kong Admin API.

The purpose of this issue is to add metrics for our caching client-go based implementation which caches and periodically resolves that cache to the Admin API.

**Comment by hbagdi** [comment]
Just a note, the metrics are part of the public interface for the controller and they shouldn't be broken so we should take extra precaution when we are introducing them and keep forward-compatibility in mind.

**Comment by ccfishk** [comment]
@shaneutt @hbagdi query for clarification : does controller expose kong (proxy, all the services deployed on the cluster) metrics using following handler ?
https://github.com/Kong/kubernetes-ingress-controller/blob/main/cli/ingress-controller/main.go#L633

how does this metrics associated to the Admin API /metrics endpoints ?

**Comment by hbagdi** [comment]
> how does this metrics associated to the Admin API /metrics endpoints ?

The `/metrics` on Admin and Status API of Kong provides metrics for Kong proxy itself.
The metrics for controller are separate from the metrics of Kong proxy.
We don't want to mix those two.

**Comment by shaneutt** [comment]
https://github.com/Kong/kubernetes-ingress-controller/pull/1612 changed this such that we no longer manage cache in the proxy server, so this is no longer relevant.
