### ISSUE TITLE
Make the /config timeout configurable

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1291]
Implement a flag to control the setting below.

https://github.com/Kong/kubernetes-ingress-controller/blob/347ed5fb48a6f3e74b537e56e82259bdb0d82b1a/railgun/internal/proxy/clientgo_cached_proxy_resolver.go#L214

**Comment by tharun208** [comment]
@shaneutt I like to work on this

**Comment by shaneutt** [comment]
> @shaneutt I like to work on this

Sounds good, freel free and thank you :bow:

**Comment by tharun208** [comment]
implemented in #1401
