### ISSUE TITLE
Support selector tags in KIC 2.0

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1292]
The line below always implies that selector tags are configured as empty.

https://github.com/Kong/kubernetes-ingress-controller/blob/347ed5fb48a6f3e74b537e56e82259bdb0d82b1a/railgun/internal/proxy/clientgo_cached_proxy_resolver.go#L216

**Comment by rainest** [comment]
#1415 was merged.
