### ISSUE TITLE
KIC 2.0: Handle profiling flag

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1298]
1.x uses the `--profiling` flag to enable [pprof](https://golang.org/pkg/net/http/pprof/) endpoints [on the health/metrics/etc. HTTP server](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/cli/ingress-controller/main.go#L698-L709).

2.x uses the controller-runtime default servers, so it doesn't immediately have a place to put this. We'd need to add a custom server to still expose profiling data. The rest of the implementation is unlikely to change, since we just call pprof's functions.

**Comment by tharun208** [comment]
@shaneutt I like to work on this

**Comment by shaneutt** [comment]
> @shaneutt I like to work on this

Please feel free, and thanks again! :bow:

**Comment by tharun208** [comment]
Before getting started in 1.x we are running the profiling server in a separate goroutine. can we do the same here? also where to keep in this in 2.0 ? in `admission.go` or inside `manager/run.go` ?

**Comment by shaneutt** [comment]
> Before getting started in 1.x we are running the profiling server in a separate goroutine. can we do the same here?

Yes, it makes sense to have this running concurrently and separately from the main routine as `v1.x` did.

> also where to keep in this in 2.0 ? in `admission.go` or inside `manager/run.go` ?

I would suggest opting for `internal/` for now, perhaps `internal/metrics/` and then we can wire it up via `manager.run.go` if that sounds good to you?

Side note: we can always move things later if it makes sense, but _in general_ defaulting to `internal/` sends a clear message that the functionality is meant to be abstracted away from end-users and so provides us some extra freedom later if we want to move things around.

**Comment by tharun208** [comment]
> > Before getting started in 1.x we are running the profiling server in a separate goroutine. can we do the same here?
> 
> Yes, it makes sense to have this running concurrently and separately from the main routine as `v1.x` did.
> 
> > also where to keep in this in 2.0 ? in `admission.go` or inside `manager/run.go` ?
> 
> I would suggest opting for `internal/` for now, perhaps `internal/metrics/` and then we can wire it up via `manager.run.go` if that sounds good to you?
> 
> Side note: we can always move things later if it makes sense, but _in general_ defaulting to `internal/` sends a clear message that the functionality is meant to be abstracted away from end-users and so provides us some extra freedom later if we want to move things around.

sure, sounds good to me 👍🏻

**Comment by rainest** [comment]
Implemented in #1417
