### ISSUE TITLE
KIC 2.0: handle sync-rate-limit flag

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1300]
1.x uses the `--sync-rate-limit` flag to [configure a client-go rate limiter](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/internal/ingress/controller/controller.go#L129), which [blocks the parser builder](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/internal/ingress/controller/controller.go#L89) (where we fetch objects from the K8S API).

For 2.x we need to figure out how to fit this into our new cache client code.

**Comment by mflendrich** [comment]
KIC 2.x introduces rate limiting in #1267 in a different (incompatible) fashion.

After discussion, the scope of this issue is to:
- decide whether we want to implement the `--sync-rate-limit` flag in a compatible fashion
- if yes: implement it
- if not: mark the breaking change in the docs
