### ISSUE TITLE
KIC 2.0: handle update-status and update-status-on-shutdown flags

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1304]
`--update-status` [enables or disables](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/internal/ingress/controller/controller.go#L160-L184) the Ingress [status update background job](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/internal/ingress/controller/controller.go#L244-L249).

`--update-status-on-shutdown` [enables or disables Ingress status updates by the leader when it is shutting down](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/internal/ingress/status/status.go#L129-L133). It is enabled by default. The 1.x implementation had [known issues](https://github.com/Kong/kubernetes-ingress-controller/issues/581).

In 1.x, these updates populate address information for Ingress objects (i.e. the value shown in the `ADDRESS` column when you run `kubectl get ingress`). 2.x [reworks status handling significantly](https://github.com/Kong/kubernetes-ingress-controller/issues/1275).

Low priority since toggling status updates off isn't a critical feature.

**Comment by shaneutt** [comment]
I have re-enabled `--update-status` but I can see no value in maintaining the `--update-status-on-shutdown`. KIC 2.0 has no other mechanisms for cleanup on shutdown, and in fact the idempotent nature of the current design is meant to account for "cleanup". As such I have made a PR which proposes deprecating the second flag given that it conflicts with the direction we're going with KIC, and seems to be of dubious value (whereas conversely `--update-status` is of obvious value).

**Comment by sephethus** [comment]
That's fine, nobody knows where to put that flag anyway because it's not like there's examples or documentation.
