### ISSUE TITLE
KIC 2.0: handle publish-service and publish-status-address flags

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1305]
`--publish-service` and `--publish-status-address` [provide the address for Ingress status information](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/internal/ingress/status/status.go#L226-L270). The former looks up the address associated with a Service and uses that. The latter allows users to set an address directly.

[Either one or the other must be configured](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/cli/ingress-controller/main.go#L151-L153).

These flags should be implemented as part of the [remaining status update work](https://github.com/Kong/kubernetes-ingress-controller/issues/1275).

**Comment by mflendrich** [comment]
@mflendrich to clearly identify the scope of this issue and #1349 and the overlap between the two.

**Comment by mflendrich** [comment]
May be fixed by #1451

**Comment by rainest** [comment]
Additionally needs https://github.com/Kong/kubernetes-ingress-controller/pull/1509
