### ISSUE TITLE
KIC 2.0: handle enable-reverse-sync flag

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1307]
`--enable-reverse-sync` toggles an [argument passed to PerformUpdate](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/internal/ingress/controller/kong.go#L53). When enabled, it [disables the config SHA check](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/pkg/sendconfig/sendconfig.go#L41-L47), and the controller always performs a sync regardless of whether or not the config changed.

For 2.x, we should plug something similar into [the equivalent config SHA check](https://github.com/Kong/kubernetes-ingress-controller/pull/1282/files).

**Comment by tharun208** [comment]
@rainest , I see from the `main` branch this flag is already handled.

**Comment by rainest** [comment]
Yep, we missed this when added it. @tharun208 thanks for catching the discrepancy.

Solved in #1313
