### ISSUE TITLE
KIC 2.0: handle dump-config flag

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1308]
`--dump-config` enables a [diagnostic dump of generated configuration](https://github.com/Kong/kubernetes-ingress-controller/blob/v1.2.0/internal/ingress/controller/kong.go#L60-L69). It is disabled by default.

**Comment by tharun208** [comment]
as #1408 is there. instead of writing to local files, can we expose the config in a separate URL `/config` ?.

**Comment by rainest** [comment]
Yeah, that's the rough plan, probably under `/debug/config`-the filesystem dumps were a quick and easy way to get the files directly from the config sync loop, but my long-term plan was to instead expose a web interface, since copying stuff out is clunky.

The other thing I'd like to add is a short history of the last few generated configurations rather than only recording the latest good/bad config: we've found that one of the most common use cases for this is to figure out why the controller is updating configuration when we wouldn't expect it to. Getting several iterations of config updates with the single dumps is possible by just copying it out multiple times, but you have to time it manually, which is annoying.

**Comment by tharun208** [comment]
@rainest I like to work on this

**Comment by rainest** [comment]
@tharun208 sure, go ahead.

We do want to leave the flag in place since enabling these can expose sensitive info within the config somewhere it wouldn't normally be accessible, and it should only be on temporarily when collecting diagnostic info though, so please don't remove that.

**Comment by tharun208** [comment]
@rainest, is it okay to extend the `UpdateKongAdminSimple` as we are already calling `deckgen.ToDeckContent` ?
https://github.com/Kong/kubernetes-ingress-controller/blob/next/pkg/sendconfig/common_workflows.go#L47

**Comment by rainest** [comment]
I don't see any particularly good place to stick it. Originally we added the dir to the user config struct and passed that (which already included the dump mode) to `OnUpdate()` (sort of the predecessor to `UpdateKongAdminSimple()`). `OnUpdate()` was also a method and had access to the controller config (sort of like the `clientgoCachedProxyResolver` struct).

They arguably shouldn't go into the `Kong` struct, since that holds connection information for the admin API, and the dump configuration doesn't fall into that category.

As-is, I think these should be new fields in `clientgoCachedProxyResolver` and should be arguments to `UpdateKongAdminSimple()`.

The latter's signature is getting unwieldy at this point. @shaneutt do you think it'd make sense to refactor it to accept a new struct containing static config (probably `ingressClassName`, `enableReverseSync`, this dump configuration, and `kongConfig`, and possibly the cache, which don't change between invocations) and pass that instead?

**Comment by tharun208** [comment]
@rainest, also I am planning to expose the config on the web interface, can I include the same in this pr or?

**Comment by rainest** [comment]
Yep, [that's fine](https://github.com/Kong/kubernetes-ingress-controller/issues/1308#issuecomment-858841763). It'd be an additional part of https://github.com/Kong/kubernetes-ingress-controller/blob/next/railgun/internal/diagnostics/server.go

To implement that you'd presumably add a channel to ship the config blob from the update loop to the diagnostics server.

**Comment by rainest** [comment]
@tharun208 hey, checking in on this again. We'd like to put out a feature complete 2.x beta by the end of July, so we plan to take over development of this to get it out on time for that. Did you have any draft code for this already in progress that you wanted to publish for us to try and work on collaboratively, or was it as of yet not started?

**Comment by tharun208** [comment]
@rainest I haven't started working on this. I am un-assigning myself from this issue.
