### ISSUE TITLE
CI License Check Issues

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1335]
I've noticed a few license check CI failures on PRs recently, in each case the license setup was find there was just some other error that occurred. Here's some example PRs I've seen fail:

- https://github.com/Kong/kubernetes-ingress-controller/pull/1319
- https://github.com/Kong/kubernetes-ingress-controller/pull/1325
- https://github.com/Kong/kubernetes-ingress-controller/pull/1326
- https://github.com/Kong/kubernetes-ingress-controller/pull/1322

**Comment by rainest** [comment]
These are all from the Github Actions outage, I think. Dependabot PRs shouldn't have issues.

Foreign PRs do: https://github.com/Kong/kubernetes-ingress-controller/pull/1272/checks?check_run_id=2622761132

**Comment by shaneutt** [comment]
> These are all from the Github Actions outage, I think. Dependabot PRs shouldn't have issues.
> 
> Foreign PRs do: https://github.com/Kong/kubernetes-ingress-controller/pull/1272/checks?check_run_id=2622761132

There's some older ones from these PRs which were failing due to regex checks, but I'm not finding them in the history now perhaps they were purged?
