### ISSUE TITLE
KIC 2.0: status field parity with 1.x

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1349]
Acceptance Criteria:
- [x] all 3 API versions (ext/v1beta1, net/v1beta1, net/v1) of `Ingress` get `status` updates that matches what we do for KIC 1.x
- [x] integration tests are added that prove the status updates and protect against regressions to them
- [x] the `--publish-service` flag works as it did in 1.x

**Comment by rainest** [comment]
These are not the CRD status fields (which just exist in 1.x and aren't used AFAIK), but are handled as part of the general status update job in 1.x, which does add information to Ingresses (their address status):

https://github.com/Kong/kubernetes-ingress-controller/issues/1305
https://github.com/Kong/kubernetes-ingress-controller/issues/1304
