### ISSUE TITLE
KIC 2.0 - Ingress LoadBalancer Status Parity

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1350]
The `Ingress` controllers for `extensions.v1beta1`, `net.v1beta1` and `net.v1` need to add missing `.status.loadBalancer` updates for parity with how these statuses are handled in 1.x.

Acceptance Criteria:
- [ ] all 3 supported `Ingress` APIs get `status` updates that matches what we do for KIC 1.x
- [ ] integration tests are added that prove the status updates and protect against regressions to them

**Comment by mflendrich** [comment]
duplicate of #1349
