### ISSUE TITLE
KIC 2.0 - Fix workspace support

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1353]
Passing `--kong-workspace` to 2.x attempts to use a workspace, but it does so incorrectly and fails to start. On the controller:

```
$ kubectl logs -f -n helmgress dancing-cow-kong-d5868fc74-llh4h -c ingress-controller
time="2021-05-25T22:52:27Z" level=info msg="admission webhook server disabled"
time="2021-05-25T22:52:27Z" level=info msg="starting controller manager" commit=UNKNOWN logger=setup release=UNKNOWN repo=UNKNOWN
W0525 22:52:27.146765       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-05-25T22:52:27Z" level=info msg="the ingress class name has been set" logger=setup value=smoke
time="2021-05-25T22:52:27Z" level=info msg="metrics server is starting to listen" addr=":10255" logger=controller-runtime.metrics
time="2021-05-25T22:52:29Z" level=error msg="unable to start proxy cache server" error="HTTP status 404 (message: \"Not found\")" logger=setup
Error: HTTP status 404 (message: "Not found")
```
On Kong:

```
127.0.0.1 - - [25/May/2021:22:55:11 +0000] "HEAD /workspaces/other HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
127.0.0.1 - - [25/May/2021:22:55:11 +0000] "GET /other/ HTTP/1.1" 404 23 "-" "Go-http-client/1.1"
```
This needs to be looking at `/kong` in the workspace instead. As best I recall, the ensure workspace code doesn't currently work either.

**Comment by tharun208** [comment]
@shaneutt, I will debug and fix this

**Comment by shaneutt** [comment]
> @shaneutt, I will debug and fix this

Thanks @tharun208 :vulcan_salute:

**Comment by shaneutt** [comment]
@tharun208 just checking in, how are things going with this one? Can we provide any assistance?

**Comment by shaneutt** [comment]
@tharun208 we're reaching a point where this issue is becoming time sensitive for the KIC 2.0 release, in a day or two if we don't hear back from you we'll have to start a separate implementation to meet our timelines, but please check in before then if you can. We would even be happy to work from any partial implementation you may have and continue it. Thank you! :bow:

**Comment by tharun208** [comment]
@shaneutt, sorry totally missed it. Can you take care of this?

**Comment by shaneutt** [comment]
> @shaneutt, sorry totally missed it. Can you take care of this?

Yes, no problem at all we always appreciate your contributions and totally understand. :vulcan_salute: thanks for letting us know :heart:

**Comment by shaneutt** [comment]
Needs https://github.com/Kong/go-kong/pull/73
