### ISSUE TITLE
Fix service and endpoint RBAC generators

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1356]
See https://github.com/Kong/kubernetes-ingress-controller/issues/1352#issuecomment-848243055 and https://github.com/Kong/kubernetes-ingress-controller/issues/1352#issuecomment-848289173 for a bit of background.

The 2.x controller needs to interact with Service and Endpoint resources, but currently generates RBAC resources that don't actually allow this. It attempts to create roles with permissions to these resources in a `v1` API group, but this is incorrect. These resources are in the core (empty) API group, and the permission needs to have `{"apiGroups": [""]}`, not `{"apiGroups": ["v1"]}` for these. It currently has the latter.

kubebuilder generates these permissions from the annotations at https://github.com/Kong/kubernetes-ingress-controller/blob/6ef21e594fa71e0b7d5471797405d10221353f2e/railgun/controllers/configuration/zz_generated_controllers.go#L124-L126

As best I can tell, these are sourced from the following template:
https://github.com/Kong/kubernetes-ingress-controller/blob/6ef21e594fa71e0b7d5471797405d10221353f2e/railgun/hack/generators/controllers/networking/main.go#L32-L54
https://github.com/Kong/kubernetes-ingress-controller/blob/6ef21e594fa71e0b7d5471797405d10221353f2e/railgun/hack/generators/controllers/networking/main.go#L298-L300

However, I'm unsure what we should use to regenerate the generated code after. My attempts to run `make generate`, `make controller-gen`, and `go generate ./...` don't appear to be correct.

**Comment by mflendrich** [comment]
@rainest see #1357 if that solves the problem.
