### ISSUE TITLE
Streamline codegen makefile targets

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1358]
We have been confused by separate unrelated codegen targets existing in both the 1.x and the 2.x makefile:

```
make controller-gen
make generate
make manifests
make generate.controllers
```

They need to be run in a particular order in order to produce the desired effect (see #1357)

The scope of this issue is to being to reign over code generation in KIC.
This may take a form of documenting code generation or combining the codegen targets into one.

**Comment by rainest** [comment]
Similar to 1.x we'll also want generation linter to run these automatically on PRs in a temporary location and compare the actual PR code to them.

**Comment by rainest** [comment]
Learning from #1361:

- You also need to run `make generate.clientsets` in some cases.
- Generated code is split between kubebuilder and client-gen. Kubebuilder _does not_ invoke client-gen on your behalf, and the two have different sets of metadata tags (https://book.kubebuilder.io/reference/markers.html and https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md). Depending on your desired change, you may need tag updates for both. If one of the make targets apparently does nothing despite your having made a tag change, and you expected it to, double-check to see if you've only added a tag for one of the tools and need to add a related tag for the other.

**Comment by shaneutt** [comment]
This is now all done with `make generate` :+1:
