### ISSUE TITLE
Ingress Controller keeps syncing new configs even when the configuration doesn't change

### ISSUE THREAD

**Issue by eduardoaemunoz** [Kong/kubernetes-ingress-controller#1399]
### Summary

My Ingress Controller is having a strange behaviour.

From time to time, the Proxy purges the cache:

```
2021/06/04 10:17:12 [notice] 22#0: *5917 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"
2021/06/04 10:17:12 [notice] 22#0: *5917 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"
127.0.0.1 - - [04/Jun/2021:10:17:12 +0000] "POST /config?check_hash=1 HTTP/1.1" 201 35612 "-" "Go-http-client/1.1"
2021/06/04 10:17:16 [notice] 22#0: *5986 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"
2021/06/04 10:17:16 [notice] 22#0: *5986 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"
127.0.0.1 - - [04/Jun/2021:10:17:16 +0000] "POST /config?check_hash=1 HTTP/1.1" 201 35677 "-" "Go-http-client/1.1"
2021/06/04 10:17:19 [notice] 22#0: *6020 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"
2021/06/04 10:17:19 [notice] 22#0: *6020 [lua] init.lua:260: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"
127.0.0.1 - - [04/Jun/2021:10:17:19 +0000] "POST /config?check_hash=1 HTTP/1.1" 201 35603 "-" "Go-http-client/1.1"
```

This triggers some syncing in the Ingress Controller :

```
time="2021-06-04T10:17:12Z" level=info msg="syncing configuration" component=controller
time="2021-06-04T10:17:12Z" level=info msg="successfully synced configuration to kong" component=controller
time="2021-06-04T10:17:16Z" level=info msg="syncing configuration" component=controller
time="2021-06-04T10:17:16Z" level=info msg="successfully synced configuration to kong" component=controller
time="2021-06-04T10:17:19Z" level=info msg="syncing configuration" component=controller
time="2021-06-04T10:17:19Z" level=info msg="successfully synced configuration to kong" component=controller
```

The thing is I haven't changed anything. 

Sometimes the syncing completes without any errors (or it doesn't sync at all, ie, `level=info msg="no configuration change, skipping sync to kong" component=controller`), so I can access my endpoint, sometimes the syncing is not correct, and I can't access my endpoint so I get:

```
curl -H "Authorization: Bearer $TOKEN" https://foo.bar/baz
{
  "message":"You cannot consume this service"
}
```

Why could this be happening? What info can I provide to help debug this problem?

Thank you in advance!

**Kong Ingress controller version**: 1.2

**Kong OSS**: 2.4

### Kubernetes version

**Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T12:01:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}**

**Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}**

**Comment by eduardoaemunoz** [comment]
I would also like to know how to increase the log level in the Ingress Controller.

I'm installing everything using the Helm chart, 

I pass this to Helm:

```
ingressController:
  installCRDs: false
  enabled: true
  image:
    repository: kong/kubernetes-ingress-controller
    tag: "1.2"
  args:
    - --v=3
```

I only get info level log messages now matter the `--v=aNumber`.

**Comment by jiachinzhao** [comment]
Hi, may be related to  [issue#1244](https://github.com/Kong/kubernetes-ingress-controller/issues/1244)

You can upgrade to 1.3.1 to do a test，if not solved,  try to dump config and compare differences

**Comment by eduardoaemunoz** [comment]
I've actually fixed the problem.

I was adding two Kong Plugin ACL (each allowing a Consumer to access a route) to a single Service; that was causing the syncs and was making the access random, ie, it appears only one of the ACL is used at a time.

I've reworked the two ACLs into a single ACL and access is now working as expected. Two Consumers can access the route, everything else can't.

**Comment by shaneutt** [comment]
Glad you were able to find a solution @eduardoaemunoz, do you think there's a lesson that we can take for the KIC here given your experience? At minimum it sounds like better errors or logging could have potentially been helpful in your own RCA here?

**Comment by eduardoaemunoz** [comment]
Unless I'm wrong, ie, you can have more than one Kong ACL per Service, then I think two things could be done:
* Clearly state this somewhere in the docs (if it is, I didn't find it)
* Maybe an error/warning message stating that when two ACLs are being defined in the same Service only one can be defined/will be used by KIC

**Comment by shaneutt** [comment]
Sounds good, would you be open to filing this as a separate bug report in your own words? Or would you prefer I do that?
