### ISSUE TITLE
Version tags use the `v` prefix inconsistently

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1411]
When reviewing the CI PR #1410, I've noticed that we don't use tags consistently:
- `v2.0.0-alpha.0` has the `v` prefix
-  `2.0.0-alpha.1` does not
- for 1.2.0 we have two tags: there is both `v1.2.0` and `1.2.0`
- `v1.1.1` has the `v` prefix
- `1.1.0` does not

Arguments for sticking to the `X.Y.Z` format:
- most of our past releases used this format

Arguments for sticking to the `vX.Y.Z` format:
- compatible with go modules

My suggestion would be that we choose one of the above going forward, and retroactively create tags in the chosen format for all past releases.

Deletion of the other tags would be debatable, with a strong counterargument that we'd break existing users who rely on those tags existing.

Acceptance criteria:
- [ ] pick one version format
- [ ] retroactively create tags for the chosen version format
- [ ] ensure that release docs explicitly specify the version format
- [ ] decide whether to delete tags in the other format and execute on that decision

**Comment by shaneutt** [comment]
We've moved to a consistent pattern where we use the `vx.x.x` for tags and releases since `v2`, which might be adequate? If we still feel we're missing something here or we need to make more retroactive changes let's re-open.
