### ISSUE TITLE
HEAD images for all branches go to a dedicated Docker registry

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1413]
We need a registry for development builds that will be populated with automatic builds for all branches (and will make it possible for maintainers to push a locally built development image thereto).

Acceptance criteria
- [ ] there exists a public Docker registry (with push access for maintainers and unrestricted pulling) called e.g. `docker.io/kong/kubernetes-ingress-controller-dev` for development images.
- [ ] for each branch (that is not master or main), CI pushes a railgun and a legacy image thereto

**Comment by shaneutt** [comment]
Closing as stale. We recently took the route of creating nightly builds which we use for testing new features, which may be sufficient for now? If not and we feel there's more to do here let's re-open.
