### ISSUE TITLE
Kong Ingress controller version 1.3.1 is not available on docker hub

### ISSUE THREAD

**Issue by krmichelos** [Kong/kubernetes-ingress-controller#1430]
### Summary

**Kong Ingress controller version: 1.3.1**

### What happened
This version appears to have failed to publish (as did 1.3.0) with an authorization failed.

https://github.com/Kong/kubernetes-ingress-controller/runs/2746348124#step:13:225

1.3.0 is available on docker hub, but I wonder if it was built and pushed from a system that had an older alpine 3.11 (3.11.6) since I would have expected a current build on a fresh system to have used alpine 3.11.11 for alpine 3.11.

### Expected behavior
For the publish to succeed

**Comment by mflendrich** [comment]
Thank you for this report! Indeed, there was a permissions problem with the robot user that performs pushes from our CI. The permissions problem got resolved before the weekend but this job was affected, never to be retried.

I have re-run the CI job and the push succeeded this time - 1.3.1 images are now available on Docker Hub.
