### ISSUE TITLE
Support custom entities attached to distinct stock entities in DB-less

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1433]
# New functionality

KIC provides a means to inject custom entities associated with a specific stock entity, such as a Kong service, route, or consumer, in DB-less mode, without prior knowledge of that stock entity's ID.

# Proposed implementation

We add a new annotation, `konghq.com/custom-entity-store`, which references a Secret or ConfigMap and a key within them. This annotation is available on Service, Ingress, and KongConsumer resources. The referenced Secret/ConfigMap key's value is a raw YAML blob. The controller injects this blob verbatim under the associated Kong service, route, or consumer derived from the Kubernetes resource. Validation of entities within the value is up to the user; invalid entities will prevent configuration from syncing.

# Background

Originally an internal request, FTI-2615.

Custom plugins can define custom entities with an arbitrary schema containing Kong DAO fields. The controller has no advance knowledge of these schemas, and thus we cannot define a CRD that provides a proper structured representation of their fields. Custom entities can include foreign key references to other DAO entities.

In DB-backed mode, we provide no support for custom entities within KIC, and instruct users to add them directly via the admin API. This is not an option in DB-less mode, however, as KIC must send all DB-less config in a single blob. To support custom entities in DB-less mode, we allow users [to provide a Secret containing arbitrary YAML](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/configuring-custom-entities/) (as of [0.9.0](https://github.com/Kong/kubernetes-ingress-controller/pull/630)), and trust them to correctly define custom entities added by their plugins. This YAML is appended to the end of the DB-less configuration KIC generates.

Because the YAML blob is appended to the end of the entire generated configuration, it is only suitable for custom entities that do not reference other Kong entities. To reference other Kong entities, users would need to know the entity ID in advance and include an appropriate reference in their custom entity YAML. KIC's generated configuration does not include entity IDs and does not allow users to provide their own IDs (with the exception of CA certificates), allowing Kong to randomly generate IDs when it ingests the config blob. We do not want to add support for user-defined IDs to additional entities because they are cumbersome to manage.

Thus, to properly support custom entities with foreign key references, we need to provide a means to inject their YAML blob under the stock entity in our generated configuration, rather than only injecting top-level custom entities.

# Future work

We may want to explore adding a CRD for custom entities that supports both DB-backed and DB-less mode. Although adding entities to the API directly in DB-backed mode does work, it's at odds with how we normally have users manage configuration with KIC. Though we cannot know entity schemas in advance and would need to include a raw JSON field to contain the entity, we could include minimal scaffolding to indicate the custom entity's API endpoint (which is also effectively its object path in declarative YAML) and any foreign object references it has.

**Comment by shaneutt** [comment]
Is this issue something we could translate into a new or existing KEP? :thinking:

**Comment by rainest** [comment]
Revisiting this and thinking about implementation options. While arbitrary YAML blob from annotation does allow users to provide (hopefully valid) custom entities in the context of a specific K8S resource, we can't simply shove that inside the serialized Kong entity YAML we generate from it.

The path to serialization is generate a Kong entity struct from the K8S resource struct, transform that Kong struct into its decK file equivalent, and then marshal JSON or YAML from the decK file struct. Custom DAOs effectively let you extend standard Kong entity schemas to add new fields, and that presents a challenge for Go struct marshaling: we have no idea what those fields will be at code/compile time, and there's not really an obvious way to shove them in. If you want something like:

```
services:
  name: foo
  graphql-rate-limiting-advanced:
    costs:
    - type_path: Query.allPeople
      mul_arguments: first
    - mul_arguments: first
      add_constant: 42
```
you can't really get there from marshaling [the decK file service struct](https://github.com/Kong/deck/blob/46b074e8a24541c30834e5160b310ff737a2e548/file/types.go#L55-L78): there is no `GraphQLRateLimitingAdvanced` field that marshals into `graphql-rate-limiting-advanced`. I don't think there's a good way to either dynamically extend the struct or a good way to marshal the standard struct and then smush the additional user content as a `byte[]` onto it. The latter seems maybe more viable, but may be kludgy--it'd possibly need a custom JSON marshaler, which IIRC aren't fun.

Furthermore complicating things is that we don't marshal those structs individually, we marshal a decK `file.Content` that contains slices of each, so we don't really have a good way to insert content into the individual structs within.

**Comment by mflendrich** [comment]
Requires further design work based on considerations above. A design spike looks like a reasonable next step.

**Comment by mflendrich** [comment]
Won't fix now - please comment if interested in this feature.
