### ISSUE TITLE
Credential tags cannot be set from k8s secrets

### ISSUE THREAD

**Issue by raptium** [Kong/kubernetes-ingress-controller#1437]
### Summary

**Kong Ingress controller version**
1.3.1

**Kong or Kong Enterprise version**
2.4

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"2cbb16c", GitTreeState:"", BuildDate:"2021-01-27T02:20:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: Aliyun
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened

Create k8s secret with the following

```
kubectl create secret \
  generic app-jwt \
  --from-literal=kongCredType=jwt \
  --from-literal=key="jwt-issuer" \
  --from-literal=algorithm=HS256 \
  --from-literal=secret=... \
  --from-literal=tags=tag1
```

This secret cannot be synced to Kong as credential because `Tags` is a slice however secret data values are strings.

Work around for `redirect_uris` is here:

https://github.com/Kong/kubernetes-ingress-controller/blob/91a3ea530ffdf7ea5a291237f80fbbe16b80e55c/pkg/kongstate/kongstate.go#L86 

The **TODO** has to be done or we need another work around for `tags` as well.

### Expected behavior

Tags can be synced from k8s secret to Kong credentials.

**Comment by mflendrich** [comment]
To be implemented in https://github.com/Kong/kubernetes-ingress-controller/issues/2419
