### ISSUE TITLE
kong-validation-webhook is deployed but not used in all-in-one-dbless

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [Kong/kubernetes-ingress-controller#1438]
From what I've understood, webhook is optional and deployable with a script
https://github.com/Kong/kubernetes-ingress-controller/blob/d8f58ead71664b042c854c1a3e429fe95f17eb24/hack/deploy-admission-controller.sh

By default, `all-in-one-dbless` deploys the Service for a webhook but not a webhook itself. I think deploying a Service should be moved to `deploy-admission-controller.sh`

Acceptance criteria
- [ ] Deploy manifests that do not run the webhook do not deploy its service.

**Comment by mflendrich** [comment]
Closing - we're going to deprecate `all-in-one` manifests & Kustomize in favor of Helm and KGO (#4712)
