### ISSUE TITLE
UDP & TCP Ingress - Service Upstream Annotation

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1441]
The purpose of this issue is to add support for the following annotation to the `TCPIngress` and `UDPIngress` APIs:

```
"ingress.kubernetes.io/service-upstream": "true"
```

As per the [documentation for this annotation][annodoc] the purpose of it is to allow optionally disabling `kong.Upstream` handling of DNS & Ports for `kong.Service`s which are built by the KIC and instead allow the proxy to use the Kubernetes Service DNS directly.

[annodoc]:https://docs.konghq.com/kubernetes-ingress-controller/1.2.x/references/annotations/#ingresskubernetesioservice-upstream

Acceptance Criteria:
- [ ] add support for `service-upstream` to `TCPIngress`
- [ ] add support for `service-upstream` to `UDPIngress`
- [ ]  update the resources in `test/integration/collision_test.go` tests to enable this flag in order to work around `kong.Upstream`
- [ ] expand the tests in `test/integration/collision_test.go` to do full validation of the resulting UDP and TCP routes
- [ ] (possibly?) consider adding automation which identifies when two listeners with different protocols are sharing a port, and enabling this automatically under that scenario
- [ ] if we decide to do the above, we need to make sure we add documentation that explains when that happens and why

**Comment by rainest** [comment]
FYI this annotation actually goes on the Service, not the ingress-like pointing to it: https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/references/annotations/#service-resource

The annotation does _not_ go on (TCP/UDP)Ingress, only the Services they point to. The first task here is to verify whether pointing a TCPIngress or UDPIngress to a Service with `ingress.kubernetes.io/service-upstream` results in a route pointing to a Kong service whose upstream contains only the Service hostname in its targets.

Intuitively, this should work already--processing of Services is largely independent of Ingress-like processing, and the routes are loosely-coupled to them. Generated services largely shouldn't care what type of Ingress-like is pointing to them.

If this does in fact _not_ work, then we need to fix something. If it already works, there's nothing to do.

**Comment by shaneutt** [comment]
ran this through a debugger to be sure, the annotation is being used for `UDPIngress` and `TCPIngress` in `v2.2.1` :+1:
