### ISSUE TITLE
Failed recreating loadbalancer after few days when pods running

### ISSUE THREAD

**Issue by tzarky** [Kong/kubernetes-ingress-controller#1443]
### Summary

We have been using kong on our production clusters for a while. When we only had 20% of our applications we had no problems. 

We recently migrated the rest of our workload and since then we've had an error on part of our kong replica:

```
failed recreating balancer for app.namespace.80.svc: timeout waiting for balancer for a9a7385e-ad84-474e-9b1c-2....
```

To "solve" this problem, we are forced to restart the pod that returns this error.

Unfortunately if we don't manage to detect the problem quickly enough, all the pods end up having the error and we have 100% of our traffic interrupted.

We did not notice any excessive RAM consumption on the pods and no other errors were returned by the pod before the error below.

**Kong Ingress controller version**

We using helm chart version : `2.1.0`

image.tag : `2.4`
ingressController.image.tag : `1.3`

**Kong or Kong Enterprise version**

Kong

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"4d62230f10af41cec2851b5b113874f6d2098297", GitTreeState:"clean", BuildDate:"2021-03-22T23:01:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider**: AKS
- **Install tools**: Helm
- **Others**: Kong in DB mode Postgresql

### Steps To Reproduce

We can't find a reliable way to reproduce.

**Comment by shaneutt** [comment]
Closing as stale as there's not been any activity on this issue for a long time. If this issue is still an active problem on modern supported versions of the ingress controller (2.2 is the latest at the time of writing) please comment here and let us know what versions you're experiencing this problem on and we'll be happy to re-open and re-assess.
