### ISSUE TITLE
Proactive & dynamic controller enable/disable for 3rd party CRDs

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1449]
Currently we have some logic which adds goroutines that will scan for changes in CRDs to dynamically enable controllers (see the Knative Ingress controller in `railgun/manager/run.go`) the purpose of this issue is to extend and harden this behavior to be generic and cover multiple third party types, as well as making it easy to add new types later.

Acceptance Criteria:
- [ ] interface (or perhaps function type if preferable) added to describe the behavior of an asynchronous process which monitors CRDs and enables/disables controllers according to their prescense.
- [ ] integration tests which prove the dynamic loading/unloading of types and the relevant controllers.

**Comment by rainest** [comment]
Do we expect that we would need this in practice? While we definitely want #1448 to reduce the burden of manual configuration, requiring a controller restart to change the loaded controller set seems fine, as it shouldn't change often. I wouldn't expect users to install Knative (or similar), uninstall, reinstall, and repeat while KIC is running, but rather have a one-off event where they install Knative for the first time, restart KIC to load its controller, and then continue using Knative indefinitely after.

**Comment by shaneutt** [comment]
> Do we expect that we would need this in practice? While we definitely want #1448 to reduce the burden of manual configuration, requiring a controller restart to change the loaded controller set seems fine, as it shouldn't change often. I wouldn't expect users to install Knative (or similar), uninstall, reinstall, and repeat while KIC is running, but rather have a one-off event where they install Knative for the first time, restart KIC to load its controller, and then continue using Knative indefinitely after.

It's a good question: I made this issue as a follow up to some functionality that was added for Knative, but the purpose of this issue could just as easily become to remove that functionality if we have consensus that we're not looking to have that kind of functionality. cc @ccfishk for your thoughts?

**Comment by shaneutt** [comment]
Moving to POST KIC 2.0 as this is a new feature and not something needed for 1.x parity (in 1.x the controller would need to be restarted to add new API support).

**Comment by shaneutt** [comment]
https://github.com/Kong/kubernetes-ingress-controller/pull/1479 provides some ideas about how to do this.

**Comment by mflendrich** [comment]
Moving to "not groomed" because we don't seem to have alignment about whether this feature is a net positive or not.

**Comment by shaneutt** [comment]
> Moving to "not groomed" because we don't seem to have alignment about whether this feature is a net positive or not.

For posterity, but also so I'm personally clear can we add some quantification of what contention, or what conversations have transpired that we need to resolve? Up until this moment I had every expectation that all of @Kong/team-k8s was on board with this (my misunderstanding, perhaps).

**Comment by mflendrich** [comment]
> what contention, or what conversations have transpired that we need to resolve?

Comments https://github.com/Kong/kubernetes-ingress-controller/issues/1449#issuecomment-867132409 and https://github.com/Kong/kubernetes-ingress-controller/issues/1449#issuecomment-867645807 seem to indicate that we don't have confidence in the purpose of this feature.

**Comment by mflendrich** [comment]
Closed as won't fix because we won't have resources to get this done in the foreseeable future.
