### ISSUE TITLE
Use different namespace in all-in-one.yaml example

### ISSUE THREAD

**Issue by chlung** [Kong/kubernetes-ingress-controller#145]
SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.14.1 CE

**Kong or Kong Enterprise version**
0.14.1 CE

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: Mac
- **OS** (e.g. from /etc/os-release): MacOS 10.12.6
- **Kernel** (e.g. `uname -a`): Darwin 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64
- **Install tools**: kubectl create -f
- **Others**:

### What happened
I download the all-in-one.yaml for minikube.  First, I try the default kong namespace per example.  Then, I change namespace from "kong" to "my-test".  The kong-ingress-constroller is failed.

kong-85f56dd6c7-9xxjf                      1/1       Running            2          19m
kong-ingress-controller-648979bd76-4xhqp   1/2       CrashLoopBackOff   8          19m
postgres-0                                 1/1       Running            0          19m

I observe all containers, and I notice this error.

$ kubectl -n my-test logs kong-ingress-controller-648979bd76-4xhqp ingress-controller
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.2.0
  Build:      git-de9e38c6
  Repository: git@github.com:Kong/kubernetes-ingress-controller.git
-------------------------------------------------------------------------------

W0926 22:50:09.055476       6 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0926 22:50:09.055779       6 main.go:204] Creating API client for https://10.96.0.1:443
I0926 22:50:09.065632       6 main.go:248] Running in Kubernetes Cluster version v1.10 (v1.10.0) - git (clean) commit fc32d2f3698e36b93322a3465f63a14e9f0eaead - platform linux/amd64
F0926 22:50:09.068460       6 main.go:92] no service with name kong/kong-proxy found: services "kong-proxy" not found
### Steps To Reproduce
Test it in minikube, but the same issue in CentOS as well.
1. change all-in-one.yaml "namespace: kong" to "namespace: my-test" 
2. deploy the all-in-one.yaml
3. Check ingress-controller container log

Thanks.

**Comment by angelshila** [comment]
I can confirm this works. Not sure why it's not working for you.  

Please make sure you change namespace's value wherever it's applicable and also, make sure your references are correct.

**Comment by chlung** [comment]
Look like service path need to updated as well.  Thanks.
