### ISSUE TITLE
Update Knative Ingress condition and status after kong configuration update.

### ISSUE THREAD

**Issue by ccfishk** [Kong/kubernetes-ingress-controller#1450]
What this PR does / why we need it:
what:
Update Knative ingress status and condition after sync status to kong successfully

Why:
Knative CR status is completed in KIC 1.3.0. Need migrate it to KIC 2.0

Checklist
Complete these before marking the PR as ready to review:

 the CHANGELOG.md release notes have been updated to reflect any significant (and particularly user-facing) changes introduced by this PR
 Continuation Test including dbless, postgress and legacy all pass.

**Comment by rainest** [comment]
Closed by #1451
