### ISSUE TITLE
Bug: KIC 2.0 CTRL MGR starts with errors without Knative CRD

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1466]
After https://github.com/Kong/kubernetes-ingress-controller/pull/1396 merged we now have a problem where the controller manager can not start properly unless the Knative CRD is present, even if `--controller-knativeingress=disabled` is set. CI has been working because we preempt the tests by deploying the CRD.

Reproduction:

Create a new test cluster:

```
make test.integration.cluster
```

Pull the current HEAD of `next` and run the following (`${URL}` needs to be set to your own Admin API):

```
go run main.go manager --kong-admin-url ${URL} --kubeconfig /home/shane/.kube/config --controller-knativeingress=disabled
```

The resulting errors occur in the manager logs:

```
E0630 09:17:49.756572  680534 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Ingress: failed to list *v1alpha1.Ingress: the server could not find the requested resource (get ingresses.networking.internal.knative.dev)
```

Acceptance Criteria:
- [ ] running the controller locally on a cluster _without_ any Knative CRDs present should result in success

**Comment by rainest** [comment]
What failure did you see with this? I did notice that https://github.com/Kong/kubernetes-ingress-controller/blob/78a73e77d13c28b716fc24a4c2cd7f97caa3a284/railgun/manager/run.go#L286-L288 appeared incorrect, as it would override the flag value to enabled, but it would only do so if the Knative CRDs were available--it looks like it should be fine if the CRDs are absent and the controller flag is set to disabled.

Though #1458 does rework that check, CI will still include the Knative stuff, so it still wouldn't check this issue.

**Comment by shaneutt** [comment]
> What failure did you see with this? I did notice that
> 
> https://github.com/Kong/kubernetes-ingress-controller/blob/78a73e77d13c28b716fc24a4c2cd7f97caa3a284/railgun/manager/run.go#L286-L288
> appeared incorrect, as it would override the flag value to enabled, but it would only do so if the Knative CRDs were available--it looks like it should be fine if the CRDs are absent and the controller flag is set to disabled.
> 
> Though #1458 does rework that check, CI will still include the Knative stuff, so it still wouldn't check this issue.

This is the failure I see:

```
E0630 09:17:49.756572  680534 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Ingress: failed to list *v1alpha1.Ingress: the server could not find the requested resource (get ingresses.networking.internal.knative.dev)
```

I rebased against #1458 but this does not correct the problem. I'm going to take this one and get it fixed real quick.

**Comment by ccfishk** [comment]
Knative CRD is already cleaned up from current KIC repo. All the CI test cases pass are based on CTR Manager is able to up and function as expected. 

If we disable Knative CRD, I don't believe we can see the reflector error message. 
This bug descriptive is very unclear : how do you bump the KIC either locally or deploy as an image. Should input more details

**Comment by shaneutt** [comment]
> Knative CRD is already cleaned up from current KIC repo.

I'm not sure what is meant by this, can you please help me to better understand?

> All the CI test cases pass are based on CTR Manager is able to up and function as expected. If we disable Knative CRD, I don't believe we can see the reflector error message.

We don't disable/enable the Knative CRD _at all_, just the controller, is that what is meant here? The proposed changes in #1468 (still a draft at the time of writing) only disable the controller if the cluster does not have the CRD present, which is desired the current behavior will be broken in production systems that don't use `knative.Ingress`.

> This bug descriptive is very unclear : how do you bump the KIC either locally or deploy as an image. Should input more details.

Sorry that the description is not clear enough, I have added more details on how to specifically re-create the problem let me know if that reads better to you :bow:

**Comment by ccfishk** [comment]
The following error message displays when CRD does not exist in cluster, and the controller can be up and work as expected,  how could this be a bug ? I am totally confused. 

E0630 09:17:49.756572  680534 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Ingress: failed to list *v1alpha1.Ingress: the server could not find the requested resource (get ingresses.networking.internal.knative.dev)

Could you please clarify which part does not work other than an error message ?

**Comment by shaneutt** [comment]
> The following error message displays when CRD does not exist in cluster, and the controller can be up and work as expected, how could this be a bug ? I am totally confused.
> 
> E0630 09:17:49.756572 680534 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Ingress: failed to list *v1alpha1.Ingress: the server could not find the requested resource (get ingresses.networking.internal.knative.dev)
> 
> Could you please clarify which part does not work other than an error message ?

That's it, the error message is the problem.

**Comment by ccfishk** [comment]
Well, I believe you need understand the error message introduced by following checkin which is introduced by PR merge 

https://github.com/Kong/kubernetes-ingress-controller/pull/1458/files#diff-777c5b378220515f6b692537382429104081d22a761062c7e2f0919e6c0d1757L150

The original PR purposedly disable knative environment variable to avoid any confusion.
https://github.com/Kong/kubernetes-ingress-controller/pull/1396

**Comment by rainest** [comment]
@shaneutt does this still need to remain open. Not clear if the final version of #1458 fixed it or something else did, but current next does start up without Knative CRDs and emits the expected "it's not here, disable the controller" log:

https://gist.github.com/rainest/00fa2661752d8e83deadf8349ec536ec

**Comment by shaneutt** [comment]
> @shaneutt does this still need to remain open. Not clear if the final version of #1458 fixed it or something else did, but current next does start up without Knative CRDs and emits the expected "it's not here, disable the controller" log:
> 
> https://gist.github.com/rainest/00fa2661752d8e83deadf8349ec536ec

Nope looks like this is accounted for now and we can close thing.
