### ISSUE TITLE
Railgun integration test flakiness

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1482]
De-flake the integration test.

Known best ways to analyze flakiness:
- run the test multiple time (takes hours due to no parallelization): `env GOFLAGS="-tags=integration_tests"  go test ./railgun/test/integration -v -count=100`
- scrape historical GitHub Actions job logs for failures using the script implemented in #1383 

At the moment of writing, there is demonstrable flakiness in the integration test: https://github.com/Kong/kubernetes-ingress-controller/pull/1481/checks?check_run_id=2963346396

**Comment by mflendrich** [comment]
another instance - on a PR that changes none of the code: https://github.com/Kong/kubernetes-ingress-controller/runs/3066783657?check_suite_focus=true

**Comment by shaneutt** [comment]
These flakes have since been gone for several iterations, we can re-open this if we see problems crop back up.
