### ISSUE TITLE
DNS resolution failed: dns lookup pool exceeded retries (1): timeout. Tried

### ISSUE THREAD

**Issue by pinguo-yangbing** [Kong/kubernetes-ingress-controller#1485]
I used Kubernetes-Ingress-Controller 1.3.1, Kong Gateway2.4.1, and used the Go plugin on the service. Kong.Service.SetTarget(Servicename.Namespace, 8000) is used in the plugin.
Error:

2021/07/03 16:57:18 [error] 28#0: *7004 [lua] balancer.lua:1036: execute(): DNS resolution failed: dns lookup pool exceeded retries (1): timeout. Tried: ["(short)test-model-v100.ai-platform:(na) - cache-miss","test-model-v100.ai-platform.kong.svc.cluster.local:33 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform.svc.cluster.local:33 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform.cluster.local:33 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform:33 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform.kong.svc.cluster.local:1 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform.svc.cluster.local:1 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform.cluster.local:1 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform:1 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform.kong.svc.cluster.local:5 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform.svc.cluster.local:5 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform.cluster.local:5 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout","test-model-v100.ai-platform:5 - cache-miss/scheduled/querying/try 1 error: timeout/scheduled/querying/try 2 error: timeout/dns lookup pool exceeded retries (1): timeout"], client: 192.168.65.6, server: kong, request: "GET /model/test-model/ddd HTTP/1.1", host: "xxxx.xxxx.com"

**Comment by rainest** [comment]
These timeout errors indicate that the Kong proxy is not receiving responses to its DNS lookup requests from the cluster DNS server. Can you confirm that your cluster DNS is functioning normally, and that there are no cluster network rules that would drop that traffic for some reason?
