### ISSUE TITLE
Rewrite status handling

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1492]
(this is partially a follow up to this discussion: https://github.com/Kong/kubernetes-ingress-controller/pull/1451#discussion_r664824300)

There are some fundamental problems with the current implementation of status handling, including:

- general code maintenance problems
- race conditions and edge cases around how status updates are performed
- loose associations between kong routes and Kubernetes objects requiring lots of guesswork 

The purpose of this issue is to re-write how status handling works, ideally as a controller based mechanism which causes the resources to become enqueued and resolved.

# Prerequisites

- [x] https://github.com/Kong/kubernetes-ingress-controller/issues/2295

**Comment by mflendrich** [comment]
blocked on #2007

**Comment by shaneutt** [comment]
blocked on https://github.com/Kong/kubernetes-ingress-controller/issues/2295
