### ISSUE TITLE
Oauth2 credentials without Name field result in segfault

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1505]
Oauth2 credentials with no `name` field are [accepted by KIC's credential validation](https://github.com/Kong/kubernetes-ingress-controller/blob/1.3.1/pkg/kongstate/credentials.go#L124-L134). They are not accepted by decK's libraries, and their omission [will result in a segfault](https://github.com/Kong/deck/blob/v1.7.0/state/types.go#L929). The field is required in the [Kong plugin DAO](https://github.com/Kong/kong/blob/2.4.1/kong/plugins/oauth2/daos.lua#L33) and we should ensure that it is present in KIC.

**Kong Ingress controller version**
 ingress-controller - 1.2

**Kong or Kong Enterprise version**
Any.

### What happened
KIC crashed.

### Expected behavior
KIC does not crash.

### Steps To Reproduce

1. Create an Oauth2 credential with no name field.
2. Watch KIC crash.

See original report in https://github.com/Kong/kong/issues/7517 for additional details.

To fix, we need to add a new clause to `NewOauth2Credential()` which returns an error if `res.Name` is not set, similar to the existing clause for `res.ClientID`.

**Comment by ccfishk** [comment]
The original report specifies controller version 1.2. update accordingly.
