### ISSUE TITLE
[bug] Test Coverage Merge & Report

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1532]
Currently we have test coverage being sent multiple times from different CI runs (Unit vs Integration) to https://codecov.io on every PR, which means that Codecov can report things before everything is finished or otherwise make a lot of noise.

The purpose of this task is to look into collecting all coverage in CI in the artifact store instead of pushing it to codecov up front, and adding a final CI task that combines and pushes all combined coverage to codecov at once.

Acceptance Criteria:
- [ ] coverage pushed to Github Actions Artifactory instead of codecov on test completion
- [ ] Github Action added to merge and submit coverage after all other CI tasks have finished
- [ ] Demonstrate that codecov now reports in a cleaner more consistent fashion
- [ ] CI should be 100% green for this YAML only change

**Comment by mflendrich** [comment]
this is already done:

https://github.com/Kong/kubernetes-ingress-controller/blob/ff14ea33e8f3128caa46596a75759a528b530d02/.github/workflows/test.yaml#L208
