### ISSUE TITLE
Test KIC against multiple k8s versions

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1542]
Problem statement: We need to commit to some quality level for versions of k8s that we consider "supported".

Proposed solution: Define a "supported" major.minor k8s version to be one, for which at least one patch version is covered by the automated integration tests. We can leverage KTF support for environments for that purpose.

Separated out from #1095

Acceptance criteria:
- [ ] For an array of `major.minor.patch` or `major.minor.<latest-patch>` versions, CI tests run against each

**Comment by shaneutt** [comment]
@mflendrich I changed the AC: I'm intending to target ALL pushes to `main` and `next` and have it so that releases can't be cut from these branches until CI is :heavy_check_mark:
