### ISSUE TITLE
Kubernetes Ingress using self signed certificated instead of cert manager certificate

### ISSUE THREAD

**Issue by devils-ey3** [Kong/kubernetes-ingress-controller#1561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My Kong APIGW uses a self-signed certificate instead of using the cert-manager generated certificate.
From the documentation I use below annotations 

```
    annotations = {
      "kubernetes.io/ingress.class"                           = "kong"
      "kubernetes.io/tls-acme"                                = "true"
      "certmanager.k8s.io/cluster-issuer"                     = "le-clusterissuer"

    }
```
![image](https://user-images.githubusercontent.com/12210908/125963174-5f28fc72-515e-4843-98a0-1f0ed681a9a0.png)

I have pushed the cert certificate by using the kong admin API but it still using self-signed certificate. 

The ingress controller is attached to a **classic load balancer** in AWS. 

### Expected Behavior

By using those annotations, kong gateway should use valid SSL certificate. 
![image](https://user-images.githubusercontent.com/12210908/125964409-698c9bcb-abe4-426d-823e-faac73fc7b8d.png)

### Kong Ingress Controller version

```shell
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    1.1.1
  Build:      ba4eea9
  Repository: git@github.com:Kong/kubernetes-ingress-controller.git
  Go:         go1.15.3
-------------------------------------------------------------------------------
```

### Kubernetes version

```shell
1.19
```

**Comment by rainest** [comment]
Can you show the entire Ingress? Has cert-manager successfully provisioned the certificate and added a matching `tls:` block to the Ingress spec? The controller won't do anything with the cert-manager annotations itself; it can only parse the standard Ingress TLS configuration block. cert-manager _should_ add that though.
