### ISSUE TITLE
Lint for Golang error wrapping

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We have a standard set in the codebase currently to "wrap" errors when producing them with `fmt.Errorf` from the standard library, as such:

```go
err1 := fmt.Errorf("failed because the computer wanted to take a nap instead")
err2 := fmt.Errorf("Error: could not save the planet: %w", err1)
```

However we often end up trying to enforce this standard manually in PR reviews.

### Proposed Solution

- implement a linter (existing OR new) that checks that errors provided as arguments to `fmt.Errorf` are properly wrapped
- add the linter to our CI configuration (ideally, as a linter loaded into `golangci-lint`)

### Acceptance Criteria

- [ ] as a maintainer PRs can't be merged if there are inconsistent error wrappings present in the diff

**Comment by ccfishk** [comment]
Golang has clear definition about the wrapper method which we need just to follow
https://pkg.go.dev/fmt#pkg-functions
https://cs.opensource.google/go/go/+/refs/tags/go1.16.6:src/fmt/errors.go;l=17

**Comment by mflendrich** [comment]
There seems to be a linter like that in existence:
https://github.com/polyfloyd/go-errorlint
