### ISSUE TITLE
better sync cluster ingress(es) deletion to kong admin api/proxy

### ISSUE THREAD

**Issue by ccfishk** [Kong/kubernetes-ingress-controller#1581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

When user delete an ingress from the cluster, its route capabilities should be disabled from proxy also.
   Observed empty KongState object (service, upstream, certification etc are empty) generated by Parse.Build() function though ingress objects do exist in the cluster, which should not happen.

### Proposed Solution
   Need triage, come up reproducible steps. Based on that, provide fix.

**Comment by shaneutt** [comment]
> When user delete an ingress from the cluster, its route capabilities should be disabled from proxy also.

If I'm understanding the problem statement here correctly the problem is:

1. delete an `Ingress` resource
2. routing via the proxy does not get removed

However in several of our existing integration tests which are consistently passing, we specifically do teardown tears which check this:

https://github.com/Kong/kubernetes-ingress-controller/blob/main/railgun/test/integration/ingress_test.go#L128

So it seems the problem statement here is contradicted by the tests, is there something more than I'm missing?

**Comment by ccfishk** [comment]
This issue was tracking empty KongState object generated by Parse.Build() function, which still should not happen.
 Because of the Proxy config "last win" mechanism, one empty KongState could be also used to sync Proxy, which is a valid case.
Still need investigate locate the KongState.

**Comment by shaneutt** [comment]
> This issue was tracking empty KongState object generated by Parse.Build() function, which still should not happen.

Understood, but for clarity: an empty KongState _is valid_ when the cache is empty (e.g. all relevant cluster components are deleted).

> Because of the Proxy config "last win" mechanism, one empty KongState could be also used to sync Proxy, which is a valid case.
> Still need investigate locate the empty KongState.

If we've got some place _other_ than the `Proxy` implementation where we're POSTing new `/config` updates, this would be a major problem. The implementation of `internal/proxy/clientgo_cached_proxy_resolver.go` was intended to make these updates synchronous and serial if you find that this is broken or that we're doing asynchronous updates elsewhere then please do mark this issue as `severity/high` and lets get that fixed. :fearful:

**Comment by ccfishk** [comment]
Dont have concrete data for this issue atm. close it atm. will re-open if have new findings.
