### ISSUE TITLE
Container Images for 2.0

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Image builds for 2.x were disabled during the teardown of 1.x temporarily so as to separate them into their own scope.

We need to add the image builds back before the beta release.

### Proposed Solution

- [x] add a distroless image build
- [x] configure image builds at the end of the release workflow

### Additional information

Internal discussions among maintainers seemed to indicate that alpine and UBI images may be OK to stop building given lack of usage.

### Acceptance Criteria

- [x] users have access to a standard KIC 2.0 image (distroless)

**Comment by mflendrich** [comment]
What is "standard" and how is it different from "alpine-based"?

For 1.x, the "1.x.y" tag has been merely an alias for "1.x.y-alpine".

**Comment by shaneutt** [comment]
> What is "standard" and how is it different from "alpine-based"?
> For 1.x, the "1.x.y" tag has been merely an alias for "1.x.y-alpine".

It was redundant, description updated :+1:

**Comment by shaneutt** [comment]
Description cleaned up with recent changes in direction, follow up is now https://github.com/Kong/kubernetes-ingress-controller/issues/1653
