### ISSUE TITLE
Knative ingress tests don't work on GKE

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our knative ingress tests do not complete successfully against a GKE cluster (as provided by the [KTF](https://github.com/kong/kubernetes-testing-framework)).

### Expected Behavior

The tests should pass on a GKE backed cluster.

### Steps To Reproduce

```markdown
1. create a GKE based cluster
2. run the Knative tests against the cluster
```

### Kong Ingress Controller version

```shell
v2.0.0-alpha.2
```

### Kubernetes version

```shell
v1.21.7
```

**Comment by ccfishk** [comment]
@shaneutt  Is this an ingress create/config/update failure, or Knative CRD/CR deployment failure ?

**Comment by shaneutt** [comment]
> @shaneutt Is this an ingress create/config/update failure, or Knative CRD/CR deployment failure ?

This seems to be specific to how we do our tests, but not necessarily a failure to deploy knative. I assume we just need to make our test slightly more generic and it will work, I would expect only small changes needed to get this working.
