### ISSUE TITLE
kong ingress seems case sensitive

### ISSUE THREAD

**Issue by ly123-liu** [Kong/kubernetes-ingress-controller#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

kong ingress seems case-sensitive , can kong ingress support case-sensitive like nginx (~*) can match uri with upper or lower words

example:
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: common-rewrite
  namespace: test
config:
  replace:
    uri: '/$(uri_captures[1])/$(uri_captures[2])'
plugin: request-transformer

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-kong-ingress-internal-v1
  namespace: test
  annotations:
    kubernetes.io/ingress.class: "test-kong-ingress"
    konghq.com/plugins: common-rewrite
spec:
  rules:
  - http:
      paths:
      - path: /(test)/v1/(.*)
        backend:
          serviceName: test
          servicePort: 8080

want above ingress can support /test/v1/check or  /Test/v1/check , but upstream just sees /test/v1/check ,  can kong ingress do that ?

found some issue in kong ,says kong api can do that : https://discuss.konghq.com/t/uri-matching-for-an-api/349/2

since we use kong ingress + kong gateway in k8s,  are there some way in kong ingress  or kong plugin can do that ?  thanks

**Comment by rainest** [comment]
Standard route paths in Kong are case-sensitive and there's no dedicated toggle to make them case-insensitive.

As mentioned in that forum thread, regular expression paths will be your best option. Rules are automatically parsed as regular expressions if they contain any characters outside the standard characters allowed in HTTP paths: https://docs.konghq.com/gateway-oss/2.4.x/proxy/#using-regexes-in-paths

Per that thread, the `(?i)` modifier (or other [PCRE modifiers](https://www.regular-expressions.info/modifiers.html)) should work within the expression. If that doesn't appear to be the case you'll want to file a [Kong issue](https://github.com/Kong/kong/issues) instead (the controller just passes whatever path you provide to Kong and doesn't perform route matching itself) to either investigate why the modifier isn't recognized or set case sensitivity elsewhere (there's an [option in the underlying library we use to match regexes](https://github.com/openresty/lua-nginx-module#ngxrematch), but we don't expose it in route configuration).
