### ISSUE TITLE
Should preserve_host default to true?

### ISSUE THREAD

**Issue by bspaans** [Kong/kubernetes-ingress-controller#163]
I'm trying to use cert-manager with kubernetes-ingress-controller and ran into the following issue: https://github.com/jetstack/cert-manager/issues/958

tl;dr: It almost works, but since Kong does not preserve the hostname by default the ACME challenge 
ultimately fails. 

There are some workarounds for this (see also #162), but I suppose this is a subtle difference between the Kong and nginx ingress controllers, and I wonder if this should default to true to make this controller a full drop-in replacement?

**Comment by hbagdi** [comment]
Since we are tracking this in #162, I'll close this.
