### ISSUE TITLE
docs: update the version compat matrix for KIC 2.0

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1652]
- [x] Ensure that the version compatibility matrix is updated for KIC 2.0.

**Comment by shaneutt** [comment]
Resolved by https://github.com/Kong/docs.konghq.com/pull/3081

**Comment by shaneutt** [comment]
This is resolved in that the documentation is written, but there is a follow up for the final merge to `main`: https://github.com/Kong/kubernetes-ingress-controller/issues/1719

**Comment by mflendrich** [comment]
Blocked on https://github.com/Kong/kubernetes-ingress-controller/issues/1683

Close this only after:
- the blocker (1.22 tests) has been resolved
- the 1.22 row has been added to the compat matrix

**Comment by rainest** [comment]
Tentatively added the new table row: https://github.com/Kong/docs.konghq.com/pull/3099/commits/2b4b23abea5b9a99edd10a69da2f94175c7e9424

**Comment by shaneutt** [comment]
Preview is working properly, 1.22 available for 2.0.0 (but not earlier): https://deploy-preview-3099--kongdocs.netlify.app/kubernetes-ingress-controller/2.0.x/references/version-compatibility/

**Comment by mflendrich** [comment]
Done
