### ISSUE TITLE
UBI Image

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Some end-users need Redhat compliant images for all components, so our `distroless` based images will not suffice. The purpose of this task is to add UBI images for these environments.

### Proposed Solution

- [ ] implement UBI image builds
- [ ] make UBI image build and push a part of our release workflow

### Acceptance Criteria

- [ ] as an end-user on Redhat systems I have a compliant UBI image to deploy the KIC to my OpenShift clusters

**Comment by rainest** [comment]
Handled in https://github.com/Kong/kubernetes-ingress-controller/pull/1921
