### ISSUE TITLE
Run upgrade tests after beta cut

### ISSUE THREAD

**Issue by ccfishk** [Kong/kubernetes-ingress-controller#1655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We have breaking changes in 2.0, user would have broken controller after upgrade.

### Proposed Solution

We need ensure there is no regression when user upgrade from 1.3 to 2.0
Run upgrade tests against beta
Run upgrade tests against Kong ee

**Comment by ccfishk** [comment]
duplicate. close as it is.

**Comment by shaneutt** [comment]
> duplicate. close as it is.

im confused by this comment: which issue does this duplicate?

**Comment by shaneutt** [comment]
Oh, its https://github.com/Kong/kubernetes-ingress-controller/issues/1656 :+1:
