### ISSUE TITLE
Kong Ingress should not use kubernetes.io/ingress.class:"nginx"

### ISSUE THREAD

**Issue by joe1chen** [Kong/kubernetes-ingress-controller#166]
### Summary

Kong Ingress should not be using "nginx" as the value for `kubernetes.io/ingress.class` because this prevents Kong Ingress from being used alongside another nginx ingress.

### What happened
We are currently using the standard NGINX ingress in GKE.  The standard NGINX ingress is already using the `kubernetes.io/ingress.class: "nginx"` annotation.  If we try to introduce the Kong ingress into our cluster, with the same annotation, now both the standard NGINX ingress and the Kong ingress will conflict.

### Expected behvaior
Kong ingress should be using their own ingress class in order to distinguish it from the standard NGINX ingress.  Something like:

`kubernetes.io/ingress.class: "kong"` 

would make a lot of sense.

**Comment by hbagdi** [comment]
@joe1chen Yes, we plan to change the ingress class to `kong` in future. If I recall correctly, the decision to keep the default class as `nginx` was made to keep compatiblitiy with`kube-lego` 

You can change the Ingress class to `kong` using `--ingress-class=kong` flag.
Please refer: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/ingress-class.md

**Comment by hbagdi** [comment]
This will be fixed with #213. Next release of Ingress Controller will use the Ingress class "kong" by default.

**Comment by udaykanth469** [comment]
Is it possible to change default ingress class to some other name?

**Comment by hbagdi** [comment]
> Is it possible to change default ingress class to some other name?

It will be from 0.10 onwards (which ships in a couple of weeks).
