### ISSUE TITLE
Delete ingress v1beta1 code paths (breaks k8s <1.19)

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

When versions of k8s older than 1.19 go out of support for KIC, we'll be ready to delete the code paths associated with `networking.k8s.io/v1beta1` and `extensions/v1beta1` Ingress.

The scope of this issue is to drop support for talking to the API server using APIs older than v1.
Note to users: this is not equivalent to dropping support for v1beta1 Ingress resources. As long as k8s accepts v1beta1 Ingress resources (FWIW, until v1.22 not inclusively), they will work with KIC regardless of this change.

### Proposed Solution

Drop `networking.k8s.io/v1beta1` and `extensions/v1beta1` code paths from KIC
Drop the ingress version negotiation mechanism.

### Additional information

Marking this issue _blocked_ because this needs to wait until we decide not to support k8s versions older than 1.19.

### Acceptance Criteria

- [ ] Code paths for ingress versions older than v1 have been dropped, and the controllers have been deleted.
- [ ] Ingress class version negotiation mechanism has been deleted.
- [ ] Documentation clearly says that k8s <1.19 is not supported anymore.

**Comment by mflendrich** [comment]
At the moment of writing, this is a breaking change for ~11% of installations. Out of those installations that we'd break, 97% are on KIC older than 2.0.
Also, <1.19 appears to be unsupported by any major cloud provider.

I think that we're ready to make this breaking change.

**Comment by randmonkey** [comment]
Considering that KIC 2.6 already removed support for k8s < 1.22 de facto, it is OK to make such a breaking change now.

**Comment by mflendrich** [comment]
Unclear whether the cost to benefit ratio justifies deleting the old code paths (in the event we want to work with ancient vendor versions of Kubernetes that aren't v1-capable.

Soft alternatives available:
- say explicitly that v1beta1 APIs are unsupported anymore and can be deleted at any point in time
- the above + hide it before a feature flag so as to prevent accidental use

**Comment by pmalek** [comment]
Since 2.5 is (going to be?) marked as LTS we'll still have something to offer for those users that run 1.21 and older.

I'd personally try to trim down the code surface of supported k8s object versions especially those that are not served by the respective kubernetes API version anyway.

#3867 aims to drop support for netv1beta Ingress. We can target it for whichever version we want but I'd vote for sooner rather than later since we don't support 1.21 and older at this point anyway, as per https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/#general.

**Comment by pmalek** [comment]
@mflendrich 

>  Ingress class version negotiation mechanism has been deleted.

I was looking for this but can't seem to find anything relevant. Did you mean this https://github.com/Kong/kubernetes-ingress-controller/blob/eb47a6906e583a5b39cbb15038671d7fef472062/internal/controllers/utils/utils.go#L24-L48 which already doesn't take netv1beta1 Ingress into account?

---

As for 

>  Documentation clearly says that k8s <1.19 is not supported anymore.

Is the table at https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/#kubernetes enough?
