### ISSUE TITLE
Issue with SSLpassthrough

### ISSUE THREAD

**Issue by anb0107** [Kong/kubernetes-ingress-controller#170]
Issue:
I see below errors in ingress logs:
- **Error creating upstream "adminui-default-https-backend-443": no object matching key "testapp/default-https-backend" in local store
- Ignoring SSL Passthrough for location "/testapp/" in server "ssltest.test.local"**

How to reproduce:
Using nginx-ingress-0.28.2, app version 0.19.0.
Trying to access an application over https://.
Backend application's port is 8443.
- Created OpenSSl certs and generated tls-secret from  the .kry and .crt.
- Set below parameters in ingress.yaml
    **nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.org/ssl-services: "default-https-backend"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"**
-  Resource access from the browser is successful over https.
And in ingress logs, I do see that the request landed on port 8443 (which is applicaion's SSL port)
- But I do see the below mentioned error messages in the logs getting printed randomly.
**Error creating upstream "adminui-default-https-backend-443": no object matching key "testapp/default-https-backend" in local store
Ignoring SSL Passthrough for location "/testapp/" in server "ssltest.test.local"**
- And when I do describe ingress, I see below output (tls1 terminates ssltest.test.local not passthrough):
ame:             ssl-test
Namespace:        default
Address:
Default backend:  default-https-backend:443 (<none>)
TLS:
  **tls1 terminates ssltest.test.local**
Rules:
  Host               Path  Backends
  ----               ----  --------
  ssltest.test.local
                     /testapp/              ssl-admin:8443 (192.168.1.28:8443,192.168.1.30:8443)

**Comment by hbagdi** [comment]
I'm guessing you opened this issue in the wrong repository.
Please open your issue at https://github.com/kubernetes/ingress-nginx.

Please re-open if needed.

**Comment by hicaistar** [comment]
> I'm guessing you opened this issue in the wrong repository.
> Please open your issue at https://github.com/kubernetes/ingress-nginx.
> 
> Please re-open if needed.

So, do we support "SSLpassthrough" with Kong Ingress Controller？How can I use it?

**Comment by hbagdi** [comment]
> So, do we support "SSLpassthrough" with Kong Ingress Controller？How can I use it?

Yes for traffic on ports other than 80 and 443.

**Comment by hbagdi** [comment]
> So, do we support "SSLpassthrough" with Kong Ingress Controller？How can I use it?

No

**Comment by hicaistar** [comment]
> > So, do we support "SSLpassthrough" with Kong Ingress Controller？How can I use it?
> 
> No

Thanks.
