### ISSUE TITLE
Confirm performance impact of new upstream map

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1709]
Per https://github.com/Kong/kubernetes-ingress-controller/pull/1702#discussion_r689799668 the addition of a deduplication map inside `getUpstreams()` likely contributes some significant additional memory usage and CPU time within `parser.Build()`, which runs every config cycle. We should collect before and after profiling information similar to https://github.com/Kong/kubernetes-ingress-controller/issues/1519#issuecomment-894553822 to try and assess `Build()` and `getUpstreams()` runtime/memory consumption if possible (may be difficult, since it looks like `getUpstreams()` was previously so negligible that it didn't show up). If the increase is significant, we should look into a data structure that's more efficient than the built-in Golang map type.

**Comment by mflendrich** [comment]
This adds O(n) hashtable accesses where n is the number of services. This shouldn't be a significant performance regression judging by static analysis of the code.

**Comment by mflendrich** [comment]
closing - stale
