### ISSUE TITLE
Update to Golang 1.17

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Dependabot wanted to [update us to the newly released Golang 1.17.0](https://github.com/Kong/kubernetes-ingress-controller/pull/1712) but there's a few more things that need to be taken care of (`go.mod`, `Dockerfile`, `CHANGELOG.md`).

Also we don't need to do this in any kind of hurry, probably better to let the dust settle a bit and give people a chance to upgrade their workstations and then worry about this.

Release Notes: https://golang.org/doc/go1.17

### Proposed Solution

- [x] update the `Dockerfile` for Golang 1.17
- [x] update the `go.mod` for Golang 1.17 & run `go mod tidy && go mod verify`
- [x] add an entry in the `CHANGELOG.md` for the Go version update for builds

### Acceptance Criteria

- [ ] as a contributor all the existing build tooling is adjusted for the most recent 1.17 release of Golang

**Comment by mflendrich** [comment]
I propose an additional acceptance solution (maybe it's already covered but it's not immediately obvious to me): that the transitive deps (dropped by 1.17) get removed from go.mod according to the new semantics.

**Comment by shaneutt** [comment]
> I propose an additional acceptance solution (maybe it's already covered but it's not immediately obvious to me): that the transitive deps (dropped by 1.17) get removed from go.mod according to the new semantics.

Will `go mod tidy && go mod verify` (as proposed above) not manage this automatically?
