### ISSUE TITLE
Do a pass over KIC 2.x documentation and find quality issues

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1719]
Problem statement:

The documentation for KIC 2.0 needs a final pass to ensure that we haven't missed any significant quality problems.
We'll be reviewing the docs in this PR: https://github.com/Kong/docs.konghq.com/pull/3099. It will be merged at the moment of publishing KIC 2.0 GA.

Acceptance criteria:
- [ ] go through all the examples and ensure that they all work
- [ ] ensure that the guides are up to date
- [ ] ensure that we don't have external links that should be replaced by internal
- [ ] read through all of the documentation and identify areas where something is out of date or not accurate anymore with 2.0

**Comment by rainest** [comment]
https://github.com/Kong/docs.konghq.com/pull/3118 (mostly) removes outdated Ingress examples.

We need to regenerate the CLI arguments page. I forget if we have a tool to do this or it's done by hand, but the controller fields still use the old EnablementStatus style.

**Comment by mflendrich** [comment]
@shaneutt is to break this task up into chunks digestible by a single person.

**Comment by shaneutt** [comment]
This is now split up into separate issues:

- https://github.com/Kong/kubernetes-ingress-controller/issues/1789
- https://github.com/Kong/kubernetes-ingress-controller/issues/1790
- https://github.com/Kong/kubernetes-ingress-controller/issues/1791
- https://github.com/Kong/kubernetes-ingress-controller/issues/1792
- https://github.com/Kong/kubernetes-ingress-controller/issues/1793
- https://github.com/Kong/kubernetes-ingress-controller/issues/1794
- https://github.com/Kong/kubernetes-ingress-controller/issues/1795
- https://github.com/Kong/kubernetes-ingress-controller/issues/1796
- https://github.com/Kong/kubernetes-ingress-controller/issues/1797
- https://github.com/Kong/kubernetes-ingress-controller/issues/1798
