### ISSUE TITLE
  IP of the old Pod in the targets was not deleted

### ISSUE THREAD

**Issue by Chris0408** [Kong/kubernetes-ingress-controller#1732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Old Pod has terminated  but  the IP of the old Pod in the targets was not deleted, cause the request to fail.
How should I locate and deal with what caused the problem？

### Expected Behavior

When the old Pod terminate, the IP of the old Pod is immediately deleted from the targets 

### Kong Ingress Controller version

```shell
v1.3.0
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rainest** [comment]
Does `kubectl get endpoints` still show the old Pod IP? If so, there's some lower-level issue, with the K8S API server not providing up-to-date information.

If not, what do your controller logs show? Generally, there's no issue reading the current list of endpoints and updating targets accordingly, but there may be some unrelated issue that's preventing your controller from applying updated configuration to Kong.
