### ISSUE TITLE
Audit KongIngress for feature parity with Kong 2.5 and 2.6

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We need to ensure that all new features added in Kong 2.5 and 2.6 wrt. 2.4 are supported in the `KongIngress` resource, so that all of these features are accessible to users of KIC.

### Proposed Solution

Functional part:
Audit the Kong Gateway changelog and identify new functionality of Kong that KIC does not expose today. Create issues for missing features.

Non-functional part:
Any improvements added to Kong 2.5 that might be useful (e.g. in the context of observability/monitoring) should be considered - whether we want to make use of these in KIC or not.

Go-kong part:
Ensure that go-kong is up to date with Admin API, and that KIC uses the newest go-kong.
Ensure tha as field parity with Kong 2.5

### Acceptance Criteria

- [ ] For all configuration params (and other Kong 2.5 interface KIC use) added to the Admin API in Kong 2.5, the corresponding fields should exist in the `KongIngress` resource;  or,  an issue under "blockers for KIC 2.0 GA" milestone is created to implement that param.
- [ ]  The configuration params mentioned above refer to both EE (potentially, feature "event hooks" matters) and OSS.

**Comment by rainest** [comment]
With the switch to the original 1.x CRDs, this is moot and superseded by https://github.com/Kong/kubernetes-ingress-controller/issues/1778 for post-GA, correct? Is there anything we think we still need to do for GA with regard to KongIngress?

**Comment by mflendrich** [comment]
Closing in favor of a more systemic solution to ensuring that our Go types across all projects are in sync with Gateway.

cc @scseanchow @hbagdi
