### ISSUE TITLE
autogenerated Kong(Cluster)Plugin - superfluous CRD fields

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Similar to #1749, but for different CRDs: KongPlugin and KongClusterPlugin.

**Comment by rainest** [comment]
Was part of https://github.com/Kong/kubernetes-ingress-controller/pull/1757
