### ISSUE TITLE
Audit all autogenerated CRDs and explain all diffs against hand-written ones

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Ensure that no unwanted difference occurs in autogenerated CRDs, as opposed to the hand-written CRDs.

### Proposed Solution

- [ ] For each bit of difference between the handwritten CRDs from KIC 1.x (converting them to `v1` CRDs first!), and the autogenerated ones coming out of Kubebuilder, perform a `diff` operation and either justify each line of diff, or make an issue to have it resolved (unless one already exists). In particular, audit for non-schema metadata changes such as `additionalPrinterColumns`.
- [ ] When we start work on this again, we need to re-enable the Kustomization override in https://github.com/Kong/kubernetes-ingress-controller/commit/8ae7e2957da229f63e2744c5acdcdc2232c40f2c, also described in https://github.com/Kong/kubernetes-ingress-controller/pull/1763#pullrequestreview-743233367 until https://github.com/Kong/kubernetes-ingress-controller/issues/1778 is done.

**Comment by rainest** [comment]
When we start work on this again, we need to re-enable the Kustomization override in https://github.com/Kong/kubernetes-ingress-controller/commit/8ae7e2957da229f63e2744c5acdcdc2232c40f2c, also described in https://github.com/Kong/kubernetes-ingress-controller/pull/1763#pullrequestreview-743233367 until https://github.com/Kong/kubernetes-ingress-controller/issues/1778 is done.
