### ISSUE TITLE
Ensure that KIC 2.0 uses stable legacy manifests for Kong CRDs rules

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Due to the perceived size of #1761 we're making a decision to ship KIC 2.0 with preexisting handwritten CRDs and RBAC rules.

### Proposed Solution

Ensure that KIC 2.0 ships with:
- CRDs for "Kong types": Kong(Cluster)Plugin, KongIngress, TCPIngress, etc. are those that shipped with KIC 1.3 (hand-written).
- CRD for UDPIngress generated from Kubebuilder

### Additional information

If we deem it possible to include TCPIngress from the new autogenerated manifests, we can consider not resorting to the legacy CRD for it.

### Acceptance Criteria

- [x] ~Kustomize manifests include the CRDs [converted] from KIC 1.3~ https://github.com/Kong/kubernetes-ingress-controller/pull/1763
- [x] Helm chart for 2.0 include the CRDs [converted] from KIC 1.3 https://github.com/Kong/charts/pull/456

**Comment by shaneutt** [comment]
automation closed, but the chart needs a patch before this is fully complete.
