### ISSUE TITLE
Clarify namespace watching in the docs

### ISSUE THREAD

**Issue by tomaszdudek7** [Kong/kubernetes-ingress-controller#1765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

This post https://kubevious.io/blog/post/comparing-top-ingress-controllers-for-kubernetes states the following:

> Kong doesn’t support cross namespace, which means the ingress controller’s functionality is limited to a particular namespace.

while this issue https://github.com/Kong/kubernetes-ingress-controller/issues/683 made by an employee of Kong Inc. states:

> Currently, it is possible to either configure the controller to listen for all resources from all namespaces (default) or one specific namespace.

A similar statement can be found in the [docs](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/concepts/deployment/) right after the `namespace` paragraph:

> If Kubernetes Ingress Controller is being used to proxy traffic for all namespaces in a Kubernetes cluster, which is generally the case, [...]

Who is telling the truth? I haven't been able to find the specific configuration in the docs or helm charts which would configure which namespaces are to be handled. Where do we specify whether KIC has to handle all namespaces or a selected one?

### Proposed Solution

Add a corresponding information to the documentation. Contact the blog post author to fix their article.

**Comment by RobSerafini** [comment]
It looks like this is resolved. Let us know if you have further questions.
