### ISSUE TITLE
Complete the autogenerated CRD descriptions

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1766]
### Problem Statement

CRDs generated by Kubebuilder have `description` fields for many of the fields.

These are already a significant improvement over the manually written CRDs from KIC 1.x, but the use of descriptions is not consistent yet (there doesn't seem to be a key for presence or lack of presence of a description on specific fields).

### Proposed Solution

Add descriptions to all fields of all autogenerated CRDs. Alternatively, choose fields not to add descriptions to, in a consequent manner.

### Acceptance Criteria

- [ ] User of our autogenerated CRDs has a consistent experience when using `kubectl explain` with all our CRDs.

**Comment by randmonkey** [comment]
I checked all our 6 CRDs in this repo:
 - `kongclusterplugin`
 - `kongconsumer`
 - `kongingress`
 - `kongplugin`
 - `tcpingress`
 - `udpingress`
fields `kongingress` does not have descriptions, and other CRDs and their fields have descriptions. So I would update the descriptions of `kongingress`.
