### ISSUE TITLE
Consider not encouraging DB-mode setups in our examples

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Since KIC deployed with a DB-backed gateway is a compromise between the declarative nature of KIC (and ingress controllers in general), we shouldn't be endorsing DB-backed setups because it's not a recommended practice.

### Proposed Solution

Keep the DB-backed deployment scenario documented for reference purposes, but not treat them as first-class deployment patterns alongside DB-less in our example deploy manifests.

Potentially, delete the DB-backed manifests altogether.

### Acceptance Criteria

TBD.

**Comment by shaneutt** [comment]
Closing as stale. While there's definitely truth in the desire to focus on DBLESS mode the reality appears to be that DB backed is here to stay for the foreseeable future. Let's re-open if we feel there's more ground we need to cover here, or if future requirements start supporting this direction.

**Comment by davidmontoyago** [comment]
This caused a lot of confusion for our team as well and agree that the docs (for the Ingress controller specifically) should avoid this ambiguity. An alternative would be to hint in the docs at using a Kubernetes client (Go, Python, etc) from within apps to manage consumers and credentials. Overall, the docs make a distinction between Declarative and Imperative configuration but it does not consider that creating consumers and credentials via the Kubernetes API is also an Imperative approach.
