### ISSUE TITLE
Consider cleanup of the `/examples` directory

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Usefulness of the `/examples` directory is not certain.

### Proposed Solution

Audit the contents of the `/examples` directory in the repo, and leave only what is still relevant.

**Comment by shaneutt** [comment]
Closing as stale, if we still need to follow up more here let's re-open.
