### ISSUE TITLE
fix the --proxy-timeout-seconds flag description

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Reported by @hbagdi as below:

> The doc line needs work, I don’t know what Kong Client is (as a user):
>     flagSet.Float32Var(&c.ProxyTimeoutSeconds, "proxy-timeout-seconds", proxy.DefaultProxyTimeoutSeconds,
>         "Define the rate (in seconds) in which the timeout configuration will be applied to the Kong client.",

### Kong Ingress Controller version

```shell
2.0.0-beta.2
```

### Kubernetes version

```shell
n/a
```

**Comment by shaneutt** [comment]
@tharun208 did you still want to work on this one?

**Comment by tharun208** [comment]
@shaneutt can you give me the updated description help text?. So, that i can come up with a patch..

**Comment by shaneutt** [comment]
@tharun208 perhaps:

```
The number of seconds before requests to the Kong Gateway will time out.
```
