### ISSUE TITLE
Consider adding "support" guidance alongside version compatibility

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

https://github.com/Kong/kubernetes-ingress-controller/issues/1652 ensures that we have a place in docs that says "version X speaks the same protocol as version Y"

The problem currently not covered by the docs is "what configuration of component versions has maintainer/vendor support until when" (@eskibars to clarify)

**Comment by mflendrich** [comment]
@eskibars to define what value we're trying to provide here

**Comment by shaneutt** [comment]
Closing as stale, let's re-open if there's more we need to follow up on here.
