### ISSUE TITLE
[2.0] add workspace instance and RBAC-protected tests into KIC integration

### ISSUE THREAD

**Issue by ccfishk** [Kong/kubernetes-ingress-controller#1785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

To verify KIC interact with enterprise gateway working as expected, it is nice to test workspace and RBAC-protected instance. 

### Proposed Solution

Add workspace instance and RBAC-protected use cases into KIC integration test cases. To accomplish this, need follow existing documentation, verify and translate the manual step into test cases. 

### Additional information

https://docs.konghq.com/enterprise/2.5.x/admin-api/rbac/examples/#use-case
not very sure this is the right case we can apply

**Comment by shaneutt** [comment]
An issue which covered testing with RBAC restrictions already exists: https://github.com/Kong/kubernetes-ingress-controller/issues/1096

**Comment by ccfishk** [comment]
> An issue which covered testing with RBAC restrictions already exists: #1096

This issue is covering clarity of workspace, and basic RBAC usage, which KIC involves, the scope is different. But I do not mind making this part of 1096 if you prefer.

**Comment by ccfishk** [comment]
Basically, if user specify --kong-workspace=notdefault, proxy will create workspace which replace default, and all input/output will be executed on the nondefault workspace, we need ensure after flipping this, generic test cases should not fail. 

We might consider super-admin creating multiple workspaces later on, but ensure enable rbac protected instance, and KIC is able to communicate with.

**Comment by shaneutt** [comment]
> > An issue which covered testing with RBAC restrictions already exists: #1096
> 
> This issue is covering clarity of workspace, and basic RBAC usage, which KIC involves, the scope is different. But I do not mind making this part of 1096 if you prefer.

No I think your suggestion that the RBAC testing should have it's own separate scope makes sense. I've updated #1096 with a comment, and changed the AC there to point to this issue for RBAC related testing instead.

**Comment by ccfishk** [comment]
Kong 2.5 : admin GET api /workspace-name/kong fails with error message "404 not found" which prevents KIC initializing from bootstrapping, though Get workspaces/workspace-name works as expected. @mflendrich @rainest , any thought about this ? 

Not sure if Kong 2.5 already deprecated this API, or some other reason.
