### ISSUE TITLE
KIC 2.0 docs: Prometheus metrics reference not linked to from the ToC

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1803]
https://kic-v2-beta--kongdocs.netlify.app/kubernetes-ingress-controller/2.0.x/references/prometheus/

This page is not accessible from the "References" dropdown on the left-hand side, but it should be.

**Comment by shaneutt** [comment]
all set, PR is merged and I double checked the netlify preview:

![netlify-preview](https://user-images.githubusercontent.com/5332524/131909521-dbc45e60-10ec-46b4-b0ff-778c5e4bef23.png)
