### ISSUE TITLE
Support Service documents

### ISSUE THREAD

**Issue by jkroepke** [Kong/kubernetes-ingress-controller#1808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Currently it's not possible to attach/uploads documents for services.

### Proposed Solution

Add a new annotation to services (or Ingress?) that fetch all files from a specific config map.

### Additional information

Due the 1MiB limit of Kubernetes objects, consider supporting compressed files. Compressed files can be stored inside `binaryData` field of ConfigMaps.

**Comment by shaneutt** [comment]
For this feature, can you please provide some concrete use cases and the acceptance criteria for resolution?
