### ISSUE TITLE
Ensure that Prometheus metrics are present on the metrics endpoint

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@hbagdi reported that

the metrics listed in
https://kic-v2-beta--kongdocs.netlify.app/kubernetes-ingress-controller/2.0.x/references/prometheus/

were not visible on the metrics endpoint of KIC 2.0.

### Expected Behavior

Metrics listed in the doc above
- `send_configuration_count`
- `ingress_parse_count`
- `proxy_configuration_duration_milliseconds`

are verified to be present in the prom output of KIC.

### Steps To Reproduce

```markdown
1. Run KIC from deploy/single-v2/all-in-one-dbless.yaml
2. curl the metrics endpoint of KIC
3. observe that these 3 metrics are not visible
```

### Kong Ingress Controller version

```shell
2.0.0-beta.2
```

### Kubernetes version

```shell
1.21 microk8s
```

### Anything else?

Also it makes sense to enhance the regression test that we have in `test/integration/controller_test.go` to verify not only that the count of metrics is > 0, but also that these 3 are present in the output.

**Comment by ccfishk** [comment]
If I understand the test steps correctly, KIC is not exposed as a K8S service resource in all-in-dbless.yaml, if user curl metrics endpoints based on proxy hostname, it wont get KIC metrics. This is expected. 
User can expose KIC metrics as a service as following
`apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-controller
  namespace: kong
spec:
  ports:
  - name: cmetrics
    port: 10255
    protocol: TCP
    targetPort: 10255
  selector:
    app: ingress-kong
  type: LoadBalancer
`
And curl this service ip + 10255/metrics, should be able to review the data.  
Or install prometheus operator, configure PodMonitor, ServiceMonitor, should also be able to see the metrics.

**Comment by ccfishk** [comment]
We need update docs - access KIC metrics guide step by step. Basically, there are two ways
- expose KIC metrics as a k8s service (above sample), and deploy this service. and access the service directly (most efficient one)
- install prometheus operator, pod and service monitor, following https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md. configuration is pretty tricky
