### ISSUE TITLE
Upgrade Deck to v1.8.x or newer

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Deck `v1.8.0` has released and is not automatically upgradable:

https://github.com/Kong/kubernetes-ingress-controller/pull/1823

### Proposed Solution

- make the changes needed to upgrade Deck
- upgrade Deck to v1.8.x

### Acceptance Criteria

- [ ] KIC is updated to the latest deck `v1.8.x` release

**Comment by rainest** [comment]
We furthermore want https://github.com/Kong/deck/pull/535 done for the bugfix.

**Comment by mflendrich** [comment]
blocked on deck#535
