### ISSUE TITLE
E2E test flake: services "kong-admin" not found

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/Kong/kubernetes-ingress-controller/runs/3653525856?check_suite_focus=true#step:5:123 has the following test failure:

```
    all_in_one_test.go:319: finding the ip address for the admin API
    all_in_one_test.go:321: 
        	Error Trace:	all_in_one_test.go:321
        	            				all_in_one_test.go:136
        	Error:      	Received unexpected error:
        	            	services "kong-admin" not found
        	Test:       	TestDeployAllInOneEnterpriseDBLESS
--- FAIL: TestDeployAllInOneEnterpriseDBLESS (131.80s)
```

### Expected Behavior

The test should not have the failure referenced above.

### Steps To Reproduce

```markdown
n/a - this is a test flake.
```

### Kong Ingress Controller version

```shell
commit 8c9c255 (main branch)
```

**Comment by shaneutt** [comment]
Sorry, this was already a known issue that is fixed in https://github.com/Kong/kubernetes-ingress-controller/pull/1816. It was not expected that it would get blocked in PR review and so it wasn't reported as an issue because I personally though it would land within a few hours.
