### ISSUE TITLE
prometheus/common needs manual upgrade

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#1877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We've skipped 5 consecutive version bumps from dependabot because they didn't apply cleanly:

0.31: #1867
0.30: #1590 
0.29: #1452 et al
0.28: #1403 
0.27: #1395 

If we continue skipping versions like this, the drift will keep building up and the upgrade will become more problematic and regression-risky.

### Proposed Solution

Bump github.com/prometheus/common to the most recent available version manually

### Additional information

Assigning severity medium because this issue will rot if left unattended for long.

### Acceptance Criteria

- KIC is using github.com/prometheus/common in its latest stable version

**Comment by shaneutt** [comment]
Resolved by #1950
