### ISSUE TITLE
Automated Github Workflow Version Matrix Updates

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#1886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Versions of components in our release testing and other Github Workflow matrices are currently manually managed and updated over time. We should automate this to avoid lag and misses.

### Proposed Solution

- [ ] create a script which can identify components and versions listed in github actions workflows YAMLs
- [ ] the script should be able to identify newer patches or other releases for these components
- [ ] the script should be able to compile new workflow yamls with updated component versions, while still maintaining the history of major/minor releases
- [ ] CI should be added to run these checks on a daily basis and automatically submit a PR with updates

### Acceptance Criteria

- [ ] as a maintainer of the KIC I do not need to manually manage component version matrices for our testing workflows, this is automatically handled for me.

**Comment by czeslavo** [comment]
Idea: consider making the update mechanism generic in a way that it's able to handle version updates in arbitrary files. It could be configured like so:

```go
type BumpedVersionResolver interface {
	// FindNewerVersion looks for a newer version than the current one, and returns it if found one.
	// It might be implemented for github releases, docker registries, git tags etc.
	FindNewerVersion(current string) (string, error)
}

type VersionUpdateConfig struct {
	FilePath               string
	RegexOfVersionToUpdate string
	BumpedVersionResolver  BumpedVersionResolver
}
```

This way we'd be able to update not only dependencies in the workflow files, but also the ones that are defined in Golang consts, like the [Helm chart version](https://github.com/Kong/kubernetes-ingress-controller/pull/4494#discussion_r1290149754).

**Comment by czeslavo** [comment]
It was solved: https://github.com/Kong/kubernetes-ingress-controller/issues/4692.
