### ISSUE TITLE
Kong Plugins Annotation Example Doesn't Actually Have An Example

### ISSUE THREAD

**Issue by jwyoungpm** [Kong/kubernetes-ingress-controller#192]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Attempting to understand how to attach a plugin to a specific service, the [readme](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/custom-resources.md#kongplugin) claims to have an example of how to use annotations to do this but only shows an example of a plugin definition and not an example of using an annotation in an ingress/service definition to attach a plugin to the ingress/service

**Kong Ingress controller version**
N/A

**Kong or Kong Enterprise version**
N/A

### Kubernetes version
N/A
**paste `kubectl version` output**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened

There is no actual example of how to use the plugin CRD

### Expected behvaior

Using the kong plugin CRD is confusing and not well documented, there is no example of how to actually attach a plugin to a defined ingress on the kongplugin readme.

### Steps To Reproduce

1.
2.
3.
4.

**Comment by angelshila** [comment]
The following link shows **new** syntax of annotating a KongPlugin object to an ingress/svc:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/annotations.md

The following link shows how to annotate a plugin to an ingress/svc using kubectl patch command:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/minikube.md

The following link contains two different examples which use annotating a plugin to an ingress/svc while creating an ingress/svc:
https://github.com/Kong/kubernetes-ingress-controller/tree/master/docs/external-service
Note: the above link still shows the deprecated syntax of plugin annotations, but you do get an idea.

**Comment by mativillagra** [comment]
Hello. 

I just tested the example it works, but with one change. 

1. Step 2 . Configure a request-transformer plugin to remove the Host header from the original request. 

echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: transform-request-to-mockbin
config:
  remove:
    headers: host
" | kubectl create -f -

output 

The KongPlugin "transform-request-to-mockbin" is invalid: []: Invalid value: map[string]interface {}{"metadata":map[string]interface {}{"namespace":"default", "generation":1, "creationTimestamp":"2018-11-06T11:47:59Z", "uid":"cef6686c-e1b9-11e8-bd89-080027ada357", "selfLink":"", "clusterName":"", "name":"transform-request-to-mockbin"}, "apiVersion":"configuration.konghq.com/v1", "config":map[string]interface {}{"remove":map[string]interface {}{"headers":"host"}}, "kind":"KongPlugin"}: validation failure list:
.plugin in body is required

I add **plugin: request-transformer** to be able to work I paste here. 

echo "
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: transform-request-to-mockbin
config:
  remove:
    headers: host
plugin: request-transformer
" | kubectl create -f -

[](https://docs.konghq.com/hub/kong-inc/request-transformer/)

Also if you follow the example on creating the Ingress (6. Create an Ingress rule) on the deploy guides (minikube) 

[](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/minikube.md)

Be sure to delele that Ingress so the **Expose an external application example** works. 

Hope it helps!

**Comment by jwyoungpm** [comment]
Thanks to both of you! I was looking in the wrong spot @angelshila and had missed those links, thanks for the tip. 

Regardless, I think that plugin spot could use some more information and perhaps a link to those docs, I will consider opening a PR to update it in the future.
