### ISSUE TITLE
Ingress Does not Get Assigned Address

### ISSUE THREAD

**Issue by doctorwu** [Kong/kubernetes-ingress-controller#1925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I install Kong from the bit.ly URL in GKE (not sure about anywhere else), and create an Ingress in a script. The Ingress resource does get assigned an IP address. Doing `kubectl -n kong rollout restart deployment ingress-kong` jogs it into working again.

### Expected Behavior

Ingress should be assigned the kong proxy IP address.

### Steps To Reproduce

```markdown
Attached is a script snippet:


kubectl create namespace kong --context $KUBE_CONTEXT

kubectl create secret generic kong-enterprise-license --from-file=./license -n kong --context=$KUBE_CONTEXT

kubectl apply -f https://bit.ly/k4k8s-enterprise-install --context $KUBE_CONTEXT

echo "apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuma-control-plane
  namespace: $NS
  annotations:
    konghq.com/strip-path: 'true'
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: $CP_SERVICE
          servicePort: 5681
        path: /kuma" | kubectl --context $KUBE_CONTEXT apply -f -
```
```


### Kong Ingress Controller version

```shell
v2.0.2
```

### Kubernetes version

```shell
1.19.13-gke.1200
```

**Comment by doctorwu** [comment]
Seems to be back. Using GKE v1.20.11-gke.1300 and KIC v2.1.1

When I install Kong with `kubectl apply -f https://bit.ly/k4k8s-enterprise-install` and create an Ingress right after installation, the Ingress never gets an IP address. However, when I delete the Ingress and recreate, all is good.

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-ingress-controller/commit/7aaaf43fe0c02cc55993e359835291d1a449d6b4 is the proposed non-blocking fix. Waiting for nightly stuff to work so that we can run E2E on it.
