### ISSUE TITLE
Add Grafana dashboard for controller Prometheus metrics

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#1926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As of 2.x, we have Prometheus metrics, but do not yet have a Grafana dashboard.

### Proposed Solution

Create a Grafana dashboard and add it to https://grafana.com/orgs/konghq

### Acceptance Criteria

- [ ] A Grafana dashboard displaying controller metrics is available.

**Comment by giovannicandido** [comment]
I have imported the grafana dashboard with id 7424 but the metrics kong_http_status do not exist in prometheus after enabling metrics in kong. Is this problem related or should I open a new issue?

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-ingress-controller/pull/2035 is a basic draft. The success/failure counts should be more or less fine fine, though IDK how useful the translation count is (I don't know if it ever fails in practice, and we perform translations constantly, so it ends up just being number go up) and they don't seem bound to the selected time window (which is what I want) like the duration histogram is: changing the time window in the UI always shows the same value for the counts, so I'm assuming that's from the beginning time.

After running a job to create 5000 Ingresses (expected to make sync time more or less linear, since it's DB-less), I end up with:

![Screenshot_select-area_20211124132323](https://user-images.githubusercontent.com/571832/143314437-e5ac0b94-58f4-4a70-9c60-c653d2b5ca2f.png)

Switching to 5m from 15m updates the histogram, but not the stats:
![Screenshot_select-area_20211124132508](https://user-images.githubusercontent.com/571832/143314581-ba5fe564-a4f0-4789-8ec4-64068e6ba1f8.png)

Unsure if there's a way to get rid of the area under graph or whatever for the translations; I don't think it serves any use.
