### ISSUE TITLE
Makefile tag reporting incorrect version

### ISSUE THREAD

**Issue by FraPazGal** [Kong/kubernetes-ingress-controller#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The reported version by `TAG` in the Makefile is incorrect for release `v1.3.3`:

https://github.com/Kong/kubernetes-ingress-controller/blob/v1.3.3/Makefile

### Expected Behavior

The version should be up-to-date as such: `TAG?=1.3.3`

### Kong Ingress Controller version

```shell
v1.3.3 release and 1.3.x branch
```

**Comment by mflendrich** [comment]
This is a known issue with the `1.3.3` release - sorry about that. We've updated the tag in the `1.3.x` branch that tracks the `1.3` line, and we'll update our release instructions to prevent it from happening ever again. Sorry for causing confusion here.
