### ISSUE TITLE
Allow customers to isolate permissions of KIC across different Kong workspaces

### ISSUE THREAD

**Issue by scseanchow** [Kong/kubernetes-ingress-controller#2002]
As a customer I would like to use workspace admins to install KIC in different k8s namespaces separately. KIC is required to read endpoints /, /tags, /workspaces and /workspaces/*, as of today, a workspace admin don't have enough permissions to install KIC.

For example, given a structure as follows:

```
default: used by themselves
company-a: used by company a
company-b: used by company b
```

the customer (default) would like to use the workspace-admin token to control company A/B's KIC instance.

**Comment by mflendrich** [comment]
closing as resolved already - works as of KIC 2.0.1
