### ISSUE TITLE
Ingress does not get updated when Service has `konghq.com/protocol: https` annotation

### ISSUE THREAD

**Issue by jeroen-s** [Kong/kubernetes-ingress-controller#2011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I end up here: 

https://github.com/Kong/kubernetes-ingress-controller/blob/5740914960f17f7216cc41d18134efddd9882e00/internal/ctrlutils/ingress-status.go#L163

### Expected Behavior

I should end up here:

https://github.com/Kong/kubernetes-ingress-controller/blob/5740914960f17f7216cc41d18134efddd9882e00/internal/ctrlutils/ingress-status.go#L149

### Kong Ingress Controller version

```shell
v2.0.5
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by shaneutt** [comment]
Hi @jeroen-s thanks for reporting this.

This issue was previously reported in https://github.com/Kong/kubernetes-ingress-controller/issues/1991 and a fix has been issued. We're intending for this to land in the next patch release `2.0.6` which will most likely release in the next couple of days.
