### ISSUE TITLE
Ingress does not get updated when name contains period(s)

### ISSUE THREAD

**Issue by jeroen-s** [Kong/kubernetes-ingress-controller#2012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Due to:

https://github.com/Kong/kubernetes-ingress-controller/blob/5740914960f17f7216cc41d18134efddd9882e00/internal/ctrlutils/ingress-status.go#L190

I end up here:

https://github.com/Kong/kubernetes-ingress-controller/blob/5740914960f17f7216cc41d18134efddd9882e00/internal/ctrlutils/ingress-status.go#L201

with `name` being the part of the Ingress name before the first period.

### Expected Behavior

Normal Ingress update.

### Kong Ingress Controller version

```shell
v2.0.5
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by shaneutt** [comment]
Hi @jeroen-s thanks for reporting this :+1: 

I have a PR up which addresses this as well as one other issue: #2013 

Ideally if review goes swiftly the intention will be to release this in the next patch version `v2.0.6` in the next few days.
