### ISSUE TITLE
Support protocol selection for TCPIngress

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Kong 2.7 [will include](https://github.com/Kong/kong/commit/8c46e10e8f23d1024d10f230a1dfaa10e74b384f) a new `tls_passthrough` protocol. This allows SNI selection of routes without terminating TLS at Kong.

Currently, TCPIngresses [hard-code all TCP protocols when building a route object](https://github.com/Kong/kubernetes-ingress-controller/blob/v2.0.5/internal/parser/translate.go#L354). This will not work with `tls_passthrough`, as you cannot set both it and `tls` on the same route.

### Proposed Solution

Support `konghq.com/protocols` on TCPIngress. Optionally validate that these protocols are valid for TCPIngress routes.

Optionally automatically add the `tcp` protocol to all TCPIngress routes even if not included in the requested protocols. The annotation will apply to all rules in the TCPIngress, but a TLS protocol will not work for rules without `host`. You can include both rules with `host` and rules without `host` in the same TCPIngress. Our existing behavior (always include everything) indicates that this should be okay, though this is a good opportunity to verify that this does not cause unintended side effects.

TCPIngress currently has no validation webhook, so that'd require a bit of extra boilerplate work if we want to ensure that you don't try and set `grpcs` or whatever on a TCPIngress.

**Comment by mflendrich** [comment]
@scseanchow to provide UX feedback on the proposed solution

**Comment by mflendrich** [comment]
Blocked on reviewing that the test coverage requested in #1179 covers the area where this change might potentially cause regression.

**Comment by rainest** [comment]
@mflendrich @scseanchow @RobSerafini given our current behavior (we set `protocols=[tls,tcp]` on all TCPIngress routes and let the presence of `hostname` dictate whether a route requires SNI and is thus TLS-only), we have two options here:

1. As proposed above, extend support for the `konghq.com/protocols` annotation to TCPIngress. Users will be able to freely set protocols on the routes generated from a TCPIngress.
2. Add a new boolean annotation, e.g. `konghq.com/tls-passthrough`. When set on a TCPIngress, all generated routes will use `protocols=[tls_passthrough,tcp]` rather than `protocols=[tls,tcp]`.

IMO items in favor of option 1:

- It is consistent with the UX for Ingress resources, which use the `konghq.com/protocols` annotation also.
- It is more flexible for future similar features. If Kong adds additional TCP-ish protocols in the future beyond `tcp`, `tls`, and `tls_passthrough`, we will not require any new annotation.
- It allows you to create TLS-only port-based TCP routes, whereas currently all TCPIngress routes will accept plaintext TCP if they do not include a hostname.

and in favor of option 2:

- There are fewer options, so it's harder to misconfigure. Exposing protocols directly allows you to request stuff like `[udp,tcp]` (valid per Kong, but maybe not actually viable in practice--I have no idea what this does on the service end) or `[grpcs,tcp]` (invalid, will result in configuration failure). We can, however, add validation to option 1 that mitigates this

**Comment by mflendrich** [comment]
Decision: we go with (1) from @rainest's comment above.

**Comment by shaneutt** [comment]
> Decision: we go with (1) from @rainest's comment above.

There's a possible problem with this decision based on [prior art solving similar problems](https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1alpha2/tlsroute_types.go). In Gateway APIs TLS passthrough is [specifically supported by the TLSRoute](https://github.com/kubernetes-sigs/gateway-api/blob/master/site-src/faq.md?plain=1#L69) API and that is independent. By not following the example laid out for us by upstream we may run into:

- considerable complexity that the combined efforts of upstream contributors were specifically trying to avoid
- a much harder time converting and migrating from kong API types to parallel gateway API types in future iterations

I think we should reconsider our approach here and consider either:

- creating a parallel TLS API that can later be migrated to `TLSRoute` in upstream when it's GA
- only support `tls_passthrough` options with the upcoming `TLSRoute` support we are adding for [Gateway APIs](https://github.com/Kong/kubernetes-ingress-controller/blob/main/keps/0002-kong-gateway-api.md#milestone-2---alpha-quality---extended-api-support-provisional)

**Comment by rainest** [comment]
Only supporting on `TLSRoute` won't provide this for a while; GWAPI GA is a long while off and we want this available once Kong 2.7 is released, so we do need something

If it's purely determined by resource type for GWAPI (as [the TLS guide](https://gateway-api.sigs.k8s.io/v1alpha2/guides/tls/?h=pass#clientserver-and-tls) indicates) we can do what we currently do with TCPIngress and just hard-code the default protocol set. Both TLSRoute and TCPIngress need to support the general override pattern (as-is it's impossible for anything that creates Kong Routes to _not_ support it) and share the implementation for it, so we shouldn't need to refactor anything on our end.

Dunno what plans are for assisting migration, but #2041 won't change much whether we create a new CRD or not (the test resource type would change, but the test steps shouldn't need to).

**Comment by shaneutt** [comment]
> Only supporting on `TLSRoute` won't provide this for a while; GWAPI GA is a long while off

Right now in upstream we're looking at february/march for a beta API, and while we can't be certain I would expect that we would have our implementation in at least beta quality state during the same timeframe. This isn't an argument to what you're saying, just more of a note. At some point it seems reasonable that some new functionality would _only_ go into GW apis and we would start deprecating some of our parallel APIs (`TCPIngress`, `UDPIngress`) not saying that time is _now_ but just something to think about.
