### ISSUE TITLE
Wrong reported version in Makefile

### ISSUE THREAD

**Issue by FraPazGal** [Kong/kubernetes-ingress-controller#2027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The newest released version `2.0.6` has its `Makefile` still using `TAG?=2.0.5`:

https://github.com/Kong/kubernetes-ingress-controller/blob/e2a1a8dfdf57fc145c85cabedfe67b83e2e301c5/Makefile#L5

### Expected Behavior

The `Makefile` should be updated to use the same `TAG` like the one used in the release, `2.0.6`

### Kong Ingress Controller version

```shell
v2.0.6
```

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-ingress-controller/pull/2032 intends to resolve this issue once and for all. Note that it will append a prerelease tag if you added additional commits beyond the tag without creating your own tag, which is a change from the previous behavior.

@mflendrich I don't know if you want to fix and re-tag: the official builds don't use this value (the Docker build in CI pulls its value directly from the git tag already), and for local builds you can at least do `TAG=2.0.6 make container` to override the incorrect value. If we then adopt #2032, the problem becomes moot for future releases.

**Comment by FraPazGal** [comment]
The changes added at #2032 look great. Thanks for the fix!

**Comment by shaneutt** [comment]
It sounds like this is all set now as of #2032, please feel free to re-open if there's more needed :vulcan_salute:
