### ISSUE TITLE
OIDC Upstream sent too big header while reading response header from upstream

### ISSUE THREAD

**Issue by chaseaucoin** [Kong/kubernetes-ingress-controller#2037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I have the following configuration:
- K8s provided by EKS
- Kong Ingress as the sole ingress controller

And I invoke a login request via POST in a service with the following details:
- Service uses OIDC via Cognito
- Service responds with a 302 redirect to the SSO provider

I get the following failure:
- message: "An invalid response was received from the upstream server"

Looking at the logs for the kong proxy service I find the following:
- 209 upstream sent too big header while reading response header from upstream
- I believe this is due to the length of the URI with the embedded token

I have tried updating the deployment for "ingress-kong" deployment

`spec:
      containers:
        - name: proxy
          image: 'kong:2.5'
          ports:
            - name: proxy
              containerPort: 8000
              protocol: TCP
            - name: proxy-ssl
              containerPort: 8443
              protocol: TCP
            - name: metrics
              containerPort: 8100
              protocol: TCP
          env:
            - name: KONG_PROXY_LISTEN
              value: '0.0.0.0:8000, 0.0.0.0:8443 ssl http2'
            - name: KONG_PORT_MAPS
              value: '80:8000, 443:8443'
            - name: KONG_ADMIN_LISTEN
              value: '127.0.0.1:8444 ssl'
            - name: KONG_STATUS_LISTEN
              value: '0.0.0.0:8100'
            - name: KONG_DATABASE
              value: 'off'
            - name: KONG_NGINX_WORKER_PROCESSES
              value: '2'
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: nginx_proxy_large_client_header_buffers
              value: 16 128k
            - name: nginx_http_client_header_buffer_size
              value: 16k`

the added change was nginx_proxy_large_client_header_buffers and nginx_http_client_header_buffer_size

this did not change the outcome. 

If I access the service directly this does not happen, whether from a container, or on bare metal.

How can I set an appropriate buffer in kong ingress so that I do not get upstream sent too big header while reading response header from upstream?

### Expected Behavior

When I make a request with a large header I should still be able to access it so long as it is valid HTTP 1.1+ spec.

### Kong Ingress Controller version

```shell
kong/kubernetes-ingress-controller:2.0.5
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by bungle** [comment]
Options:
1. store OpenID connect session data on server side (redis or memcached)
2. generate smaller JWTs from token endpoint
3. enable compression of sessions on OpenID Connect plugin
4. allow large headers
5. disables sessions on oidc plugin

**Comment by chaseaucoin** [comment]
@bungle 
I basically did option 1 to get myself over the hump. 

How would I go about option 4: "allow large headers"
