### ISSUE TITLE
Bug: KongPlugin set to global does not respect namespace

### ISSUE THREAD

**Issue by UkiahSmith** [Kong/kubernetes-ingress-controller#205]
### Summary

KongPlugin set to global will be created, and configured, in multiple instances of Kong regardless of namespace.

**Kong Ingress controller version:** 0.1.3

**Kong or Kong Enterprise version:** Kong Enterprise 0.33

### Kubernetes version

Kubernetes version 1.10.3 hosted on AWS (EKS) and kubectl 1.11

### What happened

Two instances of Kong are running in K8s each one with it's own serviceaccount, namespace and ingress controller. When a KongPlugin is set to global it will be created in both instances of Kong, even when they do not have access to each other's namespace.

### Expected behvaior

A global KongPlugin configured in one ingress controller should only be created, and configured, for the Kong instance with the same namespace.

**Comment by nmacherey** [comment]
I have the same problem for all CustomResources see #218 ...
KongConsumer/KongPlungin are created in all existing Kong instances

**Comment by hbagdi** [comment]
0.3.0 brings in support for `ingress.class` annotation based filtering which should solve the problem of two Ingress controllers fighting to satisfy the same resource.
