### ISSUE TITLE
Assume `goimports --local` as our imports formatting standard

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

@shaneutt proposed in https://github.com/Kong/kubernetes-ingress-controller/pull/2051#discussion_r763372456 that we reformat our imports using `goimports --local <package prefix>`, so that the "local" imports (from the KIC repo) land after all other imports.

### Proposed Solution

- One-shot reformatting of KIC by running `goimports --local "github.com/kong/kubernetes-ingress-controller" -w **.go` and submitting it in a PR
- A CI check that ensures that all new changes abide by this formatting standard

### Additional information

Autogenerated code coming from controller-gen/kubebuilder does not follow this style today. Blanket reformatting of the repository touches a lot of autogenerated files. We'd either need to tune the codegen mechanism to format the files appropriately, or exclude codegen from this rule.

### Acceptance Criteria

- [ ] all Go files in KIC reformatted with `--local` (possibly excluding autogenerated files - see above)
- [ ] a CI check in place that prevents submission of files that are not formatted with `--local`

**Comment by tharun208** [comment]
It looks like the [gci](https://github.com/daixiang0/gci) linter gives a similar result. Could we drop goimports in favor of that?

We can add it to the existing `golangci` configuration and also Kuma uses `gci` for formatting imports.

**Comment by shaneutt** [comment]
Sounds good @tharun208 :+1:, are you interested in adding that?

**Comment by tharun208** [comment]
@shaneutt yes and will raise a PR

**Comment by shaneutt** [comment]
Thank you :bow:
