### ISSUE TITLE
Add TCPIngress performance tests

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Broken out of https://github.com/Kong/kubernetes-ingress-controller/issues/1179

### Acceptance Criteria

Tests confirm that:

- [ ] Multiple `TCPIngress` resources can be rapidly created, each backend resolving in under 1 minute
- [ ] Bulk parallel connections through `TCPIngress` succeed, no failures at KIC/Kong level
- [ ] Multiple `TCPIngress` resources can be rapidly deleted, each backend route becomes disconnected in under 1 minute

**Comment by mflendrich** [comment]
closing as won't fix - we have more burning testing needs elsewhere
