### ISSUE TITLE
Test TCPIngress behavior when upstream disappears

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Broken out of #1179

### Acceptance Criteria

Tests confirm that:
- [ ]  Long running persistent connections (where the backend server doesn't support reconnect mechanisms) disconnect and fail properly when pods change

**Comment by rainest** [comment]
Per https://github.com/Kong/kubernetes-ingress-controller/issues/1179#issuecomment-982085102, this is all NGINX-level behavior. AFAIK Kong has no control over the connection once established, and cannot set any NGINX-level configuration that would influence this behavior.

**Comment by mflendrich** [comment]
Closing as won't fix per @rainest's comment above.
