### ISSUE TITLE
Kubernetes 1.23 compatibility

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2097]
Acceptance criteria:

- [x] Compatibility matrix for KIC 2.0 includes k8s 1.23
- [x] Our automated tests run against k8s 1.23
- [x] Changes in k8s 1.23 changelog assessed for potential impact on KIC

**Comment by mflendrich** [comment]
#2072 is unrelated to KIC supporting k8s 1.23, but it describes the (non-trivial) work needed to bump the k8s libraries we use in KIC.

**Comment by rainest** [comment]
Main takeaways are that we may want to configure IPv4/v6 dual-stack test environments and should look at migrating from PodSecurityPolicy to PodSecurity in the future, but nothing that we'd immediately need to account for.

- FlexVolume deprecation doesn't matter, we don't use it.
- [klog deprecations](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#klog) affect 1.x but not 2.x, which longer accepts the klog flags for any remaining code still using klog.
- GA IPv4/IPv6 dual stack maybe affects us, but not in any knowable way. L3 should largely be handled for us, so we shouldn't have obvious IPv6 concerns. We can use a dual-stack test cluster if we wish to confirm further.
- HorizontalPodAutoscaler v2 graduates to GA does not affect us, as the chart uses v1, which is not deprecated.
- Generic Ephemeral Volume feature graduates to GA does not affect us, as we do not deal with storage drivers.
- Skip Volume Ownership change graduates to GA ditto.
- Allow CSI drivers to opt-in to volume ownership and permission change graduates to GA ditto.
- PodSecurity graduates to Beta will eventually need changes in the chart, but this is still a beta.
- Container Runtime Interface (CRI) v1 is default doesn't affect us, we aren't a container runtime.
- Structured logging graduate to Beta does not affect us, it is for cluster admins.
- Simplified Multi-point plugin configuration for scheduler is for cluster admins.
- CSI Migration updates relates to storage drivers and does not affect us.

We already use 1.23 client libraries, so there are no API changes that we need to account for.

Dispatch jobs can now [run against 1.23 in a CI environment](https://github.com/Kong/kubernetes-ingress-controller/runs/4943307216?check_suite_focus=true), do we think we need to keep this open until the regular jobs run against them as well, or just update those as usual (bump versions as part of the release process) once they become available in GKE?

**Comment by shaneutt** [comment]
> GA IPv4/IPv6 dual stack maybe affects us, but not in any knowable way. L3 should largely be handled for us, so we shouldn't have obvious IPv6 concerns. We can use a dual-stack test cluster if we wish to confirm further.

It does occur to me that we should have an E2E test which is deploying dual-stack enabled and verifying IPv6 configurations and traffic as a litmus test.

> Dispatch jobs can now run against 1.23 in a CI environment, do we think we need to keep this open until the regular jobs run against them as well, or just update those as usual (bump versions as part of the release process) once they become available in GKE?

Our measure of compatibility is currently that all E2E tests pass on the version. Given the PR you have open where we can optionally run the integration tests, I think if we just make those integration tests default to on instead of off once they pass we can consider this complete, and otherwise update the defaults for day-to-day integration test runs over time as you suggested.

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/1753133776 is with the integration tests also.
