### ISSUE TITLE
namespace restricted backendRefs

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2155]
The purpose of this issue is to enforce namespace restrictions for backendRefs in the admission webhook controller, under the httproute validation (which lives in `internal/validation/gateway/httproute.go`).

# Pre-Requisites

- [ ] #2080

**Comment by shaneutt** [comment]
added AC to reflect this need and closing as a duplicate of https://github.com/Kong/kubernetes-ingress-controller/issues/2080
