### ISSUE TITLE
deterministic unique route identifier for HTTPRoute match translations

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2156]
# Problem

Stretch item for the Milestone 1

Context: https://github.com/Kong/kubernetes-ingress-controller/pull/2136#discussion_r779672118

Our current logic that translates HTTPRoute contents to Admin API `route`s creates routes named after the relative order of entries in the HTTPRoute. This causes a problem that was previously outlined in #1005 for other types of configuration sources as well.

# Proposed Solution

There is prior art for this in https://github.com/Kong/kubernetes-ingress-controller/pull/1003

- [ ] compare and decide on a hashing algorithm (we've considered crc64, SHA256 and UUID5)
- [ ] hash all uniquely identifying data on `HTTPRoute` and `Ingress` APIs (e.g. `UNIQ_ID`)
- [ ] apply a naming scheme of `<TYPE>.<NAMESPACE>.<NAME>.<UNIQ_ID>`
- [ ] use a map to detect and avoid collisions, and append a number

# Acceptance criteria

- [ ] routes created in `translate.ingressRulesFromHTTPRoutes` don't get deleted and recreated when their order changes - are immune to reordering

**Comment by shaneutt** [comment]
The PR for this has gotten quite huge, but as a stretch goal this does not need to hold up Gateway M1 and ultimately it's a general improvement to our codebase so I'm removing it from the Gateway milestones as no work there needs to wait for it.

**Comment by shaneutt** [comment]
This is now declined due to a lack of end-user or customer request and the complexity in implementation.
