### ISSUE TITLE
multiple backendRefs in an HTTPRoute supported

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2157]
In HTTPRoutes, `matches` are considered an alternative (if one of the `match`es matches, it is used), but `backendRefs` act together: if there's more than one backendRef, the behavior unspecified (our current best guess is that we should do loadbalancing - equivalent to defining multiple upstreams in Kong).

Today the behavior of KIC is throwing an error (ignoring the HTTPRoute resource as it if didn't exist) if the user creates an HTTPRoute with more than 1 backendRef.

Acceptance criteria
- [ ] Semantics of multiple `backendRef`s on an HTTPRoute is well-defined in upstream Gateway API (possibly requiring our contribution and alignment with other ingress controllers)
- [ ] KIC supports the "more than one backendRef in an HTTPRoute" case according to the semantics defined in the bullet point above

**Comment by shaneutt** [comment]
I checked in with some upstream community members and it seems like the `BackendRefs []HTTPBackendRef` default strategy is ultimately "round robin", but only incidentally by way of the existing "weighted" strategy, and it's all up to the implementation to decide at this point. Needless to say, I don't appear to be the only contributor that seems to think that there's need for improvement to both the spec and documentation and I've been encouraged to make a GEP for this.

**Comment by shaneutt** [comment]
After investigating this today I realized the context is significantly greater than what was originally posted so I created https://github.com/Kong/kubernetes-ingress-controller/issues/2166 which replaces this issue
