### ISSUE TITLE
Gateway APIs E2E Tests

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2158]
Testing Plan:

- [ ] deploy a new Kubernetes cluster with [KTF](https://github.com/kong/kubernetes-testing-framework)
- [ ] deploy KIC to the cluster using the `all-in-one` style manifests
- [ ] enable `--feature-gates=Gateway=true` on the KIC
- [ ] deploy a `GatewayClass` and `Gateway` resource
- [ ] verify that the `Gateway` gets provisioned properly and the proxy is listening
- [ ] deploy multiple variations of `HTTPRoute` objects
- [ ] verify that each route for each supported matching rule is routing properly
- [ ] perform large numbers of requests against all routes and verify integrity
- [x] ~run the upstream Gateway [conformance tests](https://github.com/kubernetes-sigs/gateway-api/pull/969/files) against the kong `Gateway` and verify success~ we'll follow up in milestone 2: https://github.com/Kong/kubernetes-ingress-controller/issues/2210

Acceptance criteria
- [ ] deployment with all-in-one manifests is tested E2E
- [ ] The E2E test includes RBAC permissions for HTTPRoute, Gateway and GatewayClass etc.

**Comment by rainest** [comment]
Draft in #2205, which basically runs through a simplified version of the integration tests with an actual deployment.
Re:

- deploy multiple variations of HTTPRoute objects
- verify that each route for each supported matching rule is routing properly
- perform large numbers of requests against all routes and verify integrity

Is there something we're looking for here that can only be handled in E2E, and do we indeed need them if not?

Normally E2E is just a test of a single basic route, whereas extensive testing of functionality is in integration tests instead (and the existing HTTPRoute integration tests do already cover functionality beyond "makes route or not"). E2E serves to verify that we can deploy and route successfully using the published manifests, and to test scenarios that integration can't (upgrades, multiple replicas). Integration is generally much easier for development between supporting a debugger and allowing cluster reuse.

Conformance will need to be deferred til the implementation is done, since our current partial implementation is not conformant. At most we can make a draft that integrates it and fails, which should be separate from our initial test.

**Comment by rainest** [comment]
Conformance will not only be broken at present, it's unreleased, and attempting to pull in master results in some other issues:

```
15:08:44-0800 esenin $ go get -d -t sigs.k8s.io/gateway-api/conformance@master 
go get: downgraded sigs.k8s.io/gateway-api v0.4.1 => v0.4.1-0.20220119180606-398f7e14fcef
15:10:08-0800 esenin $ GOFLAGS="-tags=e2e_tests" go vet ./...                 
test/e2e/all_in_one_test.go:37:2: no required module provides package sigs.k8s.io/gateway-api/pkg/client/clientset/gateway/versioned; to add it:
	go get sigs.k8s.io/gateway-api/pkg/client/clientset/gateway/versioned
# github.com/kong/kubernetes-ingress-controller/v2/internal/validation/gateway
internal/validation/gateway/httproute.go:131:112: undefined: v1alpha2.ParentRef
# github.com/kong/kubernetes-ingress-controller/v2/internal/validation/gateway
vet: internal/validation/gateway/httproute.go:131:128: ParentRef not declared by package v1alpha2
# github.com/kong/kubernetes-ingress-controller/v2/internal/parser
vet: internal/parser/translate_httproute_test.go:45:37: ParentRef not declared by package v1alpha2
# github.com/kong/kubernetes-ingress-controller/v2/internal/controllers/gateway
internal/controllers/gateway/httproute_controller.go:359:15: undefined: v1alpha2.ParentRef
internal/controllers/gateway/route_utils.go:21:47: undefined: v1alpha2.ParentRef
# github.com/kong/kubernetes-ingress-controller/v2/internal/controllers/gateway
vet: internal/controllers/gateway/route_utils.go:21:63: ParentRef not declared by package v1alpha2
```
It looks like they have breaking API changes to ParentRef staged as well, so IMO we should definitely defer this til after they're part of a released version.

Initial assessment is that we should be able to adopt the `TestConformance()` entrypoint at the end of our E2E test like so:

```
    client, err := gatewayclient.NewForConfig(env.Cluster().Config())                                                          
    require.NoError(t, err)                                                                                                    
                                                                                                                               
    t.Logf("Running conformance tests with %s GatewayClass", *gatewayClassName)                                                
                                                                                                                               
    cSuite := suite.New(suite.Options{                                                                                         
        Client:           client,                                                                                              
        GatewayClassName: gwc.Name,                                                                                            
        Debug:            false,                                                                                               
        Cleanup:          false,                                                                                               
    })                                                                                                                         
    cSuite.Setup(t)                                                                                                            
    cSuite.Run(t, tests.ConformanceTests)
```
but no verification til it can compile.

**Comment by shaneutt** [comment]
Yes we can wait some time for conformance as it's still being actively developed and is brand new, I've created https://github.com/Kong/kubernetes-ingress-controller/issues/2210 for the follow up.
