### ISSUE TITLE
Ingress controller crashes when kube API is unavailable

### ISSUE THREAD

**Issue by rmoesbergen** [Kong/kubernetes-ingress-controller#2161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We experienced an issue where the (GCP / GKE 1.20) k8s API was unavailable for ~5 minutes due to some maintenance. To my surprise the Kong ingress controller crashed and stopped updating the kong proxy configuration once the k8s API returned. See the logs below. The controller stopped posting updates, so traffic started to slowly fail as pods were replaced/added/removed and getting new IP's.

```
I0112 12:00:22.023303       1 trace.go:205] Trace[1209622979]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 11:59:52.022) (total time: 30001ms):
Trace[1209622979]: [30.001264522s] [30.001264522s] END
E0112 12:00:22.023335       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.26.0.1:443/api/v1/endpoints?resourceVersion=174617446": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:00:22.247719       1 trace.go:205] Trace[589260902]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 11:59:52.247) (total time: 30000ms):
Trace[589260902]: [30.000660093s] [30.000660093s] END
E0112 12:00:22.247761       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1.KongClusterPlugin: failed to list *v1.KongClusterPlugin: Get "https://10.26.0.1:443/apis/configuration.konghq.com/v1/kongclusterplugins?resourceVersion=174616420": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:00:22.371170       1 trace.go:205] Trace[1659195216]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 11:59:52.369) (total time: 30001ms):
Trace[1659195216]: [30.001641266s] [30.001641266s] END
E0112 12:00:22.371209       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: Get "https://10.26.0.1:443/apis/networking.k8s.io/v1/ingresses?resourceVersion=174616756": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:00:22.738573       1 trace.go:205] Trace[796640324]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 11:59:52.736) (total time: 30001ms):
Trace[796640324]: [30.001659192s] [30.001659192s] END
E0112 12:00:22.738612       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://10.26.0.1:443/api/v1/services?resourceVersion=174616650": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:00:28.934186       1 trace.go:205] Trace[1712794377]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 11:59:58.933) (total time: 30000ms):
Trace[1712794377]: [30.000828697s] [30.000828697s] END
E0112 12:00:28.934233       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1.KongIngress: failed to list *v1.KongIngress: Get "https://10.26.0.1:443/apis/configuration.konghq.com/v1/kongingresses?resourceVersion=174617276": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:00:34.854238       1 trace.go:205] Trace[1111040925]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:00:04.853) (total time: 30001ms):
Trace[1111040925]: [30.001202261s] [30.001202261s] END
E0112 12:00:34.854269       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.UDPIngress: failed to list *v1beta1.UDPIngress: Get "https://10.26.0.1:443/apis/configuration.konghq.com/v1beta1/udpingresses?resourceVersion=174616125": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:00:35.017165       1 trace.go:205] Trace[1895686329]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:00:05.016) (total time: 30000ms):
Trace[1895686329]: [30.000992087s] [30.000992087s] END
E0112 12:00:35.017203       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: Get "https://10.26.0.1:443/api/v1/secrets?resourceVersion=174617231": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:01:11.779237       1 trace.go:205] Trace[1479041956]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:00:41.778) (total time: 30001ms):
Trace[1479041956]: [30.001007924s] [30.001007924s] END
E0112 12:01:11.779274       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1beta1.TCPIngress: failed to list *v1beta1.TCPIngress: Get "https://10.26.0.1:443/apis/configuration.konghq.com/v1beta1/tcpingresses?resourceVersion=174616790": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:01:23.221755       1 trace.go:205] Trace[801914851]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:00:53.220) (total time: 30001ms):
Trace[801914851]: [30.001409972s] [30.001409972s] END
E0112 12:01:23.221793       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1.Ingress: failed to list *v1.Ingress: Get "https://10.26.0.1:443/apis/networking.k8s.io/v1/ingresses?resourceVersion=174616756": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:01:25.736497       1 trace.go:205] Trace[1009326758]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:00:55.735) (total time: 30001ms):
Trace[1009326758]: [30.001175514s] [30.001175514s] END
E0112 12:01:25.736574       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1.KongClusterPlugin: failed to list *v1.KongClusterPlugin: Get "https://10.26.0.1:443/apis/configuration.konghq.com/v1/kongclusterplugins?resourceVersion=174616420": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:01:26.768151       1 trace.go:205] Trace[2081720204]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:00:56.766) (total time: 30001ms):
Trace[2081720204]: [30.001583204s] [30.001583204s] END
E0112 12:01:26.768185       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get "https://10.26.0.1:443/api/v1/endpoints?resourceVersion=174617446": dial tcp 10.26.0.1:443: i/o timeout
I0112 12:01:28.726015       1 trace.go:205] Trace[1229912018]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:01:05.443) (total time: 23282ms):
Trace[1229912018]: ---"Objects listed" 23281ms (12:01:28.725)
Trace[1229912018]: [23.282312603s] [23.282312603s] END
I0112 12:01:28.763888       1 trace.go:205] Trace[674923170]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:01:16.271) (total time: 12491ms):
Trace[674923170]: ---"Objects listed" 12491ms (12:01:28.763)
Trace[674923170]: [12.491848511s] [12.491848511s] END
I0112 12:01:28.874416       1 trace.go:205] Trace[974436842]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:01:13.484) (total time: 15389ms):
Trace[974436842]: ---"Objects listed" 15389ms (12:01:28.874)
Trace[974436842]: [15.389560995s] [15.389560995s] END
I0112 12:01:29.121634       1 trace.go:205] Trace[1174901138]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.23.0-alpha.1/tools/cache/reflector.go:167 (12-Jan-2022 12:00:59.277) (total time: 29844ms):
Trace[1174901138]: ---"Objects listed" 29844ms (12:01:29.121)
Trace[1174901138]: [29.844251436s] [29.844251436s] END
```

After this, the logging just stopped.

### Expected Behavior

I would expect the ingress controller to report the timeout/connectivity issues, but keep trying and eventually recover once the k8s API returns. Or perhaps the liveness probe should fail so the container gets restarted.

### Steps To Reproduce

```markdown
1. Deploy kong ingress controller
2. Make the k8s API server unavailable
```

### Kong Ingress Controller version

```shell
Kong version 2.7, ingress controller version 2.1, installed using the helm chart (v2.6.4).
```

### Kubernetes version

```shell
GKE 1.20
```

**Comment by rainest** [comment]
Do you know of any means to replicate this reliably?

I attempted to create a single control+3 worker KIND cluster, deploy Kong and some Ingress to the workers, use `docker pause` on the control plane, unpause it after, and restart the Deployment backing the Ingress.

I did observe that KIC logging paused while the control plane was paused, which makes sense, as almost every action taken by the controller is triggered by an API server event, but after unpausing the controller began logging again and updated target IPs correctly.

If you exec into the proxy pod and check `env` output, what is `KUBERNETES_SERVICE_HOST` set to? If it's an IP, and you can trigger the same sort of maintenance event again on demand, does the cluster IP of your Kubernetes API service (usually `kubernetes.default`) change? That'd probably explain the issue if so, since the controller only obtains cluster configuration at startup. I'm not sure if `KUBERNETES_SERVICE_HOST` even updates automatically after a pod spawns.

This goes beyond my knowledge of cluster administration, but I suspect that should instead be the service hostname (`kubernetes.default`) if the IP of the API isn't static, though I'm unsure how where Kubernetes auto-populates that variable. It is possible to override it at the controller level by setting `CONTROLLER_APISERVER_HOST`.

**Comment by rmoesbergen** [comment]
Thanks for looking into this. It's pretty hard to reproduce unfortunately. I tried setting a NetworkPolicy that blocks outbound traffic from the kong pod, but haven't been able to reproduce in the same way as the original report. I think the key here is to trigger the timeout while kong is running. Getting a 'connection refused' or other tcp errors probably won't trigger this, but that's just a hunch. I'll keep trying.

KUBERNETES_SERVICE_HOST is set to an IP address (the address of the 'kubernetes.default' service). The IP of the service remains the same during the lifetime of the cluster (the service is not touched during maintenance). At least for our clusters this is the case (we use GKE).

**Comment by rainest** [comment]
What was actually done to trigger the outage? I assume it's not possible to actually repeat because GKE fully manages its control nodes, and you can't restart them unless you're upgrading their version. We also use GKE for some of our testing environments, however, and have not observed this problem when upgrading.

From some more research, it looks like that value may always be just the IP. However, if so, and the IP changing was indeed the reason the controllers did not recover, there are two questions I don't have a good answer for:

* The [client-go default behavior](https://github.com/kubernetes/client-go/blob/v0.23.3/rest/config.go#L512-L542) is to just use `KUBERNETES_SERVICE_HOST`, which seems odd if that's not a fault-tolerant choice for most environments. I didn't find any issues proposing that it needed to be changed.
* The address is a Service address, so even if the API server restarts, it should remain the same. Destroying and re-creating the Service would re-assign it, but I'm not sure under what conditions that would occur.

**Comment by rmoesbergen** [comment]
The crash occurred during a (major) control plane upgrade of GKE. We have a single-zone cluster, so the control plane goes offline for a while during the upgrade while the master node gets replaced. I've been trying to reproduce this, also by triggering GKE upgrades, but no luck. I'm starting to think either something already got fixed, or this bug is very hard to trigger.

Regarding the API IP: I'm very sure that the API server IP never changes, at least in our cluster. I have old logs where the IP is logged, and it's still the same months later. Is seems the kubernetes.default ClusterIP service is created on cluster creation, and never changes during the lifetime of the cluster.

Since it's so hard / impossible to reproduce, let's close this for now. If it ever returns, I'll just re-open or create a new (hopefully more detailed) bug report.
