### ISSUE TITLE
HTTPRoute - Multiple BackendRefs Support

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2166]
### Problem Statement

At the time of writing we only allow a single `HTTPBackendRef` for any given `rule` in an `HTTPRoute` as we did not feel the upstream specification and documentation was clear enough on how to define or implement various `LoadBalancer` strategies. After discussing this with the upstream community it seems that this sentiment may be shared among multiple contributors.

In spite of the confusion it does appear that the spec currently allows for defining a "weighted" load-balancing strategy (which incidentally allows flat "round-robin" by using equal weights) but that's it, and it's _implicit_ rather than _explicit_. We'll need support for options like "least-connections" which is available in the Kong `Upstreams` API, and it would be ideal for these configurations to be configurable in a simple, topical manner.

### Proposed Solution

- [x] make it possible to define multiple backendrefs, trigger a round-robin strategy for these configurations as the default

Additional information

- Least-connections handled in a separate issue: https://github.com/Kong/kubernetes-ingress-controller/issues/2374

### Acceptance Criteria

- [x] HTTPRoutes with multiple backendRefs no longer fail validation
- [x] HTTPRoutes with multiple backendRefs result in an upstream being created in Kong with targets for each backendRef
- [x] HTTPRoutes support the following LB strategies: round-robin (equal weights), weighted, ~least-connections~

**Comment by shaneutt** [comment]
I've started a draft of upstream changes for this and I'm talking on slack with multiple community members to get some early feedback:

https://github.com/kubernetes-sigs/gateway-api/pull/993

**Comment by shaneutt** [comment]
Moving this from milestone 1 to milestone 2 as we're going to take an [interim solution](https://github.com/Kong/kubernetes-ingress-controller/issues/2173) while we work with upstream on this.

**Comment by shaneutt** [comment]
Upstream has concluded that for now we should use `Policy` objects to influence the loadbalancing strategy within managed `HTTPRoutes`, and has not seemed generally favorable to adding any of this specification natively to `HTTPRoute`.

**Comment by shaneutt** [comment]
> Heads up. I have added an explicit _HTTPRoutes support the following LB strategies: round-robin (equal weights), weighted, least-connections_ acceptance criterion. The "weighted" part might resolve #557.

We'd previously discussed saving least connections for another scope, the primary reason for that being that we expect needing to create a policy API to attach to routes to implement this which makes this already large body of work even larger. I would like to keep that separate still unless there's some strong need to make it a part of this work?

**Comment by mflendrich** [comment]
Done - separated least-connections out into a separate ticket.
