### ISSUE TITLE
Error go format upstream field

### ISSUE THREAD

**Issue by pgold30** [Kong/kubernetes-ingress-controller#221]
---

### Summary

We moved from 0.2.2 to 0.3.0 today , and we are using kong v1.0.0-alpine moved from 0.14.1 
routes services and everything is there and the migration went fine, but we are getting errors in kong-ingress-controller 
.
**Kong Ingress controller version**
0.3.0

**Kong or Kong Enterprise version**
1.0.0-alpine

### Kubernetes version
1.10.11

### Environment

- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): debian 9

### What happened
We moved from 0.2.2 to 0.3.0 today , and we are using kong v1.0.0-alpine moved from 0.14.1 
routes services and everything is there and the migration went fine, but we are getting errors in kong-ingress-controller . after migration we cant login we receive Kong Error An invalid response was received from the upstream server.
from log kong-ingress pod i see:
`I0110 10:49:28.510073       6 controller.go:128] syncing Ingress configuration...
I0110 10:49:28.528584       6 kong.go:1075] cert: 0xc000047a90
E0110 10:49:28.532580       6 kong.go:209] err fetching upstream mock-http-server.8080 from Kong: json: cannot unmarshal number 1545238185.15 into Go struct field Upstream.created_at of type int64
E0110 10:49:28.532655       6 controller.go:131] unexpected failure updating Kong configuration: 
syncing targets: json: cannot unmarshal number 1545238185.15 into Go struct field Upstream.created_at of type int64`

### Expected behavior
Everything should work as before

### Steps To Reproduce

1.Migrate from versions mentioned

**Comment by hbagdi** [comment]
I looked into this and it seems like this is an issue with migrations within Kong: https://github.com/Kong/kong/issues/4183.


Meanwhile, if you've trouble upgrading, I recommend the following:

Deploy a fresh Kong 1.0.0 Ingress in your k8s cluster alongside the existing one.
Since all config is stored in Kubernetes, the new cluster will configure itself exactly as the current one.

Once the configuration is complete, switch your service or load-balancer to point to your new Kong cluster and then decommission the old cluster.

**Comment by thiagoit** [comment]
We created a new DB and deployed Kong again as mentioned above but we also had to change some yaml config from comma separated to arrays.

**Comment by hbagdi** [comment]
@thiagoit I assume these were for KongPlugin custom resources? Could you which plugins were these, or if not plugins, then which configs?

**Comment by hbagdi** [comment]
@pgold30 👍 
Please do share your blog entry on [Kong Nation](http://discuss.konghq.com/) when you publish it. We'd love to hear more about your use case and deployment guide. Thank you!

**Comment by hbagdi** [comment]
The original issue in this post is fixed with Kong 1.0.1.

Thank you for reporting the issue.
