### ISSUE TITLE
Blog Post for KIC 2.2

### ISSUE THREAD

**Issue by scseanchow** [Kong/kubernetes-ingress-controller#2229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Issue to track the creation of the Gateway API Milestone 1 blog post

### Acceptance Criteria

- [x] Blog post written and edited 
- [x] Blog is staged on https://konghq.com/blog/
- [x] Reviewed by docs/writing/pmm team

**Comment by shaneutt** [comment]
blog post now complete https://konghq.com/blog/kong-ingress-controller-2-2/
