### ISSUE TITLE
Documentation Update for KIC 2.2

### ISSUE THREAD

**Issue by scseanchow** [Kong/kubernetes-ingress-controller#2230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Issue to track the creation of documentation around Gateway API milestone 1.

### Acceptance Criteria

- [x] 2.2 documentation added to https://github.com/kong/docs.konghq.com
- [x] banner is created to indicate this is a technical preview feature
- [x] Gateway + HTTPRoute guide added to 2.2 documentation
- [x] Update implementations page on [link](https://gateway-api.sigs.k8s.io/implementations/)

**Comment by shaneutt** [comment]
blocked on https://github.com/Kong/kubernetes-ingress-controller/issues/2231

**Comment by rainest** [comment]
https://github.com/Kong/docs.konghq.com/pull/3621 for basics and https://github.com/Kong/docs.konghq.com/pull/3622 for GWAPI.
