### ISSUE TITLE
Github Release of 2.2

### ISSUE THREAD

**Issue by scseanchow** [Kong/kubernetes-ingress-controller#2231]
### Problem Statement

Issue to track the Github release of KIC 2.2

### Acceptance Criteria

- [ ] https://github.com/Kong/kubernetes-ingress-controller/blob/main/RELEASE.md

**Comment by shaneutt** [comment]
waiting to give #2156 a chance to get into 2.2, but it's not a technical blocker so if we can't move it along in a couple days I'll release around it.
