### ISSUE TITLE
Update Go Kong Dependency to v0.26

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2233]
### Problem Statement

It seems that `go-kong` can't be cleanly upgraded to `v0.26`:

https://github.com/Kong/kubernetes-ingress-controller/pull/2228

Something seems to be breaking the knative integration tests.

The purpose of this task is to make the update manually.

**Comment by rainest** [comment]
Obsoleted by https://github.com/Kong/kubernetes-ingress-controller/pull/2246
