### ISSUE TITLE
Prevent KIC crash loop when waiting for Admin API availability

### ISSUE THREAD

**Issue by rbabyuk-vs** [Kong/kubernetes-ingress-controller#2274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I schedule new pods I see equally the same behaviour each time - pod fails to start and does 'restarts', kubectl reports minimum 2 restarts before pod is marked as 'running'. in events I see next:
```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m26s                  default-scheduler  Successfully assigned kong/kong-kong-55fc8bc5cf-k6hzr to gke-gke-cluster-dev-1
  Normal   Pulled     4m24s                  kubelet            Container image "kong:2.7" already present on machine
  Normal   Created    4m24s                  kubelet            Created container clear-stale-pid
  Normal   Started    4m24s                  kubelet            Started container clear-stale-pid
  Normal   Pulled     4m23s                  kubelet            Container image "kong:2.7" already present on machine
  Normal   Created    4m23s                  kubelet            Created container proxy
  Normal   Started    4m23s                  kubelet            Started container proxy
  Warning  BackOff    4m14s (x5 over 4m21s)  kubelet            Back-off restarting failed container
  Normal   Created    4m (x3 over 4m23s)     kubelet            Created container ingress-controller
  Normal   Pulled     4m (x3 over 4m23s)     kubelet            Container image "kong/kubernetes-ingress-controller:2.1" already present on machine
  Normal   Started    3m59s (x3 over 4m23s)  kubelet            Started container ingress-controller
```

pod startup take between 30-40 seconds
in logs for 'ingress-controller' container I see next:
```
4
time="2022-02-17T09:51:28Z" level=info msg="getting the kong admin api client configuration" logger=setup
3
time="2022-02-17T09:51:28Z" level=error msg="tag filtering disabled because Kong Admin API does not support tags" error="making HTTP request: Get \"https://localhost:8444/tags\": dial tcp 127.0.0.1:8444: connect: connection refused" logger=setup
2
Error: could not retrieve Kong admin root: making HTTP request: Get "https://localhost:8444/": dial tcp 127.0.0.1:8444: connect: connection refused
1
Error: could not retrieve Kong admin root: making HTTP request: Get "https://localhost:8444/": dial tcp 127.0.0.1:8444: connect: connection refused

```
(this is for 'failed' attempt)

### Expected Behavior

when I start new pod, it's started without extra restarts or failures

### Steps To Reproduce

```markdown
I use GKE and helm to deploy kong.
1. schedule deployment of pod
2. observe behaviour with kubectl get pods
or kubectl describe po $pod_name
```

### Kong Ingress Controller version

```shell
2.2.1(the same with 2.1 and 2.2)
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rainest** [comment]
Does this create issues for you in practice? This is expected: one of the first things the controller container needs to do is connect to Kong, and if that fails, the container dies. The Kong container tends to take longer to start than the controller container, so you'll see several controller start failures while Kong is coming online, and it will successfully connect and continue running once Kong is available.

**Comment by rbabyuk-vs** [comment]
my guess is that if ew can properly handle this then startup time for a container could be decreased.

**Comment by rbabyuk-vs** [comment]
@ltartarini right, good point, same here

**Comment by rohank2002** [comment]
Facing the same issue, it takes 2 restarts for the Kong ingress controller container before it is in Ready state.

**Comment by rohank2002** [comment]
One possible solution is adding a preStart hook or an init container to wait for the proxy to start. But the Kong Ingress Controller image from 2.X.X does not have bash in it.

**Comment by mflendrich** [comment]
Let's add a timed wait/retry mechanism when KIC tries to establish a connection with Admin API. That will allow Kong some time to start up alongside KIC.

The timeout could be flag-configurable.

**Comment by mflendrich** [comment]
Maintainers will not actively work on this in in the coming weeks, but we'd warmly welcome a PR. This is a fairly small change after all.
