### ISSUE TITLE
Ingress controller can't update service when using cassandra

### ISSUE THREAD

**Issue by stackedsax** [Kong/kubernetes-ingress-controller#231]
### Summary

When using Cassandra as a backend store, creating ingress rules works just fine.  When ingress rules are updated with a different `serviceName` or `servicePort`, the controller hits a foreign key violation in Cassandra.  Essentially, it can't delete the upstream because there is a target that still references it.

**Kong Ingress controller version**
0.3

**Kong or Kong Enterprise version**
CE 1.0

### Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
### Environment

- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`): 
- **Install tools**: 
- **Others**: I think this is cassandra-specific.  I didn't see that same problem occur on postgres.

### What happened
Ingress rule does not update and the controller spits out an error over and over again.

### Expected behavior
I imagine that the relevant targets should be removed before trying to delete the upstreams.

### Steps To Reproduce

1. Create an Ingress definition; `kubectl install` it
2. Change the `serviceName` or `servicePort` in that Ingress definition and `kubectl apply` it
3. Tail the logs of the controller
4. Observe this error:
```
Unexpected error deleting Kong upstreams and targets that depend on service 0xc000255d00: removing a Kong upstream: 400 Bad Request {"message":"an existing 'targets' entity references this 'upstreams' entity","name":"foreign key violation","fields":{"@referenced_by":"targets"},"code":4}
```

**Comment by stackedsax** [comment]
Oh, and to work around the problem when I run into it, I merely truncate the targets table.  Since I'm not creating anything manually, the ingress controller seems to recreate all the targets when I do this.  Just a quick fix, but might be useful for testing.

Like so:

```
kubectl exec kong-cassandra-0 -- cqlsh -k kong -e 'truncate targets;'
```

**Comment by hbagdi** [comment]
We will investigate this and get back to you.
