### ISSUE TITLE
Kong excessive configuration reloading and memory leak caused by secret creationTimestamp 

### ISSUE THREAD

**Issue by Elssuy** [Kong/kubernetes-ingress-controller#2320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When there is multiple secrets referencing the same TLS certificate with **same timestamp** (replicated by kubed for example) for the same SNIs. Kong-Ingress-Controller keeps reloading the configuration (roughly every 3 seconds). These excessive reloading coupled by a memory leak cause the pod to be OOMKilled by Kubernetes.

### Expected Behavior

When two TLS Secrets contains the same certificate for same SNIs, Kong-Ingress-Controller should keep the same UID in its configuration.

### Steps To Reproduce

```markdown
1. Deploy latest Kong chart with default `values.yaml`
2. Create 2 Secrets with same creationTimestamp and same TLS content
3. Create 2 Ingress having:
  - Same Tls.Hosts
  - Pointing each on it's own Secret created on step 2

K3D + Pulumi project to reproduce bug here: https://github.com/Elssuy/kong-ingress-controller-bug-config-reload
```

### Kong Ingress Controller version

```shell
v2.2.0
```

### Kubernetes version

```shell
Any Kubernetes version
```

### Anything else?

Kubed is a tool commonly used to replicate secrets on multiple namespaces. When used it syncs secrets across namespaces and sometimes sync `creationTimestamps`.
My initial solution of ordering certificates returned by `getCerts()` in `internal/dataplane/parser.go` doesn't seems to work... I'm counting on your codebase knowledge to help me through this.

**Comment by Elssuy** [comment]
#2338 solves the excessive reloading issue. Memory leak might not be resolved.

**Comment by erSitzt** [comment]
@Elssuy 

not sure if this is the same issue, but it sounds similar to what i just experienced (still v2.1 though)

I had old/orphaned cert-manager certificate requests which seem to have caused a loop with "updating sni.." messages in kong.
Ran up to 20Gb of mem when i saw it :)
Deleting the old certificate requests solved it.

**Comment by pmalek** [comment]
@erSitzt Thanks for your comment.

2.1 has been released a while ago (more than a year actually). If you'd like to upgrade at some point and report if you're seeing the same issue then we could take a closer look.
