### ISSUE TITLE
I install kong using helm,and enabled ingress,but I don't know which pod is ingress

### ISSUE THREAD

**Issue by 13567436138** [Kong/kubernetes-ingress-controller#233]
[root@node1 kong]# kubectl get pod -n kong -o wide
NAME                                  READY   STATUS      RESTARTS   AGE     IP               NODE    NOMINATED NODE
kong-kong-5fd54cfb4f-vhxmp            1/1     Running     0          5m41s   10.233.74.120    node4   <none>
kong-kong-controller-b89f66cb-9s7tg   2/2     Running     0          5m41s   10.233.102.175   node1   <none>
kong-kong-init-migrations-rfmpm       0/1     Completed   0          5m41s   10.233.102.174   node1   <none>
kong-postgresql-0                     1/1     Running     0          5m41s   10.233.102.176   node1   <none>

**Comment by Ngob** [comment]
I think git issues are reserved to issues. If you have question, it is best to go to https://discuss.konghq.com/ .
And, about your question, the ingress is in this pod kong-kong-controller-b89f66cb-9s7tg
kong-kong-init-migrations-rfmpm : Handle migration
kong-kong-5fd54cfb4f-vhxmp The gateway
kong-postgresql-0 : The database
Ingress documentation explain each role in a clear way, I think it is best to start here

**Comment by 13567436138** [comment]
thanks
