### ISSUE TITLE
Use `ingress-class` instead of `ingress.class` for Knative Ingress 

### ISSUE THREAD

**Issue by nak3** [Kong/kubernetes-ingress-controller#2344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Since Knative changed `ingress.class` to `ingress-class` by https://github.com/knative/networking/pull/522, the annotation should be updated to `kubernetes.io/ingress-class: "kong"`.

### Proposed Solution

- Replace all `ingress.class` in the code tree with `ingress-class`.

### Additional information

Note, the old style `ingress.class` is still supported in Knative for now.

**Comment by dprotaso** [comment]
nit: on the issue the labels you should do the lookup on are

`networking.knative.dev/ingress-class` and 
`networking.knative.dev/ingress.class`

not `kubernetes.io`
