### ISSUE TITLE
maintenance: rework parser translate upstream, service and route naming

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2347]
### Problem Statement

Currently we have some problems with how routes are named, and inconsistencies across different API types such as `Ingress` route names are appended with a `%d%d` which indicates the ordering of the rules and has multiple problems including causing config thrash upon rule re-ordering that doesn't need to happen (we looked at fixing this in TODO but decided against it at the time) and also ambiguity in cases like `1111` where it can potentially mean more than one thing.

The purpose of this task is to come up with a standard naming convention for these kong components that are shared across all API implementations instead of each API having it's own possibly unique way, and including things like object type and namespace name identifiers to make these strings easier to understand at a glance.

### Proposed Solution

- [ ] look for opportunities to generalize and create convention for naming upstreams, services and routes in parser translations
- [ ] effectively re-implement https://github.com/Kong/kubernetes-ingress-controller/pull/2222

### Additional information

https://github.com/Kong/kubernetes-ingress-controller/pull/2222 is an important point of reference for this as there were attempts made therein to make route naming conformant and easy to understand at a glance across all API types.

### Acceptance Criteria

- [ ] as a developer the naming of upstreams, services and routes that are generated from KIC and posted to Kong are clear, concise and all APIs follow the same pattern.

**Comment by mflendrich** [comment]
Closing as stale - the landscape has changed significantly since this problem was originally discovered. We can reopen and/or suggest targeted improvements where they feel appropriate.
