### ISSUE TITLE
Error with plugin in 0.3.0

### ISSUE THREAD

**Issue by salamando** [Kong/kubernetes-ingress-controller#235]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.3.0

**Kong or Kong Enterprise version**
1.0.3

### Kubernetes version
1.9
**paste `kubectl version` output**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
Error info when create or patch kongplugin
"400 Bad Request {"message":"3 schema violations (config.blacklist: field required for entity check when updating; config.whitelist: invalid cidr range: Invalid IP; run_on: required field missing)"
400 Bad Request {"message":"schema violation (config.whitelist: expected an array)","name":"schema violation","fields":{"config":{"whitelist":"expected an array"}},"code":2}
 400 Bad Request {"message":"2 schema violations (config.blacklist: field required for entity check when updating; run_on: required field missing)","name":"schema violation","fields":{"run_on":"required field missing","config":{"blacklist":"field required for entity check when updating"}},"code":2}"

### Steps To Reproduce

1.add run_on in CRD.
2.Testing for KongPlugin CRD for kong 1.0.3

**Comment by salamando** [comment]
Expect upgrade.
Thx.

**Comment by hbagdi** [comment]
Could you share your `KongPlugin` CRD? It seems like a config issue.
`run_on` field is currently missing in the CRD but that doesn't prevent you from configuring Kong plugins.

**Comment by hbagdi** [comment]
Please re-open if problem persists.

**Comment by salamando** [comment]
> Please re-open if problem persists.

Thanks for reply.

I still use 0.2.2 for now.

I will have a test for next version.
