### ISSUE TITLE
Fix typos in Dockerfile

### ISSUE THREAD

**Issue by krish7919** [Kong/kubernetes-ingress-controller#2377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

https://github.com/Kong/kubernetes-ingress-controller/blob/main/Dockerfile#L14 and https://github.com/Kong/kubernetes-ingress-controller/blob/main/Dockerfile#L37 are redundant with a repeat of `COPY pkg/ pkg/` lines in the Dockerfile.

**Comment by shaneutt** [comment]
Thanks for the report :+1: I've created #2378 to resolve these.
