### ISSUE TITLE
Implement AllowedRoutes kinds filters

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2408]
https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.AllowedRoutes include two filters, `namespaces` and `kinds`. The former (implemented in #2389) restricts the namespaces a controller can ingest routes from, the latter restricts which kinds (e.g. HTTPRoute, UDPRoute) a listener can ingest routes from.

This was not implemented along with namespace filters because it is of limited use at present: there are not currently listeners that support more than one kind of route (e.g. HTTP and HTTPS listeners can only support HTTPRoute, TCP listeners can only support TCPRoute, etc.) and there is no reason to make a filter that excludes the single route kind a listener can handle, or to make a filter that prevents a listener from ingesting route kinds it cannot handle.

We expect this to be useful in the future if additional route kinds are added for some listeners, e.g. if a future version adds GRPCRoutes handled by an HTTPS listener. We should implement this in the same milestone as those route types.

**Comment by mflendrich** [comment]
This may be a useful feature when we add GRPC support: https://github.com/Kong/kubernetes-ingress-controller/issues/2420

**Comment by mflendrich** [comment]
Blocked on GRPCRoute (or any other route type that would benefit from this) support in KIC.
