### ISSUE TITLE
Rewrite translation of Ingress spec to Kong resources

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#241]
## Problem

Currently, Ingress Controller takes in all the Ingress rules and translates them into Server and Location blocks, very similar to how Nginx is configured. This is the case because this controller was forked from the nginx ingress controller and then updated to get it to work with Kong.

This results in a few problem
- Kong is much more dynamic in nature and has different proxying capabilities than Nginx. Translating Ingress rules into Server, Upstream, Location block limits us in using all features of Kong, like method based routing (#202)
- Kong not only has proxying capabilities but lets you runs custom code in form of plugins, which can be configured on various routing levels. We run into problem when we store this meta into coarse Server and Location blocks.

## Solution

Translate Ingress rules, along with associated KongIngress objects directly into Kong resources.
This can capture all Kong specific configuration properties and leverage Kong's declarative configuration capabilities.

**Comment by eshepelyuk** [comment]
Is this issue released ? since I can see the corresponding PR is already closed

**Comment by hbagdi** [comment]
@eshepelyuk 0.4.0 release coming up soon (a few days) which will include these changes.

**Comment by eshepelyuk** [comment]
@hbagdi does this mean #244 will be closed too ?

**Comment by hbagdi** [comment]
@eshepelyuk Yes, the support for it is already landed in `next` branch.
There is a Docker image for the Ingress controller tagged `0.4.0-rc0` published if you would like to give it a go.

**Comment by eshepelyuk** [comment]
Thanks for reply, will wait until features will be closed :)
