### ISSUE TITLE
Allow custom tags on all entities managed by KIC

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Context:
- https://github.com/Kong/kubernetes-ingress-controller/issues/1437

For credentials (and other types of objects created by KIC in Kong Admin API), allow the user to set custom tags.

### Acceptance Criteria

- [ ] As a user of KIC I can set tags on a secret corresponding to a Kong consumer set of credentials. That tag will be propagated to the entity created in Kong.
- [ ] The same, in a less specified manner, for other types of objects created by KIC in Kong.

**Comment by mflendrich** [comment]
Closing as won't fix - we're happy to reconsider this decision. Please speak up if you're interested in this feature.

**Comment by gallolp** [comment]
@mflendrich would you be willing to take a look at #3198 and maybe reconsider adding support for tagging. Many thanks in advance!
