### ISSUE TITLE
Promote `UDPIngress` from `v1beta1` to `v1`

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The UDPIngress CRD has a v1beta1 `apiVersion` today.

I think that this API is sufficiently proven today to justify its promotion to `v1`. This issue tracks the promotion.

### Proposed Solution

- Create a `v1` apiversion in the UDPIngress CRD
- Update KIC to support the v1 UDPIngress version (functionally equivalent to what v1beta1 is today)
- Make v1 the default/future code path and write it so that v1beta1 can be removed at some point in time easily

### Acceptance Criteria

- [ ] UDPIngress CRD supports both v1beta1 and v1 apiversions
- [ ] KIC treats v1 UDPIngress same as v1beta1 today
- [ ] Test coverage for v1 becomes no less than test coverage for v1beta1 (unit, integration, e2e)
- [ ] Upgrade path (enabling support for v1 CRDs) is well known and documented (also for users of the helm chart - updates of CRDs are notoriously painful)
- [ ] A deprecation plan for v1beta1 UDPIngress exists

**Comment by shaneutt** [comment]
Blocked waiting for `UDPRoute` GA release, in 1 year if this is still blocked revisit and consider moving `UDPIngress` to v1.
