### ISSUE TITLE
Add option to skip syncing consumers

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#243]
Many users use Kong Ingress Controller to configure routing and plugins but also wish to use consumers and credential endpoints dynamically.

This enables users to decoratively manage most of Kong but dynamic entities like Consumers, which might be created via an API call from another service to work.

This also keeps the sync overhead for use-cases with a large number of consumers, where declarative configuration (for consumers) is not required.

**Comment by devopsop** [comment]
I would love to be able to use the admin API to create consumers once again. Kong doesn't like that and it deletes all my consumers. I will be waiting for that "feature".

**Comment by hbagdi** [comment]
Consumers managed by the Ingress Controller will be tagged. Any consumer created via Admin API will not be deleted/updated with Ingress Controller V0.5.0.
