### ISSUE TITLE
Add support for Kong1.1 DB less mode

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#244]
Kong 1.1 allows users to run Kong without a database.

The configuration is then supplied using a configuration file.

This requires translating all the resources into a Kong resource object and then rendering a YAML out of it.

**Comment by hbagdi** [comment]
Currently blocked on #241

**Comment by MilanDasek** [comment]
@hbagdi well, so I can probably close this: https://github.com/helm/charts/issues/12704

**Comment by hbagdi** [comment]
@MilanDasek Yes, please close the other issue. Thanks!

**Comment by hbagdi** [comment]
This is now available with 0.4.0 release!

**Comment by eamonnmcevoy** [comment]
Can the current helm chart be used for this or does it need updated also? I tried setting `env:database: off` in values.yaml but it doesn't seem to work. (chart version 0.9.9)

**Comment by hbagdi** [comment]
Helm chart support for db-less is under works.
Meanwhile, use the YAMLs to try it out.
Stay tuned!

**Comment by MilanDasek** [comment]
@hbagdi will there be an upgrade path for a helm chart? 
`helm upgrade -f myKongValuesDBless.yaml kong stable/kong`

or we will need delete helm chart and install from scratch?

When we can expect chart compatible with db-less feature?

thanks

**Comment by hbagdi** [comment]
Hello @MilanDasek 

Helm chart for DB-less mode is almost done (pending CI issue):
https://github.com/helm/charts/pull/13475

The upgrade path will be to deploy the Kong Ingress Controller in dbless mode in parallel to the previous installation and then cut the traffic over.
