### ISSUE TITLE
Consolidate Gateway resources and helpers used in tests

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2461]
Currently, Gateway API-related tests typically start by creating a Gateway, waiting for the controller to mark it ready, and then proceeding with whatever they're actually doing (e.g. ensuring HTTPRoutes work as expected).

The code to handle this is copy pasta and can probably be replaced by setting up a standard Gateway/GatewayClass instance during suite setup and linking individual tests Routes to it. Tests that have unique requirements for their Gateways can always create their own, as multiple Gateways can coexist fine.

Migration away from pre-provisioned Gateways and actually spawning Kong instances in response to the creation of a Gateway object will affect this, but probably not significantly. We'd create a standard Gateway at the start of all tests, wait for an operator to create a Deployment for it, and use that for most tests. Snowflake tests would still create their own Gateway resource, but it'd result in an actual separate Kong instance, so they'd have to further look up its proxy Service.

Various Route types further have helper functions to check that they are linked to Gateway resources successfully. AFAIK the status subsections are identical, and the functions are largely type-agnostic. However, they currently use the single-type `TCPRoute.Get()` and similar, so we'd need to find some way to rip that out.

Unsure if we want to do this for the Gateway tests themselves, i.e. `TestUnmanagedGatewayBasics()` and such, but we should consider it when consolidating the code used for Route tests.

# Additional Notes

- [ ] cleanup all TODO items in code which reference this issue before considering this resolved

**Comment by mflendrich** [comment]
Removing the `nice-to-have` label because @mlavacca started working on this and it would otherwise be hidden from the board by default.
