### ISSUE TITLE
set multiple rate limit plugins for one service with two consumer is not working

### ISSUE THREAD

**Issue by eqmcc** [Kong/kubernetes-ingress-controller#247]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.3.0

### Kubernetes version

kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-28T15:20:58Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

### Environment

"CentOS Linux 7 (Core)"

### What happened
I'm trying to set two consumers with two different rate limit but failed:
I applied bellow yaml files:

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer1
  namespace: nginx-kong-test
username: consumer1

---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer2
  namespace: nginx-kong-test
username: consumer2

---
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: credential1
  namespace: nginx-kong-test
consumerRef: consumer1
type: key-auth
config:
  key: "111"

---
apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: credential2
  namespace: nginx-kong-test
consumerRef: consumer2
type: key-auth
config:
  key: "222"

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rl-consumer1
  namespace: nginx-kong-test
enabled: true
consumerRef: consumer1
config:
  second: 1
plugin: rate-limiting

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rl-consumer2
  namespace: nginx-kong-test
enabled: true
consumerRef: consumer2
config:
  second: 10
plugin: rate-limiting

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-consumer1
  namespace: nginx-kong-test
disabled: false
plugin: key-auth
config:
  hide_credentials: true

---  
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-consumer2
  namespace: nginx-kong-test
disabled: false
plugin: key-auth
config:
  hide_credentials: true

and added annotations to the service as bellow:
plugins.konghq.com: key-auth-consumer1, rl-consumer1, key-auth-consumer2, rl-consumer2

the result is I can see only consumer2 is attached to the rate limit plugin

      NAME  SCOPE APPLY TO  CONSUMER  CREATED   
      key-auth  services  c64e1725-a962-47e1-b1f9-251cc8e8608e  All consumers Mar 15, 2019  
      rate-limiting services  c64e1725-a962-47e1-b1f9-251cc8e8608e  1b249830-4638-11e9-83c5-fa163ebda1b8  Mar 15, 2019  

### Expected behvaior
rate limit have two rules suggesting each binding with a consumer

### Steps To Reproduce
apply above files

**Comment by hbagdi** [comment]
@eqmcc Could you correctly format the YAML files (using code formatting via Markdown)and paste them here or in a Github Gist so that I can reproduce the issue locally? Thanks!

**Comment by eqmcc** [comment]
@hbagdi thanks for pick this up, you can find the yaml at bellow gits address:
https://gist.github.com/eqmcc/8616fe520ddf5903adb65312dcc60f4f

**Comment by eqmcc** [comment]
@hbagdi any updates from your side? any more information needed?
Thanks

**Comment by hbagdi** [comment]
This doesn't work because Ingress Controller doesn't support consumer-only plugin.
You can solve the problem if you associate the plugin objects with an Ingress or Service resource.


I've opened up #250 to track this work.

**Comment by eqmcc** [comment]
@hbagdi thanks for the update!
