### ISSUE TITLE
kong nginx-ingress not support http2 upstream

### ISSUE THREAD

**Issue by ly123-liu** [Kong/kubernetes-ingress-controller#2473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

we use kong-nginx-ingress as gateway, and we have http2 server, can kong support http2 protocol with upstream http2 servers ?

kong docs supports backend protocols only for http/https/grpcs/grpc/tcp/tls, see docs in https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/#konghqcomprotocols

we tests client use http2 , and found kong can handle http2 ,but kong proxy url to upstream server with http1.1

this is a trafficecapture on serversides:

![WeChatWorkScreenshot_bc29bf84-b969-4bf9-b1ea-666f806e0d68](https://user-images.githubusercontent.com/57338370/167360877-d4d2a089-9561-47fa-a978-c00eb92a7e15.png)

client side http2 request

```
$ curl -0 --http2 http://nginx/yevents/v1/topic/broker.invest_plan/events -X POST --header "Content-Type: application/json" -d '[{xxxxx}]' -vv
Note: Unnecessary use of -X or --request, POST is already inferred.

Trying 172.31.20.230...
TCP_NODELAY set
Connected to nginx (172.31.20.230) port 80 (#0)
POST /yevents/v1/topic/broker.invest_plan/events HTTP/1.1
Host: nginx
User-Agent: curl/7.58.0
Accept: /
Connection: Upgrade, HTTP2-Settings
Upgrade: h2c
HTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA
Content-Type: application/json
Content-Length: 704

upload completely sent off: 704 out of 704 bytes
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Content-Length: 750
< Connection: keep-alive
< Date: Sat, 07 May 2022 05:02:43 GMT
< X-Kong-Upstream-Latency: 21
< X-Kong-Proxy-Latency: 1
< Via: kong/2.4.1
<
```

can kong support http2 upstream ? and how ? thanks

### Expected Behavior

expected kong-nginx-ingress-controller can proxy the same http2 request to http2 server

### Kong Ingress Controller version

```shell
kubernetes-ingress-controller:1.3
kong:2.4.1
```

### Kubernetes version

```shell
kubernetes  1.20 / 1.18
```

**Comment by shaneutt** [comment]
Thanks for your question @ly123-liu.

NGinx (the underlying technology behind Kong Gateway) does not support HTTP2 for upstreams unless specifically for GRPC as the community has previously decided that there wasn't a reason to do so.

Here are some related articles related to this decision:

- https://trac.nginx.org/nginx/ticket/923
- https://www.nginx.com/blog/http2-module-nginx/#QandA

Let us know if this helps and if you have any further questions or comments on this issue.
