### ISSUE TITLE
Configuration of the plugin is no problem, But it doesn't work properly.

### ISSUE THREAD

**Issue by vincent927** [Kong/kubernetes-ingress-controller#249]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
```
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.3.0
```
**Kong or Kong Enterprise version**

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```
Linux test1.eyingchina.com 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- **Install tools**:
helm
- **Others**:

### What happened

After I refer to this  [document](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/minikube.md) the plugin does not work properly.
But the configuration of the plugin is no problem.The response header does not have X-RateLimit-Limit-*

![image](https://user-images.githubusercontent.com/10399425/54595535-c516b080-4a6d-11e9-9e6c-d99932ec6190.png)

![image](https://user-images.githubusercontent.com/10399425/54595999-c1cff480-4a6e-11e9-9bcf-958b790b3242.png)

![image](https://user-images.githubusercontent.com/10399425/54595480-aca69600-4a6d-11e9-8483-8dbf5009beb9.png)

**Comment by hbagdi** [comment]
@vincent927 Can you share logs of the Ingress Controller?

**Comment by vincent927** [comment]
> @vincent927 Can you share logs of the Ingress Controller?

Thanks!
It seems to be my problem, I am directly accessing through ingress, and changing to kong-proxy access will not be a problem.
But I still have a question, how is kong-proxy exposed? If I have multiple domain names that need to be proxyed

**Comment by hbagdi** [comment]
>  But I still have a question, how is kong-proxy exposed? If I have multiple domain names that need to be proxyed

Assuming you're running in a cloud environment, you will need to expose it as a LoadBalancer service and then for each domains you're proxying, update the DNS to point to the LoadBalancer's IP (A records) or DNS name(CNAME record).

**Comment by vincent927** [comment]
@hbagdi Tks a lot!  I got it .
