### ISSUE TITLE
Add support for Consumer only plugins

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#250]
Currently, plugins can be defined on route level, service level or a combination of route+consumer and service+consumer.

The controller should be able to configure consumer-only plugin.

**Comment by hbagdi** [comment]
Added with #306 and will be available with Kong Ingress Controller 0.5.0, set to be released mid June.

**Comment by WoodyFleurant** [comment]
@hbagdi if I understand correctly it's not possible right now to have
`plugins.konghq.com: key-auth,acl-group` ?

**Comment by hbagdi** [comment]
No, it is possible to do that.
