### ISSUE TITLE
Change admission failure policy

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Currently, the admission webhook being offline (because the controller is down or not fully started) prevents updates to any Secret resource.

### Proposed Solution

Change the [failure policy](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy) from `Fail` to `Ignore`. This will allow Secret updates (and other configuration--this setting is global across the controller) that result in broken configuration, but falling into that window and being broken is hopefully unlikely.

### Additional information

Broken out of https://github.com/Kong/kubernetes-ingress-controller/issues/2431.

### Acceptance Criteria

- [ ] The admission controller does not reject any configuration, valid or otherwise, if it is offline.
- [ ] The admission controller still rejects invalid configuration if it online.

This is Kubernetes functionality rather than controller functionality, and requires an abnormal configuration state (the conroller VAWC resource is present, but the controller is not running). Because it would therefore require a dedicated E2E test only to test API Server behavior, please do not create a new test and instead provide documentation of successful manual validation along with the PR.

**Comment by jrsmroz** [comment]
Seems like this should be changed in [helm chart ](https://github.com/Kong/charts/blob/684ca0ccd6578248ba270f640122788ba4939dc2/charts/kong/values.yaml#L495) and [script used for testing  ](https://github.com/Kong/kubernetes-ingress-controller/blob/main/hack/deploy-admission-controller.sh). I don't see other places it's being set.

**Comment by shaneutt** [comment]
> Seems like this should be changed in
> 
>     * [helm chart ](https://github.com/Kong/charts/blob/684ca0ccd6578248ba270f640122788ba4939dc2/charts/kong/values.yaml#L495)
> 
>     * [operator helm chart ](https://github.com/Kong/kong-operator/blob/f4b6ba65a7572931cfe1449f2907dc75e61c3cb6/helm-charts/kong/values.yaml#L434)
> 
>     * [charts-private](https://github.com/Kong/charts-private/blob/dedd27073980e866bd97e2187600f1a60f9af453/charts/kong/values.yaml#L495)
> 
>     * [script used for testing  ](https://github.com/Kong/kubernetes-ingress-controller/blob/main/hack/deploy-admission-controller.sh). I don't see other places it's being set.
> 
>     * [Documentation](https://github.com/Kong/charts/blob/684ca0ccd6578248ba270f640122788ba4939dc2/charts/kong/README.md), indicating new default value
>       -[Custom plugins init repo](https://github.com/Kong/custom-plugins/blob/be5c5c220d93bc030db448c8b1f9337897f1b7aa/deploy/values.yaml#L191)
> 
>     * https://github.com/Kong/k8s-lab-resources/blob/988d985d6297af4aad6491759adb3d99ebd9fe2a/helm-values/kong/sleepy-rhino.yaml#L430
> 
>     * probably more repos
> 
> 
> Not sure about:
> 
>     * [multi-cloud-blog repo](https://github.com/Kong/multi-cloud-blog/blob/8448253c441a8e41c2ef0a1a6ca724cee1a1ce26/kong/values.yaml#L200)
> 
>     * Demo tools for sales

The multi-cloud-blog repo I'm pretty sure is defunct. As for demo tools for sales, perhaps. But let's at least just get started with the Helm chart for now.
