### ISSUE TITLE
Not working on EKS with EC2 machine t4g

### ISSUE THREAD

**Issue by neerajyadav** [Kong/kubernetes-ingress-controller#2513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
The container `ingress-controller` in pod `ingress-kong` keep failing.
Logs show `exec user process caused: exec format error`

### Expected Behavior

Should create KIC and expected to run smoothly

### Steps To Reproduce

```markdown
1. Create EKS cluster with node group of type `t4g.large`.
2. Run command `kubectl create -f https://bit.ly/k4k8s` on the cluster.
3. The container `ingress-controller` in pod `ingress-kong` keep failing.
Logs show `exec user process caused: exec format error`
```

### Kong Ingress Controller version

```shell
v2.3.1
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-14c7a48", GitCommit:"35f06c94ad99b78216a3d8e55e04734a85da3f7b", GitTreeState:"clean", BuildDate:"2022-04-01T03:18:05Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

Switched node from `t4g.large` to `t3a.medium`. It works fine.
There seems to be an issue with EC2 instances of type `t4g`.

**Comment by neerajyadav** [comment]
Yes @shaneutt I was aware of that. `t4g` instance are latest from aws and offer better performance and cost benefits. That's why I choose `t4g`.

**Comment by pmalek** [comment]
Hi @neerajyadav 

At the moment we're not offering ARM/ARM64 builds: https://hub.docker.com/r/kong/kubernetes-ingress-controller/tags

There's [an issue](https://github.com/Kong/kubernetes-ingress-controller/issues/2500) that tracks the effort.

**Comment by pmalek** [comment]
BTW: I forgot to mention that if you feel up for it @neerajyadav you can try our [nightly builds](https://hub.docker.com/r/kong/nightly-ingress-controller/tags) which already include ARM64 builds.
