### ISSUE TITLE
Refactor the translators in internal/dataplane/parser

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2516]
### Problem Statement

The translator logic inside of `internal/dataplane/parser/` (e.g. `translate_ingress.go`) is responsible for translating Kubernetes objects (like `Ingress`) into the underlying Kong Admin API objects (like `kong.Service`, `kong.Route`, and `kong.Upstream`) that configure the routing that supports the Kubernetes definition. The structure of the translators has historically originated from `v0` of the ingress controller and is overdue for a significant refactoring as there are multiple maintenance problems:

- much of the logic is large nested blocks of code which are hard to read and make changes
- documentation and comments are sparse throughout
- there's a lot of copy-pasted code across all translators for all types

The purpose of this task is to significantly refactor these translators according to the problems reported above.

### Proposed Solution

An alternative implementation was added in the (at the time `Alpha`) feature gate `CombinedRoutes` which broke translation down into a single function backed by a private index object with smaller discreet methods and supporting functions. For solving this issue we should consider whether that style can be co-opted and become the new style for translators in general, OR if we prefer to take a different route after further study. In either case code re-use is very important and we need to try to optimize implementations to reduce the copy-paste problem we started with and perhaps consider making generic functions which serve the various types.

### Additional information

This issue originates from a comment in a PR https://github.com/Kong/kubernetes-ingress-controller/pull/2507#discussion_r881779453

### Acceptance Criteria

- [ ] as a maintainer of the KIC I can update the translation implementation for multiple types in one body of code, rather than having to make the same change multiple times in multiple places
- [ ] as a maintainer of the KIC the dataplane translation code can be followed easily with plentiful godocs and all public symbols are documented.

**Comment by afzal442** [comment]
I would like to look into it. Thanks.

**Comment by afzal442** [comment]
hi there,
> For solving this issue we should consider whether that style can be co-opted and become the new style for translators in general, OR if we prefer to take a different route after further study. 

Could you give any pointers here on how I can approach this with any use case or template?

**Comment by mflendrich** [comment]
Closing as stale.
