### ISSUE TITLE
Check and handle cross-Gateway compatibility

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2559]
The unmanaged Gateway implementation within the controller will ingest any Gateway resource of the correct class. Because we cannot separate Gateways by address, we de facto always combine them Combination is [permissible](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GatewaySpec) but with some limitations.

With https://github.com/Kong/kubernetes-ingress-controller/issues/2557, these Gateways can potentially include conflicting or incompatible configuration, though whether this is an issue is sometimes ambiguous. For example:

- Defining multiple L4 Listeners for the same port is not permissible under compatible Listener rules, and Listener validation within a single Gateway rejects it. However, two Gateways with L4 Listeners with the same port **and** protocol may be permissible and desirable.
- Defining multiple L7 Listeners is permissible if they use unique hostnames. Without cross-Gateway validation, GatewayA and GatewayB can both define HTTPS Listeners for `example.com`, and we will have no means to determine which Listener's TLS configuration should be the source of the certificate we bind to `example.com`

This is maybe nice-to-have though not marked as such initially: it becomes a moot point if we migrate entirely over to the operator-based model where we spawn independent Kong instances for each Gateway. It may be worth considering then still (though it becomes much more of a nice-to-have) to see if we can combine Gateways to conserve resources.

Stub AC:

- [ ] Remove [TODO](https://github.com/Kong/kubernetes-ingress-controller/blob/da63a94ccdcdc7714cb05073e9fda5f57407bf12/internal/controllers/gateway/gateway_controller.go#L327)

**Comment by shaneutt** [comment]
Placing in milestone 3 for now, as we'll need to at least make some sort of decision about this before our beta release.

**Comment by rainest** [comment]
It does not look like you'd lose anything significant by only allowing a single Gateway if you'd ultimately collapse them all to a single Gateway anyway. https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GatewaySpec includes only Listeners and addresses. We don't support address configuration in unmanaged mode anyway, and both requiring you place all Listeners into a single Gateway  and combining the Listener sets from multiple Gateways ultimately results in equivalent configuration.

AFAICT the only case where you'd need separate Gateways is if you do want to handle incompatible Listener sets, e.g. multiple TCP Listeners on port 22, by having them on separate addresses. We can't support that under any scenario with a single Kong instance, so we may as well just deny multiple Gateways from the start rather than trying the more complicated per-Listener compatibility checks proposed here initially.

**Comment by mflendrich** [comment]
KIC documentation explicitly disallows configurations with more than one gateway in GatewayClass. Closing as this is not a problem now (with no multiple gateways in GatewayClass).
