### ISSUE TITLE
Coverage reports on codecov are broken

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#2569]
It seems that coverage reports even though that are successfully uploaded to codecov ([example](https://github.com/Kong/kubernetes-ingress-controller/runs/6858906002?check_suite_focus=true#step:3:79)) are not properly accounted for ([example](https://codecov.io/gh/Kong/kubernetes-ingress-controller/commit/eb4f8283d06267001180bb01518b62f702fb662f)) and this error is presented to the user visiting codecov:

> There was an error processing coverage reports.

Commits view shows that something broke around couple of months ago: 
![image](https://user-images.githubusercontent.com/739996/173367579-55ff6204-10cf-483b-88fb-b787c0352f4d.png)

[Main repo view at codecov](https://app.codecov.io/gh/Kong/kubernetes-ingress-controller) show last update on August 5 2021:
![image](https://user-images.githubusercontent.com/739996/173367727-aaae4164-f8c0-416c-838a-4c37f0b053d9.png)

Pull requests seem to be accounted for but their coverage report statuses are set to "No report uploaded yet":
![image](https://user-images.githubusercontent.com/739996/173367989-3b706045-c49c-4bfd-9b2a-aaaad9b379c9.png)

### Acceptance criteria

- Codecov reports are working for PRs, i.e. are being added to PRs in comments (as it used to be the case?)

**Comment by pmalek** [comment]
Seems #3266 might fix this.

**Comment by mflendrich** [comment]
Closing as the problem seems to have been fixed.
