### ISSUE TITLE
Ensure that the nightly test run includes the release tests

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The experience releasing KIC 2.4 was that test failures (#2574) occured that weren't noticed before.

There is a [nightly test job](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/e2e.yaml) that currently [runs something different](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/e2e.yaml) than the [release job does](https://github.com/Kong/kubernetes-ingress-controller/blob/a5e45395a84f87618143af2838f581cce45a8405/.github/workflows/release.yaml#L214). Both are called "e2e" tests, causing confusion.

https://github.com/Kong/kubernetes-ingress-controller/issues/1605

### Proposed Solution

Ensure that the nightly CI job runs the exact same set of tests that the release job does.

This likely requires removing either the `test.e2e` make target or the [run-tests.sh](https://github.com/Kong/kubernetes-ingress-controller/blob/main/hack/e2e/run-tests.sh) script. because they are duplicates with overlapping purpose.

### Acceptance Criteria

- [ ] The nightly CI job runs the exact same set of tests that the release job does.
- [ ] If a release happens on the exact same `main` HEAD as the nightly job has run, no new test failures should occur and block the release unexpectedly.

**Comment by randmonkey** [comment]
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/2696513827 now the nightly build jobs include the same integration tests as in release action.
