### ISSUE TITLE
Catch the test case variables to prevent variable shadowing in unit tests

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#2607]
Most of our table driven unit tests goes in this format:
```
	for idx, tt := range cases {
		t.Run("case-name", func(t *testing.T) {
			// do something on tt
		})
	}
```
The loop iteration variable `tt` is used in the inner function, while `t.Run` runs the function in param in a separated goroutine. If we use `t.Parallel()` to run test cases in parallel, the variable inside may not be the same as expected:  https://stackoverflow.com/a/61101881 
So it is needed to add an assignment statement to catch `tt`, for example:
```
	for idx, tt := range cases {
                tt := tt
		t.Run("case-name", func(t *testing.T) {
			// do something on tt
		})
	}
```

**Comment by programmer04** [comment]
I've tested such a case and it's detected by linter, `loopclosure: loop variable tt captured by func literal (govet)`, [read more](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/loopclosure). Furthermore `looppointer` linter has been introduced in https://github.com/Kong/kubernetes-ingress-controller/pull/4429
