### ISSUE TITLE
Regression Testing with Kuma

### ISSUE THREAD

**Issue by doctorwu** [Kong/kubernetes-ingress-controller#2616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Changes to helm chart will occasionally break deployment of KIC when a service mesh is present. Having a regression tests greatly reduces risk of breaking changes.

### Proposed Solution

Create an automated deployment of GW, KIC and Kuma when a PR is created. If the environment stands up, proceed to next phase of the release cycle.

### Additional information

- [ ] needs https://github.com/Kong/kubernetes-testing-framework/issues/303

### Acceptance Criteria

As an end user, I consider it acceptable when you can deploy GW, KIC and Kuma without having to make unreasonable changes to the default values.yaml.

**Comment by mflendrich** [comment]
Testing covered by https://github.com/Kong/kubernetes-ingress-controller/pull/2635 and https://github.com/Kong/charts/pull/625.
