### ISSUE TITLE
Integration Test ServiceAccount Impersonation

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2617]
### Problem Statement

Historically in the integration tests we've used whatever `kubeconfig` was available to run the controller manager for the integration tests. Generally speaking this has meant we've run the integration tests with `cluster-admin` permissions. While we do test our explicit RBAC permissions in the E2E tests and this has otherwise caught permissions problems in the past, it would be an improvement to use these permissions for the integration tests as well for faster feedback.

### Additional information

The [Gateway Operator](https://github.com/kong/gateway-operator) has an example implementation of this, it uses impersonation to run the integration tests using the RBAC permissions present in `config/` in the test suite.

### Acceptance Criteria

- [ ] as a contributor if I make changes that require or include RBAC changes the integration tests will utilize those permissions so that I can get fast feedback if there's a problem.

**Comment by naveen0111** [comment]
Hi Shane, 

I am interested in contributing to the ingress-controller and planning to take this as my first so it will help me understand the environment and code base. 

Wondering if this link [Gateway Operator](https://github.com/kong/gateway-operator) is still valid? I tried to access it but it says page not found.

Thanks,
Naveen

**Comment by pmalek** [comment]
Hi @naveenyanamaddi 👋 

For the time being Gateway Operator repo is closed while our organization works on the wording for the license. When that's all figured out and we update the license you should be able to access it at some point. No ETA at the moment thought.

**Comment by shaneutt** [comment]
> Hi Shane,
> 
> I am interested in contributing to the ingress-controller and planning to take this as my first so it will help me understand the environment and code base.
> 
> Wondering if this link [Gateway Operator](https://github.com/kong/gateway-operator) is still valid? I tried to access it but it says page not found.
> 
> Thanks, Naveen

Hi @naveenyanamaddi, thank you for your interest!

As @pmalek said we need to make some final decisions about the Gateway Operator repository, but we do expect that source to be available in the future. For the moment however since you're interested (and because ultimately how to do impersonation with [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) is no secret, and it's pretty straightforward) I'll provide some examples here that should help get you started. This will be broken down into the two main jobs that need to be performed: deployment of the  RBAC rules, service accounts and bindings needed; and then the code that adds the impersonation to use the service account on test runs.

### Installing RBAC rules and creating a service account and role bindings

The test clusters that are initialized by the integration test suite don't currently get the service accounts and RBAC permissions deployed to them, they only get the CRDs deployed here:

https://github.com/Kong/kubernetes-ingress-controller/blob/6a8f4be60fb31757c53828c44814e886f427dc6d/internal/util/test/controller_manager.go#L49

We'll need to add code that deploys the RBAC rules (probably adjacent to the `DeployCRDs` code above is fine, and provides a decent example of how to do this) from the following location:

https://github.com/Kong/kubernetes-ingress-controller/tree/main/config/rbac

Then the `ServiceAccount` and the relative role bindings can be done in Go code in the test suite setup.

### Adding impersonation to the controller manager client

Impersonation is handled via a `k8s.io/client-go/rest.Config` object (which `controller-runtime` uses to configure its own clients). When starting a `controller-runtime` controller manager you can override the client that `controller-runtime` would create by default by providing a `cluster.NewClientFunc`, which can be used to inject the impersonation that you want:

```go
newClientFunc := func(cache cache.Cache, config *rest.Config, options client.Options, uncachedObjects ...client.Object) (client.Client, error) {
	config.Impersonate.UserName = "system:serviceaccount:kong-system:controller-manager"

	c, err := client.New(config, options)
	if err != nil {
		return nil, err
	}

	return client.NewDelegatingClient(client.NewDelegatingClientInput{
		CacheReader:       cache,
		Client:                    c,
		UncachedObjects: uncachedObjects,
	})
}
```

These imports will be needed for that:

```go
import (
	"k8s.io/client-go/rest"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/client"
)
```

And then ultimately that client builder function will be passed as an option to create the new `controller-runtime` manager:

```go
        mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
                // other options, e.t.c.
                NewClient:              cfg.NewClientFunc,
        })
```

(where the import for `ctrl` is aliased: `ctrl "sigs.k8s.io/controller-runtime"`)

Now one of the tricky parts is that in the ingress controller _today_ we don't call `NewManager` directly in the test suite, we actually just piggy-backed on the cobra command:

https://github.com/Kong/kubernetes-ingress-controller/blob/6a8f4be60fb31757c53828c44814e886f427dc6d/internal/util/test/controller_manager.go#L82

So as a piece of maintenance we'll need to replace that call with the equivalent underlying calls instead of calling the `rootcmd` wrapper, but then it should be pretty pluggable to add the impersonation after that.

---

If you continue to be interested in taking this one on, please feel free to reach out for help in this issue OR in `#kong` in [Kubernetes Slack](https://kubernetes.slack.com) and we would be happy to provide further guidance!

**Comment by parkjeongryul** [comment]
I have introduced the Gateway API into our Kubernetes system using KIC. 
If there are still parts that need to be implemented, I'm interested in contributing to KIC project. 

I think this issue is pending now, so i want to take this as my first.
Can i give it a try?
