### ISSUE TITLE
Capture diagnostic artifacts for Kubernetes clusters in CI after failures

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2625]
### Problem Statement

When tests fail in CI we currently have to try and reproduce those locally and check the state of the reproduction cluster to diagnose them currently. This however doesn't always work when the problem is transient, or environment specific. The purpose of this task is to make it possible to capture diagnostic data in Github Actions when these failures occur so that we can do postmortem analysis without having to build a local reproduction.

### Prerequisites

- [ ] https://github.com/Kong/kubernetes-testing-framework/issues/306

### Acceptance Criteria

- [ ] when a CI run fails, a diagnostic dump of the clusters API state is emitted to the Github Actions artifacts for a human operator to download and review.
- [ ] statuses and events are captured for all resources in the cluster
- [ ] logs are captured for all pods in the cluster
- [ ] logs are captured for all cluster components (apiserver, controller-manager, kube-proxy, etc)

**Comment by jrsmroz** [comment]
E2E tests already dump the diagnostics. It was added by https://github.com/Kong/kubernetes-ingress-controller/commit/f9c3dcfa25543d541da440c764ae22171064dddf

**Comment by lahabana** [comment]
This is still the state of things

**Comment by pmalek** [comment]
After a chat with @lahabana I've noticed that regular integration tests do dump diagnostics (example: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/12006829482/job/33466243618#step:9:29). It's just the isolated suite that doesn't. 

#6771 should fix that and close this issue.
