### ISSUE TITLE
Flaky `TestIngressClassNameSpec`  test failure

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#2637]
```
    ingress_test.go:305: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/ingress_test.go:305
        	Error:      	Condition never satisfied
        	Test:       	TestIngressClassNameSpec
```

Relevant assertion that failed: https://github.com/Kong/kubernetes-ingress-controller/blob/e4372f09da4a781e6b9a4ddb11636ab2b5866e5b/test/integration/ingress_test.go#L305-L322

Relevant CI failure: https://github.com/Kong/kubernetes-ingress-controller/runs/7145412694?check_suite_focus=true

**Comment by pmalek** [comment]
Again: https://github.com/Kong/kubernetes-ingress-controller/runs/8211944549?check_suite_focus=true#step:6:3217

**Comment by jrsmroz** [comment]
Let's see if buildpulse if detects any flakes in `TestKongIngressEssentials`

**Comment by pmalek** [comment]
> Let's see if buildpulse if detects any flakes in `TestKongIngressEssentials`

Didn't you mean to post it in https://github.com/Kong/kubernetes-ingress-controller/issues/2632 😅 ?
