### ISSUE TITLE
Load test mesh detection

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2647]
Ensure that mesh detection does not impact performance in clusters with lots of services and/or pods.

Acceptance criteria
- [x] Measured performance of mesh detection in a cluster with 1k-10k-100k services (can be headless and with no endpoints)
- [x] Measured performance of mesh detection in a cluster with 1k-10k-100k pods (can be unschedulable)
- [x] Comparison of resource usage between mesh detection on & off
- [x] Test results documented in a comment of this issue

**Comment by randmonkey** [comment]
Test environment: microk8s 1.24.0 on Thinkpad T14s with 8 cores, 32 GiB memeory.
 
The load is in CPU/memory format, the result comes from the value returned from `kubectl top nodes` and `kubectl top pods -n kong` at the starting time of KIC pod. 

number of services | total duration of mesh detection | duration of detecting mesh deployment | duration of detecting whether KIC is running under mesh | duration of detecting service distribution running under each mesh | load of node(with detection) | load of node (without detection) | load of KIC pod(with detection) | load of KIC pod(without detection)
------------------ | --------------- | -------------------------- | ----------------------- | ------------------- | -------------- | ---------------------- |  --------- | ------- 
 < 10                         | 28.8ms | 10.6 ms | 2.6 ms  | 15.6 ms | 200m/4Gi | 194m/4Gi | 2m/100Mi | 2m/100Mi |
 1k(headless,no endpoints)    | 157 ms | 114 ms  | 4.9 ms  | 38.5 ms | 300m/8Gi | 259m/7.5Gi |  3m/260Mi | 3m/160Mi |
 10k (headless,no endpoints)  | 1.32 s | 952 ms  | 6.2 ms  | 360 ms  | 418m/10Gi |301m/9.5Gi | 3m/371Mi | 3m/255Mi |
 100k (headless, no endpoints)  | 27.7 s | 12.1 s  | 58 ms   | 15.6 s | 3234m/18.6Gi | 1700m/17.2Gi | 3m/1387Mi| 3m/1015Mi |
 1k (headless, with endpoints) | 306 ms | 160 ms | 5.5 ms | 141 ms | 882m/10.9Gi| 640m/10Gi | 3m/292Mi | 2m/260Mi |
 10k (headless, with endpoints) | 5.3 s | 2.2 s  | 36.4 ms | 3.1s | 2004m/14.3Gi | 1698m/13.7Gi | 2m/555Mi | 2m/379Mi |
