### ISSUE TITLE
Release Pipeline - update to publish to Red Hat Scan Registry and Submit Image Cert Results

### ISSUE THREAD

**Issue by DaniellaFreese** [Kong/kubernetes-ingress-controller#2649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

To support publishing to Red Hat Marketplace, images need to be pushed to the red hat scan registry on a regular release cadence, followed by executing the preflight utility and submitting the results. 

An example workflow is provided to show how this can be executed via a gh workflow. 

### Proposed Solution

```console
jobs:
  build-push-image: 
    runs-on: ubuntu-latest
    outputs: 
      redhat_scan_tag: ${{ steps.redhat_scan_tag.outputs.tag }}
    steps: 
    - name: "Redhat Meta: Add scan tag to list of redhat tags"
      id: rh-scan-meta
      run : echo "scan.connect.redhat.com/ospid-f8304390-ff4c-4b7f-8c7e-1ed13370b3c2/kong-ingress-controller:version"

    - name: docker login to RH Scan Registry 
      uses: docker/login-action@v2
      with:
        registry: scan.connect.redhat.com
        username: ${{ secrets.RH_USERNAME }}
        password: ${{ secrets.RH_TOKEN }}
    - name: Redhat Image Build and Push 
      run: echo "build stage"
    - name: setup output 
      id: redhat_scan_tag
      run: |
        echo "::set-output name=tag::${{ steps.rh-scan-meta.outputs.tags }}"
    
  rh-scan-registry-submit: 
    runs-on: ubuntu-latest
    needs: build-push-image
    steps: 
      - name: check preflight can see docker-config
        uses: addnab/docker-run-action@v3
        with:
          image: quay.io/opdev/preflight:stable
          run: |
            echo ${{ secrets.RH_AUTH_CONFIG }} > ./dockerconfig.json
            preflight check container  ${{ needs.build-push-image.redhat_scan_tag }}  --submit \
            --pyxis-api-token=${{ secrets.RH_PYXIS_TOKEN }} \
            --certification-project-id=${{ secrets.RH_PROJECT_ID }} \          
             --docker-config=./dockerconfig.json 
```

### Additional information

The partner engineering team can help retrieve any secrets needed from the red hat portal
### Acceptance Criteria

- [ ] no breaking changes to the current release pipeline 
- [ ] the release & nightly pipelines should push the new image with appropriate tags to Red Hat scan registry 
- [ ] the release & nightly pipelines should run the preflight utility and submit results to the Red Hat scan registry

**Comment by mflendrich** [comment]
Commented in the internal partner engineering team issue about the place where we'll get the credentials to the RH Connect Docker registry.

**Comment by mflendrich** [comment]
Blocked by credentials for a technical push account being available.
