### ISSUE TITLE
All Paths are being rate limited. 

### ISSUE THREAD

**Issue by ronnie-webb2** [Kong/kubernetes-ingress-controller#2669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every path gets rate limited. 

### Expected Behavior

Only /v3/services/register get ratelimited

### Steps To Reproduce

```markdown
helm.sh/chart=kong-2.10.2 
kong/kubernetes-ingress-controller:2.3

**KongPlugin**

`apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-mobile
config:
  minute: 3
  limit_by: path
  path: /v3/services/register
  hour: 10000
  fault_tolerant: true
  hide_client_headers: false
plugin: rate-limiting`

**route ingress**

annotations:
    cert-manager.io/cluster-issuer: letsencrypt-integration
    external-dns.alpha.kubernetes.io/skip: 'true'
    konghq.com/plugins: rate-limiting-mobile
    kubernetes.io/ingress.class: kong-ingress-controller
status:
  loadBalancer:
    ingress:
      - ip: x.x.x.x
spec:
  rules:
    - host: example-host.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: example-host
                port:
                  number: 9142
    - host: example-host-1.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: example-host-1
                port:
                  number: 9142
    - host: example-host-2.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: example-host-2
                port:
                  number: 9142

Problem is I want to rate limit everything going to  /v3/services/register,  But every path gets rate limited. Any suggestions?
```

### Kong Ingress Controller version

```shell
kong/kubernetes-ingress-controller:2.3
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1900", GitCommit:"1f775cfbf564daf2c8f0ba548eff09f58045c4a4", GitTreeState:"clean", BuildDate:"2022-04-13T09:36:54Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"
```

**Comment by rainest** [comment]
If you review the plugin configuration in the admin API, does it look correct, i.e. does it have the settings you added in your KongPlugin?

If so, do you see that you have different limit counters on the chosen path and others? If you send enough requests on another path to get throttled, can you still send requests on the designated path?

I think the `limit_by=path` configuration is probably functioning as intended (maybe? there's not much context on the PR that originally added it) but isn't at all documented.

That will rate limit any path on the configured route, but will accrue counters depending on whether it's on the designated path or not: there is one bucket for requests whose path matches the configuration, and another bucket for requests on any other path. If you have the limit set to 6/hour and the plugin path set to `/example/foo` for a route with path `/example/`, you could send 6 requests to `/example/foo`, hit the path limit, and then send 3 requests each on `/example/bar` and `/example/baz` before hitting the other path limit.

If the behavior you're seeing matches that, we'll want to move this to the Kong repo for further evaluation. The actual behavior as I read it looks quite odd, but I can't say for sure whether that's wrong vis a vis the original intent.
