### ISSUE TITLE
Feature proposal: add a flag to disable compression on kubeconfig

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#2675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

When querying API server with a big amount (depending on size ~100s or ~1000s) of secrets the connection to API server times out.

### Proposed Solution

- Implement a feature/runtime flag that will disable compression on kubeconfig to minimize API processing

### Additional information

Related bug report #2382

### Open questions

- We still need to decide if we want to:

  - disable compression on the whole client (as you've proposed in your diff)
  - or disable it only for the initial list and the recreate the client with the already established defaults (compression enabled)
  
- Whether this should be done as a feature or runtime flag

### Acceptance Criteria

- [ ] As a user I should be able to toggle a flag which will allow me to disable compression when issuing calls to API server

**Comment by shyamjvs** [comment]
PTAL at https://github.com/kubernetes/kubernetes/issues/112296 - that should help with above issue fmu.

**Comment by mflendrich** [comment]
Closing until #112296 brings clear resolution and/or a specific request for this flag gets reported with the above context.
