### ISSUE TITLE
How to use KongConsumer's userName property

### ISSUE THREAD

**Issue by WywTed** [Kong/kubernetes-ingress-controller#268]
There is a KongConsumer and its userName is "just测试". The document says the userName must be unique in a Kong Env. 
So, once i define the userName, how can i use the userName, or where to use it.
~~~ 
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: kong-consumer-test-abcck323da
  namespace: project-test
username: just测试
~~~

**Comment by hbagdi** [comment]
>  So, once i define the userName, how can i use the userName, or where to use it.

Consumers can be used to manage access to services in Kong.
The following is a good guide to get you started: https://docs.konghq.com/1.1.x/getting-started/adding-consumers/

Once, you create a consumer you can create credentials using `KongCredential` custom resource.

**Comment by WywTed** [comment]
I know what you mean, but when using  ingress-controller, the relationship is combined by the consumerRef which is the k8s' crds' name. And k8s resource name is case sensitive and just  letter, number and short line('-'), but the  userName can be any other character.

**Comment by hbagdi** [comment]
> I know what you mean, but when using ingress-controller, the relationship is combined by the consumerRef which is the k8s' crds' name. And k8s resource name is case sensitive and just letter, number and short line('-'), but the userName can be any other character.

I see your point but how is it a problem in any case?

**Comment by WywTed** [comment]
We have a Management-UI which manage different project(namespace) in k8s, and each project can create KongConsumer into the same kong env. So if it doesn't matter about the userName, we can generate random string for each creation.

**Comment by hbagdi** [comment]
> We have a Management-UI which manage different project(namespace) in k8s, and each project can create KongConsumer into the same kong env. So if it doesn't matter about the userName, we can generate random string for each creation.

@WywTed I'm sorry but I still don't understand what you're trying to get to here or what exactly is your question. You can auto-generate the username and KongConsumer resource if you'd like.

**Comment by WywTed** [comment]
OK， thanks.
