### ISSUE TITLE
Add controllers for ReferenceGrant

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2690]
Gateway APIs [renamed](https://github.com/kubernetes-sigs/gateway-api/pull/1179) ReferencePolicy to [ReferenceGrant](https://gateway-api.sigs.k8s.io/api-types/referencegrant/). ReferencePolicy will be [removed in 0.6](https://github.com/kubernetes-sigs/gateway-api/issues/1206). AFAIK these are completely identical in form and function; only the name has changed.

We will need to add a new controller and handle both types temporarily in the store and related functions temporarily.

**Comment by mlavacca** [comment]
This has been fixed by #2772, in which `ReferencePolicies` have been replaced by `ReferenceGrants`.
