### ISSUE TITLE
Gateway API: drop support for v1alpha2 APIs which have v1beta1 releases

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2693]
### Problem Statement

When Gateway API released [v0.5.0](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.5.0) the new `v1beta1` types were backwards compatible with their previous `v1alpha2` counterparts so not much controller machinery had to be changed. This is not guaranteed to continue however, so the purpose of this task is to drop support for `v1alpha2` entirely for `GatewayClass`, `Gateway` and `HTTPRoute` and establish that as the new baseline going forward so that we're not burdened with maintenance trying to further support alpha APIs when more stable beta versions exist.

### Acceptance Criteria

- [ ] `v1alpha2.GatewayClass`, `v1alpha2.Gateway` and `v1alpha2.HTTPRoute` support is dropped in favor of their `v1beta1` counterparts to reduce maintenance burden.

**Comment by mflendrich** [comment]
won't fix - no obvious driver for this right now.
