### ISSUE TITLE
Update Kuma compatibility to use patch

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2695]
https://github.com/Kong/kubernetes-ingress-controller/pull/2626 uses a deprecated annotation for no-controller Deployment compatibility. https://github.com/kumahq/kuma/issues/4525 is now fixed, and we can migrate to the patch approach once it is released.

IMO we should still push to revert the deprecation and keep the annotation around indefinitely per https://github.com/kumahq/kuma/issues/4279, both for simplified configuration and to keep compatibility with a wider range of Kuma releases, but if that doesn't happen we will definitely need the patch approach.

**Comment by rainest** [comment]
You change the annotation added in #2626 to a patch annotation, which will probably look exactly like the the example in https://github.com/kumahq/kuma/issues/4525

The patch annotation should now work for us (the fix we needed was released in Kuma 1.8, in August), but the compatibility timeline concerns remain: if we make that change now, the chart will be compatible with Kuma 1.8 _only_. We probably don't want to make the change until we have to, because we've released a Kuma version without support for `kuma.io/service-account-token-volume`.

Whether `kuma.io/service-account-token-volume` will actually be removed, and when that will happen if so, remains in limbo until https://github.com/kumahq/kuma/issues/4279 reaches a decision. If the decision is to keep it, we close this without doing anything.

At present, however, this is more a reminder that we might have to change something in the future. Tests should alert us to that need if we miss it happening, since the chart does test against the latest Kuma version (not 100% sure but I don't see anything in here or the KTF addon that would pin the version, so it should be latest).

**Comment by mflendrich** [comment]
@rainest please fill in the issue format (problem, proposed solution, AC)

**Comment by rainest** [comment]
@mflendrich the status here remains unchanged: there isn't a proposed solution because we don't know if the problem will actually exist yet. I've asked the mesh team if they've had any discussion around plans since the issue there hasn't had many updates since we last checked it.

Roughly, the AC _would_ look like:

- [ ] Add a template for a [ContainerPatch](https://kuma.io/docs/2.0.x/explore/dpp-on-kubernetes/#custom-container-configuration) resource that adds a mount for the chart's ServiceAccount token. The example in https://github.com/kumahq/kuma/issues/4525 should be a decent starting point.
- [ ] Add an [annotation](https://kuma.io/docs/2.0.x/reference/kubernetes-annotations/#kumaiocontainer-patches) for this ContainerPatch to the chart's Deployment Pod template.
- [ ] Validate that Kuma versions 1.8 and higher run successfully via the existing chart tests.
- [ ] Add changelog/release notes that indicate Kuma <1.8 is no longer supported.

**Comment by rainest** [comment]
Per the Kuma issue, the existing annotation will be kept indefinitely. We will continue to use it for compatibility with a wider range of Kuma releases, so there is no action to take here.
