### ISSUE TITLE
[Need help] Setup kong ingress controller into kubernetes cluster deploy by rancher 2.0

### ISSUE THREAD

**Issue by DevOpsRoot** [Kong/kubernetes-ingress-controller#27]
Hello,

I'm using a kubernetes cluster deployed by rancher 2.0 ( it's a beta but it's works good ) and i want to set up the kong ingress controler into.

Actually kong start properly ( and the other component too), the only problem come from the postgres DB which didn't start ! i thinks it's come from the Stateful Set .. any idea how to set up the db with another deployement mode ?

I use the Rancher CLI like this : 

```
rancher kubernetes create -f all-in-one-postgres.yaml
```

All appears as created in the terminal, but the postgres database remains as "schedule" in the rancher GUI

**Comment by aledbf** [comment]
@DevOpsRoot please check the reason of the error running `kubectl describe pod -n kong postgres-0`

**Comment by DevOpsRoot** [comment]
```Name:           postgres-0
Namespace:      default
Node:           <none>
Labels:         app=postgres
                controller-revision-hash=postgres-9b84458c9
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"default","name":"postgres","uid":"a5bd0268-47c1-11e8-a212-06793c4cb7fe","apiVers...
Status:         Pending
IP:             
Controlled By:  StatefulSet/postgres
Containers:
  postgres:
    Image:  postgres:9.5
    Port:   5432/TCP
    Environment:
      POSTGRES_USER:      kong
      POSTGRES_PASSWORD:  kong
      POSTGRES_DB:        kong
      PGDATA:             /var/lib/postgresql/data/pgdata
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6wc75 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  datadir-postgres-0
    ReadOnly:   false
  default-token-6wc75:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6wc75
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  1s (x7 over 33s)  default-scheduler  PersistentVolumeClaim is not bound: "datadir-postgres-0"
``` 
Thanks you i'am a nood :dizzy_face:

**Comment by DevOpsRoot** [comment]
@aledbf i'm running that in an ec2 instance

**Comment by aledbf** [comment]
@DevOpsRoot ok, that should work OOTB.
Please replace [this lines](https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/single/all-in-one-postgres.yaml#L114-L126) with 
```
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}
```
to get this working. Please keep in mind you will lose the data if the postgresql pod dies.

Please get help in the rancher community about why the PVC is not being created.

**Comment by aledbf** [comment]
Maybe you should follow https://rancher.com/docs/rancher/v1.5/en/kubernetes/storage/#persistent-volumes---ebs

**Comment by DevOpsRoot** [comment]
Thank you, i will try with an ELB and give you the result in one hour @aledbf

**Comment by aledbf** [comment]
Closing. Please reopen if you still have issues after fixing the PVC issue
