### ISSUE TITLE
Bot user for dependabot to include in CODEOWNERS and allow automerge PRs

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#2730]
Given recent changed in CI such that [dependabot's PRs get automatically enabled auto-merge and are approved by `githubactions[bot]`](https://github.com/Kong/kubernetes-ingress-controller/blob/278a7e12892db5872e969e0746a265d3fbd30032/.github/workflows/automerge-dependabot.yaml) we have realized that in order for this to work dependabot would have to be added to CODEOWNERS (which is not possible as per this post: https://github.community/t/is-it-possible-to-add-github-apps-bot-to-codeowners/3146/2 by one of Github's maintainer) or the CODEOWNERS would need to be disabled for a repo (which we don't want to do).

This leaves us with one option: to introduce a bot user account for which we'll be able to create Personal Access Tokens giving us the permissions to auto merge the PRs.

**Comment by mflendrich** [comment]
Consensus: won't fix - this has inherent risks
