### ISSUE TITLE
Use projected token or TokenRequest API

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2731]
Per https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets spawning Secrets for auto-population is no longer the standard method of obtaining those credentials, and the new methods provide more secure tokens. There are two options for obtaining these:

- A [projected volume](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection), which generates a token in not a Secret and exposes it as a mount similar to the existing mount.
- [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/), which uses a TokenRequest resource whose status will include the token.

We should explore both options and determine which is best for our needs. Some initial thoughts:

- These tokens rotate. Our existing code has nothing to handle this, though it's possible that either client-go or controller-runtime support it natively. We need to confirm behavior after a rotation and build support for it if none exists in libraries.
- Concerns around mesh sidecar support remain. This probably pushes us to the projected volume approach until mesh sidecars are capable of handling their own TokenRequests (IIRC Istio does this, but Kuma and Linkerd do not).

**Comment by shaneutt** [comment]
Have you identified any specific features or code areas where we need to make relevant adjustments?

**Comment by rainest** [comment]
It would replace https://github.com/Kong/kubernetes-ingress-controller/blob/main/config/base/secret-sa-token.yaml and the associated mounts.

**Comment by mflendrich** [comment]
Dumb question. What do we use those tokens for?

**Comment by rainest** [comment]
> Dumb question. What do we use those tokens for?

Very belated response since I only saw it when I got the closure notification today: the service account that KIC uses to access Kubernetes resources needs a credential, and it needs to load it from somewhere. This changes how that somewhere is exposed to the process on the container filesystem.
