### ISSUE TITLE
Missing ingress TLS secret breaks everything on DB-less Kong

### ISSUE THREAD

**Issue by ismailbaskin** [Kong/kubernetes-ingress-controller#277]
### Summary

When using Cert-manager's [Ingress Shim](http://docs.cert-manager.io/en/latest/tasks/issuing-certificates/ingress-shim.html) there is no TLS secret resource at first. Absence of TLS secret breaks the kong's /config yaml generation process. 

ingress-controller container's exposes this kind of error log:

"requeuing example/example-ingress, err error building kong state: error fetching certificate 'example/example-net-tls': error retrieving secret example/example-net-tls: secret example/example-net-tls was not found"  

**Kong Ingress controller version**
0.4

**Kong or Kong Enterprise version**

CE 1.1.2 (KONG_DATABASE=off)

**Comment by hbagdi** [comment]
This is something that we have been addressing over time.
Previously, everything used to break as soon as one error was encountered.

We will be addressing this.

**Comment by hbagdi** [comment]
This got fixed in 69b021c0ef907d57ecd65eee36351afb78dcd5ef and f052b729b4e7af25ffe6b2bf763f1031ebfad74e.
