### ISSUE TITLE
Spike: Gateway API support for query string matching on HTTP routes

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2778]
## Problem Statement

Query string matching is an extended feature of Gateway API, but if we can support it we would like to.

## Acceptance Criteria 
- [ ] spike the options and effort to enable query string route matching in KIC. (If the implementation is sufficiently complex, then the result of this issue should be a KEP or some other kind of design doc)

**Comment by jrsmroz** [comment]
- Kong does not support routing based on query params natively.
- Path tegex can't be used, as only paths are matched, not query string.
- [Router expressions](https://docs.konghq.com/gateway/latest/reference/router-expressions-language/#main) does not expose query string
- We don't have a plugin that can be used. We would need to create one.

**Comment by jrsmroz** [comment]
`QueryParamMatchType` does not mark the `QueryParams` field with `Support: Extended`.

**Comment by randmonkey** [comment]
Now Kong gateway has supported matching HTTP query parameters in expression router: https://github.com/Kong/kong/pull/11348 We can move on to this (note that we only support query param matching in Kong 3.5 and later).

**Comment by mflendrich** [comment]
This feature has been implemented in Kong (https://github.com/Kong/kong/pull/11348), will be backported into 3.4.x (https://github.com/Kong/kong/pull/11469) and the Gateway API conformance part will be covered by #3679.
