### ISSUE TITLE
Make Gateway API enabled by default

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2779]
### Problem Statement

Now that [Gateway API](https://github.com/kubernetes-sigs/gateway-api) has APIs in `v1beta1` with the release of `v0.5.0` we are ready to call our Gateway API implementation beta as well. The purpose of this task is to mark the beta APIs as beta and enable them by default for future KIC releases. Alpha APIs should remain in their current alpha state behind a feature gate that is off.

### Proposed Solution

Create a new feature gate called `GatewayAlpha` which implicates support for the alpha apis. Put anything that's pre-beta under that gate, and turn it off by default. Mark `Gateway` feature gate as beta and turn it on by default. Update relevant documentation.

### Acceptance Criteria

- [x] beta gateway APIs are supported and on by default in KIC https://github.com/Kong/kubernetes-ingress-controller/pull/2781
- [x] alpha gateway APIs are off by default in KIC https://github.com/Kong/kubernetes-ingress-controller/pull/2781
- [x] documentation is updated to adjust for these changes

**Comment by shaneutt** [comment]
Documentation is being handled now in other issues:

- https://github.com/Kong/docs.konghq.com/issues/4229
- https://github.com/Kong/docs.konghq.com/issues/4123
- https://github.com/Kong/docs.konghq.com/issues/4123
