### ISSUE TITLE
all-in-one-postgres TLS error

### ISSUE THREAD

**Issue by mmaryo** [Kong/kubernetes-ingress-controller#279]
Hello 

I juste create a new cluser (1.12) on EKS 

And run https://github.com/Kong/kubernetes-ingress-controller/blob/next/deploy/single/all-in-one-postgres.yaml

After that, I link Ip Adress to my domain with Gandi 
@ | A | 10800 | 21x.7x.14x.4x

And open in browser my domaine <abc.com>

It switch to HTTPS 
Is it normal ?

![Screenshot 2019-04-26 17:22:11](https://user-images.githubusercontent.com/1669985/56818547-1d4c8980-6848-11e9-9472-3be3ded8ad9a.png)

So I tried to add a ssl certificate

Simply like this : 
https://kubernetes.io/docs/concepts/services-networking/ingress/#tls

And create a dummy app with tls 

        apiVersion: extensions/v1beta1
        kind: Ingress
        metadata:
          name: dummy
          namespace:  dummy
          annotations:
            kubernetes.io/ingress.class: "kong"
            secretName: tls-test
        spec:
          rules:
            - host: mmm.app
              http:
                paths:
                  - path: "/dummy"
                    backend:
                      serviceName: http-svc
                      servicePort: http

The url <mydomain>/dummy continue to say certificat error

Need your help

Thanks

**Comment by hbagdi** [comment]
@mmaryo The secrete needs to be added in the `tls` section under `spec` and not under `annotations` like you have in the YAML you'v posted.

Also, please ensure the certificate is a valid and signed by a public CA.

**Comment by mmaryo** [comment]
thanks @hbagdi I correct that 

In summary, today I do : 

1/ 
kubectl apply -f https://bit.ly/kong-ingress

2/ 
kubectl -n dummy create secret tls tls-test --key *.mmm.app.key --cert  *.mmm.app.chain.pem

3/
 Then add an application 

      apiVersion: v1
      kind: Namespace
      metadata:
        name: dummy
      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: echoserver
        namespace: dummy
      spec:
        ports:
          - port: 80
            targetPort: 8080
            protocol: TCP
        type: NodePort
        selector:
          app: echoserver
      ---
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: echoserver
        namespace: dummy
      spec:
        replicas: 1
        template:
          metadata:
            labels:
              app: echoserver
          spec:
            containers:
              - image: gcr.io/google_containers/echoserver:1.4
                imagePullPolicy: Always
                name: echoserver
                ports:
                  - containerPort: 8080
      ---
      apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        name: echoserver
        namespace: dummy
        annotations:
          kubernetes.io/ingress.class: kong
      spec:
        tls:
          - hosts:
              - mmm.app
            secretName: tls-test
        rules:
          - host: mmm.app
            http:
              paths:
                - path: /dummy
                  backend:
                    serviceName: echoserver
                    servicePort: 80


4/ Try to ping server with curl 

`curl -XGET http://mmm.app/dummy`
`{"message":"no Route matched with those values"}`

-> Why ? Everything seems good 

4/ With https

`curl -XGET https://mmm.app/dummy`
```curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.```   


6/ I tested my certificat : 
`openssl s_client -connect mmm.app:443 -tls1_2`   

```
CONNECTED(00000003)
depth=0 C = US, ST = California, L = San Francisco, O = Kong, OU = IT Department, CN = localhost
verify error:num=18:self signed certificate
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = Kong, OU = IT Department, CN = localhost
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=San Francisco/O=Kong/OU=IT Department/CN=localhost
   i:/C=US/ST=California/L=San Francisco/O=Kong/OU=IT Department/CN=localhost

...

-----END CERTIFICATE-----
subject=/C=US/ST=California/L=San Francisco/O=Kong/OU=IT Department/CN=localhost
issuer=/C=US/ST=California/L=San Francisco/O=Kong/OU=IT Department/CN=localhost
---


```   

-> Why O=Kong ??

**Comment by hbagdi** [comment]
@mmaryo Can you please curl the following endpoint on Kong's Admin API: `curl http://localhost:8001/snis` and post the output here. Do you see `mmm.app` registered as an SNI in Kong?

**Comment by mmaryo** [comment]
thanks @hbagdi 

To requete Kong Admin I forward port to localhost : 

➜  kubectl port-forward service/kong-ingress-controller 8001:8001     
Forwarding from 127.0.0.1:8001 -> 8001
Forwarding from [::1]:8001 -> 8001
Handling connection for 8001


➜  curl http://localhost:8001/snis
{"next":null,"data":[]}% 

Is it wrong ?

**Comment by hbagdi** [comment]
@mmaryo It seems like you are probably running into the same bug as #285 which is now fixed and will be available in the next release.

**Comment by mmaryo** [comment]
thanks @hbagdi 
do you know when next version will be release ?

**Comment by hbagdi** [comment]
I'm not sure yet.
We have a couple of bugs to fix.
0.5.0 will be in some time in June, we might be able to do 0.4.1 with the bug fixes later this month.
