### ISSUE TITLE
convert the core filter `RequestRedirect` to the proper Kong plugin

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#2799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We should support the core `HTTPRoute` filter `RequestRedirect` to be compliant with Gateway API. The core filter `RequestHeaderModifier` has already been supported in KIC by means of a kong plugin, and we should do the same for this filter.

### Proposed Solution

Extend the function `generatePluginsFromHTTPRouteRuleFilters` to support the filter `RequestRedirect`

### Additional information

https://github.com/Kong/kubernetes-ingress-controller/issues/2793#issuecomment-1209577878
https://github.com/Kong/kubernetes-ingress-controller/issues/2793#issuecomment-1209786514

### Acceptance Criteria

- [ ] the core filter `RequestRedirect` is translated to the proper Kong plugin

**Comment by randmonkey** [comment]
Searched for all free plugins  in plugin hub, there was no plugins that fully satisfy the requirements of `RequestRedirect`.
- [request termination](https://docs.konghq.com/hub/kong-inc/request-termination/) could return a certain code for request, but could not set `Location` for redirecting.
- [resonpse transformer](https://docs.konghq.com/hub/kong-inc/response-transformer/) could set custom headers in response, but it need to access the upstream.

**Comment by randmonkey** [comment]
After investigation, currently the `RequestRedirect` feature could NOT be implemented using one or combination of existing free plugins of kong gateway (except for the [serverless functions](https://docs.konghq.com/hub/kong-inc/serverless-functions/), but this allows running custom lua code, which is insecure). So, we decided not to include this feature in the upcoming 2.6.0 release of KIC.

**Comment by mflendrich** [comment]
not blocked anymore - @randmonkey has a solution proposal (can you please post it here?)

**Comment by randmonkey** [comment]
One possible method to implement `RequestRedirect` filter (See #2799): Run a server from KIC to return redirect responses, and use `RequestModifier` plugin to carry the specifications to the redirect server. 
When a rule uses `RequestRedirect`, we generate a route sending traffic to KIC redirect server, and carry the settings of filter using  `RequestModifier` plugin to add headers (if the corresponding field presents. When the fields are configured, they remain unchanged until `HTTPRoute` resource modified):
-  `X-Kic-Redirect-Scheme` for `Scheme` field
-  `X-Kic-Redirect-Hostname` for `Hostname` 
- `X-Kic-Redirect-Path-Modifier-Type` for `Path.Type`
- `X-Kic-Redirect-Path-Replace-Fullpath` for `Path.ReplaceFullPath`
- `X-Kic-Redirect-Path-Replace-Prefixmatch` for `Path.ReplacePrefixMatch`
- `X-Kic-Redirect-Port` for `Port`
- `X-Kic-Redirect-Statuscode` for `StatusCode`
When a request to that path came to Kong, it first go through the `RequestModifier` plugin to add the header carrying the settings. Then the request with added headers is proxied to KIC redirect server, then KIC server use the header and original request to generate and return the redirect response.

**Comment by mheap** [comment]
@mlavacca Is this core or extended conformance?

**Comment by mlavacca** [comment]
This is core and has already been fixed by #https://github.com/Kong/kubernetes-ingress-controller/pull/3702. We can close it 🎉
