### ISSUE TITLE
Feature to use default backend service when endpoints aren't found for ingress service

### ISSUE THREAD

**Issue by arbiter34** [Kong/kubernetes-ingress-controller#280]
### Summary
It would be useful if the default backend service specified via cli flag was used as a fall back upstream for any service which is found not to have endpoints.  This prevents the removal of kong routes/services when a backing resource goes into a status other than ready.  

I see comments around the default backend in regards to using it for serving a 503 which leads me to think I'm configuring it wrong, or there's a bug.

I've tried sticking a default backend on the ingress with no luck.  Any direction here is appreciated.

**Kong Ingress controller version**
0.3.0

**Kong or Kong Enterprise version**
Kong 1.1

### Kubernetes version
`Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.9-dispatcher", GitCommit:"e3f5193e8f1091a162af7e17a781e6a3129bcfd0", GitTreeState:"clean", BuildDate:"2019-03-28T18:15:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-gke.6", GitCommit:"394ee507d00f15a63cef577a14026096c310698e", GitTreeState:"clean", BuildDate:"2019-03-30T19:31:43Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}`

### Environment

- **Cloud provider or hardware configuration**: GKE

**Comment by hbagdi** [comment]
If no endpoints are found, Kong will send back `503 Service Unavailable` to the consumer.

> I've tried sticking a default backend on the ingress with no luck. Any direction here is appreciated.

That used to be for Nginx Ingress where a request would be routed to the default backend when an incoming requests matches no Ingress rules. The flag is non-functional in 0.3.0 and is removed in 0.4.0 version.

**Comment by arbiter34** [comment]
This doesn't seem correct, if no end points are found, the service/route gets removed from kong, which results in falling back to the next matching route.

**Comment by hbagdi** [comment]
> This doesn't seem correct, if no end points are found, the service/route gets removed from kong, which results in falling back to the next matching route.

That sounds like a bug if that is happening.
Please open a bug with reproduction steps.
