### ISSUE TITLE
Kong Ingress Pod restart when performance testing

### ISSUE THREAD

**Issue by hnhai** [Kong/kubernetes-ingress-controller#2803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Kong Ingress Pod restart when performance testing

### Expected Behavior

It work normaly

### Steps To Reproduce

```markdown
1, I'm install Kong DBless mode (10 pods) type NodePort in Kubernetes. We have a LoabBalancer to that NodePort.
2, Client (Jmeter) -> LB -> Kong Ingress -> Backend App.
3, Jmeter call 20.000 ccu, in 5 minutes. 20% of request have 502 error
4, Pods of Kong restart. LB return 502 to client.
```

### Kong Ingress Controller version

```shell
kong:2.8.1
kubernetes-ingress-controller:2.4.1
```

### Kubernetes version

```shell
v1.21.6
```

### Anything else?

I have try increment heathcheck timeout, Pods of Kong don't restart any more but still return 502 to client

**Comment by shaneutt** [comment]
Thanks for the report @hnhai. It sounds like despite the fact that you're using the Kong Kubernetes Ingress Controller (KIC) this problem may be specifically within the `proxy` container (and therefore the Kong Gateway). When the problem occurs, are new configurations actively being pushed by the KIC to the Gateway, or are your configurations (e.g. `Ingress`, e.t.c.) unchanging during these times?

**Comment by hnhai** [comment]
Sorry @shaneutt , I found the problem. Because I don't config resource for Kong Ingress Pod.
After set request ram and CPU it working normaly
