### ISSUE TITLE
Ensure Gateway feature is auto-disabled when CRDs aren't present

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2814]
### Problem Statement

For the upcoming release we now turn on the Gateway feature by default, but the CRDs may not be present. When this is the case the controller will throw errors.

The purpose of this task is to add a check that validates whether `GatewayClass`, `Gateway`, and `HTTPRoute` are installed. If they aren't then the Gateway feature gate is forced to false and the controllers disabled.

### Acceptance Criteria

- [x] if I deploy the KIC in a cluster without Gateway API CRDs, I get no errors or failures to watch those types
- [x] if I deploy the KIC in a cluster without Gateway API CRDs, I get an INFO level error explaining that Gateway API is not enabled

**Comment by randmonkey** [comment]
> ### Problem Statement
> For the upcoming release we now turn on the Gateway feature by default, but the CRDs may not be present. When this is the case the controller will throw errors.
> 
> The purpose of this task is to add a check that validates whether `GatewayClass`, `Gateway`, and `HTTPRoute` are installed. If they aren't then the Gateway feature gate is forced to false and the controllers disabled.
> 
> ### Acceptance Criteria
> * [ ]  if I deploy the KIC in a cluster without Gateway API CRDs, I get no errors or failures to watch those types
> * [ ]  if I deploy the KIC in a cluster without Gateway API CRDs, I get an INFO level error explaining that Gateway API is not enabled

I tried latest commit on `main` branch for the case, the KIC started without setting up the controllers for Gwateway APIs, and did not print errors. Because when we start controllers, we used a `AutoHandler` to check whether the watched CRD exists, e,g for gateway controller: 
https://github.com/Kong/kubernetes-ingress-controller/blob/217e4c4bd98fc954fa00aa75b010be2cc7bce247/internal/manager/controllerdef.go#L279-L285

So, the first item in AC has already been satisfied. I will submit a PR to check existence of  CRDs `GatewayClass`, `Gateway`, `HTTPRoute` and disable gateway feature when the CRDs are not installed.

**Comment by shaneutt** [comment]
> > ### Problem Statement
> > For the upcoming release we now turn on the Gateway feature by default, but the CRDs may not be present. When this is the case the controller will throw errors.
> > The purpose of this task is to add a check that validates whether `GatewayClass`, `Gateway`, and `HTTPRoute` are installed. If they aren't then the Gateway feature gate is forced to false and the controllers disabled.
> > ### Acceptance Criteria
> > 
> > * [ ]   if I deploy the KIC in a cluster without Gateway API CRDs, I get no errors or failures to watch those types
> > * [ ]   if I deploy the KIC in a cluster without Gateway API CRDs, I get an INFO level error explaining that Gateway API is not enabled
> 
> I tried latest commit on `main` branch for the case, the KIC started without setting up the controllers for Gwateway APIs, and did not print errors. Because when we start controllers, we used a `AutoHandler` to check whether the watched CRD exists, e,g for gateway controller:
> 
> https://github.com/Kong/kubernetes-ingress-controller/blob/217e4c4bd98fc954fa00aa75b010be2cc7bce247/internal/manager/controllerdef.go#L279-L285
> 
> So, the first item in AC has already been satisfied. PR #2815 adds the code to check existence of CRDs `GatewayClass`, `Gateway`, `HTTPRoute` and disable gateway feature when the CRDs are not installed.

Awesome, thanks @randmonkey :vulcan_salute:
