### ISSUE TITLE
Test KIC 2.6 `main` against Kong OSS 3.0.0-alpha.1 and kong-ee nightly

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2870]
Ensure that the below testing configurations pass:

Kong OSS:
- `make test.integration` (both postgres and dbless) vs Kong OSS 3.0.0-alpha.1
- `make test.e2e` vs Kong OSS 3.0.0-alpha.14

Kong Enterprise:
- `make test.integration.enterprise.postgres` against ~Kong EE nightly~ the internal image labeled `3.0.x.x` (covered by #2850).

Let's report bugs referencing this issue for failures under investigation/fix.

Acceptance criteria
- [ ] The `test.integration` dbless against Kong OSS yields no failures
- [ ] The `test.integration` postgres against Kong OSS yields no failures
- [ ] The `test.integration.enterprise.postgres` against Kong EE yields no failures

**Comment by mflendrich** [comment]
Current known failure being fixed by https://github.com/Kong/kubernetes-ingress-controller/pull/2873.

**Comment by randmonkey** [comment]
e2e tests are blocked by #2884.

**Comment by randmonkey** [comment]
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3022469778 integration tests passed.
