### ISSUE TITLE
Kong basic-auth plugin accepts credentials from other namespaces

### ISSUE THREAD

**Issue by xmath279** [Kong/kubernetes-ingress-controller#2872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deploying an Ingress resource that uses the basic-auth KongPlugin, the credentials from other namespaces are also accepted. 

### Expected Behavior

Only the credentials linked to the KongConsumer associated with the namespaced KongPlugin should be accepted.

### Steps To Reproduce

Here is a script to deploy a simple hello-world webserver with Ingress, KongPlugin, KongConsumer and Secret resources in three different namespaces. The ingress resources use vcap.me base domain which resolves to 127.0.0.1, so it should be easy to test with Minikube or Docker Desktop.

```bash
#!/usr/bin/env bash

NS=("ns-1" "ns-2" "ns-3")
PASSWORDS=("password-1" "password-2" "password-3")

for index in "${!NS[@]}"; do
  namespace="${NS[index]}"
  password="${PASSWORDS[index]}"
  kubectl create ns $namespace
  cat <<EOF | kubectl -n $namespace apply -f-
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginxdemos/hello
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
spec:
  selector:
    app: hello-world
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  labels:
    name: hello-world
  annotations:
    konghq.com/plugins: basic-auth
spec:
  ingressClassName: kong
  rules:
  - host: hello-world.$namespace.vcap.me
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: hello-world-svc
            port: 
              number: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth
consumerRef: consumer
config:
  hide_credentials: true
plugin: basic-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: consumer
  annotations:
    kubernetes.io/ingress.class: kong
username: consumer-$namespace
credentials:
- credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
stringData:
  kongCredType: basic-auth
  username: $namespace
  password: $password
EOF
done
```

After deploying that, we can easily test it like so:

```bash
# Confirm the route is indeed protected by basic-auth
curl -I hello-world.ns-1.vcap.me
HTTP/1.1 401 Unauthorized
Date: Thu, 25 Aug 2022 19:04:24 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
WWW-Authenticate: Basic realm="kong"
Content-Length: 26

# Use first namespace password. This should succeed.
curl -I -u ns-1:password-1 hello-world.ns-1.vcap.me
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Server: nginx/1.23.1
Date: Thu, 25 Aug 2022 18:59:41 GMT
Expires: Thu, 25 Aug 2022 18:59:40 GMT
Cache-Control: no-cache

# Use second namespace password. This should fail.
curl -I -u ns-2:password-2 hello-world.ns-1.vcap.me
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Server: nginx/1.23.1
Date: Thu, 25 Aug 2022 18:59:41 GMT
Expires: Thu, 25 Aug 2022 18:59:40 GMT
Cache-Control: no-cache
```

The second cURL command should not work for this Ingress route.

### Kong Ingress Controller version

```shell
kong/kubernetes-ingress-controller:2.5
kong/kong-gateway:2.8
```

### Kubernetes version

```shell
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/arm64"}
```

**Comment by rainest** [comment]
This is expected: Kong does not have any notion of Kubernetes namespaces and merges configuration from all namespaces together, and treats all auth plugin credentials as equals. We use namespaces to segregate configuration at the Kubernetes level (a KongConsumer in namespaceA can only use credential Secrets in namespaceA, not in namespaceB), not at the Kong level.

You'll want to use the [ACL plugin](https://docs.konghq.com/hub/kong-inc/acl/) for this. Auth plugins like basic-auth or jwt provide authentication, ACL provides authorization. To use it for your case, you'd create an ACL KongPlugin and apply it to all Ingresses (or Services, if you prefer) in a namespace and allow some allow group (a group with the same name as the namespace is probably a good choice). You'll then create Secrets with `kongCredType=acl` and `group=groupname` keys and assign them to KongConsumers in the namespace.

https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/configure-acl-plugin/ covers this process step-by-step for a slightly different use case.

I'll go ahead and close this out, but if you do have any other questions, let us know and we'll respond back.

**Comment by MikeBlomm** [comment]
@rainest I managed to setup the key-auth plugin in combination with the ACL plugin, which seem to work fine. But only if every api key is unique.

A new problem arises if I use the same `key-auth` key in different namespaces. For example: I have three different deployments with their own ingress configured. All have a separate key-auth and ACL plugin, but the actual apikey is the same. When trying to call an endpoint with the api key provided, it will only succeed with 1 of the 3 deployments. KIC will respond with a ```403 error: "message":"You cannot consume this service"``` for the other 2 deployments, while they have the correct ACL configured. 

For some of the deployments I want to use the same api key (as they belong to each other), is there a way to achieve this without allowing all api keys to be used within all namespaces?

**Comment by rainest** [comment]
Not sure I follow--if you post some example resources and test requests that replicate the issue we may understand better.

Generally speaking, credentials (such as API keys) are always usable across namespaces. Consumers probably should have, in retrospect, been cluster-level entities, but they probably aren't going to change at this point.

ACL should let you effectively limit credentials to a namespace, with the caveat that you need to apply the same plugin to all Ingresses or Services in that namespace. There is an open feature request to apply plugins at the namespace level, i.e. that you'd be able to annotate a namespace to indicate that all Ingresses (or Services/KongConsumers) should apply a given plugin to their route, but no planned release for it yet.

**Comment by mflendrich** [comment]
Closing as stale - but we're still interested in the response, we will reopen the issue accordingly.
