### ISSUE TITLE
Centralized Kong plugins configuration

### ISSUE THREAD

**Issue by ludovic-pourrat** [Kong/kubernetes-ingress-controller#2877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We would like to centralize the setup of our common Kong plugins in the namespace where Kong is running, and we would like to reference from the target application Ingress and Service Kubernetes objects the Kong Plugins.
At this time the KIC is searching for the Kong Plugin in the same namespace as the target application.

Benefits

- This will drastically reduce the number of CRDs to create at large scale.
- This provide a way to better segregate the ownership of plugins , especially for the security related ones, upon which the responsibility can be fully and easily assigned.
- Ease of consumption for the applications by just referencing the predefined plugins

### Proposed Solution

By setting up a feature flag we would like to amend the KIC to lookup for the Kong Plugins  in the namespace from where the KIC is running, or in another namespace location.

### Additional information

We are considering to create a PR for this feature proposal (might be part of the upcoming hackathon). 

### Acceptance Criteria

- [] As a user I can control from where the lookup for Kong Plugins CRDs is being executed by the Kong Kubernetes controller when configuring Kubernetes Ingress and Services resources. 
- [] By default the lookup is being executed locally to the namespace of the resource.

**Comment by rainest** [comment]
Can you share what issues or limitations you've encountered using KongClusterPlugins for this? They should already provide a centralized store for plugin configuration if you want that, albeit not in a namespace (though I'd argue that cluster scope is functionally a namespace with some special traits).

**Comment by ludovic-pourrat** [comment]
Hi @rainest the main limitation encountered with the cluster plugins option is about handling name collisions between our deployments within the same cluster. 
I would agree that is is something we could managed anyway.
At this stage we have constrained the cluster plugins to a specific set this is why we where thinking managing plugins from a centralized namespace, from where along is deployed.

Thanks.

**Comment by backjo** [comment]
We're trying to work through a similar problem - i.e. we have two Kong KICs running in seperate namespaces that we want seperate global plugins configured on with the same name
