### ISSUE TITLE
Deprecate traditional route generation in favor of service-consolidated routes

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2881]
https://github.com/Kong/kubernetes-ingress-controller/pull/2507 introduced a feature flag that changes the way the controller generates routes. The current default generates a route per path rule in an Ingress to easily deal with multiple rules in an Ingress potentially having different Services and thus requiring separate Kong routes. The new flag mode consolidates all rules within an Ingress that share a Service and creates a single Kong route for them. This can result in a significant reduction in configuration size and DB-less configuration load time.

The new method does not functionally impact routing: requests that went to a given Service using the original method still go to the same Service in the new method. It is, however, a soft breaking change, as it affects some non-functional metadata that some environments may scrape for unknown purposes: the number of routes changes and the new routes use a completely different naming scheme, so any third-party tooling expecting consistent route naming will be interrupted by the new system. We expect that the number of affected environments is likely low, however, and would like to roll out the new system as the new default to provide its performance benefits to a wider audience. We wish to initially flip the default while leave the old method available, but deprecated, initially, and later remove it entirely if there are no significant issues or requests to keep the old method around.

The new method currently only covers Ingress v1 translation, not v1beta1 or HTTPRoute translation. It will need to be expanded to the others. We may optionally omit support for v1beta1 because it will soon [no longer be supported by any supported Kubernetes version](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122) (I'm not sure exactly what our 3.0 plans are as far as version support or removal of v1beta1, but I suspect it's up for consideration at least).

- [x] Combined routes functionality is available for both HTTPRoute and Ingress v1. (implementing for v1beta1 out of scope because we're willing to delete the v1beta1 path soon).
- [ ] The `combinedRoutesFeature` gate is enabled by default, and the previously gated functionality becomes the default functionality.
- [ ] There is a new follow-up issue to remove support for the original method entirely in the 3.0 milestone.
- [ ] Documentation announces that the original method is deprecated and links to the removal issue for any negatively affected users to offer comment.
- [ ] The changelog lists this as a breaking change and describes the effects (no functional change but new route names and IDs with multiple paths versus a single path per route).

**Comment by shaneutt** [comment]
We have this in `v2.7.0`, but the reason this became a gated feature previously had to do with not wanting any surprises on upgrade (e.g. routes all change right during the upgrade). Should this be in `v3.0.0`, or what's the thinking behind trying now to do it in `v2.7.0`?

**Comment by rainest** [comment]
I'd like to remove the old code path entirely (I don't think there's any compelling reason to keep it around), and 3.0 would be a good time to do so, assuming we're using it as the actual breaking change release. There's going to be _some_ upgrade where all the routes change if it becomes the default or only option, so I'm inclined to have at least one version where that happens but you can flip back to the old version and come appeal to us to not remove it entirely.

**Comment by jrsmroz** [comment]
@rainest WOuld you mind if I take a look ot this feature, starting with  `Combined routes functionality for HTTPRoute`"

**Comment by rainest** [comment]
Sure, go ahead.

**Comment by jrsmroz** [comment]
I am not yet sure how the service based consolidation for the `HTTPRoute`  should look.

For the `Ingress`, the `IngressRules` are aggregated under the same service if they share the key defined as a tuple:
```
(
  ingress.Namespace, 
  ingress.Name, 
  ingressRule[i].HTTP.Paths[j].Backend.Service.Name, 
  ingressRule[i].HTTP.Paths[j].Backend.Service.Port.Number
)
```

In case of `HTTPRoute` it more complex, and a rule like above is not enough to aggregate. Without the service based consolidation the parser creates separate service for the key:
```
(
  httpRoute.Namespace, 
  httpRoute.Name, 
  httpRouteRuleNumber
)
```

In order to enable the service based consolidation for `HTTPRoute` there is a need to determine a way to identify the services that can aggregate the routes. Given the fact that `HTTPRouteRule` may reference multiple weighted backends, it seems reasonable to aggregate the routes only if they point to the same set of weighted backeds.

**Comment by rainest** [comment]
It is indeed more complicated. With the HTTPRoute translator as-is, I think the answer here is that multi-service backends just simply aren't eligible for such consolidation. We could potentially change that, but there's not a clear answer as to how. We may want to check with the other Gateway API implementations to see if they have good prior art, though I think a lot of them have proxies that just natively support multiple services per route and it's a non-issue as such.

The [change to support multi-Service backends](https://github.com/Kong/kubernetes-ingress-controller/pull/2402/files) uses the rule number-named service mentioned above [via `generateKongServiceFromBackendRef()`](https://github.com/Kong/kubernetes-ingress-controller/blob/963623d02453d49f284bcef4dfd078cf76b684d5/internal/dataplane/parser/translate_utils.go#L75-L151), invoked [from the HTTPRoute translator](https://github.com/Kong/kubernetes-ingress-controller/blob/963623d02453d49f284bcef4dfd078cf76b684d5/internal/dataplane/parser/translate_httproute.go#L84). There's [further processing to generate the Kong service](https://github.com/Kong/kubernetes-ingress-controller/blob/963623d02453d49f284bcef4dfd078cf76b684d5/internal/dataplane/parser/ingressrules.go#L44-L96), but as the name is already decided, so that doesn't matter as much.

The [host+service+port route name scheme](https://github.com/Kong/kubernetes-ingress-controller/blob/963623d02453d49f284bcef4dfd078cf76b684d5/internal/dataplane/parser/translators/ingress.go#L187) we use for Ingress doesn't transfer well to multi-service backends, since those can have (theoretically) infinite service+port combinations, and would be unwieldy to name.

I can't think of anything that works well, save our old bad standby option, "hash some unique identifying inputs and stuff the hash in the name". Maybe a bit less unwieldy is appending each distinct combination of N service+port+weight combos to a list and referring to them by index, so for

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: simple-split
spec:
  rules:
  - backendRefs:
    - name: foo-v1
      port: 8090
      weight: 90
    - name: foo-v2
      port: 8080
      weight: 10
  - backendRefs:
    - name: foo-v1
      port: 8090
      weight: 90
    - name: foo-v2
      port: 8080
      weight: 10
  - backendRefs:
    - name: foo-v1
      port: 8080
      weight: 90
    - name: foo-v3
      port: 8080
      weight: 10
```
You get two routes, `namespace.name.multi-0.xx` and `namespace.name.multi-1.xx`, where the former are the two rules that use v1/v2 and the latter is the rule that uses v1/v3. That's at least no less unintelligible than hashes, and does provide a means (though it is indirect--you have to count the combos yourself) of determining what they're referencing.

I don't think we can get a good indication of the underlying services with gateway labels (FTI-4368), which still could be large (hopefully not in practice), but at least isn't stuffed into the route name with all other identifying info.

**Comment by jrsmroz** [comment]
Yeah, creating a key from a backend refs works. 

Given the above example, the metadata would be

```
("<G>.<K>.<NS>.foo-v1.8090.90;<G>.<K>.<NS>.foo-v2.8080.10;", ["rule1", "rule2"], ["foo-v1", "foo-v2"])
("<G>.<K>.<NS>.foo-v1.8090.90;<G>.<K>.<NS>.foo-v3.8080.10;" ["rule3"], ["foo-v1", "foo-v2"])
```

The result would be
```
for backend refs key "<G>.<K>.<NS>.foo-v1.8090.90;<G>.<K>.<NS>.foo-v2.8080.10;" 
create service with ["rule1", "rule2"] and backends ["foo-v1", "foo-v2"],

for backend refs key "<G>.<K>.<NS>.foo-v1.8090.90;<G>.<K>.<NS>.foo-v3.8080.10;" 
create service with ["rule3"] and backends ["foo-v1", "foo-v2"]
```
I can't think of anything better right now.

**Comment by rainest** [comment]
In https://github.com/Kong/kubernetes-ingress-controller/pull/3008#pullrequestreview-1141603475 and https://github.com/Kong/kubernetes-ingress-controller/pull/3008#issuecomment-1278638285 we've found that HTTPRoute rules are much more difficult to consolidate than Ingress rules, as they allow for more complex matching (headers, methods) and transformations (filters, which will generally apply a standard plugin configuration to the route) per rule. Ingress only supported these via Ingress-wide annotations.

As such, #3008 consolidates _Service generation_ for HTTPRoutes (the original implementation created them per rule to handle multi-Service backends easily), but we'll need to handle route consolidation in a new PR.
