### ISSUE TITLE
Reconciler logs do not appear during integration tests

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2882]
Reconciler logs, e.g. [this log from the Ingress controller reconciler](https://github.com/Kong/kubernetes-ingress-controller/blob/9e3b4a5fe6151be7c5b99b01b5f0a59f139e3e1a/internal/controllers/configuration/zz_generated_controllers.go#L99) do not appear during integration tests. For example, [example_log.txt](https://github.com/Kong/kubernetes-ingress-controller/files/9472138/example_log.txt) most assuredly did reconcile Ingresses and other resources, but the "reconciling resource" log string that we use in all generated controllers never appears in it. This makes it difficult to diagnose issues that we cannot easily replicate when using a debugger. Log level does not appear to be the cause, as other debug-level logs do appear.

My initial attempt to step through the logger call and try to find a cause was not successful. I did not go through the entire call chain (it's quite long!), but after ~8 levels of calls it looked like the call was past various "should we actually emit this log?" checks and was attempting to write to stdout.

The controller's logging situation is somewhat confusing and has multiple log libraries wrapping each other as best I recall. https://github.com/Kong/kubernetes-ingress-controller/blob/9e3b4a5fe6151be7c5b99b01b5f0a59f139e3e1a/internal/manager/setup.go#L33-L53 sets up the controller-runtime logger, which we then [bind to the reconciler configuration](https://github.com/Kong/kubernetes-ingress-controller/blob/9e3b4a5fe6151be7c5b99b01b5f0a59f139e3e1a/internal/manager/controllerdef.go#L89). Somewhat confusingly, the initial `WARNING: log stifling has been enabled (experimental)` message, sent via that same logger, does appear.

Acceptance:
- [ ] Reconciler logs appear in integration test stdout or stderr, or are otherwise accessible if it's not possible to send to stdout or stderr.

**Comment by rainest** [comment]
May be something specific to the Makefile invocation or Actions workflow? It looks like I do get these locally when running `dlv test` directly.

**Comment by randmonkey** [comment]
> May be something specific to the Makefile invocation or Actions workflow? It looks like I do get these locally when running `dlv test` directly.

I think so.

**Comment by jrsmroz** [comment]
This may be related to what was already fixed in KGO. https://github.com/Kong/gateway-operator/pull/75

> sigs.k8s.io/controller-runtime package has a deadline od 30s, to set up a logger. After the time passes, the logger is set to nil logger and cannot be changed.
>
> This PR changes the integration tests setup order, so the controller logger is setup before setup of kind cluster begins. Kind cluster setup can take way more than 30s, thus the logger needs to be in place before the kind cluster is created.

The deadline starts ticking when the controller package is loaded. 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/log/log.go#L60-L70
