### ISSUE TITLE
Ingress Controller 0.4.0 - Service scoped plugins are not created

### ISSUE THREAD

**Issue by davideagle** [Kong/kubernetes-ingress-controller#289]
Ingress Controller - service scoped plugins are not created
### Summary

Ingress controller does not create Service scoped plugins, however Route scoped plugins are creeated

**Kong Ingress controller version**
0.4.0

**Kong or Kong Enterprise version**
Kong 1.1.2

### Kubernetes version

Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.7", GitCommit:"65ecaf0671341311ce6aea0edab46ee69f65d59e", GitTreeState:"clean", BuildDate:"2019-01-24T19:22:45Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64"}

### What happened
Only Route Scoped plugins are created

**Ingress Controller Log**
> kong-ingress-controller-86895d6b65-7hspd ingress-controller 3 errors occured:
kong-ingress-controller-86895d6b65-7hspd ingress-controller while processing event: {Create} failed: 400 Bad Request {“message”:“schema violation (protocols: must match the protocols of at least one route pointing to this Plugin’s service)”,“name”:“schema violation”,“fields”:{“protocols”:“must match the protocols of at least one route pointing to this Plugin’s service”},“code”:2}
kong-ingress-controller-86895d6b65-7hspd ingress-controller while processing event: {Create} failed: 400 Bad Request {“message”:“schema violation (protocols: must match the protocols of at least one route pointing to this Plugin’s service)”,“name”:“schema violation”,“fields”:{“protocols”:“must match the protocols of at least one route pointing to this Plugin’s service”},“code”:2}
kong-ingress-controller-86895d6b65-7hspd ingress-controller while processing event: {Create} failed: 400 Bad Request {“message”:“schema violation (protocols: must match the protocols of at least one route pointing to this Plugin’s service)”,“name”:“schema violation”,“fields”:{“protocols”:“must match the protocols of at least one route pointing to this Plugin’s service”},“code”:2}

**Kong Proxy Log**
> kong-proxy-657755bddf-kmhb4 kong-proxy 100.96.12.235 - - [08/May/2019:12:16:24 +0000] “GET /plugins/schema/basic-auth HTTP/1.1” 200 126 “-” “Go-http-client/1.1”
kong-proxy-657755bddf-kmhb4 kong-proxy 100.96.12.235 - - [08/May/2019:12:16:24 +0000] “GET /plugins/schema/acl HTTP/1.1” 200 190 “-” “Go-http-client/1.1”
kong-proxy-657755bddf-kmhb4 kong-proxy 100.96.12.235 - - [08/May/2019:12:16:24 +0000] “GET /plugins/schema/key-auth HTTP/1.1” 200 329 “-” “Go-http-client/1.1”
kong-proxy-657755bddf-kmhb4 kong-proxy 100.96.12.235 - - [08/May/2019:12:16:24 +0000] “POST /plugins HTTP/1.1” 400 265 “-” “Go-http-client/1.1”
kong-proxy-657755bddf-kmhb4 kong-proxy 100.96.12.235 - - [08/May/2019:12:16:24 +0000] “POST /plugins HTTP/1.1” 400 265 “-” “Go-http-client/1.1”
kong-proxy-657755bddf-kmhb4 kong-proxy 100.96.12.235 - - [08/May/2019:12:16:24 +0000] “POST /plugins HTTP/1.1” 400 265 “-” “Go-http-client/1.1”

### Expected behvaior
Service Scoped plugins should have been created

### Steps To Reproduce
Apply https://gist.github.com/davideagle/a5d846f8446d811471a882aaea74120f

**Comment by hbagdi** [comment]
This will be fixed as part of #295 

The fix in deck (https://github.com/hbagdi/deck/pull/16) is present in deck v0.3.0, which is what we will be using once #295 is merged in.

**Comment by davideagle** [comment]
I see that the upgrade to deck v0.3.0 has been merged in, do I have to wait for the next release of kubernetes-ingress-controller in order to try this out?

**Comment by hbagdi** [comment]
Yes, another release in the works and will be out in a couple of weeks.

**Comment by hbagdi** [comment]
This will be fixed with 0.5.0 hence. closing this.
