### ISSUE TITLE
remove `v1alpha2.GatewayClass` support, switch to `v1beta1`

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#2890]

**Comment by shaneutt** [comment]
Should this just be a PR and not need it's own issue? Was #2887 insufficient to cover the scope?

**Comment by pmalek** [comment]
> Should this just be a PR and not need it's own issue? Was #2887 insufficient to cover the scope?

I was tempted to use Github's UI and create an issue out of bullet points that you've created. This was I thought I could easily track the status of the "epic" which in my view (after deciding to split it up) #2887 is.
