### ISSUE TITLE
Handle the error case: `HTTPRoute` on a TLS listener that is `passthrough`

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#2901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

When the user creates a `Gateway` with a TLS listener with mode = `passthrough`, routes that don't work with passthrough mode (most notably `HTTPRoute` but other kinds might fall into this case, too) need appropriate error handling for that case.

### Additional information

This will be much easier to implement after [#2662](https://github.com/Kong/kubernetes-ingress-controller/issues/2662) is done.

### Acceptance Criteria

- [ ] Attaching a HTTPRoute or TCPRoute to a Gateway that supports TLS but it wants to use passthrough, should be resolved to an error.
- [ ] Attaching a TLSRoute to a TLS listener that specifies terminate results in an error condition.

**Comment by mlavacca** [comment]
There are some upstream (https://github.com/kubernetes-sigs/gateway-api/issues/1474) docs inconsistencies that affect the ACs of this issue. Blocking it until the upstream issue gets resolved.

**Comment by mflendrich** [comment]
Since TCP/TLS/UDPRoutes are alpha maturity in KIC, we're good to make a guess about the expected behavior that we'll correct if necessary before promoting to beta/GA.

**Comment by randmonkey** [comment]
I think this issue should be moved out of KIC 2.8.0 milestone, because the upstream dependent  https://github.com/kubernetes-sigs/gateway-api/issues/1474 is in v0.7.0 milestone now, which is not expected to release in recent days.
