### ISSUE TITLE
Can't access Administration Console page with keycloak behind Kong

### ISSUE THREAD

**Issue by jhonyscamacho** [Kong/kubernetes-ingress-controller#291]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

I have Keycloak behind [Kong Ingress Controller](https://github.com/Kong/kubernetes-ingress-controller). 
I 'm able to see keycloak welcome page at my **{url}/auth/**. However, when I click at **Administration Console** I am redirected to **{url}:8000/auth/admin/master/console/**

Further information:

In the first moment I thought that the problem was with keycloak, but @Igor-lkm tested [keycloak behind express-gateway and it's worked ok](https://github.com/codecentric/helm-charts/issues/17#issuecomment-490427197). So, looks like the problem is with kong.

@Igor-lkm made others test cases: [here](https://gitter.im/Kong/kong?at=5cd2be415d48a24fd090998e)
### Kubernetes version

- kubectl: 
  ```bash
  Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"} 
  Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:30:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
  ```

### Environment

- **Cloud provider or hardware configuration**: AWS
- **Install tools**: kubectl, helm
- **Others**:

### What happened

I have Keycloak behind [Kong Ingress Controller](https://github.com/Kong/kubernetes-ingress-controller). 
I 'm able to see keycloak welcome page at my **{url}/auth/**. However, when I click at **Administration Console** I am redirected to **{url}:8000/auth/admin/master/console/**

### Expected behvaior

When I click at **Administration Console** I should be redirect to **{url}/auth/admin/master/console/**

### Steps To Reproduce

1. Create a kubernetes cluster with kops in AWS
2. Installing [Kong Ingress Controller](https://github.com/Kong/kubernetes-ingress-controller) executing the following command:

```bash
helm install --name kong-develop --namespace develop stable/kong \
--set ingressController.enabled=true
```
3. Create an AWS Classic Load Balancer following the instructions bellow:

3.1 Basic Configuration

* **Load Balancer name**: KongDevelopLB
* **Create LB Inside**: Choose your cluster VPC

3.2 Listeners

| Load Balancer Protocol | Load Balancer Port | Instance Protocol | Instance Port |
|:----------------------:|:------------------:|:-----------------:|---------------|
| TCP | 80 | TCP | kong-proxy NodePort service |
| TCP | 443 | TCP | kong-proxy TLS NodePort service |
| TCP | 8444 | TCP | kong-admin NodePort service |

To help you detect the correct ports, take a look at the example image bellow:

![kong-services](https://user-images.githubusercontent.com/27226470/57199709-6ee7c900-6f58-11e9-9141-412d28d9f7dd.png)

In the example cluster shown in the image above:

* Load Balancer port **80** should point to instance port **32518**;
* Load Balancer port **443** should point to instance port **31021**;
* Load Balancer port **8444** should point to instance port **31725**.

3.3 Select Subnets

* **Select Subnets**: Select the cluster available subnets

3.4 Security Group

* **Assign a security group**: Create a new security group
* **Security group name**: KongDevelopLB-SecurityGroup

Type | Protocol | Port Range | Source
-- | -- | -- | --
Custom TCP Rule | TCP | 80 | Anywhere
Custom TCP Rule | TCP | 443 | Anywhere
Custom TCP Rule | TCP | 8444 | Anywhere

3.5 Configure Health Check

Health Check should point to kong-admin NodePort service. To help you find the correct port take a look at the example image bellow.

Based on the image bellow health check should point to **31725** port.

![kong-services](https://user-images.githubusercontent.com/27226470/57199709-6ee7c900-6f58-11e9-9141-412d28d9f7dd.png)

3.6 Add EC2 Instances

Add only the **node instances**.

3.8 Bind Load Balancer and Cluster

Edit the node cluster **Inbound security group** adding the following rules:

| Type | Protocol | Port Range | Source | Description |
|:----:|:--------:|:----------:|:------:|:-----------:|
| Custom TCP Rule | TCP | kong-admin NodePort service | Custom - **the KongDevelopLB security group id** | kongDevelopLB |
| Custom TCP Rule | TCP | kong-proxy NodePort service | Custom - **the KongDevelopLB security group id** | kongDevelopLB |
| Custom TCP Rule | TCP | kong-proxy TLS NodePort service | Custom - **the KongDevelopLB security group id** | kongDevelopLB |

Example:

![kong-services](https://user-images.githubusercontent.com/27226470/57199709-6ee7c900-6f58-11e9-9141-412d28d9f7dd.png)

Based on the image above:

* kong-admin NodePort service is **31725**.
* kong-proxy NodePort service is **32518**.
* kong-proxy TLS NodePort service is **31021**.

3.9 Create an alias to the Load Balancer

In Route53 service, create an alias record set inside inside cluster hosted zone to point to kong Load Balancer.

Example:

If your cluster DNS name is **kubernetes.mydomain.com**
you could create an alias record set like this: **develop.kubernetes.mydomain.com**

4. Installing keycloak behind Kong Ingress

4.1 Create a values.yaml file with the content bellow:

```yaml
init:
 image:
  pullPolicy: Always

keycloak:
 username: admin
 password: admin
 readinessProbe:
  timeoutSeconds: 60
 service:
  type: NodePort
 persistence:
  deployPostgres: true
  dbVendor: postgres
 ingress:
  enabled: true
  hosts:
   - develop.kubernetes.mydomain.com
 extraEnv: |
   - name: PROXY_ADDRESS_FORWARDING
     value: "true"
```
4.2 Install keycloak using the values.yaml files craeted in step 4.1

Execute the code bellow:

```bash
helm install --name keycloak-develop --namespace develop codecentric/keycloak --values values.yaml
```

4.3 Access keycloak 

Open the browser and access the following url: **http://develop.kubernetes.mydomain.com/** and you gonna be redirected to http://develop.kubernetes.mydomain.com/auth/

4.4 Access the Administration Console

Click at the Administration Console link and you will be redirected to **https://develop.kubernetes.mydomain.com:8000/auth/admin/master/console/**

**Comment by gpguerra** [comment]
I had the same problem. But I did not use helm to deploy keycloak. 
I had to set these variables in keycloak manifest to make the redirect work.
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_HOSTNAME
          value: keycloak.example.com #your hostname
        - name: KEYCLOAK_HTTP_PORT
          value: "80"
        - name: KEYCLOAK_HTTPS_PORT
          value: "443"


hope it helps.

**Comment by hbagdi** [comment]
@jhonyscamacho Could you try the steps recommended by @gpguerra and close the issue if i fixes the problem for you?

**Comment by jhonyscamacho** [comment]
> I had the same problem. But I did not use helm to deploy keycloak.
> I had to set these variables in keycloak manifest to make the redirect work.
> - name: PROXY_ADDRESS_FORWARDING
> value: "true"
> - name: KEYCLOAK_HOSTNAME
> value: keycloak.example.com #your hostname
> - name: KEYCLOAK_HTTP_PORT
> value: "80"
> - name: KEYCLOAK_HTTPS_PORT
> value: "443"
> 
> hope it helps.

@gpguerra thanks for the help!

I follow the steps and it didn't work. The problem persists.

I configure the variables with [keycloak helm](https://github.com/codecentric/helm-charts/tree/master/charts/keycloak) via keycloak.extraEnv parameter and with deployment file, using the [keycloak docker image directly](https://hub.docker.com/r/jboss/keycloak/)

In both cases the problem is the same: the estrange redirect to port 8000 when I click at the Administration Console link.

I'm still try to solve the problem. Any help is welcome.

**Comment by jhonyscamacho** [comment]
Definitely it is a Ingress problem.

I created a keycloak deployment (using service **LoadBalancer**) based in the yaml file below and it worked, keycloak Admin Console was accessible and the 8000 redirect was gone.

```yaml

keycloak:
 image:
  pullPolicy: Always
 username: admin
 password: admin
 readinessProbe:
  timeoutSeconds: 60
 service:
  type: LoadBalancer
 persistence:
  deployPostgres: true
  dbVendor: postgres
 extraEnv: |
  - name: KEYCLOAK_HTTP_PORT
    value: "80"
  - name: KEYCLOAK_HTTPS_PORT
    value: "443"
```

I'm still getting an strange HTTPS error but it's a work in progress.

I have no idea about what is causing the ingress problem/bu. Any help is welcome.

**Comment by hbagdi** [comment]
I spent some time to replicate this issue and found the following:

The ELB is configured with TCP protocol on both sides, meaning ELB terminates the TCP connection from client. Kong receives the connection and then injects `X-Forwarded-Port` header. Since Kong is listening on port 8000, it sets the header value to 8000. 
Keycloak respects the header value and constructs the redirect URL accordingly.

So, there is nothing technically wrong here with Kong or Keycloak, in fact they are doing what exactly should be doing:

To fix the problem, you have two options:
- Configure keycloak with explicit ports via env vars as you have done
- Change Kong listeners to listen on 80 and 443 for HTTP and HTTPS respectively and then the injected `X-Forwarded-Port` will be correct

**Comment by jhonyscamacho** [comment]
> I spent some time to replicate this issue and found the following:
> 
> The ELB is configured with TCP protocol on both sides, meaning ELB terminates the TCP connection from client. Kong receives the connection and then injects `X-Forwarded-Port` header. Since Kong is listening on port 8000, it sets the header value to 8000.
> Keycloak respects the header value and constructs the redirect URL accordingly.
> 
> So, there is nothing technically wrong here with Kong or Keycloak, in fact they are doing what exactly should be doing:
> 
> To fix the problem, you have two options:
> 
> * Configure keycloak with explicit ports via env vars as you have done
> * Change Kong listeners to listen on 80 and 443 for HTTP and HTTPS respectively and then the injected `X-Forwarded-Port` will be correct

@hbagdi thanks for the help!

Could you please share both kong Ingress and keycloak configuration yaml files?

**Comment by hbagdi** [comment]
The first option, you have figured out the solution yourself. Add the following to the values.yaml for keycloak helm chart:
```yaml
 extraEnv: |
  - name: KEYCLOAK_HTTP_PORT
    value: "80"
  - name: KEYCLOAK_HTTPS_PORT
    value: "443"
```

For the second, use the following values for the helm chart:

```yaml
proxy:
  # HTTP plain-text traffic
  http:
    enabled: true
    servicePort: 80
    containerPort: 80
  tls:
    enabled: true
    servicePort: 443
    containerPort: 443
ingressController:
  enabled: true
```


Please close this issue if your issue is resolved, thanks!

**Comment by jhonyscamacho** [comment]
> The first option, you have figured out the solution yourself. Add the following to the values.yaml for keycloak helm chart:
> 
> ```yaml
>  extraEnv: |
>   - name: KEYCLOAK_HTTP_PORT
>     value: "80"
>   - name: KEYCLOAK_HTTPS_PORT
>     value: "443"
> ```
> 
> For the second, use the following values for the helm chart:
> 
> ```yaml
> proxy:
>   # HTTP plain-text traffic
>   http:
>     enabled: true
>     servicePort: 80
>     containerPort: 80
>   tls:
>     enabled: true
>     servicePort: 443
>     containerPort: 443
> ingressController:
>   enabled: true
> ```
> 
> Please close this issue if your issue is resolved, thanks!

Thanks!

My kong Ingress configuration was missing the enabled and service parameters.

I will test it and give feedback asap!

**Comment by jhonyscamacho** [comment]
> The first option, you have figured out the solution yourself. Add the following to the values.yaml for keycloak helm chart:
> 
> ```yaml
>  extraEnv: |
>   - name: KEYCLOAK_HTTP_PORT
>     value: "80"
>   - name: KEYCLOAK_HTTPS_PORT
>     value: "443"
> ```
> 
> For the second, use the following values for the helm chart:
> 
> ```yaml
> proxy:
>   # HTTP plain-text traffic
>   http:
>     enabled: true
>     servicePort: 80
>     containerPort: 80
>   tls:
>     enabled: true
>     servicePort: 443
>     containerPort: 443
> ingressController:
>   enabled: true
> ```
> 
> Please close this issue if your issue is resolved, thanks!

@hbagdi I tried the second option and it didn't work.

When I try to change Kong listeners to listen on 80 and 443 for HTTP and HTTPS respectively kong pod status get CrashLoopBackOff as shown in the image bellow:

![Screenshot_2019-05-15_18-26-03](https://user-images.githubusercontent.com/27226470/57810648-ad426c80-773e-11e9-9689-56c1e18e54b3.png)

![Screenshot_2019-05-15_18-26-03----](https://user-images.githubusercontent.com/27226470/57810892-4ec9be00-773f-11e9-84e2-8504e7833851.png)

**Comment by hbagdi** [comment]
For the second option to work, you will need to add `cap_net_bind_service` permission to the Kong's executable: https://github.com/Kong/docker-kong/blob/master/alpine/docker-entrypoint.sh#L31


This is intentionally left as is to not give Kong the ability to bind to privileged ports.

**Comment by jhonyscamacho** [comment]
> For the second option to work, you will need to add `cap_net_bind_service` permission to the Kong's executable: https://github.com/Kong/docker-kong/blob/master/alpine/docker-entrypoint.sh#L31
> 
> This is intentionally left as is to not give Kong the ability to bind to privileged ports.

Is there a way to configure it using helm chart?

**Comment by hbagdi** [comment]
You will have to create a new Docker image using Kong's docker image to give Kong that permission. There is nothing that can be done with Helm for this (and whatever is needed is already present in the Helm chart).

The first solution should suffice to solve the problem you're facing.

**Comment by jhonyscamacho** [comment]
I will test and provide feedback

**Comment by jhonyscamacho** [comment]
> > The first option, you have figured out the solution yourself. Add the following to the values.yaml for keycloak helm chart:
> > ```yaml
> >  extraEnv: |
> >   - name: KEYCLOAK_HTTP_PORT
> >     value: "80"
> >   - name: KEYCLOAK_HTTPS_PORT
> >     value: "443"
> > ```
> > 
> > 
> > For the second, use the following values for the helm chart:
> > ```yaml
> > proxy:
> >   # HTTP plain-text traffic
> >   http:
> >     enabled: true
> >     servicePort: 80
> >     containerPort: 80
> >   tls:
> >     enabled: true
> >     servicePort: 443
> >     containerPort: 443
> > ingressController:
> >   enabled: true
> > ```
> > 
> > 
> > Please close this issue if your issue is resolved, thanks!
> 
> @hbagdi I tried the second option and it didn't work.
> 
> When I try to change Kong listeners to listen on 80 and 443 for HTTP and HTTPS respectively kong pod status get CrashLoopBackOff as shown in the image bellow:
> 
> ![Screenshot_2019-05-15_18-26-03](https://user-images.githubusercontent.com/27226470/57810648-ad426c80-773e-11e9-9689-56c1e18e54b3.png)
> 
> ![Screenshot_2019-05-15_18-26-03----](https://user-images.githubusercontent.com/27226470/57810892-4ec9be00-773f-11e9-84e2-8504e7833851.png)
> 
> Although, kong ingress listen to default ports works correctly.

@hbagdi as you said, the first solution worked.

Thanks for the help!

@gpguerra thank you!

**Comment by samsja** [comment]
> For the second option to work, you will need to add `cap_net_bind_service` permission to the Kong's executable: https://github.com/Kong/docker-kong/blob/master/alpine/docker-entrypoint.sh#L31
> 
> This is intentionally left as is to not give Kong the ability to bind to privileged ports.

Hello, i am having the exact same issue with my keycloak behing the kong ingress controler.
The first solution that add ExtraEnv varaible is not working wiht me and i am trying the second one, but i am not able to manualy change the proxy https redirection, how can i add cap_net_bind_service permission to the Kong's executable , as you said before ?

**Comment by spacejam101** [comment]
@jhonyscamacho Having the same issue also ^ but I binded the port on 80 with keycloak already and still having the error.

**Comment by Igor-lkm** [comment]
@jhonyscamacho is not working either 🤔

**Comment by Igor-lkm** [comment]
In fact I just had a second look and seems env variable `KEYCLOAK_HOSTNAME` is required. So this config would work:

```
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_HTTP_PORT
      value: "80"
    - name: KEYCLOAK_HTTPS_PORT
      value: "443"
    - name: KEYCLOAK_HOSTNAME
      value: example.com
```

And this one would not:

```
  extraEnv: |
    - name: KEYCLOAK_HTTP_PORT
      value: "80"
    - name: KEYCLOAK_HTTPS_PORT
      value: "443"
```

😲 🎉
