### ISSUE TITLE
KIC's Gateway API able to work under KGO

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#2913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

This issue is needed to make the kong-gateway-operator (KGO) work with `HTTPRoutes`: as a KGO user I want to deploy a Gateway, and then once it's ready I want to deploy HTTPRoutes which will be served by that Gateway. To achieve so, we need to remove the KIC requirement that Gateway resources be unmanaged.

### Additional information

related KGO issue: https://github.com/Kong/gateway-operator/issues/188

### Acceptance Criteria

- [ ] We should allow the injection of the controller-name via args
- [ ] The gateway resources shouldn't be unmanaged to be successfully reconciled

**Comment by randmonkey** [comment]
Thank you for @mlavacca's effort to find out that we need to remove the KIC requirement that Gateway resources be unmanaged. I have already worked on KGO part, and it is OK for me to address both parts.

**Comment by mlavacca** [comment]
Sure, @randmonkey. Feel free to unassign me and assign yourself :)
