### ISSUE TITLE
Deprecate KongIngress fields that are available via annotations

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#2941]
## Problem Statement

KongIngress was initially the sole means of configuring Kong-specific (e.g. `https_redirect_status_code`) settings on Kong services derived from Services and routes derived from Ingresses. Over time (circa early 2020?), we added support for configuring these via annotations instead. Annotations are the preferred method to configure these settings (maintaining a single resource is easier than maintaining two) and take precedence when both an annotation and KongIngress configure the same field. We retained the ability to configure existing settings via KongIngress for compatibility with existing configuration.

AFAIK upstream configuration is still handled via KongIngress. Upstream configuration, in particular load balancing configuration, is a complex object that cannot fit within a single annotation string value. Upstream configuration will continue to require a CRD, though ideally this should be a new KongUpstream CRD. An additional source of confusion for KongIngress is that it can apply to an Ingress or Service, but only the configuration corresponding to the resulting object is honored. You can create a KongIngress with a `service.connect_timeout` or `upstream.*` and attach it to an Ingress, but we won't do anything with that configuration--those fields are only applied when the KongIngress is attached to a Service. This is unintuitive for users without a detailed mental model of how the Kubernetes resources and Kong resources interact. KongIngress's name is further misleading and suggests that it should be applied to Ingresses only (or in some users' interpretation, should be a wholesale replacement for the standard Ingress object).

Having two means of configuring the same settings is confusing, as it's not clear from the configuration itself what the resulting configuration will be when both attempt to configure the same setting. I am not aware of compelling reasons to have KongIngress continue to support fields available via annotations other than backwards compatibility, and propose that we deprecate them and later remove them in a major release. This requires several changes:

## Proposed Solution

- Audit KongIngress fields to check if they are not supported via annotations and either add annotations for them or report on why annotations are not possible. The [service timeout fields](https://github.com/Kong/kubernetes-ingress-controller/blob/7cf2144443d340254e937900bf89ee9fa349a8c6/internal/dataplane/kongstate/service.go#L57-L81) are a conspicuous example that definitely can be annotations, as they're all single integer values.
- Find a way for Ingresses to support an annotation for headers (this looks like the only KongIngress-only route field). This may be annoying to deal with. `konghq.com/headers: foo:a,b,c;bar:x,y,z` would kinda work but would be clunky as hell and break semicolons (commas are fine to break, they're already a designated special separation character). Can we use an annotation prefix, like `konghq.com/header/foo: a,b,c` and `konghq.com/header/bar: x,y,z`?
- If we find service or route fields that cannot fit in annotations, revisit whether we wish to proceed with deprecation at all, keep KongIngress with only these fields, or create additional CRDs beyond KongUpstream.
- Add a feature flag that preserves the existing KongIngress behavior and toggle it off by default once we deprecate the feature. Remove this flag and existing KongIngress functionality entirely in a later release.
- Add a new KongUpstream CRD and controller, and use it to apply configuration to the upstreams generated for services. We may optionally keep KongIngress around and keep this functionality there, but I'd recommend we kill the name ambiguity if possible. Add an annotation that applies this configuration to Service resources and warns users if they instead attempt to apply it to an Ingress.

## Additional Information

We may optionally look at providing documentation for generating similar resources. KongIngress does provide one bit of functionality that annotations definitely cannot: you can attach the same KongIngress to many resources, update the single KongIngress and have that change reflected across all generated Kong resources. IMO something like this should be doable with Kustomize and handled before applying the resources rather than having an in-controller templating system. Kustomize works generically to apply patches to any Kubernetes resource and results WYSIWG configuration in the cluster: templating, for example, that all Ingresses have `request_buffering: true" client side means that all your Ingresses on the server will actually show that they have `request_buffering: true` set. Templating inside the controller means that users need to look at multiple resources to determine the final configuration and differentiate template versus setting application bugs if the result is incorrect, and that we'll need to maintain an additional large feature. Even if we do use in-controller templating, KongIngress isn't actually sufficient to meet user requests (IIRC we've received requests to also template KongPlugins, and KongIngress doesn't provide that).

Further work:

- [x] #3017
- [ ] #3018

## Acceptance Critieria

- [x] For each non-Upstream KongIngress field, if an equivalent of that field is possible to set by means of a k8s annotation, this field is marked as deprecated in the CRD and in the documentation.
- [x] For KongIngress fields that are left not deprecated after the above, issues exist to migrate them off of KongIngress (and these issues are listed in a comment on this issue)

**Comment by jrsmroz** [comment]
I was actually updating the docs to indicate which annotations override KonIngress fields: https://github.com/Kong/docs.konghq.com/pull/4483

**Comment by rainest** [comment]
https://github.com/Kong/docs.konghq.com/pull/4799 is the non-schema set of doc changes that announce this. It's currently invisible, but will appear once we add 2.8.

https://github.com/Kong/kubernetes-ingress-controller/issues/3174 is the issue for the remaining section (upstream) that needs to be migrated into a new CRD.

**Comment by rainest** [comment]
https://github.com/Kong/docs.konghq.com/pull/4813 doesn't substantively change what's already in place, but will be the final version of the CRD page once it's in. The generator source [now includes the updated deprecation info](https://github.com/Kong/kubernetes-ingress-controller/pull/3246).

There's nothing more to do here, so closing this. #3019 is sorta the successor and already in the milestone.
