### ISSUE TITLE
Gateway API ReferenceGrant reaching BETA

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#2954]
### Problem Statement

Previously `ReferenceGrant` was an alpha only API feature. As of `v0.6.0` of Gateway API this will be in beta and we should promote our implementation.

### Prerequisites

- [x] https://github.com/kubernetes-sigs/gateway-api/issues/1448
- [x] #3214 

### Acceptance Criteria

- [ ] as a user, `ReferenceGrant` is working properly for my `v1beta1` Gateway API resources

**Comment by mflendrich** [comment]
Blocked on Gateway API v0.6.0 being released.

**Comment by mflendrich** [comment]
Blocked by #3214
