### ISSUE TITLE
Visibility of Gateway API: warning banner is gone for KIC 2.6

### ISSUE THREAD

**Issue by jrsmroz** [Kong/kubernetes-ingress-controller#2967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The Gateway API articles has `alpha:true` set in frontmatter. As a result the articles are marked with a warning banner `his feature is released as a [tech preview](https://docs.konghq.com/gateway/latest/availability-stages/#tech-preview) (alpha-quality) and should not be deployed in a production environment.` This is no longer true for KIC 2.6, the Gateway API is not alpha maturity.

Example articles with the banner include:
- https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/gateway-api/
- https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/using-gateway-api/

### Proposed Solution

Remove the banner. The https://github.com/Kong/docs.konghq.com/pull/4486 made it possible to override this flag for specific release.

Some examples:
```
---
title: Page Here
alpha: false # This is the default, but is here for completeness

overrides:
  alpha:
    true:
      gte: 2.3.x
      lte: 2.5.x
---
```

```
---
title: Another Page
availability: GA

overrides:
  availability:
    Private Beta:
      lte: 2.8.x
---
```

We should ensure that the banner is gone for KIC 2.6 documentation.

### Additional information

Splited from https://github.com/Kong/kubernetes-ingress-controller/issues/2878

### Acceptance Criteria

- [x] As a KIC user, when I read the GW API documentation for KIC 2.5 and bellow, I am warned by a banner the Gateway API is alpha level support.
- [x] As a KIC user, when I read the GW API documentation for KIC 2.6 and above, I am not getting a warning banner.
- [x] As docs maintainer I ensured that all KIC articles wirth GW API banner have been updated.

**Comment by scseanchow** [comment]
Does this need to be tied to a KIC release, can we just make this change and merge to docs ASAP?

**Comment by pmalek** [comment]
I've pushed this to address this issue: https://github.com/Kong/docs.konghq.com/pull/4588

PTAL

**Comment by pmalek** [comment]
With the above 2 PRs merged this can be closed.
