### ISSUE TITLE
Visibility of Gateway API: getting started guide update

### ISSUE THREAD

**Issue by jrsmroz** [Kong/kubernetes-ingress-controller#2969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

[Getting started](https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/getting-started/), probably one of the first steps for most users, does not mention the Gateway API at all. 

### Proposed Solution

[Getting started](https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/getting-started/) mentions the existence of Gateway API support in KIC .

### Additional information

- Splitted from https://github.com/Kong/kubernetes-ingress-controller/issues/2878
- Should be easier to do after the https://github.com/Kong/kubernetes-ingress-controller/issues/2966 is completed.

### Acceptance Criteria

- [ ] As KIC user, after reading the [Getting started guide](https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/getting-started/) , I am aware of the Gateway API support in KIC.
- [ ] As KIC user, after reading the [Getting started guide](https://docs.konghq.com/kubernetes-ingress-controller/2.6.x/guides/getting-started/), I know how to configure basic traffic proxying using the Gateway API.

**Comment by randmonkey** [comment]
fixed by https://github.com/Kong/docs.konghq.com/issues/4638
