### ISSUE TITLE
Release Pipeline - RH Portal backend registry is changing to quay.io 

### ISSUE THREAD

**Issue by DaniellaFreese** [Kong/kubernetes-ingress-controller#2977]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

For the Red Hat Image Certification - the image is pushed to the backend redhat registry. Red Hat informed us they are making a minor update to the portal, and moving to quay.io. The impact is the login, registry key, and image tag are shifting to the new registry. 

The change is scheduled to take effect Oct 3. 

We have been provided a UAT environment to review, test and validate the changes. Any team member with access to RH portal can login to the UAT env. Here is the link to the changes in KIC RH UAT Portal : https://connect.uat.redhat.com/projects/5eab1b8ea165648bd1353266/settings

### Proposed Solution

For the release pipeline - update the credentials and image tag used to push images to the backend RH registry. 

### Acceptance Criteria

- [ ] `RH_TOKEN` and `RH_USERNAME` secrets for a new registry.
- [ ]  `RH_SCAN_REGISTRY` is updated to a new registry
  - Defined in [release.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/release.yaml) file
- [ ] The release pipeline after Oct 3 2022 is pushing images to the new docker registry.
- [ ] The newly pushed images are visible in Red Hat Connect portal under KIC project.

**Comment by jrsmroz** [comment]
Added acceptance criteria.

**Comment by jrsmroz** [comment]
I've added the acceptance criteria, that should reflect the scope of work.
