### ISSUE TITLE
Update Gateway API to 0.5.1

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#2998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The Gateway API 0.5.1 has been released and we need to make us compliant with the conformance test changes.

### Proposed Solution

* bump the Gateway API to 0.5.1
* identify the conformance test failures
* fix the controller behavior to be conformant with the API

### Acceptance Criteria

- [ ] The Gateway API is updated to the latest (0.5.1) version
- [ ] All the conformance tests pass

**Comment by jrsmroz** [comment]
Example log from failed conformance tests: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3149841829/jobs/5125891514
