### ISSUE TITLE
can not create/update KongClusterPlugin or KongPlugin due to error "configFrom.secretKeyRef.key: Required value"

### ISSUE THREAD

**Issue by albertforweb** [Kong/kubernetes-ingress-controller#3000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

similar as this closed but not fixed : https://github.com/Kong/kubernetes-ingress-controller/issues/780 

version is used " github.com/kong/kubernetes-ingress-controller v1.3.4 "

trying to update a KongClusterPlugin with this payload:
{
 "kind": "KongClusterPlugin",
 "apiVersion": "configuration.konghq.com/v1",
 "metadata": {
  "name": "global-request-termination",
  "creationTimestamp": null,
  "labels": {
   "global": "true"
  },
  "annotations": {
   "kubernetes.io/ingress.class": "kong"
  }
 },
 "disabled": true,
 "config": {
  "message": "So long and thanks for all the fish!",
  "status_code": 403
 },
 "configFrom": {
  "secretKeyRef": {}
 },
 "plugin": "request-termination"
}

but got this error :
"
KongClusterPlugin.configuration.konghq.com "global-request-termination" is invalid: [configFrom.secretKeyRef.key: Required value, configFrom.secretKeyRef.name: Required value, configFrom.secretKeyRef.namespace: Required value
"

and same thing also happens on KongPlugin

### Expected Behavior

should not check on "configFrom" and be able to create or update KongPlugin and KongClusterPlugin when "configFrom" is not provided

### Kong Ingress Controller version

```shell
kubernetes-ingress-controller:2.5.0
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rainest** [comment]
That resource _is_ setting a `configFrom` though:

```
...
"message": "So long and thanks for all the fish!",
"status_code": 403
},
"configFrom": {
"secretKeyRef": {}
},
...
```
You want to not set that field at all, not provide a partial object.
