### ISSUE TITLE
unexpected failure updating Kong  configuration: route 'e3a45d7e-6c' does not have a name. decK needs routes to be named.

### ISSUE THREAD

**Issue by ajistyle** [Kong/kubernetes-ingress-controller#301]
I have a problem, I hope you can help me solve it.  please!

    shell > kubectl logs kong-ingress-controller-df98bfddb-kkhz9 -n kong ingress-controller

E0604 00:52:28.572669       7 controller.go:117] unexpected failure updating Kong     configuration:
route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
W0604 00:52:28.572698       7 queue.go:113] requeuing kube-system/kube-dns, err route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
E0604 00:52:31.906827       7 controller.go:117] unexpected failure updating Kong configuration:
route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
W0604 00:52:31.906856       7 queue.go:113] requeuing kube-system/kubernetes-dashboard, err route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
E0604 00:52:35.230292       7 controller.go:117] unexpected failure updating Kong configuration:
route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
W0604 00:52:35.230321       7 queue.go:113] requeuing kube-system/kube-dns, err route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
E0604 00:52:38.573080       7 controller.go:117] unexpected failure updating Kong configuration:
route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
W0604 00:52:38.573109       7 queue.go:113] requeuing kube-system/kubernetes-dashboard, err route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
E0604 00:52:41.900031       7 controller.go:117] unexpected failure updating Kong configuration:
route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
W0604 00:52:41.900060       7 queue.go:113] requeuing kong/kong-proxy, err route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
E0604 00:52:45.229800       7 controller.go:117] unexpected failure updating Kong configuration:
route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
W0604 00:52:45.229830       7 queue.go:113] requeuing guanwei/guanwei-sys-mvc, err route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
E0604 00:52:48.572557       7 controller.go:117] unexpected failure updating Kong configuration:
route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.
W0604 00:52:48.572584       7 queue.go:113] requeuing default/kubernetes, err route 'e3a45d7e-6c08-4305-868a-f512aad6ecc6' does not have a name. decK needs routes to be named.

**Comment by hbagdi** [comment]
It seems like you upgraded from Kong Ingress Controller 0.3.0 to 0.4.0. You need a fresh Kong cluster for the upgrade as the older and newer version of the Ingress Controller are not compatible due to the breaking changes that are made between the two versions.
