### ISSUE TITLE
E2E tests shouldn't use cleaner.Cleanup

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As E2E tests create their own clusters, it doesn't make sense to use `cleaner.Cleanup` (cleaning up in-cluster resources created by the test) on their tear down. Instead, we should simply `cluster.Cleanup` the whole cluster. It should save some time while running the tests.

### Proposed Solution

Remove `cleaner.Cleanup` calls in favour of `cluster.Cleanup` in all E2E tests (`test/e2e/`) that create their own cluster.

### Additional information

Ticket is a result of discussion: https://github.com/Kong/kubernetes-ingress-controller/pull/3013#discussion_r986589068

### Acceptance Criteria

- [ ] Every test case in `test/e2e/` that always creates its own cluster, calls `cluster.Cleanup` instead of `cleaner.Cleanup` on its teardown.
- [ ] Diagnostics generated by the `cleaner` are still being dumped for every test case

**Comment by rainest** [comment]
These are, I think, mostly just copied boilerplate from the integration tests. Normally part of the cleaner's job is to hold onto resources until the failure diagnostics complete. We used to write API client Delete calls in defers for created resources, but those would execute before the earlier defer to collect diagnostics.

E2E wasn't bothering to clean anything at all and still isn't--we're not calling cleaner.Add so the Cleanup call is basically a no-op.

Change shouldn't interfere with diagnostics though, so long as it's still run after them.

**Comment by czeslavo** [comment]
> Change shouldn't interfere with diagnostics though, so long as it's still run after them.
Good point, I extended ACs to not lose that.

**Comment by czeslavo** [comment]
It's been fixed by https://github.com/Kong/kubernetes-ingress-controller/pull/3431.
