### ISSUE TITLE
GEP-957: Gateway port matching for L7 Gateway API Routes

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3016]
https://github.com/Kong/kubernetes-ingress-controller/issues/2709 originally covered the implementation of GEP-957 (Gateway routes can match inbound requests based on their destination port) for both L4 and L7/HTTP routes. This issue was split out for HTTP routes only.

Acceptance:

- [x] Test if Kong supports port routing on HTTP routes via the `destination` field.

One of the following:
- [ ] ~If Kong HTTP routes support port matching via the `destination` field, populate it.~ @rainest says that Kong does not support this.
- [ ] If Kong HTTP routes do not support this, cover the limitation in documentation and confer with the team/product to determine whether we want to add support.

**Comment by rainest** [comment]
Initial analysis is that this doesn't work. The field is not allowed, at least not with the traditional router configuration. No idea whether the expression router would allow it:

```
	while processing event: {Update} route 19084e67-0075-4eb7-a830-d8f5a34219b2 failed: HTTP status 400 (message: "schema violation (destinations: cannot set 'destinations' when 'protocols' is 'http' or 'https')")
```

So the next steps are to note lack of support for ports in HTTPRoute and then decide whether we're okay just leaving that as-is or if we want to push the gateway to add support for destinations/port configurations for HTTP routes.

**Comment by jrsmroz** [comment]
The expression router does have `net.port - Server end port number`
See the [available-fields](https://docs.konghq.com/gateway/latest/reference/router-expressions-language/#available-fields)

But if we go with expression router, doesn't that mean we need to rewrite how we generate routes? As stated in the [docs](https://docs.konghq.com/gateway/3.0.x/key-concepts/routes/expressions/#create-routes-with-expressions):

> Edit [kong.conf](https://docs.konghq.com/gateway/latest/production/kong-conf) to contain the line router_flavor = expressions and restart Kong Gateway. Note: once you enable expressions, the match fields that traditionally exist on the Route object (such as paths, methods) will no longer be configurable and you must specify Expressions in the expression field.

That would be a major rewrite.
>

**Comment by rainest** [comment]
Yeah, expressions does work for this:

```
14:13:31-0700 esenin $ curl -s localhost:8001/routes/d627f277-5129-407d-9346-017909cc0895 | jq .expression
"http.path == \"/mock\""

14:14:41-0700 esenin $ curl -sv localhost:8000/mock -H "kong-debug: 1" 2>&1 | grep -E "Route-Id|< HTTP"    
< HTTP/1.1 522 
< Kong-Route-Id: d627f277-5129-407d-9346-017909cc0895

14:15:28-0700 esenin $ curl -s localhost:8001/routes/d627f277-5129-407d-9346-017909cc0895 | jq .expression
"http.path == \"/mock\" && net.port == 9999"

14:17:02-0700 esenin $ curl -sv localhost:8000/mock -H "kong-debug: 1" 2>&1 | grep -E "Route-Id|< HTTP"    
< HTTP/1.1 404 Not Found

14:17:06-0700 esenin $ curl -sv localhost:9999/mock -H "kong-debug: 1" 2>&1 | grep -E "Route-Id|< HTTP" 
< HTTP/1.1 522 
< Kong-Route-Id: d627f277-5129-407d-9346-017909cc0895
```

**Comment by mflendrich** [comment]
Superseded by #3314 and #3315.
