### ISSUE TITLE
Each non-Upstream KongIngress field has an equivalent annotation

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3017]
To complete, all fields available in KongIngress must have an annotation that provides equivalent functionality, or have been broken out into separate issues explaining how they will be handled otherwise. Fields currently missing annotations are listed below.

**Service**

- [ ] connect_timeout
- [ ] write_timeout
- [ ] read_timeout
- [ ] retries

**Route**

- [ ] headers
- [ ] path_handling

Of these, `route.headers` is the only one expected to be difficult:

> Find a way for Ingresses to support an annotation for headers (this looks like the only KongIngress-only route field). This may be annoying to deal with. `konghq.com/headers: foo:a,b,c;bar:x,y,z` would kinda work but would be clunky as hell and break semicolons (commas are fine to break, they're already a designated special separation character). Can we use an annotation prefix, like `konghq.com/header/foo: a,b,c` and `konghq.com/header/bar: x,y,z`?

**Comment by rainest** [comment]
https://github.com/Kong/kubernetes-ingress-controller/pull/3121 will handle all the Service annotations.
