### ISSUE TITLE
Ensure that CRD docs are up to date with actual CRDs

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Ensure that for each CRD in [KIC CRD reference](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/custom-resources/#kongingress), there is no drift between the docs and the CustomResourceDefinition

### Proposed Solution

Do the diff and fix discrepancies

### Acceptance Criteria

- [x] No drift between CRD docs and CustomResourceDefinitions in KIC

**Comment by rainest** [comment]
Gateway API's docs do this well and seem to have it automated somehow. https://github.com/kubernetes-sigs/gateway-api/blob/6d1eb375fd46227fdf68d4196ad8b7596ee27986/apis/v1beta1/gateway_types.go#L68-L114 matches the text at https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.Gateway

They're using https://www.mkdocs.org/ to create the dev site, but it doesn't look like that definitely provides the generated content from Go types; it may rely on some helper or plugin.

**Comment by czeslavo** [comment]
Gateway API uses https://github.com/ahmetb/gen-crd-api-reference-docs to generate docs, seems like it's quite popular among other projects as well. I'll give it a try.

**Comment by rainest** [comment]
Completed by https://github.com/Kong/docs.konghq.com/pull/4813
