### ISSUE TITLE
Find out gaps between Kong 3.0 features and KIC expressions 

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Kong 3.0 release included several improvements and new features, especially the new DSL based router. We need to investigate on what features are available in Kong, but could not be expressed using KIC. These gaps will force users who want to use the features to call Kong admin API directly, instead of using KIC.

### Proposed Solution

- find out what features in Kong 3.0 could not be expressed using KIC CRDs (`KongIngress`, `KongPlugin`,...)
- find out how to use expression based router to translate path matches in resources having path match, e.g: `Ingress`, `HTTRRoute`

### Acceptance Criteria

- [ ] We have a document to record what features in Kong 3.0 are not supported in KIC, and brief proposals to implement them
- [ ] We have method to translate path matches in k8s resources(`Ingress`,`HTTPRoute`,...) to expressions of Kong 3.0 router

**Comment by mflendrich** [comment]
replaced by https://github.com/Kong/kubernetes-ingress-controller/issues/3730
