### ISSUE TITLE
ParentRef group and kind not checked for Routes

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#3075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Whenever the respective controller reconciles a route, the function `getSupportedGatewayForRoute` is called to retrieve all the Gateways referenced by the Route, which have at least one listener that matches the Route requisites.
The function `getSupportedGatewayForRoute` iterates over all the Gateway referenced by the Route, checking neither the group nor the kind of the ParentRef. Since `Gateway` is the default kind to be used by the routes as ParentRef, but the user can customize it, such fields should be checked to ensure that the referenced parent is a `Gateway`.

### Proposed Solution

* if the route references an object different from a Gateway as a parent, we should return an error, as no other kinds are currently supported as parent references.

### Acceptance Criteria

- [ ] if the route references an object different from a Gateway as parent, the reconcile must throw an error
- [ ] a test case is added to ensure the above condition

**Comment by mflendrich** [comment]
@mlavacca says that GWAPI conformance tests in v0.6.0 require that KIC rejects routes with an invalid ParentRef.

This makes this issue a blocker for bumping GWAPI to 0.6.
