### ISSUE TITLE
Deprecated GetSchema kong-go's function is used

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

`PluginSchemaStore` [uses the `GetSchema`](https://github.com/Kong/kubernetes-ingress-controller/blob/e86bd68101359db503ded73fceeeca82d5b58eb5/internal/util/plugin_schema_helper.go#L41) method of `kong-go`'s client while it is marked as deprecated. We should not use the deprecated method and migrate to the suggested `GetFullSchema`. 

### Proposed Solution

- Change the `PluginSchemaStore` to use `kong-go`'s `GetFullSchema` method instead of `GetSchema` 
- Identify what is the difference between both and ensure that no functionality gets broken due to the change (existing integration tests should be sufficient to detect any potential regression)

### Acceptance Criteria

- [ ] KIC doesn't call the deprecated  `go-kong`'s `GetSchema` method.

**Comment by randmonkey** [comment]
The return value of the two APIs has slight differents:
`GetSchema` calls `GET /plugins/schema/*`, and `GetFullSchema` calls `GET /schemas/plugins/*`. The response from the two APIs are not the same. From practice, I can see configuration schema of plugin is in `fields` field of  `GET /plugins/schema/*`, but `fields.config` in `GET /schemas/plugins/*`. However, I did not see documents of the details of the two APIs, so I am not sure   if we could just do this simple replace.
