### ISSUE TITLE
Add support for `ingress.kubernetes.io/force-ssl-redirect` annotation

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#309]
This should set `HTTPSRedirectStatusCode` to 308 (configurable via KongIngress CR).

**Comment by BiggA94** [comment]
Kong 1.2 supports `https_redirect_status_code` now.
I think, using a KongIngress with `https_redirect_status_code` should be the way to go for now.
Kong-Ingress should support this as well, in order to be 1.2 compliant, currently it does not.

**Comment by ismailbaskin** [comment]
Although I agree with what @BiggA94 said, I think Ahmet aims to be compatible with ingress-nginx with this annotation.

**Comment by BiggA94** [comment]
Okay, I missunderstood it I think, sorry. I read it like doing it only this way.
The best would be, to support both methods.

As of being Kong 1.2 Compliant, should I open another ticket for the `https_redirect_status_code` problem?

**Comment by hbagdi** [comment]
@BiggA94 Yes please. Also, we welcome contributions!

All you would need is to add that field as a property in here under the route section: https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/manifests/custom-types.yaml

Feel free to PR it!
