### ISSUE TITLE
Add parser tests for gateway API L4 routes

### ISSUE THREAD

**Issue by jrsmroz** [Kong/kubernetes-ingress-controller#3092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Currently parser package does not provide any tests for `UDPRoute`,  `TCPRoute` and `TLSRoute`
Those are in alpha right now, so it's understandable it was not the top priority.

### Proposed Solution

Implement parser tests for `UDPRoute`,  `TCPRoute` and `TLSRoute`

### Acceptance Criteria

- [ ] `UDPRoute` translation into kong config is tested in dataplane parser package
- [ ] `TCPRoute` translation into kong config is tested in dataplane parser package
- [ ] `TLSRoute` translation into kong config is tested in dataplane parser package

**Comment by programmer04** [comment]
It can be now easily covered with introducing of test cases and expected results in `internal/dataplane/parser/testdata/golden` - golden tests approach
