### ISSUE TITLE
Service is not use KongIngress by default

### ISSUE THREAD

**Issue by subicura** [Kong/kubernetes-ingress-controller#310]
### Summary

Before 0.4.0, Service use KongIngress proxy config by default, but in 0.4.0 Service should use "configuration.konghq.com" annotation.

**Kong Ingress controller version**

0.4.0

**Kong or Kong Enterprise version**

### Kubernetes version

**paste `kubectl version` output**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened

Service don't use KongIngress proxy config by default.

### Expected behvaior

Service use KongIngress proxy config by default, if service has no "configuration.konghq.com" annotation.

### Steps To Reproduce

1. Create Ingress
2. Create KongIngress proxy config
3. Create Service without annotation. (all same name)
4. Check KongIngress proxy option for service.

**Comment by subicura** [comment]
Is it a bug or right action?

**Comment by hbagdi** [comment]
Could you elaborate on what you mean by the following?

> Service use KongIngress proxy config by default


With 0.4.0, to change configs of a service in Kong, there exists only one method, put the `configuration.konghq.com` annotation on that service.

**Comment by subicura** [comment]
Hi! Before 0.4.0, service uses same name kongingress(proxy, route, ..) automatically. But in 0.4.0, service don't use kongingress(proxy) automatically. Route config is ok, but proxy config is not.
automatically means no annotation.

**Comment by hbagdi** [comment]
As noted in the breaking changes section of 0.4.0 release in the [changelog](https://github.com/Kong/kubernetes-ingress-controller/blob/master/CHANGELOG.md#040---20190424), this is expected.

Please add the annotation to the service resource in k8s to override properties of services and upstreams in Kong.
