### ISSUE TITLE
redhat-certification-test from nightly job fails 

### ISSUE THREAD

**Issue by jrsmroz** [Kong/kubernetes-ingress-controller#3118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

redhat-certification-test from nightly job fails.

The local image cache is no longer used. It may be change in `quay.io/opdev/preflight:stable`. We can no longer run checks on images that are not published.

https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3358462686/jobs/5565485610

### Expected Behavior

Pipeline should be able to run redhat image checks nightly sucessfully.

**Comment by programmer04** [comment]
Obsolete, surpassed by 
- https://github.com/Kong/kubernetes-ingress-controller/issues/3689
