### ISSUE TITLE
Gateway listeners `ListenerStatus.AttachedRoutes` not updated on route attachment

### ISSUE THREAD

**Issue by jrsmroz** [Kong/kubernetes-ingress-controller#3120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a HTTPRoute is attached to the gateway, the `Gateway.Status.Listeners[].AttachedRoutes` is not updated. it's always zero:

https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/controllers/gateway/gateway_utils.go#L210-L234
https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/controllers/gateway/gateway_utils.go#L291

Checking the code show there are no other places where we set AttachedRoutes.

This makes the conformance test to fail, or to be flaky. https://github.com/Kong/kubernetes-ingress-controller/issues/2939

### Expected Behavior

`Gateway.Listeners[].AttachedRoutes` should be updated.

### Steps To Reproduce

```markdown
1. Deploy KIC.
2. Create Gateway
3. Attach a HTTPRoute to a gateway.
4. Wait for HTTPRoute to be ready.
5. Checks the status of gateway, `Gateway.Status.Listemers[].AttachedRoutes`
```

### Kong Ingress Controller version

```shell
v2.7.0
```

**Comment by pmalek** [comment]
After a cursory look through the codebase, it seems to be that we're not performing any sort of "route matching", i.e. we don't go through routes specifications in order to attach routes to matching gateway's listeners.

I believe that should be done first (before this issue here is resolved) but I might be proven incorrect.

**Comment by mlavacca** [comment]
Moving this to the 2.10 milestone, as this condition will be checked by the conformance test when the new Gateway API release is out.

**Comment by mflendrich** [comment]
@mlavacca are you referring to the 0.6.2 release of Gateway API?

If so - we can label it as "blocked" on https://github.com/kubernetes-sigs/gateway-api/pull/1814.

**Comment by mlavacca** [comment]
> @mlavacca are you referring to the 0.6.2 release of Gateway API?

Yes, It was blocked by 0.6.2. We can unblock it now
