### ISSUE TITLE
Plugin: rate-limiting-advanced doesnt require config.namespace in UI but does through KIC

### ISSUE THREAD

**Issue by ryan-dyer-sp** [Kong/kubernetes-ingress-controller#3128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a rate-limiting-advanced plugin via UI, the config.namespace is not a required value and ends up creating a random hash value (default value).  However in KIC the same behavior does not occur and the schema validation is requiring namespace be present. 

### Expected Behavior

Can create rate-limiting-advanced plugin via KIC without needing to specify namespace and a random hash is created for it.

### Steps To Reproduce

```markdown
Create rate-limiting-advanced plugin without config.namespace
```

### Kong Ingress Controller version

```shell
2.7
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:46:22Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by programmer04** [comment]
**Reproduced for DB mode** with KIC 3.0 and Kong Gateway Enterprise 3.4. **For DB-less there is no problem**.

**Route cause**
KIC under the hood uses [deck](https://github.com/Kong/deck) that uses [go-kong](https://github.com/Kong/go-kong), a request made to the Kong Gateway under the hood looks like that
```json
PUT http://<ADMIN-API>/plugins/8908ed44-a942-4652-85e4-1c35d3962a42

{
  "config": {
    "consumer_groups": null,
    "dictionary_name": "kong_rate_limiting_counters",
    "disable_penalty": false,
    "enforce_consumer_groups": false,
    "error_code": 429,
    "error_message": "API rate limit exceeded",
    "header_name": null,
    "hide_client_headers": false,
    "identifier": "consumer",
    "limit": [
      2
    ],
    "namespace": null,
    "path": null,
    "redis": {
      "cluster_addresses": null,
      "connect_timeout": null,
      "database": 0,
      "host": null,
      "keepalive_backlog": null,
      "keepalive_pool_size": 30,
      "password": null,
      "port": null,
      "read_timeout": null,
      "send_timeout": null,
      "sentinel_addresses": null,
      "sentinel_master": null,
      "sentinel_password": null,
      "sentinel_role": null,
      "sentinel_username": null,
      "server_name": null,
      "ssl": false,
      "ssl_verify": false,
      "timeout": 2000,
      "username": null
    },
    "retry_after_jitter_max": 0,
    "strategy": "local",
    "sync_rate": null,
    "window_size": [
      100
    ],
    "window_type": "sliding"
  },
  "enabled": true,
  "id": "8908ed44-a942-4652-85e4-1c35d3962a42",
  "name": "rate-limiting-advanced",
  "protocols": [
    "grpc",
    "grpcs",
    "http",
    "https"
  ]
}
```

equivalent deck file (that results in the above request)
```yml
_format_version: "3.0"
plugins:
  - config:
      limit:
        - 2
      window_size:
        - 100
    name: rate-limiting-advanced
```

*response with validation error*
```json
{
  "fields": {
    "config": {
      "namespace": "required field missing"
    }
  },
  "code": 2,
  "name": "schema violation",
  "message": "schema violation (config.namespace: required field missing)"
}
```

the problem is that in the body field `config.namespace: null` is explicitly specified in the request payload, when it is omitted everything works. See the below that works

```sh
curl -X PUT -H 'Kong-Admin-Token:password' -H 'Content-Type:application/json' 172.18.128.1:8001/plugins/8908ed44-a942-4652-85e4-1c35d3962a42 -d '{"name": "rate-limiting-advanced", "config":{"limit": [2], "window_size": [100]}}'
```

returns a response for successfully created plugin. But when the field `config.namespace: null` is speciefied

```sh
curl -X PUT -H 'Kong-Admin-Token:password' -H 'Content-Type:application/json' 172.18.128.1:8001/plugins/8908ed44-a942-4652-85e4-1c35d3962a42 -d '{"name": "rate-limiting-advanced", "config":{"limit": [2], "window_size": [100], "namespace": null}}' 
```

the same error is returned as mentioned in *response with validation error*.

**Comment by programmer04** [comment]
Blocked by [FTI-5568](https://konghq.atlassian.net/browse/FTI-5568) - problem with Kong Gateway

**Comment by programmer04** [comment]
Discussed with Kong Gateway team. It is expected to require the field `config.namespace` in the declarative flow of configuration. KIC uses that mechanism under the hood, thus it behaves as expected. Configuring a plugin via the UI is not equivalent to dealing with declarative configuration.
