### ISSUE TITLE
How to define route's name

### ISSUE THREAD

**Issue by WywTed** [Kong/kubernetes-ingress-controller#315]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.3.0

**Kong or Kong Enterprise version**
kong 1.0

### Kubernetes version
~~~
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"8920c466b3112b7debc96d4475c5495bdc87a971", GitTreeState:"clean", BuildDate:"2019-02-21T05:45:18Z", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
~~~

### Environment

- **Kernel** (e.g. `uname -a`): Linux k8s-master-1 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubectl
- **Others**:

### What happened
* There is no place to define route's name in kongingress. If i want to use route's name, how can i do?
* Data in db are generated by kong resource such as kongingress and ingress. For route record in db, how can i find the ingress by a route record or how can i find route record by an ingress? 
* in this [PR: expose metrics per service/route](https://github.com/Kong/kong-plugin-prometheus/pull/48), it may use route's name.

**Comment by hbagdi** [comment]
You can't define a route's name. It will be auto-generated by the Ingress Controller.

**Comment by rb-leadr** [comment]
This is problematic when it comes to metrics - all I see in my metrics are things like this. We create the route using a k8s ingress, and the service using a k8s service.

our backend backend service is "monolith" and ingress is named "api-gateway"...

"route:api-gateway.monolith.04" or "route:api-gateway.monolith.05" - in metrics. Is there a way to get better route names without creating an ingress for every single route?

That seems painful.
