### ISSUE TITLE
watchNamespaces ClusterRoles Error

### ISSUE THREAD

**Issue by deckong** [Kong/kubernetes-ingress-controller#3158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when using the watchNamespaces attribute and providing a namespace to that list, for example we will use "roles".:

`watchNamespaces:
    - roles`

If you deploy pods to that namespace, you will be met with errors regarding cluster roles permissions not being sufficient to access some entities:

`time="2022-11-10T18:43:27Z" level=error msg="failed to list services in cluster" error="services is forbidden: User \"system:serviceaccount:roles:roles-kong\" cannot list resource \"services\" in API group \"\" at the cluster scope" logger=reporter.mesh`

These errors will persist every hour thereafter. 
KIC v2.7.0
helm v3.9.4
chart v2.13.1
k8 v1.24.4

### Expected Behavior

The expectation here is errors like this one should NOT be happening. Roles should be properly permitted and defined in clusterroles.

### Steps To Reproduce

```markdown
1. Basic helm deployment using our kong values.yaml
2. Make sure the watchNamespaces attribute is enabled and a namespace is placed like shown above. 
3. Make sure that deployed-to namespace matches what is placed in the values.yaml
4. Check kong-pod logs, if you do not see the error, you may need to watch 60 mins for its reproduction.
```

### Kong Ingress Controller version

```shell
v2.7.0
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

### Anything else?

Client errors a little more in-depth including errors for the services, endpoints, and pods errors of forbidden.

**Comment by randmonkey** [comment]
What was your `values.yaml` and what is the difference between it and our default values? Is there any differences in RBAC configs? If the service account for running KIC pod does not have A `ClusterRole` with permission to list services binded, it cannot list namespaces.

**Comment by dascole** [comment]
Hi @randmonkey 

I can reproduce this with only changing ingressController.watchNamespaces

`helm upgrade -i $(hostname) kong/kong -n kongfused --set ingressController.watchNamespaces={"kongfused,kong"}`


Upon startup (and repeated hourly)
`time="2022-11-11T13:21:02Z" level=error msg="failed to list services in cluster" error="services is forbidden: User \"system:serviceaccount:kongfused:daznix-kong\" cannot list resource \"services\" in API group \"\" at the cluster scope" logger=reporter.mesh
`

The **ClusterRole** does not have permissions for services, which I believe is expected when we use watchNamespaces. A **role** is created for each namespace we explicitly define and it does have the appropriate permissions. 

I am not clear on why is this permission required at the cluster scope though.

**Comment by randmonkey** [comment]
> 

This is the mesh detection part in the per-hour telemetry. Here we wanted to check out that how many services are running under a specific service mesh, so KIC will list all services and pods (which is allowed by default RBAC settings) to check whether they are running under a mesh. 

This will not affect configurations of ingresses. The only affections are error logs and missing messages about service meshes in the telemetry messages reported to splunk.

To resolve this error, I have came up with this solution:
mesh detector only check for services and pods in namespaces in `watchNamespaces`
