### ISSUE TITLE
Optimize SecretNameToSNIs.addHosts for performance

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Currently, `SecretNameToSNIs` stores hosts in a slice. It is not the optimal way to store it, because when the new host is added, we need to [build an ad-hoc map](https://github.com/Kong/kubernetes-ingress-controller/blob/c9b3bb4ed985b80096f287ca887df52cc161999b/internal/dataplane/parser/ingressrules.go#L135) to filter hosts that are duplicates. [It was proven](https://github.com/Kong/kubernetes-ingress-controller/pull/3150#discussion_r1018630675) that in the case of a bigger set of hosts, it degrades the performance significantly.

### Proposed Solution

Rewrite `SecretNameToSNIs.filterHosts` so that it uses a map for hosts storage instead of a slice.

### Additional information

Keep in mind that the hosts map has to make sure that hosts are globally unique, not only on the level of the secret. 

### Acceptance Criteria

- [ ] SNI hosts are stored in a map when building `SecretNameToSNIs`
- [ ] When merging multiple `SecretNameToSNIs`, duplicates are discarded

**Comment by randmonkey** [comment]
Changed to priority/medium because we will merge `SecretNameToSNIs` into one in #3150.
