### ISSUE TITLE
For Gateway API docs, specify KIC version - GWAPI version feature relationships

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As a user of KIC I don't know whether the version I'm using supports some Gateway API feature (or if it was added in a later version of KIC).

Diffing docs pages for two different KIC versions is a workaround, but it's tedious and @rainest @czeslavo agree that this is bad UX.

### Proposed Solution

[This page](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/gateway-api-support/) to include a mapping saying "KIC version X supports GWAPI feature Y"

### Acceptance Criteria

- [ ] The mapping between KIC versions and GWAPI features is present on [this docs page](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/gateway-api-support/)

**Comment by czeslavo** [comment]
As https://github.com/Kong/docs.konghq.com/pull/4869 is merged, I think we may close it as done.
