### ISSUE TITLE
Policy attachment for Upstreams that will supersede KongIngress.spec.upstreams

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We're deprecating KongIngress #2505 #2941.

Some of KongIngress fields can be migrated into annotations, some (that configure upstream behavior) require their own CRD.

Gateway API defines a framework for such CRDs called policy attachments ([docs](https://gateway-api.sigs.k8s.io/references/policy-attachment/ )).

### Proposed Solution

Define a policy attachment CRD (`KongUpstreamPolicy`) that will configure Upstreams in a way `KongIngress` does today.

```[tasklist]
- [x] Define `KongUpstreamPolicy` CRD API
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/4929
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/4951
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/4930
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/4931
- [x] Add changelog entry describing KongUpstreamPolicy addition
- [x] Write a new guide that will replace `Using KongIngress resource`
- [x] Update `Configuring healthchecks` guide to use `KongUpstreamPolicy`
```

### Acceptance Criteria

- [ ] Policy attachments configure upstreams on par with KongIngress for Gateway API routes.
- [ ] Policy attachments configure upstreams on par with KongIngress for Ingress types.
- [ ] https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-kongingress-resource/ is replaced with a guide that discusses the new resource.
- [ ] https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/configuring-health-checks/ is updated to use the new resource. It should also cover GWAPI usage, though shouldn't need to do more than include the [standard test route boilerplate](https://github.com/Kong/docs.konghq.com/blob/2342cddbfa8a3729bfe1515140d1474106c87f79/app/_src/kic-v2/guides/getting-started.md#L11-L17). Upstreams apply to service configuration, and use the same Service resource for both GWAPI and Ingress.

**Comment by czeslavo** [comment]
As a result of the discussion under https://github.com/Kong/kubernetes-ingress-controller/pull/4880 we concluded `KongUpstreamPolicy` will not strictly follow [GEP-713](https://gateway-api.sigs.k8s.io/geps/gep-713). It will differ in terms of the way the attachment is defined - instead of using `TargetRef` (that allows only 1-1 attachment), we'll use annotations (`konghq.com/upstream-policy: <name>`).

**Comment by czeslavo** [comment]
Updated `Configuring healthchecks` guide: https://github.com/Kong/docs.konghq.com/pull/6309.

**Comment by czeslavo** [comment]
Replacement for `Using KongIngress resource` guide: https://github.com/Kong/docs.konghq.com/pull/6407
