### ISSUE TITLE
container has runAsNonRoot and image will run as root

### ISSUE THREAD

**Issue by RobinsChens** [Kong/kubernetes-ingress-controller#318]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**

**Kong or Kong Enterprise version**

### Kubernetes version

**paste `kubectl version` output**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### Steps To Reproduce

1.
2.
3.
4.

**Comment by hbagdi** [comment]
Please open an issue with details and enough information for us to understand the issue that you are facing. Thank you.
