### ISSUE TITLE
How to use seperately PostgreSQL databases?

### ISSUE THREAD

**Issue by Zhang21** [Kong/kubernetes-ingress-controller#319]
This isn't an issue!

<br>

For security and persistent of data, I want to use seperately PostgreSQL database（like aws rds PostgreSQL） without `kong-k8s-ingress-controller` default  PostgreSQL in k8s/docker which created by YAML file.

I try to delete sections about PostgreSQL in YAML file，and edit PostgreSQL configuration options（like: `KONG_PG_HOST`, `KONG_PG_USERNAME`...）

<br>

thanks!

**Comment by hbagdi** [comment]
Did it work for you?

If yes, could you close the issue?

If not, please let us know how we can help here. Thanks!

**Comment by hbagdi** [comment]
Closing this issue due to lack of response.
@Zhang21 Please feel free to re-open if your issue is not resolved.
