### ISSUE TITLE
Release KIC v2.8.0

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3199]
### Release Type

minor release

### **For all releases** Github Workflow Test Matrix Checkup

- [x] check the testing workflow ([.github/workflows/test.yaml](/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/test.yaml)) and ensure that all matrix versions ([.github/workflows/e2e.yaml](/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/e2e.yaml) and [.github/workflows/release.yaml](/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/release.yaml))  are up to date for various component releases. If there have been any new releases (major, minor or patch) of those components since the latest version seen in that configuration make sure the new versions get added before proceeding with the release. Remove any versions that are no longer supported by the environment provider.
- [x] Kubernetes (via [KIND](https://hub.docker.com/r/kindest/node/tags) and the latest image available when creating a new rapid channel cluster from the GKE new cluster wizard)
- [x] Istio (via [Istio's releases page](https://github.com/istio/istio/releases))

https://github.com/Kong/kubernetes-ingress-controller/pull/3277

### **For all releases** Create Release Branch

- [x] ensure that you have up to date copy of `main`: git checkout main; git pull
- [x] create the release branch for the version (e.g. `release/1.3.1`): `git branch -m release/x.y.z`
- [x] Make any final adjustments to CHANGELOG.md. Double-check that dates are correct, that link anchors point to the correct header, and that you've included a link to the Github compare link at the end.
- [x] retrieve the latest license report from FOSSA and save it to LICENSES
- [x] ensure base manifest versions use the new version (`config/image/enterprise/kustomization.yaml` and `config/image/oss/kustomization.yaml`) and update manifest files: `make manifests`
- [x] push the branch up to the remote: `git push --set-upstream origin release/x.y.z`

### **For all releases** Create a Release Pull Request

- [x] Check the [latest test run](https://github.com/Kong/kubernetes-ingress-controller/actions/workflows/e2e.yaml) to confirm that E2E tests are succeeding. If you are backporting features into a non-main branch, run a [targeted E2E job against that branch](https://github.com/Kong/kubernetes-ingress-controller/actions/workflows/e2e_targeted.yaml).
  Run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3732348684
- [x] Open a PR from your branch to `main`.
- [x] Once the PR is merged, [initiate a release job](https://github.com/Kong/kubernetes-ingress-controller/actions/workflows/release.yaml). Your tag must use `vX.Y.Z` format. Set `latest` to true if this will be the latest release.
  Run 1: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3732472974
  Last run: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/3734142793
- [x] CI will validate the requested version, build and push an image, and run tests against the image before finally creating a tag and publishing a release. If tests fail, CI will push the image but not the tag or release. Investigate the failure, correct it as needed, and start a new release job.

### **For all releases** Publish images to Red Hat Catalog

- [x] Verify the image was pushed by a pipeline to the [KIC project in Red Hat partners portal](https://connect.redhat.com/projects/5eab1b8ea165648bd1353266/images) to confirm that E2E tests are succeeding. If you are backporting features into a non-main branch, run a [targeted E2E job against that branch](https://github.com/Kong/kubernetes-ingress-controller/actions/workflows/e2e_targeted.yaml).
- [x] Click publish button for all tags related to the release that were pushed to the portal. That will publish the image to Red Hat Catalog.
- [ ] Make sure the latest tag was added when asked. If forgot, the tag can be added from the dropdown menu.
  We weren't able to make the `latest` tag appear in the RH catalog even though it was successfully being pushed to the registry. @czeslavo opened a support ticket in RH to resolve this issue. 

### **For all releases** Synchronize documentation with docs.konghq.com

- [x] Trigger [synchronize_docs](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/synchronize_docs.yaml) workflow.
- [x] Ensure the PR is created in [docs.konghq.com](https://github.com/Kong/docs.konghq.com/pulls) repository.
- [x] Review and approve the PR if everything looks correct.

### **For major/minor releases only** Update Release documents

- [x] Create a new branch in the [documentation site repo](https://github.com/Kong/docs.konghq.com).
- [x] Update articles in the new version as needed.
- [x] Update `references/version-compatibility.md` to include the new versions (make sure you capture any new Kubernetes/Istio versions that have been tested)
  PR: https://github.com/Kong/docs.konghq.com/pull/4944
- [x] Copy `app/_data/docs_nav_kic_OLDVERSION.yml` to `app/_data/docs_nav_kic_NEWVERSION.yml` and update the `release` field to `NEWVERSION`. Add entries for any new articles.
- [x] Add a section to `app/_data/kong_versions.yml` for your version.
- [x] Open a PR from your branch.
  PR: https://github.com/Kong/docs.konghq.com/pull/4932
- [x] Inform and ping the @team-k8s via slack of impending release with a link to the release PR.

### Release Troubleshooting

The [Release Troubleshooting guide](https://github.com/Kong/kubernetes-ingress-controller/blob/main/RELEASE.md#release-troubleshooting) covers strategies for dealing with a release that has failed.

### Manual Docker image build

If the "Build and push development images" Github action is not appropriate for your release, or is not operating properly, you can build and push Docker images manually

### Steps

- [ ] Check out your release tag.
- [ ] Run `make container`. Note that you can set the `TAG` environment variable if you need to override the current tag in Makefile.
- [ ] Add additional tags for your container (e.g. `docker tag kong/kubernetes-ingress-controller:1.2.0-alpine kong/kubernetes-ingress-controller:1.2.0; docker tag kong/kubernetes-ingress-controller:1.2.0-alpine kong/kubernetes-ingress-controller:1.2`)
- [ ] Create a temporary token for the `kongbot` user (see 1Password) and log in using it.
- [ ] Push each of your tags (e.g. `docker push kong/kubernetes-ingress-controller:1.2.0-alpine`)

**Comment by czeslavo** [comment]
As the release is done, I'm closing this issue. Further actions that can be taken as follow-ups to the release will be tracked under https://github.com/Kong/team-k8s/issues/267.
