### ISSUE TITLE
Issue in yaml for all-in-one postgres deployment.

### ISSUE THREAD

**Issue by nico-kuzak** [Kong/kubernetes-ingress-controller#320]
When I tried to deploy Kong Ingress Controller on an AKS cluster, based on the steps here:

https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/aks.md

it failed. I looked into the actual yaml specifications here:

https://bit.ly/kong-ingress

and the problem is that at the end of creating the kong-proxy service, the 3 dividing hyphens (---) are in the wrong line (they should be in their own) and thus this service isn't created.

### Kubernetes version 
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-dispatcher", GitCommit:"1215389331387f57594b42c5dd024a2fe27334f8", GitTreeState:"clean", BuildDate:"2019-05-13T18:18:50Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.12", GitCommit:"c757b93cf034d49af3a3b8ecee3b9639a7a11df7", GitTreeState:"clean", BuildDate:"2018-12-19T11:04:29Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- AKS
- Ubuntu 16.04

### What happened

Kong was not created

### Expected behavior
Kong ingress controller was expected to be deployed

### Steps To Reproduce

1. curl -sL https://bit.ly/kong-ingress | kubectl create -f -

**Comment by hbagdi** [comment]
Apologies for the silly mistake here.
Fixed with cf5198ac26c83e57b33ca24a49c774d45032f361.
