### ISSUE TITLE
Add functionality in the `dataplane.KongClient` (or similar struct with a superset of `KongClient`'s functionality) to provide multiple Admin API endpoints and update each in `c.Update()`

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#3209]
### Problem Statement

In order to allow multiple DataPlanes deployment or horizontal scaling we need introduce a mechanism to send config to multiple Gateways at a time.

### Proposed Solution

- Extend [`dataplane.KongClient`](https://github.com/Kong/kubernetes-ingress-controller/blob/bf5fb880ef68a1644da854791b5eae8c98b907a2/internal/dataplane/kong_client.go#L39) and/or [`dataplane.Synchronizer`](https://github.com/Kong/kubernetes-ingress-controller/blob/0243a95453a266c712a006a03fd0c763e4181ebb/internal/dataplane/synchronizer.go#L35-L50) in a way that allows pushing configuration to multiple endpoints (Admin APIs) at the same time.
- Allow changing the set of endpoints (adding them and removing them) without service disruption or restarts

### Acceptance Criteria

- [x] KIC accepts many different Kong endpoints as command-line arg/env var
  - This has been achieved in #3268
- [x] KIC can send config to multiple Gateways at the same time (concurrently)
  - Same: done in #3268
- ~Modifications mentioned in this issue have to allow adding and removing endpoints during synchronization loop runtime with disruption~
  - This is being tracked in #3400 to enable dynamic configuration of Admin API endpoints through service discovery.

**Comment by mlavacca** [comment]
I'd add here an AC stating something like:

- [ ] KIC accepts many different Kong endpoints as command-line arg/env var

@pmalek does it make sense to you?

**Comment by pmalek** [comment]
This is considered done. Service discovery aspect of this is tracked in #3400
