### ISSUE TITLE
Convert Gateway supported features doc to changelog style

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#3215]
https://docs.konghq.com/kubernetes-ingress-controller/latest/references/gateway-api-support/ covers supported features for the Gateway APIs in KIC. Because the Gateway APIs spec is rapidly evolving and KIC's implementation is incomplete, KIC versions differ considerably in the level of functionality they support.

This document currently presents a set of supported features for the version viewed: if version 2.6 has support for TCPRoute and version 2.5 does not, the version 2.6 page will list TCPRoute support and the 2.5 page will not.

This format has issues presenting information to users. If you're reviewing an older doc version, it's not clear what features may be available in newer versions, and if you're reviewing a newer version, it's not clear what minimum version is required to use a feature. You can only determine what was added when by reviewing multiple pages.

To remedy this, the page should instead read more like a changelog: all versions will show the same content, but that content will indicate when features were added in chronological order. Unlike the regular changelog, this document will list Gateway APIs information only, grouped by resource (an HTTPRoute section lists HTTPRoute features added in 2.5, 2.6, 2.7, etc.).

- [ ] The Gateway API feature support reference displays the same content for all versions.
- [ ] The reference has a section for each supported resource.
- [ ] The supported resource sections have version subsections. The version subsections list features added in that version.
- [ ] The resource sections have an additional "Unsupported" section, listing core features that are not yet supported in any version.

**Comment by randmonkey** [comment]
Could it be treated as duplicate as https://github.com/Kong/kubernetes-ingress-controller/issues/3173?

**Comment by randmonkey** [comment]
close it since https://github.com/Kong/docs.konghq.com/pull/4869 is merged.
