### ISSUE TITLE
hmac auth token in "Proxy-Authorization" header was unauthorized, but in "Authorization" is authorized.

### ISSUE THREAD

**Issue by HsinHeng** [Kong/kubernetes-ingress-controller#322]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.5.0

**Kong or Kong Enterprise version**
1.2.1

### Kubernetes version
1.11

**paste `kubectl version` output**
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
### Environment
AWS EKS

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
The same generated token, which is assigned to "Authorization" is 200, 
however, "Proxy-Authorization" is 401 {"message":"Unauthorized"}

### Expected behvaior
status: 200

**Comment by hbagdi** [comment]
Please re-open if issue persists.
