### ISSUE TITLE
Compatibility tests, docs and manifest updates for Kong 3.2

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Kong 3.2 is going to be released soon, there would be the following things to do on the KIC side after Kong 3.2 is released:
- [x] test compatibility of different versions of KIC and update docs
- [x] update kong images in manifests to bump default version of Kong to 3.2

### Additional information

related issue to bump kong version in charts: https://github.com/Kong/charts/issues/765

### Acceptance Criteria

- [x] Compatibility to Kong 3.2 of different versions of KIC is tested 
- [x] Kong/KIC compatibility matrix in docs includes Kong 3.2: https://github.com/Kong/docs.konghq.com/pull/5267
- [ ] default kong version in manifests updates to 3.2   https://github.com/Kong/kubernetes-ingress-controller/issues/3694 keep it in 2.9 milestone now, but we do not want it to block release of KIC 2.9.

**Comment by randmonkey** [comment]
mark this as blocked because Kong 3.2 has not been released yet.

**Comment by pmalek** [comment]
3.2 is available now https://github.com/Kong/kong/releases/tag/3.2.0

**Comment by randmonkey** [comment]
Kong gateway team has reverted 3.2.0 and released Enterprise version of 3.2.1.0: https://hub.docker.com/r/kong/kong-gateway/tags, but kong 3.2 CE image is not available yet: https://hub.docker.com/_/kong. So some work on compatibility tests could be done, but the whole issue is still blocked.

**Comment by pmalek** [comment]
3.2 CE is already available but not under official docker images but under `kong`'s org at docker hub: https://hub.docker.com/r/kong/kong/tags?page=1&name=3.2

**Comment by aresabalo** [comment]
Image kong 3.2.2 CE pushed to Docker Hub

**Comment by rainest** [comment]
AFAIK with https://github.com/Kong/kubernetes-ingress-controller/pull/3807 and the associated PR to main this is now clear.
