### ISSUE TITLE
Make annotations documentation up to date

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Current [KIC's annotations documentation](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/) doesn't mention various annotations [that are supported in code](https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/annotations/annotations.go) (e.g. `regex-prefix`, `connect-timeout`, and more). 

We should make sure that all supported annotations are documented properly on the official docs site.

### Proposed Solution

- Find out which annotations are not documented in the [KIC annotations](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/) reference
- Document the missing ones 
- Bonus points: generate the reference from code

### Acceptance Criteria

- [ ] [KIC annotations](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/) reference documents all annotations that KIC supports

**Comment by randmonkey** [comment]
Currently the only missing annotation is `force-ssl-redirect`. I think it will be good to split out an issue to automate the generation of docs.

**Comment by randmonkey** [comment]
Only regex-prefix is not the annotations page, but introduced here: https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/upgrade-kong-3x/
others are only displayed in kic 2.8 and later, you can see them in the latest docs since now 2.8 is released.

**Comment by czeslavo** [comment]
Ahh, got it. Thanks, I was looking at the rendered page instead of the source code. 👍
