### ISSUE TITLE
Synchronization of Kong Ingress Proxy Section

### ISSUE THREAD

**Issue by nbisson** [Kong/kubernetes-ingress-controller#328]
### Summary

The proxy section is not applied by Ingress.

**Kong Ingress controller version**

Kong Ingress : 0.5.0

**Kong or Kong Enterprise version**

Kong : 1.2

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): CentOS Linux 7
- **Kernel** (e.g. `uname -a`): 3.10.0-957.5.1.el7.x86_64
- **Install tools**:
- **Others**: The datastore is Cassandra.

### What happened

When we create a kong ingress yaml with custom proxy properties, the proxy section is not applied on Kong. 
I want to change protocol and service port (https) but Kong keep default values.

### Expected behvaior

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: configuration-demo
proxy:
  protocol: "https" # this doesn't work
```

In additional, how can I change the upstream server port ?

### Steps To Reproduce

1. Create a Kong Ingress with custom proxy protocol
2. See on Kong API the service output. 
3. On protocol, we have the default value

**Comment by hbagdi** [comment]
You will need to annotate the corresponding Kubernetes service with `configuration.konghq.com: configuration-demo` for this to take effect.

This is not clearly documented and I'm currently writing that documentation so it is clearly stated and users don't keep running into this issue again and again.

**Comment by nbisson** [comment]
Thanks, it works.
