### ISSUE TITLE
Does Standalone controller Nodes with cluster service kong_admin_url has any  concurrency conflict?

### ISSUE THREAD

**Issue by gung-rgb** [Kong/kubernetes-ingress-controller#3308]
According to kis‘s docs: [Deloyment with a db](https://docs.konghq.com/kubernetes-ingress-controller/2.8.x/concepts/deployment/#with-a-database), `Control Plane pods` deploy both `gateway` and `kic`, And `kic` send change to db by call admin api of local gateway container.
![image](https://user-images.githubusercontent.com/9658013/209790412-0ebf05f2-7c34-416b-8dbf-97dfd1425269.png)

However, According to helm chart's readme, Standalone controller Nodes with cluster service kong_admin_url  is also an deployment option. 
![image](https://user-images.githubusercontent.com/9658013/209793576-145fa040-27b2-4ef3-ad71-9f872747c7cd.png)

So, Does it mean I can deploy  only controller container for `Control Plane` , And than config kong_admin_url to a service_name exposed by `Data Plane pods`?
![image](https://user-images.githubusercontent.com/9658013/209792208-d1031d11-6e21-41df-acd9-d18a046ff602.png)

On that method, Change by admin_url will send to different  pods as we use k8s service name. But [Deloyment with a db](https://docs.konghq.com/kubernetes-ingress-controller/2.8.x/concepts/deployment/#with-a-database) says:
> If multiple replicas of this pod are running, a leader election process will ensure that only one of the pods is configuring Kong’s database at a time.

So, My question is that is Standalone controller Nodes with cluster service kong_admin_url ok? Does it has any problem like 
`concurrency conflict`? Since two change maybe sent to different pods, their order apply to db can not guarantee. Thanks.

**Comment by rainest** [comment]
Yes, if I understand your question right. There's no concurrency problem.

Setting the publish service doesn't affect what Kong instances the controller talks to. We only use it to ask Kubernetes for the Service LoadBalancer address, and then set that in Ingress statuses. We don't use it at all in Kong configuration.

The replicas leader bit only applies to the controller. Only one controller replica will send configuration to the admin URL at a time. The controller can manage its leader election independent of being part of the Deployment that manages the gateway instances.

All Kong instances in their Deployment are active all the time, but Kong (unlike the controller) is leaderless, and there's no need to send updates always to the same Kong instance. The database driver allows any Kong instance to update the DB. Updates trigger broadcasts that instruct all the other Kong instances to pull configuration after some Kong instance writes it.

I'll go ahead and close this out, but if you have any other questions let us know and we'll reopen it.
