### ISSUE TITLE
Lack of information information in admission controller error

### ISSUE THREAD

**Issue by FelipeSolanaAdidas** [Kong/kubernetes-ingress-controller#3356]
We use Kong with a lot of namespaces in only one workspace and we found a lot of problems that take time to be fixed because of a lack of information in the admission controller. 

This is only and example, in general will be nice to have namespace and name of the resources that provoke an error. The error start to happen when a user create a consumer with credentials:

Internal error occurred: failed calling webhook "[validations.kong.konghq.com](http://validations.kong.konghq.com/)": failed to call webhook: an error on the server ("**unique key constraint violated for username**") has prevented the request from succeeding

The error is not related with the resources that is getting the error but not information is provide to understand the origin

In this  case a username duplicated several time in other namespace.

With a different information will be easier identify the root of the problem:

Internal error occurred: failed calling webhook "[validations.kong.konghq.com](http://validations.kong.konghq.com/)": failed to call webhook: an error on the server ("**name: consumer-name namespaces :consumer-ns  unique key constraint violated for username**") has prevented the request from succeeding

**Suggestion change the return in the code to enrich the output:**

https://github.com/Kong/kubernetes-ingress-controller/blob/4b16d140a3a5e6d3f468c8d79b4c98865f57e8d2/internal/validation/consumers/credentials/validation.go#L133

`
return fmt.Errorf("name:%s namespaces:%s error:%v",secret.Name, secret.Namespace, err)
`

With this line will be easier identify this kind of problems.

How the user could add three times the same user credentials is for another episode

**Comment by pmalek** [comment]
Hi @FelipeSolanaAdidas 👋 

The suggestion seems 👍 to us. We'll happily accept a contribution if you're willing to make one.
