### ISSUE TITLE
Configured status of object is reported before translation all finished

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Method `parser.GenerateKubernetesObjectReport` for a kubernetes object is called when parser finished to generate services and routes for the object. This method is called to mark the object as "successfully configured" for controller to use. But translation failures on the object may happen after `GenerateKubernetesObjectReport` is called for the object. In such situation, controllers may mistake an object failed to translate as successfully configured. 

### Proposed Solution

- update the parser to store translation status of each object from both `configuredKubernetesObjects` and `failuresCollector`
- update the logic of controllers of judging whether an object is configured

### Additional information

Discovered in developing for #3172. Seems to be considered a sub-issue for it.

### Acceptance Criteria

- [ ] controllers for objects does not treat objects triggering translation failures in steps after `ingressRulesFrom*` as successfully configured

**Comment by mflendrich** [comment]
@randmonkey has this been fixed by https://github.com/Kong/kubernetes-ingress-controller/pull/3359 ?

**Comment by randmonkey** [comment]
> @randmonkey has this been fixed by #3359 ?

I think so. So it could be closed now.
