### ISSUE TITLE
How to use the kong Prometheus Plugin installed on kong via kubernetes-ingress-controller？

### ISSUE THREAD

**Issue by HefeiJoe** [Kong/kubernetes-ingress-controller#339]
https://github.com/Kong/kong-plugin-prometheus

Don't know how to configure conf of nginx

http://{kong-ingress-controller}:8001/metrics/
![image](https://user-images.githubusercontent.com/27885579/61855994-c95b4a80-aef3-11e9-8116-4a7cee24b637.png)

How to configure? kong via kubernetes-ingress-controller
server {
    server_name kong_prometheus_exporter;
    listen 0.0.0.0:9542; # can be any other port as well

    location / {
        default_type text/plain;
        content_by_lua_block {
             local prometheus = require "kong.plugins.prometheus.exporter"
             prometheus:collect()
        }
    }

    location /nginx_status {
        internal;
        access_log off;
        stub_status;
    }
}

help me，please！

**Comment by hbagdi** [comment]
You only need to scrape the port `9542` of Kong deployment to get Prometheus metrics.
You do not need to change any configuration in the nginx template for this purpose.

Please provide more details on how you are deploying the Kong Ingress Controller if you would like more help from us. Thanks you!

**Comment by HefeiJoe** [comment]
> You only need to scrape the port `9542` of Kong deployment to get Prometheus metrics.
> You do not need to change any configuration in the nginx template for this purpose.
> 
> Please provide more details on how you are deploying the Kong Ingress Controller if you would like more help from us. Thanks you!

I installed kong this way
# using YAMLs
kubectl apply -f https://bit.ly/kong-ingress
![image](https://user-images.githubusercontent.com/27885579/62175629-ec14b580-b370-11e9-9be5-e5172af43a9e.png)
Then add the Kong Prometheus Plugin
curl http://{kong-ingress-controller-ip}:8001/plugins -d name=prometheus
but，I don't see any metrics of Prometheus
Need I installPrometheus in kubernetes？Or do I need anything else?
I hope you can help me. Thank you, Sir

**Comment by hbagdi** [comment]
>  Need I install prometheus in kubernetes？Or do I need anything else?

Yes, you need to install Prometheus in your Kubernetes cluster if it is not already present.
And then configure Prometheus to collect metrics from Kong.
You can then use Prometheus or Grafana to visualize these metrics.
