### ISSUE TITLE
0.1.x controller attempts to PATCH SNI object incorrectly

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#340]
### Summary

When updating a hostname to use a new certificate, controller 0.1.x attempts to PATCH an SNI object by its ID. SNI objects do not have IDs on Kong versions supported by 0.1.x

**Kong Ingress controller version**
0.1.3

**Kong or Kong Enterprise version**
0.34-1

### What happened
The controller found an existing SNI for a hostname when attempting to apply a new certificate to it. This executed [this StatusOk](https://github.com/Kong/kubernetes-ingress-controller/blob/0.1.3/internal/ingress/controller/kong.go#L1178-L1191) case and attempted to execute `sni, res = client.SNIs().Patch(sni.ID, sni)`. Because SNI objects on 0.13-based releases do not have IDs (a complete object looks like `{"created_at":1555950056000,"name":"example.com","ssl_certificate_id":"7bbe8a14-6205-11e9-8808-121a6edbaadc"}`, the controller attempted to request `PATCH /snis/`, which is invalid.

On the controller, these log lines appear:
```
I0725 20:57:57.116118       7 kong.go:1184] updating certificate for host example.com to certificate id 50388d30-969f-11e9-8808-121a6edbaadc
E0725 20:57:57.118111       7 controller.go:131] unexpected failure updating Kong configuration: 
patching a Kong certificate: the server does not allow this method on the requested resource (patch snis.meta.k8s.io)
```
In the admin API pod, this log line (along with a lengthy generic "lapis couldn't satisfy this request" traceback) appears:
```
content_by_lua(nginx-kong.conf:125):2: in function <content_by_lua(nginx-kong.conf:125):1>, client: 127.0.0.1, server: kong_admin, request: "PATCH /snis HTTP/1.1", host: "localhost:8001"
```

### Expected behvaior
The controller patches the SNI object by name, e.g. `PATCH /snis/example.com`. The admin API accepts this and updates the SNI to use the new certificate.

`sni, res = client.SNIs().Patch(server.Hostname, sni)` should accomplish this.

### Steps To Reproduce
The following is unverified but should reproduce the issue:

1. Create an Ingress with a TLS definition.
2. Update the Ingress to use a different Secret for its TLS definition.
3. Review error logs

**Comment by rainest** [comment]
Temporary mitigation: because this only occurs when replacing an existing SNI, forcing the controller to create a new reaches the intended state without issues. To force this, manually delete the offending SNI object from the admin API, e.g.
```
curl -svX DELETE localhost:8001/snis/example.com
```

**Comment by hbagdi** [comment]
It is very unlikely that we will ever get to this. 0.1 was released a long time ago and the code has matured quite a bit over the last year, including a rewrite. Hence, I'm going to close this.
