### ISSUE TITLE
Single controller deployments: limit functionality to dbless only

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#3401]
As the original issue #702 mentions: single controller deployments, as implemented for the needs of #702, should only support dbless modes when using more than 1 replica.

This issue tracks the effort to enforce this limitation.

## Acceptance criteria
- [ ] If KIC is configured with gateway discovery enabled AND KIC notices that the setup is not db-less, KIC terminates with an error saying this is an unsupported configuration
- [ ] The Helm chart validates that gateway discovery cannot be enabled together with DB mode

**Comment by rainest** [comment]
> should only support dbless modes when using more than 1 replica

For historical context, https://github.com/Kong/kubernetes-ingress-controller/issues/2052. DB-backed "single" controller (i.e. controller Pod replicas managed by a controller-only Deployment) need a leader, and only that one leader may send config to its downstream Kong instance (via a Kong admin API Service).

Otherwise you'll hit split-brain scenarios where you talk to a different Kong instance that hasn't received configuration yet, or is still pulling it from the DB. In the past such eventually-consistent states have caused distributed systems issues (FTI-1158). We should review current DB-backed config sync behavior to inform our integration design (the mentioned issues are ancient, but a good source of lessons learned).

Single-controller deployments will need to interrogate their Kong partner and make determinations as to how they should handle downstream topography/ACID expectations and the like.

**Comment by pmalek** [comment]
> DB-backed "single" controller (i.e. controller Pod replicas managed by a controller-only Deployment) need a leader, and only that one leader may send config to its downstream Kong instance (via a Kong admin API Service).

Given that, we should not be concerned about leader election at all assuming that we'll only run one controller per Kong Gateway Deployment: there will only be one sending the configurations, right?

---

> DB-backed "single" controller (i.e. controller Pod replicas managed by a controller-only Deployment) 

How was that deployed in the past then?

**Comment by rainest** [comment]
> How was that deployed in the past then?

https://github.com/Kong/charts/blob/main/charts/kong/README.md#standalone-controller-nodes

You deploy the controller only, give it a URL to send updates to, tell it what LB Service it should use for Ingress status population (the Kong proxy Service, usually), and provide workspace/filter tag info.

The last of those (workspace/filter tag) is used when the Kong instance is in some sort of database-backed multi-tenant environment. Support for those should be an open question to product management. Aligns with the "DB-less only" aspect, but we be cognizant of what happens if you have a SCD and try to use `–kong-workspace` or `–kong-admin-filter-tag`.

**Comment by pmalek** [comment]
I'm having hard time understanding the challenge of leader election in the context of running 1 controller pod and 1 (or many with single controller deployments) Gateway instance(s).

There's just 1 that'll send the config, right?

**Comment by rainest** [comment]
Ideally, yes. We have had more complex configurations where there are multiple controllers looking at different Ingress classes and sending configuration for that ingress class to specific Kong workspace. Forgive the horrid ASCII diagram:
```
  controller instance configured to use red ingress class


┌──────────────────┐                                       ┌──────────────────────────────────────────────┐
│                  │                                       │              kong deployment                 │
│ ingress class red│                                       │                                              │
│                  │                                       │                                              │
│ ┌─────           │                                       │                                              │
│ │inactive┼replicas                                       │                                              │
│ │    │  │      │ │                                       │       ┌───────────────────────┐              │
│ └────┘  └──────┘ │                                       │       │                       │              │
│                  │                                       │       │     red workspace     │              │
│ ┌──────────────┐ │                                       │       │                       │              │
│ │              │ │                                       │       │                       │              │
│ │  leader      │ ├───────────────────────────────────────┼───────►                       │              │
│ ├──────────────┤ │                                       │       │                       │              │
└─┴──────────────┴─┘                                       │       │                       │              │
                                                           │       │                       │              │
 controller instance configured to use blue ingress class  │       └───────────────────────┘              │
┌──────────────────┐                                       │                                              │
│                  │                                       │                                              │
│                  │                                       │                                              │
│   ingress class blue                                     │                                              │
│                  │                                       │          ┌──────────────────────┐            │
│                  │                                       │          │                      │            │
│                  │                                       │          │                      │            │
│             │    │                                       │          │   blue workspace     │            │
│             └────┼───────────────────────────────────────┼──────────►                      │            │
│                  │                                       │          │                      │            │
│                  │                                       │          │                      │            │
│                  │                                       │          │                      │            │
│                  │                                       │          └──────────────────────┘            │
└──────────────────┘                                       │                                              │
                                                           │                                              │
                                                           │                                              │
                                                           │                                              │
                                                           │                                              │
                                                           │                                              │
                                                           └──────────────────────────────────────────────┘
```

There may be multiple active controller instances (Pod replicas for a controller Deployment), only one of which has leadership. The controller leader is the only one interacting with the Kong admin API, the others are just keeping track of resources and generating configuration should they need to take over.

If there are many _DB-less instances_, the controller leader would be responsible for actually sending the `POST /config` requests to each of the Kong Pods, via each Kong Pod's admin API.

If there many DB-backed instances, the controller leader talks to a single Kong admin API Service, and then Kong's config replication takes care of distributing config to all the proxy instances.

`–kong-workspace` or `–kong-admin-filter-tag` affect how that controller leader interacts with that admin API Service (whether it uses a workspaced admin API URL) and the resources it creates (the tag filter).

**Comment by pmalek** [comment]
> If there are many DB-less instances, the controller leader would be responsible for actually sending the POST /config requests to each of the Kong Pods, via each Kong Pod's admin API.

As per https://github.com/Kong/kubernetes-ingress-controller/blob/9d052f5f71dc0e14de9e56e596ef180176a76717/internal/manager/setup.go#L53-L56 we don't do this today with dbless, i.e. we automatically set leader election to disabled.

**Comment by rainest** [comment]
That's true, but we also only have the one controller per Kong instance. With a single-controller deployment, that will no longer be the case: there will be N controller replicas, and only one should be sending configuration to the Kong instances at a given time. One controller to many Kongs _will_ require a leader election.

**Comment by randmonkey** [comment]
Now we already enabled leader election when SCD/gateway discovery is enabled:https://github.com/Kong/kubernetes-ingress-controller/blob/836455cc213a341860cf6a39a858d705a4ee8275/internal/manager/setup.go#L112-L115

So when SCD is enabled, only one instance could send configurations to Kong gateways. Do we still need this to enable SCD/gateway discovery only for dbless mode? What is expected when db backed gateways deployed, and SCD enabled?  @rainest @pmalek

**Comment by czeslavo** [comment]
From what I understand, even if the DB-mode along with GW discovery MIGHT work in the current state, we want to explicitly limit the use cases (similarly to the Konnect sync, where we explicitly only allow it to be used together with the GW discovery while in theory it should also work with a single Pod deployment just fine).

**Comment by pmalek** [comment]
Referring to the discussion we had on this topic on Slack: the consensus is that we do want to ship support for dbless **only** initially (i.e. in v2.9).

We might (and most likely will) ship support for db-backed setups as well in later releases (most likely the one that comes after 2.9). The primary reason for this is to allow soak time of gateway discovery and to prune out all the possible edge cases that are out there.

Having said that @randmonkey the snippet you linked can stay as is for now. Additionally we push back (for now to v2.10 milestone) #3607.
