### ISSUE TITLE
Documentation for PR Template format. Good documentation needed

### ISSUE THREAD

**Issue by viragumathe5** [Kong/kubernetes-ingress-controller#341]
The PR template needs to be well documented that helps the contributors contributing to KONG

https://github.com/Kong/kubernetes-ingress-controller/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by hbagdi** [comment]
If you feel there are any additions to the template that will help in the contribution, please feel free to open a PR to update it, thanks.
