### ISSUE TITLE
ConfigPush metrics in SCD mode should be labeled with dataplane's host

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

KIC reports `ConfigPushCount` and `ConfigPushDuration` Prometheus metrics. When running in SCD mode, it could be useful to have the reported metrics to be grouped by an instance of a dataplane.

### Proposed Solution

Add `dataplane_host` label to both `ConfigPushCount` and `ConfigPushDuration` metrics.

### Acceptance Criteria

- [x] It's possible to group `ConfigPushCount` and `ConfigPushDuration` Prometheus metrics by dataplane address
- [ ] Users can get information about this change from outside facing documentation https://docs.konghq.com/kubernetes-ingress-controller/latest/references/prometheus/
  - https://github.com/Kong/docs.konghq.com/pull/5146

**Comment by pmalek** [comment]
Relevant docs PR: https://github.com/Kong/docs.konghq.com/pull/5146

**Comment by rainest** [comment]
Closing this one since we have the separate docs milestone tracking that and the code is already in.
