### ISSUE TITLE
Make all-in-one-dbless use SCD

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#3423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

After #702 gets implemented in the controller we have to expose this functionality to the end users.

This issue aims to track this effort.

### Proposed Solution

- Change all the all-in-one DBLESS manifests to use SCD.
- Mark the old `all-in-one-dbless.yaml` as deprecated by renaming it to `all-in-one-dbless-legacy.yaml`

### Acceptance Criteria

- [x] As a user I can deploy KIC with Gateway using "all-in-one" manifest(s) and leverage  #702.
- [ ] The old `all-in-one-dbless.yaml` (using a single Pod deployment) is renamed to `all-in-one-dbless-legacy.yaml`
- [ ] All all-in-one DBLESS manifests in `deploy/single` use SCD and their paths are unchanged.
- [ ] E2E tests using old `all-in-one-dbless.yaml` use the new one (with the same name, but using SCD)
- [ ] There's an E2E verifying `all-in-one-dbless-legacy.yaml` works as expected

**Comment by pmalek** [comment]
This is almost done.

Users can already use [deploy/single/all-in-one-dbless-multi-gw.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-dbless-multi-gw.yaml) to install KIC in SCD mode (separate KIC and Gateway deployments).

Currently those manifests use 2.8.1 tag for KIC, hence its deployment is expected to fail with this until 2.9 is released (with #3421) and used in those manifests.

**Comment by czeslavo** [comment]
Do the ACs still hold? 

> 1. All all-in-one DBLESS manifests in deploy/single use SCD and their paths are unchanged.

Do we really intend to deprecate the old DB-less single-pod setup and replace it with gw-discovery?

We've introduced [deploy/single/all-in-one-dbless-multi-gw.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-dbless-multi-gw.yaml) which became a separate, brand-new deploy option.

I'd say it should still be a valid config to have a single Pod deployment as it's the simplest one which in many cases will be sufficient for users. Please correct me if I'm wrong.

**Comment by czeslavo** [comment]
After our discussion on Slack, I have updated the ACs of this issue to be more precise in terms of renaming the all-in-one manifests and covering E2E tests adaptation. @pmalek @mflendrich please take a look if that makes sense.

**Comment by pmalek** [comment]
> After our discussion on Slack, I have updated the ACs of this issue to be more precise in terms of renaming the all-in-one manifests and covering E2E tests adaptation. @pmalek @mflendrich please take a look if that makes sense.

👍 from me.
