### ISSUE TITLE
Ensure that tests for single controller deployments exist

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3429]
With #702 being implemented and #3421 merged we'd like to ensure that we have sufficient test coverage for Single Controller Deployments.

### Acceptance Criteria

- [x] All components of KIC that are affected by SCD are covered with unit tests
  - [x] #3634
  - [x] https://github.com/Kong/kubernetes-ingress-controller/issues/3568
- [x] Multi Gateway all in one manifests are tested in e2e test suite after making those manifests a default (https://github.com/Kong/kubernetes-ingress-controller/issues/3423)
- [x] e2e test for this has been added in https://github.com/Kong/kubernetes-ingress-controller/pull/3421/files#diff-d7850eda46771ac1eb42d866bb557fd98bdea88b6bcfba6b26b10cc975a40856

**Comment by mflendrich** [comment]
closed in favor of #3568

**Comment by czeslavo** [comment]
Reopening this after realizing there's more than just one test to be added before the release. Let this issue serve us as the one that when closed means SCD is covered sufficiently in tests.

I made a [comment](https://github.com/Kong/kubernetes-ingress-controller/issues/3631#issuecomment-1450084133) in https://github.com/Kong/kubernetes-ingress-controller/issues/3631 that might be helpful in understanding rationale behind tests I put into the AC of this issue.

Can we agree that everything included in this issue's ACs is enough to consider SCD ready for release? @pmalek @mflendrich
