### ISSUE TITLE
Feature request: L4 Ingress support

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#343]
Kubernetes Ingress API doesn't support L4 (TCP) yet.
Research ways to add in support either using existing KongIngress API or other solutions.

**Comment by hbagdi** [comment]
@desktophero We're actively adding in support for gRPC.

I've put this on hold due to unclear L4 requirements from end-users.
Can you explain your use-case please?

**Comment by mukgupta** [comment]
I am not sure if I really need L4 Ingress for this but here you go. I have a Kubernetes Pod that listens on TCP/UDP. I want to expose this TCP/UDP service publicly using Ingress. Currently I have to create a LoadBalancer for this (which has extra cost).

**Comment by hbagdi** [comment]
So, would the simplest solution of having an Ingress solution to route based on `sni` (if encrypted TLS), or using the source/destination IP/port combination enough for your use-case?

**Comment by mukgupta** [comment]
In my case I'd want to have routing based on a fixed port number
