### ISSUE TITLE
Conformance Test: GatewayInvalidRouteKind

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3447]
Split from #3305. 
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

After bumping gateway API to 0.6.0,  conformance test case `GatewayInvalidRouteKind` fails because no `ResolvedRef` condition is added to the gateway status. 

### Proposed Solution

- Add  `ResolvedRef` condition with status `False` in gateway status if the gateway contains unsupported route kind.

### Acceptance Criteria

- [ ] conformance test case `GatewayInvalidRouteKind` passes.

**Comment by mlavacca** [comment]
fixed by #3513
