### ISSUE TITLE
Include the KIC-Konnect integration in telemetry

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Introducing KIC-Konnect integration we would like to have visibility of the installations that use it.

### Proposed Solution

Add a `konnect` parameter to the signal that KIC reports to Splunk.

### Acceptance Criteria

- [ ] KIC reports `konnect` parameter in its telemetry signal when a Konnect feature flag is enabled

**Comment by czeslavo** [comment]
Filled out the ACs, un-assigning myself.
