### ISSUE TITLE
Port projected volume SA token from chart

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#3475]
https://github.com/Kong/charts/pull/722 added support for the [modern projected volume system](https://github.com/Kong/kubernetes-ingress-controller/issues/2731) to the chart. We should update the deployment manifests here to use the same.

Acceptance:

- [ ] The KIC [deploy manifests](https://github.com/Kong/kubernetes-ingress-controller/tree/main/deploy/single) use a projected volume for their ServiceAccount tokens.
- [ ] The projected volume configuration matches the configuration used in the chart.

**Comment by rainest** [comment]
Stuffing this in 2.9 for now since it should just be copy/paste from the chart unless we discover that there's some unexpected issue and need to rework the design.

**Comment by pmalek** [comment]
It just occurred to me that when doing this we'll be cutting out users using k8s older than 1.20.

Unless there's a mechanism in `kustomize` - that I'm not aware of -  to make a manifest be included conditionally based on k8s version (which you can do in `helm`).

**Comment by seh** [comment]
> Unless there's a mechanism in `kustomize`

There is no such mechanism, given that _kustomize_ is not a client of the Kubernetes API.
