### ISSUE TITLE
Feature request: support for upstream client authentication

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#348]
Kong 1.3 will ship with support for client authentication on the upstream side.
This means that Kong can authenticate itself to the upstream and upstream service can accept traffic only from Kong if needed.

**Comment by vietwow** [comment]
Hi @hbagdi , this feature is about mutual ssl authentication ?

**Comment by hbagdi** [comment]
Yes, it is one part to mutual TLS authentication. The other part, Kong verify upstream's certificate is already supported.
So, once this is merged in, you can essentially perform mTLS between Kong and your service.
