### ISSUE TITLE
Stub issue for number ports creating zero-backend services

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#3484]
Something is broken with port/service mapping that I don't quite understand yet. This collects notes for the time being.

Broadly, it looks like we didn't build support for Ingresses that reference port by number instead of name into combined routes properly.

https://gist.github.com/rainest/8d5a067e9c8b93c98100559fcbe75631 reproduces this issue.

**Comment by seh** [comment]
I _think_ I'm suffering a similar problem even for _Ingresses_ referencing _Service_ ports by name. It works for some _Ingresses_ and _Services_, but not for others. I haven't yet figured out which details make the difference.

**Comment by seh** [comment]
> I haven't yet figured out which details make the difference.

That turned out to be due to using DNS names in the "tls" field that are too long to fit in a an X.509 certificate's CN.

**Comment by rainest** [comment]
Per https://github.com/Kong/kubernetes-ingress-controller/pull/3691 description and seh's comments it looks like this was a red herring. I forgot to change something and got confused by the error message.

There is an existing error that explains the actual problem:

```
ERRO[26402] failed to fetch service: Service default/httpbin not found  service_name= service_namespace=default
```
I got hung up on my new one firing as a side effect.
