### ISSUE TITLE
Surface deck errors as Kubernetes events

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Similarly to https://github.com/Kong/kubernetes-ingress-controller/issues/3205, we'd like to make sure that all error/warnings detected by deck when applying configuration in DB-mode are properly propagated by means of Kubernetes events.

### Proposed Solution

Refactor deck `sync.Solver` so it returns errors/warnings it detected.

### Acceptance Criteria

- [ ] When deck rejects an entity a Kubernetes Event is created on the resource that is the reason for rejection.

**Comment by mheap** [comment]
This is a nice to have, but given our primary topologies of DB-less and non-KIC with Konnect I think this should wait

**Comment by mflendrich** [comment]
It may make sense to do #5289 as a prerequisite for this issue.
