### ISSUE TITLE
client-body-buffer-size

### ISSUE THREAD

**Issue by urvineet** [Kong/kubernetes-ingress-controller#350]
i want to update client-body-buffer-size

Found for Nginx
nginx.ingress.kubernetes.io/client-body-buffer-size: 1M

**Comment by ismailbaskin** [comment]
@urvineet Do you want to use different body buffer size value for each service?

**Comment by ismailbaskin** [comment]
You can mount custom nginx configuration file via config map volume to kong-ingress-controller container. After that, you have to specify the config file's path with KONG_NGINX_HTTP_INCLUDE env variable. You can find examples from this [documentation](https://docs.konghq.com/1.0.x/configuration/#including-files-via-injected-nginx-directives).

**Comment by urvineet** [comment]
to achieve it,  i need to define custom server block in conf file which i am looking 

I just want to update client-body-buffer-size

**Comment by hbagdi** [comment]
For the Kong container, set the following env variable:
```
KONG_CLIENT_BODY_BUFFER_SIZE: 1024k
```

Refer: https://github.com/Kong/kong/blob/1.2.1/kong.conf.default#L391

**Comment by andloh** [comment]
Can `client-body-buffer-size` be configured via an annotation or KongPlugin now? Like nginx: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#client-body-buffer-size

**Comment by MArK1done** [comment]
> Can `client-body-buffer-size` be configured via an annotation or KongPlugin now? Like nginx: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#client-body-buffer-size

Same question for me. Is this feature available now?

**Comment by programmer04** [comment]
It can be configured globally per Kong Gateway with the environment variable `KONG_CLIENT_BODY_BUFFER_SIZE` see how to use it with
- [with Helm](https://docs.konghq.com/kubernetes-ingress-controller/latest/install/helm/#main) - in value file set `gateway.env.client_body_buffer_size:  1024k`
- for Kong Gateway Operator use [DeploymentOptions](https://docs.konghq.com/gateway-operator/latest/reference/custom-resources/#deploymentoptions)

**Comment by juan-kabbali** [comment]
> Can `client-body-buffer-size` be configured via an annotation or KongPlugin now? Like nginx: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#client-body-buffer-size

Same question here, as  `client_body_buffer_size` could differs between ingresses.
