### ISSUE TITLE
Ensure kubectl GKE auth plugin is installed in CI environments

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

In order to authenticate with GKE using `kubectl`, from v1.26 a custom `kubectl` plugin will be required. We have to adapt our workflows to ensure that the plugin is installed and does not break tests on v1.26.

### Proposed Solution

Add a step to install the plugin in CI (either by some custom GH action or `sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin`). 

### Additional information

Google's article describing whys: https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke.

GKE release notes: https://cloud.google.com/kubernetes-engine/docs/release-notes

### Acceptance Criteria

- [ ] Tests against GKE v1.26 pass
OR
- [ ] We get no warnings regarding the deprecation of kubectl built-in GKE auth in tests against GKE < v1.26 (if we decide to complete it before v1.26 is available on GKE)

**Comment by pmalek** [comment]
It seems that no warnings can be observed in E2E GKE test runs.

Is there anything else we need to do here or is this ready to be closed @czeslavo?

**Comment by czeslavo** [comment]
Perhaps it is so because we no longer use `kubectl` directly in the GH workflow or the e2e Makefile target. Yeah, I think we can close it. 👍
