### ISSUE TITLE
When the pod is rolled and updated, the http request is interrupted for nearly 1s

### ISSUE THREAD

**Issue by chenzhougit** [Kong/kubernetes-ingress-controller#3505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by chenzhougit** [comment]
When adding upstream, is it possible to judge the status of the pod?

**Comment by mflendrich** [comment]
@chenzhougit, please fill in the expected & actual behavior when reporting issues in our repo.

Based on my understanding of the problem you're reporting, I think that the `/status/ready` endpoint (https://github.com/Kong/charts/pull/844) in Kong might give you the behavior you're expecting.
