### ISSUE TITLE
Gateway API v0.6.1 support

### ISSUE THREAD

**Issue by shaneutt** [Kong/kubernetes-ingress-controller#3516]
The purpose of this task is to implement support for Gateway API v0.6.1.

This patch release includes a large number of conformance test changes.

- [ ] Update CRD usage everywhere to v0.6.1
- [ ] Make code adjustments for relevant changes
- [ ] Make code adjustments to fulfill applicable conformance tests

**Comment by shaneutt** [comment]
Blocked on the [upstream v0.6.1 release](https://github.com/kubernetes-sigs/gateway-api/pull/1702).

**Comment by shaneutt** [comment]
Release is out: https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.6.1

No longer blocked.

**Comment by mlavacca** [comment]
Fixed by https://github.com/Kong/kubernetes-ingress-controller/pull/3524
