### ISSUE TITLE
Ensure objects IDs are stable across Konnect and managed Gateway instances

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

When Konnect integration is enabled, we should make sure that all objects' IDs we configure both in Konnect and all managed Kong proxies are consistent and stable. That means that a Kong Gateway resource generated by KIC in the parsing process has to:
- have the same ID both in Konnect and in all proxy instances that are managed by KIC,
- the ID doesn't change between data-plane sync loop runs if the object name hasn't changed since the last run.

This is a requirement that will enable reliable and consistent metrics/analytics gathering. 

### Proposed Solution

When running in Konnect mode, first synchronize the configuration against Konnect and keep it for updating all the managed Kong proxies. That will ensure that IDs are populated with the ones that Konnect has assigned to the objects during their creation, and they will be propagated accordingly to all the proxies instances.

### Acceptance Criteria

- [x] All Gateway resources (Service, Route, etc.) have stable IDs assigned across all Admin APIs that KIC calls (both in Konnect and regular Kong proxies)
- [x] Gateways resources' IDs do not change between data-plane sync loop runs given the resource name hasn't changed since the last run

**Comment by mflendrich** [comment]
Prior art: https://github.com/Kong/kubernetes-ingress-controller/issues/834#issuecomment-759739025

**Comment by mheap** [comment]
@czeslavo I've linked the PR you submitted. Is that enough to consider this issue done?

**Comment by czeslavo** [comment]
@mheap Yes, that is done. Sorry, I didn't update it accordingly. Closing.
