### ISSUE TITLE
how to set proxy_connect_timeout for single service

### ISSUE THREAD

**Issue by xbazhen** [Kong/kubernetes-ingress-controller#354]
I want to set some config for a service
```
    proxy_connect_timeout 900;
    proxy_read_timeout 900;
    proxy_send_timeout 900;
```

in kubernetes offical nginx-controller，I can set as：
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy‑connect‑timeout: 900
    nginx.ingress.kubernetes.io/proxy‑read‑timeout: 900
    nginx.ingress.kubernetes.io/proxy‑send‑timeout: 900
```
Does kubernetes-ingress-controller and kong support this?
If yes，how to set？

**Comment by hbagdi** [comment]
No, Kong Ingress Controller doesn't support those annotations as they are specific to the Nginx Ingress Controller.

To do this using Kong, you need to use KognIngress resource:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/references/custom-resources.md#kongingress

Please see [this guide](https://github.com/Kong/kubernetes-ingress-controller/tree/master/docs/guides) on how to use KongIngress resource.

**Comment by xbazhen** [comment]
> No, Kong Ingress Controller doesn't support those annotations as they are specific to the Nginx Ingress Controller.
> 
> To do this using Kong, you need to use KognIngress resource:
> https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/references/custom-resources.md#kongingress
> 
> Please see [this guide](https://github.com/Kong/kubernetes-ingress-controller/tree/master/docs/guides) on how to use KongIngress resource.

Do you mean set like this in kongIngress？
```
proxy:
  connect_timeout: 10000
  read_timeout: 10000
  write_timeout: 10000
```

**Comment by hbagdi** [comment]
> Do you mean set like this in KongIngress？

Yes.
And then associate the KongIngress resource with the Kubernetes service for which you want to set the timeout in Kong.

Please close the issue if your issue is resolved with this solution. Thanks!

**Comment by xbazhen** [comment]
> > Do you mean set like this in KongIngress？
> 
> Yes.
> And then associate the KongIngress resource with the Kubernetes service for which you want to set the timeout in Kong.
> 
> Please close the issue if your issue is resolved with this solution. Thanks!

OK，I will do after debugged the 404 problem。

**Comment by xbazhen** [comment]
[The 404 problem](https://github.com/Kong/kubernetes-ingress-controller/issues/355#issue-479460093) might take a little longer, close it for now.

**Comment by vivianforzj** [comment]
@xbazhen Have you solved the problem? If you have, could you share your settings?  I still cannot work it out.Thank you.

**Comment by hbagdi** [comment]
Please follow the following guide to override a specific configuration in Service in Kong:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-kongingress-resource.md

**Comment by vivianforzj** [comment]
I use kong ingress according to the guide, and add the timeout settings, but it seems that the timout settings does not work as expected.

**Comment by hbagdi** [comment]
Can you please open a new Github issue with your problem?
Please mention all the configuration you have.

**Comment by vivianforzj** [comment]
@hbagdi I had already opened a new issue https://github.com/Kong/kubernetes-ingress-controller/issues/472
