### ISSUE TITLE
frequently return 404 in db less

### ISSUE THREAD

**Issue by xbazhen** [Kong/kubernetes-ingress-controller#355]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version** 0.5.0

**Kong version**  1.2.0 1.2.1

### Kubernetes version 1.14.1

**Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}**

### Environment

- **Cloud provider or hardware configuration  **: VM
- **OS** : Ubuntu 16.04.5 LTS
- **Kernel** : Linux Pi-k8s-master1-U17 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

### What happened
I install kubernetes-ingress-controller and kong in my kubernetes cluster，as this document：
[getting-started](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/getting-started.md)

but I frequently receive 404 from such url

curl -i http://10.2.3.34:30372/foo
{"message":"no Route matched with those values"}

https://node-ip:admin-api-nodeport/services
{"next":null,"data":[]}
https://node-ip:admin-api-nodeport/routes
{"next":null,"data":[]}

even i access pod ip，it also return 404，frequently 。
https://node-ip:admin-api-nodeport/routes

I believe it may not be a config problem，Because request http://10.2.3.34:30372/foo more frequent，such as 30 times in 10s，it will return 10 normal and 20 bad。(kong:1.2.0)

After I upgrade kong to 1.2.1，It becomes normal，this afternoon。
unfortunately，2 days later(kong:1.2.1)，I reuqust it again，  https://node-ip:admin-api-nodeport/services
I received the same result as kong 1.2.0。

### Expected behvaior
curl -i http://10.2.3.34:30372/foo
not 404

https://node-ip:admin-api-nodeport/services
have data

### Steps To Reproduce

1. kubernetes 1.14.1
2. helm install kubernetes-ingress-controller 0.5.0 and kong 1.2.0 with db less
    helm install stable/kong --set ingressController.enabled=true \
  --set postgresql.enabled=false --set env.database=off
3. [getting-started](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/getting-started.md) 
4. frequent access such url，about 3 times every 1s。
 http://node-ip:kong-proxy-nodeport/foo
 https://node-ip:admin-api-nodeport/services
 https://node-ip:admin-api-nodeport/routes

**Comment by hbagdi** [comment]
We need some more details to help you debug the issue:
- How many pods of the Ingress Controller are you running?
- Can you share the controller logs?

**Comment by xbazhen** [comment]
> We need some more details to help you debug the issue:
> 
> * How many pods of the Ingress Controller are you running?
> * Can you share the controller logs?

1 pod
```
# kubectl get po | grep kong
ingress-controller-kong-85dbc5d9b9-rsswc   2/2     Running   2          76m
```

I request it 60 times，1 time per second。
```
# for i in $(seq 1 60)
> do
>     echo $(date -R) | tr '\n' '|' | sed 's/|/              /g'; curl -s -I http://10.2.3.34:30352/foo | grep HTTP
>     sleep 1
> done
Tue, 13 Aug 2019 16:23:39 +0800              HTTP/1.1 503 Service Temporarily Unavailable
Tue, 13 Aug 2019 16:23:40 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:41 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:42 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:43 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:45 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:46 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:23:48 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:49 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:50 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:51 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:52 +0800              HTTP/1.1 503 Service Temporarily Unavailable
Tue, 13 Aug 2019 16:23:53 +0800              HTTP/1.1 503 Service Temporarily Unavailable
Tue, 13 Aug 2019 16:23:54 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:55 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:23:56 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:57 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:58 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:23:59 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:00 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:01 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:02 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:03 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:04 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:05 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:07 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:08 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:09 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:10 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:11 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:12 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:13 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:14 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:15 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:16 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:17 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:18 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:19 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:20 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:21 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:22 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:23 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:24 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:25 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:26 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:27 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:28 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:29 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:30 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:32 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:33 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:34 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:35 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:36 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:37 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:38 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:39 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:40 +0800              HTTP/1.1 200 OK
Tue, 13 Aug 2019 16:24:41 +0800              HTTP/1.1 404 Not Found
Tue, 13 Aug 2019 16:24:42 +0800              HTTP/1.1 200 OK
```

some logs of ingress-controller-kong
```

I0813 08:23:46.703107       1 controller.go:128] successfully synced configuration to Kong
W0813 08:23:51.068639       1 parser.go:660] service prd/xxx-101-svc does not have any active endpoints
W0813 08:23:51.068734       1 parser.go:660] service prd/xxx-102-svc
W0813 08:23:51.069347       1 parser.go:660] service prd/
W0813 08:23:51.069485       1 parser.go:660] service prd/
W0813 08:23:51.069586       1 parser.go:660] service prd/
W0813 08:23:51.069757       1 parser.go:660] service prd/
W0813 08:23:51.069781       1 parser.go:660] service prd/
W0813 08:23:51.069840       1 parser.go:660] service prd/
W0813 08:23:51.069862       1 parser.go:660] service prd/
W0813 08:23:51.069931       1 parser.go:660] service prd/
W0813 08:23:51.069964       1 parser.go:660] service prd/
W0813 08:23:51.069985       1 parser.go:660] service prd/
W0813 08:23:51.070015       1 parser.go:660] service prd/
W0813 08:23:51.070146       1 parser.go:660] service prd/
W0813 08:23:51.070170       1 parser.go:660] service prd/
W0813 08:23:51.070645       1 parser.go:660] service prd/
W0813 08:23:51.070845       1 parser.go:660] service prd/
W0813 08:23:51.070942       1 parser.go:660] service prd/
W0813 08:23:51.070984       1 parser.go:660] service prd/
W0813 08:23:51.071127       1 parser.go:660] service prd/
W0813 08:23:51.071191       1 parser.go:660] service prd/
W0813 08:23:51.071232       1 parser.go:660] service prd/
W0813 08:23:51.071259       1 parser.go:660] service prd/
W0813 08:23:51.071280       1 parser.go:660] service prd/
W0813 08:23:51.071699       1 parser.go:660] service prd/
W0813 08:23:51.071880       1 parser.go:660] service prd/
W0813 08:23:51.071996       1 parser.go:660] service prd/
W0813 08:23:51.072317       1 parser.go:660] service prd/
W0813 08:23:51.072393       1 parser.go:660] service prd/
W0813 08:23:51.072473       1 parser.go:660] service prd/
W0813 08:23:51.072555       1 parser.go:660] service prd/
W0813 08:23:51.072600       1 parser.go:660] service prd/
W0813 08:23:51.072687       1 parser.go:660] service prd/
W0813 08:23:51.072836       1 parser.go:660] service prd/
W0813 08:23:51.073329       1 parser.go:660] service prd/
W0813 08:23:51.073503       1 parser.go:660] service prd/
W0813 08:23:51.073602       1 parser.go:660] service prd/
E0813 08:23:51.074141       1 parser.go:480] error getting endpoints for 'auto/xxx-666-svc' service: error getting service 'auto/xxx-666-svc' from the cache: service auto/xxx-666-svc was not found
E0813 08:23:51.074472       1 parser.go:360] fetching KongIngress for service auto/xxx-666-svc: fetching service 'auto/xxx-666-svc' from cache: service auto/xxx-666-svc was not found
E0813 08:23:51.075591       1 parser.go:385] fetching KongIngress for service 'xxx-666-svc' in namespace 'auto': fetching service 'auto/xxx-666-svc' from cache: service auto/xxx-666-svc was not found
E0813 08:23:51.075663       1 parser.go:541] fetching service 'auto/xxx-666-svc': service auto/xxx-666-svc was not found
I0813 08:24:08.321063       1 controller.go:128] successfully synced configuration to Kong
```

**Comment by hbagdi** [comment]
I was not able to reproduce this locally.

@xbazhen Can we narrow this down a little?
From logs, it seems like there are other Ingress rules that exist as well.
Can you remove those Ingress rules and only have a single Ingress rule for the echo service and ensure if the problem exists or not?

**Comment by xbazhen** [comment]
> I was not able to reproduce this locally.
> 
> @xbazhen Can we narrow this down a little?
> From logs, it seems like there are other Ingress rules that exist as well.
> Can you remove those Ingress rules and only have a single Ingress rule for the echo service and ensure if the problem exists or not?

OK，these ingresses are a part of our disaster recovery env。
I can delete it and tested again

**Comment by hbagdi** [comment]
Do you have Ingress resource for each of those 46 services?
Only if an Ingress resource exists, then the controller will try to sync those services to Kong.

**Comment by xbazhen** [comment]
yes, they are created by helm template.

**Comment by hbagdi** [comment]
Can you edit them and use `ingress.class` resource to limit Kong to only one Ingress resource?

I suspect this is to do with a specific configuration and we need to drill down to the problematic configuration to have a reproducible test case.

**Comment by hbagdi** [comment]
Please re-open this issue if it persists and if we can have more data to get to the root of this.

**Comment by wopol** [comment]
@hbagdi  i have the same issue:

Kong Ingress controller version
0.6.0

Kong proxy version
1.4

I periodically see problems with ingress controller. After this log(kong) all request to kong ends with 404 statusCode.
```
2019/12/17 12:30:49 [notice] 845#0: *249884 [lua] cache.lua:321: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"
2019/12/17 12:30:49 [notice] 1#0: signal 17 (SIGCHLD) received from 845
2019/12/17 12:30:49 [alert] 1#0: worker process 845 exited on signal 9
2019/12/17 12:30:49 [alert] 1#0: shared memory zone "kong_process_events" was locked by 845
2019/12/17 12:30:49 [notice] 1#0: start worker process 846
```
After one or two minutes i see
```
2019/12/17 12:31:49 [notice] 846#0: *249915 [lua] cache.lua:321: purge(): [DB cache] purging (local) cache, client: 127.0.0.1, server: kong_admin, request: "POST /config?check_hash=1 HTTP/1.1", host: "localhost:8444"
```
And everything works great. This situation is correlated with log from ingress-controller:
```
E1217 12:30:49.409910       1 controller.go:132] unexpected failure updating Kong configuration:
posting new config to /config: making HTTP reqeust: Post https://localhost:8444/config?check_hash=1: EOF
W1217 12:30:49.409937       1 queue.go:113] requeuing com-prod-hp/frontend-service, err posting new config to /config: making HTTP reqeust: Post https://localhost:8444/config?check_hash=1: EOF
```
But ingress controller is running with flag --ingress-class=hans. Why received event from com-prod-hp namespace ? ?
