### ISSUE TITLE
Use Konnect SDK in Konnect integration tests

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

In order to unblock ourselves when developing KIC-Konnect integration, we manually generated runtime-groups and runtime-groups-config Go clients to be used in KIC tests: https://github.com/Kong/kubernetes-ingress-controller/pull/3535 

In the meantime, an official Go SDK for Konnect APIs was developed: https://github.com/Kong/sdk-konnect-go. We can now use it instead of our own client.

### Proposed Solution

Modify testing helpers to use the Konnect SDK instead of the internal client ([1](https://github.com/Kong/kubernetes-ingress-controller/tree/7f0eb0424b69be4afb48b363f03f74a78f1eebc5/internal/konnect/controlplanes), [2](https://github.com/Kong/kubernetes-ingress-controller/tree/7f0eb0424b69be4afb48b363f03f74a78f1eebc5/internal/konnect/controlplanesconfig)).

### Acceptance Criteria

- [ ] Konnect SDK is used to create test control planes and data planes' client certificates in Konnect.

**Comment by tao12345666333** [comment]
I want to pick up this one. However, I noticed that in the README of this repository, it is stated that this project is only a prototype. I would like to confirm if we can use this project.


https://github.com/Kong/sdk-konnect-go/blob/077efc64e23b051ebff780fd2c05b5113463f74f/README.md?plain=1#L3

**Comment by pmalek** [comment]
This is a note for end users outside of our organisation.

Since ATM we're responsible for https://github.com/Kong/sdk-konnect-go/ we can safely use it and adjust as we go (and import it in KIC).

**Comment by tao12345666333** [comment]
Thanks, got it.

**Comment by tao12345666333** [comment]
I have checked the relevant code and found that @pmalek  has already modified them. Thank you!
Now this issue can be closed.

@czeslavo WDYT? Thanks

**Comment by pmalek** [comment]
All client code has been removed from https://github.com/Kong/kubernetes-ingress-controller/tree/main/internal/konnect/controlplanesconfig and https://github.com/Kong/kubernetes-ingress-controller/tree/main/internal/konnect/controlplanes and replace with usage of sdk-konnect-go.

Closing this, @czeslavo feel free to reopen if you feel there's something missing to address.
