### ISSUE TITLE
Version support matrix can add kubernetes

### ISSUE THREAD

**Issue by xbazhen** [Kong/kubernetes-ingress-controller#356]
I just saw this in readme.md
```
The Ingress controller is tested on Kubernetes version 1.8 through 1.10.
```

I want to now kubernetes-ingress-controller is support Kubernetes version 1.11 1.12 1.13 1.14 1.15？

**Comment by hbagdi** [comment]
Hello @xbazhen,

It seems like the README is out of date.
I'll push a commit up to fix that.

We have tested KIC up to Kubernetes version 1.14 and have not seen issues yet.

**Comment by hbagdi** [comment]
Removed in https://github.com/Kong/kubernetes-ingress-controller/commit/d925c36dd4a5d21f27bbf301faf899708764ef85
