### ISSUE TITLE
Kong Ingress in Azure (AKS)

### ISSUE THREAD

**Issue by Tomelin** [Kong/kubernetes-ingress-controller#3564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm deployment Kong Ingres in Azure and noticed that the LoadBalancer is not create and the status is pending.  I checked and in kong-proxy service has the annotation from AWS but I deployment the kong in Azure.

I not found what the correct annotation should be in the service.

Link I use to deployment Kong ingress in Azure
https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/v2.8.0/deploy/single/all-in-one-dbless.yaml

### Expected Behavior

The Azure LoadBalancer is not create

### Steps To Reproduce

```markdown
1. kubectl create -f https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/v2.8.0/deploy/single/all-in-one-dbless.yaml
2. check the service - kubectl -n kong get service kong-proxy
3. describe the service - kubectl -n kong describe service kong-proxy
4. validate the annotations - kubectl -n kong get service kong-proxy -o jsonpath={.metadata.annotations
```

### Kong Ingress Controller version

```shell
v2.8.0
```

### Kubernetes version

```shell
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"9710807c82740b9799453677c977758becf0acbb", GitTreeState:"clean", BuildDate:"2022-12-13T08:17:45Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1
```

**Comment by Tomelin** [comment]
I change for this annotations and working:

service.beta.kubernetes.io/azure-load-balancer-internal: "true"
service.beta.kubernetes.io/azure-load-balancer-sku: standard

**Comment by pmalek** [comment]
@Tomelin Thanks for your report and for letting us know about the solution.

Since you've arrived that the solution I'm closing this issue for now. Feel free to comment if there's anything else you'd like to have discussed here.
