### ISSUE TITLE
can not sync services and routes from ingress in db mode

### ISSUE THREAD

**Issue by xbazhen** [Kong/kubernetes-ingress-controller#357]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version** 0.5.0

**Kong version**  1.2.0

### Kubernetes version 1.14.1

**Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}**

### Environment

- **Cloud provider or hardware configuration  **: VM
- **OS** : Ubuntu 16.04.5 LTS
- **Kernel** : Linux Pi-k8s-master1-U17 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
- **Others**:

### What happened
I install kubernetes-ingress-controller and kong in my kubernetes cluster，as this document：
[getting-started](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/getting-started.md)

but I found nothing in services api

https://node-ip:admin-api-nodeport/services
{"next":null,"data":[]}
https://node-ip:admin-api-nodeport/routes
{"next":null,"data":[]}

export PROXY_IP='http://10.2.3.34:31014'
curl -i $PROXY_IP/foo
{"message":"no Route matched with those values"}

### Expected behvaior
https://node-ip:admin-api-nodeport/services
have data

### Steps To Reproduce

1. kubernetes 1.14.1
2. helm install kubernetes-ingress-controller 0.5.0 and kong 1.2.0 with db
    helm install stable/kong --set ingressController.enabled=true
3. [getting-started](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/getting-started.md) 
4. access such url
 https://node-ip:admin-api-nodeport/services
 https://node-ip:admin-api-nodeport/routes

**Comment by hbagdi** [comment]
Did you create any Ingress resources as mentioned in the guide?
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/getting-started.md#basic-proxy

**Comment by xbazhen** [comment]
> Did you create the Ingress resources as mentioned in the guide?
> https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/getting-started.md#basic-proxy

Yes I did

```
# history

 1954  echo "
 1955  apiVersion: extensions/v1beta1
 1956  kind: Ingress
 1957  metadata:
 1958    name: demo
 1959  spec:
 1960    rules:
 1961    - http:
 1962        paths:
 1963        - path: /foo
 1964          backend:
 1965            serviceName: echo
 1966            servicePort: 80
 1967  " | kubectl apply -f -
```

```
# kubectl get ing
NAME   HOSTS   ADDRESS     PORTS   AGE
demo   *       10.2.3.33   80      17h
```
```
# kubectl  get ing demo -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["10.2.3.33"],"port":80,"protocol":"HTTP","serviceName":"default:echo","ingressName":"default:demo","path":"/foo","allNodes":false},{"addresses":["10.2.3.33"],"port":443,"protocol":"HTTPS","serviceName":"default:echo","ingressName":"default:demo","path":"/foo","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"demo","namespace":"default"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"echo","servicePort":80},"path":"/foo"}]}}]}}
  creationTimestamp: "2019-08-12T08:23:59Z"
  generation: 1
  name: demo
  namespace: default
  resourceVersion: "51052677"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/demo
  uid: 88e431b6-bcda-11e9-8770-005056b610a7
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: echo
          servicePort: 80
        path: /foo
status:
  loadBalancer:
    ingress:
    - ip: 10.2.3.33
```


here is other info，just info
```
# kubectl get po
NAME                                                 READY   STATUS      RESTARTS   AGE
echo-866464c5d4-6m9vw                                1/1     Running     0          17h
echo-866464c5d4-6v96b                                1/1     Running     0          17h
echo-866464c5d4-8hhcw                                1/1     Running     0          17h
echo-866464c5d4-cq6q8                                1/1     Running     0          17h
ingress-controller-kong-769ff8ffcb-hm498             1/1     Running     0          18h
ingress-controller-kong-controller-f9bd7b84b-zd9cx   2/2     Running     2          18h
ingress-controller-kong-init-migrations-bvwjt        0/1     Completed   0          18h
ingress-controller-postgresql-0                      1/1     Running     0          18h
```

**Comment by hbagdi** [comment]
> export PROXY_IP='http://10.2.3.34:31014'

The LoadBalancer IP for your Ingress is set to `10.2.3.33`. Are you hitting the the correct IP address?

**Comment by balrongs** [comment]
i have the same problem . im hitting in 172.31.30.27:32451 ...  
PROXY_IP=172.31.30.27
PROXY_PORT=32451 
the response
curl --insecure  $PROXY_IP:$HTTP_PORT -H "Host: foo.bar" 
{
  "message": "no Route matched with those values"
}

and this is the ingress 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-trust-kong
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "kong"
    configuration.konghq.com: kong-custom-ingress
spec:
  rules:
    - host: foo.bar
      http:
        paths:
          - path: /
            backend:
              serviceName: http-svc
              servicePort: 80




```
NAME                                                  READY   STATUS      RESTARTS   AGE
pod/http-svc-d6786c9c-45m7r                           1/1     Running     0          5h25m
pod/http-svc-d6786c9c-8fg9s                           1/1     Running     0          5h25m
pod/http-svc-d6786c9c-q8rfp                           1/1     Running     0          5h27m
pod/http-svc-d6786c9c-rpddw                           1/1     Running     0          5h25m
pod/http-svc-d6786c9c-rsgds                           1/1     Running     0          5h25m
pod/wistful-ferret-kong-6c4f8d5cd9-2g6lp              1/1     Running     0          84m
pod/wistful-ferret-kong-controller-5c9d5b89b9-69djh   2/2     Running     2          84m
pod/wistful-ferret-kong-init-migrations-kfffr         0/1     Completed   0          84m
pod/wistful-ferret-postgresql-0                       1/1     Running     0          84m


NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/http-svc                             NodePort    10.100.211.213   <none>        80:32293/TCP                 5h27m
service/kubernetes                           ClusterIP   10.96.0.1        <none>        443/TCP                      39d
service/wistful-ferret-kong-admin            NodePort    10.109.175.50    <none>        8444:31799/TCP               84m
service/wistful-ferret-kong-proxy            NodePort    10.99.201.139    <none>        80:32451/TCP,443:31313/TCP   84m
service/wistful-ferret-postgresql            ClusterIP   10.110.86.2      <none>        5432/TCP                     84m
service/wistful-ferret-postgresql-headless   ClusterIP   None             <none>        5432/TCP                     84m


NAME                                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/http-svc                         5/5     5            5           5h27m
deployment.apps/wistful-ferret-kong              1/1     1            1           84m
deployment.apps/wistful-ferret-kong-controller   1/1     1            1           84m

NAME                                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/http-svc-d6786c9c                           5         5         5       5h27m
replicaset.apps/wistful-ferret-kong-6c4f8d5cd9              1         1         1       84m
replicaset.apps/wistful-ferret-kong-controller-5c9d5b89b9   1         1         1       84m

NAME                                         READY   AGE
statefulset.apps/wistful-ferret-postgresql   1/1     84m


NAME                                            COMPLETIONS   DURATION   AGE
job.batch/wistful-ferret-kong-init-migrations   1/1           23s        84m


Kubernetes master is running at https://172.31.30.27:8443
Heapster is running at https://172.31.30.27:8443/api/v1/namespaces/kube-system/services/heapster/proxy
KubeDNS is running at https://172.31.30.27:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
monitoring-influxdb is running at https://172.31.30.27:8443/api/v1/namespaces/kube-system/services/monitoring-influxdb/proxy


```

**Comment by xbazhen** [comment]
> > export PROXY_IP='http://10.2.3.34:31014'
> 
> The LoadBalancer IP for your Ingress is set to `10.2.3.33`. Are you hitting the the correct IP address?

That not a problem，10.2.3.33 10.2.3.34 both are node of my kubernetes cluster。

**Comment by hbagdi** [comment]
Were you able to solve this problem?
I see that you have other issues that are also open and for those to work you will have to solve this issue first.

**Comment by xbazhen** [comment]
It may be hard for me to solve this problem in this issue.

first, i deploy the kubernetes-ingress-controller in db less mode, but i found the 404 problem,
so i deleted it and deploy the db mode in my kubernetes cluster,   unfortunately, the db mode also not ok in my kubernetes cluster.

the next day, i delele the db mode, and focus on the db-less mode up to now.

**Comment by hbagdi** [comment]
Please re-open this issue if need. Thanks!
