### ISSUE TITLE
Rename "service discovery" / "single controller deployments" to "gateway discovery"

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

https://github.com/Kong/charts/pull/747#discussion_r1108795199 proposed a "gateway discovery" name for the #702 feature.

### Proposed Solution

Conclude the aforementioned [discussion](https://github.com/Kong/charts/pull/747#discussion_r1108795199) from the Helm chart PR and:
- either rename this feature to "gateway discovery" as proposed, or
- drop the proposal

### Acceptance Criteria

- [ ] documentation refers to the SCD feature as _gateway discovery_
- [x] CLI flags refer to the SCD feature as _gateway discovery_
- [x] Helm chart refers to the SCD feature as _gateway discovery_

**Comment by czeslavo** [comment]
As there's no documentation on docs.konghq.com yet, all ACs seem to be satisfied. I've created an issue to track docs separately: https://github.com/Kong/kubernetes-ingress-controller/issues/3604
