### ISSUE TITLE
Enable debug logs for kong ingress controller

### ISSUE THREAD

**Issue by dsnr-pavankumar** [Kong/kubernetes-ingress-controller#3597]
Hi,

Could someone help to enable debug logs for kong ingress controller.
I tried below environment variables to enable debug logs for kong ingress controller, but no luck.

  env:
        - name: controller_log_level
          value: debug
        - name: log_level
          value: debug
        - name: KONG_LOG_LEVEL
          value: debug

Thanks in advance for your help

**Comment by dsnr-pavankumar** [comment]
On defining below for ingress-controller container, debug logs started coming..
- name: LOG_LEVEL
          value: debug
        - name: KONG_LOG_LEVEL
          value: debug
        - name: POD_NAME

**Comment by pmalek** [comment]
I'm not 100% sure why the above would work but what you're looking for is `CONTROLLER_LOG_LEVEL=debug` set in env.
