### ISSUE TITLE
<Feature Request> Helm Chart for Kong Ingress Controller

### ISSUE THREAD

**Issue by shreyaskarnik** [Kong/kubernetes-ingress-controller#36]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

It would be great if there the resources in `deploy` are made available as helm charts for easy deployments to multiple Kubernetes Clusters.

**Comment by perryao** [comment]
wanted to let you guys know I started working on this here: https://github.com/pgalchemy/charts/tree/kong-ingress/incubator/kong-ingress. Thinking it would make sense to get it merged into kubernetes/charts soon. Still WIP, and borrowing heavily from the existing nginx-ingress chart as well as the manifests from here. Haven't had a chance to test rbac yet, but would love some feedback from the kong team before I submit a PR to kubernetes/charts.

**Comment by carpenterm** [comment]
Are there any plans for an official Helm chart for the kong ingress controller?

**Comment by chris-scentregroup** [comment]
I am also interested in this for L7 routing, where kong is basically multi-tenanted based on hostname and possibly URI/href path.

**Comment by merqurio** [comment]
@shreyu86 
Check 
https://github.com/helm/charts/pull/7350
