### ISSUE TITLE
Gateway discovery is documented on docs.konghq.com

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Having #702 shipped in 2.9, we should make sure that the Gateway discovery feature has proper documentation on our official docs site.

### Proposed Solution

- Write a guide-style article explaining how to use the Gateway discovery to make data planes scalable
- Mention the new configuration variant in https://docs.konghq.com/kubernetes-ingress-controller/2.8.x/concepts/deployment/#deployment-options

### Acceptance Criteria

- [x] Guide explaining how to install Kong Gateways and Kong Ingress Controller with Gateway discovery to scale data planes exists 
  - [x] Done via https://github.com/Kong/docs.konghq.com/pull/5231 - merged to [`release/kic-2.9`](https://github.com/Kong/docs.konghq.com/tree/release/kic-2.9)
- [x] The guide is referenced in https://docs.konghq.com/kubernetes-ingress-controller/2.8.x/concepts/deployment/#deployment-options
  - [x] Done via https://github.com/Kong/docs.konghq.com/pull/5231 - merged to [`release/kic-2.9`](https://github.com/Kong/docs.konghq.com/tree/release/kic-2.9)
- [x] Installation guides make the SCD deployment the default
  - [x] Done via https://github.com/Kong/docs.konghq.com/pull/5231 - merged to [`release/kic-2.9`](https://github.com/Kong/docs.konghq.com/tree/release/kic-2.9)
  - [x] Installation guides snippet extracted to a common include https://github.com/Kong/docs.konghq.com/pull/5256
- [x] An explanation of gateway discovery is present in the repo
  - [x] #3664 - This adds a mention about Gateway Discovery
- [x] Descriptions of the DB-less setup are ensured to be not incorrect in the gateway discovery context
- [x] The appropriate "References" are up to date regarding gateway discovery
  - [x] Done via https://github.com/Kong/docs.konghq.com/pull/5231 - merged to [`release/kic-2.9`](https://github.com/Kong/docs.konghq.com/tree/release/kic-2.9)
  - [x] CLI flags references - https://docs.konghq.com/kubernetes-ingress-controller/latest/references/cli-arguments/- have been updated in [`release/kic-2.9`](https://github.com/Kong/docs.konghq.com/tree/release/kic-2.9)

**Comment by pmalek** [comment]
#3664 - This adds a mention about Gateway Discovery. Would we want something more elaborate? Link to a section about GD at docs.konghq.com?

**Comment by pmalek** [comment]
> An explanation of gateway discovery is present in the repo

This has not been added as we don't really maintain in repo docs for our features. If we ever decided that should be added then let's reopen this issue and add that.
