### ISSUE TITLE
When Gateway discovery is enabled and Kong is DB backed, KIC only sends config to one of Kong gateway endpoint

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

In DB-backed deployment of kong gateway,  KIC should only send to one of gateway admin API endpoints, and kong gateway instances could do the synchronization of configuration via DB. So, instead of limiting gateway discvoery/SCD to be used with only DB-less mode (#3401), we could let KIC to send configuration on any one of available gateway clients when gateway discovery is enabled, to enable KIC to work with multiple DB-backed gateway instances. 

### Proposed Solution

- When gateway discovery is enabled, and kong gateway is DB-backed, KIC send kong configurations to only one of gateway clients.

### Acceptance Criteria

- [ ] When kong gateway is DB-backed, and KIC is configured to enable gateway discovery, KIC only sends configuration to one gatewat pod.
- [ ] In the deployment above, all gateway nodes could receive the same configuration.
- [ ] Have an "all-in-one-postgres-multiple-gw.yaml" that could deploy KIC with gateway discovery + kong with postgres DB backend

**Comment by mflendrich** [comment]
Maybe we should instead disallow DB mode gateway if gateway discovery is enabled? (I believe we discussed that option on slack)

**Comment by randmonkey** [comment]
postpone this and do #3401 because we do not want to support gateway discovery with DB-backed gateways in KIC 2.9.

**Comment by mflendrich** [comment]
Closing - we're supporting GD for DB-less only today.

**Comment by mheap** [comment]
@mflendrich Is there a replacement issue to support GD with DB-backed?
