### ISSUE TITLE
How does the kong ingress controller in version 0.7.1 achieve grayscale publishing via request headers?

### ISSUE THREAD

**Issue by xincli** [Kong/kubernetes-ingress-controller#3608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

How can the open source version of kong ingress controller implement forwarding to different services based on user request headers?

**Comment by czeslavo** [comment]
Hey @xincli, according to the [changelog](https://github.com/Kong/kubernetes-ingress-controller/blob/main/CHANGELOG.md#060), KIC v0.6.0 has introduced `KongIngress.Route.Headers`. You can read more about using it in this [guide](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-kongingress-resource/#use-kongingress-with-ingress-resource).

If you decided to upgrade to the latest version of KIC (which I would highly recommend, 0.7.1 is far outdated and no longer supported), up from 2.8.0 you can use a Kubernetes [annotation](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/#konghqcomheaders) to specify header matching rules.

**Comment by xincli** [comment]
@czeslavo I tested kongingress, but found that I can't do regular matching, i.e. how to forward based on the request header when I know part of a field in the request header?

**Comment by czeslavo** [comment]
@xincli you should be able to use regex matching by appending a well-known `~*` prefix to the expected header value. Please take a look at https://docs.konghq.com/gateway/latest/admin-api/#request-body-3 (attributes: headers).

> One or more lists of values indexed by header name that will cause this Route to match if present in the request. The Host header cannot be used with this attribute: hosts should be specified using the hosts attribute. When headers contains only one value and that value starts with the special prefix ~*, the value is interpreted as a regular expression.

**Comment by xincli** [comment]
@czeslavo I have the following configuration, but the regular expressions don't seem to work
![image](https://user-images.githubusercontent.com/58928559/226778709-f65fc4d9-3413-4254-b687-38dcc693c9da.png)
![image](https://user-images.githubusercontent.com/58928559/226778689-279506f0-0723-4ef6-9cf2-9c9a12f82927.png)

**Comment by czeslavo** [comment]
@xincli Could I ask you for providing us with input to make reproduction possible? That would be:
- Kong Gateway version,
- Kong Ingress Controller version,
- the minimal set of YAML manifests that you expect to work (KongIngress, Ingress, etc.),
- actual behavior you're facing,
- expected behavior.

**Comment by xincli** [comment]
@czeslavo Kong Gateway version：2.0.1
Kong Ingress Controller version：0.7.1
Ingress YAML：
<img width="572" alt="image" src="https://user-images.githubusercontent.com/58928559/227573817-2b1bf56a-1a13-4523-88b8-4c43a55df685.png">
KongIngress YAML：
<img width="511" alt="image" src="https://user-images.githubusercontent.com/58928559/227574026-e03ca205-53fd-468d-872d-73ce96c7649b.png">
The devops-httpserver service listens on two ports, where port 8080 is for normal business and port 8090 is for grayscale authentication. After user login, the cookie will contain the character xincli, for example: aaa=bb; cc=dd; username=xincli; xxx=yyy, how do I forward the requests containing the xincli character in the cookie to the grayscale route? The above configuration test is not effective.
![image](https://user-images.githubusercontent.com/58928559/227574225-4f1cf94b-7a68-4c6d-8398-9189ceb5ca25.png)

**Comment by programmer04** [comment]
For the newest KIC, you can route by header
- with [networking.k8s.io/v1 Ingress and annotations](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/routing-by-header/)
- with the usage of [gateway.networking.k8s.io/v1beta1 HTTPRoute](https://gateway-api.sigs.k8s.io/api-types/httproute/#matches), you don't use `Ingress` in such configuration, but other resources read more on [the official website](https://gateway-api.sigs.k8s.io/)

`KongIngress` will be deprecated soon, thus it's better to not use it
