### ISSUE TITLE
GRPCRoute docs

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#3611]
### Problem Statement

The GRPCRoute controller has been recently introduced, and we need to provide basic documentation on using such a new API.

### Acceptance Criteria

- [x] a new section must be added to the Ingress controller documentation to cover the GRPCRoute functionality and provide some examples.

**Comment by mflendrich** [comment]
I think we should also have a guide to GRPCRoute use with Gateway API.

**Comment by mlavacca** [comment]
That is what this issue is about. I'm expanding the current guide we have on GRPC ingress by including the GRPCRoute as well.

**Comment by mlavacca** [comment]
going to be fixed by https://github.com/Kong/docs.konghq.com/pull/5216
