### ISSUE TITLE
Gateway discovery documentation

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3619]
This is about documenting #702.

## Acceptance Criteria
- [ ] Installation guides make the SCD deployment the default
- [ ] An explanation of gateway discovery is present in the repo
- [ ] Descriptions of the DB-less setup are ensured to be not incorrect in the gateway discovery context
- [ ] The appropriate "References" are up to date regarding gateway discovery

**Comment by czeslavo** [comment]
Duplicate: https://github.com/Kong/kubernetes-ingress-controller/issues/3604

**Comment by rainest** [comment]
Copied the AC from here into the other issue.
