### ISSUE TITLE
Telemetry for Gateway API objects

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#3649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Regarding telemetry and Gateway API, currently, the only telemetry data we have is related to the feature (whether it is enabled). Since the Gateway feature gate is now enabled by default, we want to know whether the functionality is actively used. For this reason, we need to add telemetry to the controller to actually know how many Gateway API objects are used. We should add telemetry for:
- `Gateway`
- `HTTPRoute`

additionally, alpha APIs should be monitored:

- `GatewayClass`
- `ReferenceGrant`
- `TCPRoute`
- `UDPRoute`
- `GRPCRoute`
- `TLSRoute`

### Proposed Solution

The controllers should be improved to export telemetry data about the number of Gateway API objects.

### Acceptance Criteria

we export telemetry data for:
- [ ] number of `GatewayClass`es used
- [ ] number of `ReferenceGrant`s used
- [ ] number of `HTTPRoute`s used
- [ ] number of `TCPRoute`s used
- [ ] number of `UDPRoute`s used
- [ ] number of `TLSRoute`s used
- [ ] number of `GRPCRoute`s used

**Comment by pmalek** [comment]
The gateway count is already provided via : https://github.com/Kong/kubernetes-telemetry/blob/main/pkg/provider/k8sgatewayscountprovider.go in https://github.com/Kong/kubernetes-telemetry/blob/main/pkg/telemetry/workflowsk8s.go#L99-L109 which is used in KIC in here https://github.com/Kong/kubernetes-ingress-controller/blob/a8262ed642cf36c0f1bcf5f845daa665a09131fe/internal/manager/telemetry/manager.go#L103-L111.

The others should be relatively easy to implement based on that.
