### ISSUE TITLE
Bit.ly links to manifests on docs.konghq.com point to KIC's main branch

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3650]
Bit.ly links to manifests on docs.konghq.com point to KIC's main branch. They probably shouldn't as main is considered unstable. 

Example: https://docs.konghq.com/gateway/latest/install/kubernetes/kubectl/#deploy 

## Proposed solution:
Change all bitly link to static ones pointing to the appropriate release tag in the repo.

**Comment by pmalek** [comment]
Here's my proposal on how to fix this: https://github.com/Kong/docs.konghq.com/pull/5240
