### ISSUE TITLE
extended conformance - `HTTPRouteQueryParamMatching`

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#3679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Support the `HTTPRouteQueryParamMatching` feature in conformance tests (extended)

### Acceptance Criteria

- [ ] the conformance test `HTTPRouteQueryParamMatching` is successfully ran
- [ ] validation in the admission webhook has to allow such configuration and validate it

**Comment by mflendrich** [comment]
Removed blocker issue - query string matching https://github.com/Kong/kong/pull/11469 is being backported into the nearest 3.4.x releases of Gateway

**Comment by programmer04** [comment]
Surpass old obsolete issue https://github.com/Kong/kubernetes-ingress-controller/issues/2152 too
