### ISSUE TITLE
extended conformance - `HTTPResponseHeaderModification`

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#3683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Support the `HTTPResponseHeaderModification` feature in conformance tests (extended)

### Acceptance Criteria

- [ ] the conformance test `HTTPRouteResponseHeaderModifier` is successfully ran

**Comment by rodman10** [comment]
Can I work on this? Thanks!

**Comment by rodman10** [comment]
Thanks reply ! According to my understanding, I should add an response-transform when a filter of responseHeaderModifier type is parsed, and I am confused that the conformance mentined here is just gateway-api or anything else? It's very possible I'm missing something, thanks for correcting me.

**Comment by mlavacca** [comment]
The conformance test mentioned in the issue is from the Gateway API suite: https://github.com/mlavacca/gateway-api/blob/a4e8bad07dedaf738cce83cb44a4e8641937fade/conformance/tests/httproute-response-header-modifier.go#L33

The final outcome of this issue should be having that test passed. As you can see in our conformance [tests](https://github.com/Kong/kubernetes-ingress-controller/blob/9186bef5e00bdb85e53937d17f0b1dc999d3317f/test/conformance/gateway_conformance_test.go#L107), we are currently skipping it.

For what concerns what needs to be done, we should convert that filter into a kong plugin (as already done for [other](https://github.com/Kong/kubernetes-ingress-controller/blob/5c4d7d552678acf282f63a69e932c8f1c3a894a4/internal/dataplane/parser/translators/httproute.go#L352-L382) filters), but may require an investigation of the problem and changes in other parts of the codebase, it needs to be figured out.

**Comment by rodman10** [comment]
I have tried to implement this extended filter by generate a response-transform plugin with `headers` config, as `requestHeaderModifier` does. After remove the `HTTPRouteResponseHeaderModifier` from skip list, the gateway-api conformance test seems passed, would you like to give me some little hints about the `other parts of the codebase`? Thanks!

**Comment by mlavacca** [comment]
> I have tried to implement this extended filter by generate a response-transform plugin with `headers` config, as `requestHeaderModifier` does. After remove the `HTTPRouteResponseHeaderModifier` from skip list, the gateway-api conformance test seems passed, would you like to give me some little hints about the `other parts of the codebase`? Thanks!

Cool! If you want to publish the PR, it'd be great :) As I said, this issue required a bit of investigation, it may be that we don't need to change anything else than what you already did :)

**Comment by rodman10** [comment]
I have published a [PR](https://github.com/Kong/kubernetes-ingress-controller/pull/4350) for this issue. Thanks!
