### ISSUE TITLE
experimental conformance - `HTTPRouteHostRewrite`

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#3685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Support the `HTTPRouteHostRewrite` feature in conformance tests (experimental)

### Acceptance Criteria

- [ ] the conformance test `HTTPRouteRewriteHost` is successfully ran

**Comment by pmalek** [comment]
`SupportHTTPRouteHostRewrite` has not been enabled yet in the conformance suite.

#6112 adds that and will close this issue.
