### ISSUE TITLE
experimental conformance - `HTTPRoutePathRewrite`

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#3686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Support the `HTTPRoutePathRewrite` feature in conformance tests (experimental)

### Acceptance Criteria

- [x] the conformance test `HTTPRouteRewritePath` is successfully ran

**Comment by pmalek** [comment]
`SupportHTTPRoutePathRewrite` has not been enabled yet in the conformance suite.

#6114 adds that and will close this issue.
