### ISSUE TITLE
Upgrade golang.org/x/net-v0.4.0 to 0.7.0

### ISSUE THREAD

**Issue by akoshok1** [Kong/kubernetes-ingress-controller#3687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Please see https://github.com/advisories/GHSA-vvpx-j8f3-3w6h - need to update dependancy in question.

### Expected Behavior

This should help pass vulnerability scan.

### Steps To Reproduce

```markdown
Scan with Anchore CVE
```

### Kong Ingress Controller version

```shell
2.8.1
```

### Kubernetes version

```shell
NA
```

**Comment by pmalek** [comment]
Thanks for the report! Given that 2.9 is bound to happen in relatively near term future, the fact that we don't tend to release patch releases and that [it's fixed on `main`](https://github.com/Kong/kubernetes-ingress-controller/blob/2c3345786889b236550971d9061cdacef4c1b447/go.mod#L35) I'm inclined to close this.

Is there a real concern there or just a scan result?

Also given that 

```
go mod why -m golang.org/x/net
# golang.org/x/net
github.com/kong/kubernetes-ingress-controller/v2/internal/manager
k8s.io/client-go/rest
golang.org/x/net/http2
```

and the only thing that's being used from `k8s.io/client-go/rest` package in `github.com/kong/kubernetes-ingress-controller/v2/internal/manager` is `*rest.Config`, it doesn't look like a real concern to me.

**Comment by akoshok1** [comment]
Many thanks.  There is no concern for this to wait until 2.9.
