### ISSUE TITLE
Align router defaults with Kong upstream

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#3693]
Kong 3.x uses the `traditional_compatible` router [by default](https://github.com/Kong/kong/blob/3.2.1/kong.conf.default#L1586). The [KIC manifests](https://github.com/Kong/kubernetes-ingress-controller/blob/95292a6f042386952df5ac33dcea21888ac35765/config/base/kong-ingress-dbless.yaml#L74-L75) and [chart](https://github.com/Kong/charts/blob/d4b5309efb5ee571d0202bfb1d0dc59da4813a0a/charts/kong/values.yaml#L91) use `traditional` instead.

The initial 3.x releases had issues where some regular expressions caused serious failures. These failures [are now fixed](https://github.com/Kong/kong/pull/9719): regular expressions incompatible with `traditional_compatible` are still non-functional (unsure actually--looking at the Kong PR we maybe convert them gracefully?), but no longer break the entire router build.

We are not aware of KIC-generated routes that trigger this issue (`Exact` and `Prefix` Ingress rules, and similar rules in HTTPRoute and GRPCRoute, transform resource configuration into a Kong regular expression route for spec compliance). We only expect that user-provided regular expressions can hit the problem behavior.

Given our current understanding of the initial issues and subsequent fixes, we should be able to remove our router flavor override.

Acceptance:

- [ ] The chart and KIC manifests do not override `KONG_ROUTER_FLAVOR`, and use the upstream default (`traditional_compatible`).
- [ ] Test harnesses do not override the router flavor and use the upstream default.
- [ ] KIC-generated regex routes work when the Kong instance uses the default `traditional_compatible` router flavor.
- [ ] Documentation covers which user-provided regular expressions will break with `traditional_compatible` and how to rewrite them for use with the new router.

Per the unsure point above, we need a small spike to confirm if users actually need to change anything for Kong 3.1+. It may be the case that 3.1+ handle "incorrect" regular expressions gracefully and route them as expected, rather than rejecting them. If so, we probably only need a changelog note indicating 3.0.x errata, and that users that do not want to upgrade past gateway 3.0.x should add the override to `traditional` back (probably only in the chart, since the static manifests have no expectations of support for Kong versions other than the version in the static manifest).

**Comment by rainest** [comment]
Tentative breaking label, but if the problem regexes from FTI-4444 "just work" in 3.1+, this is non-breaking and only requires a 3.0.x errata mention in the changelog.

**Comment by mheap** [comment]
If we're considering KIC 3.0 in the coming months, I'd recommend holding off on the change to `traditional_compatible` until then. There is a small risk of breakage, but a major version bump is a good indicator to be more careful

**Comment by rainest** [comment]
To clarify, there was more serious breakage (the entire router build would fail) when 3.x was initially released, and that prompted using `traditional` because KIC doesn't generate expression routes anyway, so may as well be conservative. To the best of our knowledge, that serious issue has been addressed, and we don't expect new serious issues.

In particular, we don't expect that anything KIC produces will break. User-supplied problem regexes have the same works/doesn't work characteristics as they would without KIC. We're not really making a breaking change, we're walking back an earlier aggressive mitigation for breaking changes elsewhere.

**Comment by mheap** [comment]
Understood. My personal preference would be to hold this until 3.0 unless people are pushing for better router performance regularly

**Comment by mflendrich** [comment]
This is mutually exclusive with #4718. Marking "blocked" until we decide one way or the other.

**Comment by rainest** [comment]
I think the above is supposed to refer to https://github.com/Kong/kubernetes-ingress-controller/issues/4719 ?

Either way, whatever, the places we need to touch are going to be the same, so whichever we end up using, we can modify the replacement string in the diff.

Files that interact with `KONG_ROUTER_FLAVOR` that I skipped:
`test/e2e/compatibilities_test.go` uses router flavors but is explicitly about testing different varieties, so leaving that as-is.
`test/internal/testenv/testenv.go` just validates that a given router flavor is one of the available choices.
`test/kongintegration/containers/kong.go` is already set to `expressions`

Integration tests in CI set `TEST_KONG_ROUTER_FLAVOR` explicitly, but runs without that locally will use the chart defaults. If we update the chart defaults also, runs that do not specify the router will use the new value when that's released.

**Comment by mflendrich** [comment]
Handled in https://github.com/Kong/kubernetes-ingress-controller/issues/4719
