### ISSUE TITLE
Docs: How to migrate Ingresses to GW API Routes

### ISSUE THREAD

**Issue by rspurgeon** [Kong/kubernetes-ingress-controller#3701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Users of KIC will soon desire to migrate from Ingress API to the new Gateway API. It's currently unclear what steps will be required for users to navigate this migration and what features will KIC provide to assist.

### Proposed Solution

- Build a strategy document describing how users can successfully make this migration

### Additional information

- The list of covered aspects remains open - TBD what the migration guide might need further

### Acceptance Criteria

- [ ] As an established user of KIC's Ingress API, there is a `docs.konghq.com` document I can follow to migrate my setup to Gateway API
- [ ] The migration guide covers zero-downtime
- [ ] The migration guide covers migration of plugins

**Comment by mflendrich** [comment]
@mlavacca mind assigning yourself? I think this is what you're doing with ingress2gateway

**Comment by mlavacca** [comment]
Closing as completed by https://github.com/Kong/docs.konghq.com/pull/6239
