### ISSUE TITLE
Gateway API conformance `HTTPRouteHeaderMatching` case

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

#3673 took care of all Gateway API 0.6.1 core conformance tests except for `HTTPRouteHeaderMatching`.

The reason is that `HTTPRouteHeaderMatching` requires alphabetical sort as the ultimate tie-breaking logic (for the sake of determinism in this very unlikely production-useful case).

This issue tracks the Gateway API conformance effort to implement that tie-breaking logic as expected by the `HTTPRouteHeaderMatching` test.

### Proposed Solution

When the expression router (#3730) is available in KIC, ensure that routes generated by KIC explicitly specify the priority in the order as expected by the Gateway API standard.

### Acceptance Criteria

- [ ] The `HTTPRouteHeaderMatching` test passes
- [ ] The `HTTPRouteHeaderMatching` test is no longer disabled in the conformance test suite

**Comment by randmonkey** [comment]
This is enabled now for expression router. However, with Kong's traditional or traditional compatible router, we could not support the precedence, so we could not enable it for traditional/traditional_compatible routers.
Closed this.
