### ISSUE TITLE
Run e2e tests against manifests on bit.ly 

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#3761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We have upgraded our default manifests in master, which is then uploaded to bitly before we release 2.9.0. But our e2e tests runs tests against the latest code, so that the incompatibilities between the config inside the manifest and the latest released version. So that we need a workflow to run e2e tests against manifests on bit.ly to confirm that we can use it to deploy a working KIC. 

### Proposed Solution

- Run a daily e2e against manifests downloadable on e2e, without any changes on configurations and images.

### Acceptance Criteria

- [ ] Have a workflow that runs e2e daily against all manifests downloadable on e2e to guarantee that the manifests are able to deploy a working KIC.

**Comment by mflendrich** [comment]
> which is then uploaded to bitly

Minor clarification - no _upload to bit.ly happens_ ever - bit.ly simply redirects to the newest deploy/single/all-in-one-dbless.yaml file in the main branch.

> we need a workflow to run e2e tests against manifests on bit.ly

We might want to test the manifests in the `deploy/single` directory instead.

**Comment by rainest** [comment]
Where did we get that we weren't using the stock manifests? The path to load them is:

https://github.com/Kong/kubernetes-ingress-controller/blob/924ea38984c93bce2781f27e313eb19e8f22a8f5/test/e2e/all_in_one_test.go#L39-L51

https://github.com/Kong/kubernetes-ingress-controller/blob/924ea38984c93bce2781f27e313eb19e8f22a8f5/test/e2e/utils_test.go#L117

https://github.com/Kong/kubernetes-ingress-controller/blob/924ea38984c93bce2781f27e313eb19e8f22a8f5/test/e2e/utils_test.go#L173-L190

The override only fires if you provide an image, and that `ci` image should only show up on the targeted tests. The tests that run nightly use the latest nightly image: https://github.com/Kong/kubernetes-ingress-controller/blob/88fd1c2ba15462dee9a106feec53b4f9c7ecbf6e/.github/workflows/e2e_nightly.yaml#L13

The release tests do technically override, but to the release version: https://github.com/Kong/kubernetes-ingress-controller/blob/88fd1c2ba15462dee9a106feec53b4f9c7ecbf6e/.github/workflows/release.yaml#L163

**Comment by programmer04** [comment]
We don't have bit.ly links anymore, moreover [e2e tests are run every night](https://github.com/Kong/kubernetes-ingress-controller/actions/workflows/e2e_nightly.yaml)
