### ISSUE TITLE
Do not use bit.ly links pointing to master/main branch in docs

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As we've [fixed](https://github.com/Kong/docs.konghq.com/pull/5240) the issue with bit.ly links pointing to master/main branch for KIC deployment all-in-one manifests, we still have some bit.ly links in the docs that we have no control over and they do point to KIC's main branch. The links are:

- https://bit.ly/install-kong-admission-webhook 
- https://bit.ly/k8s-httpbin
- https://bit.ly/grpcbin-service

Docs repository: https://github.com/Kong/docs.konghq.com

### Proposed Solution

Replace all mentioned bit.ly links with ones that point to a specific tag (could be done in a similar fashion to https://github.com/Kong/docs.konghq.com/pull/5240 where we use `v{{site.data.kong_latest_KIC.version}}` to get the latest KIC version to build a link).

### Acceptance Criteria

- [ ] KIC docs on docs.konghq.com do not include any bit.ly link that points to github.com/kong/kubernetes-ingress-controller's main or master branch

**Comment by Abhicodeitout** [comment]
@czeslavo  pull request will be raised in  https://github.com/Kong/docs.konghq.com  right

**Comment by czeslavo** [comment]
@Abhicodeitout yup, I just created the issue here because it's directly related to KIC itself.
