### ISSUE TITLE
IngressV1 with CombinedRoutes can create too many Kong Services

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#3777]
## Problem statement 

When two `netv1.Ingress`es use the same `Service` as their backends and `CombinedRotues` feature flag is on, it results in KIC parser creating two Kong Services, one per each Ingress, while it should create just one.

## Proposed solution

Change the Kong Service naming/caching pattern to not include the Ingress name.

## Acceptance criteria
- [x] When `CombinedRoutes=true` and multiple `netv1.Ingress`es point to a single backend `Service`, only one Kong Service gets created.

**Comment by pmalek** [comment]
Can we ensure that as part of this task we also add docs to https://docs.konghq.com/kubernetes-ingress-controller/latest/references/feature-gates/ ?

**Comment by czeslavo** [comment]
> Can we ensure that as part of this task we also add docs to https://docs.konghq.com/kubernetes-ingress-controller/latest/references/feature-gates/ ?

Yes, good point: https://github.com/Kong/docs.konghq.com/pull/5542
