### ISSUE TITLE
How to add NGINX 3rd Party Modules in kong?

### ISSUE THREAD

**Issue by HefeiJoe** [Kong/kubernetes-ingress-controller#380]
Ingress or openresty can add a module this way:
./configure --add-module=path/to/nginx_upload_module
![image](https://user-images.githubusercontent.com/27885579/64218320-b9bc2200-cef3-11e9-8e05-23cd768e3081.png)

But configure is not found in the kubernetes-ingress-controller
![image](https://user-images.githubusercontent.com/27885579/64218240-73ff5980-cef3-11e9-9138-afad39ec04f6.png)
![image](https://user-images.githubusercontent.com/27885579/64218284-9c875380-cef3-11e9-99f6-fccb41b39617.png)

**Comment by hbagdi** [comment]
You will need to use https://github.com/kong/openresty-build-tools to build a valid OpenResty that is usable by Kong and then install that.
