### ISSUE TITLE
Ingress controller reads only head of list of EndpointSlices

### ISSUE THREAD

**Issue by seh** [Kong/kubernetes-ingress-controller#3815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As noted in [my review of PR 3509](https://github.com/Kong/kubernetes-ingress-controller/pull/3509/files#r1149782341), when the ingress controller tries to read multiple pages of _EndpointSlices_ from the API server ([not using the controller's cache](https://sourcegraph.com/github.com/Kong/kubernetes-ingress-controller@1dca7d17da936742c03158e4b27a20a37ddc1884/-/blob/internal/manager/config.go?L292) yet at that point), if the `List` call reports that it has returned only a subset of the available items, we fail to request the remaining items on the next `List` call, such that we'll keep reading only the head of a longer list.

### Expected Behavior

When the API server indicates that it only returned a subset of the available _EndpointSlice_ objects, Kong should read following subsets repeatedly, and stop reading only once it's read all of the available objects.

Instead, Kong will read the same head of the list repeatedly until there are few enough such objects that the API server returns all of them in a single `List` call.

### Steps To Reproduce

1. Create at least 100,001 Kong proxy pods.
1. Create an ingress controller pod.
1. Inspect the proxy pods mentioned late in the _EndpointSlice_ list to see whether they're programmed by the ingress controller.

### Kong Ingress Controller version

_2.9.0_

### Kubernetes version

```
Server Version: version.Info{
  Major:"1",
  Minor:"25",
  GitVersion:"v1.25.7",
  GitCommit:"723bcdb232300aaf5e147ff19b4df7ec8a20278d",
  GitTreeState:"clean",
  BuildDate:"2023-02-22T13:58:23Z",
  GoVersion:"go1.19.6",
  Compiler:"gc",
  Platform:"linux/amd64"
}
```

### Anything else?

Per the documentation, [an _EndpointSlice_ can report as many as 1,000 `Endpoint`s](https://github.com/kubernetes/api/blob/ec59454f24f514bb472628bc0a5c8c9125218dbc/discovery/v1/types.go#L46-L47), but it is allowed to report fewer. The ingress controller requests [no more than 100 _EndpointSlices_ at a time](https://sourcegraph.com/github.com/Kong/kubernetes-ingress-controller@1dca7d17da936742c03158e4b27a20a37ddc1884/-/blob/internal/adminapi/endpoints.go?L31). That means that a single `List` call can return no more than _100 × 1,000 = 100,000_ `Endpoint`s, with one per proxy pod. This is a large number, but the 1,000-`Endpoint`s-per-call estimate may not hold.

That means that this defect is unlikely to afflict users, but it's a logic defect nonetheless, and we should correct it. I suspect that the change we need is to add the following to the `internal/adminapi.GetAdminAPIsForService` function:
```go
		if endpointsList.Continue == "" {
			break
		}
		// New statement:
		continueToken = endpointsList.Continue
```
Alternately:
```go
		// New statement:
		continueToken = endpointsList.Continue
		if continueToken == "" {
			break
		}
```

**Comment by pmalek** [comment]
Good catch @seh! Thanks!

#3846 should fix this.
