### ISSUE TITLE
http2 support for rest apis in community kong api gateway

### ISSUE THREAD

**Issue by ankitec98** [Kong/kubernetes-ingress-controller#3839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, Currently from our golang based client application is calling rest apis to server app. server app is using kong proxy for routing external APIs.  when we enabled http2 in golang ,but in response header we are still seeing http 1.1. is there any open issue with http2 in kong api? is this because upstream service? 

### Expected Behavior

we want http 2 in response header , to ensure communication indeed is happening over http2.

### Kong Ingress Controller version

```shell
2.8.9
```

### Kubernetes version

```shell
1.23
```

**Comment by pmalek** [comment]
Hi @ankitec98 👋 

Can you be a bit more specific? I believe you're talking about the Kong Gateway itself (not sure what aspect of it though).

If that's the case I suggest you file an issue at https://github.com/Kong/kong. I'll leave this issue open so that you can respond.

**Comment by ankitec98** [comment]
Sure, i thought it is issue with controller, as Kong document refers it supports http 2.0. if thats case i will open an issue with Kong,.thanks.

**Comment by pmalek** [comment]
No problem. Please note that you've specified the version of KIC as 2.8.9 which does not exist. Additionally, Gateway didn't release such a version either: https://github.com/Kong/kong/releases. 🤔 

> i will open an issue with Kong,.thanks.

I'm going to close this issue for now. Feel free to reach out if you need any help.
