### ISSUE TITLE
Feature request: gRPC Ingress support

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#387]
Kong 1.3 ships with gRPC routing capabilities.
Kong Ingress Controller should be able to route gRPC traffic.
Ingress or another new API will be needed to define gRPC routing in a declarative fashion.

**Comment by ThWoywod** [comment]
That would be a great extension! 👍

**Comment by hbagdi** [comment]
This is in master now via #454 and set to be released in 0.7.0.

**Comment by email2liyang** [comment]
this is an exciting feature of Kong Ingress to support grpc, when will version 0.7.0 is there any document to follow to enable grpc support for Kong Ingress?

**Comment by hbagdi** [comment]
@email2liyang The current target date for 0.7 is the week of January 6th.
You can access the gRPC guide here: https://github.com/Kong/kubernetes-ingress-controller/blob/4fec266da471e8d87fc2c89a09f60fcd6eb055b6/docs/guides/using-ingress-with-grpc.md

**Comment by email2liyang** [comment]
@hbagdi thanks, this is really cool, do we have the same setup over SSL? like https for grpcs? it will be good to have such information in the guide, I think lots of people wants to expose their api over SSL

e.g: only need to have a tls section in the ingress yaml file?

```
spec:
  tls:
  - hosts:
    - xxxxx.com
    secretName: xxx-tls
```

**Comment by email2liyang** [comment]
sorry another question, we are running on kong 1.2 and kong ingress 0.5.0, is there guide to upgrade Kong and kong ingress to latest version for production env. I know there is a upgrade guide  for stand alone kong https://docs.konghq.com/1.4.x/upgrading/, but could not find out anything for kong in k8s

**Comment by hbagdi** [comment]
> do we have the same setup over SSL? like https for grpcs?

Yes.

> it will be good to have such information in the guide

PRs welcome to update the docs.

> sorry another question, we are running on kong 1.2 and kong ingress 0.5.0, is there guide to upgrade Kong and kong ingress to latest version for production env.

That is on the my mind to write up but haven't found the bandwidth for it. For now, follow Kong's upgrade guide, and read this repository's changelog.
