### ISSUE TITLE
readyz endpoint regularly takes 3-5 seconds to return

### ISSUE THREAD

**Issue by kinghrothgar** [Kong/kubernetes-ingress-controller#3876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just upgraded from 2.2.X to 2.7.X and the readyz endpoint started timing out. We are running in dbless mode and running 2.8.2 of the gateway. We had the timeout set to 1s and after upgrade readyz often takes 3-5s to respond. I dug into the code and I believe what is going on is that while the controller is syncing the config to Kong, the readyz endpoint is blocked waiting for an RLock:

https://github.com/Kong/kubernetes-ingress-controller/pull/1720/files#diff-8169828fcd89fdef2c5714568e2c034c3334249d4b7e41223ea1ccb85f8251fdR169

The controller usually takes about 4s to sync the config (gathered from the prometheus metrics) to the gateway container and seems to do this in a tight loop. As soon as it finished a sync it seems to immediately start a new sync. I'm not sure if that is intended or if the config updates should be event driven and not happening constantly:
```
time="2023-04-11T18:41:15Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:41:20Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:41:25Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:41:30Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:41:35Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:41:40Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:41:45Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:41:50Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:41:55Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:42:00Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:42:05Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:42:10Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:42:15Z" level=info msg="successfully synced configuration to kong."
time="2023-04-11T18:42:20Z" level=info msg="successfully synced configuration to kong."
```

A readiness endpoint that regularly takes this long to respond in my opinion is problematic. If a service is taking 5s to tell me it's healthy, to me that implies there's something wrong / it's overloaded. From reading through the code if I'm following it correctly, waiting on the lock only protects from a stale read in only one case, when the server is shutting down:

https://github.com/Kong/kubernetes-ingress-controller/blob/ac4d48b70b137bc37a9b4c74d79885037776c5e4/internal/dataplane/synchronizer.go#L158

In my opinion, a readiness endpoint that responds promptly regularly is more important that the above condition.

### Expected Behavior

The readiness endpoint to respond promptly when kong is in a healthy state.

### Steps To Reproduce

```markdown
1. Run a version of ingress controller that has this commit https://github.com/Kong/kubernetes-ingress-controller/pull/1720/files#diff-8169828fcd89fdef2c5714568e2c034c3334249d4b7e41223ea1ccb85f8251fdR169 (we're using 2.7.X)
2. Have a config that is complex enough that syncing to the gateway takes several seconds
3. Hit the readyz endpoint in a loop
```

### Kong Ingress Controller version

```shell
2.7.0
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.12-dispatcher", GitCommit:"16927ebb4e9056330d797f5b7a2051ba73af1200", GitTreeState:"clean", BuildDate:"2023-03-19T06:09:26Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10-gke.2300", GitCommit:"1d7ae0799b40b0cd95502e3a5e698db62572e341", GitTreeState:"clean", BuildDate:"2023-02-22T09:28:49Z", GoVersion:"go1.19.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rainest** [comment]
Ultimately we intend to get rid of the hack where the controller is de facto responsible for reporting the gateway's readiness by having the gateway report its own readiness, via https://github.com/Kong/kong/pull/10610/files

The controller readyz should indeed not hang unless it actually hasn't provided a config to the gateway container (that doesn't seem to be the case here), but that should become a moot point once the gateway can report readiness independently. However, this may be a concern for LTS support.

**Comment by kinghrothgar** [comment]
Will test it out!
