### ISSUE TITLE
Duplicate upstream config in KongIngress CRD

### ISSUE THREAD

**Issue by suankan** [Kong/kubernetes-ingress-controller#398]
Below are duplicated items in yaml:

https://github.com/Kong/kubernetes-ingress-controller/blob/922ae26bd00bbde2977d565f3ee5cb482019301a/deploy/manifests/custom-types.yaml#L145
https://github.com/Kong/kubernetes-ingress-controller/blob/922ae26bd00bbde2977d565f3ee5cb482019301a/deploy/manifests/custom-types.yaml#L191

I'm tracking KIC CRDs in my repo and my `yamllint` checker picked it up.

**Comment by hbagdi** [comment]
Indeed, thanks for the issue.

It seems like this has been fixed in the `master` branch since then:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/manifests/base/custom-types.yaml

Does that solve your problem?

**Comment by suankan** [comment]
Hi @hbagdi,

Yeah I see its fixed in master.
In my case, when I using KIC 0.5.0 I've taken CRDs from your tagged version 0.5.0 and locally removed redundant duplicate `upstream`.
