### ISSUE TITLE
Bump to Gateway API 0.7.0

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Gateway API 0.7.0-rc2 is out as of now. 0.7 GA is expected next week.

Per @randmonkey there are no significant API changes, only updates to conformance tests.

### Proposed Solution

Consider bumping Gateway API to 0.7 in KIC

### Acceptance Criteria

- [ ] KIC uses Gateway API 0.7.0

**Comment by pmalek** [comment]
We still have this to do: https://github.com/Kong/kubernetes-ingress-controller/issues/2953.

Do we want to try 0.7 and jump over 0.6.2?
