### ISSUE TITLE
Automation for ingress to gateway API migration

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#3994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Design and build KIC features which help users successfully migrate APIs from Ingress to Gateway API.

This should include at least `Ingress`, `TCPIngress`, `UDPIngress`.

### Proposed Solution

There is a translation project in the works: https://github.com/kubernetes-sigs/ingress2gateway that we can possibly use.

We are considering two options
- connect directly to Kubernetes API and read the Ingress objects from e.g. a specific namespace
- read from YAML files

### Additional information

This supports #3701

### Acceptance Criteria

- [ ] As an established Ingress API user, I can use a tool that will take my Ingress API definitions and convert them into equivalent Gateway API definitions.

**Comment by programmer04** [comment]
Related, older issue
- https://github.com/Kong/kubernetes-ingress-controller/issues/3701

**Comment by randmonkey** [comment]
move future works to https://github.com/kubernetes-sigs/ingress2gateway
