### ISSUE TITLE
Docs: Deployment Methods documentation mentions the Konnect integration with a diagram

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4002]
### Problem statement

With the introduction of integration with Konnect we should add more documentation about it to clearly show users how it works.

One such missing piece that could be added is a diagram of KIC-Konnect integration.

### Acceptance criteria

- [ ] [Deployment Methods documentation](https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/deployment/) mentions the Konnect integration with a diagram

**Comment by czeslavo** [comment]
Done in https://github.com/Kong/docs.konghq.com/pull/5636.
