### ISSUE TITLE
Traffic routed to incorrect pods

### ISSUE THREAD

**Issue by inglemr** [Kong/kubernetes-ingress-controller#403]
### Summary

We have been using Kong Ingress Controller for about a year now but in the last 2-3 months have been running into issues with Kong pointing traffic to the wrong pods. We believe this has to do with how the Kong Ingress Controller caches ips based off what the Kubernetes Service object is targeting rather than sending traffic through the service object itself. 

Also to give additional context we autoscale most of workloads based off of load on the cluster and other application based metrics meaning that we have applications that can easily scale between 10-50 pods at any point in time. 

In the case of today however we were doing a full cluster rotation of about 20 nodes which resulted in about 30 pods being routed to incorrectly based on the rules that were pushed into the Kong database. 

Below you can see an example where traffic is being sent to a pod called "filebeat" that has no ingress or svc object attached to it and is also in another namespace outside of another service called "workflow". If notice in the attached screenshot the IP for filebeat is "100.126.128.2" and kong API is returning that ip as a valid upstream for the workflow svc. 

<img width="1435" alt="Screen Shot 2019-09-16 at 6 54 29 PM" src="https://user-images.githubusercontent.com/10470446/64998824-a2961080-d8b3-11e9-9e09-843277813c02.png">

We even have a few more extreme examples where an internal database hosted on Kubernetes is being pointed at from a completely unrelated service in an entirely different namespace.

In our cluster we have:
178 Svc objects
114 ingress objects
574 pods ( note this does scale up and down due to autoscaling)
246 deployments

If any other information is needed let me know.

**Kong Ingress controller version**
0.5.0

**Kong or Kong Enterprise version**
 1.2.1

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:52:43Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
### Environment

- **Cloud provider or hardware configuration**:
AWS
- **OS** (e.g. from /etc/os-release):
Container Linux by CoreOS 2191.5.0 (Rhyolite
- **Kernel** (e.g. `uname -a`):
 4.19.68-coreos
- **Install tools**:
- **Others**:

I also route this rudimentary ruby script that we used to identify pods that were being routed to from an invalid source. Keep in mind this is slightly geared toward the way we manage our pods/svc and handle routing based on API/UI svcs but should still be usable with some slight modification. In this case I was curating a list of kubectl delete commands since deleting the pods would sometimes resolve the issue since I assume a hook was being detected by Kong to refresh the IP cache it stored. Recently however this has not been working.

```
require 'httparty'
require 'kubeclient'

#kong admin api
@admin_api = "http://localhost:8444"

@kube_api = "https://kubeapi"
@kube_auth_options = { bearer_token: 'xx'}

ssl_options = { verify_ssl: OpenSSL::SSL::VERIFY_NONE }
@client = Kubeclient::Client.new(
  "#{@kube_api}/api/", 'v1', ssl_options: ssl_options, auth_options: @kube_auth_options
)

def get_upstreams
  upstreams = {}
  
  response = JSON.parse(HTTParty.get("#{@admin_api}/upstreams").body)
  loop do
    response["data"].each do |upstream|
      upstreams[upstream["id"]] = upstream
    end
    
    if response["next"]
      response = JSON.parse(HTTParty.get("#{@admin_api}#{response["next"]}").body)
    else
      break
    end      
   end
   return upstreams
end

def get_upstream_targets(id)
  routes = []
  response = JSON.parse(HTTParty.get("#{@admin_api}/upstreams/#{id}/targets").body)
  response["data"].each do |target|
    routes << target["target"] 
  end
  return routes
end



def get_pods_to_delete_by_ips(ips)
  pods = @client.get_pods()
  pod_list = {}
  pods.each do |pod|
    pod_list[pod.metadata.namespace]||= []
    pod_list[pod.metadata.namespace] << {"name" => pod.metadata.name, "ip" => pod.status.podIP }if ips.include?(pod.status.podIP)
  end
  return pod_list
end


def create_delete_commands(pod_list)
  puts "Run the below commands"
  pod_list.each do |key, data|
    if data.size > 0
      puts "kubectl delete pod  -n #{key} #{data.map{|pod| pod["name"]}.join(" ")}"
    end
  end
end


upstreams = get_upstreams

bad_ips = []
upstreams.each do |key, upstream|
  type = nil
  type = "api" if upstream["name"].include?("api")
  type = "web" if upstream["name"].include?("web")
  if !type 
    puts "Skipping no type in #{upstream["name"]}"
    next
  end
  targets = get_upstream_targets(upstream["id"])
  upstreams[key]["targets"] = targets
  pods = @client.get_pods(namespace: upstream["name"].split(".")[0-2],label_selector: "type=#{type}")
  pod_ips = []
  pods.each do |pod|
    pod_ips << pod.status.podIP
  end
  targets.each do |target_ip|
    puts "[#{upstream["name"]}] Checking if #{target_ip} is in #{pod_ips}"
    if !pod_ips.include?(target_ip.split(":").first)
      puts "-> #{target_ip.split(":").first} not in list of ips for #{upstream["name"]}"
      bad_ips << target_ip.split(":").first
    end
  end
end


create_delete_commands(get_pods_to_delete_by_ips(bad_ips))
```

**Comment by tmedford** [comment]
We consider this a major design flaw in kong and are looking to move off kong ingress given its unpredictability.

**Comment by hbagdi** [comment]
I'm sorry to hear about these issues that you are encountering but this is the first report of the issue. We would like to get down the root cause and address it as soon as possible.

> We believe this has to do with how the Kong Ingress Controller caches ips based off what the Kubernetes Service object is targeting rather than sending traffic through the service object itself.

Kong Ingress Controller doesn't perform any caching but the underlying `client-go` library does it. It seems unlikely that this would be the case though.

If an IP re-assignment happens, meaning k8s re-assigns an IP address from one pod to another, there possibly could be a brief period (time it takes the change to propagate the change to all Kong nodes), where there could be an overlap, but that's probably not what we are seeing here.

Is this reproducible?
Would it possible to record the output `kubectl get endpoints <svc-name>` when this does occur to ensure that k8s endpoints and service definitions are in correct sync?

Also please note that Kong Ingress Controller 0.6 (being released today/tomorrow), brings in support for an annotation (`ingress.kubernetes.io/service-upstream`) on the service resource, which can be used to route traffic directly to Kubernetes Service IP and then kube-proxy performs the load balancing by routing the traffic to the correct pod.

**Comment by inglemr** [comment]
Its only reproducible when we have a large influx of pods being recreated. We were eventually able to make it stabilize yesterday by dropping the Kong database and allowing the ingress controller to rebuild completely from scratch. 

When we run into this problem again I'll run the given command and provide the output. I'll add that we don't see this in our smaller dev clusters so this could just be an issue of the size of our cluster? In saying that we will attempt to reproduce in that environment.

Thank you for the update on the 0.6 controller will do some testing and see if that solves our problem in the larger clusters.

**Comment by stratdes** [comment]
I am having the same issue on a preemptible GKE cluster when a node is destroyed and created again.

**Comment by hbagdi** [comment]
This seems like an instance of https://github.com/Kong/kong/issues/4846.

@inglemr Could you try out Kong 1.4rc1 to verify if that fixes the problems in your deployment?

**Comment by hbagdi** [comment]
It seems like this was a bug in Kong itself where the history of the upstream was not correctly processed: https://github.com/Kong/kong/pull/5318

Please upgrade to Kong 1.4.2.
Please re-open if the issue persists.

**Comment by BaloMueller** [comment]
I'm running Kong 1.5.1 and this problem persists.

**Comment by pahnd** [comment]
I am having the same issue on kong/kubernetes-ingress-controller:2.9 when I have a large pods being recreated. Is there any way to configure attaching to a service, instead of  attach to a pod ?
