### ISSUE TITLE
Test Request: Kong Gateway [OSS|EE] version 2.8.4.1-rc2

### ISSUE THREAD

**Issue by VicYP** [Kong/kubernetes-ingress-controller#4062]
### What component needs testing with KIC?

Other

### Container image

kong/kong-gateway-internal:2.8.4.1-rc2-alpine

**Comment by pmalek** [comment]
Triggered with kong/kong-gateway-dev:2.8.4.1-rc3 as indicated by @VicYP in DM.

**Comment by pmalek** [comment]
As discussed elsewhere and covered in #4657 the validation workflow currently fails for 2.8.x.

Closing until #4657 is resolved.
