### ISSUE TITLE
GKE: Using pod dns names doesn't work on GKE which breaks Gateway Discovery

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

#4044 introduced a change that for Gateway discovery produces IP DNS names instead of IPs.

So instead of `http://10.0.0.1:8444` now we create `https://10-0-0-1.kong-admin-svc-name.kong-namespace-name.svc:8444`.

This doesn't work on GKE which instead of `coredns` uses `kube-dns`:

```
/ # dig kong-admin.kong.svc.cluster.local

; <<>> DiG 9.18.14 <<>> kong-admin.kong.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20568
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;kong-admin.kong.svc.cluster.local. IN  A

;; ANSWER SECTION:
kong-admin.kong.svc.cluster.local. 30 IN A      10.37.72.13
kong-admin.kong.svc.cluster.local. 30 IN A      10.37.72.14

;; Query time: 1 msec
;; SERVER: 10.37.70.234#53(10.37.70.234) (UDP)
;; WHEN: Tue May 23 20:20:16 UTC 2023
;; MSG SIZE  rcvd: 83

/ # dig 10-37-72-13.kong-admin.kong.svc.cluster.local

; <<>> DiG 9.18.14 <<>> 10-37-72-13.kong-admin.kong.svc.cluster.local
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 41444
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;10-37-72-13.kong-admin.kong.svc.cluster.local. IN A

;; AUTHORITY SECTION:
cluster.local.          60      IN      SOA     ns.dns.cluster.local. hostmaster.cluster.local. 1684872000 28800 7200 604800 60

;; Query time: 0 msec
;; SERVER: 10.37.70.234#53(10.37.70.234) (UDP)
;; WHEN: Tue May 23 20:20:22 UTC 2023
;; MSG SIZE  rcvd: 156
```

### Expected Behavior

GD works on GKE.

### Kong Ingress Controller version

```shell
57e9e08a22ee34372759a6e6ee7e5c25052ce2aa
```

### Anything else?

Possibly related issue which talks about lack of EndpointSlice support in kube-dns: https://github.com/kubernetes/kubernetes/issues/107742

**Comment by pmalek** [comment]
Just checked on GKE `v1.26.4-gke.500` with kube-dns and I can see both `Endpoints` and `EndpointSlice`s for all services endpoints. So it's not about the lack of support for `EndpointSlices` in kube-dns but rather about it not providing DNS names for Pod DNS names.

Also it seems that kube-dns doesn't return the A records for each hostname under a service as per the spec at https://github.com/kubernetes/dns/blob/master/docs/specification.md#241---aaaaa-records

```
/ # dig +noall +answer proxy-kong-5488cb7d9c-mxbl6.kong-admin.kong.svc.cluster.local
# should return 10.12.56.10 🤔 
/ # dig +noall +answer kong-admin.kong.svc.cluster.local
kong-admin.kong.svc.cluster.local. 30 IN A      10.12.56.10
kong-admin.kong.svc.cluster.local. 30 IN A      10.12.56.9

```

**Comment by pmalek** [comment]
Service scoped, Pod DNS names are not provided by kube-dns but namespace Pod DNS names are:

```
/ # dig +noall +answer 10-12-56-9.kong.pod.cluster.local
10-12-56-9.kong.pod.cluster.local. 30 IN A      10.12.56.9
/ # dig +noall +answer 10-12-56-9.kong-admin.kong.svc.cluster.local
/ #
```

What we can do is:

- Construct service scoped dns name as described in https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records : `pod-ip-address.service-name.my-namespace.svc.cluster.local`
- Use https://github.com/miekg/dns to query that DNS name
- If it's available then use it
- If it's not then fallback to `pod-ip-address.my-namespace.pod.cluster.local` and query that
- Use https://github.com/miekg/dns to query that DNS name
- If that's not available, use an IP address as last resort

Simple test showing how to query the DNS 

```go
package main

import (
	"fmt"
	"net"
	"testing"

	"github.com/miekg/dns"
	"github.com/stretchr/testify/require"
)

func TestDNS(t *testing.T) {
	const (
		serviceName = "metrics-server"
		addr        = "10-244-0-4"
		namespace   = "kube-system"
	)

	cfg, err := dns.ClientConfigFromFile("/etc/resolv.confg")
	require.NoError(t, err)

	t.Run("svc", func(t *testing.T) {
		svcDomain := fmt.Sprintf("%s.%s.%s.svc.cluster.local", addr, serviceName, namespace)
		msg := (&dns.Msg{}).SetQuestion(dns.Fqdn(svcDomain), dns.TypeA)

		client := &dns.Client{}
		r, _, err := client.Exchange(msg, net.JoinHostPort(cfg.Servers[0], cfg.Port))
		require.NoError(t, err)

		logAnswer(t, r)
	})

	t.Run("pod", func(t *testing.T) {
		svcDomain := fmt.Sprintf("%s.%s.pod.cluster.local", addr, namespace)
		msg := (&dns.Msg{}).SetQuestion(dns.Fqdn(svcDomain), dns.TypeA)

		client := &dns.Client{}
		r, _, err := client.Exchange(msg, net.JoinHostPort(cfg.Servers[0], cfg.Port))
		require.NoError(t, err)

		logAnswer(t, r)
	})
}

func logAnswer(t *testing.T, r *dns.Msg) {
	t.Helper()

	t.Logf("r:\n%+v", r)
	for _, rr := range r.Answer {
		t.Logf("rr:\n%#v", rr.Header())
		if a, ok := rr.(*dns.A); ok {
			t.Logf("a:\n%s", a.A)
		}
	}
}
```

**Comment by mflendrich** [comment]
@pmalek 

> What we can do is:
> 
> - Construct service scoped dns name as described in https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records : `pod-ip-address.service-name.my-namespace.svc.cluster.local`
> - Use https://github.com/miekg/dns to query that DNS name
> - If it's available then use it
> - If it's not then fallback to `pod-ip-address.my-namespace.pod.cluster.local` and query that
> - Use https://github.com/miekg/dns to query that DNS name
> - If that's not available, use an IP address as last resort

Maybe make it configurable?
- introduce a flag (`--gateway-discovery-dns-strategy`) with 4 settings `ip`, `service-scoped`, `namespace-scoped`, `auto` having `auto` as the default
- run a sanity check on KIC startup that the chosen DNS mode is available (and exit with error if not, the error should point at this flag)
