### ISSUE TITLE
Assume traditional router when `router_flavor` is missing

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

#3935 introduced a check for `router_flavor` in Admin API config: https://github.com/Kong/kubernetes-ingress-controller/blob/ed051792ae2f2e6db2dfc3946f0416aa6abd1e45/internal/manager/utils/kongconfig/root.go#L49-L52

This check returns an error when this key is missing: https://github.com/Kong/kubernetes-ingress-controller/blob/ed051792ae2f2e6db2dfc3946f0416aa6abd1e45/internal/manager/utils/kongconfig/root.go#L106.

This means that Gateway versions which do not include said config field are breaking the KIC <-> Gateway integration.

We're OK in terms of compatibility because https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/ states that KIC 2.7 and above is compatible with GW 3.0+ but we could improve this by assuming we work with `traditional` router when that field is missing.

Related issue: https://github.com/Kong/kubernetes-ingress-controller/issues/4062

**Comment by mheap** [comment]
KIC 2.7 is compatible with GW 2.0+ - we should have a fallback

**Comment by pmalek** [comment]
I misinterpreted the table 🤦 You're right. In that case I believe we can assume that if the field is missing we assume `traditional` and use that.

**Comment by randmonkey** [comment]
@pmalek I think it is OK if Kong 3.0+ could guarantee that it contains the `router_flavor` field. If not we may assume `traditional` for 3.0- and `tradtional_compatible` for 3.0+.
