### ISSUE TITLE
Kong Testing Request template runs e2e tests that rely on `CONTROLLER_KONG_ADMIN_SVC` which is not support pre 2.9

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4069]
### Problem statement

[Validate kong image workflow](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/validate_kong_image.yaml) runs e2e tests which currently rely on `CONTROLLER_KONG_ADMIN_SVC` (or `--kong-admin-svc` flag).

These either deploy our all in one manifests (e.g. https://github.com/Kong/kubernetes-ingress-controller/blob/b53c014c01e58f86e7c6254c4b3085670ab317e3/test/e2e/all_in_one_test.go#L326-L337) or rely on kustomizations (e.g. here  in the helpers https://github.com/Kong/kubernetes-ingress-controller/blob/eb974e7cc2eebba7f3047acc5523f8037c361907/test/e2e/kustomizations_test.go) which also rely on `CONTROLLER_KONG_ADMIN_SVC`.

This is not respected by KIC versions below 2.9 hence effectively making testing those (earlier) versions with that workflow impossible.

**Comment by pmalek** [comment]
cc: @mflendrich

**Comment by randmonkey** [comment]
@pmalek  is it possible to fix by using `all-in-one-dbless-legacy.yaml` when KIC version is below 2.9?

**Comment by pmalek** [comment]
I'd have to double check how the manifests are being used but if we only replace the version this should be ok without the small little corner case: we need to use the old manifests which contain the RBAC policy rules for `Endpoints` instead of `EndpointsSlice`s which we're using today: https://github.com/Kong/kubernetes-ingress-controller/blob/74b39d2fa569fefb3ba96cdf268fd0d51fb6d182/deploy/single/all-in-one-dbless.yaml#L1319-L1326
