### ISSUE TITLE
ingress-controller -0.6.0 -schema violations

### ISSUE THREAD

**Issue by iot123** [Kong/kubernetes-ingress-controller#410]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.6.0

**Kong or Kong Enterprise version**
1.3.0

### Kubernetes version

**paste `kubectl version` output**
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

### Environment
test
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
I deployed complete kong-1.3.0 package using below link
https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml.

but giving error in ingress-controller container i.e:
E0925 06:59:21.734026       1 controller.go:132] unexpected failure updating Kong configuration: 
1 errors occurred:
	while processing event: {Create} failed: 400 Bad Request {"message":"3 schema violations (config.credentials: expected a boolean; config.origins: expected an array; config.preflight_continue: expected a boolean)","name":"schema violation","fields":{"config":{"origins":"expected an array","credentials":"expected a boolean","preflight_continue":"expected a boolean"}},"code":2}

### Steps To Reproduce

1.
2.
3.
4.

**Comment by hbagdi** [comment]
Please share the KongPlugin resource that you have created.
That has an erroneous configuration it seems.

**Comment by hbagdi** [comment]
Please re-open if issue persists.
