### ISSUE TITLE
Release v2.10 report

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#4120]
This issue is a report on the release performed in https://github.com/Kong/kubernetes-ingress-controller/issues/4098

Problems
- [ ] **release issue template**
    - [x] 🟢 broken links
        -  [.github/workflows/test.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/test.yaml)
        -  [.github/workflows/e2e.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/main/.github/workflows/e2e.yaml)
    - [x] 🔴  tags for `kindnode` and `istio` images - to consider 
       https://github.com/Kong/kubernetes-ingress-controller/pull/4126 every patch version has to be explicitly updated. K8s version is already available, but `kindnode` image not yet. It leads to saying explicitly that we have to test against older versions. Maybe instead of specifying e.g. `1.26.4` just rely on `1.26` to use the latest available version and avoid tedious checks/updates. 
       ⏫ 
       it won't be implemented, because images with such tags are not available and won't be available in the future see https://github.com/kubernetes-sigs/kind/issues/2376#issuecomment-1611894903
     - [x] 🟢  for `istio` is easier to check latest versions here https://istio.io/latest/news/releases than go through GH releases
     - [x] 🟢 make references to files clickable
        - `config/image/enterprise/kustomization.yaml`
        - `config/image/oss/kustomization.yaml`
        - `config/variants/enterprise/kustomization.yaml` (it seems redundant, because it doesn't contain any version)
     - [ ] vague bullet point `Update articles in the new version as needed.` (at the first glance it's not obvious that it means anything new needed in docs)
     - [ ] relation between `Trigger release_docs workflow. Note that you will need to update the new version's navigation manifest (e.g. for 2.7 to use the new file after.)` and `Ensure a draft PR is created in docs.konghq.com repository.` when release PR was created earlier, maybe let's have documentation branch for specific version from the start
     - [x] 🟢 steps from **`Steps`** are no longer up to date, policy for obtaining credentials has changed
     - [ ] nothing about required upgrading Helm Chart like did in https://github.com/Kong/charts/pull/816
- [ ] **release CI**
     - [ ] flakiness for the [test-e2e (v1.23.13) - TestDeployAllInOneDBLESSGateway](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5174585565/jobs/9321461327#logs)
     - [x] 🟢 #4145
- [ ] **docs**
     - [ ] consider having a long-living branch in docs repo `release/kic-2.11` (for the next release), all required docs changes can be reviewed and targeted to it by developers on their own. Before release make PR from this branch to `main` to be able to have checked all required changes in one pass by technical writers, Michael, etc.
     - [ ] document way of creating issues for changes in docs, let's have them in KIC repo to be able to track them in milestone and make require for release checklist merging `release/kic-2.XX` in docs repo

**Comment by pmalek** [comment]
2.10 is yet another release which tag landed on the release branch: 

```
* bc6f76d8 - chore(deps): bump github.com/golangci/golangci-lint in /third_party (#4130) (2 days ago) <dependabot[bot] - 49699333+dependabot[bot]@users.noreply.github.com>
* 8c075951 - chore(release): prepare release/2.10.0 (#4128) (5 days ago) <Jakub Warczarek - jakub.warczarek@konghq.com>
| * aca19f07 - (tag: v2.10.0, origin/release/2.10.x) chore(release): prepare release/2.10.0 (#4128) (#4131) (2 days ago) <github-actions[bot] - 41898282+github-actions[bot]@users.noreply.github.com>
|/
* 7e7d28cf - chore(release): bump K8s & Istio versions for 2.10 release (#4126) (5 days ago) <Jakub Warczarek - jakub.warczarek@konghq.com>
* dcd58c38 - test: trim prefix / of path and suffix / of proxy URL in MustHTTPRequest (#4125) (5 days ago) <Tao Yi - tao.yi@konghq.com>
```

This causes 2 thing: 

- poor discoverability of tags within the git history
- inaccurate tags created via `git describe --tags`: currently the last tag that's reachable from `main` is 2.8.1 which causes `git describe --tags` to return: `v2.8.1-478-gab03a527`


### Proposed solution

Create `vX.Y.0` tags on `main`.

**Comment by programmer04** [comment]
For https://github.com/Kong/kubernetes-ingress-controller/issues/4120#issuecomment-1580398292, issue https://github.com/Kong/kubernetes-ingress-controller/issues/4638 has been created
