### ISSUE TITLE
Multiple Ingresses that point to the same IP Address

### ISSUE THREAD

**Issue by nico-kuzak** [Kong/kubernetes-ingress-controller#413]
Is there any way to implement mergeable types (see here: https://github.com/nginxinc/kubernetes-ingress/tree/master/examples/mergeable-ingress-types). Does it work with the Ingress Controller?

If not, is there a way to have multiple ingresses point to the same IP address?

Whenever I currently try this, only one of them works.

**Comment by hbagdi** [comment]
> If not, is there a way to have multiple ingresses point to the same IP address?

All Ingress resources will share the same external IP address(es) of your Load Balancer.
Multiple Ingress resources pointing to the same service in Kubernetes will be automatically de-duplicated.

> Whenever I currently try this, only one of them works.

Could you explain in detail what you are trying to do here?

**Comment by nico-kuzak** [comment]
I am trying to build a CI/CD pipeline that creates a service and an ingress for each different model (and all ingresses would be connected to the Kong Ingress Controller). It works with the new version - 0.6.0, [after this fix](https://github.com/Kong/kubernetes-ingress-controller/blob/master/CHANGELOG.md#fixed) Thanks!
