### ISSUE TITLE
Kubernetes installation is failing due to image tag  not found

### ISSUE THREAD

**Issue by seifrajhi** [Kong/kubernetes-ingress-controller#4132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Wheen I try to kong into my Kubernetes cluster using below url, it fails because

Url used : https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-dbless.yaml

```
kubelet            Failed to pull image "kong/kubernetes-ingress-controller:2.10.0": rpc error: 
code = NotFound desc = failed to pull and unpack image "docker.io/kong/kubernetes-ingress-controller:2.10.0":
failed to resolve reference "docker.io/kong/kubernetes-ingress-controller:2.10.0":
docker.io/kong/kubernetes-ingress-controller:2.10.0: not found
```

### Expected Behavior

I should run 

```bash
Kubectl apply -f https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-dbless.yaml
```
I should have all resources up and running

### Steps To Reproduce

1.
```markdown

Kubectl apply -f https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-dbless.yaml
```

2. 
```
Kubectl describe pod  -n kong ingress-kong-57cdcfcb56-rv65x
...
...
...
Warning  Failed       17m (x3 over 27m)     kubelet            Error: ImagePullBackOff
  Normal   Pulling      16m (x5 over 27m)     kubelet            Pulling image "kong/kubernetes-ingress-controller:2.10.0"
  Warning  Failed       16m (x5 over 27m)     kubelet            Failed to pull image "kong/kubernetes-ingress-controller:2.10.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/kong/kubernetes-ingress-controller:2.10.0": failed to resolve reference "docker.io/kong/kubernetes-ingress-controller:2.10.0": docker.io/kong/kubernetes-ingress-controller:2.10.0: not found
  Warning  Failed       16m (x5 over 27m)     kubelet            Error: ErrImagePull
  Normal   BackOff      2m34s (x51 over 27m)  kubelet            Back-off pulling image "kong/kubernetes-ingress-controller:2.10.0"
```

**Comment by programmer04** [comment]
Hello @seifrajhi it works now.

By the way the manifests from `main` branch are not treated as a stable interface for end users to use. We explicitly made a change in [our docs](https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/overview) to prevent users from relying on those manifest.

If you'd like to still use the all in one manifests I encourage you to use a tagged version e.g. https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/v2.10.0/deploy/single/all-in-one-dbless.yaml
