### ISSUE TITLE
Helm db less not deploying ingress controller pod and service object

### ISSUE THREAD

**Issue by spacejam101** [Kong/kubernetes-ingress-controller#414]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**

**Kong or Kong Enterprise version**

### Kubernetes version

**paste `kubectl version` output**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### Steps To Reproduce

1.helm install stable/kong --namespace=kong --set ingressController.enabled=true
--set postgresql.enabled=false --set env.database=off 
2.
3.
4.

**Comment by hbagdi** [comment]
Can you paste the output of the command when you run that?
I just tested it on my end and it seems to be working fine.

Also, please make sure that you have your Helm repositories up to date by running:
```
helm repo update
```

**Comment by hazzanz** [comment]
The ingress controller container is in the kong pod for me as opposed to a separate pod

**Comment by hbagdi** [comment]
@spacejam101 Could you elaborate on what issue you are facing and share some error logs so that we can understand and help you better?

**Comment by spacejam101** [comment]
@hbagdi Hi! I was able to fix the issue with specifying the proxy.type as Loadbalancer thank!

**Comment by hbagdi** [comment]
Closing as the problem has been fixed.
