### ISSUE TITLE
Support `instance_name` for plugins

### ISSUE THREAD

**Issue by mheap** [Kong/kubernetes-ingress-controller#4140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Kong Gateway 3.2 added support for setting an `instance_name` on plugins. KIC is unaware of this field

### Proposed Solution

- Add support for setting `instance_name` on the `KongPlugin CRD`

### Acceptance Criteria

- As a user I can provide an `instance_name` for plugins and have it shown in Konnect/Kong Manager/Admin API

**Comment by msmost** [comment]
We would like to see this added in KIC
