### ISSUE TITLE
"Bad gateway" deploying demo application

### ISSUE THREAD

**Issue by dangtrinhnt-mmt** [Kong/kubernetes-ingress-controller#415]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Bad gateway error when trying to access $PROXY_IP/foo

**Kong Ingress controller version**

0.6.0

**Kong or Kong Enterprise version**

1.3.0

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-eks-5ac0f1", GitCommit:"5ac0f1d9ab2c254ea2b0ce3534fd72932094c6e1", GitTreeState:"clean", BuildDate:"2019-08-20T22:39:46Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: AWS EKS

### What happened

I'm trying to deploy the demo application with Kong-ingress in my istio service mesh inside AWS EKS. When I run this command `curl -i $PROXY_IP/foo`, I got this errors

> curl -i $PROXY_IP/foo
> HTTP/1.1 502 Bad Gateway
> Date: Mon, 30 Sep 2019 05:30:48 GMT
> Content-Type: text/plain; charset=UTF-8
> Transfer-Encoding: chunked
> Connection: keep-alive
> Server: kong/1.3.0
> X-Kong-Upstream-Latency: 12
> X-Kong-Proxy-Latency: 24
> Via: kong/1.3.0

> An invalid response was received from the upstream server

### Expected behavior

st like "HTTP/1.1 200 OK..."

### Steps To Reproduce

As in https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/getting-started.md

**Comment by dangtrinhnt-mmt** [comment]
Okie, I figured out. It's because I enabled mTLS policy for all services using istio configuration and it blocks Kong from communicating with upstreams.

**Comment by hbagdi** [comment]
If envoy is injected into the Kong Ingress Controller, you shouldn't be having this error.

Also, please make sure to add `traffic.sidecar.istio.io/includeInboundPorts: ""` annotation to your Kong Ingress Controller pod so that envoy doesn't take over Ingress traffic.

**Comment by nfickas** [comment]
Just curious I'm receiving a 504 Gateway Timeout error having followed the kubernetes.io blog post that is similar to the example that was followed above.

I added the annotation that you suggested above @hbagdi and am still receiving similar errors. Any thoughts on how to fix this?
