### ISSUE TITLE
Is it possible to provide tls certificate while deploying using helm chart?

### ISSUE THREAD

**Issue by smartaquarius10** [Kong/kubernetes-ingress-controller#4153]
Hello,

Does kong offers any out of the box functionality so that we can pass tls certificate and key while deploying using helm chart. If possible, after that there is no need to creates secrets for certificates in every namespace..

Especially this use case is very help ful if cluster shared and we have wildcard based certificate.

**Comment by rainest** [comment]
You can provide [Secrets to mount as volumes](https://github.com/Kong/charts/blob/4eb477b89c5be82a0d7735469fc1178ad008d930/charts/kong/values.yaml#L408-L416), and then provide those paths to the [default proxy certificate settings](https://github.com/Kong/kong/blob/2097daf25546e25f845b78bb642d99e80ebb6374/kong.conf.default#L787-L819) under `env`. This certificate is used if no Ingress-attached certificate matches a request hostname. However, you can only provide a single certificate this way.

The chart does not provide a means of deploying certificates attached to Ingresses for services other than its own (e.g. the admin API).

Kong's certificate hostname matching model means you do not strictly need to deploy certificates for every Ingress. Certificates are matched based on hostnames alone, so creating a wildcard certificate attached to an Ingress in one namespace for `*.example.com` will be served for another namespace's `foo.example.com` Ingress if the latter has no more specific certificate of its own (though you may need to override the latter's protocols to include HTTPS--I forget if we disable that by default for Ingresses with no certificates).

This approach is, however, an unsupported violation of the expectations of the Ingress spec, and isn't something we design the controller around: the spec just expects that you will always specify a certificate alongside its rules.

Although still in beta, the new [Gateway API](https://docs.konghq.com/kubernetes-ingress-controller/latest/concepts/gateway-api/) specification changes this design. In its spec, certificates are bound to a [hostname-identified Listener](
https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1beta1.Listener), which multiple rulesets can bind to [across namespaces](https://gateway-api.sigs.k8s.io/api-types/referencegrant/).

**Comment by smartaquarius10** [comment]
@rainest Got it thanks
