### ISSUE TITLE
Remove `CombinedServices` feature gate

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#4160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We'd like to make `CombinedServices` feature gate a default behavior from KIC 3.0.

### Proposed Solution

- Remove the feature gate
- Leave the behavior as it was turned on

### Acceptance Criteria

- [ ] CombinedServices behavior is always turned on with no possibility to opt-out

**Comment by programmer04** [comment]
Possible duplication
- https://github.com/Kong/kubernetes-ingress-controller/issues/3131
