### ISSUE TITLE
Add HTTP 8080 listen for conformance tests

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#4166]
[A conformance test](https://github.com/kubernetes-sigs/gateway-api/blob/v0.7.1/conformance/tests/httproute-redirect-port-and-scheme.go#L52-L55) requires testing against a listener on port 8080. Our manually-deployed test Kong instance doesn't have this at present, so the test fails. Adding such a listen (or testing against an operator-deployed instance) should let the test pass, though this isn't confirmed.

**Comment by rainest** [comment]
This should become moot, upstream plans to remove it https://github.com/kubernetes-sigs/gateway-api/issues/2094

**Comment by mlavacca** [comment]
closing as superseded by #4563
