### ISSUE TITLE
[question] ingress-nginx and kubernetes-ingress-controller

### ISSUE THREAD

**Issue by xuejipeng** [Kong/kubernetes-ingress-controller#422]
I have some scenarios to make  ingress-nginx and kubernetes-ingress-controller coexist
if ingress-nginx and kubernetes-ingress-controller can be used together？

thx

**Comment by hbagdi** [comment]
Yes, multiple Ingress controllers can be used in conjunction.
Please use `kubernetes.io/ingress.class` annotation on your Ingress resources to ensure that not all Ingress resources are processed by both the controllers:
https://github.com/Kong/kubernetes-ingress-controller/blob/b986e433ec3efb4d3e158a2ec611528e55552e38/docs/references/annotations.md
