### ISSUE TITLE
Version Control of the Kubernetes Ingress Controller

### ISSUE THREAD

**Issue by nico-kuzak** [Kong/kubernetes-ingress-controller#427]
Is there an easy way to version control the Kubernetes Ingress Controller? For instance, if I want to initialize a cluster and deploy version 0.5 instead of 0.6.

**Comment by hbagdi** [comment]
You can simply change the tag of the image being used: https://github.com/Kong/kubernetes-ingress-controller/blob/71a7653e714f7e8694d57a730d1ef006a784f8a6/deploy/single/all-in-one-dbless.yaml#L569

**Comment by nico-kuzak** [comment]
Ok - that's what I've been doing. Thanks again
