### ISSUE TITLE
postgresql server isn't starting

### ISSUE THREAD

**Issue by BugAgain** [Kong/kubernetes-ingress-controller#428]
### Summary

Tried to follow [this](https://konghq.com/blog/observability-kubernetes-kong/) tutorial from @hbagdi but it looks like the postgres is not working.

I'm in a local kubernetes cluster provided by docker desktop on windows 10.

### What happened

![01](https://user-images.githubusercontent.com/29819739/67168684-0b721c00-f37d-11e9-868e-f9ca7ee3010e.png)

![02](https://user-images.githubusercontent.com/29819739/67168687-1036d000-f37d-11e9-8bb0-9769c7376827.png)

And this is the log msg:

> [0m
[0m[1mWelcome to the Bitnami postgresql container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-postgresql[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-postgresql/issues[0m
[0m
nami    INFO  Initializing postgresql
postgre INFO  ==> No injected postgresql.conf file found. Creating default postgresql.conf file...
postgre INFO  ==> No injected pg_hba.conf file found. Creating default pg_hba.conf file...
postgre INFO  ==> Deploying PostgreSQL with persisted data...
postgre INFO  ==> Configuring PostgreSQL...
postgre INFO  ==> Configuring replication parameters...
postgre INFO  ==> Configuring permissions for config files...
postgre INFO 
postgre INFO  ########################################################################
postgre INFO   Installation parameters for postgresql:
postgre INFO     Persisted data and properties have been restored.
postgre INFO     Any input specified will not take effect.
postgre INFO   This installation requires no credentials.
postgre INFO  ########################################################################
postgre INFO 
nami    INFO  postgresql successfully initialized
[0m[38;5;2mINFO [0m ==> Starting postgresql... 
nami    ERROR Unable to start com.bitnami.postgresql: pg_ctl: could not start server
Examine the log output.

**Comment by hutchic** [comment]
This doesn't look specific to the Kong helm chart but an issue running the postgresql helm chart with your environment / setup.

Can you try and run the postgresql helm chart on it's own per https://github.com/helm/charts/tree/master/stable/postgresql and see if you can reproduce the issue there?

**Comment by BugAgain** [comment]
As you said, this was merely a setup issue with the postgresql helm chart, but it has already been fixed. Thanks!

That tutorial is great, but it can't cover all the details, so novice people may have different issues.
