### ISSUE TITLE
Make `release/2.5.x` PR tests workflow work

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#4284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As `release/2.5.x` is our LTS release branch, we need its CI to work properly. Currently, it's not possible to merge any PR to the release branch due to failing `test.yaml` workflow. 

### Proposed Solution

- Investigate why `test.yaml` is failing and fix the discovered issues
- Start building on top of https://github.com/Kong/kubernetes-ingress-controller/pull/4282 where @rainest already fixed linting and some of testing machinery problems

### Acceptance Criteria

- [ ] As a developer, when I create a PR based on `release/2.5.x` release branch and I do not introduce any bug, I expect the `test.yaml` workflow to pass allowing my PR to be merged after review

**Comment by rainest** [comment]
Conformance appears to be a lost cause. It looks like older versions of the upstream code just applied master rather than their tagged version (maybe they still do this?), but master now uses v1beta1:

```
time="2023-07-06T20:04:04Z" level=info msg="processing gatewayclass" V1Alpha2GatewayClass="{\"Namespace\":\"\",\"Name\":\"1aa450d2-d18b-406e-8572-66fa0ebaa1ed\"}" logger=controllers.Gateway.V1Alpha2GatewayClass name=1aa450d2-d18b-406e-8572-66fa0ebaa1ed
    suite.go:80: Test Setup: Applying base manifests
    apply.go:75: Creating gateway-conformance-infra Namespace
    apply.go:73: 
        	Error Trace:	/home/runner/go/pkg/mod/sigs.k8s.io/gateway-api@v0.4.1-0.20220306235253-71fee1c2808f/conformance/utils/kubernetes/apply.go:73
        	            				/home/runner/go/pkg/mod/sigs.k8s.io/gateway-api@v0.4.1-0.20220306235253-71fee1c2808f/conformance/utils/suite/suite.go:81
        	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/conformance/gateway_conformance_test.go:57
        	Error:      	Received unexpected error:
        	            	no matches for kind "Gateway" in version "gateway.networking.k8s.io/v1beta1"
        	Test:       	TestGatewayConformance
        	Messages:   	error getting resource
--- FAIL: TestGatewayConformance (1.53s)
```

```
> sigs.k8s.io/gateway-api/conformance/utils/kubernetes.MustApplyWithCleanup() /home/traines/go/pkg/mod/sigs.k8s.io/gateway-api@v0.4.1-0.20220306235253-71fee1c2808f/conformance/utils/kubernetes/apply.go:73 (hits goroutine(198):1 total:1) (PC: 0x268a93a)
    68:			namespacedName := types.NamespacedName{Namespace: uObj.GetNamespace(), Name: uObj.GetName()}
    69:			fetchedObj := uObj.DeepCopy()
    70:			err := c.Get(ctx, namespacedName, fetchedObj)
    71:			if err != nil {
    72:				if !apierrors.IsNotFound(err) {
=>  73:					require.NoErrorf(t, err, "error getting resource")
    74:				}
    75:				t.Logf("Creating %s %s", uObj.GetName(), uObj.GetKind())
    76:				err = c.Create(ctx, &uObj)
    77:				require.NoErrorf(t, err, "error creating resource")
    78:	

(dlv) p location
"https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/master//conformance/base/manifests.yaml"
```

 I think technically we can apply the v1beta1 manifests and still use the v1alpha2 client, but don't know if we want to bother: we're not going to be _adding_ conformance functionality to 2.5, and GWAPI is still beta. Do we care about beta features for LTS purposes?

**Comment by rainest** [comment]
dbless integration finishes successfully after backporting f5c2ddc547b26bc5c5b82069d82905c7afa321e0. Postgres is still failing but I'm unsure how much that's actual failures versus just tests being flakier earlier. The failures aren't consistent across Enterprise and OSS Postgres, suggesting the latter.

**Comment by rainest** [comment]
The current LTS is now 2.8, and backports to it do run tests. AFAIK there's no general issue running tests on minor branches anymore, so closing this.

The point about conformance still stands. Until GWAPI reaches a stable state that's probably just a fact of life. It's beta functionality until then, so I'm not concerned about it.

We do have general issues with wanting KTF upgrades for a variety of reasons and those pulling in breaking changes from libraries that KIC also uses. We could try to invoke KTF via CLI if these updates become too onerous, but it's usually possible to backport the compatibility changes.
