### ISSUE TITLE
invalid image tag for kong/kubernetes-ingress-controller:2.10.2

### ISSUE THREAD

**Issue by neeraj-ec** [Kong/kubernetes-ingress-controller#4289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

File [/deploy/single/all-in-one-dbless.yaml#L1687](https://github.com/Kong/kubernetes-ingress-controller/blob/8f031ed6271b4b66802a7ac4beb827dfe96887ca/deploy/single/all-in-one-dbless.yaml#L1687) mentions image tag `kong/kubernetes-ingress-controller:2.10.2` which does not exists. Hence deployment fails.

### Expected Behavior

Working dbless deployment on k8s cluster

### Steps To Reproduce

```markdown
`kubectl apply -f https://bit.ly/k4k8s`
```

### Kong Ingress Controller version

```shell
latest
```

**Comment by pmalek** [comment]
Hi @neeraj-ec,

Do you mind sharing with us where did you find the instructions that utilize the https://bit.ly/k4k8s URL?

We specifically mention at https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/k4k8s/#kustomize that 

> Kustomize manifests are provided for illustration purposes only and are not officially supported by Kong. There is no guarantee of backwards compatibility or upgrade capabilities for our Kustomize manifests. For a production setup with Kong support, use the [Helm Chart](https://github.com/kong/charts).

If you want to use `kustomize` manifests - given the lack of support mentioned above, you can still use the versioned manifests as indicated e.g. at https://docs.konghq.com/kubernetes-ingress-controller/2.10.x/deployment/minikube/#deploy-kic

```
kubectl create -f https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/v2.10.0/deploy/single/all-in-one-dbless.yaml
```

**Comment by neeraj-ec** [comment]
@pmalek it has nothing to do with kustomize. In the [Get Started section](https://github.com/Kong/kubernetes-ingress-controller#get-started) it mentions the command `kubectl apply -f https://bit.ly/k4k8s`.

When you visit the url https://bit.ly/k4k8s, it renders the yaml which uses 
```yaml
image: kong/kubernetes-ingress-controller:2.10.2
```   

Now when I check the docker hub there is no `2.10.2` tag available for `kong/kubernetes-ingress-controller`. That's why running it stuck at ImagePullOff error.

**Comment by randmonkey** [comment]
@neeraj-ec  Now 2.10.2 is released and image `kong/kubernetes-ingress-controller:2.10.2` is pushed to docker hub. The general issue that manifests may be unavailable when tags are updated in manifests but the not actually released is expected to be received by https://github.com/Kong/kubernetes-ingress-controller/pull/4305.
