### ISSUE TITLE
no matches for kind "ClusterIssuer" in version "certmanager.k8s.io/v1alpha1"

### ISSUE THREAD

**Issue by WoodyFleurant** [Kong/kubernetes-ingress-controller#431]
To reproduce 

Follow installation guide until Request TLS Certificate from Let's Encrypt

When doing 
`echo "apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: user@example.com # please change this
    http01: {}
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory" | k apply -f -`

I get no matches for kind "ClusterIssuer" in version "certmanager.k8s.io/v1alpha1"

As a workaround 

kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/00-crds.yaml

**Comment by jussiarpalahti** [comment]
It seems Cert Manager has changed its API or at least its identifier:
https://docs.cert-manager.io/en/latest/tutorials/acme/http-validation.html#issuing-an-acme-certificate-using-http-validation

In Kong's example here it is `apiVersion: certmanager.k8s.io/v1alpha1` but most recent release of Manager uses `apiVersion: cert-manager.io/v1alpha2`. I changed the examples but am currently stuck with "Created new CertificateRequest resource "echoa-4278383622".

**Comment by hbagdi** [comment]
As @jussiarpalahti mentioned, this is an API group and version change from cert-manager's side.
We have two options:
- Remove the section from our guide and point users to cert-manager's guide to set up the cluster issuer.
- Update it in our guide.

A docs PR to fix this is welcome!

**Comment by hbagdi** [comment]
Fixed with #433
