### ISSUE TITLE
error while evaluating the ingress spec: service "default/echo" is type "ClusterIP", expected "NodePort" or "LoadBalancer"

### ISSUE THREAD

**Issue by WoodyFleurant** [Kong/kubernetes-ingress-controller#432]
After following the installation and trying to setup a basic proxy for echo service I get this error in Google Cloud

error while evaluating the ingress spec: service "default/echo" is type "ClusterIP", expected "NodePort" or "LoadBalancer"

**Comment by hbagdi** [comment]
Where are you getting this error from and when?
I don't think that's coming from Kong Ingress controller.

Make sure that you are not using the default GKE Ingress controller. That could be throwing this error.

**Comment by WoodyFleurant** [comment]
Actually, if I put annotation `kubernetes.io/ingress.class: "kong"` in metadata tag, it works fine and error disappears

**Comment by ernestofreyreg** [comment]
Shouldn't this be updated on the documentation and examples?
