### ISSUE TITLE
Separate route validation and translation

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#4321]
From https://github.com/Kong/kubernetes-ingress-controller/pull/4296#issuecomment-1630355669

We expect to have some level of separate code paths for traditional and expression route translation for the foreseeable future. Kong 3.x supports both, but expression is in beta. We intend to transition to expression in order to satisfy GWAPI conformance, but won't be able to drop traditional until/unless it's deprecated.

Most route validation is not specific to the translation format, but is currently part of the format-specific translation functions. We wish to refactor this out of those functions and make it format-agnostic.

**Comment by rainest** [comment]
Tentative 2.11 but can be deferred, as it has no user-facing impact.

**Comment by mflendrich** [comment]
This could fit in nicely with other general opportunistic clean-ups we're planning for 3.0. Moved to the 3.0 milestone
