### ISSUE TITLE
Annoymous reporting is opt-in by default

### ISSUE THREAD

**Issue by maximveksler** [Kong/kubernetes-ingress-controller#4348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following errors are being printed in our kong deployment

```
time="2023-07-12T04:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T05:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T06:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T07:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T08:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T09:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T10:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T11:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T12:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T13:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T14:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T15:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T16:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T17:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T18:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T19:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T20:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T21:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T22:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-12T23:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-13T00:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-13T01:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
time="2023-07-13T02:57:04Z" level=error msg="failed to forward report" error="failed to send report: write tcp 10.1.19.131:51262->35.169.37.138:61833: write: broken pipe" forwarder=TLSForwarder
```

It seems it's related to KIC reporting statistics to a central server.

Searching it looks like `send_anonymous_reports` should be used to disable this option however I couldn't find documentation.

### Expected Behavior

No default call back home should be implemented in opt-in mode upon deployment.

### Steps To Reproduce

```markdown
1. Deploy KIC
2. Wait for downtime / Block communication to 35.169.37.138
```

### Kong Ingress Controller version

```shell
kong:3.2
```

### Kubernetes version

```shell
EKS 1.27
```

### Anything else?

Kindly 
1. Document this call back home, it's surprising to say the least.
2. Provide a method to disable it
3. Consider having a this by default opt-out

**Comment by mflendrich** [comment]
@maximveksler, thank you for your report.

Anonymous reports allow us, the maintainers of Kong Ingress Controller, to better understand the usage patterns and make informed decisions when making changes that impact our user base (e.g. deprecating old features based on the right data about real-world usage).

The setting that controls the anonymous reports feature is documented on the [official KIC documentation site](https://docs.konghq.com/kubernetes-ingress-controller/2.10.x/references/cli-arguments/) as well as in the `--help`:

```console
$ ./manager --help
      ...
      --anonymous-reports                                 Send anonymized usage data to help improve Kong (default true)
      ...
```

You can disable anonymous reports by setting this flag to `false` (or using an equivalent environment variable as described in the [Environment variables](https://docs.konghq.com/kubernetes-ingress-controller/2.10.x/references/cli-arguments/#environment-variables) section). We understand that some users will choose to disable this feature - please remember that it's the best tool at our disposal to make informed decisions about the future shape of KIC.

**Comment by maximveksler** [comment]
For people looking for documentatino on how to disable using KIC (kuberneters Ingress Controller)

```
kong:
  env:
    anonymous_reports: "off"
```

**Comment by mheap** [comment]
Hey @maximveksler,

As @mflendrich mentioned, `--anonymous-reports` shows up in both the controller flags and is documented on the docs site. 

As the product is open source, you can see the data collected at https://github.com/Kong/kubernetes-ingress-controller/blob/ace87d077958bd9029231da8751ebd4efb64a35d/internal/manager/telemetry/manager.go#L33-L39

As you can see, we collect things like which feature flags are enabled, and if the controller is attached to Konnect. Understanding usage is key to developing a product that is useful to our consumers. Anonymous reports is the primary way to capture this data and make informed decisions about when it's safe to remove deprecated features.

I understand that in security-conscious environments this behaviour is not ideal. However, in these environments the traffic will be blocked by firewall rules, and operators are reviewing components before inserting them in to critical infrastructure.

Anonymous reports are what enable us to build the best product available for our community of users and we intend to stay with the opt-out model. If anyone is struggling to disable the reports, please let us know and we'll work with you to get it resolved.
