### ISSUE TITLE
Run conformance tests with expression router enabled

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#4352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

https://github.com/Kong/kubernetes-ingress-controller/pull/4296 implemented HTTPRoute priority translation when using Kong with the expression router. This was mandatory to fix the HTTPRouteHeaderMatching conformance test.
As it is possible to see from https://github.com/Kong/kubernetes-ingress-controller/pull/4351, where the expression router has been enabled in conformance tests, the new HTTPRoute translation and the priority setting fixed such a test, but broke a bunch of others:

- `HTTPExactPathMatching`
- `HTTPRouteHostnameIntersection`
- `HTTPRouteMatchingAcrossRoutes`
- `HTTPRouteMatching`
- `HTTPRoutePathMatchOrder`
- `HTTPRouteRequestHeaderModifier`

### Proposed Solution

Debug test by test and figure out what's the reason why they are failing. The conformance tests logs for such failures can be found [here](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/5552404904/jobs/10139720178?pr=4351).

### Additional information

The following are the failing test cases:
- `HTTPExactPathMatching` (subset of cases)
  - `1_request_to_'/two'_should_go_to_infra-backend-v2`
  - `0_request_to_'/one'_should_go_to_infra-backend-v1`
- `HTTPRouteHostnameIntersection` (subset of cases)
  - `1_request_to_'very.specific.com:1234/s1'_should_go_to_infra-backend-v1`
  - `13_request_to_'very.specific.com/s3'_should_go_to_infra-backend-v3`
  - `8_request_to_'foo.bar.wildcard.io/s2'_should_go_to_infra-backend-v2`
  - `6_request_to_'foo.wildcard.io/s2'_should_go_to_infra-backend-v2`
  - `7_request_to_'bar.wildcard.io/s2'_should_go_to_infra-backend-v2`
  - `0_request_to_'very.specific.com/s1'_should_go_to_infra-backend-v1`
  - `20_request_to_'foo.bar.anotherwildcard.io/s4'_should_go_to_infra-backend-v1`
  - `18_request_to_'foo.anotherwildcard.io/s4'_should_go_to_infra-backend-v1`
  - `19_request_to_'bar.anotherwildcard.io/s4'_should_go_to_infra-backend-v1 `
- `HTTPRouteMatchingAcrossRoutes` (subset of cases)
  - `6_request_to_'example.com/v2/example'_should_go_to_infra-backend-v2`
  - `4_request_to_'example.com/v2'_should_go_to_infra-backend-v2`
- `HTTPRouteMatching` (subset of cases)
  - `6_request_to_'/v2/'_should_go_to_infra-backend-v2`
  - `3_request_to_'/v2'_should_go_to_infra-backend-v2`
  - `4_request_to_'/v2/example'_should_go_to_infra-backend-v2` 
- `HTTPRoutePathMatchOrder` (all cases)
  - `0_request_to_'/match/exact/one'_should_go_to_infra-backend-v3`
  - `5_request_to_'/match/any'_should_go_to_infra-backend-v3`
  - `4_request_to_'/match/prefix/any'_should_go_to_infra-backend-v1`
  - `1_request_to_'/match/exact'_should_go_to_infra-backend-v2`
  - `2_request_to_'/match'_should_go_to_infra-backend-v1`
  - `3_request_to_'/match/prefix/one/any'_should_go_to_infra-backend-v2` 
- `HTTPRouteRequestHeaderModifier` (all cases)
  - `6_request_to_'/case-insensitivity'_with_headers_should_go_to_infra-backend-v1`
  - `2_request_to_'/add'_with_headers_should_go_to_infra-backend-v1`
  - `3_request_to_'/add'_with_headers_should_go_to_infra-backend-v1`
  - `5_request_to_'/multiple'_with_headers_should_go_to_infra-backend-v1`
  - `4_request_to_'/remove'_with_headers_should_go_to_infra-backend-v1`
  - `1_request_to_'/set'_with_headers_should_go_to_infra-backend-v1`
  - `0_request_to_'/set'_with_headers_should_go_to_infra-backend-v1`

### Acceptance Criteria

- [ ] All the core HTTP conformance tests pass with the expression router enabled.

**Comment by randmonkey** [comment]
The errors are caused by a missing `StripPath: false` setting in translated Kong routes. will fix in #4359.
