### ISSUE TITLE
Ingress controller wildcard certificate

### ISSUE THREAD

**Issue by dg410** [Kong/kubernetes-ingress-controller#4370]
### Discussed in https://github.com/Kong/kubernetes-ingress-controller/discussions/4361

<div type='discussions-op-text'>

<sup>Originally posted by **dg410** July 17, 2023</sup>
Hi, I'm working on a disconnected openshift environment where it's not possible to use Let's encrypt. I want to use a default wildcard certificate on the ingress controller, so that every ingress resource that is using the ingress controller will use the certificate. How can I achieve this?</div>

**Comment by rainest** [comment]
Handled in the discussion.
