### ISSUE TITLE
docs for rewrite URI feature

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#4397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We need to have document to tell users how to use rewrite URI feature, especially tell them how to use capture groups in URIs and how to use escape characters(if we decide to support it). The document should exist in our doc site, and also in the repo. 

### Proposed Solution

- Add a guide page and a reference page to introduce rewrite URI feature, and include examples for each point in the feature (normal usage, capture groups, escape chars if supported)
- Introduce the feature and tell users this is a feature-gated feature in `FEATURE_GATES.md`

### Additional information

related issue: #4308 

### Acceptance Criteria

- [ ] Have a guide page to introduce how to use the rewrite URI feature, and a reference page to tell the rules of translating the annotation to Kong configuration
- [ ] Have an introduction of the feature and the controlling feature gate in `FEATURE_GATES.md`

**Comment by rainest** [comment]
https://github.com/Kong/docs.konghq.com/pull/6086 for the rest of it.

I'm pretty sure we don't need a separate guide for this. It's not a particularly complex feature, and the guide would basically be a copy of the reference example, or about 2 sentences of duplicate content after a bunch of boilerplate "set up a route to attach this to" content.
