### ISSUE TITLE
Kubernetes ingress rule not working

### ISSUE THREAD

**Issue by angapov** [Kong/kubernetes-ingress-controller#44]
**Is this a request for help?**: yes

**What keywords did you search in Kong Ingress controller issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
ingress, kubernetes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kong Ingress controller version**:
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.0.4

**Kubernetes version** (use `kubectl version`):
v1.9.3

**Environment**:

- **Cloud provider or hardware configuration**: AWS 
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): 4.4
- **Install tools**: Kubernetes cluster on AWS instances deployed by Kops
- **Others**:

**What happened**: 
I deployed Kong with ingress controller using this manifest: https://pastebin.com/raw/fNdceRc5
Kubernetes resource overview: https://pastebin.com/raw/N7VnhHHx

I created simple ingress rule to expose Kong dashboard:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-dashboard-ingress
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - http:
      paths:
      - path: /kong
        backend:
          serviceName: kong-dashboard
          servicePort: 8080
```
However it seems that dashboard is not exposed:
```
$ curl XXX.us-east-1.elb.amazonaws.com/kong
{"message":"no route and no API found with those values"}
```

Last logs from ingress-controller:
```
I0515 06:04:32.804892       5 controller.go:127] syncing Ingress configuration...
I0515 06:07:47.564574       5 controller.go:127] syncing Ingress configuration...
I0515 06:07:47.565028       5 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kong", Name:"kong-dashboard-ingress", UID:"84e3d91f-578e-11e8-b6a3-12b7dba3ea38", APIVersion:"extensions", ResourceVersion:"640543", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress kong/kong-dashboard-ingress
I0515 06:14:26.138244       5 controller.go:127] syncing Ingress configuration...
I0515 06:14:29.471761       5 controller.go:127] syncing Ingress configuration...
I0515 06:14:32.805099       5 controller.go:127] syncing Ingress configuration...
```

In Kong logs I see only 404s.

Here is description of ingress resource:
```
Name:             kong-dashboard-ingress
Namespace:        kong
Address:          XXX.us-east-1.elb.amazonaws.com
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host  Path  Backends
  ----  ----  --------
  *
        /kong   kong-dashboard:8080 (<none>)
Annotations:
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"kong"},"name":"kong-dashboard-ingress","namespace":"kong"},"spec":{"rules":[{"http":{"paths":[{"backend":{"serviceName":"kong-dashboard","servicePort":8080},"path":"/kong"}]}}]}}

  kubernetes.io/ingress.class:  kong
Events:                         <none>
```

**What you expected to happen**:
I expect that Kong dashboard will be available on XXX.us-east-1.elb.amazonaws.com/kong

**How to reproduce it** (as minimally and precisely as possible):
Try to apply above mentioned manifests in Kubernetes on AWS.

**Anything else we need to know**:

**Comment by angapov** [comment]
Same behavior with same manifests on minikube.

**Comment by angapov** [comment]
It seems that ingress-controller is not doing anything. I see no POST requests in admin-api and database tables are also empty.

**Comment by devdavidkarlsson** [comment]
`    kubernetes.io/ingress.class: "kong"`

should be 
   
` kubernetes.io/ingress.class: "nginx"`

```
export KONG_ADMIN_PORT=$(minikube service -n kong kong-ingress-controller --url --format "{{ .Port }}")
export KONG_ADMIN_IP=$(minikube service   -n kong kong-ingress-controller --url --format "{{ .IP }}")
export PROXY_IP=$(minikube   service -n kong kong-proxy --url --format "{{ .IP }}" | head -1)
export HTTP_PORT=$(minikube  service -n kong kong-proxy --url --format "{{ .Port }}" | head -1)
export HTTPS_PORT=$(minikube service -n kong kong-proxy --url --format "{{ .Port }}" | tail -1)
curl ${KONG_ADMIN_IP}:${KONG_ADMIN_PORT}/routes |jq .
curl ${KONG_ADMIN_IP}:${KONG_ADMIN_PORT}/services |jq .
```

**Comment by angapov** [comment]
But I specified --ingress-class=kong in ingress-controller args...

**Comment by devdavidkarlsson** [comment]
Hmm, ok. What do you get on the endpoints listed above?

And the upstreams one:

curl ${KONG_ADMIN_IP}:${KONG_ADMIN_PORT}/upstreams |jq .

**Comment by yorinasub17** [comment]
I came across this as well, and noticed that the ingress controller [ignores any ingress rules that don't have a specific host attached to it](https://github.com/Kong/kubernetes-ingress-controller/blob/master/internal/ingress/controller/kong.go#L197). It worked once I specified a host to the ingress rule.

**Comment by angapov** [comment]
@yorinasub17 you are right. Configuring hosts did the trick. Thank you!
