### ISSUE TITLE
Use `kong` namespace in integration tests

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#4431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As our manifests use `kong` as a namespace, that would make sense to use the same one in our integration tests to not introduce unnecessary noise. Currently, integration tests use `kong-system` namespace which proved to be problematic for RBACs installation to work as expected in https://github.com/Kong/kubernetes-ingress-controller/pull/4376.

### Proposed Solution

- Change [`ControllerNamespace`](https://github.com/Kong/kubernetes-ingress-controller/blob/3339b60258503cc79b8b515b7b4382296feeb07b/test/consts/misc.go#L17) to `kong`
- Adapt any breaking tests to the change
- Clean up code responsible for installing RBACs explicitly into `kong` namespace (as added in https://github.com/Kong/kubernetes-ingress-controller/pull/4376)

### Acceptance Criteria

- [ ] `kong` namespace is used in integration tests instead of `kong-system`

**Comment by randmonkey** [comment]
Kong gateway is installed by `kong.Builder` in KTF addons, but the builder has fixed namespace `kong-system` and does not support changing namespace. Created a KTF issue: https://github.com/Kong/kubernetes-testing-framework/issues/765 and mark it as the blocker.
