### ISSUE TITLE
Configure `consumer_group_consumers` in dbless mode kong configurations to set consumers in consumer groups

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#4448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

In dbless mode of kong gateway, caller need to put relationship between `consumer_group` and `consumer` in the field `consumer_group_consumers` to put consumers in consumer groups. The format goes like 
```
{
  "_format_version": "3.0",
  "consumers": [
    {
      "username": "test-consumer",
      "tags": [
         ...
      ]
    }
  ],
  "consumer_group_consumers": [
    {
      "consumer_group": "test-consumer-group-1",
      "consumer": "test-consumer"
    },
    {
      "consumer_group": "test-consumer-group-2",
      "consumer": "test-consumer"
    }
  ],
  "consumer_groups": [
    {
      "name": "test-consumer-group-2",
      "tags": [
        ...
      ]
    },
    {
      "name": "test-consumer-group-1",
      "tags": [
        ...
      ]
    }
  ]
}
```
one item in `consumer_group_consumers` array puts a consumer in a consumer group. We need to configure this field to put consumers in consumer groups. 

### Proposed Solution

- configure `consumer_group_consumers` for relationship between consumers and consumer groups when Kong is running in dbless mode.

### Additional information

Blocker: `file.Content` in deck does not contain `ConsumerGroupConsumers`.

### Acceptance Criteria

 - [ ] When Kong gateway runs in dbless mode, KIC could translate relationship between consumers and consumer groups into `consumer_group_consumers` correctly

**Comment by randmonkey** [comment]
blocked by: https://github.com/Kong/deck/issues/993

**Comment by programmer04** [comment]
It was discovered during work on https://github.com/Kong/kubernetes-ingress-controller/issues/3728
