### ISSUE TITLE
Rename Runtime Groups to Control Plane

### ISSUE THREAD

**Issue by mheap** [Kong/kubernetes-ingress-controller#4466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The `Runtime Group` terminology is being phased out in support of `Control Plane` in Konnect

### Proposed Solution

* Replace all usage of the term `Runtime Group` in public facing configuration/logs with `Control Plane`
* Replace the path `~/kic/api/runtime_groups/(?<rgid>\S+?)/(?<path>\S+)` with `~/kic/api/control_planes/(?<rgid>\S+?)/(?<path>\S+)`
* Replace the path `~/kic/api/runtime_groups/(?<rgid>\S+?)/oauth2` with `~/kic/api/control_planes/(?<rgid>\S+?)/oauth2`

### Additional information

Refactoring internal method names away from Runtime Group is optional, but recommended

### Acceptance Criteria

- [x] `konnect-runtime-group-id` CLI flag is deprecated, `konnect-control-plane-id` is introduced instead
- [x] `internal/konnect/runtimegroups` package uses `ControlPlane` naming instead of `RuntimeGroup` for its types and functions
- [x] tests and test helpers do not use `RuntimeGroup` term
- [x] `internal/dataplane/sendconfig` package does not use `RuntimeGroup` term

**Comment by mflendrich** [comment]
Reopening to determine the scope of the remaining work (at least check if log prints, flag names, or as @randmonkey pointed out - object names in the code) need changing.
Then please put them in the ACs and shepherd this effort through completion.
