### ISSUE TITLE
Official arm64 build for the controller

### ISSUE THREAD

**Issue by lyndon160** [Kong/kubernetes-ingress-controller#451]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

As specified here, images on bintray should follow have an architecture appended to them:
https://github.com/Kong/kong/blob/master/CHANGELOG.md

Currently only amd64 is available.

Kong proxy does but the ingress controller does not. Currently, without rebuilding and uploading to another repository, this is stopping users deploying kong to Arm64.

**Comment by lyndon160** [comment]
Following on from this, building the Dockerfile on an Arm machine works but the resulting container proceduces `standard_init_linux.go:190: exec user process caused "exec format error"`

This normally an issue when a dependancy is not Arm compatible.

**Comment by lyndon160** [comment]
The runtime error was caused by issue with the golang build which was building for AMD64 instead of being platform agnostic.

An image on bintray with an arm64 build would still be useful

**Comment by hbagdi** [comment]
@lyndon160 Can you remove the `GOARCH` environment variable from this line and try again:
https://github.com/Kong/kubernetes-ingress-controller/blob/31de1cdd6aa9d5415113269859136efcd4187d45/Dockerfile#L10

**Comment by lyndon160** [comment]
@hbagdi removing that fixes the build as I said in the comment above.

**Comment by hbagdi** [comment]
Okay, we will need to figure out how to make it possible to build arm64 executable on amd64. The Go binary can be built easily using `GOARCH` variable but I'm not sure how we can do the Docker build on an amd64 machine.

Any thoughts?
Would be happy to work along with you and accept this contribution.

**Comment by lyndon160** [comment]
Yes I do:

`docker buildx build --platform linux/amd64,linux/arm64 -t ingress-controller . --push`

**Comment by carnei-ro** [comment]
I'm facing this issue too. Built the image leandrocarneiro/kong-ingress-controller:0.7.0 (arm64)

**Comment by hbagdi** [comment]
@carnei-ro Can you work with us to PR the work into this repo?

**Comment by carnei-ro** [comment]
@hbagdi is there any pipelines to build? which? As said, the only thing I have done is to change the GOARCH and built it in an ARM64 host. You can use https://blog.hypriot.com/post/docker-intel-runs-arm-containers/ to run ARM64 containers in AMD64 hosts (linux).

**Comment by hbagdi** [comment]
The build process is in the Makefile currently and it is executed on amd64 linux machines.
Building an ARM64 binary is straight-forward but we need to use `docker buildx` to build an arm64 Docker image.

**Comment by lyndon160** [comment]
@hbagdi, now that there is a solution for building the Arm64 version, can we get this pushed to Kong's official repository?

**Comment by AlaaAttya** [comment]
hi @hbagdi seems @lyndon160 has the solution to build the ARM docker image on AMD machine. so can we push officially?

**Comment by hbagdi** [comment]
Yes. Please send a PR.

**Comment by gpabdo** [comment]
@carnei-ro @lyndon160 How does this PR look? https://github.com/Kong/kubernetes-ingress-controller/pull/926

**Comment by shaneutt** [comment]
Additional context available in https://github.com/Kong/kubernetes-ingress-controller/issues/1019 for anyone tracking this.

**Comment by shaneutt** [comment]
At this point @Kong/team-k8s has been given the following requirement for multi-arch/arm support to be accepted:

* we must have integration/e2e tests which test functionality and performance of the KIC on the target architecture

In conflict with this however the team does not have priority internally to add this support nor the associated maintenance costs at this time, nor along our upcoming roadmap for 2021 due to a lack of demand from customers and end-users.

For these reasons, we're considering that it may be best for us to close this issue and the related PR for now so as to best communicate that we're not planning on moving forward with this at this time, with the option to re-open it always available to us all if the surrounding circumstances change.

Before closing anything however, we wanted to reach out and check in with contributors and subscribers to this issue, please let us know what your thoughts are on this? We're open to suggestions for alternative courses of action if we can find some additional justification to do so. Thank you :bow:

**Comment by shaneutt** [comment]
> hello, wouldn't it be nice to have the arm64v8 image (dockerHub) and tweaked installation .yaml officially available? (I know it can be simple, but... I think saving time is cool)

Hi @SouzaGuilherme :wave:

Last we reported on this we didn't have enough internal cause to start supporting ARM and that hasn't changed, though we're open to suggestions that would start pushing us in the other direction: can you help us to better understand your use case?

Also we are missing raw ARM support in our CI (Github Actions) and it doesn't seem that Github has any interest in adding this:

https://github.com/actions/virtual-environments/issues/2536

So without significant further investment in CI (e.g. we would like to avoid using self-hosted runners and/or taking on extra infrastructure) we don't appear to be in a position where we can hit the ground running.

**Comment by michael-riha** [comment]
FYI for `2.3.1` I just pushed a simple `patch` & build for `arm64`

https://github.com/Kong/kubernetes-ingress-controller/issues/2441#issuecomment-1112991210

```
comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
```
