### ISSUE TITLE
KongPlugin instance_name needs suffixes on generated plugins

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#4516]
Per conversation with @hbagdi, the plugin `instance_name` field must be globally unique (or possibly workspace unique, though I don't think it should matter for us--the controller can only address a single workspace, so it can't handle cross-workspace concerns even if we wanted to).

Usage of the KongPlugin resource will attempt duplicate `instance_name` values on different Kong plugin instances in several common cases:

- The KongPlugin is applied to multiple resources.
- The KongPlugin is applied to a resource that requires multiple Kong resources, such as an Ingress that cannot be represented with a single Kong route.

In the former case, users can create separate KongPlugins, but this is not ideal. In the latter case, there is no workaround other than not using `instance_name`. 

We need some mechanism of differentiating `instance_name`  values in these cases. This would likely take the form of a short random suffix. Counters or attached resource name are also viable options, though the latter could be quite long.

UX considerations are that this value ultimately gets used as a human-friendly identifier to distinguish multiple plugins of the same type in Manager (or, I guess, jq filters in admin API output), e.g.

![instance](https://github.com/Kong/kubernetes-ingress-controller/assets/571832/3107ec6c-a8f4-4dfc-935a-4f27aced0baf)

The UI can filter on instance names and allows partial matches, so a filter for `instance-` will find both `instance-bn45` and `instance-tf5r`, so a random suffix is close enough to giving all Kong plugins from a single KongPlugin the same name.

Acceptance:

- [ ] When a KongPlugin with `instance_name` set is applied to multiple Kong resources, the resulting Kong plugins have unique `instance_name` values and Kong does not reject configuration.
- [ ] The same is true when a KongPlugin is attached to a resource that requires multiple Kong resources and thus multiple Kong plugins. AFAIK only Ingress, xRoute, and Service are the resources that can have a 1:many resource:Kong entity relationship.
- [ ] Controller documentation describes the transform we use and explains why we use it.

**Comment by mheap** [comment]
Added to KIC 2.12, but we should backport to 2.11 too
