### ISSUE TITLE
Rename the `--publish-service` flag to `--ingress-service` with alias

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4518]
### Problem statement

This issue aims to discuss a potential improvement in env var and CLI flags renaming where KIC references `publish-service`.

https://github.com/Kong/kubernetes-ingress-controller/blob/0dfd102d904c8d218b5952036182c4dbe840dea9/internal/manager/config.go#L204-L205

### Proposed solution

Rename `publish-service` to something more meaningful like e.g. `ingress-service`

### Acceptance Criteria
- [x] `--publish-service` continues to work BUT is deprecated (possibly prints a warning log entry)
- [x] `--ingress-service` works and is documented
- [x] a `breaking change` issue exists for the eventual removal (in KIC 4.0?)
- [x] Helm chart is adjusted

**Comment by mflendrich** [comment]
Can we make this change non-breaking by renaming the flag but leaving the alias behind (so that the old one still works)?
Possibly with a warning in the logs.

**Comment by pmalek** [comment]
Perhaps that could be possible with something like https://github.com/spf13/pflag#mutating-or-normalizing-flag-names

**Comment by programmer04** [comment]
It's even simpler - [MarkDeprecated(...)](https://github.com/spf13/pflag?tab=readme-ov-file#deprecating-a-flag-or-its-shorthand) does precisely what we need. It still allows users to use this flag, but prints a message about depreciation and doesn't show it in help.

**Comment by mflendrich** [comment]
Removing the breaking change label & renaming the issue now that we're settled on the non-breaking direction of deprecating & aliasing.

**Comment by pmalek** [comment]
@programmer04 Is there anything else to be done in code to account for this?

There's still 1 AC to be fulfilled for sure

> a `breaking change` issue exists for the eventual removal

Not sure which version we'd like to target this though.

**Comment by programmer04** [comment]
@pmalek 
The issue has been created
- https://github.com/Kong/kubernetes-ingress-controller/issues/4814

the only leftover is in the Helm chart, [see](https://github.com/Kong/charts/blob/21045e6d97ef9bfff324d43821b6a0ab76cd64e0/charts/kong/templates/_helpers.tpl#L457). I want to address it too as a part of this issue, I'm working on it

**Comment by rainest** [comment]
I think we should actually keep the existing `--publish-service` only:

- Breaking user-facing renames always cost some amount of migration friction and upgrade work, so they should have a strong justification. AFAIK we don't have support cases indicating this is a confusion point or a functional need to change this.
- We expose all generated routes this service, not just Ingresses. A name that's not specific to the resource kind lets us refer to the same concept (the service whose addresses we populate in route-generating resource statuses) throughout, e.g. in https://github.com/Kong/kubernetes-ingress-controller/pull/4855

The setting itself doesn't easily lend itself to a any discoverable name. Most users do not set it, as the default setting (the Kong proxy service from the same release or whatever) is fine. You override it when that can't be determined automatically (e.g. when you [deploy the controller in a separate chart release](https://github.com/Kong/charts/blob/main/charts/kong/README.md#standalone-controller-nodes)) or when you have some other proxy in front of Kong, and I'd expect you find it through documentation related to either of those tasks (though I don't think we have any for the latter).

Background is that it's the name NGINX chose when they wrote the first Ingress controller and just carried on from there. [HAProxy](https://www.haproxy.com/documentation/kubernetes-ingress/enterprise/configuration-reference/startupargs/#%E2%80%93publish-service) uses the same.

I don't think there's any official terminology in either the Ingress or GWAPI specs--they name the addresses you use in statuses, but have no designated name for their source. Some of those sources may be things other than Services (IIRC most of the cloud providers just create an ALB or whatever and assign its addresses without creating a Service), so focusing on the addresses alone kinda makes sense there.

**Comment by programmer04** [comment]
As discussed above it has been decided to not change those flags
