### ISSUE TITLE
Bump Gateway API to `0.8.0`

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#4560]
### Problem Statement

The Gateway API `v0.8.0` is going to be released. At the time of writing, [`0.8.0-rc2`](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.8.0-rc2) has been created.
Once 0.8.0 is released, we need to bump our dependency and verify that all the conformance tests work.

### Acceptance Criteria

- [ ] the Gateway API is bumped to 0.8.0
- [ ] All the core conformance tests pass
- [ ] The previously passing extended tests pass

**Comment by programmer04** [comment]
Some related work has been already started in 
- https://github.com/Kong/kubernetes-ingress-controller/pull/4551
- https://github.com/Kong/kubernetes-ingress-controller/pull/4509
