### ISSUE TITLE
Support retry when looking up installed Kong CRDs on startup or implement `DynamicCRDController` for those

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4618]
### Problem statement

When starting up KIC in an environment where the kubernetes control plane might not be reachable for  a short duration we disable controllers for those CRDs which were not detected through the means of https://github.com/Kong/kubernetes-ingress-controller/blob/5abc699aeee552945a76c82e3f7abb3e1b2fabf1/internal/manager/conditions.go#L71-L78

This has proven to be problematic because KIC doesn't retry to get those CRDs and hence never starts controllers for Kong CRDs that are installed.

### Proposed solution

Implement `DynamicCRDController` like it has been done for Gateway API controllers, e.g. https://github.com/Kong/kubernetes-ingress-controller/blob/2bafc2d8793208f14f2d1ba5a6a4a5c9d4fb31ea/internal/manager/controllerdef.go#L349-L371 or check the error returned via `meta.RESTMapper`'s `KindsFor()` https://github.com/Kong/kubernetes-ingress-controller/blob/ccafa7ca9da7fb52ba959c2ebbc0974e22497b5b/internal/controllers/utils/utils.go#L94

The latter could check for `discovery.ErrGroupDiscoveryFailed` error like so

```
	errDiscovery := &discovery.ErrGroupDiscoveryFailed{}
	if errors.As(err, &errDiscovery) {
		return false
	}
```

and perform some retry logic based on that.

**Comment by czeslavo** [comment]
Closing this as https://github.com/Kong/kubernetes-ingress-controller/pull/4641 addressed the issue of the control plane API not being available on controller start-up.
