### ISSUE TITLE
docs: add documentation for `konghq.com/rewrite` annotation

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#4625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

https://github.com/Kong/kubernetes-ingress-controller/pull/4360 added support for `https://konghq.com/rewrite` annotation.

This issue tracks the effort of adding documention for it.

### Proposed Solution

- add documentation in https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/

### Acceptance Criteria

- [ ] As a User I can find relevant information in KIC docs about `https://konghq.com/rewrite`

**Comment by programmer04** [comment]
Handled in 
- https://github.com/Kong/docs.konghq.com/pull/6086
