### ISSUE TITLE
Kong proxy cannot connect to upstream service

### ISSUE THREAD

**Issue by adambom** [Kong/kubernetes-ingress-controller#463]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

I am running Kong in Kubernetes using the ingress controller. We have multiple ingress rules configured. At first, the service is accessible without any issues, but after an extended period of time (on the order of hours) certain service calls start failing with status 502. Looking in the logs for kong proxy, we errors that look like this:

```
2019/11/21 17:06:28 [error] 33#0: *15430227 connect() failed (111: Connection refused) while connecting to upstream, client: 18.208.181.247, server: kong, request: "GET / HTTP/1.1", upstream: "http://10.245.133.73:80/", host: "*insert hostname here*"
```

Once it starts happening, it is reproducible on 100% of calls to that service until the kong pods (containing the ingress controller and the proxy) are restarted. However, not all services are affected by this issue. Just some.

This is the ingress that's having issues:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gone-monkey
  namespace: redacted
spec:
  rules:
  - host: gone-monkey.redacted.redacted.redacted.redacted
    http:
      paths:
      - backend:
          serviceName: gone-monkey
          servicePort: 80
```

Interestingly, we also see logs in the ingress controller that seem suspicious:

```
I1121 12:18:37.639654       1 status.go:201] new leader elected: kong-main-kong-6b57c9dc58-5jzgj
E1119 02:45:38.128522       1 reports.go:107] error sending report: write udp 10.249.132.220:45262->34.195.241.46:61829: write: connection refused
E1119 04:45:38.126994       1 reports.go:107] error sending report: write udp 10.249.132.220:45262->34.195.241.46:61829: write: connection refused
E1119 06:45:38.126979       1 reports.go:107] error sending report: write udp 10.249.132.220:45262->34.195.241.46:61829: write: connection refused
E1119 11:45:38.127018       1 reports.go:107] error sending report: write udp 10.249.132.220:45262->34.195.241.46:61829: write: connection refused
E1119 19:45:38.126992       1 reports.go:107] error sending report: write udp 10.249.132.220:45262->34.195.241.46:61829: write: connection refused
E1121 09:40:52.514862       1 leaderelection.go:324] error retrieving resource lock infrastructure/kong-ingress-controller-leader-kong-kong: Get https://10.249.0.1:443/api/v1/namespaces/infrastructure/configmaps/kong-ingress-controller-leader-kong-kong: dial tcp 10.249.0.1:443: connect: connection refused
E1121 09:56:09.173761       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongIngress: Get https://10.249.0.1:443/apis/configuration.konghq.com/v1/kongingresses?resourceVersion=68133203&timeout=8m37s&timeoutSeconds=517&watch=true: dial tcp 10.249.0.1:443: connect: connection refused
E1121 09:56:09.173762       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongPlugin: Get https://10.249.0.1:443/apis/configuration.konghq.com/v1/kongplugins?resourceVersion=68133203&timeout=5m33s&timeoutSeconds=333&watch=true: dial tcp 10.249.0.1:443: connect: connection refused
E1121 09:56:09.173761       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongConsumer: Get https://10.249.0.1:443/apis/configuration.konghq.com/v1/kongconsumers?resourceVersion=68133203&timeout=5m59s&timeoutSeconds=359&watch=true: dial tcp 10.249.0.1:443: connect: connection refused
E1121 09:56:09.173769       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1beta1.Ingress: Get https://10.249.0.1:443/apis/extensions/v1beta1/ingresses?resourceVersion=67714204&timeout=8m16s&timeoutSeconds=496&watch=true: dial tcp 10.249.0.1:443: connect: connection refused
```

Note that while the ingress controller is unable to connect to the Kubernetes API, our cluster is otherwise completely operational.

**Kong Ingress controller version**
0.6.0

**Kong proxy version**
[1.4](https://github.com/Kong/docker-kong/blob/3064639825d8f33fa84220993de49c5cfee5a3a9/alpine/Dockerfile)

**Kong or Kong Enterprise version**
Kong

I am running version 0.23.0 of the Kong helm chart. You can find our complete manifest (and values) [in this gist](https://gist.github.com/adambom/c2cae01fd59a2157824933c47d554925).

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:43:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: AKS
- **OS** (e.g. from /etc/os-release): Unknown. Can find out if it helps.
- **Kernel** (e.g. `uname -a`): Unknown. Can find out if it helps.
- **Install tools**: helm
- **Others**:

### What happened
Proxied service started returning 502 errors after some time in service

### Expected behvaior
Proxied service should serve the content from the upstream

### Steps To Reproduce

1. Deploy kong with the configuration specified [here](https://gist.github.com/adambom/c2cae01fd59a2157824933c47d554925) 
2. Create a service
3. Create an ingress for that service
4. Check that you can access the service
5. Wait
6. Try and access the service

**Comment by hbagdi** [comment]
@adambom, Thank you for providing the detailed issue report.

My recommendation was going to use DB-less mode, suspecting a delay in the propagating the update of targets via the database but that doesn't seem to be the case.

Some follow up questions to understand the issue more:
1. Is it possible in AKS to get logs for the Control plane, specifically the API-server? We need to figure out why the API-server is refusing connections. It will be worth-while to open a ticket with Azure asking them why the API-server is refusing connections.
2. I see that you have an HPA associated with Kong, how many instances are running when you see this problem? Also, could you share logs from those controllers as well?
3. The `reports.go` error indicate that the Kong is having trouble reaching outside the cluster as well, which could mean that the node on which Kong is running is having networking issues as well. When you see the above errors, do you see a problem with Kong's routing for other services (other than the one in question) or does that work alright?
4. Can you share more logs so that there is more context rather than just the relevant lines?

`client-go`, the underlying library has a retry logic to re-connect to the API-server when watching a resource fails. I'm not sure why that is not working.

**Comment by gillianmilne** [comment]
We seem to be experiencing the same or similar issue (can make a new ticket if you feel it is different).
In the mean time we are adding the annotation `ingress.kubernetes.io/service-upstream` to our services to see if that helps and increasing the logging level to debug.

**Kong Ingress controller version**
0.6.0

**Kong proxy version**
1.4

**Kong or Kong Enterprise version**
Kong

**Kubernetes Version**
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-29T18:43:18Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}`
```

**Cloud provider or hardware configuration:** GKE
**Install tools:** yaml (all-in-one-postgres modified to point to a postgres sql instance in gcp)


For reference: 
1. Might not be looking in the correct place for it, but not finding any other logs related to the refused requests in regards to reports.lua
2. We're running two instances in GKE, looking at the metrics for it it seems to be more than sufficiently resourced as well.
3. We do not seem to be experiencing the issue with reports.go, but we are seeing issues with reports.lua. I don't think it needs to connect to anything out of the cluster? Not sure if it is related? eg.
```
2019/11/29 18:20:01 [warn] 29#0: *15369219 [lua] reports.lua:70: log(): [reports] could not connect to TCP socket: connection refused, context: ngx.timer
```
4. What we understand to be going on is that it goes to refresh the target ips of the pods, fails and gets stuck in a state where it is unable to apply new configurations. `successfully synced configuration to Kong` logs no longer appear after this. 

```
E 2019-11-29T12:17:42.647146923Z 2019/11/29 12:17:42 [notice] 1#0: signal 17 (SIGCHLD) received from 27
 
E 2019-11-29T12:17:42.647184133Z 2019/11/29 12:17:42 [alert] 1#0: worker process 27 exited on signal 9
 
E 2019-11-29T12:17:42.699156482Z 2019/11/29 12:17:42 [notice] 1#0: start worker process 28
 
E 2019-11-29T12:17:42.810732486Z 2019/11/29 12:17:42 [notice] 28#0: *14610062 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'services' into the cache ..., context: init_worker_by_lua*
 
E 2019-11-29T12:17:42.901534838Z 2019/11/29 12:17:42 [notice] 28#0: *14610062 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'services' into the cache (in 253ms), context: init_worker_by_lua*
 
E 2019-11-29T12:17:42.901570884Z 2019/11/29 12:17:42 [notice] 28#0: *14610062 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'plugins' into the cache ..., context: init_worker_by_lua*
 
E 2019-11-29T12:17:42.915696164Z 2019/11/29 12:17:42 [notice] 28#0: *14610062 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'plugins' into the cache (in 13ms), context: init_worker_by_lua*
 
E 2019-11-29T12:17:43.005239727Z 2019/11/29 12:17:43 [notice] 28#0: *14610063 [lua] cache_warmup.lua:24: warming up DNS entries ..., context: ngx.timer
 
E 2019-11-29T12:17:43.321848620Z 2019/11/29 12:17:43 [notice] 28#0: *14610063 [lua] cache_warmup.lua:34: finished warming up DNS entries' into the cache (in 315ms), context: ngx.timer
 
E 2019-11-29T12:17:48.304872539Z 2019/11/29 12:17:48 [error] 28#0: *14610064 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/kong/runloop/balancer.lua:405: attempt to index local 'upstream' (a nil value)
 
E 2019-11-29T12:17:48.304938406Z stack traceback:
 
E 2019-11-29T12:17:48.305038624Z coroutine 0:
 
E 2019-11-29T12:17:48.305046482Z 	/usr/local/share/lua/5.1/kong/runloop/balancer.lua: in function 'create_balancer'
 
E 2019-11-29T12:17:48.305053612Z 	/usr/local/share/lua/5.1/kong/runloop/balancer.lua:739: in function 'init'
 
E 2019-11-29T12:17:48.305059494Z 	/usr/local/share/lua/5.1/kong/runloop/handler.lua:874: in function </usr/local/share/lua/5.1/kong/runloop/handler.lua:873>, context: ngx.timer
 
E 2019-11-29T12:20:01.444425944Z 2019/11/29 12:20:01 [notice] 1#0: signal 17 (SIGCHLD) received from 28
 
E 2019-11-29T12:20:01.444490852Z 2019/11/29 12:20:01 [alert] 1#0: worker process 28 exited on signal 9
 
E 2019-11-29T12:20:01.446225409Z 2019/11/29 12:20:01 [notice] 1#0: start worker process 29
 
E 2019-11-29T12:20:01.599495798Z 2019/11/29 12:20:01 [notice] 29#0: *15057629 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'services' into the cache ..., context: init_worker_by_lua*
 
E 2019-11-29T12:20:01.614849745Z 2019/11/29 12:20:01 [notice] 29#0: *15057629 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'services' into the cache (in 170ms), context: init_worker_by_lua*
 
E 2019-11-29T12:20:01.614912287Z 2019/11/29 12:20:01 [notice] 29#0: *15057629 [lua] cache_warmup.lua:42: cache_warmup_single_entity(): Preloading 'plugins' into the cache ..., context: init_worker_by_lua*
 
E 2019-11-29T12:20:01.701626325Z 2019/11/29 12:20:01 [notice] 29#0: *15057629 [lua] cache_warmup.lua:81: cache_warmup_single_entity(): finished preloading 'plugins' into the cache (in 86ms), context: init_worker_by_lua*
 
E 2019-11-29T12:20:01.795587589Z 2019/11/29 12:20:01 [notice] 29#0: *15057630 [lua] cache_warmup.lua:24: warming up DNS entries ..., context: ngx.timer
 
E 2019-11-29T12:20:02.205353327Z 2019/11/29 12:20:02 [notice] 29#0: *15057630 [lua] cache_warmup.lua:34: finished warming up DNS entries' into the cache (in 408ms), context: ngx.timer
```

**Comment by hbagdi** [comment]
@gillianmilne Do you see any timeouts in the logs of the controller?
The end result is the same but I think the cause is different for what you are seeing.
Also, I'm not sure what is sending SIGKILL to the worker process. That should not be happening.

**Comment by gillianmilne** [comment]
We're starting to think this might be related to some memory leak issues other users are reporting.
![image](https://user-images.githubusercontent.com/21034930/70001981-8187b680-15aa-11ea-8b2b-28ce246ee256.png)
This graph has memory limit utilization over time, and the pattern we've been seeing is when it maxes out and drops back down, the leader ingress controller stops syncing.
Searching the logs we're not finding anything with the timeout as a keyword. Although when the proxy container logs are included we do see a lot of these 
```
2019-12-02 23:46:15.295 AEST
2019/12/02 13:46:15 [error] 26#0: *5413019 [lua] balancer.lua:793: do_upstream_event(): failed recreating balancer for gsf-nswcertificates-ui-service.gsf-nswcertificates-ui.svc: timeout waiting for balancer for b1c8c5d2-097a-486a-a4bd-45fe1ac70a79, client: 127.0.0.1, server: kong_admin, request: "PUT /upstreams/eb97f30d-7cd4-4fd5-9c77-487261cea3a5 HTTP/1.1", host: "localhost:8444"
```

**Comment by hbagdi** [comment]
It is very likely that it is the memory leak.
There is one docker image available with the fix: `hutchic/kong:alpine-e7eae9d`.
Can you give it a go?
Please make sure to remove `securityContext` stanza from your deployment if you have one.

**Comment by gillianmilne** [comment]
This might be worse, the spike is where I scaled it to 3 pods to see if it might help.
![image](https://user-images.githubusercontent.com/21034930/70102347-82404b80-1683-11ea-9192-57fe47e48f4b.png)

It did also eventually start failing to sync after 30 minutes, these are logs from the ingress controller:
```
E 2019-12-04T00:00:30.639250Z unexpected failure updating Kong configuration:  
W 2019-12-04T00:00:30.639442Z requeuing a-namespace/a-namespace-service, err 7 errors occurred: 
E 2019-12-04T00:00:30.639556546Z 7 errors occurred:
 
E 2019-12-04T00:00:30.639569800Z 	while processing event: {Update} failed: making HTTP reqeust: Put https://localhost:8444/upstreams/5ca23e1b-8b9d-42ec-a480-fbb90a00eeb3: net/http: TLS handshake timeout
 
E 2019-12-04T00:00:30.639578956Z 	while processing event: {Update} failed: making HTTP reqeust: Put https://localhost:8444/upstreams/0dc13f49-03c8-4792-ac0f-c530ca0e46a1: net/http: TLS handshake timeout
 
E 2019-12-04T00:00:30.639585228Z 	while processing event: {Update} failed: 500 Internal Server Error {"message":"An unexpected error occurred"}
 
E 2019-12-04T00:00:30.639591998Z 	while processing event: {Update} failed: 500 Internal Server Error {"message":"An unexpected error occurred"}
```
This is how we've assigned resources in the deployment yaml
```
resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
```
It has 2 replicas in an environment with no traffic currently. There are 24 routes configured. Is it under-resourced? We believed this to be more than sufficient given what our current nginx ingress controller and older Kong deployment uses in our production environment.

Thanks for all the assistance, unfortunately we won't be able to continue testing for now though, we have moved on to deploying without the ingress controller

**Comment by adambom** [comment]
Upgrading from version 1.4.0 to version 1.4.1 seems to have fixed the issue for me. The memory profile is now flat and all the errors have gone away.

**Comment by adambom** [comment]
@gillianmilne I would suggest increasing the memory request/limit for your pods. My pods are currently consuming approximately 700MiB. The request is 1.25GiB with a limit of 2.5Gib.
