### ISSUE TITLE
Rework README to showcase Gateway API

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#4714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The repo readme only references Ingress and has zero mention of Gateway API.

### Proposed Solution

Expose Gateway API as the upcoming recommendation for working with KIC.
Add a note that this is beta (and will likely become GA very soon)

### Acceptance Criteria

- [ ] The README puts Gateway API in front of the users' eyes

**Comment by programmer04** [comment]
What is the event for Gateway API to become GA? If we have a GH issue for it, it would be beneficial to add updating README (removing mentioning about beta) to its acceptance criteria
