### ISSUE TITLE
Deprecate KongIngress CRD entirely

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#4720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Standard Ingress and gateway-api are feature reach enough to express everything, thus `KongIngress` can be entirely deprecated. 

### Additional information

Required to be resolved/resolves/obsoletes:
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/3174
- [x] https://github.com/Kong/kubernetes-ingress-controller/issues/3018
- [ ] https://github.com/Kong/kubernetes-ingress-controller/issues/4210

### Acceptance Criteria

- [x] `KongIngress.(Service|Route)` fields are not allowed to be set
- [x] `KongIngress.Upstream` field is deprecated (a warning is returned from the admission webhook)

**Comment by mflendrich** [comment]
Blocked by the issues mentioned in
> Required to be resolved/resolves/obsoletes

**Comment by czeslavo** [comment]
@mheap Is this still valid that we want to remove `KongIngress` in KIC 3.0 completely? `KongIngress.Upstream` hasn't been deprecated and dropping that might be unexpected for users. We only had it being planned in the [Using KongIngress](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-kongingress-resource/) guide: 

> The upstream section of KongIngress will be replaced with [a new resource](https://github.com/Kong/kubernetes-ingress-controller/issues/3174), but this is still in development and upstream is not officially deprecated yet.

**Comment by czeslavo** [comment]
After a short discussion I've updated the ACs to reflect what we want to actually achieve by resolving this issue.
