### ISSUE TITLE
Gateway API is the default model for service networking in KIC

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#4721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Since `gateway-api` should be released in version `1.0.0` before KIC `3.0.0`, it becomes the default model for service networking in KIC. Thus documentation, examples, etc. should be updated accordingly, and the overall experience (error messages, events, etc. should be smooth). I doesn't mean that `Ingress` becomes deprecated, it still be supported and has nice documentation.

### Additional information

The most related issues
- #3701
- #3994 
- #4654

### Acceptance Criteria

- [ ] docs are in place, default examples present usage of Gateway API
- [ ] overall experience from a user perspective is smooth

**Comment by randmonkey** [comment]
close this because `Ingress` is provided by default, but gateway APIs are not.
