### ISSUE TITLE
Gateway discovery mode is the only one supported by KIC

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#4722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Currently, Helm chart installs KIC in the following mode - every pod has one instance of Kong Gateway and the respective instance of KIC.

To use newer and more scalable and cost-efficient mode - gateway discovery 
```
ingressController.gatewayDiscovery.enabled=true 
```
has to be configured.

It should be enabled by default, other modes should be deprecated. 
 

### Additional information

Requires update in Helm chart that will become the default way of deploying KIC
- https://github.com/Kong/kubernetes-ingress-controller/issues/4712

Obsoletes
- https://github.com/Kong/kubernetes-ingress-controller/issues/4598

### Acceptance Criteria

- [ ] gateway discovery is the only supported mode
- [ ] documentation properly describes how it works
- [ ] KIC tests and supported deployment (Helm) should test/provide it

**Comment by mflendrich** [comment]
Blocked by https://github.com/Kong/kubernetes-ingress-controller/issues/4671

**Comment by mflendrich** [comment]
In fact, #4751 and #4671 satisfy 100% of the scope of what's to be done. Closing this.
