### ISSUE TITLE
Document when using DaemonSet makes sense

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#4728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Users ask us if using a `DaemonSet` instead of a `Deployment` workload when deploying KIC+Kong is possible. We should have a place in documentation that we can direct them to.

### Proposed Solution

- Add a FAQ entry explaining how to use `DaemonSet` when deploying Kong using Helm chart and when it makes sense.

### Acceptance Criteria

- [ ] https://docs.konghq.com/kubernetes-ingress-controller/latest/faq/ includes a response to "Is there any particular guidance on when to deploy KIC as a daemonset vs deployment?"

**Comment by pmalek** [comment]
@programmer04 this shouldn't be closed yet, right? We still need to answer the question from the issue title

**Comment by programmer04** [comment]
Yeah, PRs that have the word `closes` to reference the issue are evaluated as `or` not `and`, here is the PR - https://github.com/Kong/docs.konghq.com/pull/6403
