### ISSUE TITLE
feature: merge configuration from ConfigMap or Secret

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#473]
Apart from configuring via Ingress resource, make it possible also to import configuration from a specific ConfigMap or Secret. This can contain routing information for configurations which can't be represented using the Ingress API, such as:
- L4 routing
- https://discuss.konghq.com/t/workaround-kubernetes-ingress-to-allow-wildcard-hosts/5015

**Comment by shaneutt** [comment]
@hbagdi can you please shed a little bit more light on the use cases (user stories in particular) that support this request? It would just be helpful to me to have a little bit more context here.

**Comment by RobSerafini** [comment]
Waiting for customer request.
