### ISSUE TITLE
Spike: Proxy/Dataplane/Gateway/Kong Gateway naming mess

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#4732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Naming should be consistent for KOng Gateway across docs, logs, codebase, Helm chart, etc. Currently, it is referenced as 
- `proxy` (e.g. this is the name of a container with Kong Gateway deployed by Helm)
- `Kong proxy`
- ` Dataplane`
- `gateway`
- `Kong Gateway`
- etc.

### Proposed Solution

- decide on consistent naming
- implement it everywhere 

### Acceptance Criteria

- [ ] Kong Gateway is named consistently across docs, logs, codebase, Helm chart, etc.
- [ ] document it somewhere, maybe in Readme.md

**Comment by mflendrich** [comment]
This needs to be a spike because:
- "Gateway" is an overloaded term (Kong Gateway, GWAPI Gateway)
- "Control plane" is an overloaded term (hybrid mode CP vs KGO's managed mode CP)
- "Dataplane" is likewise overloaded (hybrid mode DP vs KGO's managed mode DP)
