### ISSUE TITLE
deploy-admission-controller.sh broken on MacOS

### ISSUE THREAD

**Issue by mheap** [Kong/kubernetes-ingress-controller#4787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The instructions on https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/admission-webhook do not work on MacOS.

The `base64` command on MacOS doesn't support the flags used:

```bash
curl -sL https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/main/hack/deploy-admission-controller.sh | bash
```

Output:

```
secret/kong-validation-webhook created
deployment.apps/ingress-kong patched
base64: invalid argument /var/folders/l2/vkfc3_xn4hvbymyf11phc78h0000gn/T/tmp.skWnFNHk/tls.crt
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -Dd, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
```

Is it worth fixing, or should we ignore as we're defaulting to Helm only in KIC 3.0

### Expected Behavior

The script works as expected

### Steps To Reproduce

```markdown
Run the following on MacOS:


curl -sL https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/main/hack/deploy-admission-controller.sh | bash
```
```


### Kong Ingress Controller version

```shell
N/A
```

### Kubernetes version

```shell
N/A
```

**Comment by pmalek** [comment]
@mheap #4796 should fix this. I've tested it on darwin and linux (debian) on arm64 and it worked fine. PTAL
