### ISSUE TITLE
Support for custom Kong plugins which add new auth types/endpoints ?

### ISSUE THREAD

**Issue by cewood** [Kong/kubernetes-ingress-controller#482]
### Summary

When attempting to use custom Kong plugins such as [peter-evans/kong-plugin-paseto](https://github.com/peter-evans/kong-plugin-paseto) or [mr5/kong-rbac](https://github.com/mr5/kong-rbac), and configure them declaratively using Kubernetes CRD's, the Kong/kubernetes-ingress-controller doesn't seem to handle/support this.

Am I correct in assuming that custom plugins which define their own custom Admin API endpoints/resources such as `http://kong:8001/consumers/{consumer}/paseto` or `http://kong:8001/consumers/{consumer}/rbac-roles` in the case of these two plugins, isn't supported by Kong/kubernetes-ingress-controller ?

**Kong Ingress controller version**

kong-ingress-controller:0.6.2

**Kong or Kong Enterprise version**

kong:1.3

### What happened

Kong/kubernetes-ingress-controller logs error messages about an unsupported authentication type, and thus doesn't create the resources in the Kong Admin API.

### Expected behvaior

Kong/kubernetes-ingress-controller knows how to query the available plugins via the Kong Admin API and describe what endpoints and resources they provide, and then make the correct calls necessary for the corresponding resources that have been posted to Kubernetes.

cc/ @Amzani @narsipra

**Comment by hbagdi** [comment]
> Am I correct in assuming that custom plugins which define their own custom Admin API endpoints/resources such as http://kong:8001/consumers/{consumer}/paseto or http://kong:8001/consumers/{consumer}/rbac-roles in the case of these two plugins, isn't supported by Kong/kubernetes-ingress-controller ?

That's correct. This is not yet supported.
I've not seen enough use of these to warrant adding the additional complexity to the project yet.

In your case, could you configure these via the Admin API and then configure the plugin via KongPlugin custom resource?

**Comment by cewood** [comment]
> I've not seen enough use of these to warrant adding the additional complexity to the project yet.

Makes sense, I thought this might be the case.


> In your case, could you configure these via the Admin API and then configure the plugin via KongPlugin custom resource?

This was exactly what we were thinking, albeit via an integration with some internal tools. Thanks for confirming / suggesting this, much appreciated.

I'll go ahead and close this issue now.
