### ISSUE TITLE
Add a proper docs home for kongCredType helper

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#4854]
https://github.com/Kong/kubernetes-ingress-controller/issues/2502#issuecomment-1758213596 is a script to locate credentials with the deprecated kongCredType field and generate commands to label them.

It should go into upgrade documentation, but at present the 3.x docs are just an initial skeleton without an upgrade guide or section to slot this into.

Once there is a docs page, update the KIC changelog link to the above issue comment to the permanent docs page home.

**Comment by mheap** [comment]
https://github.com/Kong/docs.konghq.com/blob/release/kic-3.0/app/_src/kubernetes-ingress-controller/upgrade/kic.md

**Comment by rainest** [comment]
Included in https://github.com/Kong/docs.konghq.com/pull/6369
