### ISSUE TITLE
Use kevholditch/gokong

### ISSUE THREAD

**Issue by marcelometal** [Kong/kubernetes-ingress-controller#487]
Hi,

What do you think about using [kevholditch/gokong](https://github.com/kevholditch/gokong) instead of redeclare all the types and methods? Ex: [types.go](https://github.com/Kong/kubernetes-ingress-controller/blob/9d0c485a3edb7b219d3485dca6fc0a2eed4256d7/internal/apis/configuration/v1/types.go)

Cheers,

**Comment by hbagdi** [comment]
We use https://github.com/hbagdi/go-kong. I'm the maintainer of that library.
That is compatible with Kong and Kong Enterprise both. It shouldn't be too hard to map the types.

The types listed in the file you've linked are Kubernetes types. They serve a different purpose and are not used as bindings to Kong's Admin API.

**Comment by marcelometal** [comment]
Ho @hbagdi ,

There are some initiatives for Kong admin API ([kevholditch/gokong](https://github.com/kevholditch/gokong), [hbagdi/go-kong](https://github.com/hbagdi/go-kong), etc). 

Why not keeping an official client?

**Comment by hbagdi** [comment]
Once we have an official Go client, we will have to add support for other languages as well.
We've been considering but not have kept one around due to maintenance cost.

> There are some initiatives for Kong admin API

There are only two currently. I'm happy to work with @kevholditch to merge them into one.
