### ISSUE TITLE
[ help request ] assign kong's pod to a specific woker node

### ISSUE THREAD

**Issue by DevOpsRoot** [Kong/kubernetes-ingress-controller#49]
Hello,

Kubernetes version : v1.10.1
kubernetes-ingress-controller version : 0.0.4

I'm trying to assign kong pod's to a specific worker node. I found in the kubernetes documentation a solution to do that :  NodeSelector ( https://kubernetes.io/docs/concepts/configuration/assign-pod-node/ ) . But when i apply this spec to the all-in-one-postgres.yaml file, i have got an error like this :

```[ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "nodeSelector" in io.k8s.api.core.v1.Container, ValidationError(Deployment.spec.template.spec.containers[1]): unknown field "nodeSelector" in io.k8s.api.core.v1.Container]; if you choose to ignore these errors, turn validation off with --validate=false```

Maybe there is another way to do that ? 
Thanks

**Comment by DevOpsRoot** [comment]
Problem solved !

**Comment by aledbf** [comment]
`nodeSelector` is located in `Deployment.spec.template.spec`

**Comment by DevOpsRoot** [comment]
Yes thanks a lot @aledbf for your response, it was an indentation error... i'm really sorry about the creation of this stupid issue !

**Comment by DiazRock** [comment]
Don't sorry that @DevOpsRoot. I got the same problem.
