### ISSUE TITLE
Configuring HTTPS redirects

### ISSUE THREAD

**Issue by Rajakavitha1** [Kong/kubernetes-ingress-controller#4907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

In the current [Configuring HTTPS redirects](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/configuring-https-redirect/) document the examples are for testing the feature using Ingress we need equivalent examples using GatewayAPIs

### Proposed Solution

Provide GatwayAPI examples

### Additional information
Dependent PR: https://github.com/Kong/docs.konghq.com/pull/6309
_No response_

### Acceptance Criteria

* Provide instructions how to configure HTTPS redirects using Gateway API resources
* Instructions may be provided as a response to this issue and @Rajakavitha1 will port to the WIP KIC 3.0 branch in docs

**Comment by rainest** [comment]
https://github.com/Kong/docs.konghq.com/pull/6335 revises the existing 2.x guide and is valid for both 2.x and 3.x AFAIK.

**Comment by Rajakavitha1** [comment]
@mheap  please suggest the PR that we should use for 3.0 https://github.com/Kong/docs.konghq.com/pull/6335 or https://github.com/Kong/docs.konghq.com/pull/6306

**Comment by mheap** [comment]
@Rajakavitha1 Please work from https://github.com/Kong/docs.konghq.com/pull/6335 and format as needed

**Comment by Rajakavitha1** [comment]
> @Rajakavitha1 Please work from [Kong/docs.konghq.com#6335](https://github.com/Kong/docs.konghq.com/pull/6335) and format as needed

Done!!!

**Comment by mheap** [comment]
Resolved in https://github.com/Kong/docs.konghq.com/pull/6335
