### ISSUE TITLE
Setting up Active and Passive health checks

### ISSUE THREAD

**Issue by Rajakavitha1** [Kong/kubernetes-ingress-controller#4908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

In the current [Setting up Active and Passive health checks](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/configuring-health-checks/) document the examples are for testing the feature using Ingress we need equivalent examples using GatewayAPIs

### Proposed Solution

Provide GatewayAPI examples

### Additional information

Helps resolve PR: https://github.com/Kong/docs.konghq.com/pull/6309

### Acceptance Criteria

* Provide instructions how to configure active/passive healthchecks using Gateway API resources
* Instructions may be provided as a response to this issue and @Rajakavitha1 will port to the WIP KIC 3.0 branch in docs

**Comment by czeslavo** [comment]
I have updated the linked docs PR with GW API and KongUpstreamPolicy usage.
