### ISSUE TITLE
Support conformance test `HTTPRouteTimeoutBackendRequest` 

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#4914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Support extended conformance test `HTTPRouteTimeoutBackendRequest` added in gateway API 1.0.0-rc1.

### Additional information

blocked by #4879

### Acceptance Criteria

- [ ] pass conformance test  `HTTPRouteTimeoutBackendRequest`

**Comment by tao12345666333** [comment]
As per GEP-1742 https://gateway-api.sigs.k8s.io/geps/gep-1742/#timeout-values  the `HTTPRouteTimeoutBackendRequest` refers to the timeout for a single request from the gateway to a backend. 

In the NGINX ecosystem, we have three parameters that can control this flow.

* `proxy_connect_timeout`
* `proxy_send_timeout`
* `proxy_read_timeout`

In Kong Gateway, we also have three parameters in the Service object. https://docs.konghq.com/gateway/latest/admin-api/#service-object


<!DOCTYPE html><meta http-equiv="content-type" content="text/html; charset=utf-8"><figure class="md-table-fig" cid="n283" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(184, 191, 198); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

connect_timeout  | The timeout in milliseconds for establishing a connection to the upstream server. Default: 60000.
-- | --
write_timeout  | The timeout in milliseconds between two successive write operations for transmitting a request to the upstream server. Default: 60000.
read_timeout  | The timeout in milliseconds between two successive read operations for transmitting a request to the upstream server. Default: 60000.


This means that `timeouts.backendRequest` should equal the sum of `connect_timeout`, `read_timeout`, and `write_time`.

**I think we should discuss assigning this value to the three parameters or setting it as a specific parameter.**

**Comment by pmalek** [comment]
After reading through the GEP-1742 and specifically the description of the `timeouts.backendRequest`:

```
    // BackendRequest specifies a timeout for an individual request from the gateway
    // to a backend. This covers the time from when the request first starts being
    // sent from the gateway to when the full response has been received from the backend.
    //
    // An entire client HTTP transaction with a gateway, covered by the Request timeout,
    // may result in more than one call from the gateway to the destination backend,
    // for example, if automatic retries are supported.
    //
    // Because the Request timeout encompasses the BackendRequest timeout, the value of
    // BackendRequest must be <= the value of Request timeout.
    //
    // Support: Extended
    //
    // +optional
    BackendRequest *Duration `json:"backendRequest,omitempty"`
```

I'm afraid that we might not be able to implement this given that read and write timeouts are related to individual operations within the whole request while the connect timeout only specifies the timeout for establishing the connection with the upstream.

**Comment by tao12345666333** [comment]
Yes.

Our team has already discussed a lot and also made records in the upstream project's issue. We will collaborate with the upstream to explore feasible solutions.
ref: https://github.com/kubernetes-sigs/gateway-api/issues/1742#issuecomment-1811367123

> capability level 1: the user setting read / write / connect timeouts by route annotations (done today)
> capability level 2: the user setting the timeouts.backendRequest in a route that KIC models in an imperfect way using connect/read/write timeouts (possible with Jintao's change)
> capability level 3: the user setting the timeouts.backendRequest in a route that KIC models in a perfect way (requires a plugin or a new feature in Kong Gateway)
> capability level 4: the GEP being extended so that read/write/connect timeouts are first class gateway api concepts (requires GEP/GWAPI CRD change but possible with Kong Gateway)
> quote by @mflendrich 


I will implement according to the second part, when the user specifies `timeouts.backendRequest`, set `ConnectTimeout`, `ReadTimeout` and `WriteTimeout` in Service **to the same value**, and clearly describe in the document what impact the user will receive.

- [ ] Modify the code to make timeouts.backendRequest effective.
- [ ] Add documentation to clearly describe this behavior.

**Comment by tao12345666333** [comment]
I have another question regarding the https://github.com/Kong/kubernetes-ingress-controller/pull/3060 that introduces a  `CombinedRoutes` feature to reduce configurations.

https://github.com/Kong/kubernetes-ingress-controller/blob/ec64c885042301e1dec7e13826b51ed9f28b14a5/internal/dataplane/translator/subtranslator/httproute.go#L71-L80


For example, we have the following configuration:


```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: timeout-example
spec:
  ...
  rules:
  - backendRefs:
    - name: some-service
      port: 8080
    matches:
      - headers:
        type: Exact
        name: Cookie
        value: client=slow
    timeouts:
      backendRequest: 5s
  - backendRefs:
    - name: some-service
      port: 8080
    matches:
      - headers:
        type: Exact
        name: Cookie
        value: client=fast
    timeouts:
      backendRequest: 2s

```

`Timeout` and `backendRefs` are at the same level. Using the current implementation logic, there will be a situation where the timeout is overwritten.
In our actual situation, I believe that because the timeout is still experimental and our implementation differs from the specification in some ways, I expect to implement this function at a lower cost.
Therefore, I think a feasible method is not to make too many modifications to the current implementation logic. 
Even if there is an overwrite situation, only keep the last one. At the same time, inform users of this behavior.
