### ISSUE TITLE
Update EKS deployment documentation

### ISSUE THREAD

**Issue by harshal-shah** [Kong/kubernetes-ingress-controller#493]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

The EKS deployment page seems to be copied from GKE and hence contains some incorrect information. 
For example: 
Service of type LoadBalancer on EKS will create an AWS ELB which does not have a external IP but instead has a hostname 
so the status field in the service shall be like below: 
~~~
    "status": {
        "loadBalancer": {
            "ingress": [
                {
                    "hostname": "testtesttesttesttest.eu-west-1.elb.amazonaws.com"
                }
            ]
        }
    }
~~~
The proxy IP export command should be as follows: 

~~~
export PROXY_IP=$(kubectl get -o jsonpath="{.status.loadBalancer.ingress[0].hostname}" service -n kong kong-proxy)
~~~

**Comment by hbagdi** [comment]
PR welcome to fix it!
