### ISSUE TITLE
New topic : Kubernetes Runtimes

### ISSUE THREAD

**Issue by Rajakavitha1** [Kong/kubernetes-ingress-controller#4938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Document supported Kubernetes versions + _why_ we choose to support those versions

### Acceptance Criteria

* Provide information on supported k8s versions and how we decide what to support e.g. cloud vendor lifetimes
* Instructions may be provided as a response to this issue and @Rajakavitha1 will port to the WIP KIC 3.0 branch in docs

**Comment by pmalek** [comment]
You can base your work @Rajakavitha1 on these:

- The existing version compat matrix https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/#kubernetes 
  - Note that we're bumping the minimum supported Kubernetes version to 1.24 (internal thread my @mheap https://kongstrong.slack.com/archives/C011RQPHDC7/p1698764618733349?thread_ts=1698757312.230499&cid=C011RQPHDC7) with the caveat that 1.24 lacks [CRD Validating Expressions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules) (or rather have it disabled by default) and `KongUpstreamPolicy` validations will be limited on that version (as those heavily use the CRD Validating Expressions
- Our user facing version support policy at https://docs.konghq.com/kubernetes-ingress-controller/latest/support-policy/
- Internal doc about supported versions https://docs.google.com/document/d/1Se04bL3JUUSjTbxz8GvyiKA0oPRJzD9NP7UXrTEYZZI/edit#heading=h.xkhc8z1tmopv (feel free to ping us to get access)
