### ISSUE TITLE
New Topic: TLS Passthrough Service Configuration

### ISSUE THREAD

**Issue by Rajakavitha1** [Kong/kubernetes-ingress-controller#4946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Requested by @mflendrich 

How to do TLS Passthrough using Gateway API resources    

### Acceptance Criteria

* Provide instructions how to do TLS passthrough using Gateway API resources
* Instructions may be provided as a response to this issue and @Rajakavitha1 will port to the WIP KIC 3.0 branch in docs

**Comment by rainest** [comment]
Both passthrough and terminate are configured in the same fashion. See the comment on terminate issue: https://github.com/Kong/kubernetes-ingress-controller/issues/4945#issuecomment-1779436681

**Comment by lahabana** [comment]
Done there: https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/services/tls/#tls-passthrough
