### ISSUE TITLE
New Topic: HA of Workloads

### ISSUE THREAD

**Issue by Rajakavitha1** [Kong/kubernetes-ingress-controller#4947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Requested by @mflendrich 

HA of your workloads (leveraging Kong's load balancing capability)   

### Acceptance Criteria

* ...
* Instructions may be provided as a response to this issue and @Rajakavitha1 will port to the WIP KIC 3.0 branch in docs

**Comment by mheap** [comment]
@mflendrich Could you help with AC here?

**Comment by lahabana** [comment]
This is not relevant anymore
