### ISSUE TITLE
Properly support extended, experimental field `Spec.CommonRouteSpec.ParentRefs[*].Port` in TCPRoute & UDPRoute

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#4958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Currently only field `Spec.CommonRouteSpec.ParentRefs[*].SectionName` is properly supported, see
- https://github.com/Kong/kubernetes-ingress-controller/pull/4928

that fixes

- https://github.com/Kong/kubernetes-ingress-controller/issues/4864

Setting `Spec.CommonRouteSpec.ParentRefs[*].Port` does not have any effect. It should work as described in the specification.

### Proposed Solution

Implement support for `Port` field as described in the [gateway-api spec](https://github.com/kubernetes-sigs/gateway-api/blob/ebe9f31ef27819c3b29f698a3e9b91d279453c59/apis/v1/shared_types.go#L121-L154).

### Additional information

Conformance tests in `gateway-api` repo for checking this doesn't exist when it was been written. Ensure that is properly tested, consider adding such test to the upstream. 

### Acceptance Criteria

- [ ] field `Spec.CommonRouteSpec.ParentRefs[*].Port` works as described in spec for TCPRoute & UDPRoute
- [ ] it is properly tested

**Comment by pangruoran** [comment]
Could you please assign this to me? thanks!
