### ISSUE TITLE
knative removal - docs update

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#4961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Extracted from #2813

The KIC docs are out of date - we need to drop the knative guides and update the feature gates documentation https://docs.konghq.com/kubernetes-ingress-controller/latest/references/feature-gates/#feature-gates-for-alpha-and-beta-features

### Proposed Solution

- update the feature gates guide for Knative removal in KIC 3.0
- walk through the docs and ensure that the knative guides are removed

### Acceptance Criteria

- [ ] Feature gates documentation is updated
- [x] Changelog clearly states that KIC 3.0 is removing support for knative
- [ ] Stale Knative guides in KIC docs are removed

**Comment by pmalek** [comment]
https://github.com/Kong/docs.konghq.com/pull/6356 doesn't yet include anything related to Knative in v3 docs.

KIC changelog already mentions that knative support was removed https://github.com/Kong/kubernetes-ingress-controller/blob/419cd078a7f7df717642a7d43c86cfbc7aaaab25/CHANGELOG.md?plain=1#L89-L90

**Comment by mheap** [comment]
KNative is not mentioned in the new docs

```
❯ fgrep -ir "knative" app/_src/kubernetes-ingress-controller; echo $?
1
```
