### ISSUE TITLE
request all return 404 

### ISSUE THREAD

**Issue by steinliber** [Kong/kubernetes-ingress-controller#50]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kong Ingress controller version**:0.04

**Kubernetes version** (use `kubectl version`):1.9

**Environment**:

- **Cloud provider or hardware configuration**:  2h4g
- **OS** (e.g. from /etc/os-release): ubuntu16.04
- **Kernel** (e.g. `uname -a`): Linux kubemaster 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubernets

**What happened**:
I have ingress configured but request return 404
Here is the Kong Ingress controller log

`
E0524 05:13:30.385111       7 kong.go:637] Unexpected error creating Kong Route: [400] {"fields":{"paths":"must not have a trailing slash"},"name":"schema violation","code":2,"message":"schema violation (paths: must not have a trailing slash)"}
E0524 05:13:30.385123       7 controller.go:130] unexpected failure updating Kong configuration:
the server rejected our request for an unknown reason (post routes.meta.k8s.io)
`

Here is the return result

`
{"message":"no route and no API found with those values"}
`

**Anything else we need to know**:

Here is my config 

`
piVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nlp-api-kong
  namespace: nlp-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: test.xxxx.com
    http:
      paths:
      - path: /article-summary/
        backend:
          serviceName: article-summary-rest-svc
          servicePort: http
`

Here is admin upstreams return 

`
 {
      "created_at": 1527135234334,
      "hash_on": "none",
      "id": "cd95daeb-f900-477b-84a4-3f4f62252fe6",
      "healthchecks": {
        "active": {
          "unhealthy": {
            "http_statuses": [
              429,
              404,
              500,
              501,
              502,
              503,
              504,
              505
            ],
            "tcp_failures": 0,
            "timeouts": 0,
            "http_failures": 0,
            "interval": 0
          },
          "http_path": "/",
          "healthy": {
            "http_statuses": [
              200,
              302
            ],
            "interval": 0,
            "successes": 0
          },
          "timeout": 1,
          "concurrency": 10
        },
        "passive": {
          "unhealthy": {
            "http_failures": 0,
            "http_statuses": [
              429,
              500,
              503
            ],
            "tcp_failures": 0,
            "timeouts": 0
          },
          "healthy": {
            "successes": 0,
            "http_statuses": [
              200,
              201,
              202,
              203,
              204,
              205,
              206,
              207,
              208,
              226,
              300,
              301,
              302,
              303,
              304,
              305,
              306,
              307,
              308
            ]
          }
        }
      },
      "name": "nlp-dev.article-summary-rest-svc.http",
      "hash_fallback": "none",
      "slots": 1000
    },
`

**Comment by subicura** [comment]
@steinliber Hello! Error message shows **paths must not have a trailing slash**. Please change `path: /article-summary/` to `path: /article-summary`, and try again.

And kong-ingress is not support `nginx.ingress.kubernetes.io/rewrite-target` annotation. Use custom-type(`KongIngress` > `proxy` > `path`.). See https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/custom-types.md.

**Comment by steinliber** [comment]
this is my config

`
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: nlp-api-kong
namespace: nlp-dev
annotations:
kubernetes.io/ingress.class: nginx
spec:
rules:
    host: test.xxxx.com
    http:
    paths:
    path: /article-summary
    backend:
        serviceName: article-summary-rest-svc
        servicePort: http
`
where is this config in kong proxy, so that i can get into container to see if config exist

**Comment by subicura** [comment]
@steinliber Can you show me services configuration? (http://kong-admin:8001/services) And What kong-ingress-controller version do you use?

**Comment by subicura** [comment]
Add this configuration.

```

**Comment by subicura** [comment]
Add this configuration.

```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: configuration-demo
  namespace: nlp-dev 
upstream:
  proxy:
    path: /
```

**Comment by steinliber** [comment]
i request http://kong-admin:8001/services. it return 

`
{
"next": null,
"data": []
}
`

my kong-ingress-controller version is 0.04

after i add your configuration, request http://kong-admin:8001/services still return like before

**Comment by steinliber** [comment]
i also use traefik as ingress , does this influence this

**Comment by steinliber** [comment]
I0524 08:47:41.162493       7 kong.go:634] creating Kong Route for host nlp-devkong.taptapcode.com, path /article-summary and service edd44bce-00b6-4bbd-a94b-620bcf2d47de
E0524 08:47:41.272720       7 kong.go:681] Route 1bb2c834-5068-4439-bd01-5292834e0b4e does not contain any plugins. Checking if it is required to remove plugins...
I0524 08:47:41.274597       7 kong.go:813] deleting Kong Route 6d3c6bb1-1788-4394-a7ba-cb5b06ae9ea0

**Comment by steinliber** [comment]
look like create success

**Comment by steinliber** [comment]
now i have services config but look like path not right

`
{
"next": null,
"data": [
{
"host": "nlp-dev.segment-rest-svc.http",
"created_at": 1527149635,
"connect_timeout": 60000,
"id": "edd44bce-00b6-4bbd-a94b-620bcf2d47de",
"protocol": "http",
"name": "nlp-dev.segment-rest-svc.http",
"read_timeout": 60000,
"port": 80,
"path": "/",
"updated_at": 1527149635,
"retries": 5,
"write_timeout": 60000
}
]
}
`

**Comment by subicura** [comment]
@steinliber How about routes info? http://kong-admin:8001/routes

**Comment by steinliber** [comment]
{
"next": null,
"data": [
{
"created_at": 1527166061,
"strip_path": false,
"hosts": [
"nlp-devkong.taptapcode.com"
],
"preserve_host": false,
"regex_priority": 0,
"updated_at": 1527166061,
"paths": [
"/article-summary"
],
"service": {
"id": "edd44bce-00b6-4bbd-a94b-620bcf2d47de"
},
"methods": null,
"protocols": [
"http"
],
"id": "1bb2c834-5068-4439-bd01-5292834e0b4e"
}
]
}

**Comment by subicura** [comment]
Oh, add strip_path: true option and try again!

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: xxx
proxy:
  path: /
route:
  strip_path: true

**Comment by steinliber** [comment]
It works, thanks
