### ISSUE TITLE
Rewrite annotation causing KIC sync loop

### ISSUE THREAD

**Issue by jeffrey-arndt** [Kong/kubernetes-ingress-controller#5021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setup:

2 Ingress objects pointing at the same service
1 Ingress with the rewrite annotation
1 Ingress without the annotation

We see that the request transformer plugin is applied at the Service level and the configuration flip flops creating and deleting the plugin in a loop

Video attached showing the behavior:

https://drive.google.com/file/d/1FYwZaSOwT-Lvin9NzTcFN2mnFxds1UAR/view?usp=sharing

### Expected Behavior

The the Ingress objects should not conflict causing a scenario where the plugin is deleted/recreated over and over

Additionally, I believe it would be better that the request transformer plugin is applied at the route level. This would allow for more granular configuration

### Steps To Reproduce

```markdown
1) Stand up a KIC + Proxy and enable the rewrite feature gate
  env:
    feature_gates: RewriteURIs=true

2) Stand up an echo service
3) Create 2 Ingress objects:

echo "
   apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: echo1
     namespace: kong
     annotations:
       konghq.com/strip-path: 'true'
   spec:
     ingressClassName: kong
     rules:
     - host: kong.example
       http:
         paths:
         - path: /echo
           pathType: ImplementationSpecific
           backend:
             service:
               name: echo
               port:
                 number: 1027
   " | kubectl apply -f -

echo "
   apiVersion: networking.k8s.io/v1
   kind: Ingress
   metadata:
     name: echo2
     namespace: kong
     annotations:
       konghq.com/rewrite: /api/foo/REWRITE
       konghq.com/strip-path: 'true'
   spec:
     ingressClassName: kong
     rules:
     - host: kong.example
       http:
         paths:
         - path: /rewrite
           pathType: ImplementationSpecific
           backend:
             service:
               name: echo
               port:
                 number: 1027
   " | kubectl apply -f -

3) Verify via Kong Manager the plugin is being delete/recreated. Check the KIC logs to see repeated sync succesful messages looping
```

### Kong Ingress Controller version

```shell
KIC 2.12 / Gateway 3.4.0.0
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by programmer04** [comment]
Rewrite is attached in KIC code on service level instead of route level

https://github.com/Kong/kubernetes-ingress-controller/blob/9ad403fff3b440868b18167fb397e9f353fa3058/internal/dataplane/translator/subtranslator/ingress.go#L444-L474

It leads to conflicts as described https://github.com/Kong/kubernetes-ingress-controller/issues/5140#issuecomment-1805264155

**Comment by programmer04** [comment]
@jeffrey-arndt yesterday releases
- [v2.12.2](https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v2.12.2)
- [v3.0.1](https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v3.0.1)

contain a fix for the reported bug

**Comment by herself** [comment]
I'm seeing the same issue with KIC 3.2 and Kong 3.7.1 and getting the same behaviour - two Ingresses with the same backing service, the rewrite gets applied randomly on requests.

Should I open a new bug? Or will this be tracked here? Any additional data I can provide?

**Comment by pmalek** [comment]
@herself 👋 

Yes, please create a new issue specifically mentioning the version that you use. Can you also try with 3.3 if the issue persists?

**Comment by herself** [comment]
Thanks - unfortunately, it seems to persist on 3.3 as well. Opened https://github.com/Kong/kubernetes-ingress-controller/issues/6542, thank you for guidance!
