### ISSUE TITLE
New Topic: Upgrading Gateway

### ISSUE THREAD

**Issue by Rajakavitha1** [Kong/kubernetes-ingress-controller#5026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

As a user I'd like to upgrade Kong Gateway that is managed by KIC.

### Acceptance Criteria

* Provide instructions how to upgrade DB-less Kong Gateway
* Provide a link to Kong Gateway upgrade instructions for DB-backed
* Instructions may be provided as a response to this issue and @Rajakavitha1 will port to the WIP KIC 3.0 branch in docs

**Comment by Rajakavitha1** [comment]
@mheap I am not able to add labels to this issue. Please help.

**Comment by czeslavo** [comment]
# Upgrading Kong Gateway when running with Kong Ingress Controller

When you're running Kong Ingress Controller, you must be aware it consists of two main components (learn more in 
[Deployment methods]).
- Kong Ingress Controller itself (a control plane),
- Kong Gateway (a data plane).

Both of them are versioned separately and as such can be upgraded separately as well. In this guide we'll show you how
to upgrade Kong Gateway when running with Kong Ingress Controller.

To see what Kong Gateway images are available, please refer to Docker Hub:

- [Kong Gateway Enterprise](https://hub.docker.com/r/kong/kong-gateway/tags)
- [Kong Gateway OSS](https://hub.docker.com/_/kong/tags)

## Prerequisites

- Kubernetes Ingress Controller installed with the use of `kong/ingress` helm chart.
- [yq] CLI installed (for YAML processing).

## Checking Kong Gateway and Kong Ingress Controller versions 

Before you start, you should check what version of Kong Gateway and Kong Ingress Controller you're currently running. 

```shell
helm get values --all kong -n kong  | yq '{
  "gateway": .gateway.image.repository + ":" + .gateway.image.tag,
  "controller": .controller.ingressController.image.repository + ":" + .controller.ingressController.image.tag
}'
```

As an output, you should get Kong Gateway and Kong Ingress Controller versions deployed in your cluster, for example:

```shell
gateway: kong:3.3
controller: kong/kubernetes-ingress-controller:2.12
```

To understand what version of Kong Gateway is compatible with your version of Kong Ingress Controller, please refer to
[Compatibility Matrix]. Before upgrading, please also make sure your Helm charts repository is up-to-date by running
`helm repo update`.

> Note: Upgrading Kong Gateway in DB mode
> 
> When you're running Kong Gateway in DB mode, you must take into account database migrations that have to be run.
> Because of that, sometimes it may be necessary to upgrade Kong Gateway from one version to another in multiple steps
> (e.g. when they're not subsequent versions).
> 
> Please refer to [Upgrade Kong Gateway 3.x.x] to learn more about upgrade paths between different versions of Kong Gateway.

## Upgrading Kong Gateway version in Helm release

To upgrade Kong Gateway version in Helm release, you can either:

- edit your `values.yaml` file used for Helm install (if you have one) and run the `helm upgrade` command with 
  `--values` flag
- pass `--set` flag to the `helm upgrade` command.

_TODO Below could be a navtab._

### `helm upgrade --set`

Run `helm upgrade` command with `--set` flag and `gateway.image.tag` set to the version of Kong Gateway you want to
upgrade to:

```shell
helm upgrade -n kong kong kong/ingress --set gateway.image.tag=3.4 --wait
```

### `helm upgrade --values`

If you have a `values.yaml` file, you can edit it and change `gateway.image.tag` to the version of Kong Gateway you want:

```yaml
gateway:
  image:
    tag: 3.4
```

and then run `helm upgrade` command with `--values` flag:

```shell
helm upgrade -n kong kong kong/ingress --values values.yaml --wait
```

The output is similar to this:

```shell
Release "kong" has been upgraded. Happy Helming!
NAME: kong
LAST DEPLOYED: Fri Nov  3 15:27:49 2023
NAMESPACE: kong
STATUS: deployed
REVISION: 5
TEST SUITE: None
```

As we pass `--wait` to `helm upgrade`, we ensure that the command only returns when the rollout finishes successfully. 
You can verify the upgrade was successful by checking the version of Kong Gateway Deployment running in your cluster:

```shell
kubectl get deploy kong-gateway -n kong -ojsonpath='{.spec.template.spec.containers[0].image}'
```

You should see now the new version of Kong Gateway:

```shell
kong:3.4
```

[Deployment methods]: https://docs.konghq.com/kubernetes-ingress-controller/2.12.x/concepts/deployment/
[yq]: https://github.com/mikefarah/yq
[Compatibility Matrix]: https://docs.konghq.com/kubernetes-ingress-controller/latest/references/version-compatibility/#kong
[Upgrade Kong Gateway 3.x.x]: https://docs.konghq.com/gateway/3.4.x/upgrade/

**Comment by Rajakavitha1** [comment]
@mheap  we can mark this issue as closed. The new PR for upgrade: https://github.com/Kong/docs.konghq.com/pull/6460

**Comment by lahabana** [comment]
Done: https://docs.konghq.com/kubernetes-ingress-controller/latest/upgrade/gateway/
