### ISSUE TITLE
Fix validating Kong image tests

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#5045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The tests to validate Kong images fails constantly:
https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6706653705
After investigation, we found the two configuration problems:
- The `router_flavor` is set to `expressions` for tests with dbless Kong, while the used KIC image is `2.12` and does not include the change to remove the `ExpressionRoutes` feature gate, so the initial configurations could never be successfully sent
- The integration tests detected that the Kong image is enterprise edition, and enables enterprise features, but the features could not be enabled because license is not provided.

### Proposed Solution

- When KIC image is below 3.0, configure router flavor to `traditional_compatible` or set feature gate `ExpressionRoutes` to true
- Skip integration tests requiring enterprise feature when license is not given

### Acceptance Criteria

- [ ] Validation of Kong has no failures caused by misconfigurations of tests

**Comment by pmalek** [comment]
@randmonkey Can you elaborate on the enterprise license aspect of this issue?

https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6706653705/job/18223679900#step:9:5 does have the license env set

> Skip integration tests requiring enterprise feature when license is not given

I'd say that

- We should **fail** the test when license is not provided but `TEST_KONG_ENTERPRISE="true"` is set
- We should skip the test if `TEST_KONG_ENTERPRISE` is not set

**Comment by pmalek** [comment]
Ok fix is for the integration tests only right? Since it uses the patched `RunWhenKongEnterprise`. The e2e failures are a separate thing.
