### ISSUE TITLE
kong dashboard manual configuration reset

### ISSUE THREAD

**Issue by maoyangcao** [Kong/kubernetes-ingress-controller#505]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary
kong dashboard manual route configuration reset，when pod restart or add new ingress.
but I have no configuration any KongIngress。

**Kong Ingress controller version**
kong-ingress-controller:0.7.0

**Kong or Kong Enterprise version**
kong:1.4

**Comment by hbagdi** [comment]
You have to use CRDs to make these changes. You cannot use any dashboard to apply your changes. If you do, they will be reset by the controller.

**Comment by maoyangcao** [comment]
but if i remove tags of routes on kong dashboard ,It will not be reset。

**Comment by maoyangcao** [comment]
> You have to use CRDs to make these changes. You cannot use any dashboard to apply your changes. If you do, they will be reset by the controller.

but if i remove tags of routes on kong dashboard ,It will not be reset。

**Comment by hbagdi** [comment]
If there is a name collision then it will be reset.
If you manually create a route with a name that doesn't clash with the Ingress Controller, then those routes will not be reset.
