### ISSUE TITLE
Move CRD validation that's possible to be done in CEL, from webhook to CRD Validation Expressions

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#5062]
### Problem statement

KIC seems to not only have started using https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules which are available in Kubernetes 1.25+.

This issue tracks the migration of webhook validation to CRD Validation Expressions where possible.

### Acceptance criteria

- [x] Webhook validations that are doable in CEL are migrated to CEL

**Comment by pangruoran** [comment]
I want to handle the error "plugin name cannot be empty". Thanks

**Comment by randmonkey** [comment]
Could we really remove the the checks in admission webhooks when moved the checks to CELs? The feature gate `CustomResourceValidationExpressions` is enabled by default in k8s 1.25 while there are still usage of 1.21. So if we remove the checks in admission webhooks, the checks will not take effect in k8s 1.24 and below.

**Comment by pmalek** [comment]
@randmonkey As per https://docs.konghq.com/kubernetes-ingress-controller/latest/reference/version-compatibility/#general we're support k8s 1.25+ with KIC v3 so we should be good in this regard.

**Comment by pmalek** [comment]
I've gone through the code in [`internal/admission/`](https://github.com/Kong/kubernetes-ingress-controller/blob/2bcd01a6a69dfeaff9d23d8445cd5d6c28329626/internal/admission) and I haven't found any further opportunities to replace validations there to CRD validation expressions. 

If you happen to find any please, feel free to re-open this.

---

1 lesson from reading that code though, is that we have Gateway API related code in admission webhook which most likely should land in controller's code (in order to reconcile those objects into appropriate status conditions). 


Started team discussion on this: https://kongstrong.slack.com/archives/C011RQPHDC7/p1700161029335029 which will probably result in a net new issue to remove those validations from admission webhook.
