### ISSUE TITLE
Revise CRD code markers/validations

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#5105]
### Problem statement

#5103 tries to solve #5061 but leaves the CRD validations unreviewed.

For instance: 

- `KongConsumer`'s `Username` is required ([enforced in admission webhook](https://github.com/Kong/kubernetes-ingress-controller/blob/a364f353c4733ec1c7a607915aa8237affdd9935/internal/admission/validator.go#L108-L111)) but that could easily be changed to a required field on the CRD level via:

  ```
	  // +kubebuilder:validation:Required
	  Username string `json:"username"`
  ```

  This unfortunately can only be done when the `// +kubebuilder:validation:Optional` is removed from the package as that overrides the field level setting.

### Acceptance criteria

- [ ] All Kong provided CRDs are reviewed for moving validation code from admission webhook to CRD level and all possible changes are merged to `main`

**Comment by randmonkey** [comment]
@pmalek Please check if there are nothing in the current webhook that can be moved to CRD annotations.
