### ISSUE TITLE
question: Why do I need to set it twice delete event chan？

### ISSUE THREAD

**Issue by chenjinxuan** [Kong/kubernetes-ingress-controller#513]
![image](https://user-images.githubusercontent.com/25172225/72791322-15543580-3c72-11ea-9010-c3deafa1efc2.png)
https://github.com/Kong/kubernetes-ingress-controller/blob/master/internal/ingress/controller/event_handler.go

**Comment by hbagdi** [comment]
This is an oversight. There is no need to send the delete event twice.

Although, this should not result in any bug as multiple events are idempotent.

@chenjinxuan Can you send a PR to fix this?

**Comment by chenjinxuan** [comment]
> This is an oversight. There is no need to send the delete event twice.
> 
> Although, this should not result in any bug as multiple events are idempotent.
> 
> @chenjinxuan Can you send a PR to fix this?

It was my pleasure

**Comment by hbagdi** [comment]
Fixed in #514
