### ISSUE TITLE
The dependency on the `deck` Go module is eradicated from KIC

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#5153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

https://github.com/Kong/deck/issues/1060 is extracting the database reconciliation logic into a brand new Go module that will be called `go-database-reconciler`.

### Proposed Solution

Eradicate the use of the `deck` module (in favor of `go-kong` and `go-database-reconciler`).
This includes transitive depedencies (KTF is known to be one at the moment of writing, as Travis described in https://github.com/Kong/deck/issues/1060#issuecomment-1793273349).

### Acceptance Criteria

- [x] If I grep `go.mod` and `go.sum` for `github.com/kong/deck`, there should be no matches.

**Comment by rainest** [comment]
Completed in https://github.com/Kong/kubernetes-ingress-controller/pull/5156
