### ISSUE TITLE
docs: create `ReferenceGrant` documentation

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#5154]
### Problem statement

After introducing support for Gateway v1 we seem to only have `ReferenceGrant` documented in the example: https://github.com/Kong/kubernetes-ingress-controller/blob/628fe6a585abb5b1cb49568c597fd68e319a2668/examples/gateway-referencegrant-httproute.yaml.

### Acceptance criteria

- [x] Gateway API's `ReferenceGrant` is documented in https://docs.konghq.com/kubernetes-ingress-controller/latest/

**Comment by CAcquaviva** [comment]
We should include documentation for AllowedRoutes also.

**Comment by czeslavo** [comment]
Done: https://github.com/Kong/docs.konghq.com/pull/6677
