### ISSUE TITLE
CI: Document modifications do not require running all tests.

### ISSUE THREAD

**Issue by tao12345666333** [Kong/kubernetes-ingress-controller#5206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

We have files that only contain documents. When we make changes to them, we don't need to run all tests.

e.g.
* README.md and  other `*.md`
* `docs`
* `keps`

https://github.com/Kong/kubernetes-ingress-controller/actions/runs/6939756390?pr=5193

### Proposed Solution

we can add a path filter.

* https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
* https://github.com/dorny/paths-filter

**Comment by programmer04** [comment]
Reopened by revert done in #5225
