### ISSUE TITLE
Support conformance test case `unresolved-gateway-with-one-attached-unresolved-route` 

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#5247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

A new conformance test case related to the `AttachedRoutes` has been created upstream but has not yet been released. This is a core test and needs to be addressed to be conformant with the next Gateway API iterations.

Test case:

https://github.com/mlavacca/gateway-api/blob/main/conformance/tests/gateway-with-attached-routes.go#L95-L128

### Acceptance Criteria

- [ ] run and pass the conformance test `unresolved-gateway-with-one-attached-unresolved-route`

**Comment by tao12345666333** [comment]
Could you assign it to me?

**Comment by tao12345666333** [comment]
![image](https://github.com/Kong/kubernetes-ingress-controller/assets/3264292/73ac1250-d2ed-4f14-aed7-5b17edd785e2)

After verification, KIC has passed the test case.
I have already communicated with Mattia, we can close this issue now.
