### ISSUE TITLE
Flaky ingress test case `TestIngressRewriteURI`

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#5272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

The integration test case `TestIngressRewriteURI` is flaky. Failing runs:
- https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7083522718/job/19276085373
- https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7057987758/job/19212681226#step:6:1925

### Acceptance Criteria

- [ ] Integration test case  `TestIngressRewriteURI`  is not flaky

**Comment by programmer04** [comment]
I've checked on Buildpulse, and in the last 14 days no flakes where reported. I think your #5287 fixed this and issue can be closed. WDYT @randmonkey?

**Comment by randmonkey** [comment]
I think it is OK to close this since no flakes reported.
