### ISSUE TITLE
No way to modify the deployment created by the KongIngress CRD without patching it

### ISSUE THREAD

**Issue by r0fls** [Kong/kubernetes-ingress-controller#53]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Kong Ingress controller version**:
I created the resources directly from https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml

**What happened**:
I need to add things like pod labels and resources to the kong ingress controller deployment, but can't find docs on the kong CRDs, and don't know if doing that is supported.

**What you expected to happen**:
I expected adding pod labels and other customizations, such as resource requests/limits, to the kong deployment to be supported.

**How to reproduce it** (as minimally and precisely as possible):
Try adding a custom label to the kong deployment without patching it.

**Comment by devdavidkarlsson** [comment]
Not sure if I follow: how do you want to add a label to a kubernetes deployment if not by patching using for example kubectl.

**Comment by r0fls** [comment]
IMHO It should be a field on one of the CRDs. I consider patching resources manually to be a last resort.

**Comment by r0fls** [comment]
For instance, if there was a kong ingress controller deployment included directly in the all-in-one-postgres.yaml resources, i could edit the yaml. This is needed for building the cluster consistently from configuration, and avoiding using bash scripts to do so.

**Comment by r0fls** [comment]
The nginx ingress controller supports this via values supplied to their helm chart, as an example.

**Comment by aledbf** [comment]
Closing. As @devdavidkarlsson said, you can customize the deployment.

> The nginx ingress controller supports this via values supplied to their helm chart, as an example.

There is no helm chart for the ingress controller.
