### ISSUE TITLE
Allow multiple key/value pairs per secret for Consumer credentials

### ISSUE THREAD

**Issue by timduhenchanter** [Kong/kubernetes-ingress-controller#531]
With 0.7.1 we can now use secrets for credentials which is great and thank you for the addition!  

However, my team is using AWS Secrets Manager as the backbone of our secret management and it's pay per secret.  The current implementation is 1:1 secret:credential but it would be helpful and more cost effective for at least a subset of us to be able to store multiple key/value pairs with references to credentials in a single Kubernetes secret.

**Comment by hbagdi** [comment]
Are you thinking of storing multiple secrets related to the same consumer in a secret?
Or do you wish to store multiple secrets associated with different consumers in the same secret. If the latter, then how will you solve the problem of associating these secrets with different consumers?

**Comment by timduhenchanter** [comment]
My original thought was to just be able to store multiple key/value pairs in a secret tied to a single consumer.  I don't really have a business requirement to add the additional complexity of a secret being used across consumers but if you have a simple implementation in mind then I'm all for it.

**Comment by hbagdi** [comment]
> My original thought was to just be able to store multiple key/value pairs in a secret tied to a single consumer.

This could make sense and I was never aware of a use-case for this.

What is your current use-case for having multiple credentials for the same consumer?

**Comment by timduhenchanter** [comment]
AWS Secrets are being pulled by https://github.com/godaddy/kubernetes-external-secrets and each AWS Secret is currently $0.40.  In order to maintain how secrets are fetched if we could store multiple keys in a single secret it would greatly reduce the cost of secret storage and also keep the namespace tidy where all consumer secrets could be stored in a single location.

**Comment by timduhenchanter** [comment]
@hbagdi any thoughts on this since the request was raised?  This is blocking our adoption of the ingress-controller.

**Comment by hbagdi** [comment]
This is on our roadmap but not a priority at the moment.
We will happily work with anyone in the community if they come up with a design proposal (and then a subsequent PR to implement it).

**Comment by RobSerafini** [comment]
Stale. Please update if you still have needs here.
