### ISSUE TITLE
e2e failure: TestDeployAndUpgradeAllInOnePostgres in nightly tests against unreleased Kong

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#5313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

e2e test case `TestDeployAndUpgradeAllInOnePostgres` starts to fail against unreleased Kong since https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7096222874. 
After checking the diagnostics, we found the new pod stucks in `PodInitializing` state, and the `wait-for-migrations` has the following logs:
```
2023-12-08T04:38:45.79252952Z stdout F Executed migrations:
...
2023-12-08T04:38:45.792622013Z stdout F New migrations available:
...
2023-12-08T04:38:45.792750823Z stdout F Run 'kong migrations up' to proceed
2023-12-08T04:38:48.362110045Z stderr F 2023/12/08 04:38:48 [warn] Database has pending migrations from a previous upgrade, and new migrations from this upgrade (version 3.6.0.0-enterprise-edition)
```
Seems that the wait for migration job (on upcoming Kong 3.6) should be reviewed.

### Proposed Solution

- Fix the job to migrate data in upgrading Kong with database

### Acceptance Criteria

- [ ] TestDeployAndUpgradeAllInOnePostgres passes.

**Comment by randmonkey** [comment]
After testing locally, the failures only happens on the nightly version of Kong gateway enterprise edition (image `kong/kong-gateway-dev:nightly`).  The test passes for 3.5.0.0 enterprise, and also latest nightly of Kong gateway OSS. The logs of `kong-migrations` has the following error:
```
Error: [PostgreSQL error] cluster_mutex callback threw an error: /usr/local/share/lua/5.1/kong/workspaces/counters.lua:172: ERROR: null value in column "workspace_id" violates not-null constraint
Failing row contains (null, rbac_roles, 3).
stack traceback:
	[C]: in function 'assert'
	/usr/local/share/lua/5.1/kong/workspaces/counters.lua:172: in function 'postgres_run_query_in_transaction'
	/usr/local/share/lua/5.1/kong/workspaces/counters.lua:196: in function 'pg_initialize_counters_migration'
	/usr/local/share/lua/5.1/kong/workspaces/counters.lua:202: in function 'initialize_counters'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:45: in function 'reinitialize_entity_counters'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:142: in function </usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:94>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/db/init.lua:408: in function </usr/local/share/lua/5.1/kong/db/init.lua:358>
	[C]: in function 'pcall'
	/usr/local/share/lua/5.1/kong/concurrency.lua:66: in function 'cluster_mutex'
	/usr/local/share/lua/5.1/kong/cmd/utils/migrations.lua:94: in function 'up'
	/usr/local/share/lua/5.1/kong/cmd/migrations.lua:329: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:38: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:38>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:38: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:22>
	(command line -e):7: in function 'inline_gen'
	init_worker_by_lua(nginx.conf:161):44: in function <init_worker_by_lua(nginx.conf:161):43>
	[C]: in function 'xpcall'
	init_worker_by_lua(nginx.conf:161):52: in function <init_worker_by_lua(nginx.conf:161):50>

  Run with --v (verbose) or --vv (debug) for more details
```
Need to review the migration steps from 3.2 to 3.6.

**Comment by tao12345666333** [comment]
Can you provide the sha value of this image? The image is overwritten with the same tag after each build.

**Comment by randmonkey** [comment]
> * kong/kong-gateway-dev:nightly

`d3224acb758959e8f83bf1acc7e9410903409f75810a770bddd70430f12c9521`

**Comment by randmonkey** [comment]
Update: the migration (`kong migrations up` command) still fails on `kong:latest` to `kong/kong-gateway-dev:nightly` (3.5 CE -> 3.6 EE) and `kong/kong:latest-ubuntu` to `kong/kong-gateway-dev:nightly` (effectively 3.6 CE -> 3.6 EE). 
But when we run `kong migrations finish` after failing to run `kong migrations up`, it succeeds and then we can run  `kong/kong-gateway-dev:nightly` successfully.
