### ISSUE TITLE
Ingress Controller 0.7.1 Crashes when Kubernetes Secret is not formatted as expected

### ISSUE THREAD

**Issue by timduhenchanter** [Kong/kubernetes-ingress-controller#532]
### Summary
Kong Ingress Controller Crashes when Kong Credential secret does not contain key `key`

**Kong Ingress controller version**
0.7.1

**Kong or Kong Enterprise version**
1.4.3

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:51:44Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

### Environment
AWS EKS

### What happened
Kong Ingress Controller Crashes trying to read in a secret that does not have a key in the secret named "key"

### Expected behavior
Kong Ingress Controller will gracefully handle this without null pointer exception resulting in crash

### Steps To Reproduce

1. Create a secret with key `kongCredType` and do not create a subsequent key named `key`

### Output
```
E0207 19:49:04.782376       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 277 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x142a600, 0x2229630)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x82
panic(0x142a600, 0x2229630)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/hbagdi/deck/file.(*stateBuilder).ingestKeyAuths(0xc000ec99f0, 0xc00032b0a0, 0x2, 0x2, 0x2, 0xc00032b0a0)
	/go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:222 +0x408
github.com/hbagdi/deck/file.(*stateBuilder).consumers(0xc000ec99f0)
	/go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:161 +0x57b
github.com/hbagdi/deck/file.(*stateBuilder).build(0xc000ec99f0, 0x0, 0x0, 0x4)
	/go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:56 +0x124
github.com/hbagdi/deck/file.Get(0xc0009e00e0, 0xc000049200, 0x1, 0x4, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/reader.go:51 +0x130
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).onUpdateDBMode(0xc0009a6000, 0xc0009e00e0, 0x13c6960, 0xc000c7a8e0)
	/kong-ingress-controller/internal/ingress/controller/kong.go:161 +0x1c4
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).OnUpdate(0xc0009a6000, 0xc000650a80, 0x0, 0x0)
	/kong-ingress-controller/internal/ingress/controller/kong.go:63 +0x26c
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).syncIngress(0xc0009a6000, 0x149a360, 0xc000156820, 0xc017934d78, 0x2adca41b2681c)
	/kong-ingress-controller/internal/ingress/controller/controller.go:117 +0x1fa
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).worker(0xc00046fce0)
	/kong-ingress-controller/internal/ingress/task/queue.go:111 +0x2df
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005407a8)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ec9fa8, 0x3b9aca00, 0x0, 0x1, 0xc00051e2a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).Run(0xc00046fce0, 0x3b9aca00, 0xc00051e2a0)
	/kong-ingress-controller/internal/ingress/task/queue.go:59 +0x6b
created by github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).Start
	/kong-ingress-controller/internal/ingress/controller/controller.go:232 +0xe8
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11ab8c8]
goroutine 277 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x142a600, 0x2229630)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/hbagdi/deck/file.(*stateBuilder).ingestKeyAuths(0xc000ec99f0, 0xc00032b0a0, 0x2, 0x2, 0x2, 0xc00032b0a0)
	/go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:222 +0x408
github.com/hbagdi/deck/file.(*stateBuilder).consumers(0xc000ec99f0)
	/go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:161 +0x57b
github.com/hbagdi/deck/file.(*stateBuilder).build(0xc000ec99f0, 0x0, 0x0, 0x4)
	/go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/builder.go:56 +0x124
github.com/hbagdi/deck/file.Get(0xc0009e00e0, 0xc000049200, 0x1, 0x4, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/hbagdi/deck@v0.7.1-0.20191223190449-3d9f90945d9d/file/reader.go:51 +0x130
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).onUpdateDBMode(0xc0009a6000, 0xc0009e00e0, 0x13c6960, 0xc000c7a8e0)
	/kong-ingress-controller/internal/ingress/controller/kong.go:161 +0x1c4
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).OnUpdate(0xc0009a6000, 0xc000650a80, 0x0, 0x0)
	/kong-ingress-controller/internal/ingress/controller/kong.go:63 +0x26c
github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).syncIngress(0xc0009a6000, 0x149a360, 0xc000156820, 0xc017934d78, 0x2adca41b2681c)
	/kong-ingress-controller/internal/ingress/controller/controller.go:117 +0x1fa
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).worker(0xc00046fce0)
	/kong-ingress-controller/internal/ingress/task/queue.go:111 +0x2df
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005407a8)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ec9fa8, 0x3b9aca00, 0x0, 0x1, 0xc00051e2a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88
github.com/kong/kubernetes-ingress-controller/internal/ingress/task.(*Queue).Run(0xc00046fce0, 0x3b9aca00, 0xc00051e2a0)
	/kong-ingress-controller/internal/ingress/task/queue.go:59 +0x6b
created by github.com/kong/kubernetes-ingress-controller/internal/ingress/controller.(*KongController).Start
	/kong-ingress-controller/internal/ingress/controller/controller.go:232 +0xe8
```

**Comment by guneemwelloeux** [comment]
The problem actually shows up if a secret is created and missing one of the fields required for the specified `kongCredType`. For example, creating a `basic-auth` type credential, with a missing `username` key will cause the same issue.

**Comment by rainest** [comment]
Confirmed still present on 1.0.0. This stems from insufficient sanity checks in deck, which we leverage for DB-backed KIC instances. https://github.com/Kong/deck/pull/223 adds those sanity checks, but we'll still want to add additional controller logic to print information about the problem resource once it's in.

**Comment by rainest** [comment]
Bother--we probably cannot produce useful errors for this because we generate the aggregate desired state from K8S resources and then pass that in its entirety to deck. Any deck-level errors bubble up to https://github.com/Kong/kubernetes-ingress-controller/blob/1.0.0/internal/ingress/controller/controller.go#L120-L123 via https://github.com/Kong/kubernetes-ingress-controller/blob/1.0.0/internal/ingress/controller/kong.go#L279-L281 (I think--doesn't look like it'd be from one of the other error returns).

We could maybe try to catch this earlier in the per-credential type code at https://github.com/Kong/kubernetes-ingress-controller/blob/1.0.0/internal/ingress/controller/parser/kongstate/consumer.go#L29-L35 instead. I don't particularly like adding additional validation logic into the controller if possible, but we may not have a better option here.

**Comment by rainest** [comment]
Doesn't appear that we can handle this in that section of consumer.go (SetCredential) either. That runs after deck generates state, so assuming the deck change goes in, trying to check there won't work, as we'll have already entered the sync failure loop.

@timduhenchanter and/or @guneemwelloeux do you have any context around how/why those problem credentials got created in the first place? While the proposed change is an improvement (the controller no longer crashes) it's not a great one (the controller will get stuck in a state while it's continuously logging the same, not particularly helpful error). We'll probably want to augment that with documentation as such, to the effect of "if you see this error, you need to search through credentials to find which are missing critical fields manually", and knowing the background here should help us write that more clearly.

**Comment by timduhenchanter** [comment]
@rainest We are using a GitOps model and developers have full access in their repo to their Kubernetes definitions. We have some OPA Gatekeeper admission controller rules around it now but at the time it crashed all services routed via Kong. That being said considering Kong has such a significant impact -- crash avoidance for an individual misconfiguration would be ideal.
