### ISSUE TITLE
Implement `KongVault` controller and translator to translate and apply configuration of custom Kong vaults

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#5333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Split from #4559.

The issue tracks the implementation of controller and translator of `KongVault` that reconciles `KongVault` resources and translate them to configurations of custom Kong vaults, then apply the configuration on Kong gateway(s). 

### Proposed Solution

- Implement a `KongVault` controller to reconcile and store `KongVault` resources
- Add a translator to translate `KongVault` to configuration of custom Kong vault and apply the config on Kong gateway

### Acceptance Criteria

- [ ] `KongVault` resources are correctly translated and configured on Kong gateway.

**Comment by randmonkey** [comment]
Finished in multiple PRs.

**Comment by programmer04** [comment]
`KongVault` should be handled in https://github.com/Kong/kubernetes-ingress-controller/blob/b8b543cda0dddeb5de2d4cc267eb881bbec7c206/internal/dataplane/configfetcher/kongrawstate.go#L14-L172 too @randmonkey, see https://github.com/Kong/kubernetes-ingress-controller/issues/5377

**Comment by pmalek** [comment]
This should include the RBAC rules being added to role in the chart:

```
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongvaults
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configuration.konghq.com
  resources:
  - kongvaults/status
  verbs:
  - get
  - patch
  - update
```

Currently `nightly` fails with `ingress` chart 0.10.1:

```
kong-controller-88b76dcb6-4xlx5 ingress-controller W0123 10:24:21.089708       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: failed to list *v1alpha1.KongVault: kongvaults.configuration.konghq.com is forbidden: User "system:serviceaccount:kong:kong-controller" cannot list resource "kongvaults" in API group "configuration.konghq.com" at the cluster scope
kong-controller-88b76dcb6-4xlx5 ingress-controller E0123 10:24:21.089780       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1alpha1.KongVault: failed to list *v1alpha1.KongVault: kongvaults.configuration.konghq.com is forbidden: User "system:serviceaccount:kong:kong-controller" cannot list resource "kongvaults" in API group "configuration.konghq.com" at the cluster scope
```
