### ISSUE TITLE
Log the detailed error and generate events when failed to fill in defaults of plugins

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#5341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Currently the `ToDeckContent` function does not log the actual error message returned from `fillPlugin`. This brings difficulty to troubleshoot when filling default values. We need to record the actual error somewhere -- in logs and k8s events.

### Proposed Solution

- Record the error returned from `fillPlugin` function in logs
- Emit an event to record the error when the failure happens

### Additional information

May need to backport to 2.12.x or 3.0.x?

### Acceptance Criteria

- [ ] Actual error in filling plugins can be seen in logs and k8s events.

**Comment by tao12345666333** [comment]
Does it need to be backported to v2.12.x?

**Comment by randmonkey** [comment]
> Does it need to be backported to v2.12.x?

I think we should at least implement the logging of concrete errors in `fillPlugin` in 2.12.x (and it should be easy and harmless to implement). Currently we did not include concrete errors in 2.12.x: https://github.com/Kong/kubernetes-ingress-controller/blob/9efed3f009b9a4e4d91db351776740100d80b0a3/internal/dataplane/deckgen/generate.go#L74.
But we already include the error logs, so I think the proper actions are:
- implement logging the concrete error in 2.12.x
- implement emitting proper events in main (in 3.1.x)

**Comment by randmonkey** [comment]
Done in #5346.
