### ISSUE TITLE
Bump actions upload-artifact and download-artifact from 3 to 4

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#5357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Updating
- actions/upload-artifact - doesn't allow upload multiple times with the same name - [breaking change](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes)
- actions/download-artifact -  [breaking changes](https://github.com/actions/download-artifact/tree/v4/?tab=readme-ov-file#breaking-changes)

have to be done together and require adjustments in workflows, because currently, we reuse names in workflows
![image](https://github.com/Kong/kubernetes-ingress-controller/assets/9593424/757527c3-1904-4082-bc4d-480ba0cf82da)

Supersedes
- https://github.com/Kong/kubernetes-ingress-controller/pull/5350
- https://github.com/Kong/kubernetes-ingress-controller/pull/5348

### Acceptance Criteria

- [ ] actions are bumped from 3 to 4 and everything works as used to work

**Comment by rainest** [comment]
I attempted an upgrade that changed names around, but ran into an issue handling the [consolidation step](https://github.com/Kong/kubernetes-ingress-controller/blob/a74df3eec44c122d250ba3b7470d65390b9d6d50/.github/workflows/_test_reports.yaml).

Our current download jobs rely on all artifacts having the same name, which isn't possible on v4. Downloading currently only supports a single name or downloading all artifacts, without any obvious designated pattern for separating out different groups (codecov versus buildpulse, in our case).

https://github.com/actions/download-artifact/issues/248#issuecomment-1859310198 proposes adding a `name-prefix` option that looks like what we'd need, but is pending review.

**Comment by programmer04** [comment]
Version [4.1.0](https://github.com/actions/download-artifact/releases/tag/v4.1.0) contains this feature
- https://github.com/actions/download-artifact/pull/259
