### ISSUE TITLE
Custom Resources to add ca-certificate

### ISSUE THREAD

**Issue by elkh510** [Kong/kubernetes-ingress-controller#536]
Hi
we use kong kubernetes-ingress-controller
is some Custom Resources available to add ca-certificate?
the option of adding via rest api is not suitable.
thanks!

**Comment by hbagdi** [comment]
Perfect timing.
We have this as a backlog item as well.

@elkh510, in your use-case, would storing the CA certificate in a Kubernetes Secret or ConfigMap work rather than another CRD?

**Comment by elkh510** [comment]
Hello
we use Kong for Kubernetes.
There is a need to use MTLS.
we create the mtls plugin in this way:

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: mtls-auth
plugin: mtls-auth
disabled: false
config:
  ca_certificates:
    - $ {ca_certificates_id}
  skip_consumer_lookup: true
  consumer_by: []
  authenticated_group_by: "CN"
```

but before creating you need to know $ {ca_certificates_id}.
I would like to have a CRD, in which you can add your own (or generate automatically with the specified parameters) ca certificate, and in Plugin ("mtls-auth", the example of which is given above), refer to this CRD.
Based on how we use Kong for Kubernetes now, it would be convenient to store the ca certificate in Kubernetes "Secret", which will have 2 fields: 
one for certification,
second for ca certificates id

**Comment by merlineus** [comment]
@hbagdi do you mean that it is possible to use Kubernetes secret or ConfigMap with mtls-auth plugin?

**Comment by hbagdi** [comment]
> do you mean that it is possible to use Kubernetes secret or ConfigMap with mtls-auth plugin?

No it is not possible to use it today but it is something that is high on priority list.

> Based on how we use Kong for Kubernetes now, it would be convenient to store the ca certificate in Kubernetes "Secret", which will have 2 fields

What if the secret has only a single field to store the CA cert and we re-use the UID of the secret resource as the ID in Kong's database? Does that work? The reason for doing this is to minimize the amount of configuration that the user has to provide, which also reduces the scope of errors.

**Comment by romanp-lohika-tix** [comment]
>What if the secret has only a single field to store the CA cert and we re-use the UID of the secret resource as the ID in Kong's database? Does that work? The reason for doing this is to minimize the amount of configuration that the user has to provide, which also reduces the scope of errors.

if in the field "ca_certificates"  will be an opportunity to refer to a secret with CA cert, yes, for us it will work.
```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: mtls-auth
plugin: mtls-auth
disabled: false
config:
  ca_certificates: // **opportunity to refer to a secret with CA cert**
    - $ {ca_certificates_id}
  skip_consumer_lookup: true
  consumer_by: []
  authenticated_group_by: "CN"
```

**Comment by hbagdi** [comment]
Yes, you will be able to specify the cert ID materialistically.
Thank you for your response @romanp-lohika-tix!

**Comment by merlineus** [comment]
Hello @hbagdi, do you have ETA for this to be implemented? Absence of this feature makes our configuration a very complicated process on a big amount of mtls-auth plugins.

**Comment by elkh510** [comment]
Hello @hbagdi
any updates ?

**Comment by wasdee** [comment]
set env `KONG_SSL_CERT`  and `KONG_SSL_CERT_KEY`
`ca_bundled.crt` is created by concat `cert.crt` and `ca_cert.cert` together.

```
kong:
    image: kong:3.8
    ports:
      - ${KONG_HTTP_PORT}:8000/tcp
      - ${KONG_HTTPS_PORT}:8443/tcp
      - 8001:8001
      - 8002:8002
      - 8444:8444
    environment:
      KONG_SSL_CERT: /certs/ca_bundled.crt
      KONG_SSL_CERT_KEY: /certs/cert.key
    volumes:
      - ./Volumes/certs:/certs:ro
 ```

ref. [https://www.linkedin.com/pulse/kong-api-management-ssl-configuration-g-manoj-kumar-reddy]
