### ISSUE TITLE
credType not recognized

### ISSUE THREAD

**Issue by kingwill27** [Kong/kubernetes-ingress-controller#537]
### Summary

When using secret-based credentials, the ingress controller appears to find the secret but does not load the `credType` successfully, instead only loading an empty string. Below are the logs and a screenshot of the secret, displaying the credType value.

E0210 20:39:47.760737       1 parser.go:312] invalid credType in secret 'ex/auth-t77757c246'
E0210 20:39:47.760763       1 parser.go:316] invalid credType '' in secret 'ex/auth-t77757c246'

![image](https://user-images.githubusercontent.com/26404333/74188356-dc293880-4c13-11ea-9818-863341981da8.png)

Additionally, are there any documentation or guides demonstrating how to properly use the secret-based credentials?

**Kong Ingress controller version**: 7.1

**Kong or Kong Enterprise version**: 1.4

**Comment by hbagdi** [comment]
Are you sure you have `credType` set in Secret's data?

Here is a guide that walks through this setup: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-consumer-credential-resource.md#provision-a-consumer

**Comment by kingwill27** [comment]
I was using `credType` and not `kongCredType` - looks like things are working now, thank you for linking that documentation!
