### ISSUE TITLE
Flaky integration test: `TestValidationWebhook/should_fail_the_validation_if_the_secret_in_ConfigPatches_of_KongClusterPlugin_generates_invalid_configuration`

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#5375]
### Problem statement

During one of the kong image validation workflow runs the `TestValidationWebhook/should_fail_the_validation_if_the_secret_in_ConfigPatches_of_KongClusterPlugin_generates_invalid_configuration` test has failed but it shouldn't (it passed on [re-run](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7286242198))

```
    webhook_test.go:891: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/webhook_test.go:891
        	Error:      	An error is expected but got nil.
        	Test:       	TestValidationWebhook/should_fail_the_validation_if_the_secret_in_ConfigPatches_of_KongClusterPlugin_generates_invalid_configuration
```

https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7286242198/job/19854637730

**Comment by pmalek** [comment]
Still occurring https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7444386286/job/20250735830

**Comment by czeslavo** [comment]
To fix this, let's move the flaky test to envtests that were scaffolded in https://github.com/Kong/kubernetes-ingress-controller/pull/5605. `TestAdmissionWebhook_KongVault` can be used as an example of the admission webhook test that deploys Kong in docker so it's possible to also test cases that require communication with DP.

**Comment by pmalek** [comment]
Fun fact: `TestAdmissionWebhook_KongVault` failed in https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8437912949/job/23108889362?pr=5751

```
      admission_webhook_envtest_test.go:52: 
          	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/admission_webhook_envtest_test.go:196
          	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/admission_webhook_envtest_test.go:52
          	Error:      	Received unexpected error:
          	            	Internal error occurred: failed calling webhook "kongvaults.validation.ingress-controller.konghq.com": failed to call webhook: an error on the server ("HTTP status 405 (message: \"Method not allowed\")") has prevented the request from succeeding
          	Test:       	TestAdmissionWebhook_KongVault
```

**Comment by czeslavo** [comment]
> Fun fact: `TestAdmissionWebhook_KongVault` failed in https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8437912949/job/23108889362?pr=5751
> 
> ```
>       admission_webhook_envtest_test.go:52: 
>           	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/admission_webhook_envtest_test.go:196
>           	            				/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/envtest/admission_webhook_envtest_test.go:52
>           	Error:      	Received unexpected error:
>           	            	Internal error occurred: failed calling webhook "kongvaults.validation.ingress-controller.konghq.com": failed to call webhook: an error on the server ("HTTP status 405 (message: \"Method not allowed\")") has prevented the request from succeeding
>           	Test:       	TestAdmissionWebhook_KongVault
> ```

@pmalek It could fail because we mistakenly updated the Kong version that's used in envtests (https://github.com/Kong/kubernetes-ingress-controller/pull/5608/files). We have to stay with 3.4.x until 3.7.x is released with a fix for https://konghq.atlassian.net/browse/KAG-3699. https://github.com/Kong/kubernetes-ingress-controller/pull/5756 should address that.

**Comment by programmer04** [comment]
😞 https://github.com/Kong/kubernetes-ingress-controller/commit/09f1e556e68442b87345879e18867e9b0226e3a7

**Comment by pmalek** [comment]
Still failing: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/8468297488/job/23201043133#step:7:4530

```
creating consumer background-noise-consumer-45
Warning: import/export of basic-authcredentials using decK doesn't work due to hashing of passwords in Kong.
creating basic-auth background-noise-consumer-31-credential-1 for consumer background-noise-consumer-31
creating basic-auth background-noise-consumer-32-credential-2 for consumer background-noise-consumer-32
creating basic-auth background-noise-consumer-31-credential-0 for consumer background-noise-consumer-31
creating basic-auth background-noise-consumer-32-credential-3 for consumer background-noise-consumer-32
creating basic-auth background-noise-consumer-31-credential-2 for consumer background-noise-consumer-31
creating basic-auth background-noise-consumer-31-credential-4 for consumer background-noise-consumer-31
creating basic-auth background-noise-consumer-33-credential-2 for consumer background-noise-consumer-33
creating basic-auth background-noise-consumer-33-credential-0 for consumer background-noise-consumer-33
creating basic-auth background-noise-consumer-32-credential-1 for consumer background-noise-consumer-32
creating basic-auth background-noise-consumer-31-credential-3 for consumer background-noise-consumer-31
creating basic-auth background-noise-consumer-33-credential-4 for consumer background-noise-consumer-33
creating basic-auth background-noise-consumer-33-credential-1 for consumer background-noise-consumer-33
creating basic-auth background-noise-consumer-32-credential-0 for consumer background-noise-consumer-32
creating basic-auth background-noise-consumer-33-credential-3 for consumer background-noise-consumer-33
creating basic-auth background-noise-consumer-32-credential-4 for consumer background-noise-consumer-32
    webhook_test.go:901: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/webhook_test.go:901
        	Error:      	An error is expected but got nil.
        	Test:       	TestValidationWebhook/should_fail_the_validation_if_the_secret_in_ConfigPatches_of_KongClusterPlugin_generates_invalid_configuration
Warning: import/export of basic-authcredentials using decK doesn't work due to hashing of passwords in Kong.
creating basic-auth background-noise-consumer-35-credential-3 for consumer background-noise-consumer-35
creating basic-auth background-noise-consumer-36-credential-1 for consumer background-noise-consumer-36
creating basic-auth background-noise-consumer-34-credential-3 for consumer background-noise-consumer-34
creating basic-auth background-noise-consumer-35-credential-1 for consumer background-noise-consumer-35
creating basic-auth background-noise-consumer-34-credential-0 for consumer background-noise-consumer-34
creating basic-auth background-noise-consumer-34-credential-1 for consumer background-noise-consumer-34
```

**Comment by pmalek** [comment]
Should be fixed by https://github.com/Kong/kubernetes-ingress-controller/pull/5797
