### ISSUE TITLE
kubernetes v1.15.8-gke.3 with 1.4.0

### ISSUE THREAD

**Issue by Emmanuelgelati** [Kong/kubernetes-ingress-controller#538]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. helm install --name kong --namespace ingress --set env.database=off --set ingressController.enabled=true stable/kong
2. kubectl logs -n ingress kong-kong-76756db57d-7jx65 -c ingress-controller

Log:

Kong Ingress controller
  Release:    0.7.0
  Build:      e4605db
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.13.1
-------------------------------------------------------------------------------

I0211 11:08:38.330443       1 main.go:407] Creating API client for https://10.24.0.1:443
I0211 11:08:38.341552       1 main.go:451] Running in Kubernetes Cluster version v1.15+ (v1.15.8-gke.3) - git (clean) commit 2ccf2c797713077f4a3d0f87c4b4bae725362326 - platform linux/amd64
I0211 11:08:38.367011       1 main.go:187] kong version: 1.4.0
I0211 11:08:38.367041       1 main.go:196] Kong datastore: off
I0211 11:08:38.500859       1 controller.go:224] starting Ingress controller
E0211 11:08:38.501587       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 158 [running]:

**Comment by hbagdi** [comment]
@Emmanuelgelati Please update to 0.7.1.
Also, please use Kong's chart repo instead of the default: https://charts.konghq.com/

**Comment by Emmanuelgelati** [comment]
@hbagdi same error using the konghq.com chart:

kubectl logs -n ingress kong-kong-5678848cc7-4q8b4 -c ingress-controller 
```
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.7.0
  Build:      e4605db
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.13.1
-------------------------------------------------------------------------------

I0211 18:03:39.025325       1 main.go:407] Creating API client for https://10.24.0.1:443
I0211 18:03:39.037353       1 main.go:451] Running in Kubernetes Cluster version v1.15+ (v1.15.9-gke.8) - git (clean) commit a9973cbb2722793e2ea08d20880633ca61d3e669 - platform linux/amd64
I0211 18:03:39.066880       1 main.go:187] kong version: 2.0.1
I0211 18:03:39.066916       1 main.go:196] Kong datastore: off
I0211 18:03:39.209372       1 controller.go:224] starting Ingress controller
E0211 18:03:39.210358       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 171 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x142a5c0, 0x2229630)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x82
```

**Comment by Emmanuelgelati** [comment]
@kidd thanks for hint, solved using the helm parameter ingressController.image.tag = 0.7.1
