### ISSUE TITLE
Starting in KIC 3.0.x, Same-named Entities in Multiple Workspaces Results in Collisions

### ISSUE THREAD

**Issue by msmost** [Kong/kubernetes-ingress-controller#5389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We leverage KIC to manage multiple workspaces (following the architecture described in this [Kong Nation article](https://discuss.konghq.com/t/multiple-workspace-in/7780)), within a single deployment of Kong. We deploy each of the components as separate pods:
* KIC Instance 1 (for managing workspace 1)
* KIC Instance 2 (for managing workspace 2)
* Kong Control Plane
* Kong Data Plane

When we upgraded from KIC 2.12.x to 3.0.x, we started seeing the following failure in the ingress controller logs:
`{
   error: performing update for https://<redacted> failed: 1 errors occurred:
	while processing event: {Create} consumer test failed: HTTP status 400 (message: "an existing 'plugins' entity references this 'consumers' entity")
   level: error
   logger: dataplane-synchronizer
   msg: Could not update kong admin
}`

A corresponding failure can be seen in the control plane logs for the admin API:

`Key (id, ws_id)=(<redacted>) is still referenced from table "plugins"., client: <redacted>, server: <redacted>, request: "PUT /workspace1/consumers/<redacted> HTTP/2.0", host: <redacted>`

`[notice] 2398#0: *306518 [lua] init.lua:309: upsert(): ERROR: update or delete on table "consumers" violates foreign key constraint "plugins_consumer_id_fkey" on table "plugins"`

This error seems to be related to the KIC instances for workspaces 1 and 2 trying to create/manage entities which have the same name.

### Expected Behavior

When provisioning entities with the same name into different workspaces, KIC should be able to create/manage those entities without error.

When we reverted back to v2.12.x, KIC started behaving as expected.

### Steps To Reproduce

```markdown
1. Provision KIC v2.12.x twice with the `kong_workspace` environment variable set with different values.
2. Observe that when the following configuration is applied, KIC is able to configure properly.
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: test-workspace1
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: kong-workspace1
username: test
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: test-workspace2
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: kong-workspace2
username: test

3. Upgrade to KIC v3.0.x and observe that only the consumer in kong-workspace1 will be created, and the one in kong-workspace2 will error.
```

### Kong Ingress Controller version

```shell
v3.0.1
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.1-eks-2f008fe", GitCommit:"abfec7d7e55d56346a5259c9379dea9f56ba2926", GitTreeState:"clean", BuildDate:"2023-04-14T20:43:13Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.8-eks-8cb36c9", GitCommit:"fca3a8722c88c4dba573a903712a6feaf3c40a51", GitTreeState:"clean", BuildDate:"2023-11-22T21:52:13Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by randmonkey** [comment]
@msmost Could you please provide version of Kong gateway before and after your upgrade? It would be better if you also provide the dumped configuration of each workspace of Kong before and after the upgrade.

**Comment by msmost** [comment]
@randmonkey - Before the upgrade, Kong gateway was at `v3.4.3.2`. After the upgrade Kong gateway was at `v3.5.0.2`. Instead of providing the before and after config here, I will open a case with Kong Support and reference this thread.

**Comment by mflendrich** [comment]
@msmost,

The root cause has been identified - it's the `FillIDs` feature (feature gate that was default-disabled in KIC <3.0 and is enabled by default in 3.0) creating resource IDs that conflict across the workspace boundary.

There is a workaround: when running KIC 3.0, set the `CONTROLLER_FEATURE_GATES` env variable to `FillIDs=false`.
Could you try this and report back?

**Comment by randmonkey** [comment]
Created https://github.com/Kong/go-kong/issues/393 because the `FillID` methods for each entity is in `go-kong`.

**Comment by msmost** [comment]
@mflendrich - Confirmed, with the `FillIDs` feature gate set to `false` the same-named entities in different workspaces are created as expected.

Thank you @mflendrich and @randmonkey for your quick response!
