### ISSUE TITLE
Test flake: TestHTTPRouteEssentials 

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#5424]
TestHTTPRouteEssentials randomly failed in a [PR workflow](https://github.com/Kong/kubernetes-ingress-controller/actions/runs/7479068018/job/20355503130).

```
    httproute_test.go:333: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/httproute_test.go:333
        	            				/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/asm_amd64.s:1650
        	Error:      	Received unexpected error:
        	            	resource name may not be empty
        	Test:       	TestHTTPRouteEssentials
    httproute_test.go:331: 
        	Error Trace:	/home/runner/work/kubernetes-ingress-controller/kubernetes-ingress-controller/test/integration/httproute_test.go:331
        	Error:      	Condition never satisfied
        	Test:       	TestHTTPRouteEssentials
```

**Comment by pmalek** [comment]
This does not show up anymore in BuildPulse: https://app.buildpulse.io/@Kong/kubernetes-ingress-controller?q=TestHTTPRouteEssentials&select%5B%5D=&show_type=default&sort=disruptiveness&daterange=December+2+-+December+16&starting_at=%222024-08-31T22%3A00%3A00.000Z%22&ending_at=%222024-12-31T22%3A59%3A59.999Z%22&user_time_zone=Europe%2FWarsaw

Closing.
