### ISSUE TITLE
Last valid config (KongRawStateToKongState) doesn't support Licenses and Vault fields

### ISSUE THREAD

**Issue by programmer04** [Kong/kubernetes-ingress-controller#5447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the discussion https://github.com/Kong/kubernetes-ingress-controller/pull/5438#issuecomment-1892327811 under the PR for the issue
- https://github.com/Kong/kubernetes-ingress-controller/issues/5377

a better way of testing was proposed by @czeslavo. Let's go ahead and implement it.

That new way of testing uncovers the lack of support for 
- `Vaults` (still in progress https://github.com/Kong/kubernetes-ingress-controller/issues/4559)
- `Plugins` (they are handled a little bit differently thus they probably should be omitted in tests)
- `Licenses` 

For `Licenses` it is a little bit more complicated. There are two ways of configuring licenses in Kong Gateway with KIC
- directly passed as env var to Kong Gateway (it's not a problem - it's transparent for KIC)
- retrieved from Konnect by KIC and fed with configuration to a Kong Gateway instance

In the second case setting up a license fetched from Konnect is done in https://github.com/Kong/kubernetes-ingress-controller/blob/af769ce3d4fbec65f6f58e518db809ca728542a3/internal/dataplane/translator/translator.go#L142-L230
that is not executed when fallback occurs 
https://github.com/Kong/kubernetes-ingress-controller/blob/af769ce3d4fbec65f6f58e518db809ca728542a3/internal/dataplane/kong_client.go#L424-L434
 

### Expected Behavior

The license in the config fallback is presented when KIC in Konnect is run.

### Kong Ingress Controller version

```shell
v3.0.2
```

### Kubernetes version

```shell
doesn't matter
```

### Acceptance Criteria

- [ ] KIC can send license from last known good configuration when integrated with Konnect or got from KongLicenses
- [ ] KIC can send vaults from last known configuration

### Anything else?

**Proposed solution**

https://github.com/Kong/kubernetes-ingress-controller/blob/0314607aa90983243b0d8972ad0dc9b9fb090a16/internal/dataplane/configfetcher/config_fetcher.go#L49

The above can be modified to use (and include) `LicenseGetter`, fetch it, and add it to the config.

Or maybe it should rely on the same flow as other fields of configuration and take it from Kong Gateway API.

**Comment by czeslavo** [comment]
> Plugins (they are handled a little bit differently thus they probably should be omitted in tests)

I think that we should ensure that Plugins' mapping is implemented as expected. I can see we only map ones that are attached to Routes and Services while we don't handle Consumer/ConsumerGroup and global ones.
