### ISSUE TITLE
Move CI to use Github actions

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#548]
Travis CI queue waits and issues are on the rise and is creating more problems now.
Other projects at Kong have successfully moved to Github Actions with positive results and so should this repository.

**Comment by Andersoncalde12** [comment]
All dret

**Comment by agustindaguerre** [comment]
@hbagdi is this still an issue? I would like to try addressing this if you can let me know where to start.

**Comment by hbagdi** [comment]
Yes, this is still an issue.
The way to go about this would be to study the small Makefile and `.travis.yml` files in the repository then try to write a workflow for Github Action.

**Comment by agustindaguerre** [comment]
ok, thanks. I'll start working on that.

**Comment by hbagdi** [comment]
If anyone wants to take this up, the basic steps are documented here: https://github.com/hbagdi/go-kong/blob/master/.github/workflows/test.yaml
