### ISSUE TITLE
TLS v1.1 not supported with kong-ingress + cert-manager

### ISSUE THREAD

**Issue by rparsonsbb** [Kong/kubernetes-ingress-controller#552]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

I **think** this is an issue with kong-ingress-controller because when I look at the config for kong-proxy containers it shows the `nginx_http_directives ssl_protocols` as `TLSv1.1 TLSv1.2 TLSv1.3`.

**Kong Ingress controller version**
0.6.0

**Kong or Kong Enterprise version**
1.3

### Kubernetes version

`Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`

### Environment

- **Cloud provider or hardware configuration**: AWS EKS
- **OS** (e.g. from /etc/os-release): amazon-linux2
- **Kernel** (e.g. `uname -a`):
- **Install tools**: eksctl for cluster, helm for kong ingress
- **Others**:

### What happened
[kong-ingress-controller paired with cert-manager](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/cert-manager.md) supports only TLS 1.2+ and not TLS 1.1, which is configured in kube-proxy

### Expected behavior
TLS 1.1 to be supported

### Steps To Reproduce

1. follow [kong + cert-manager guide](https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/cert-manager.md) and then use [ssllabs](https://www.ssllabs.com/ssltest/) to verify TLS versions accepted.

**Comment by hbagdi** [comment]
TLS 1.1 is enabled by default.
You should use this property instead: https://docs.konghq.com/2.0.x/configuration/#nginx_http_ssl_protocols

And specifying that environment variable, you need to use `KONG_` prefix.

**Comment by rparsonsbb** [comment]
Yes sorry, I did set the environment var in the helm chart (confusuing that the `KONG_` prefix isn't needed here until I dug in) but I'm still only getting 1.2 and 1.3 which can be verified by ssl labs. https://www.ssllabs.com/ssltest/analyze.html?d=webapi%2ddev.blackbookcloud.com&s=3.227.136.80&latest

Since `TLSv1.1 TLSv1.2 TLSv1.3` is default I added `TLSv1` also to confirm that the block was updated in the `.conf` - it was - but still only 1.2 and 1.3 are showing up in ssllabs, and a 1.1 call fails to the site.

The architecture is NLB (level 4) with two tcp listeners on 80 and 443 (no tls) into kong-ingress-controller which terminates tls on 443 to all http services/routes.

Not sure if you guys are dog-fooding with konghq.com, [but it also does not support 1.1](https://www.ssllabs.com/ssltest/analyze.html?d=konghq.com)

**Comment by rparsonsbb** [comment]
For further validation I created a blank EKS cluster.

* installed external-dns via helm
* installed kong-ingress using [this values.yaml](https://gist.github.com/rparsonsbb/1069dfe18b601b534003cb997f7b1de4)
* installed cert-manager and created a ClusterIssuer
* created the echo service mentioned in the cert-manager guide (`curl -sL bit.ly/echo-service | kubectl apply -f -`)
* created the ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echo-bbc-com
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: dns-letsencrypt-prod
spec:
  tls:
  - secretName: echo-bbc-com
    hosts:
    - echo.blackbookcloud.com
  rules:
  - host: echo.blackbookcloud.com
    http:
      paths:
      - path: /
        backend:
          serviceName: echo
          servicePort: 80
```

cannot use TLSv1 or TLSv1.1

### TLSv1
```
❯ curl -v -I --tlsv1.0 --tls-max 1.0 https://echo.blackbookcloud.com
* Rebuilt URL to: https://echo.blackbookcloud.com/
*   Trying 107.20.82.57...
* TCP_NODELAY set
* Connected to echo.blackbookcloud.com (107.20.82.57) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS handshake, Client hello (1):
* TLSv1.0 (IN), TLS alert, Server hello (2):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* stopped the pause stream!
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

### TLSv1.1
```
❯ curl -v -I --tlsv1.1 --tls-max 1.1 https://echo.blackbookcloud.com
* Rebuilt URL to: https://echo.blackbookcloud.com/
*   Trying 107.20.82.57...
* TCP_NODELAY set
* Connected to echo.blackbookcloud.com (107.20.82.57) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.1 (OUT), TLS handshake, Client hello (1):
* TLSv1.1 (IN), TLS alert, Server hello (2):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
* stopped the pause stream!
* Closing connection 0
curl: (35) error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

### TLSv1.2
```
❯ curl -v -I --tlsv1.1 --tls-max 1.2 https://echo.blackbookcloud.com
* Rebuilt URL to: https://echo.blackbookcloud.com/
*   Trying 34.198.44.220...
* TCP_NODELAY set
* Connected to echo.blackbookcloud.com (34.198.44.220) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=echo.blackbookcloud.com
*  start date: Feb 25 23:31:38 2020 GMT
*  expire date: May 25 23:31:38 2020 GMT
*  subjectAltName: host "echo.blackbookcloud.com" matched cert's "echo.blackbookcloud.com"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> HEAD / HTTP/1.1
> Host: echo.blackbookcloud.com
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Content-Type: text/plain; charset=UTF-8
Content-Type: text/plain; charset=UTF-8
< Connection: keep-alive
Connection: keep-alive
< Date: Wed, 26 Feb 2020 00:51:23 GMT
Date: Wed, 26 Feb 2020 00:51:23 GMT
< Server: echoserver
Server: echoserver
< X-Kong-Upstream-Latency: 2
X-Kong-Upstream-Latency: 2
< X-Kong-Proxy-Latency: 0
X-Kong-Proxy-Latency: 0
< Via: kong/1.4.3
Via: kong/1.4.3

<
* Connection #0 to host echo.blackbookcloud.com left intact
```

This test was using the default ingress (elastic/classic load balancer), I also destroyed the kong-ingress helm installation and recreated using an nlb with the same results.

**Comment by hbagdi** [comment]
Can you set the environment variable on proxy container:

```
KONG_NGINX_HTTP_SSL_PROTOCOLS="TLSv1.1 TLSv1.2 TLSv1.3"
```

What happens then?

**Comment by rparsonsbb** [comment]
Its already set from the helm chart 
```
<<K9s-Shell>> Pod: kong-ingress/kong-kong-64bbf6789f-88jtj | Container: proxy 
/ $ echo $KONG_NGINX_HTTP_SSL_PROTOCOLS
TLSv1 TLSv1.1 TLSv1.2 TLSv1.3
```

Konga connected via kube-proxy shows that this is being consumed correctly.
![image](https://user-images.githubusercontent.com/50666468/75373229-e85df880-5897-11ea-97ee-296db8f96412.png)

This is the cluster / ingress that's hosting the site that I provided ssl labs for previously [here].(https://www.ssllabs.com/ssltest/analyze.html?d=webapi%2ddev.blackbookcloud.com&latest)

**Comment by hbagdi** [comment]
@dndx @fffonion Any idea what is causing this problem?

**Comment by hbagdi** [comment]
Sorry, fat fingered and closed the issue.

**Comment by fffonion** [comment]
Could you share the kong error log when sending tls1.1 and tls1.0 requests?

**Comment by rparsonsbb** [comment]
sure, is `log_level` just set as an environment variable?

**Comment by rparsonsbb** [comment]
`2020/02/26 19:13:17 [info] 24#0: *31375 SSL_do_handshake() failed (SSL: error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher) while SSL handshaking, client: 4.30.234.146, server: 0.0.0.0:8443`

This is the only line that appears when curling.

**Comment by aaronhmiller** [comment]
Wondering if https://docs.konghq.com/2.0.x/configuration/#ssl_cipher_suite is the cause?
If TLS 1.1 is a requirement, the suite will need to be set to "old". The default of "modern" (Kong 1.3) or "intermediate" (Kong 2.0) will cause the observed behavior. https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by aaronhmiller** [comment]
@rparsonsbb please try setting `env.ssl_cipher_suite="old"` and let us know if this resolves it?

**Comment by rparsonsbb** [comment]
`env.ssl_cipher_suite="old"` has corrected the TLS issues, when configured now with _both_ `nginx_http_ssl_protocols="TLSv1 TLSv1.1 TLSv1.2 TLSv1.3"` **and** `ssl_cipher_suite="old"` kong-ingress will serve TLSv1 through TLSv1.3.

Thanks so much to all of you for your help, I'll write up a guide and submit a PR in case anyone else runs into this issue again.
