### ISSUE TITLE
No more ip addresses assigned to ingresses after connection refused from k8s api server

### ISSUE THREAD

**Issue by timducheyne** [Kong/kubernetes-ingress-controller#561]
### Summary
The ingress controller (control plane) stops working when the k8s api server is not available for a moment. It no longer assigns an ip address to new ingress resources
This situation does not resolve itself. A restart of the kong ingress controller is required to restore the functionality.
Note, as expected, during this time the proxy remains ok.

**Kong Ingress controller version**
kong-ingress-controller 0.7.0   
setup without db
deployed using helm chart 1.1.1

**Kong or Kong Enterprise version**
kong 1.5.0

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.22", GitCommit:"be6e649e67f82e64e43e32119b2b14250a7f9542", GitTreeState:"clean", BuildDate:"2020-01-30T19:02:16Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

### Environment
- **Cloud provider or hardware configuration**:
GKE
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
An update of the cluster made the k8s api server temporarily unavailable (this could happen also for other reasons eg an upgrade or a crash). From then on, new ingress resources (kubectl get ingress) stopped getting ip addresses
The pods and services are running and accessible, but ingress is not.

### Expected behavior
The ingress is available

### Steps To Reproduce
on a GKE cluster
edit a property of the cluster using the GCE console   (eg  enable autoscaling or enable the kubernetes dashboard)
while the update is going on, the k8s api server is not available
following types of error appear in the ingress controller logs
```
I0306 14:34:07.779492       1 kong.go:66] successfully synced configuration to Kong
I0306 14:42:59.696356       1 kong.go:66] successfully synced configuration to Kong
E0306 14:42:59.753710       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongPlugin: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongplugins?resourceVersion=153469748&timeout=7m49s&timeoutSeconds=469&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753764       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.Secret: Get https://10.18.0.1:443/api/v1/secrets?resourceVersion=153470335&timeout=5m47s&timeoutSeconds=347&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753785       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.Endpoints: Get https://10.18.0.1:443/api/v1/endpoints?resourceVersion=153473503&timeout=5m6s&timeoutSeconds=306&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753823       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongIngress: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongingresses?resourceVersion=153469744&timeout=6m19s&timeoutSeconds=379&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753839       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongCredential: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongcredentials?resourceVersion=153399704&timeout=5m11s&timeoutSeconds=311&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753868       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1beta1.Ingress: Get https://10.18.0.1:443/apis/networking.k8s.io/v1beta1/ingresses?resourceVersion=153470123&timeout=7m13s&timeoutSeconds=433&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753873       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.KongConsumer: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongconsumers?resourceVersion=153399704&timeout=8m28s&timeoutSeconds=508&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:42:59.753969       1 reflector.go:283] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to watch *v1.Service: Get https://10.18.0.1:443/api/v1/services?resourceVersion=153469736&timeout=6m9s&timeoutSeconds=369&watch=true: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.755496       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongPlugin: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongplugins?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.756720       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Get https://10.18.0.1:443/api/v1/secrets?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.757591       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Endpoints: Get https://10.18.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.758488       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongIngress: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongingresses?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.759657       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongCredential: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongcredentials?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.760559       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1beta1.Ingress: Get https://10.18.0.1:443/apis/networking.k8s.io/v1beta1/ingresses?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.761854       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongConsumer: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongconsumers?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:00.762785       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Service: Get https://10.18.0.1:443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:01.756638       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.KongPlugin: Get https://10.18.0.1:443/apis/configuration.konghq.com/v1/kongplugins?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
E0306 14:43:01.757696       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190819141724-e14f31a72a77/tools/cache/reflector.go:98: Failed to list *v1.Secret: Get https://10.18.0.1:443/api/v1/secrets?limit=500&resourceVersion=0: dial tcp 10.18.0.1:443: connect: connection refused
```
when the update finishes, the errors stop and the ingress controller appears to be ok
```
I0306 14:46:52.074934       1 kong.go:66] successfully synced configuration to Kong
I0306 14:46:55.400113       1 kong.go:66] successfully synced configuration to Kong
I0306 14:46:58.669002       1 kong.go:66] successfully synced configuration to Kong
I0306 14:47:54.409095       1 kong.go:66] successfully synced configuration to Kong
```
but this is not the case
when you deploy a new application, the services and routes are correctly registered in kong
but the ingress itself is never assigned an ip address
ie.  normally following should be visible in the ingress controller logs
```
I0306 14:11:44.021102       1 status.go:342] updating Ingress xxx status to [{11.111.111.111 }]
```
but this never appears

when you do kubectl get ingress
you can see that no address was assigned for the new ingress resource
the ingress resources that were already present are ok. They still have an address pointing to kong 

just restarting the kong pod resolves the issue
all ingresses now have the ip address of kong
Note that this does not happen immediately: after restart it takes almost 2 minutes for the update to be performed. Following shows the logs after restart. This was only a restart, nothing new was deployed.
```
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.7.0
  Build:      e4605db
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.13.1
-------------------------------------------------------------------------------

I0306 17:32:35.995117       1 main.go:407] Creating API client for https://10.18.0.1:443
I0306 17:32:36.007248       1 main.go:451] Running in Kubernetes Cluster version v1.14+ (v1.14.10-gke.22) - git (clean) commit be6e649e67f82e64e43e32119b2b14250a7f9542 - platform linux/amd64
I0306 17:32:36.594323       1 main.go:187] kong version: 1.5.0
I0306 17:32:36.594457       1 main.go:196] Kong datastore: off
I0306 17:32:36.828148       1 controller.go:224] starting Ingress controller
I0306 17:32:36.832248       1 status.go:201] new leader elected: kong-ingress-controller-kong-84cbb69b67-6rw6b
I0306 17:32:37.135013       1 kong.go:66] successfully synced configuration to Kong
I0306 17:32:40.355227       1 kong.go:66] successfully synced configuration to Kong
I0306 17:32:43.628054       1 kong.go:66] successfully synced configuration to Kong
I0306 17:32:46.919831       1 kong.go:66] successfully synced configuration to Kong
I0306 17:33:17.063874       1 status.go:201] new leader elected: kong-ingress-controller-kong-84cbb69b67-tmrkp
I0306 17:33:17.162826       1 kong.go:66] successfully synced configuration to Kong
I0306 17:34:17.074996       1 status.go:342] updating Ingress xxx/xxxx status to [{11.111.111.111 }]
I0306 17:34:17.318395       1 kong.go:66] successfully synced configuration to Kong
```

**Comment by hbagdi** [comment]
Interesting. Since the configuration sync loop works, it seems the client used for updating the status of the Ingress resource can't recover once the connectivity has been dropped.

Since you are using the DB-less mode, this also indicates that it could be a problem with leader-election between two controllers that can't recover once the connectivity with API-server is lost.

**Comment by timducheyne** [comment]
Hi Harry, 

any news on the issue? Were you able to reproduce it?  
would running it in DB mode solve the issue or are there any recommendations to mitigate the risk of encountering this in a prod env?

brgds,
Tim

**Comment by seh** [comment]
I confirmed that with Kong version 0.7.0, after about four minutes of failed connectivity to the Kubernetes API server, Kong stops vying for leader election and stops watching the _ConfigMap_ that mediates those elections.

With only a single Kong instance running, Kong never tries to become the leader again, and no longer updates _Ingress_ objects' "status" subresources.

**Comment by seh** [comment]
Note that Kong starts running the leader elector [here](https://sourcegraph.com/github.com/Kong/kubernetes-ingress-controller/-/blob/internal/ingress/controller/controller.go#L226), but doesn't pay any attention to whether it ever stops running. [`internal/ingress/election.elector.Run`](https://sourcegraph.com/github.com/Kong/kubernetes-ingress-controller/-/blob/internal/ingress/election/election.go#L40) forwards on unconditionally to [`(*tools/leaderelection.LeaderElector).Run`](https://sourcegraph.com/github.com/kubernetes/client-go@365234d2fcf08d0071f6bf50284e7480a74c5736/-/blob/tools/leaderelection/leaderelection.go#L208), which blocks on [its `renew` function](https://sourcegraph.com/github.com/kubernetes/client-go@365234d2fcf08d0071f6bf50284e7480a74c5736/-/blob/tools/leaderelection/leaderelection.go#L258-L285).

Note that `renew` exits if part of it fails. In particular, when `(*LeaderElector).tryAcquireOrRenew` fails—as [it does when it can't fetch the _ConfigMap_](https://sourcegraph.com/github.com/kubernetes/client-go@365234d2fcf08d0071f6bf50284e7480a74c5736/-/blob/tools/leaderelection/leaderelection.go#L318-L321)—then [the call to `wait.Until`](https://sourcegraph.com/github.com/kubernetes/client-go@365234d2fcf08d0071f6bf50284e7480a74c5736/-/blob/tools/leaderelection/leaderelection.go#L262-L279) returns, because failure triggers [calling on the `Context`'s associated `cancel` function](https://sourcegraph.com/github.com/kubernetes/client-go@365234d2fcf08d0071f6bf50284e7480a74c5736/-/blob/tools/leaderelection/leaderelection.go#L278), which satisfies the `Context` completion condition for [exiting from `wait.Until`](https://sourcegraph.com/github.com/kubernetes/apimachinery/-/blob/pkg/util/wait/wait.go#L84-L91).

Rather than starting the leader election process as a fire-and-forget blocking call in a goroutine, I think we need to loop and call on it again—perhaps with some backoff—when it returns. There is the configurable ["RetryPeriod" parameter](https://sourcegraph.com/github.com/kubernetes/client-go@365234d2fcf08d0071f6bf50284e7480a74c5736/-/blob/tools/leaderelection/leaderelection.go#L134-L138), but note that only helps [until the "RenewDeadline" expires](https://sourcegraph.com/github.com/kubernetes/client-go@365234d2fcf08d0071f6bf50284e7480a74c5736/-/blob/tools/leaderelection/leaderelection.go#L263-L267). At that point, the "timeoutCtx" `Context` is done, the `err` value is non-nil, and we cancel the `Context` governing the `wait.Until` call.

**Comment by seh** [comment]
I'll work on a patch for this now. We may be able to use a _NetworkPolicy_ object to temporarily choke the ingress controller off from talking to the Kubernetes API server to compare the released and patched behavior.

**Comment by seh** [comment]
I'm testing my patch for this now, and will post it for review once I can prove that it resolves this problem.
