### ISSUE TITLE
Installation using minikube with helm doesn't work

### ISSUE THREAD

**Issue by solid-studio** [Kong/kubernetes-ingress-controller#565]
# Summary

Hello,  I'm trying to install kong with helm as instructions say:

$ helm repo add kong https://charts.konghq.com
$ helm repo update
$ helm install kong/kong

But it is not working as expected.

Firstly, the command helm install kong/kong won't work for helm 3. Then, we need to use:

$ helm install kong/kong --set ingressController.installCRDs=false --generate-name

I manage to install it like this, however, the external IP never gets assigned and I cannot set the PROXY_IP variable that most of the guides mention.

<img width="1098" alt="Screenshot 2020-03-16 at 19 39 35" src="https://user-images.githubusercontent.com/56453782/76793983-08f5e000-67be-11ea-875a-467f9f725b9f.png">

One thing to notice is that when I try to install using YAMLs. Every works as expected and even the External IP gets assigned. Do you have any idea of why?

Thanks a lot

**Comment by hbagdi** [comment]
Minikube doesn't support LoadBalancers since it is a local dev cluster solution.

Please follow the Minikube installation guide for how to get the PROXY_IP for the `kong-proxy` service:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/minikube.md#setup-environment-variables


For Helm 2 vs Helm 3, please read this section in our docs:
https://github.com/Kong/charts/tree/master/charts/kong#important-helm-2-vs-helm-3

**Comment by solid-studio** [comment]
hello @hbagdi , thanks for replying. 

I followed the Minikube installation guide and the PROXY_IP worked when I installed from yaml files but not when I use helm. Not sure what is the difference. 

I actually notice that for helm the instructions says to run Tiller. Can you explain why is necessary? 

And I manage to make it work by using minikube tunnel. I still don't get why with yaml files work, even if LoadBalancers are not supported.

Thanks !

**Comment by hbagdi** [comment]
> I followed the Minikube installation guide and the PROXY_IP worked when I installed from yaml files but not when I use helm. Not sure what is the difference.

Please make sure you change the service name and the namespace according to how you install Helm. It will work  no matter it is Helm or YAML but it won't work verbatim.

> I actually notice that for helm the instructions says to run Tiller. Can you explain why is necessary?

For Helm 2, you need Tiller. If you are using Helm 3, then you can ignore that. The doc was written before Helm 3 came out and needs to be updated.
