### ISSUE TITLE
feature: auto acl based on namespaces

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#573]
### Overview
A Consumer in Kong, should be able to access the Kubernetes services that exist in the same namespace as the KongConsumer resource.

###   Implementation
For each service, an ACL plugin is applied on it with a whitelist group of the namespace in which the service belongs.
For each consumer, add it to an ACL group with the name of the namespace it belongs to.

Now, Kong will only allow traffic if the credential is associated with the a consumer that exists in the same namespace as that of the service to which the traffic is destined.

This has to be feature gated and should be enabled on a need-by-need basis only.

### Background 
Users have long-time asked for this feature in multiple channels.
The most recent one being #570.
The user expectation here is very natural since KongConsumer resource is a namespaced resource instead of a cluster-level resource. It might make sense to rethink the decision to make it a namespaced resource.

**Comment by mflendrich** [comment]
> This has to be feature gated

My recommendation is to put the feature toggle in the `IngressClass` resource (or `GatewayClass` for service-apis)

**Comment by RobSerafini** [comment]
Stale. Update if you have continued interest in this feature.
