### ISSUE TITLE
`jwt` credentials `Secret` with `konghq.com/credential` label require `rsa_public_key` field even when configured with HMAC algos

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#5736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using `Secret` credentials with `konghq.com/credential` set to `jwt` and `algorithm` field set to `HS512` yields that a `rsa_public_key` field is required

```
consumer credential failed validation: missing required field(s): rsa_public_key
```

### Expected Behavior

`jwt` credentials with HMAC algorithms: `HS256`, `HS384`, `HS512`;  are properly validated and do not require `rsa_public_key` field in secret.

**Comment by programmer04** [comment]
Check this out https://github.com/Kong/kubernetes-ingress-controller/issues/5159 @pmalek
