### ISSUE TITLE
Check duplicate plugins in webhooks

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#5749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem Statement

Came from FTI-4640.
When multiple plugins with the same type attached to the same Kong entity(service/route/consumer...), we should reject them in admission webhooks.

### Proposed Solution

- Add checks in admission webhooks for resources that can have plugins attached (includeing `Ingress`,`Service`,`KongConsumer`,`HTTPRoute` and others)
- Generate translation errors and reject them when duplicate plugins attached to the same entity

### Acceptance Criteria

- [ ] Resources with multiple plugins of the same type are rejected on webhook
- [ ] Translation error event is attached when the resource is translated to a Kong entity attached to duplicated plugins

**Comment by programmer04** [comment]
It overlaps with
- https://github.com/Kong/kubernetes-ingress-controller/issues/5602

Logs & events are generated as expected see https://github.com/Kong/kubernetes-ingress-controller/issues/5602#issuecomment-2095448875

PR https://github.com/Kong/kubernetes-ingress-controller/pull/5972 introduced validation for
- `KongConsumer`
- `Ingress`
- `Service`

validation is not yet implemented for 

- `HttpRoute`
- `ConsumerGroup`
