### ISSUE TITLE
Deleting the kong CRDs (KongConsumer, KongCredentials) does not update the kong proxy

### ISSUE THREAD

**Issue by devdavidkarlsson** [Kong/kubernetes-ingress-controller#58]
**BUG REPORT**

**Kong Ingress controller version**:
0.0.4

**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-16T03:15:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

- **Cloud provider or hardware configuration**: minikube version: v0.26.1
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`): OSX 10.12.6
- **Install tools**: helm

**What happened**:

Deleting the kong CRDs (KongConsumer, KongCredentials) does not update the kong proxy. 

After deleting the ingress resources: the routes and services disappear as expected.
Moving on to delete the CRDs but the consumer and consumer/x/jwt still reports the old data.

```
	## Consumers:
	curl ${KONG_ADMIN_IP}:${KONG_ADMIN_PORT}/consumers/ |jq .
	## Consumer anonymous jwt:
	curl ${KONG_ADMIN_IP}:${KONG_ADMIN_PORT}/consumers/anonymous/jwt |jq .
```

*RESULTS:*

```
## Consumers:
{
  "total": 1,
  "data": [
    {
      "created_at": 1527503976000,
      "username": "anonymous",
      "id": "6a24ed65-6263-11e8-8eb0-0800274b9d73"
    }
  ]
}
## Consumer anonymous jwt:
{
  "total": 1,
  "data": [
    {
      "rsa_public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnfktZb7T7zeOTeC482AMkBpqAhusGA18xQtWZ2FuWJaHVpHbRi+NklmUgMR5pblCunNFN3h3ZWOrXSO/onI2N+Dkq+ztB+HB4T9IdxF8SWIpqP9IuapvwPGW+w/xJ+SECRETSTUFFmVXZ+7PQnOi9x0Fd4Qjw83CMPMMTWgoVhOpouCUg8rfX5Wrxni/89xvILDA1LMoolab3wjofo7OMGzlkpAfTSFSZqu4vjizgahbtBcKxNr/2NuIMu6NLKetxEjpmWo5JaT0xEVwBMM9EyaPYgXeWMUUOwjDyzwVKTGO8eGwGgf1Sb06tr9osR4oLnln3wRJAGClSokfMwIDAQAB\n-----END PUBLIC KEY-----",
      "created_at": 1527503976000,
      "id": "6a29d318-6263-11e8-8eb0-0800274b9d73",
      "algorithm": "RS256",
      "key": "https://api.mything.com/auth/realms/olt",
      "secret": "L9KS3sinRGLBjQ4Qp9xZ88m6FQYy4KqU",
      "consumer_id": "6a24ed65-6263-11e8-8eb0-0800274b9d73"
    }
  ]
}


```

**What you expected to happen**:
Deleting ingress resources should update the kong config, for CRDs as well.

**Comment by hbagdi** [comment]
This is currently an expected behavior.

Currently, the Ingress Controller creates and updates the consumers and credentials but doesn't delete them. The though behind this is avoid deleting resources not created by the Ingress Controller as there can be other ways Consumers are being added to Kong's database.

This not the ideal behavior, but we expect to solve this problem in future.
