### ISSUE TITLE
Support for GW API `URLRewrite` filter in HTTPRoute

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#5853]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

As there's demand for RewriteURI feature on HTTPRoute (we've got a community [pull request](https://github.com/Kong/kubernetes-ingress-controller/pull/5578) that implements that using an annotation as Ingress does), we should consider implementing the Gateway API's `HTTPURLRewriteFilter` to satisfy it.

### Proposed Solution

Implement support for `HTTPURLRewriteFilter` using `request-transformer` `KongPlugin` attached to a route (similarly to the Ingress `konghq.com/rewrite` annotation implementation).

### Acceptance Criteria

- [x] `HTTPURLRewriteFilter` for `HTTPRoute` is implemented according to the [Gateway API spec](https://github.com/kubernetes-sigs/gateway-api/blob/c57c131b49f8aec9eb7033f05c48654c57c9cc99/apis/v1/httproute_types.go#L1078) 
- [x] [`HTTPRouteRewriteHost`](https://github.com/Kong/kubernetes-ingress-controller/blob/8dd73bd0c7754e198d19f45708fb69738c5d8a4d/test/conformance/gateway_conformance_test.go#L42) and [`HTTPRouteRewritePath`](https://github.com/Kong/kubernetes-ingress-controller/blob/8dd73bd0c7754e198d19f45708fb69738c5d8a4d/test/conformance/gateway_conformance_test.go#L44) Gateway API conformance tests pass
  - [x] https://github.com/Kong/kubernetes-ingress-controller/issues/3685
  - [x] https://github.com/Kong/kubernetes-ingress-controller/issues/3686 
- [ ] docs.konghq.com docs are updated to reflect the fact that the rewriting URL feature for HTTPRoute is implemented in other way than for Ingress (a filter vs. an annotation)
  - [ ] https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/requests/rewrite-host/#rewrite-using-regular-expressions guide is updated
  - [ ] https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/requests/rewrite-annotation/ guide is updated

**Comment by pmalek** [comment]
`ReplaceFullPath` for `URLRewrite` has been implemented in #5855.
