### ISSUE TITLE
Location header contains container port for HTTP  303 responses.

### ISSUE THREAD

**Issue by tpokki** [Kong/kubernetes-ingress-controller#593]
### Summary

Kong adds container port to HTTP 303 responses, making the redirect fail.

**Kong Helm chart version**
```
1.4.1
```

**Kong Ingress controller version**
```
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.8.0
```

**Kong or Kong Enterprise version**
```
kong:2.0  (2.0.1?)
```
### Kubernetes version

**paste `kubectl version` output**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.26", GitCommit:"525ce678faa2b28483fa9569757a61f92b7b0988", GitTreeState:"clean", BuildDate:"2020-03-06T18:47:39Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: GCP
- **Install tools**: helm v3

### What happened

The 303 responses have container port in the `Location` header. This happens on both http and https responses:

```
$ curl -D - -k http://jenkins.example.com/loginEntry
HTTP/1.1 303 See Other
Content-Length: 0
Connection: keep-alive
Date: Thu, 02 Apr 2020 06:57:29 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Location: http://jenkins.example.com:8000/login
Server: Jetty(9.4.27.v20200227)
X-Kong-Upstream-Latency: 1
X-Kong-Proxy-Latency: 0
Via: kong/2.0.2
```

```
$ curl -D - -k https://jenkins.example.com/loginEntry
HTTP/2 303 
content-length: 0
location: https://jenkins.example.com:8443/login
date: Thu, 02 Apr 2020 07:25:36 GMT
expires: Thu, 01 Jan 1970 00:00:00 GMT
server: Jetty(9.4.27.v20200227)
x-kong-upstream-latency: 1
x-kong-proxy-latency: 0
via: kong/2.0.2
```

### Expected behavior

The `Location` header value should not have the container port (8000 / 8443)

### Steps To Reproduce

1. `helm install kong/kong --generate-name --set ingressController.installCRDs=false`
2. `helm install stable/jenkins --generate-name --set master.ingress.enabled=true --set master.ingress.hostName=jenkins.example.com`
3. `curl -D -  http://<lbip>/loginEntry -H 'Host: jenkins.example.com'`

**Comment by hbagdi** [comment]
Base on the HTTP response, it seems that the upstream, jenkins in this case is returning 303 with the `Location` header. Kong is not injecting or mangling with `Location` header.

**Comment by tpokki** [comment]
Yes, jenkins does return 303, but not with the port number. Or at least if I by-pass the Kong, I get following response: 
```
$ kubectl -n cd exec -ti jenkins-1585751748-6865d54478-qm7gj -- curl -D - localhost:8080/loginEntry -H 'Host: jenkins.example.com'
HTTP/1.1 303 See Other
Date: Fri, 03 Apr 2020 04:50:35 GMT
Set-Cookie: JSESSIONID.b1985a86=node09gan1dnh252zq0ocykvtxz8u11522.node0; Path=/; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Location: http://jenkins.example.com/login
Content-Length: 0
Server: Jetty(9.4.27.v20200227)
```

Which shows the `Location` header without the port. Also, the ports 8000 and 8443 that are seen in the Location header, map to the ports used by `proxy` container by kong deployment:
```
$ kubectl get deployments kong-1585745525-kong -o json|jq '.spec.template.spec.containers[1]|{name: .name, ports: .ports}'
{
  "name": "proxy",
  "ports": [
    {
      "containerPort": 8444,
      "name": "admin-tls",
      "protocol": "TCP"
    },
    {
      "containerPort": 8000,
      "name": "proxy",
      "protocol": "TCP"
    },
    {
      "containerPort": 8443,
      "name": "proxy-tls",
      "protocol": "TCP"
    },
    {
      "containerPort": 9542,
      "name": "metrics",
      "protocol": "TCP"
    }
  ]
}
```
... so I suspect that somehow the Kong is in play here. Note that the port number in `Location` is different if I use http:// or https://.

**Comment by hbagdi** [comment]
Kong is doing the right thing here of injecting `x-fowarded-port` into the request as it proxies the request from port 80. This header is being read by Jenkins and it is constructing the `Location` header appropriately.

In your Jenkins configuration, you should have a configuration for overriding the value of `Location` header. The other way to solve this would be to configure Kong to listen on port 80 and 443, which will require higher privileges for the Kong process.

**Comment by hbagdi** [comment]
I totally understand the expectation here but the challenge is a technical implementation one:

If you have a L4 Load Balancer in front of Kong, it won't inject an headers. It will listen on port 80 and forward traffic to port 8000 in Kong. Kong has no knowledge of the Load Balancer in-front of it and as far as it is concerned, the user is sending request to port 8000.

If L7 Load Balancer is used, then that LB will inject the `x-forwarded-port` header as `80` (or 443) and Kong will respect that and you won't have a problem.

There are two alternatives:
- Configure Kong to listen on port 80 and 443. 
- Use L7 LB which injects the above header in question.


On the Kong side, we will add a feature to override these settings via a configuration value. I've taken a note of this internally.

**Comment by wombat** [comment]
@hbagdi Are there any news about this feature request?

**Comment by dilaratasyaran** [comment]
> * to

Hi,

I am trying to configure Kong to listen on port 80 and 443 using option proxy_listen: 0.0.0.0:80, 0.0.0.0:443 ssl

but it fails when db enabled. I am getting the nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied) error from the wait-for-db container.

I tried to setcap CAP_NET_BIND_SERVICE option by referencing [the commit](https://github.com/Kong/docker-kong/commit/a9d6c19ef5d91d6378b6aa6490d480096421db0b) which did not helped.

Could you have any idea how to deal with it when db enabled?

**Comment by dilaratasyaran** [comment]
> @hbagdi

Hi,

I am trying to configure Kong to listen on port 80 and 443 using option proxy_listen: 0.0.0.0:80, 0.0.0.0:443 ssl

but it fails when db enabled. I am getting the nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied) error from the wait-for-db container.

I tried to setcap CAP_NET_BIND_SERVICE option by referencing [the commit](https://github.com/Kong/docker-kong/commit/a9d6c19ef5d91d6378b6aa6490d480096421db0b) which did not helped.

Could you have any idea how to deal with it when db enabled?

**Comment by shaneutt** [comment]
Hi @Minitour, given that this appears to be most relevant to the Gateway (and that the ingress controller seems mostly circumstantial) I would recommend bringing this up as a discussion in the Kong Gateway repository: https://github.com/Kong/kong/discussions/new as the engineers working on that project often have more insights for gateway specific behaviors and also when using another proxy in front of it.

**Comment by Minitour** [comment]
Hi @shaneutt, thanks for the comment.

I ended up solving the issue by simply not "trusting" the headers being injected by the ingress.

For instance the header "X-Forwarded-Port" would have a value of 8443 when it reaches my backend, so in order to solve it, I configured a proxy (in my case it was a Flask app) and intercepted the requests and simply overrode the value of 8443 and set it to 443.

**Comment by shaneutt** [comment]
Understood, glad you have something to work with for now. I still think putting in a discussion might bear some fruit: you can phrase it as a "here's the problem, here's how I worked around the problem, does anyone have another solution?" because who knows if there's nothing native to Kong to deal with such a situation it might be a neat thing to add an option for in a patch.

**Comment by Minitour** [comment]
Will do so, thanks for the suggestion.
