### ISSUE TITLE
Kong to manage api's in microservices.

### ISSUE THREAD

**Issue by devopskaran** [Kong/kubernetes-ingress-controller#595]
---
We are setting up kong as an ingress controller. We have multiple microservices and further those microservices have multiple API(curd operations). Now suppose i have an microservice for users, It have multiple api's for curd operation like user/add, user/delete. Now I want to add JWT plugin and consumer-1 for user/delete api, custom plugin and consumer-2 for user/add. 

If i create an ingress rule with route /add . It wouldn't send this as and payload. It will hit the base url of microservice. 
So we are unbale to manage multiple api's in one microservice. Is there anything I am missing here or kong ingress controller do not support it.

-->

### Summary

Kong Ingress controller version is 2.0

### Kubernetes version

Kubernetes version is v1.13.11  

### Environment
We are using AKS cluster.

### Expected behavior
It should manage api's also. As we can do in kong as API Gateway. We can create multiple services then further we can have multiple routes for this.

**Comment by hbagdi** [comment]
> If i create an ingress rule with route /add . It wouldn't send this as and payload. It will hit the base url of microservice.
So we are unbale to manage multiple api's in one microservice. Is there anything I am missing here or kong ingress controller do not support it.

Can you share the Ingress resource that you have created?
Also, can you share the version of the controller? 2.0 is the version of Kong.

**Comment by devopskaran** [comment]
Ingress controller version is kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.7.1

**Ingress resource:-**

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user-ingress
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /add
        backend:
          serviceName: user-dev
          servicePort: 80

**Comment by hbagdi** [comment]
I think what you want is `/add` to not be remove from the request when the request is sent to your microservice. For that, please upgrade to 0.8.0 and your problem should be solved.

It contains a breaking change where `strip_path` property is set to `false`, which should solve this problem.

**Comment by hbagdi** [comment]
Closing this issue since the original question was answered. Please re-open if needed.
