### ISSUE TITLE
Bump Gateway API to v1.1

### ISSUE THREAD

**Issue by mlavacca** [Kong/kubernetes-ingress-controller#5960]
## Problem Statement

Once Gateway API v1.1 is released, we need to manually bump it and ensure all the CI jobs successfully run.

## Acceptance Criteria

- [ ] Gateway API is bumped to v1.1

This is currently blocked as Gateway API is not released yet.

**Comment by tao12345666333** [comment]
v1.1 has been released, let me handle it.
