### ISSUE TITLE
<Feature Request> KongPlugin CRDs should be reusable

### ISSUE THREAD

**Issue by PepperTeasdale** [Kong/kubernetes-ingress-controller#6]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Kong Ingress controller version**:
0.0.1

**Kubernetes version** (use `kubectl version`):
1.9.6

**Environment**:
GKE

**What happened**:
We created `KongPlugin` manifests for the plugins that we are using for multiple routes and annotated those ingresses to use the plugins per the documentation. However, only one on the routes got the plugin via kong API. We were able to work around this by creating one unique CRD per ingress, referencing the same kong plugin in the annotation prefix, as specified in #4 .

**What you expected to happen**:
Ideally we could define the plugin once and reuse it in many routes/ services.

**Comment by hbagdi** [comment]
#121 was merged to master. This will be available in the next release of Kong Ingress Controller.

Thank you for opening this issue!
