### ISSUE TITLE
kong open telemetry plugin header_type datadog not valid option and rejected by admission webhook

### ISSUE THREAD

**Issue by zackery-parkhurst** [Kong/kubernetes-ingress-controller#6015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I set `config.header_type: datadog` In the opentelemetry plugin config the request is rejected and I cannot set the setting.
<img width="1010" alt="image" src="https://github.com/Kong/kubernetes-ingress-controller/assets/97055114/eb1d5125-9799-4070-892a-4e964bb3052c">

### Expected Behavior

When I set `config.header_type: datadog` In the opentelemetry plugin config kong should allow me to create the plugin, As datadog is supposed to be a valid option according to the [kong plugin documentation ](https://docs.konghq.com/hub/kong-inc/opentelemetry/3.5.x/configuration/)
<img width="1181" alt="image" src="https://github.com/Kong/kubernetes-ingress-controller/assets/97055114/d3d319bf-a63f-4af9-9eb8-f3734f44236c">

### Steps To Reproduce

```markdown
1. Install KIC version via helm. Chart Version: 2.36.0
2. Try to install the open telemetry plugin with config.header_type: datadog

apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
 name: <global-opentelemetry>
 annotations:
   kubernetes.io/ingress.class: kong
 labels:
   global: "true"
config:
 endpoint: http://opentelemetry.collector:4318/v1/traces
 header_type: datadog
plugin: opentelemetry

```
3. Observe failure
```


### Kong Ingress Controller version

```shell
Chart Version: 2.36.0
App Version: 3.5
```

### Kubernetes version

```shell
1.27
```

**Comment by randmonkey** [comment]
@zackery-parkhurst Looks like you are using version 3.5 of your gateway, and the `opentelemetry` plugin in Kong 3.5 does not support `datadog` in `config.header_type`:
```
{
  "default": "preserve",
  "one_of": [
    "preserve",
    "ignore",
    "b3",
    "b3-single",
    "w3c",
    "jaeger",
    "ot",
    "aws",
    "gcp"
  ],
  "required": false,
  "type": "string"
}

```

You can run `kong:3.5` in docker with this command 
```
docker run -e"KONG_DATABASE=off" -e"KONG_ADMIN_LISTEN=0.0.0.0:8001"  -p"8001:8001" kong:3.5
```
Then you fetch the `header_type` of config by:
```
curl 127.1:8001/schemas/plugins/opentelemetry | jq .fields[1].config.fields[10].header_type
```
You can see the result above. This does not include `datadog`.

Can you try to paste your helm command to install KIC? I can help you to replace the Kong gateway version to 3.6.

**Comment by randmonkey** [comment]
You can also change the values in your file referred in your `values` section if you have one, or add a `set` section like this
```
esource "helm_release" "kong" {
  name       = var.kong_gateway_name
  repository = "https://charts.konghq.com"
  chart      = "kong"
  namespace  = var.kong_gateway_namespace
  version    = "2.36.0" 
  values = [
      <<EOF
      ....... ]
set {
  name = image.tag
  value = 3.6
}
```

As I checked with the gateway team, the `datadog` in `config.header_type` is only available with Kong enterprise edition. Please create an issue in the [kong](https://github.com/Kong/kong) or [docs](https://github.com/Kong/docs.konghq.com) to tell the mistake in the docs.

**Comment by zackery-parkhurst** [comment]
@randmonkey 
> As I checked with the gateway team, the datadog in config.header_type is only available with Kong enterprise edition.
Oh, this is new information. So your saying if I am using OSS I can't use the datadog in config.header_type regardless of what version of kong gateway I am on?

**Comment by randmonkey** [comment]
> @randmonkey
> 
> > As I checked with the gateway team, the datadog in config.header_type is only available with Kong enterprise edition.
> 
> Oh, this is new information. So your saying if I am using OSS I can't use the datadog in config.header_type regardless of what version of kong gateway I am on?

In Kong OSS 3.7 (will soon be released), we can use `datadog` in `config.header_type`. For Kong gateway 3.5 and 3.6, it is only available in Kong Enterprise but not OSS.

**Comment by zackery-parkhurst** [comment]
@randmonkey Thank you for this information. I will try again when 3.7 is released. I will go ahead and close this issue out!
