### ISSUE TITLE
Expose fallback configuration metrics

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#6082]
We should make it possible to monitor fallback configuration process using Prometheus metrics:

- How many times fallback configuration was built
- How many successful/failed fallback config push attempts we had
- Last time of successful fallback configuration push

**Comment by programmer04** [comment]
One of places to track a metric https://github.com/Kong/kubernetes-ingress-controller/pull/6092#discussion_r1615885773
