### ISSUE TITLE
Why dose KIC not support different service point at same pod?

### ISSUE THREAD

**Issue by pyrl247** [Kong/kubernetes-ingress-controller#611]
In our kubernetes , we make 2 services select same pod label pod ,and the ingress controller report "duplicate target definitions". 
Is KIC not support this? if so , why?
Any help will be greatly appreciated!!!!

**Comment by hbagdi** [comment]
It seems like you are using an old version of the controller which had this bug.
Can you upgrade to a newer version to fix this issue?

**Comment by pyrl247** [comment]
OK，I will try.
thanks a lot！！
