### ISSUE TITLE
Preserving Client IP Address Docs Error?

### ISSUE THREAD

**Issue by paulopez78** [Kong/kubernetes-ingress-controller#612]
Hi,

I've been checking the docs about preserving client IP Address and I'm confused about something, not sure if this a mistake or this is ok.

https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/preserve-client-ip.md

> 
> ### GKE
> 
> You can use `ExternalTrafficPolicy: Cluster` to preserve the Client IP address.
> 
> ### AKS
> 
> You can use `ExternalTrafficPolicy: Cluster` to preserve the Client IP address.

Shouldn't be `Local` instead of `Cluster`?

Regards,
Pau.

**Comment by hbagdi** [comment]
Yes. That's incorrect. I spotted the same issue yesterday in a customer meeting as well. Would you mind sending in PR to fix this up quickly?

**Comment by paulopez78** [comment]
Yes no problem, I've created a PR here #
https://github.com/Kong/kubernetes-ingress-controller/pull/615

Regards,
Pau.
