### ISSUE TITLE
Duplicate KongConsumer in another namespace causes infinite loop and halts config updates

### ISSUE THREAD

**Issue by guneemwelloeux** [Kong/kubernetes-ingress-controller#613]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

Creating a `KongConsumer` with a username already used in another `KongConsumer` in another namespace causes `ingress-controller` to keep looping on items in a queue, with no successful sync.

I believe the root cause is that `KongConsumer` resources are namespaced, but the implementation of Kong is not, and enforces unicity on the username. This seems to indicate that Kong should either allow for duplicate consumers with the same username, or that `KongConsumer` should be made a cluster-wide resource.

**Kong Ingress controller version**
0.7.1

**Kong or Kong Enterprise version**
1.4

### Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: GCP
- **OS** (e.g. from /etc/os-release): Container-Optimized OS
- **Kernel** (e.g. `uname -a`): Linux gke-staging-cluster-high-mem-pool-3-a54925d6-kxmx 4.14.137+ #1 SMP Thu Aug 8 02:47:02 PDT 2019 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
- **Install tools**:
- **Others**:

### What happened
After creating a `KongConsumer` in namespace `foo` with username `john`, `ingress-controller` goes into a infinite loop over all the resources and keeps giving the same error:  `err entity already exists`

Below is a log extract:
```
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.7.1
  Build:      1527700
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.13.1
-------------------------------------------------------------------------------

I0423 12:08:39.164428       1 main.go:407] Creating API client for https://10.15.240.1:443
I0423 12:08:39.175639       1 main.go:451] Running in Kubernetes Cluster version v1.14+ (v1.14.10-gke.27) - git (clean) commit 145f9e21a4515947d6fb10819e5a336aff1b6959 - platform linux/amd64
I0423 12:08:39.205273       1 main.go:187] kong version: 1.4.3
I0423 12:08:39.205320       1 main.go:196] Kong datastore: postgres
I0423 12:08:39.469398       1 controller.go:224] starting Ingress controller
I0423 12:08:39.498745       1 status.go:201] new leader elected: ingress-kong-7ffd98dc7-bwfjg
I0423 12:08:42.929407       1 kong.go:66] successfully synced configuration to Kong
I0423 12:08:46.145526       1 kong.go:57] no configuration change, skipping sync to Kong
I0423 12:08:52.270131       1 kong.go:57] no configuration change, skipping sync to Kong
I0423 12:08:55.555902       1 kong.go:57] no configuration change, skipping sync to Kong
W0423 12:18:15.112724       1 parser.go:1079] service demo-test/bilirubin does not have any active endpoints
I0423 12:18:15.262662       1 kong.go:66] successfully synced configuration to Kong
I0423 12:18:18.549525       1 kong.go:66] successfully synced configuration to Kong
I0423 12:18:39.250688       1 kong.go:57] no configuration change, skipping sync to Kong
I0423 12:18:42.589141       1 kong.go:57] no configuration change, skipping sync to Kong
I0423 12:18:45.917752       1 kong.go:57] no configuration change, skipping sync to Kong
E0423 12:26:15.589535       1 controller.go:119] unexpected failure updating Kong configuration:
entity already exists
W0423 12:26:15.589595       1 queue.go:112] requeuing foo/john, err entity already exists
E0423 12:26:18.923322       1 controller.go:119] unexpected failure updating Kong configuration:
entity already exists
W0423 12:26:18.923361       1 queue.go:112] requeuing foo/john, err entity already exists
E0423 12:26:22.265718       1 controller.go:119] unexpected failure updating Kong configuration:
entity already exists
W0423 12:26:22.265848       1 queue.go:112] requeuing foo/john, err entity already exists
```

### Expected behavior
The new consumer should be created and synced, and available for 

### Steps To Reproduce

1. Create a `KongConsumer` in namespace `bar` with username `john`
2. Create a `KongConsumer` in namespace `foo` with username `john`
3. Create a `KongPlugin` in namespace `foo` of type `basic-auth`
3. Create an `Ingress` in namespace `foo`, with plugin (3) activated

**Comment by guneemwelloeux** [comment]
It would have been extremely useful for the log to mention which was the entity causing the error.
To investigate the issue, I had to remove resources one by one until the error stopped showing up.

**Comment by hbagdi** [comment]
> It would have been extremely useful for the log to mention which was the entity causing the error.
To investigate the issue, I had to remove resources one by one until the error stopped showing up.

Yes, totally reasonable. 

This is a known issue internally and users do run into this once in a while.

What experience would you like to have in a case where there are duplicate KongConsumer resources? We have the following options:
- KongConsumer resource that was created first takes precedence
- The other way around of the first option; where the KongConsumer resource that was created last should take precedence
- The draconian option of when there is a conflict, don't create a consumer in Kong

To signal the error, the controller can update the `Status` of the KongConsumer resource to signal an error. Is that helpful and sufficient?

**Comment by guneemwelloeux** [comment]
> What experience would you like to have in a case where there are duplicate KongConsumer resources? We have the following options:
> 
> * KongConsumer resource that was created first takes precedence
> * The other way around of the first option; where the KongConsumer resource that was created last should take precedence
> * The draconian option of when there is a conflict, don't create a consumer in Kong

I reckon the first option would make more sense. It is the more logical, since this is the one that is actually stored in the DB. 

> To signal the error, the controller can update the `Status` of the KongConsumer resource to signal an error. Is that helpful and sufficient?

It would definitely be helpful. I am not running the admission controller, so I don't really have a clear picture of what it is doing, but is the consumer clash something that could be raised by the admission controller as well, to try and prevent the issue as early as possible?

From a documentation standpoint, I think it would be helpful to mention somewhere in the documentation for KongConsumer that, despite the fact that these resources are namespace scoped, Kong enforces unicity on the "username".

I believe it would also be nice to mention that this username has nothing to do with the username `basic-auth` secrets, meaning that 2 separate KongConsumers with different usernames could use basic-auth credentials that have the same actual basic-auth username)

In my particular case, I am going to regroup all my `KongConsumer` objects in the `kong` namespace where my ingress controller is deployed, because to me, it makes more sense to run `kubectl get kc -n kong` rather than `kubectl get kc --all-namespaces`. It would provide a simpler way to access all consumers at once, and avoids having to chase them all over.

**Comment by hbagdi** [comment]
> I reckon the first option would make more sense. It is the more logical, since this is the one that is actually stored in the DB.

+1. I was thinking about the same thing.

>  I am not running the admission controller, so I don't really have a clear picture of what it is doing, but is the consumer clash something that could be raised by the admission controller as well, to try and prevent the issue as early as possible?

It already catches this specific error if you do set it up.

> From a documentation standpoint, I think it would be helpful to mention somewhere in the documentation for KongConsumer that, despite the fact that these resources are namespace scoped, Kong enforces unicity on the "username".

Noted. Tracking this internally. We will gladly accept a PR.

**Comment by hbagdi** [comment]
Considering this resolved. Please re-open if needed.
