### ISSUE TITLE
Fix failing GRPC conformance test

### ISSUE THREAD

**Issue by lahabana** [Kong/kubernetes-ingress-controller#6136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

As pointed in: https://github.com/Kong/kubernetes-ingress-controller/pull/5776/files#r1611405584

we have a few tests that do not pass with our GRPC route implementation. @tao12345666333 looked into and it seems to be a KIC problem and not a gateway problem so we should be able to make them pass

### Proposed Solution

- Pass the `host` that has been configured in Gateway to the final generated route.

### Acceptance Criteria

- [ ] The GRPCRoute conformance  `GRPCRouteListenerHostnameMatching` tests pass in Traditional mode

**Comment by pmalek** [comment]
The GRPC conformance enabled in #5776 seems to be failing for traditional copmatible router https://app.buildpulse.io/@Kong/kubernetes-ingress-controller/tests/17956419004?filter_results_type=flaky

example: https://github.com/Kong/kubernetes-ingress-controller/actions/runs/9404948579/job/25905145650

The problematic test case seems to be 

```
2024-06-06T17:11:27.8393367Z         --- FAIL: TestGatewayConformance/GRPCRouteHeaderMatching/3_request_to_'/gateway_api_conformance.echo_basic.grpcecho.GrpcEcho/Echo'_with_headers_'{Color:blue,Version:two}'_should_go_to_grpc-infra-backend-v2 (30.00s)
```

**Comment by tao12345666333** [comment]
The following are some contextual information related to the `GRPCRouteListenerHostnameMatching` case

- https://github.com/Kong/kubernetes-ingress-controller/pull/5303/
- https://github.com/Kong/kubernetes-ingress-controller/pull/4512#discussion_r1295239397
- https://github.com/Kong/kubernetes-ingress-controller/issues/4154

**Comment by tao12345666333** [comment]
@pmalek I will use this issue for tracking https://github.com/Kong/kubernetes-ingress-controller/issues/6144

For now I have skipped 
`tests.GRPCRouteHeaderMatching.ShortName` and enable `tests.GRPCExactMethodMatching.ShortName`

It will get a more stable result.
