### ISSUE TITLE
Log metadata for Konnect requests and provide KIC metadata with requests to Konnect

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#6240]
Partially copied from https://github.com/Kong/team-k8s/issues/307. That internal issue has some additional background.

Brief version is that KIC sends requests to Konnect to obtain licenses, push configuration, push metrics, etc. These requests sometimes go wrong. When those requests fail, we would like to identify related events in logs on both the KIC and Konnect sides. We can log Konnect request metadata and include our own metadata in these requests to assist correlation.

AC:

- [ ] KIC instances log upstream request IDs when interacting with Konnect infrastructure. Konnect-side infrastructure provides `x-datadog-trace-id` to downstream clients.
- [ ] When sending requests, KIC instances provides identifying information indicating which replica and replica set (e.g. Pod, Deployment) they belong to.
- [ ] KIC optionally provides its own request ID and other useful metadata we'd like to see in Konnect logs.
- [ ] We have documentation for operations and support teams to find and use these logs.

**Comment by czeslavo** [comment]
Kind of a duplicate for https://github.com/Kong/kubernetes-ingress-controller/issues/6236. I think we can use #6236 to define a final scope of what we'd like to do in #6240.
