### ISSUE TITLE
Kong 1.5.1 is not compatible with Kong ingress controller

### ISSUE THREAD

**Issue by GQH1993** [Kong/kubernetes-ingress-controller#625]
We want to use Kong 1.5.1 + Kong ingress controller to do API gateway service.
However, it is not found in the Version Compatibility. CRD does not work after manually replacing the image.

**Comment by GQH1993** [comment]
I need some help, thank you！

**Comment by GQH1993** [comment]
When I configure the wrong service, infinite retries will be caused because the endpoint cannot be found, and configuration errors will not be prompted when forwarding
![TIM截图20200427173401](https://user-images.githubusercontent.com/45929784/80357300-5bdab100-88ad-11ea-9269-2c670a073641.png)

**Comment by GQH1993** [comment]
W0427 09:23:38.212097       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212106       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found
W0427 09:23:38.212111       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212120       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found
W0427 09:23:38.212141       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212156       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found
W0427 09:23:38.212165       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212174       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found
W0427 09:23:38.212180       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212189       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found
W0427 09:23:38.212193       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212201       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found
W0427 09:23:38.212222       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212249       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found
W0427 09:23:38.212256       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212266       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found
W0427 09:23:38.212271       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212279       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found
W0427 09:23:38.212283       1 parser.go:1468] service / does not have any active endpoints
W0427 09:23:38.212314       1 parser.go:1658] unexpected error obtaining service endpoints: Endpoints for service / not found

**Comment by hbagdi** [comment]
Hey @GQH1993,

We will add the 1.5 to the compat doc.
The error you are seeing is because of you don't have any pods running of your service.
Please ensure that you have pods running for your service.

**Comment by GQH1993** [comment]
Thanks for your feedback, I have another question.
kong-ingress-controller monitors svc under other namespaces, is this normal?

**Comment by GQH1993** [comment]
Hey @hbagdi,

Thanks for your feedback, I have another question.
kong-ingress-controller monitors svc under other namespaces, is this normal?

**Comment by GQH1993** [comment]
Hey @hbagdi,
order-db                  ExternalName   <none>           www.baidu.com   <none>                       13h
I used ExternalName to create svc for routing external domain names such as www.baidu.com.
![image](https://user-images.githubusercontent.com/45929784/80434922-b156a280-892d-11ea-8c12-f1daa9a7a767.png)

**Comment by hbagdi** [comment]
>  kong-ingress-controller monitors svc under other namespaces, is this normal?

Yes. By default, kong will satisfy Ingress resources in all the namespaces. You can configure it to listen on a specific namespace as well.
