### ISSUE TITLE
Kong Ingress Controller creates a separate ACL plugin for each service instead of global one

### ISSUE THREAD

**Issue by vymarkov** [Kong/kubernetes-ingress-controller#626]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
Kong 2.0

**Kong or Kong Enterprise version**

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: AWS EKS 
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`): 
- **Install tools**: Helm v3, Kube CRD
- **Others**:

### What happened

Kong Ingress Controller creates a separate ACL plugin for each service instead of global one for all service with out any specific stuff. Also it remove all already defined ACL groups for consumers thus it deny access to services.

### Expected behavior

Kong Ingress Controller should create one global ACL plugin.

### Steps To Reproduce

1. Define the **Kong ACL plugin** manifest and apply via `kubectl apply -f kp-acl.yaml`.
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: acl-blacklist
  namespace: kong
  labels:
    global: "true"
plugin: acl
config:
  whitelist:
  - acl-blacklist
  - acl-free
  - foobar
  - barfoo
```

2. `curl http://localhost:8001/plugins/` to fetch a list of configured plugins. 
In my case it creates and configure the separate ACL plugins for each route.
![Screen Shot 2020-04-27 at 7 38 09 PM](https://user-images.githubusercontent.com/1110697/80397516-eaa3f980-88be-11ea-98d8-fbac857b72cf.png)

3. `curl  https://echo.prod.example.com`
```
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: echo.prod.example.com
User-Agent: HTTPie/2.1.0


HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 45
Content-Type: application/json; charset=utf-8
Date: Mon, 27 Apr 2020 16:41:53 GMT
Server: kong/2.0.3
X-Kong-Response-Latency: 2

{
    "message": "You cannot consume this service"
}
```

**Comment by hbagdi** [comment]
It seems that you might have a `konghq.com/plugins` annotation on an Ingress resource, which is resulting in this behavior.

**Comment by vymarkov** [comment]
@hbagdi hi,

actually we don't set any annotations on an Ingress resource.

**Comment by hbagdi** [comment]
Have you associated your consumer with an ACL group?
The following step demonstrates this: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/configure-acl-plugin.md#adding-acls

**Comment by hbagdi** [comment]
ping

**Comment by hbagdi** [comment]
Closing due to lack of response. Please re-open if needed.
