### ISSUE TITLE
oauth2 service config disapper after a while 

### ISSUE THREAD

**Issue by steinliber** [Kong/kubernetes-ingress-controller#63]
**Is this a request for help?**: No

**What keywords did you search in Kong Ingress controller issues before filing this one?** (If you have found any duplicates, you should instead reply there.): Bug

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

I want to set a oauth2 for service, but after i set plugin oauth2 use command below

> curl -X POST http://127.0.0.1:21688/services/nlp.service.satement/plugins \
    --data "name=oauth2"  \
    --data "config.scopes=email,phone,address" \
    --data "config.mandatory_scope=true" \
    --data "config.enable_password_grant=true"

I see config in  http://127.0.0.1:21688/services/nlp.service.satement/plugins

> {
"total": 1,
"data": [
{
"created_at": 1528278429000,
"config": {
"refresh_token_ttl": 1209600,
"enable_client_credentials": false,
"mandatory_scope": true,
"token_expiration": 7200,
"hide_credentials": false,
"scopes": [
"email",
"phone",
"address"
],
"enable_implicit_grant": false,
"global_credentials": false,
"anonymous": "",
"enable_password_grant": true,
"accept_http_if_already_terminated": false,
"enable_authorization_code": false,
"provision_key": "HEa6OUAwqRONFVGHmMslsoT9yaTDSPgR",
"auth_header_name": "authorization"
},
"id": "d959e8cd-afa2-4797-bd82-ec7a4f297672",
"name": "oauth2",
"service_id": "94548d5d-b055-49ff-9d23-ffd32cb80380",
"enabled": true
}
]
}

After few minute, this config disappear, I visit http://127.0.0.1:21688/services/nlp.service.satement/plugins
it return blank

**Kong Ingress controller version**: 0.0.4

**Kubernetes version** (use `kubectl version`): 1.8

**Environment**:

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): ubuntu 
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**Comment by gerred** [comment]
Can you share any relevant KongIngress or KongPlugin manifests?
