### ISSUE TITLE
Kong for Kubernetes does not 

### ISSUE THREAD

**Issue by grk-kulkarni** [Kong/kubernetes-ingress-controller#631]
### Summary

Kong for K8 does not honor strip-path annotations in the ingress resource. 

**Kong Ingress controller version**
1.5.1-centos

### Kubernetes version
1.17.4

### Environment
Cloud: AWS
OS: Centos

### What happened
We have ingress resource with the following annotations.
 kubernetes.io/ingress.class: "kong"
 konghq.com/strip-path: "false"

ingress resource path is "/share". for e.g ingress.yaml
paths:
      - path: /share

Kong proxy is updating routes.strip-path field in kong database to "TRUE" and stripping the path "/share/" from the path while forwarding the request. for e.g path with "/share/page/index.html" is getting forwarded to backend as "/page/index.html" 

### Expected behavior
We expected Kong proxy to update routes.strip-path field in kong database to false but the value is always TRUE for all routes. We expected Kong proxy to not strip the path vaule "/share" and forward the request to backend service with the correct path "/share/*". for e.g path with "/share/page/index.html" should get forwarded to backend as "/share/page/index.html"

**Comment by hbagdi** [comment]
Are you running controller 0.8.x? Older versions don't support that annotation.

**Comment by grk-kulkarni** [comment]
version for kong ingress controller is 0.7.1

**Comment by hbagdi** [comment]
Please upgrade. Or use `KongIngress` resource's `route.strip_path` property.
