### ISSUE TITLE
Data race on updating status of KongConsumer/KongConsunmerGroup

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#6386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From FTI-6157.
Customer uses sidecar mode to deploy KIC. When KIC is scaled, multiple KIC are updating the status of the same `KongConsumer`, so lots of reconcile errors occur and may produce excessive requests to k8s APIserver and make other controllers stuck. 

### Expected Behavior

No race happens causing reconciliation errors when multiple instances of KIC are reconciling the same `KongConsumer` or `KongConsumerGroup`.

### Steps To Reproduce

```markdown
1. Deploy KIC with sidecar mode
2. Create a KongConsumer in the cluster
3. Scale the KIC to 3 replicas
4. Check the log of new created KIC pods, and we can see `Reconcile error` or `Reconciler error` happens on KongConsumer because of conflict on updating their status.
```

### Kong Ingress Controller version

```shell
2.11 and later
```

### Kubernetes version

```shell
Not relevant.
```

### Anything else?

Customer need the fix to be backported to 2.12.x LTS.

**Comment by randmonkey** [comment]
The most possible reason for the data race to happen: When a new pod is created from the scale, the status of k8s objects are "Unknown" in dataplane client. The new pod want to update the `Programmed` to `Unknown` but the old pod want to update `Programmed` to `True`. The flip of `Programmed` condition produces many reconcile requests and possible data races on updating.
When the "new" pods succeeded to configure the `KongConsumer`s and the configuration status became `True`, the update would diverge. But when the reconcile requests are too many (when lots of `KongConsumer`s and many pods are updating), the requests may stuck the API server that causes long duration of data race status.
Possible solution:
- Do not update `condition`s in status of `KongConsumer`/`KongConsumerGroup`, like `KongPlugin/KongClusterPlugin`
-  Set `AncestorStatus` and make one item per KIC instance, like `KongUpstreamPolicy`. This could reduce the chance of data race.
- Do not update `Programmed` condition to `Unknown` when the `Programmed` condition already exists (maybe only true in the first X seconds after up or before the first config applying).

**Comment by czeslavo** [comment]
> Do not update Programmed condition to Unknown when the Programmed condition already exists (maybe only true in the first X seconds after up or before the first config applying).

It sounds reasonable - it doesn't make sense to transition from Programmed to Unknown in any circumstances.

**Comment by pmalek** [comment]
Can Consumers be assigned an Ingress class? 🤔 

Since those KIC instances share the same Ingress class (or can't have it assigned) this might happen regardless in the sidecar mode. If Gateway Discovery with leader election enabled was used then there would only be 1 KIC instance setting the status.

---

Solution to this issue which would be to not update the status as proposed by @randmonkey will help solve the symptoms which is good but will not solve the problem of having multiple KIC instances using the same Consumers and trying to fill its status independently (1 KIC can fail and 1 can succeed in applying the consumer in Kong Gateway config).

But I believe this is a problem inherent to sidecar mode which we won't solve in here so addressing solely the status data race makes sense.

**Comment by randmonkey** [comment]
> Can Consumers be assigned an Ingress class? 🤔
> 
> Since those KIC instances share the same Ingress class (or can't have it assigned) this might happen regardless in the sidecar mode. If Gateway Discovery with leader election enabled was used then there would only be 1 KIC instance setting the status.
> 
> Solution to this issue which would be to not update the status as proposed by @randmonkey will help solve the symptoms which is good but will not solve the problem of having multiple KIC instances using the same Consumers and trying to fill its status independently (1 KIC can fail and 1 can succeed in applying the consumer in Kong Gateway config).
> 
> But I believe this is a problem inherent to sidecar mode which we won't solve in here so addressing solely the status data race makes sense.

They have ingress classes now.

**Comment by pmalek** [comment]
> They have ingress classes now.

Where is this checked in code? Do we have this documented anywhere?

**Comment by randmonkey** [comment]
Definition of `KongConsumer` controller is here:
```
typeNeeded{
		Group:                             "configuration.konghq.com",
		Version:                           "v1",
		Kind:                              "KongConsumer",
		PackageImportAlias:                "kongv1",
		PackageAlias:                      "KongV1",
		Package:                           kongv1,
		Plural:                            "kongconsumers",
		CacheType:                         "Consumer",
		NeedsStatusPermissions:            true,
		AcceptsIngressClassNameAnnotation: true,
		AcceptsIngressClassNameSpec:       false,
		NeedsUpdateReferences:             true,
		RBACVerbs:                         []string{"get", "list", "watch"},
		ConfigStatusNotificationsEnabled:  true,
		ProgrammedCondition: ProgrammedConditionConfiguration{
			UpdatesEnabled: true,
		},
	},
```
The doc is here: https://docs.konghq.com/kubernetes-ingress-controller/latest/reference/resource-requiring-ingress-class/ .
