### ISSUE TITLE
AWS ELB HTTP to HTTPS redirection error

### ISSUE THREAD

**Issue by yang-xiaodong** [Kong/kubernetes-ingress-controller#639]
### Summary

When I used Kong Ingress in EKS with ACM, I encountered the same error: `The plain HTTP request was sent to HTTPS port`, it has been solved in Nginx ingress, I want to know how to do it in Kong Ingress, Thanks

Nginx ingress fixed PR: https://github.com/kubernetes/ingress-nginx/pull/5374

**Kong Ingress controller version**

 2.0

### Kubernetes version

EKS 1.15

**Comment by hbagdi** [comment]
You need to ensure that traffic on port 80 and 443 is sent on port 8000 in Kong.
