### ISSUE TITLE
Rewrite annotation not working on every request when multiple Ingresses share same backing service

### ISSUE THREAD

**Issue by herself** [Kong/kubernetes-ingress-controller#6542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have two Ingresses sharing the same backing service. One has a `konghq.com/rewrite` annotation. About half of the requests going to the Ingress with the annotation don't get the rewrite rule applied.

### Expected Behavior

Every request is re-written properly.

### Steps To Reproduce

```markdown
1. Create two Ingresses that have the same backing service
2. Add a rewrite annotation to one of them
3. Post some requests. They will get re-written or not randomly
4. If you change the backing service to another on one of the Ingresses, it will work properly again

This has been outlined with examples in https://github.com/Kong/kubernetes-ingress-controller/issues/5021. I think this bug might be a reintroduction of that one, as they're practically the same
```

### Kong Ingress Controller version

```shell
3.3
```

### Kubernetes version

```shell
v1.28.13-eks-a737599
```

**Comment by herself** [comment]
Since this doesn't look like it's getting fixed fast, here's a workaround that works for me: Just copy the existing `Service` object that's used in the `spec.rules[].paths[].backend.service` part of your `Ingress`, give it a new name and modify one of the `Ingress`es to use it.

It won't matter that the backing Pods are the same, as long as it's an `Service` object with a different name.

**Comment by programmer04** [comment]
Indeed the problem exists, tested with the image `kong/kubernetes-ingress-controller:3.3`

Steps to reproduce

1. Example service 
    ```sh
    echo '
    apiVersion: v1
    kind: Service
    metadata:
     name: echo
    spec:
     ports:
       - protocol: TCP
         name: http
         port: 80
         targetPort: http
     selector:
       app: echo
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
     name: echo
    spec:
     replicas: 1
     selector:
       matchLabels:
         app: echo
     template:
       metadata:
         labels:
           app: echo
       spec:
         containers:
           - name: echo
             image: kong/go-echo:0.4.0
             ports:
               - containerPort: 1027
                 name: http
    ' | kubectl apply -f -
    ```

2. Deploy first `Ingress` - `echo1` without rewrite annotation
    ```sh
    echo '
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: echo1
    spec:
      ingressClassName: kong
      rules:
        - http:
            paths:
              - path: /echo
                pathType: ImplementationSpecific
                backend:
                  service:
                    name: echo
                    port:
                      name: http
    ' | kubectl apply -f -
    ```

3. Deploy second `Ingress` - `echo2` with rewrite annotation
    ```sh
    echo '
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: echo2
      annotations:
        konghq.com/rewrite: /api/foo
    spec:
      ingressClassName: kong
      rules:
      - http:
          paths:
          - path: /rewrite
            pathType: ImplementationSpecific
            backend:
              service:
                name: echo
                port:
                  name: http
    ' | kubectl apply -f -
    ```
   
4. Test, passing `?details=true` returns in response detail of what has been sent to the service

   - First `Ingress` - `echo1` routing
        ```sh
        curl '<GW-IP>/echo?details=true'
        ```
    
        ```txt
        HTTP request details
        ---------------------
        Protocol: HTTP/1.1
        Host: 10.96.10.25
        Method: GET
        URL: /echo?details=true
        ```

    - Second `Ingress` - `echo2` routing
        ```sh
        curl '<GW-IP>/echo?details=true'
        ```
        
        Sometimes it behaves as expected
        ```txt
        HTTP request details
        ---------------------
        Protocol: HTTP/1.1
        Host: 10.96.10.25
        Method: GET
        URL: /api/foo?details=true
        ```
        
        But it also does not
        ```txt
        HTTP request details
        ---------------------
        Protocol: HTTP/1.1
        Host: 10.96.10.25
        Method: GET
        URL: /rewrite?details=true
        ```
        
        Removing the first `Ingress` - `echo1` fixes the problem. Also when configured in different order firstly `echo2` and next `echo1` it seems to behave as expected.

**Comment by programmer04** [comment]
FYI @herself the next release `v3.4` will contain the fix

**Comment by herself** [comment]
> FYI @herself the next release `v3.4` will contain the fix

Awesome, thank you both for the fix and the heads-up! <3
