### ISSUE TITLE
`RequestRedirect` filter on HTTPRoute cannot preserve path in request

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#6557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

From FTI-6305.
Because the `RequestRedirect` filter is implemented by `request-termination` and `response-transformer` plugin. This cannot include variable part in the response head. So the redirect path in the response body is fixed and cannot preserve path in the request.

### Proposed Solution

- Use some other method to generate redirect response that can send variable response according to the request
  - For example: run a standalone server to send responses

### Acceptance Criteria

- [x] Redirect path in the response header can be preserved if no path is given
- [ ] `ReplacePrefixMatch` is also supported

**Comment by mheap** [comment]
Can this be implemented with a pre-function plugin?

```lua
kong.response.exit(301, 'redirecting', {['Location'] = 'https://other.example.com/' .. kong.request.get_path_with_query()})
```

**Comment by randmonkey** [comment]
@mheap has submitted a PR for adding a `redirect` plugin: https://github.com/Kong/kong/pull/13900 
Using the plugin (only for Kong 3.9, or other version that contains the plugin) should resolve this.
If Kong does not support this plugin, we should either:
- report a translation error
- Implement by `pre-function` plugin
@mheap Which one do you think is the better resolution?

**Comment by mheap** [comment]
I think we should leave the existing implementation pre 3.9, and use the new plugin in 3.9+.

`pre-function` is used enough that I would not want to prevent users using it if adding redirects

**Comment by randmonkey** [comment]
Now https://github.com/Kong/kong/pull/13900 is merged and we can use the `redirect` plugin if Kong version is above or equal to `3.9`. However, the plugin seems still cannot satisfy the `replacePrefixMatch`. @mheap do we have plan to support it?

**Comment by lahabana** [comment]
Let's just move support for `ReplacePrefixMatch` to a future release and do just `redirect` in 3.4 to be able to close the FTI.
