### ISSUE TITLE
Analysis of KIC's memory usage

### ISSUE THREAD

**Issue by tao12345666333** [Kong/kubernetes-ingress-controller#6576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

xref: FTI-5975

We have received a very special report, and the data in it indicate an abnormal increase in KIC's memory usage.

At the same time, there is a point that needs attention here. The deployment mode used in this report is sidecar mode.

I created this issue for task tracking. I will update it with any noteworthy progress to share later on.

### Acceptance Criteria

- [ ] Find and resolve the anomaly in the detailed information of the analysis report.

**Comment by tao12345666333** [comment]
After our testing, it was found that this issue may occur when there are a large number of huge secrets resources in the cluster.

In this specific scenario, there are over 4000 secrets resources, with an average size of 500KB.

These secrets resources come from the history of Helm release. After attempting to delete some unused secrets resources, KIC's memory usage is relieved and returns to normal levels after restarting.

**Comment by lahabana** [comment]
@tao12345666333 are you still planning on introducing a config switch to filter out some secrets?

**Comment by tao12345666333** [comment]
We can use some relatively simple methods to test. For example, create an empty Helm chart that only contains a large number of CRD resources and install it into the Kubernetes cluster.

I can quickly observe that as the Helm release is created (which means a large secret resource is created), KIC's memory starts to increase.  This indicates that it is attempting to unmarshal the secret resource and determining whether to cache it. 

In this testing scenario, since the secret resources created by Helm release have no relation to KIC, after this, the memory of KIC will return to normal level.

**Comment by tao12345666333** [comment]
> @tao12345666333 are you still planning on introducing a config switch to filter out some secrets?

@lahabana Yes. I am trying to figure out how to achieve it with minimal changes. Also working on writing a proposal.
