### ISSUE TITLE
Generate manifests from CRDs in kong/kubernetes-configuration repo

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#6579]
Part of #6488.
The scripts to generate manifests of installing CRDs should fetch CRDs from the kong/kubernetes-configuration instead using the CRDs in the `pkg/apis` package.

### Acceptance Criteria
- [ ] All scripts for generating manifests fetch CRDs from kong/kubernetes-configuration  repo

**Comment by czeslavo** [comment]
It's already done: https://github.com/Kong/kubernetes-ingress-controller/blob/0cb54115d5dd4ffc020caf18b6a3767b69866c22/config/crd/kustomization.yaml#L5. The all-in-one manifests generated for tests are generated from this kustomize which relies on `kong/kubernetes-configuration` resource.
