### ISSUE TITLE
Add flagger support for automated canary releasing

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kubernetes-ingress-controller#658]
Support for https://flagger.app to provide automated canary rollouts

**Comment by hbagdi** [comment]
This feature is currently blocked on Kong as it doesn’t provide a canarying feature needed to implement this functionality. (Kong Enterprise provides such a feature, this issue tracks the feature request for Kong open-source).

**Comment by jiraguha** [comment]
Hi @hbagdi, Any changes regarding this issue?

**Comment by hbagdi** [comment]
None yet.
Kong has yet to implement the canary release functionality and it is on the roadmap.

**Comment by hbagdi** [comment]
Feature request in Kong: https://github.com/Kong/kong/issues/6335

**Comment by mflendrich** [comment]
Handled in #557 - closing as duplicate
