### ISSUE TITLE
Kong Ingress Controller Flooding with “Unsupported parentRef kind Service” Error When Using HTTPRoute with Service as ParentRef in Service Mesh

### ISSUE THREAD

**Issue by surenraju-careem** [Kong/kubernetes-ingress-controller#6584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

When using GatewayAPI with Linkerd/Istio service mesh, we deploy HTTPRoute resources with parentRef set to a Service. This configuration is standard and supported by other service mesh solutions. However, the Kong Ingress Controller repeatedly logs the following error message:
```
unsupported parentRef kind Service and group core
Got an unexpected kind and group when checking route's parentRefs
```
https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/controllers/gateway/route_predicates.go#L91

**Steps to Reproduce**

	1.	Configure GatewayAPI in a cluster with Linkerd service mesh.
	2.	Deploy an HTTPRoute resource with parentRef set to a Service.
	3.	Observe the logs from Kong Ingress Controller, which flood with the “unsupported parentRef” error.

### Proposed Solution

Kong Ingress Controller should not log errors when Service as a parentRef kind in HTTPRoute when used with service mesh solutions, in line with GatewayAPI specifications.

https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/controllers/gateway/route_predicates.go#L91

### Additional information

https://github.com/Kong/kubernetes-ingress-controller/blob/main/internal/controllers/gateway/route_predicates.go#L91

### Acceptance Criteria

Kong Ingress Controller should not log errors when Service as a parentRef kind in HTTPRoute when used with service mesh solutions, in line with GatewayAPI specifications.

**Comment by randmonkey** [comment]
@surenraju-careem  So the `HTTPRoute` is not controlled by KIC. We should ignore the `parentRef` item if it refers to a Service.
