### ISSUE TITLE
Update guide page of custom entity in GA context

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#6628]
Currently we have a guide page for using custom entities: https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/services/custom-entity/. The page is wriiten when the `CustomEntity` feature is in alpha maturity so we need to change it to the context of GA. 

### Acceptance Criteria
- [ ] Guide page of custom entity does not contain "alpha maturity" contents

**Comment by pmalek** [comment]
https://github.com/Kong/docs.konghq.com/pull/8153 contains the changes. It also flips the `Stage` for the FG from `Beta` to `GA` at https://deploy-preview-8153--kongdocs.netlify.app/kubernetes-ingress-controller/unreleased/reference/feature-gates/

**Comment by pmalek** [comment]
https://github.com/Kong/docs.konghq.com/pull/8153 has been merged
