### ISSUE TITLE
Test for scenarios out of the guide and fix the misbehaviors

### ISSUE THREAD

**Issue by randmonkey** [Kong/kubernetes-ingress-controller#6629]
We need to test for scenarios on using custom entities out of the guide and check if there are any misbehavior of KIC happen. The misbehavior that results in significant unexpected phenomena (like panic, invalid Kong configuration) should have separate issues created and fixed before release.

### Acceptance Criteria
- [ ] A list of misuse scenario created and tests are run for each case
- [ ] Significant problems happened have issue created and fixed
- [ ] Feasible scenarios are turned into automatic test cases (envtest/integration test)

**Comment by pmalek** [comment]
Created the following issues:
- #6793, should be solved by #6802 
- #6794, should be solved by #6802
- #6787, resolved by #6791 and https://github.com/Kong/kubernetes-configuration/pull/180

Closing. If anything else is discovered let's reopen and reassess.
