### ISSUE TITLE
KIC relies on kong/kubernetes-configuration@v1.0.0

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#6635]
The goal of this issue is to make sure we release `kong/kubernetes-configuration` v1.0.0 before we release KIC relying on this module.

### Acceptance criteria
- [ ] `kong/kubernetes-configuration` dependency in go.mod is v1.0.0 (or higher)

**Comment by czeslavo** [comment]
It's no longer blocked - all outstanding tasks we wanted to complete before v1 in KCONF are done. We haven't released proper `v1.0.0` yet, though, as we concluded it's better to postpone it until just before the KIC 3.4 release to allow us to discover any potential issues. We'll keep releasing RCs of KCONF until then.

Releasing v1 can be done by triggering the release workflow: https://github.com/Kong/kubernetes-configuration/actions/workflows/release.yaml

**Comment by programmer04** [comment]
Now all the below relies on `v1.0.0`
- https://github.com/Kong/kubernetes-ingress-controller/pull/6832
