### ISSUE TITLE
Migrate deck from to kubernetes-configuration

### ISSUE THREAD

**Issue by pmalek** [Kong/kubernetes-ingress-controller#6641]
`deck` also relies on KIC's api types:

https://github.com/search?q=repo%3AKong%2Fdeck+github.com%2Fkong%2Fkubernetes-ingress-controller%2Fv3+language%3AGo&type=code&l=Go

This task tracks the migration of its dependency from KIC to kubernetes-configuration repo when KIC is already migrated.

**Comment by czeslavo** [comment]
Just a note just in case we do not have enough time to fit this into KIC 3.4 release: KIC types will stay in the repo, but will be deprecated. This will give us more time to migrate deck async.
