### ISSUE TITLE
Kong ingress controller(v3.3) panic: runtime error: invalid memory address or nil pointer dereference [recovered]   

### ISSUE THREAD

**Issue by Puvendhan** [Kong/kubernetes-ingress-controller#6649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting panic error:

` >
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d50bd2]

goroutine 527 [running]:
k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x26f0068, 0x39fa480}, {0x2028900, 0x399b6e0}, {0x39fa480, 0x0, 0x100000000000000?})
    /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:89 +0xee
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
    /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/runtime/runtime.go:59 +0x108
panic({0x2028900?, 0x399b6e0?})
    /usr/local/go/src/runtime/panic.go:785 +0x132
github.com/kong/kubernetes-ingress-controller/v3/internal/controllers/configuration.(*KongUpstreamPolicyReconciler).getUpstreamPoliciesForIngressServices(0xc000029730, {0x26f02d0, 0xc0008289b0}, {0x271ba90?, 0xc0008634a0})
    /workspace/internal/controllers/configuration/kongupstreampolicy_controller.go:327 +0xb2
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc[...]).mapAndEnqueue(0x2717080?, {0x26f02d0, 0xc0008289b0?}, {0x27008e0?, 0xc000772d60}, {0x271ba90, 0xc0008634a0?}, 0xc0007cfcd0?)
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/handler/enqueue_mapped.go:119 +0x67
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc[...]).Create(...)
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/handler/enqueue_mapped.go:84
sigs.k8s.io/controller-runtime/pkg/internal/source.(*EventHandler[...]).OnAdd(0x14, {0x2361b60?, 0xc0008634a0})
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/source/event_handler.go:92 +0x255
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
    /home/runner/go/pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/controller.go:246
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /home/runner/go/pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/shared_informer.go:978 +0x139
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
    /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:226 +0x33
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0007cff70, {0x26d1240, 0xc000edf260}, 0x1, 0xc000ef5030)
    /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:227 +0xaf
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ef8770, 0x3b9aca00, 0x0, 0x1, 0xc000ef5030)
    /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:204 +0x7f
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000fffa70)
    /home/runner/go/pkg/mod/k8s.io/client-go@v0.31.0/tools/cache/shared_informer.go:972 +0x5a
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
    /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/wait.go:72 +0x4c
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 501
    /home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.0/pkg/util/wait/wait.go:70 +0x73`

### Expected Behavior

Kong ingress controller pod should come up.

### Steps To Reproduce

```markdown
I tried with below commands, but result is same.

method:1
helm install kong kong/ingress -n kong --create-namespace 

method:2
helm upgrade --install controller kong/kong -n kic --create-namespace --set ingressController.enabled=true --set ingressController.gatewayDiscovery.enabled=true --set ingressController.gatewayDiscovery.adminApiService.name=gateway-kong-admin --set deployment.kong.enabled=false --set replicaCount=2
```

### Kong Ingress Controller version

```shell
3.3
```

### Kubernetes version

```shell
1.30.5-gke.1014001
```

### Anything else?

I followed the below documentation, but not working.

https://docs.konghq.com/kubernetes-ingress-controller/latest/install/helm/

**Comment by pmalek** [comment]
Should be fixed with #6651
