### ISSUE TITLE
add a metric to track the config size sent to the DP

### ISSUE THREAD

**Issue by lahabana** [Kong/kubernetes-ingress-controller#6659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this enhancement require public documentation?

- [X] I have added an Acceptance Criteria item for adding and/or adjusting public documentation (if applicable)

### Problem Statement

There doesn't seem to be a way today to easily track the size of the config sent to the DP.
Seeing this could enable users to track more easily what change has caused a large increase in config size and lead to performance degradation.

### Proposed Solution

- Let's add a metric when pushing this likely in [prometheus metrics](https://github.com/Kong/kubernetes-ingress-controller/blob/d593a6781a0481817f720460f52b3746d7f9d175/internal/metrics/prometheus.go#L357-L371)

### Acceptance Criteria

- [x] users can easily track and understand config size
- [x] metric is documented
- [x] ~~grafana dashboards (do we have some?) are updated~~

**Comment by programmer04** [comment]
The only thing left is the Grafana dashboard that needs to be figured out what's going on with it

cc: @lahabana

**Comment by lahabana** [comment]
@programmer04 conclusion from our chats is that Dashboards should be reworked but this is out of scope of this issue.
