### ISSUE TITLE
Renovate for config/crd kustomize dependency on kong/kubernetes-configuration

### ISSUE THREAD

**Issue by czeslavo** [Kong/kubernetes-ingress-controller#6663]
Make sure that `config/crd/kustomization.yaml` dependency on `https://github.com/kong/kubernetes-configuration/config/crd/ingress-controller?ref=v.X.X.X` is updated automatically by Renovate OR make this file generated and use a version from go.mod.

Blocked by https://github.com/Kong/kubernetes-ingress-controller/issues/6578.

**Comment by czeslavo** [comment]
It looks like this won't be needed, as Renovate can detect remote kustomizations as I verified on my fork.

**Comment by pmalek** [comment]
While renovate does detect the changes in kustomize manifests and bumps them automatically (e.g. https://github.com/Kong/kubernetes-ingress-controller/pull/6675) we'd ideally synchronize these version bumps (in the manifest) with dependabot Go version bumps (e.g. https://github.com/Kong/kubernetes-ingress-controller/pull/6672)

Reopening this to cover the above.
