### ISSUE TITLE
GCP Backend UNHEALTHY for Proxy service using the GCE Ingress Controller

### ISSUE THREAD

**Issue by ops18** [Kong/kubernetes-ingress-controller#667]
### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
kong:2.0
**Kong or Kong Enterprise version**
NA

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

### Environment
GCP(GKE)
- **Cloud provider or hardware configuration**: GCP
- **OS** (e.g. from /etc/os-release):COS
- **Kernel** (e.g. `uname -a`):
- **Install tools**: GKE
- **Others**:

### What happened
Unable to expose the proxy service using the gce ingress controller , backend unhealthy
it work when the expose proxy using the nginx ingress controller
### Expected behavior
Backend is to be healthy

### Steps To Reproduce
Expose the kong proxy service using the gce ingress controller
1.Deploy a kong using the helm chart make sure proxy service type is NodePort
2.Enable the ingress and add annotation for gce ingress controller (class:"gce")
3.Verify the backend status in LoadBalancer configuration
4.Backend is unhealty unable to access the proxy using the ingress ip

#455 
#:~/chart/kong# kubectl get svc,po,ing -n kong
NAME                              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
service/kong-proxy                NodePort    10.0.26.60    <none>        80:32247/TCP,443:31214/TCP   8m29s
#:~/chart/kong# kubectl get svc,po,ing -n kong
NAME                              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)                      AGE
service/kong-proxy                NodePort    10.0.26.60    <none>        80:32247/TCP,443:31214/TCP   9m8s
service/kong-validation-webhook   ClusterIP   10.0.25.240   <none>        443/TCP                      9m8s

NAME                                READY   STATUS    RESTARTS   AGE
pod/ingress-kong-56459f8698-bx5jb   2/2     Running   1          9m8s

NAME                    HOSTS              ADDRESS       PORTS   AGE
ingress.extensions/ks   kong.example.com   34.98.88.59   80      8m29s

#:~/chart/kong# kubectl describe ing ks -n kong
Name:             ks
Namespace:        kong
Address:          34.98.88.59
Default backend:  default-http-backend:80 (10.32.0.9:8080)
Rules:
  Host              Path  Backends
  ----              ----  --------
  kong.example.com  
                    /   kong-proxy:80 (10.32.2.153:8000)
Annotations:
  ingress.kubernetes.io/backends:                    {"k8s-be-30565--483049ccdaeac0c8":"UNHEALTHY","k8s1-483049cc-kong-kong-proxy-80-90adc07b":"UNHEALTHY"}
  ingress.kubernetes.io/forwarding-rule:             k8s-fw-kong-ks--483049ccdaeac0c8
  ingress.kubernetes.io/target-proxy:                k8s-tp-kong-ks--483049ccdaeac0c8
  ingress.kubernetes.io/url-map:                     k8s-um-kong-ks--483049ccdaeac0c8
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"gce"},"name":"ks","namespace":"kong"},"spec":{"rules":[{"host":"cafe.example.com","http":{"paths":[{"backend":{"serviceName":"kong-proxy","servicePort":80},"path":"/"}]}}]}}

  kubernetes.io/ingress.class:  gce
Events:
  Type    Reason  Age    From                     Message
  ----    ------  ----   ----                     -------
  Normal  ADD     8m32s  loadbalancer-controller  kong/ks
  Normal  CREATE  7m59s  loadbalancer-controller  ip: 34.98.88.59

**Comment by hbagdi** [comment]
You need to configure the right healthcheck in GCE so that the LB can health-check correctly.
Please consult GKE documentation for this purpose.

**Comment by ops18** [comment]
:~/chart/kong/kong# kubectl get po,svc,ing -n k
NAME                                  READY   STATUS    RESTARTS   AGE
pod/kong-test-kong-85b74b9f4d-42w97   2/2     Running   1          74m

NAME                           TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
service/kong-test-kong-proxy   NodePort   10.0.31.211   <none>        8000:32090/TCP   74m

NAME                              HOSTS   ADDRESS         PORTS   AGE
ingress.extensions/test-ingress   *       130.211.35.93   80      38m


deploy using the helm chart 

create a ingress and point out the health check using the /status for proxy service
still the backend is unhealthy 

Is there any other way to make a HealthCheck correctly .

I tryied with below changes in my health check 
/
/status 
but still it is unhealty

**Comment by ops18** [comment]
Hi I try with healch check with
1. /
2. /status (as this is configure in redinessprobe in kong configuration)
how can set the proper health check in gce 
if / and /status is not working with gce ingress controller.

**Comment by ops18** [comment]
Now its done, change the Healthchek port with /status to get the 200 respose from LoadBalancer to backend and now its working fine.
