### ISSUE TITLE
Catch errors in divergence of single and base manifests

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#668]
CI should report an error if a commit changes the base manifests but doesn't update the single manifests `./hack/build-single-manifests.sh`.

**Comment by CremBluRay** [comment]
If someone else hasn't already, can I take a stab at this one?

**Comment by hbagdi** [comment]
Go at it!
cc @rainest

**Comment by hbagdi** [comment]
Already merged.
