### ISSUE TITLE
Missing documentation of `enable-reverse-sync`

### ISSUE THREAD

**Issue by aaronhmiller** [Kong/kubernetes-ingress-controller#669]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.8.1

**Kong or Kong Enterprise version**
n/a

### Kubernetes version

**paste `kubectl version` output**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
saw new enable-reverse-sync feature

### Expected behavior
doc indicating how to set it and what parameter it takes (i.e. boolean)

### Steps To Reproduce

1. read the changelog
2. go to doc to read up on new feature
3. find that it's not documented
4. but see the feature in the commit log

**Comment by hbagdi** [comment]
This was fixed in https://github.com/Kong/kubernetes-ingress-controller/pull/718
