### ISSUE TITLE
Recreating KongConsumer doesn't update kong in-memory configuration

### ISSUE THREAD

**Issue by estebangarcia** [Kong/kubernetes-ingress-controller#674]
### Summary

Recreating KongConsumer with a different custom_id doesn't update kong's in-memory configuration

**Kong Ingress controller version**
0.8.0

**Kong or Kong Enterprise version**
Kong 2.0

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:23:21Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: DigitalOcean
- **OS** (e.g. from /etc/os-release): Managed Kubernetes
- **Kernel** (e.g. `uname -a`): 
- **Install tools**: Helm
- **Others**:

### What happened

I'm using kong's JWT plugin, I have an API that handles users and it creates a KongConsumer and credential secret on user signup. The KongConsumer includes the `username` and `custom_id` fields.

Once I use the token to access a protected endpoint all the `X-Consumer-*` headers are injected and everything work just fine, but if I remove and recreate the KongConsumer with the same information except for a different `custom_id` it seems that kong's in-memory configuration is not updated and when I access the protected endpoint the `X-Consumer-Custom-ID` header has the old id from the previously deleted KongConsumer resource. 

After restarting the controller the `X-Consumer-Custom-ID` is correct.

### Expected behavior

When the KongConsumer is recreated with the new custom_id the `X-Consumer-Custom-ID` header value should be the new value and not the old one from the deleted resource.

### Steps To Reproduce

1. Create KongConsumer with username and custom_id
2. Access protected resource, check X-Consumer-Custom-ID is the expected value
3. Delete and recreate KongConsumer with the same name, username and a different custom_id
4. Access protected resource, the X-Consumer-Custom-ID value is from the old resource and not the new one.
5. Restart controller
6. X-Consumer-Custom-ID is now showing the correct value.

**Comment by hbagdi** [comment]
Could you give this a go with `kong-docker-kubernetes-ingress-controller.bintray.io/master:c7475f9` image? That corresponds to the tip of the 0.9 release.

**Comment by estebangarcia** [comment]
@hbagdi I just tried it and experienced the same issue.

**Comment by hbagdi** [comment]
Which version of Kong are you using?

**Comment by estebangarcia** [comment]
I'm using 2.0, I've just updated my original post with the version as well.

**Comment by hbagdi** [comment]
Can you try with 2.0.4?
Is it possible for you to forward to port 8444 inside the proxy container in the ingress-kong pod?
If yes, can you please forward the port after step number 4, and check if the custom_id is updated or not in Kong via the Admin API?
`curl -k https://localhost:8444/consumers` should show that.

**Comment by estebangarcia** [comment]
With Kong 2.0.4 is now working ok. Thanks for your help.
