### ISSUE TITLE
Docs: Document caveats with Knative split and visibility issues

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#679]
Currently, the controller works with some APIs of Knative but not all.
Traffic splits are not handled at all and visibility fields are ignored. These should be explicitly documented and communicate to the users.

**Comment by mflendrich** [comment]
@hbagdi could you please clarify what "some APIs of Knative but not all" means here?

**Comment by hbagdi** [comment]
That's misleading description on my part. What I mean is that traffic split and visibility configuration is currently ignored by our controller and we need to explicitly document that.
We do want to add these features but they are blocked until Kong itself implements those.

**Comment by shaneutt** [comment]
Closing as stale. We haven't seen strong interest or usage of our Knative integrations so it's not clear to us how to prioritize this at the moment: if you're reading this and have a strong need and use case please feel free to comment here and we would be happy to re-open this and re-assess.
