### ISSUE TITLE
kubectl patch kongingress does not work

### ISSUE THREAD

**Issue by Ngob** [Kong/kubernetes-ingress-controller#68]
**Is this a request for help?**:

No

**What keywords did you search in Kong Ingress controller issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

`patch`. Looks similar to https://github.com/Kong/kubernetes-ingress-controller/pull/42 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug request
**Kong Ingress controller version**:

0.0.4

**Kubernetes version** (use `kubectl version`):

Server: v1.10.4-gke.0
Client : v1.9.7

**Environment**:

- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): I am using the Container Optimized OS provided by google:

```
BUILD_ID=10452.101.0
NAME="Container-Optimized OS"
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=66
ID=cos
```

- **Kernel** (e.g. `uname -a`): Linux gke-prod-1-default-pool-560ebb10-xx4d 4.14.22+
- **Install tools**:  I used the basic getting started provided by your [blog](https://konghq.com/blog/kubernetes-ingress-controller-for-kong/) 
- **Others**:

**What happened**:

I added the following kongingress configuration
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: foo
  namespace:  baz
proxy:
  path: /xorf
route:
  strip_path: true
```
and then:
```
kubectl patch kongingress foo --namespace="baz" -p '{"proxy": {"path": "\/nurf"}}'
```
Or
```
kubectl patch kongingress foo --namespace="baz" -p '{"proxy": {"path": "/nurf"}}'
```
The server respond:
```
Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json
```

**What you expected to happen**:

The Path of the kongingress to be updated from `/xorf` into `/nurf`

**Comment by hbagdi** [comment]
Hi @Ngob,
Thank you for opening up this issue.
I couldn't replicate this issue on my side.

Using strategic-merge-patch with custom resources is [not yet supported](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/).
I used `kubectl edit KongIngress foo` to change the `path` property, and it was reflected in Kong as it should have.

I'll leave the issue open for a little longer for any further discussions.

**Comment by Ngob** [comment]
Hello,

Sorry for the late reply.  My issue was only about the strategic-merge-patch, sorry for the bother I did not check this doc.
Thanks for your work!
