### ISSUE TITLE
Global plugins should be possible only via KongClusterPlugins and not KongPlugins

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#681]
Two years ago when we started with the project, KongPlugin resource was introduced. Over time, various features have been added on top of it, one of them being global plugins using a label of `global: "true"`. However, this breaks the Kubernetes RBAC model because global plugins impact traffic that is flowing across all namespaces. This should be possible using KongClusterPlugin only.

**Comment by rainest** [comment]
Done per #751
