### ISSUE TITLE
Spike: figure out what to do with preservehost default value

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#689]
The current default value of `preserve_host` is set to `true`, which means, Kong doesn't alter the `host` header of the HTTP request by default.
Is this conforming to the Ingress specification or not?
The scope here is to figure out an answer to this question and note next steps that are needed.

**Comment by mflendrich** [comment]
food for thought: Should this affect HTTP/2 `:authority` as well?

**Comment by hbagdi** [comment]
The current default (as of 0.9.1) value of `preserve_host` in Kong is set to `true`.

While the Ingress specification doesn't explicitly call out `Host` header (and by extension `:authority`) behavior, the community at large has agreed upon ingress controllers being transparent reverse proxies, meaning, requests from client should be forwarded to the upstream as is.

We will continue with the default value of `preserve_host` as `true` for the foreseeable future until the community brings this discussion up again.
