### ISSUE TITLE
feature: use port mapping feature of Kong

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#691]
Kong is introducing port mapping feature that will be very useful in Kong deployments on Kubernetes.
Scope:
- use this feature by default in example manifests and in Helm chart (create an issue in `kong/charts` repo if needed)
- document when to use this feature

**Comment by mflendrich** [comment]
> Kong is introducing port mapping feature

refers to Kong/kong#5861 - appears supported in Kong `2.1.0-beta.1` but not `2.1.0-alpha.1`

**Comment by mflendrich** [comment]
Added the `breaking-change` label because #753 changes `X-Forwarded-Port` in proxied requests.

**Comment by hbagdi** [comment]
It changes the port because it is a bug and hence I don't think this is a breaking change.

**Comment by mflendrich** [comment]
Closing this issue as done (the `deploy/` manifests define KONG_PORT_MAPS by default now)
The Helm part will be handled separately, in Kong/charts#168.
