### ISSUE TITLE
docs: how to integrate with Istio

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#703]
Kong and Istio can play together. We have written blogs about these, but these should be included in documentation:
https://konghq.com/blog/kong-istio-setting-service-mesh-kubernetes-kiali-observability/
https://kubernetes.io/blog/2020/03/18/kong-ingress-controller-and-istio-service-mesh/

**Comment by howardjohn** [comment]
Let me know if there is anything blocking this on the Istio side

**Comment by yangvipguang** [comment]
@hbagdi   Please 。Can both kong and kong ingress be combined with istio, what's the difference between them?

**Comment by mflendrich** [comment]
Request from #777:

> Excuse me, I want to combine kong and istio. But don't know how to do it. There are some official tutorials but they are not very detailed. For example, how to replace the gateway of istio and combine it with virtualservice. The native istio virtualservice is bound by selecting the istio gateway. So can I bind to the kong ingress controller or other ways. I strongly suggest that the official can give a relatively complete case. This place is really confusing.

**Comment by yangvipguang** [comment]
@mflendrich 
 We are planning to provide a complete how-to on running Kong with Istio soon, and the work is tracked in #703.

I have added your request to that issue. Let's continue our discussion there - closing this issue as a duplicate. Please describe in #703 what exactly you are trying to achieve with Kong, and we might be able to cover that in docs.


Excuse me, as you replied above. One more question, is it not technically compatible with istio? You need to wait for the kong version to be updated, or is it technically compatible but the documentation is not perfect

**Comment by andrzej-jedrzejewski** [comment]
@hbagdi Regarding documentation. What is the version of the kong, kong-ingress-controller and istio that it should work with?

In https://kubernetes.io/blog/2020/03/18/kong-ingress-controller-and-istio-service-mesh/ there is such info
`If you would like a deeper dive into Kong Ingress Controller 0.7, please check out the GitHub repository.` but host_header for kong is avaialble from 0.9:
https://docs.konghq.com/kubernetes-ingress-controller/1.1.x/references/annotations/#konghqcomhost-header

**Comment by hbagdi** [comment]
@andrzej-jedrzejewski You don't need `host-header` annotation to work with Istio. Version compatibility is as is listed in the doc.
