### ISSUE TITLE
KIC docs: regex paths, Kong and Ingress

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#708]
Ingress v1beta1 permits only POSIX regular expressions.
Kong supports PCRE regular expressions.

Ingress v1 has removed validation of paths and can support all types of regular expressions.

Users are tripped by this behavior and we should document what is supported and what is not supported in different versions of the Ingress resource and how to use these features.

**Comment by rainest** [comment]
Post docs repo migration, this is now https://github.com/Kong/docs.konghq.com/pull/2477
