### ISSUE TITLE
<Feature Request> Add AKS(Azure kubernetes service) deployment guide

### ISSUE THREAD

**Issue by kobynet** [Kong/kubernetes-ingress-controller#71]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUES

  - Since AKS getting more traction i think it would be necessary to have a deployment guide for that as well

**Comment by hbagdi** [comment]
Hi @kobynet,

I'm personally not familiar with Azure's managed k8s but I don't see why our [deployment](https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/single/all-in-one-postgres.yaml) would not work on it.
Have you tried taking the deployment file in this repository and applying it against your cluster? If so, what problems did you encounter?

**Comment by hbagdi** [comment]
Done with #184
