### ISSUE TITLE
upgrade client-go to 0.18.x

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#713]

**Comment by mflendrich** [comment]
Blocked by knative/pkg#1280.

`v[01].18` is a breaking change for some client-go APIs (see [v1.18 release notes](https://v1-18.docs.kubernetes.io/docs/setup/release/notes/#client-go)) and `knative.dev/pkg` (a depdendency of KIC) is not compatible (does not build) with those `v[01].18` APIs at the time of writing.

There's a (probably very impractical) possibility to upgrade to `v0.18` AND remain with the old APIs:

> Generated clientsets with the previous interface have been added in new “deprecated” packages to allow incremental migration to the new APIs. The deprecated packages will be removed in the 1.21 release.

but that requires a modified version of `knative.dev/pkg` (e.g. a fork).

**Comment by mflendrich** [comment]
#813 attempts unblocking this issue by forking knative for the time being, until Knative upstream gets updated to v0.18 (which, per the issue linked above, may happen in the upcoming release).

**Comment by mflendrich** [comment]
closed by #813
