### ISSUE TITLE
The Out of Box all-in-one-postgres.yaml does not work in latest 0.9x release

### ISSUE THREAD

**Issue by prashantbhatiain** [Kong/kubernetes-ingress-controller#714]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary
The out of box all-in-one-postgres.yaml  template does not work with latest versions .It worked fine in  release kubernetes-ingress-controller-0.7.1 .The ingress controller pod is stuck in the init state and never proceeds furthur.

**Kong Ingress controller version**
0.9.0

**Kong or Kong Enterprise version**
Kong

### Kubernetes version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:40:13Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

### Environment
AWS EKS

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
The out of box template ,all-in-one-postgres.yaml  ,does not work anymore  .It gets stuck in init state.I was trying to Run Latest Version of of Kong INgress Controller with RDS ,it created all the tables in the Postgres but ingress pod never started and got stuck in init state even after 15 mins waiting i gave up,then i ran the vanilla all-in-one-postgres.yaml  and this also got stuck.

### Expected behavior
The all-in-one-postgres.yaml should work by default when applying kubectl apply -f https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml

### Steps To Reproduce

1.kubectl apply -f https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-postgres.yaml
2.[ec2-user@ip-172-19-72-47 original]$ kubectl get pods -n kong
NAME                            READY   STATUS      RESTARTS   AGE
ingress-kong-788fd8c8bb-llps7   0/2     **Init:0/1**    0          64s
kong-migrations-p22sb           0/1     Completed   0          64s
postgres-0                      1/1     Running     0          64s

3.The pod gets stuck in Init state and never procceds

**Comment by hbagdi** [comment]
This was embarrassing and apologies for the silly mistake. Please try again.
Please delete the deployments and the pvc  that was backing postgres and start over again.
Thanks!

**Comment by prashantbhatiain** [comment]
Thanks for the quick fix ,its working now :)
