### ISSUE TITLE
KongClusterPlugin should not be a required CRD

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#717]
If KongClusterPlugin CRD is not present, the cluster should still function and adapt gracefully.
This comes up often because customers don't want to install cluster-level resources and the controller currently fails if it can't find KongClusterPlugin resource in API-server.

**Comment by andrevtg** [comment]
I was going to raise an issue on this problem too.

We could have an optional argument to disable scanning for "KongClusterPlugin" or at least not failing. A very common need is to rely only on namespaced CRDs (avoiding cluster-scoped ones).

**Comment by andrevtg** [comment]
Not sure if it will work for everyone (or even me).

Commenting out line 341 in current (v0.9.0) "main.go" did the trick:

```
//informers = append(informers, kongClusterPluginInformer)
```

Releasing your own image is easy:

```sh
git checkout 0.9.0
make container
docker tag kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.9.0 your-own-image
docker push your-own-image
```

You can switch the image:tag for the ingresscontroller on Kong's helm chart.
