### ISSUE TITLE
CRD types and clientset are in internal/ dir

### ISSUE THREAD

**Issue by sergerad** [Kong/kubernetes-ingress-controller#725]
Your CRD types and clientset code is inside internal dir of the project meaning they can't be re-used by the community.

E.g. trying to build while importing your pkgs:
`use of internal package github.com/kong/kubernetes-ingress-controller/internal/client/configuration/clientset/versioned not allowed`

Would appreciate if these pkgs were moved to pkg/

Thanks

**Comment by SergeRadinovich** [comment]
Have create a PR 
https://github.com/Kong/kubernetes-ingress-controller/pull/726

**Comment by hbagdi** [comment]
This is now fixed.
