### ISSUE TITLE
How to retrieve per service data using Kong Ingress Controller?

### ISSUE THREAD

**Issue by onfla11** [Kong/kubernetes-ingress-controller#728]
Multiple services and routes are configured using Kong Ingress Controller. CRDs are created for Ingress, KongIngress and KongPlugin.

I want to retrieve all routes, plugins per service or any plugins enabled on a particular routes similar to GET apis. 
e.g. 
GET /service/{id}/routes
GET /service/{id}/plugins
GET /route/{id}/plugins

Is there any way to retrieve it from the CRDs i.e. kong ingress controller without querying kong GET apis?  Any suggestions? Thanks

**Comment by hbagdi** [comment]
I'm not sure I understand the question.
Can you not list all the routes and services from the Ingress and Service resources that you have defined?

**Comment by onfla11** [comment]
`kubectl get service -n <namespace>`
will list all the services.

`kubectl get crd ingress -n <namespace`>
will list all the routes.

However, my use case is to retrieve routes per service. Given a service name as an input. 

I aware that, service is annotated with Ingress object. One way to achieve it is, to retrieve the annotated ingress name in from service and from ingress CRD list all the routes for a given service.

Is there any other recommended way to do the same? something similar to kong admin GET apis.

**Comment by hbagdi** [comment]
You can use annotations or labels in kubernetes to do this.
Kong doesn't do anything different in this case. You could also write a bash script which lists all ingress resources and then checks if `serviceName` in ingress resource matches with the user input.

>Please let me know if there is any other forum to ask such kind of questions. Hence forth, will post my questions there. Thanks.

You can ask question here or in Kong Nation: https://discuss.konghq.com/

**Comment by onfla11** [comment]
Thanks for the clarification.
