### ISSUE TITLE
implement a flag --process-classless-ingress-v1beta1

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#732]
Once #731 is implemented, a user should be able to change the behavior of the controller to be same as that in 0.9.0, which is, it will satisfy ingress resources which do not contain a `kubernetes.io/ingress.class` annotation. 

The scope here:
- come up with a better name for the flag, if you can't, use the one in the issue title
- implement the flag (and corresponding behavior in the controller)
- the default value for the flag should be false

For background, please see the doc in #690.

**Comment by rainest** [comment]
Modified community flag toggling the old behavior off to default to this in fb3ab86. The renamed flags flips the default behavior to not ingest classless ingresses, i.e. `false`.

**Comment by rainest** [comment]
Handled in #767.
