### ISSUE TITLE
ensure KongClusterPlugin configured as global plugins have the ingress.class annotation 

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#734]
KongClusterPlugin can be configured as global plugins using the label `global: "true"`. 
KongPlugin can do the same, but that behavior is set to be removed with https://github.com/Kong/kubernetes-ingress-controller/issues/681.

Change the store abstraction to only return global plugins if they have a matching ingress.class annotation on them.
This is required to avoid multiple Kong Ingress Controllers from picking global plugins. Users wish to configure different set of global plugins for internal and external ingress controllers.

For more details on background, please see doc in #690.

**Comment by rainest** [comment]
Handled in #767.

**Comment by nihadcf** [comment]
did you find the solution to the above scenario.
