### ISSUE TITLE
feature: accept change to KongPlugin which do not have an ingress.class annotation

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#735]
### Current behavior

If a KongPlugin is created, updated or deleted, the resource handler for the corresponding informer in the code drops the events if the plugin didn't have the ingress.class annotation on it.
This leads to an undocumented assumption that KongPlugin resources should be ingress.class aware, which is unintended and hence this is a bug.

### Desired behavior

Change the informer code to make sure such events are not dropped.
KongPlugin should not be ingress class aware, except in case of a global plugin (#734).
A class annotation being present on KongPlugin resource should make no difference.

For more details on background, please see doc in #690.

**Comment by rainest** [comment]
Handled in #767 by removing ResourceEventHandler filters.
