### ISSUE TITLE
feature: make ingress.class annotation a noop for KongIngress resource

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#736]
KongIngress has no concept of ingress.class. The annotation being present or absent makes no difference.

Currently, if a KongIngress is created, updated or deleted, the resource handler for the corresponding informer in the code drops the events if the plugin didn't have the ingress.class annotation on it.
This leads to an undocumented assumption that KongIngress resources should be ingress.class aware, which is unintended and hence this is a bug.

It should be possible to use the same KongIngress resource across multiple Kong Ingress Controllers in the same cluster.

**Comment by hbagdi** [comment]
The underlying behavior is similar to #735

**Comment by rainest** [comment]
Removing ResourceEventHandlers in #767 should accomplish this, as there's no longer anything that filters Secrets by annotation; the parser (via references from other objects) now handles all Secret filtering.

**Comment by rainest** [comment]
Closing as #767 is now merged.
