### ISSUE TITLE
Configurable ingress.class semantics for KongConsumer resource

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#737]
### Problem
KongConsumers behave similar to Ingress v1beta1 currently, meaning, if you don’t configure ingress class in the controller, then you don’t need the ingress.class annotation on KongConsumer resource. If you configure ingress class as kong, the same thing applies, but if you configure the class as anything different, then you need to configure all KongConsumer with the same ingress class.

This is a problem and a feature:
- Problem because majority of users use an ingress class to differentiate kong from other ingress controllers, in this case, applying the annotation on KongConsumer resources is a pain, especially because of higher cardinality.
- When multiple deployments of the controller are deployed and the user needs control over KongConsumers mapped to specific deployment. This is where ingress class annotation is useful
### Solution
- By default ingress class annotation makes no difference on KongConsumers
- This can be changed using a boolean configuration parameter ENABLE_INGRESS_CLASS_FILTER_KONG_CONSUMER (by default false). If this is enabled, the class on KongConsumer resources must match the class defined in the controller. This should ease the easy path i.e. cases where a user doesn't install multiple kong ingress controllers in the same cluster.

This is a breaking change but:
- fewer users would be affected by this change
- the change itself is configurable, hence the impact (in theory) should not be huge

For more background, please see the doc in #690.

**Comment by rainest** [comment]
Handled in #767.
