### ISSUE TITLE
Remove ingress.class filtering for consumer credential secrets 

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#738]
#### Consumer credentials secrets
These secrets should not have any concept of ingress.class. The annotation being present or absent should make no difference because the filtering is performed on the KongConsumer level. 

Currently, when a custom ingress class annotation is used, a create/update/delete event for secret that doesn’t contain the custom ingress class annotation is ignored by the resource handler and this should be fixed.

For more background, please see the doc in #690.

**Comment by hbagdi** [comment]
This is similar to #735 #736

**Comment by rainest** [comment]
Handled in #767 by removing ResourceEventHandler filters.
