### ISSUE TITLE
require ingress.class annotation for CA certificate secrets

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#739]
Problem
The current behavior lists all secrets containing the label konghq.com/ca-cert:true and loads them as CA certificates. In case when multiple controllers are running, this will lead to ca certificates being installed in all controllers.
Users have not reported the problem because:
- This concept is relatively new
- Not a lot of users use this entity (works only in enterprise with mtls-auth plugin)
Proposal
The resource MUST contain ingress.class annotation that matches the class provider to the controller configuration.

For more background, please see the doc in #690.

**Comment by rainest** [comment]
Closed per #815
