### ISSUE TITLE
How to setup google-analytics  plugin on kubernetes ingress

### ISSUE THREAD

**Issue by ajaysourcedigital** [Kong/kubernetes-ingress-controller#743]
I was wondering if we can use google-analytics plugin (which is a 3rd party plugin" with kubernetes kong ingress.

**Comment by hbagdi** [comment]
You can use any kong plugin with Kong Ingress:
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/setting-up-custom-plugins.md

**Comment by ajaysourcedigital** [comment]
Thanks.
