### ISSUE TITLE
`wait-for-migrations` stuck because of kong version mismatch

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#755]
### Summary

`all-in-one-postgres.yaml` gets stuck on the `wait-for-migrations` InitContainer never finishing

**Kong Ingress controller version**

b93477399642dad6e7ee0cbfc9c8a2fab6965c53 (`HEAD` of `next` at the moment of writing)

**Kong or Kong Enterprise version**

`proxy` and `migrations` running at `2.0`
`wait-for-migrations` running at `1.3`

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-1+6f17be3f1fd54a", GitCommit:"6f17be3f1fd54a88681869d1cf8bedd5a2174504", GitTreeState:"clean", BuildDate:"2020-06-23T21:17:52Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: microk8s
- **OS** (e.g. from /etc/os-release): Linux Mint 20
- **Kernel** (e.g. `uname -a`): `5.4.0-26-generic #30-Ubuntu SMP`
- **Install tools**:
- **Others**:

### What happened

```
git checkout b93477399642dad6e7ee0cbfc9c8a2fab6965c53
kubectl apply -f deploy/all-in-one-postgres.yaml
# (the migration job succeeded)
# (the wait-for-migrations InitContainer never exited)

kubectl logs -n kong -l app=ingress-kong -c wait-for-migrations
            hmac-auth: 001_14_to_15
               oauth2: 001_14_to_15, 002_15_to_10
                  jwt: 001_14_to_15
           basic-auth: 001_14_to_15
             key-auth: 001_14_to_15
        rate-limiting: 001_14_to_15, 002_15_to_10
                  acl: 001_14_to_15
response-ratelimiting: 001_14_to_15, 002_15_to_10

Run 'kong migrations up' to proceed
```

### Expected behavior
InitContainer `wait-for-migrations` of `ingress-kong` succeeding

### Steps To Reproduce

see _What Happened_

**Comment by mflendrich** [comment]
Updating `wait-for-migrations` to `kong:2.0` makes the symptom (of InitContainer being stuck) go away.

**Comment by mflendrich** [comment]
Duplicate of #714.

**Comment by hbagdi** [comment]
This is now fixed.
