### ISSUE TITLE
Kong Enterprise documented Helm 3 install command fails 

### ISSUE THREAD

**Issue by kazvictor** [Kong/kubernetes-ingress-controller#758]
### Summary

helm 3 command for installing kong enterprise ingress controller is incorrect: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/k4k8s-enterprise.md#helm

> $ helm install kong/kong --generate-name
>     --name demo --namespace kong \
>     --values https://l.yolo42.com/k4k8s-enterprise-helm-values \
>      --set ingressController.installCRDs=false

The `--name demo` parameter is invalid, can likely be removed.

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:18:29Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- Docker for Mac
- macOS
- **Kernel** (e.g. `uname -a`): Darwin Victors-MBP.localdomain 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### What happened
Helm 3 install command fails with:
`Error: unknown flag: --name`

### Expected behavior
Should succeed.

### Steps To Reproduce

1. Run Helm3 install command from docs after setting up the prerequisites: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/deployment/k4k8s-enterprise.md#helm

**Comment by hbagdi** [comment]
Ah yes, can you send a PR to fix this?
Apologies for the inconvenience.

**Comment by hbagdi** [comment]
This should be fixed now.
