### ISSUE TITLE
Upgrade ValidationWebhookConfiguration manifests to v1

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#763]
Context: https://github.com/Kong/kubernetes-ingress-controller/pull/759#discussion_r451115770

`ValidationWebhookConfiguration`s in this repo can be upgraded from `admissionregistration.k8s.io/v1beta1` to `v1` as long as we drop support for k8s `<1.16`

**Comment by mflendrich** [comment]
Similar to #801.

**Comment by shaneutt** [comment]
Resolved, we now use v1 https://github.com/Kong/kubernetes-ingress-controller/blob/main/hack/deploy-admission-controller.sh#L18
