### ISSUE TITLE
Enable service-upstream for an entire ingress class

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#774]
Currently, users can use `ingress.kubernetes.io/service-upstream: true` to disable load-balancing and health-checks feature in Kong and send traffic directly to kube-proxy which routes traffic to the right destination. This results in an additional network hop but can be useful in some scenarios.
One place this is especially useful is integrating with Service Mesh solutions like Kuma or Istio, where the envoy sidecar takes up upstream traffic from kong and routes it based on the world-view of mesh. 

The feature request here is to add a cli configuration to enable this behavior globally for all services in kong ingress controller. This makes it easy to use this feature as users don't have to add the annotation on each and every kubernetes service.

**Comment by mflendrich** [comment]
Maybe the `IngressClass` resource would be a better place?

I think that KIC flags are a good place for runtime configuration, semantics should be handled by the declarative configuration. What do you think?

**Comment by mflendrich** [comment]
#1131 is a possible attempt at solving this problem.

**Comment by RobSerafini** [comment]
Stale. Update if you have continued interest in this feature. #1586 was closed some time ago.
