### ISSUE TITLE
Multiple ingress controllers in different namespaces

### ISSUE THREAD

**Issue by okanozdemir** [Kong/kubernetes-ingress-controller#775]
### Summary

I couldn't create the second Kong deployment in the second namespace with [all-in-one-postgres.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/single/all-in-one-postgres.yaml) I changed the namespace entries in the yaml file but Kong still looking the "kong" namespace. The error is in the below:

```
-------------------------------------------------------------------------------
Kong Ingress controller
  Release:    0.9.1
  Build:      2caa524
  Repository: git@github.com:kong/kubernetes-ingress-controller.git
  Go:         go1.14.1
-------------------------------------------------------------------------------

W0717 14:06:22.230530       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0717 14:06:22.230914       1 main.go:492] Creating API client for https://10.82.0.1:443
I0717 14:06:22.242083       1 main.go:536] Running in Kubernetes Cluster version v1.16+ (v1.16.9-gke.6) - git (clean) commit 14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe - platform linux/amd64
F0717 14:06:22.244210       1 main.go:133] unexpected error getting information about service kong/kong-proxy: services "kong-proxy" is forbidden: User "system:serviceaccount:kong-test:kong-serviceaccount" cannot get resource "services" in API group "" in the namespace "kong"

```

**Kong Ingress controller version**
0.9.1

**Kong or Kong Enterprise version**
2.0

### Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-gke.6", GitCommit:"14bc8ad5f8c245f1240a8e4eab128c4d51bfeffe", GitTreeState:"clean", BuildDate:"2020-05-30T02:07:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Environment

- **Cloud provider or hardware configuration**: Google Kubernetes Engine

### What happened
Couldn't create the second kong deployment with [all-in-one-postgres.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/single/all-in-one-postgres.yaml)

### Expected behavior
I should be able to create new deployments with other namespaces.

### Steps To Reproduce

1. Download the [all-in-one-postgres.yaml](https://github.com/Kong/kubernetes-ingress-controller/blob/master/deploy/single/all-in-one-postgres.yaml)
2. `kubectl create -f all-in-one-postgres.yaml`
3. Change the namespace entries, for example "kong-test"
4. `kubectl create -f all-in-one-prosgres-EDITED.yaml`
5. check the kong error with `kubectl logs -f ingress-kong-****** -n kong-test -c ingress-controller`

### YAML Files
[all-in-one-postgres.yaml.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4938311/all-in-one-postgres.yaml.txt)
[all-in-one-postgres-EDITED.yaml.txt](https://github.com/Kong/kubernetes-ingress-controller/files/4938309/all-in-one-postgres-EDITED.yaml.txt)

**Comment by mflendrich** [comment]
In `all-in-one-postgres-EDITED.yaml.txt`, the `kong-proxy` service moved from namespace `kong` to `kong-test`, but the `CONTROLLER_PUBLISH_SERVICE` in that file is still `kong/kong-proxy`. Try changing it to `kong-test/kong-proxy`.

**Comment by rainest** [comment]
Going ahead and closing this based on inactivity and the reaction to Michal's response. @okanozdemir if you're still seeing issues, please reopen to let us know.
