### ISSUE TITLE
istio  and  kong 

### ISSUE THREAD

**Issue by yangvipguang** [Kong/kubernetes-ingress-controller#777]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

SUMMARY_GOES_HERE

**Kong Ingress controller version**
0.9.1

**Kong or Kong Enterprise version**
kong

### Kubernetes version

**paste `kubectl version` output**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"4f7ea78", GitTreeState:"", BuildDate:"2020-05-08T07:29:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

### What happened
**Excuse me, I want to combine kong and istio. But don't know how to do it. There are some official tutorials but they are not very detailed. For example, how to replace the gateway of istio and combine it with virtualservice. The native istio virtualservice is bound by selecting the istio gateway. So can I bind to the kong ingress controller or other ways. I strongly suggest that the official can give a relatively complete case. This place is really confusing.**

**Comment by mflendrich** [comment]
We are planning to provide a complete how-to on running Kong with Istio soon, and the work is tracked in #703. 

I have added your request to that issue. Let's continue our discussion there - closing this issue as a duplicate. Please describe in #703 what exactly you are trying to achieve with Kong, and we might be able to cover that in docs.
