### ISSUE TITLE
ingress v1: parse ingress class field in Ingress v1 resource

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#790]
Ingress v1beta1 resource are fitlered based on the kubernetes.io/ingress.class annotations. `Class` field is introduced in ingress v1 which should replace the annotation.
The scope here is to parse this field.
The priority here is not intuitive so please take that into account:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md#interoperability-with-previous-annotation

For #590

**Comment by mflendrich** [comment]
Specifically, resolve this TODO:

https://github.com/Kong/kubernetes-ingress-controller/blob/04a371a22856c550e5bde2e7536baac22a77f72f/internal/ingress/store/store.go#L177
