### ISSUE TITLE
JWT plugin cannot be assigned to an Ingress object

### ISSUE THREAD

**Issue by paquzach** [Kong/kubernetes-ingress-controller#795]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary
Error in kong ingress controller while assigning a JWT plugin to a route. Error shown says "expecting a set"

**Kong Ingress controller version 0.9.1**

**Kong or Kong Enterprise version 2.1.0**

### Kubernetes version

**Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
**

### Environment

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): Linux 4.4.188-1.el7.elrepo.x86_64
- **Install tools**: Helm 3
- **Others**:

### What happened
We have been experimenting with Kong in dbless mode on our kubernetes environment. 
We got to the point of setting up some custom plugins on routes using the KongPlugin kubernetes custom resource type (these plugins work). 
We created a KongPlugin JWT and associated it to an ingress rule using the annotation tag.
The plugin doesn't get assigned to the route because it is expecting a set, instead it blocks the ingress controller queue and routes are unusable. 

### Expected behavior
Plugin should be assigned to the route

### Steps To Reproduce
We are having an issue creating a JWT plugin passing it the following config:
>     apiVersion: configuration.konghq.com/v1
>     kind: KongPlugin
>     metadata:
>       name: kong-jwt
>       namespace: ingress
>     config:
>       claims_to_verify:
>         exp: null
>         nbf: null
>       key_claim_name: realm
>     plugin: jwt

Creating the plugin seems to work, we don't see any error logs in the ingress controller
The issue comes up when we create an Ingress object that uses the plugin:
>     apiVersion: extensions/v1beta1
>     kind: Ingress
>     metadata:
>       name: kong-foo-route
>       namespace: ingress
>       annotations:
>         kubernetes.io/ingress.class: "kong"
>         konghq.com/plugins: kong-jwt,kong-rate-limiting
>     spec:
>       rules:
>       - http:
>           paths:
>           - path: /foo
>             backend:
>               serviceName: aService
>               servicePort: 8080
After applying these rules to kubernetes, we get the following log in the Ingress controller
>     E0807 18:58:05.115303       1 controller.go:128] unexpected failure updating Kong configuration:
>     posting new config to /config: 400 Bad Request {"fields":{"plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,{"config":{"claims_to_verify":"expected a set"}},{"config":{"claims_to_verify":"expected a set"}}]},"name":"invalid declarative configuration","code":14,"message":"declarative config is invalid: {plugins={[14]={config={claims_to_verify=\"expected a set\"}},[15]={config={claims_to_verify=\"expected a set\"}}}}"}
>     W0807 18:58:05.115389       1 queue.go:112] requeuing kong/aRoute, err posting new config to /config: 400 Bad Request {"fields":{"plugins":[null,null,null,null,null,null,null,null,null,null,null,null,null,{"config":{"claims_to_verify":"expected a set"}},{"config":{"claims_to_verify":"expected a set"}}]},"name":"invalid declarative configuration","code":14,"message":"declarative config is invalid: {plugins={[14]={config={claims_to_verify=\"expected a set\"}},[15]={config={claims_to_verify=\"expected a set\"}}}}"}
Seems like we are writing a set, but we are still getting that error. Is this a bug, or do I have an incorrect way of writing a set?

**Comment by hbagdi** [comment]
You are providing wrong input.
Please do:
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-jwt
  namespace: ingress
config:
  claims_to_verify:
  - exp
  - nbf
  key_claim_name: realm
plugin: jwt
```

As per the [documentation](https://docs.konghq.com/hub/kong-inc/jwt/), `claims_to_verify` must be an array.

**Comment by paquzach** [comment]
@hbagdi That worked. Thank you, not getting the error anymore.
