### ISSUE TITLE
Default backend handling potentially results in unwanted configuration

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#821]
# Overview

Ingress resources allow specifying a default backend, which is used for any Ingress rules that do not have their own backend specified. For complicated historical reasons related to differences in controller implementations, this default backend is _also_ used to create a catch-all route. That catch-all route may be undesirable.

# Example

This Ingress specifies a default backend (`httpbonbon`) and two rules, one for `/default` with no backend and one for `/specific` with a backend:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    konghq.com/plugins: request-id
  name: example
spec:
  backend:
    serviceName: httpbonbon
    servicePort: 80
  rules:
  - http:
      paths:
        path: /default
  - http:
      paths:
      - backend:
          serviceName: somethingElse
          servicePort: 80
        path: /specific
```
In addition to routes for `/default` and `/specific`, this configuration creates a third Kong route (some fields omitted for brevity):

```
{
  "paths": [
    "/"
  ],
  "created_at": 1598979384,
  "snis": null,
  "service": "default.httpbonbon.80",
  "name": "default.example",
  "tags": [
    "managed-by-ingress-controller"
  ]
}
```
This route matches any request that does not match a more specific route, effectively avoiding Kong's default 404 behavior and directing those "unmatched" requests to httpbonbon.

# Potential issues

It may not be immediately obvious that the Ingress above results in this route from the Ingress alone: users may reasonably assume that the default backend, as part of the Ingress object, is scoped to that Ingress object and applies only to the rules in it. This is not the case, but this behavior is not unfamiliar to all users: many are aware of this behavior from non-Kong controller implementations and do expect it, and removing it would present a migration challenge and/or result in confusion because it violates de facto standards.

## Accidental service exposure

The catch-all route may inadvertently expose the default backend service through locations not intended or desired by the user. 

For example, consider a controller that processes two Ingress resources:
- Ingress A has a default backend and rules that use a non-public (i.e. only resolvable by internal nameservers) hostname.
- Ingress B has a second which has rules that use a public hostname and specific paths.

The catch-all route will expose the first rule's service on the public hostname for any path that does not match the second Ingress's rules.

## Accidental denial of service

The catch-all route may allow misbehaving clients to accidentally perform a DoS attack on the default backend service. Consider a scenario where a botched client update introduces a typo in one of the clients' high-traffic request paths, and the typo request does not match any other route. That high-volume traffic will then be directed to the default backend service, which may not be able to deal with the load effectively, resulting in a loss of service.

# Mitigation

This risk is difficult to effectively mitigate in the current implementation without avoiding default backends in Ingress resources altogether (i.e. you only use rules that specify their backend). While users can define multiple Ingress resources with default backends, the controller will only create a single catch-all route. However, the choice of Ingress to source this route from is essentially arbitrary (it retrieves the oldest Ingress, and relying on creation time does not allow users an easy means of ensuring that a specific Ingress will create the catch-all route).

**Comment by rainest** [comment]
Expected controller behavior here is a bit at odds with Kong's normal mode of operation. Many controllers explicitly provide a dedicated default backend service, whereas Kong normally handles this without any specific service: any request that not matching a route will receive a 404 from Kong by default.

For possible future development, I'd recommend either offering a means to disable this behavior altogether (such that users can use Ingress-scoped default backends while still using Kong's standard 404 behavior) or a means to configure the catch-all route's service that does not rely on creation time. Although I'm not familiar with the entire history here, the current Ingress documentation suggests that the latter _is_ the intended way to handle this:

https://kubernetes.io/docs/concepts/services-networking/ingress/#default-backend

> An Ingress with no rules sends all traffic to a single default backend. The defaultBackend is conventionally a configuration option of the Ingress controller and is not specified in your Ingress resources.

**Comment by mflendrich** [comment]
won't fix due to low severity and usefulness of the default backend
