### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by just1689** [Kong/kubernetes-ingress-controller#825]
Greetings

Love the work on Kong + K8s. Interesting stuff.

I'm sure you know once you hit v1 many will be able to consider the controller in the enterprise. May I ask if there is a roadmap to v1 for the Kong Ingress Controller?

**Comment by hbagdi** [comment]
We are tracking this under the 1.0.0 milestone.
We are targeting to release a 1.0 in about a month from now.

**Comment by just1689** [comment]
Fantastic stuff, thanks!
