### ISSUE TITLE
statusSync: concurrent unsynchronized sorts of `newIngressPoint`

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#829]
There is a data race in `statusSync.updateStatus` involving `newIngressPoint []apiv1.LoadBalancerIngress`.

in `status.go`: https://github.com/Kong/kubernetes-ingress-controller/blob/82b23323c590a176e490d2b5e26a3ecb1cd54262/internal/ingress/status/status.go#L326

every operation queued in `batch` performs a `sort.SliceStable(status, lessLoadBalancerIngress(status))` on the same slice (`newIngressPoint []apiv1.LoadBalancerIngress`) concurrently. The sorts are not synchronized in any way. This means that there is a data race between all the operations in `batch`. There are as many as the total # of ingress resources managed by KIC.

Proposed solution:
* sort `newIngressPoint` only once, synchronously, in `updateStatus()`, before the asynchronous `batch` is even created. 
* leave `newIngressPoint` unchanged and perform the sort on a fresh copy of the slice (to mitigate modifying an input argument which is undesirable)

**Comment by shaneutt** [comment]
This is fixed in `v2` coincidentally: The mechanism for status updates has completely changed with `v2`.
