### ISSUE TITLE
tech debt: store.ListX() use cache.ListAll() inconsistently

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#831]
Today, some of the store.ListXXX() functions use `cache.ListAll()` and some do not (and thus implement iterating over cache.Store and filtering manually). This is a code smell.

The scope of this issue is to make store.ListXXX() implementations consistent by unifying the way they loop over the List().

**Comment by shaneutt** [comment]
Stale. Let's re-open if we end up having more cause to prioritize this.
