### ISSUE TITLE
Code coverage on CI

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#835]
As a PR author/reviewer
I want to be able to view Go code coverage for all tests in a PR (equivalent to `go test -coverprofile=coverage.out ./... && go tool cover -html=coverage.out`)
So that I know which parts of the code are missing tests

If a line is shown as covered, it doesn't give useful information as to whether the logic beneath is properly tested.
However, if a line is shown as not covered, then it's certainly not properly tested.

**Comment by mflendrich** [comment]
Possible starting point for getting coverage (excluding autogenerated packages):

```bash
go test -v -coverpkg=./cli/...,./internal/... -coverprofile=coverage.out ./...
go tool cover -func=coverage.out
```

**Comment by shaneutt** [comment]
It would appear that someone has already set up [codecov](https://codecov.io) integrations for the repository:

https://codecov.io/gh/Kong/kubernetes-ingress-controller

Some coverage is already calculated there from much older builds.

Codecov appears to be a good starting point as it is:

* "certified" in the github marketplace
* easy to integrate from Github Actions
* free and unlimited for open source repos
* provides code coverage view in PR "files" tab
* we already have a previous integration to build off of

Is anyone particularly opposed to me re-enabling the existing codecov.io integration, or have any other thoughts on implementation?
