### ISSUE TITLE
kong labs incompatible with KIC >=0.10 and k8s >= 1.16

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#855]
At the moment of writing, some [Kong labs for Kubernetes](https://www.konglabs.io/kubernetes/) (those where I had edit access - that is, _Kong for Kubernetes_, _Use KongPlugin Resource_ and _Kong For Kubernetes - All_) are pinned to KIC 0.9.1 because as of #767 (KIC 0.10) KIC requires an ingress class annotation on certain resource kinds (including `Ingress`).

Also, some code labs (at least https://www.konglabs.io/configuring-a-fallback-service/ and https://www.konglabs.io/kong-for-kubernetes/ ) don't work on k8s >= 1.16 because they include a Deployment (`https://bit.ly/fallback-svc`) in an unsupported old apiversion (extensions/v1beta1)

We need to make the following fixes in the kong labs to bring them up to date:
- change the KIC deployment URL so that it points to `main` and not to the `0.9.1` tag
- update ingress manifests apiversion (today they're at `extensions/v1beta1` which is deprecated)
- add the `kong` ingress class on all resources that need it
- update `Deployment` manifests referenced by labs away from `extensions/v1beta1` which is not supported by recent k8s versions

**Comment by mflendrich** [comment]
Also, the global `KongPlugin` with `global: true` needs to be replaced with a `KongClusterPlugin`

**Comment by shaneutt** [comment]
@mflendrich where do you figure we're at with this one, given recent updates for `v2`?

**Comment by mflendrich** [comment]
> where do you figure we're at with this one, given recent updates for v2?

It's definitely even more broken than it was for 0.x/1.x.

@scseanchow could you please help us make an informed decision about the usage of this guide? Should we bring it up to date or discontinue?
