### ISSUE TITLE
several kong labs broken by KIC 0.10

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#856]
Because of #855, some Kong code labs for Kubernetes are broken because they instruct the reader to install KIC from main (that is 0.10 at the moment of writing) which expects the new ingress class semantics, but the manifests created over the course of the labs don't specify the ingress class explicitly.

I pinned KIC to 0.9.1 in those labs where I had access (_Kong for Kubernetes_, _Use KongPlugin Resource_ and _Kong For Kubernetes - All_), but the remaining ones are broken because they use 0.10.

This issue is a short-term fix for the incompatibility. The scope of this issue is to unbreak (by pinning to 0.9.1) the labs not enlisted above (as pinned) which broken at the moment of writing (KIC does not notice the ingresses).

The long-term fix would be to make the labs compatible with KIC beyond 0.9.1. This scenario is covered by #855.

**Comment by mflendrich** [comment]
- Ingress Class handling was a breaking change that needs to be reflected in labs
- labs use outdated API versions of resources
- currently labs are pinned to KIC 0.9
- TBD: version of kubernetes - we should probably use 1.19, and therefore use ingress v1

**Comment by shaneutt** [comment]
@mflendrich where do you figure we're at with this one, given recent updates for v2?

**Comment by mflendrich** [comment]
> where do you figure we're at with this one

Beyond doubt, these kong labs are even more broken than they were back then.

Closing in favor of #855.
