### ISSUE TITLE
Sync changes to basic-auth passwords in DB-mode

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#865]
53124f1 introduced the support for changing basic-auth passwords and syncing them as needed. With #823, we removed the associated code but it needs to be added back in.
The code was removed because the code didn't do what it was suppose to. The code only made updates to Kong for KongCredential resource, which are not used widely anymore. The code should be changed to do the same for  Secret-based credentials and added back in.

Please see this comment for more context:
https://github.com/Kong/kubernetes-ingress-controller/pull/862/commits/82c211bd5caabc23f9761f9cc2797278c61cdbe3#r492376403

**Comment by mflendrich** [comment]
Let's verify if this is still a problem today.

**Comment by shaneutt** [comment]
Because this one is difficult to assess from the original posting I think we should talk about it. I'm going to try and shepherd this one forward a bit and will bring it up at our next planning meeting.

**Comment by mflendrich** [comment]
Secret-based credential management works now, this is outdated. Therefore closing.
