### ISSUE TITLE
Add hack tooling to ensure local manifest generation matches CI check

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#867]
### Summary

Local hack tooling for generating manifests should not rely on the local kustomize tooling. It should always match the kustomize version used by CI, using Docker or similar.

### Background

See https://github.com/Kong/kubernetes-ingress-controller/pull/833#issuecomment-692964369

As-is, new kustomize versions can introduce minor changes in the single manifests built from base manifests. Generating single manifests using a newer or older kustomize version than the [version used by CI](https://github.com/Kong/kubernetes-ingress-controller/blob/0.10.0/.github/workflows/test.yaml#L33) may result in a failed CI check, requiring the PR submitter also update the CI check version. This is usually fine, but could result in difficulty for other contributors, whose OS/package manager may not have that specific kustomize version available.

To avoid this issue, we can add a Docker image with a static kustomize version identical to the CI job's kustomize version.

**Comment by mflendrich** [comment]
Appears done per a856c441
