### ISSUE TITLE
Dynamic switching database

### ISSUE THREAD

**Issue by dayongi** [Kong/kubernetes-ingress-controller#870]
Because not all companies are using Postgree in a real application scenario; Ask if there are plans to support switching between commonly used relational databases, such as MySQL.

**Comment by hbagdi** [comment]
Have you considered using the DB-less mode of Kong which doesn't require a database at all?

**Comment by dayongi** [comment]
Using the DB-less can't use the konga and some plugins.  I want to know if db-less is used, how does Kong ensure that the previous data will not be lost when expanding pod or node horizontally.

**Comment by hbagdi** [comment]
>how does Kong ensure that the previous data will not be lost when expanding pod or node horizontally

The data is stored in k8s datastore etcd and it is pushed into kong whenever new pods are spawned up.

> Using the DB-less can't use the konga and some plugins

The only plugin you cannot use is `oauth2`. If that is okay with you, I'd highly recommend using DB-less mode.

**Comment by rainest** [comment]
This is more a question for the proxy team than us. The question of MySQL (or other alternative ACID databases) has been raised there before, and as far as I know the decision in https://github.com/Kong/kong/issues/1867 remains unchanged/there are no plans to add official support for new databases at this time.

There are several community forks that add MySQL support, and Nokia may well continue updating theirs to support Kong 2.x and onward--I can't speak for them, but they may be able to provide you with more information if you ask in https://github.com/Kong/kong/issues/6332. Their fork is based off 1.1, which at least means they're on [the new DAO/database abstraction layer](https://github.com/Kong/kong/blob/master/CHANGELOG.md#core-36), so while bringing it up to 2.x (or a newer 1.x release) would still require significant work, it's less work than would be necessary to upgrade a 0.x (old DAO)-based fork.

On the controller end, we [effectively only distinguish between DB-less and DB-backed mode](https://github.com/Kong/kubernetes-ingress-controller/blob/0.10.0/cli/ingress-controller/main.go#L278-L287): if we see any value other than `database: off`, we use DB-backed admin API operations, which are database-agnostic. While we can't guarantee there wouldn't be unexpected issues using a third-party fork with MySQL support, the controller will at least attempt to do so, and should succeed. However, as [controller versions newer than 0.7 do not support Kong version 1.1](https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/references/version-compatibility.md), you'd need to use an older controller version pending updates to the community forks.

I'll echo Harry's suggestion to use DB-less mode instead. Konga and similar generally aren't needed when using the controller, as the controller provides similar functionality (albeit with Kubernetes manifests taking the place of a flat file configuration). We support [custom entities as of 0.9](https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/guides/configuring-custom-entities.md), which was one of the main limiting factors for using custom plugins with the controller and DB-less mode. The remaining incompatible plugins are those that require non-entity database interactions, e.g. oauth2 uses the database to manage tokens. Plugins that require that functionality typically support it via other databases, e.g. rate-limiting needs somewhere to keep track of request counts, but supports Redis for that--oauth2 is more the odd one out for not supporting anything other than the primary database, as recommended best practice is to avoid using the primary database for those types of transactions for performance reasons.

**Comment by dayongi** [comment]
ok, thanks for your answer, i get it
