### ISSUE TITLE
How to configure tls certificate

### ISSUE THREAD

**Issue by eamonnmcevoy** [Kong/kubernetes-ingress-controller#88]
**Is this a request for help?**: Yes

**What keywords did you search in Kong Ingress controller issues before filing this one?** (If you have found any duplicates, you should instead reply there.): tls, https, sni, certificate

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kong Ingress controller version**: 0.0.5
**Kong version**: 0.14.0

**Kubernetes version** (use `kubectl version`):

**Environment**: macos

- **Cloud provider or hardware configuration**: AKS
- **OS** (e.g. from /etc/os-release):  macos
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
I'm trying to configure https for my kong ingress service (dev environment).

I have a number of ingresses configured with tls.

generate certificate: 
`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=*.my.host/O=my.host"`

e.g.
example ingress
```
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: my-ingress
  namespace: my-namespace
proxy:
  path: /
route:
  protocols:
  - https
  strip_path: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  namespace: my-namespace
spec:
  tls:
  - hosts:
    - "*.my.host"
    secretName: tls-secret
  rules:  
    - host: "*.my.host"
      http:
        paths:
          - path: /                  #different path per ingress
            backend:
              serviceName: my-service
              servicePort: 80
```

ingress controller logs
I see many errors like this:
```
I0813 21:19:27.459918       5 kong.go:1014] creating Kong SSL Certificate for host *.my.host located in Secret my-namespace/tls-secret
E0813 21:19:27.470002       5 kong.go:1019] Unexpected error creating Kong Certificate: [400] {"fields":{"snis":"*.my.host already associated with existing certificate 'dd6686d9-9602-4194-90fb-b678ed4bb502'"},"name":"schema violation","code":2,"message":"schema violation (snis: *.my.host already associated with existing certificate 'dd6686d9-9602-4194-90fb-b678ed4bb502')"}
E0813 21:19:27.470023       5 controller.go:130] unexpected failure updating Kong configuration:
the server rejected our request for an unknown reason (post certificates.meta.k8s.io)
W0813 21:19:27.470034       5 queue.go:113] requeuing my-namespace/my-host-request-transformer, err the server rejected our request for an unknown reason (post certificates.meta.k8s.io)
I0813 21:19:30.790756       5 controller.go:127] syncing Ingress configuration...
I0813 21:19:30.793087       5 kong.go:1014] creating Kong SSL Certificate for host *.my.host located in Secret my-namespace/tls-secret
E0813 21:19:30.794675       5 kong.go:1019] Unexpected error creating Kong Certificate: [400] {"fields":{"snis":"*.my.host already associated with existing certificate 'dd6686d9-9602-4194-90fb-b678ed4bb502'"},"name":"schema violation","code":2,"message":"schema violation (snis: *.my.host already associated with existing certificate 'dd6686d9-9602-4194-90fb-b678ed4bb502')"}
E0813 21:19:30.794713       5 controller.go:130] unexpected failure updating Kong configuration:
the server rejected our request for an unknown reason (post certificates.meta.k8s.io)
W0813 21:19:30.794724       5 queue.go:113] requeuing my-namespace/my-host-ingress, err the server rejected our request for an unknown reason (post certificates.meta.k8s.io)
I0813 21:19:34.125269       5 controller.go:127] syncing Ingress configuration...
```
Without the tls configuration I can run my app over http, but the tls section breaks it. Not sure what I'm doing wrong.

EDIT:

I found another message in the logs
```
I0814 07:48:58.875411       5 controller.go:127] syncing Ingress configuration...
I0814 07:48:58.880426       5 kong.go:1014] creating Kong SSL Certificate for host *.my.host located in Secret my-namespace/tls-secret
I0814 07:48:58.961495       5 kong.go:1028] creating Kong SNI for host *.my.host and certificate id c89fe694-b38b-42df-8687-22f4d36857f7
E0814 07:48:58.963907       5 kong.go:1032] Unexpected error creating Kong SNI: [400] {"fields":{"ssl_certificate_id":"unknown field","certificate":"required field missing"},"name":"schema violation","code":2,"message":"2 schema violations (certificate: required field missing; ssl_certificate_id: unknown field)"}
E0814 07:48:58.963996       5 controller.go:130] unexpected failure updating Kong configuration:
the server rejected our request for an unknown reason (post snis.meta.k8s.io)
```
I believe this is the same issue as: https://github.com/Kong/kong/issues/3610

The ingress controller needs updates to work with `kong:0.14.0`

**What you expected to happen**:
app to be served over https

**How to reproduce it** (as minimally and precisely as possible):
as above

**Anything else we need to know**:

**Comment by hbagdi** [comment]
Hello @eamonnmcevoy 
Thank you for opening this issue. The ingress controller currently doesn't work with Kong CE 0.14.0.
Please use the supported Kong CE 0.13.x version.

**Comment by hbagdi** [comment]
@chlung 

> Will this issue be resolved with Kong 0.14.1 and Kong-Ingress 0.2?

Yes.

**Comment by chlung** [comment]
@hbagdi 

After I clean up all reference app and ingress for my TLS secret, the /certificates still not clean.  Is there a delay for certificates deletion?

Thanks.

**Comment by hbagdi** [comment]
It is possible that the certificate won't get deleted. It'll get updated or removed if there is a conflict but won't get deleted. This is a known *harmless* issue and we will be fixing it in future.

**Comment by chlung** [comment]
@hbagdi  thanks.
