### ISSUE TITLE
delete the flags reference from docs and point to flag defs directly instead

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#880]
[`cli-arguments.md`](https://github.com/Kong/kubernetes-ingress-controller/blob/a4bd485704b7808c69b047ee14076ab0f50e4887/docs/references/cli-arguments.md#flags) is a verbatim copy of `pflag` flag definitions present in the code. `pflag` takes care of pretty-printing an equivalent of the flags table in `cli-arguments.md`.

The scope of this issue is to de-duplicate the flag reference, and point users to either `--help`, or flag definitions in the code.

**Comment by rainest** [comment]
I propose we drop this and continue maintaining the document. Users don't typically have a standalone controller binary and changing the container args to `--help` and checking logs or execing the container locally is a bit clunky and unintuitive. We shouldn't expect users to review code, even if it's relatively straightforward--it's out of line with how users typically interact with the controller and doesn't align with how we document the rest of it.
