### ISSUE TITLE
Strip out global KongPlugin handler

### ISSUE THREAD

**Issue by hbagdi** [Kong/kubernetes-ingress-controller#882]
We currently keep the store ListGlobalKongPlugins and parser logic sort of in place, but only to warn users not to use them.

From @rainest:
Removing this is sort of an open question. The warning kinda serves a dual purpose, both warning users about old KongPlugins they haven't converted into KongClusterPlugins and warning users if they create a new one. While the latter case (legacy config) should disappear over time, trying to make a KongPlugin global is possibly an easy mistake, and removing the warning/List function would silently ignore that bad configuration, which could result in user confusion.

**Comment by shaneutt** [comment]
Closing as stale. If anyone feels there's follow up needed for this one please drop and comment and let's re-assess/re-open.
