### ISSUE TITLE
route has host=null this not routing request to upstream , plugin applied to ingress not executing 

### ISSUE THREAD

**Issue by jshahv** [Kong/kubernetes-ingress-controller#895]
"hosts":null,"preserve_host":true,

we have above configured in kong through kubernetes ingress as not having -host 

somehow with this config request are not reaching to upstream or its reaching but not passing headers like host , our ingress has plugins and thats also not applied to route.

Basically , we want kong to response with any host to allow kong accessible from local dev machine of front end developers

as per kuberntes and kong both , this should work

Is it possible that  host header , x-fowarded-host headers are not passing and causing problem ?

**Comment by hbagdi** [comment]
Could you share the Ingress and plugin resource manifests?

Also, could you please elaborate on what behavior you see currently? Do you get a 404 from Kong or do the upstream services get requests but without the right metadata?

**Comment by jshahv** [comment]
Thank you very much for quick reply.  I thought that with host:null kong will serve request from any host but somehow thats not happening
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: <name>
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: kong-request-logging
    ingress.kubernetes.io/content-security-policy: "default-src 'self';script-src 'self' 'unsafe-inline';connect-src 'self';img-src 'self' data: blob:;style-src 'self' 'unsafe-inline';media-src 'self' blob: data:;font-src 'self' data:;frame-ancestors 'self';frame-src blob: 'self';object-src 'self' blob:;"
spec:
  rules:
  - 
    http:
      paths:
      - path: /<route>
        backend:
          serviceName: <service>
          servicePort: <port>

We need x-forward-host , host and referer in upstream server.  I think request is reaching but may be not with proper header. although no clear logs
our requirement is  there is API server (with kong) and front team want to connect to those API from their localhost so host is passing as localhost. We need it working from both localhost and environment itself.

Plugin as follow
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: kong-request-logging
config:
  path: /dev/stdout
plugin: file-log

**Comment by hbagdi** [comment]
Can you please elaborate on exact behavior you see when you issue a `curl` to kong in this case?
Otherwise, we will be guessing in the dark.

Another approach I recommend is deplying a httpbin service into your cluster, route traffic to it instead of your app and see if that works. You can also inspect headers received by the upstream service using an httpbin pod.
Please take a look at any of our guides in this repository for example manifests for that.

**Comment by jshahv** [comment]
I tried with different service and see that request itself not reaching. This service has no logic of checking host , x-forward-host or referer. seems route with host=null is not matched at all

**Comment by jshahv** [comment]
I double confirm and i can see now that route is not matching due to host=null so its matching to our  "/" route which goes to different page all together. Is there a solution for same ?  I can't put curl command output but i confirmed with CURL only

**Comment by hbagdi** [comment]
That seems unlikely. If you don't add in `hosts` and only want to use path based routing, that is indeed possible and works correctly.
Are you sure you don't have multiple Ingress resources in your cluster that are all trying to route based on path only (and have the same path)?

**Comment by jshahv** [comment]
yeah very sure no two routes with same path

**Comment by mflendrich** [comment]
Closing as stale.
