### ISSUE TITLE
KongCredential Error - Ingress Controller not starting

### ISSUE THREAD

**Issue by jshahv** [Kong/kubernetes-ingress-controller#896]
0.9.1 tag Ingress Contoller
: Failed to list *v1.KongCredential: the server could not find the requested resource (get kongcredentials.configuration.konghq.com)

What can be the issue for above error. Ingress controller not starting due to this

**Comment by jshahv** [comment]
I think recent removal of KongCredential is pushed to older docker image 0.9.1.  The code is still refering KongCredential causing Ingress Controller container not starting. This issue started coming today only

**Comment by hbagdi** [comment]
Can you please bump up the version of controller to `1.0` to fix this?

**Comment by jshahv** [comment]
Thanks Upgraded. We were worried as we are very near to go-live.  If any issue found will post it here. Thanks for quick help
