### ISSUE TITLE
Setting `enabled: false` not working

### ISSUE THREAD

**Issue by aaronhmiller** [Kong/kubernetes-ingress-controller#899]
### Summary

One of the properties of a KongPlugin is its enabled state (true/false). However, this setting isn't followed. It's always the default (true).

**Kong Ingress controller version**
1.0.0

**Kong or Kong Enterprise version**
2.1.4.1

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**: EKS 
- **OS** (e.g. from /etc/os-release): 
- **Kernel** (e.g. `uname -a`):
- **Install tools**: Helm
- **Others**:

### What happened

I've an otherwise working EKS deployment. When I define new plugin definitions and apply them to the Ingress, they show up.

However, I need to validate quickly behavior with the plugin enabled and disabled. This doesn't seem possible with KIC.

### Expected behavior
Setting `enabled: false` should work

### Steps To Reproduce

1. Add a plugin, configure it, setting enabled: false
2. kubectl apply -f <config.yaml>
3. Look at it in your Kong Manager
4. Notice that the plugin is still enabled

**Comment by rainest** [comment]
See https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/references/custom-resources.md#kongplugin

Unsure of the history behind why we chose a different name, but the setting should be `disabled: true`.

That inconsistency is admittedly confusing, and we should consider aligning terminology with the proxy in a future version of the CRD--breaking change however, so unfortunately not something we can handle easily.
