### ISSUE TITLE
Update CI/CD to handle main builds, and document main build availability

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#901]
CI/CD should handle producing builds from main. #900 was wrong, but there's not yet any right target to point it to. We need a main (and possibly next?) build, but currently only have some outdated master builds.

We reference these in docs, or rather previously referenced builds off master, and those appear to have gotten lost in the master->main transition.

Follow-up from #399 

Desired end state is that we produce builds from main, and docs point to those builds.

**Comment by mflendrich** [comment]
Scope:
- KIC
- deck
