### ISSUE TITLE
Unable to create credentials with API KEY

### ISSUE THREAD

**Issue by amitoo7** [Kong/kubernetes-ingress-controller#902]
Hello, 
I am trying to run following yaml to create credentials with API KEY 

apiVersion: configuration.konghq.com/v1
kind: KongCredential
metadata:
  name: topcred
consumerRef: top
type: key-auth
config:
  key: 123abc

But i am getting error 

error: unable to recognize "api.yaml": no matches for kind "KongCredential" in version "configuration.konghq.com/v1"

Kong version details

HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 48
Content-Type: application/json; charset=utf-8
Date: Fri, 09 Oct 2020 17:19:17 GMT
Server: kong/2.1.4
X-Kong-Response-Latency: 0

{
    "message": "no Route matched with those values"
}

**Comment by hbagdi** [comment]
Please use secrets instead of KongCredential resource. KongCredential resource has been removed with the release of 1.0:
https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/guides/using-consumer-credential-resource.md

**Comment by amitoo7** [comment]
Thankyou Very Much for you Help,

I am gonna close this issue.
