### ISSUE TITLE
how to get k8s service endpoint ip:port dynamically

### ISSUE THREAD

**Issue by zffocussss** [Kong/kubernetes-ingress-controller#903]
NOTE: GitHub issues are reserved for **bug reports only**.
For anything else, please join the conversation
in Kong Nation https://discuss.konghq.com/c/kubernetes.

---

### Summary

I wan to use url_hash like nginx to load balance to the pods directly.but I do not know how to get the endpoint ip:address as they may be changed after publish through CI/CD pipeline

**Kong Ingress controller version**
kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.7.0

**Kong or Kong Enterprise version**
2.0.4

### Kubernetes version

**paste `kubectl version` output**
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"afea77eefe3272c0f53c4552183ecb16c091db41", GitTreeState:"clean", BuildDate:"2020-09-17T06:32:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**:
AKS
- **OS** (e.g. from /etc/os-release):
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.6
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
- **Kernel** (e.g. `uname -a`):
Linux kong-kong-69f945f48d-rfw8b 4.15.0-1089-azure #99~16.04.1-Ubuntu SMP Fri Jun 5 15:30:32 UTC 2020 x86_64 Linux
- **Install tools**:
- **Others**:

**Comment by hbagdi** [comment]
I'm not sure if I'm understanding you but it seems like you would like to have deterministic load balancing of requests to upstream pods. If you want a solution like sticky session, please use KongIngress resource to achieve that.

Upstreams in kong are the abstracted load-balancers. The following doc should help:
https://docs.konghq.com/2.1.x/loadbalancing/
https://docs.konghq.com/2.1.x/admin-api/#upstream-object

**Comment by mflendrich** [comment]
Closing as stale.
