### ISSUE TITLE
Modify the kong ingress resource.

### ISSUE THREAD

**Issue by dayongi** [Kong/kubernetes-ingress-controller#907]
I want to modify the specific Kong Ingress through K8S REST API, but when i try that  i got following error.

![image](https://user-images.githubusercontent.com/41787764/95828627-cbfbc700-0d67-11eb-8423-7aebf823aa04.png)
![image](https://user-images.githubusercontent.com/41787764/95828660-d6b65c00-0d67-11eb-896f-7e78cacddc4c.png)

**Comment by mflendrich** [comment]
Hi @dayongi,

The error seems to suggest (contrary to what the screenshot shows) that you send the PUT request with an zero/empty/unset `metadata.resourceVersion`.

Kubernetes API expects incoming PUT requests to contain `metadata.resourceVersion` equal to `metadata.resourceVersion` in an already existing object. Please ensure that your PUT request contains `metadata.resourceVersion` equal to `metadata.resourceVersion` of the object you're updating.

If that doesn't work still, please reopen this issue and attach the full contents of `GET` and `PUT` requests and responses, including headers and body.

**Comment by mflendrich** [comment]
See https://github.com/kubernetes/kubernetes/issues/2115 for more context.
