### ISSUE TITLE
Run in DB mode, whether the configuration is updated partially or fully

### ISSUE THREAD

**Issue by cciechao** [Kong/kubernetes-ingress-controller#912]
Kong is deployed in k8s, and the DB is postgres. When the configuration of a certain service in k8s is changed, will only the changed part be updated or all data will be updated?

@hbagdi

**Comment by rainest** [comment]
The simple answer is that only the modified piece of configuration is updated.

From the controller's perspective, it will submit a request to Kong's admin API, and that request contains the modified or new resources only.

On the Kong side, this story is a bit more complex. Whichever node receives the change updates the copy of that resource in its in-memory cache, writes the new version of the resource to the database, and writes an event to the database indicating that the resource changed.

Other nodes in the cluster scan that events table continuously (at the interval specified by [db_update_frequency](https://github.com/Kong/kong/blob/2.2.0/kong.conf.default#L1048-L1055)) and, when they see new events, retrieve whichever resources changed from the database, and then update their in-memory copies with the retrieved resource.

Furthermore, there are some in-memory structures that also built from others: for example, a route change also instructs nodes to invalidate and rebuild the compiled router, which either happens immediately after pulling the new route from the database (strict consistency) or at a regular interval (eventual consistency) based on the [worker_consistency setting](https://github.com/Kong/kong/blob/2.2.0/kong.conf.default#L1188-L1227).

Does that answer your question, and if not, can you provide a bit more context for it? It'd help us provide a more detailed answer for it if we can understand why you're asking.

**Comment by mflendrich** [comment]
Closing as stale.
