### ISSUE TITLE
making HTTP request: Get \"https://127.0.0.1:8444/\": dial tcp 127.0.0.1:8444: connect: connection refused

### ISSUE THREAD

**Issue by huangkaiyan10** [Kong/kubernetes-ingress-controller#914]
I got below error logs in ingress-controller container and I am not even sure this is the root cause
please help look into this problem.
Thanks.

W1020 03:12:11.977313       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-10-20T03:12:11Z" level=info msg="version of kubernetes api-server: 1.17" api-server-host="https://10.96.0.1:443" git_commit=8d8aa39598534325ad77120c120a22b3a990b5ea git_tree_state=clean git_version=v1.17.4 major=1 minor=17 platform=linux/amd64
time="2020-10-20T03:12:12Z" level=info msg="retry 1 to fetch metadata from kong: making HTTP request: Get \"https://127.0.0.1:8444/\": dial tcp 127.0.0.1:8444: connect: connection refused"
time="2020-10-20T03:12:13Z" level=info msg="kong version: 2.1.4" kong_version=2.1.4
time="2020-10-20T03:12:13Z" level=info msg="datastore strategy for kong: postgres"
time="2020-10-20T03:12:13Z" level=info msg="chosen Ingress API version: networking.k8s.io/v1beta1"
time="2020-10-20T03:12:13Z" level=info msg="starting leader election" component=elector retry-count=1
I1020 03:12:13.359090       1 leaderelection.go:243] attempting to acquire leader lease  kong/ingress-controller-leader-kong...
time="2020-10-20T03:12:13Z" level=info msg="leadership changed" component=status-syncer leader=ingress-kong-5bfdc99fd9-9hwpj
I1020 03:12:55.036016       1 leaderelection.go:253] successfully acquired lease kong/ingress-controller-leader-kong
time="2020-10-20T03:12:55Z" level=info msg="leadership changed" component=status-syncer leader=ingress-kong-6b669986d-z8zrj

![8444 端口不能访问](https://user-images.githubusercontent.com/5146180/96538869-31056e80-12cc-11eb-80ce-896d0dc0340e.png)
![tls 404](https://user-images.githubusercontent.com/5146180/96538873-3367c880-12cc-11eb-9c32-9b5f4b9e7ab6.png)

![image](https://user-images.githubusercontent.com/5146180/96538913-4d091000-12cc-11eb-9dad-459b1b53c84a.png)

[all-in-one-postgres.zip](https://github.com/Kong/kubernetes-ingress-controller/files/5406159/all-in-one-postgres.zip)

**Comment by rainest** [comment]
What issue are you seeing? Those logs look normal, and the first screenshot (with the "successfully synced" message followed by "no configuration change" messages) is what you should see in logs when the controller is running normally. I'll cover the other messages below.

That error in the issue title is normal at startup: Kubernetes starts the controller and Kong containers at the same time, but there's no way to guarantee that Kong's admin API will come online before the controller starts attempting to talk to it. The controller will attempt to reconnect several times to account for possible lag between when it becomes ready. The message you see after indicates that it connected successfully after that first failed attempt, as it determined the Kong version:

```
time="2020-10-20T03:12:12Z" level=info msg="retry 1 to fetch metadata from kong: making HTTP request: Get "https://127.0.0.1:8444/\": dial tcp 127.0.0.1:8444: connect: connection refused"
time="2020-10-20T03:12:13Z" level=info msg="kong version: 2.1.4" kong_version=2.1.4
```
The controller retrieves that (and other information) from the Kong admin API, so it looks like you just observed a fairly normal situation where the Kong container started a bit more slowly than the controller container.

The 404 for `/mtls-auths` is normal as well if you're not using an Enterprise version of Kong: the [mTLS plugin](https://docs.konghq.com/hub/kong-inc/mtls-auth/) is Enterprise-only and its credentials endpoint doesn't actually exist on the admin API for the community version. We should perhaps improve the controller behavior there and not check for it if we don't see an Enterprise version string, but it's benign.

**Comment by mflendrich** [comment]
Closing as stale.
