### ISSUE TITLE
fail CI if `go mod tidy` is not no-op

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#917]
To help contributors avoid a review round trip (and ensure that our go module definitions are stable):

Add a CI check ensuring that `go mod tidy` leaves `go.mod` and `go.sum` unchanged.

**Comment by rainest** [comment]
Initial research finds that hey! we're not alone in wanting this! https://github.com/golang/go/issues/27005 is probably not moving anytime soon, so there's no built-in Golang tool to do this, and we likely won't have any available in the near future. However, there are several existing solutions that work around the lack of a first-party solution linked from that issue. Grafana's approach should be fine for us also, with some minor changes to fit it into a Github Action.
