### ISSUE TITLE
UDP in Railgun

### ISSUE THREAD

**Issue by rainest** [Kong/kubernetes-ingress-controller#925]
Kong 2.2 [introduces support for UDP routes](https://discuss.konghq.com/t/kong-2-2-0-alpha-1-is-released/7118).

From a KIC implementation standpoint, [TCPIngress](https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/references/custom-resources.md#tcpingress) has fields similar to what UDP routes will require, i.e. a hostname (handled via TLS SNI) and a port.

The user interface is an open question. Service APIs propose [HTTPRoute and TCPRoute resoruces](https://kubernetes-sigs.github.io/service-apis/concepts/#httptcpfooroute). In our current model, we could introduce a new UDPIngress CRD or augment TCPIngress to support protocols other than TCP, despite the name.

Upstream TLS is an open question. On the Kong end, there are `tls`, `tcp`, and `udp` services, and all are implemented via NGINX streams: https://github.com/Kong/kong/commit/967043e3b7df39fd98fad7f0b4588795b1d35609

**Comment by mflendrich** [comment]
TBD: whether the scope of this issue is only plain UDP (without DTLS) or UDP with DTLS support (DTLS offloading, SNI, etc.).

TBD: whether kubernetes (kube-proxy, networking) works nicely with UDP (including ICMP Port Unreachable, etc.)

**Comment by mflendrich** [comment]
We need to figure out whether to implement this on top of service-apis or existing KIC APIs.

**Comment by mflendrich** [comment]
Blocked by #1010 which will give us an answer whether to implement this on top of service-apis or not.

**Comment by mflendrich** [comment]
Blocked by #1043 - we need to understand whether this should go to KIC 2.0 or 1.x or both

**Comment by shaneutt** [comment]
I took a first pass at `UDPRoute` this in [this branch](https://github.com/shaneutt/kubernetes-ingress-controller/tree/udproute) and wanted to share for posterity (but we still do need to complete #1043 before we can move forward).

**Comment by shaneutt** [comment]
We're going to follow up on my [previous branch work](https://github.com/Kong/kubernetes-ingress-controller/issues/925#issuecomment-784497961) and spike a `v1alpha1.UDPIngress` in railgun.

**Comment by shaneutt** [comment]
Merged in `v1alpha1` and continued work on the UDPIngress API is covered by follow-up issues in the UDPIngress milestone.
