### ISSUE TITLE
auto-generate PRs bumping Kong core in KIC

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#933]
as @hutchic said, we can semi-automate the Kong bumps by collaborating with Kong/kong maintainers to make it:
* a release script item https://github.com/Kong/kong/blob/master/scripts/make-patch-release
* and a Jenkins post-release stage item https://github.com/Kong/kong/blob/master/Jenkinsfile#L333

to have it auto open PRs for us.

@hutchic said further:
> Prior art in those two places exists for vagrant, docker and homebrew

**Comment by shaneutt** [comment]
Stale. @scseanchow let us know if you think this is still something we should prioritize?
