### ISSUE TITLE
ACL consumer groups under version 1.0.0

### ISSUE THREAD

**Issue by YegorMedvedev** [Kong/kubernetes-ingress-controller#936]
### Summary
No ability to add ACL consumer groups with version 1.0.0

**Kong Ingress controller version**
1.0.0

**Kong or Kong Enterprise version**
Kong:  2.1.4

### What happened
Since `KongCredential` CRD is completely deprecated in version **1.0.0**, there are no options (_or at least no documented ones_) to create consumer groups using CRD.

### Expected behaviour
Expects that consumer ACL groups will be created using CRDs

**Comment by hbagdi** [comment]
You can use Secret resource to configure ACL as well:
https://github.com/Kong/kubernetes-ingress-controller/blob/main/docs/guides/using-consumer-credential-resource.md

**Comment by YegorMedvedev** [comment]
@hbagdi , don't get me wrong, but how exactly?

**Comment by Tim-Hodge** [comment]
Hi @hbagdi - an example for setting ACL groups against a KongConsumer would be really appreciated 👍

**Comment by Tim-Hodge** [comment]
@YegorMedvedev I found instructions here: https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/configure-acl-plugin.md#adding-acls

**Comment by jcam** [comment]
The docs in the repo have been removed, and the web docs don't discuss configuring secrets at all.
The old docs can be found here:

https://github.com/Kong/kubernetes-ingress-controller/blob/680027ef386290d993c43af8439ef721c327894b/docs/guides/configure-acl-plugin.md

@hbagdi it would be nice if this info could be properly incorporated in the web docs.
