### ISSUE TITLE
use p12 for jwt plugin in kongplugin in k8s

### ISSUE THREAD

**Issue by justmy2centx** [Kong/kubernetes-ingress-controller#943]
Is it possible to **use a p12 file instead of rsa_public_key** for the jwt plugin?
If yes what would i put in the K8s secret stringData field? do i need to change the consumer too?

Summary
SUMMARY_GOES_HERE

k get deploy -n kong -o yaml | grep image
image: kong-docker-kubernetes-ingress-controller.bintray.io/**kong-ingress-controller:1.0**
imagePullPolicy: IfNotPresent
image: **kong:2.1**
imagePullPolicy: IfNotPresent

Kubernetes version
k version --short
Client Version: v1.15.11-eks-065dce
Server Version: v1.16.13-eks-2ba888

### Environment
EKS Cluster managed
```
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: app-jwt-k8s
plugin: jwt
---
apiVersion: v1
kind: Secret
metadata:
  name: app-jwt-k8s
type: Opaque
stringData:
  kongCredType: jwt
  key: devk8s-issuer
  algorithm: RS256
  rsa_public_key: |-
    -----BEGIN PUBLIC KEY-----
    _REDACTED_
    -----END PUBLIC KEY-----
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: app-jwt-k8s
username: app-jwt-k8s
credentials:
  - app-jwt-k8s
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: echo-svc
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: app-jwt-k8s, allowed-src
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - http:
        paths:
          - path: /echo
            backend:
              serviceName: echo
              servicePort: 80```

**Comment by mflendrich** [comment]
Hi @justmy2centx ,

You cannot use the PKCS12 keystore (`*.pfx`, `*.p12`) with the JWT plugin directly.
You need to extract the public key from that keystore, and then put this public key in the secret.

You can use the `openssl` command for that by issuing a command similar to this:
```console
$ openssl pkcs12 -in your_keystore.p12 -clcerts -nokeys | openssl x509 -pubkey -noout
Enter Import Password: ****
-----BEGIN PUBLIC KEY-----
.....
.....
.....
-----END PUBLIC KEY-----

```

**Comment by justmy2centx** [comment]
> Hi @justmy2centx ,
> 
> You cannot use the PKCS12 keystore (`*.pfx`, `*.p12`) with the JWT plugin directly.
> You need to extract the public key from that keystore, and then put this public key in the secret.
> 
> You can use the `openssl` command for that by issuing a command similar to this:
> 
> ```
> $ openssl pkcs12 -in your_keystore.p12 -clcerts -nokeys | openssl x509 -pubkey -noout
> Enter Import Password: ****
> -----BEGIN PUBLIC KEY-----
> .....
> .....
> .....
> -----END PUBLIC KEY-----
> ```

Thanks!!
