### ISSUE TITLE
Service port cannot be set correctly

### ISSUE THREAD

**Issue by xbini** [Kong/kubernetes-ingress-controller#945]
### Summary

Service port cannot be config correctly

**Kong Ingress controller version**
1.0

**Kong or Kong Enterprise version**
2.1

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

### Environment

- **Cloud provider or hardware configuration**:
- **OS**: CentOS Linux release 7.8.2003 (Core)
- **Kernel** : Linux kube-control-plane 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: use https://raw.githubusercontent.com/Kong/kubernetes-ingress-controller/master/deploy/single/all-in-one-dbless.yaml file to deploy
- **Others**:

### What happened
service.port seems incorrect in logs.(via `kubectl logs`), but request is proxied correctly.

```json
...
"service": {
		"host": "joke-service.kong.443.svc",
		"created_at": 1604476286,
		"connect_timeout": 60000,
		"id": "b95c526b-b533-59f3-97c8-c73d93088877",
		"protocol": "https",
		"name": "kong.joke-service.443",
		"read_timeout": 60000,
		"port": 80,
		"path": "\/",
		"updated_at": 1604476286,
		"write_timeout": 60000,
		"retries": 5,
		"ws_id": "0dc6f45b-8f8d-40d2-a504-473544ee190b"
	}
...
```

### Expected behavior

service.port would be 443.

### Steps To Reproduce

1. create a kongingress
```ymal
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: common-kong-ingress
  namespace: kong
proxy:
  path: /
  protocol: https
route:
  strip_path: false
  preserve_host: false
  methods:
    - POST
    - GET
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
    - HEAD

```
2. create a service which type is  `ExternalName`
```ymal
apiVersion: v1
kind: Service
metadata:
  name: joke-service
  namespace: kong
  annotations:
    konghq.com/override: common-kong-ingress
    configuration.konghq.com: common-kong-ingress
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
  type: ExternalName
  externalName: 192.168.1.14
```
3. create a ingress
```ymal
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: express-start-ingress
  namespace: kong
  annotations:
    konghq.com/override: common-kong-ingress
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: lb.learn.com1
      http:
        paths:
          - path: /getJoke
            backend:
              serviceName: joke-service
              servicePort: 443
```
4. create a global plugin(file-log)
```ymal
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: file-log-plugin
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  path: /dev/stdout
plugin: file-log

```
5. make a request

----- 

Then I found the this in log
``` json
...
	"tries": [{
		"balancer_latency": 0,
		"port": 443,
		"balancer_start": 1604476290466,
		"ip": "192.168.1.14"
	}]
...
```

After that, I find that there is not override s.port in this file `~/kubernetes-ingress-controller/internal/ingress/controller/parser/service.go`

```go
...
// overrideByKongIngress sets Service fields by KongIngress
func (s *Service) overrideByKongIngress(kongIngress *configurationv1.KongIngress) {
	if kongIngress == nil || kongIngress.Proxy == nil {
		return
	}
	p := kongIngress.Proxy
	if p.Protocol != nil {
		s.Protocol = kong.String(*p.Protocol)
	}
	if p.Path != nil {
		s.Path = kong.String(*p.Path)
	}
	if p.Retries != nil {
		s.Retries = kong.Int(*p.Retries)
	}
	if p.ConnectTimeout != nil {
		s.ConnectTimeout = kong.Int(*p.ConnectTimeout)
	}
	if p.ReadTimeout != nil {
		s.ReadTimeout = kong.Int(*p.ReadTimeout)
	}
	if p.WriteTimeout != nil {
		s.WriteTimeout = kong.Int(*p.WriteTimeout)
	}
}
...
```

Is this a bug?
Or, my configuration is incorrect?

**Comment by hbagdi** [comment]
This is known and is harmless. The port that is actually being used is defined in Target.
Do you have any problem proxying requests via Kong when this configuration is present?

**Comment by xbini** [comment]
@hbagdi ，thanks!

I am not meeting other problems in my use case.
