### ISSUE TITLE
Document the way to specify nginx worker process count

### ISSUE THREAD

**Issue by mflendrich** [Kong/kubernetes-ingress-controller#955]
There are cases where specifying the number of nginx worker processes is desirable. For example, the /config may take substantial time to process, and therefore stall Kong for proxied requests if the count of worker processes is 1. Also, the "auto" setting (which adjusts the count in accordance with # of available CPU cores) isn't a good fit for kubernetes deployments.

**Comment by rainest** [comment]
There shouldn't be much reason to document this separately--worker count is [a kong.conf setting](https://github.com/Kong/kong/blob/2.2.0/kong.conf.default#L448-L454), and we document those settings equivalence to environment variables in general:

https://docs.konghq.com/2.2.x/configuration/#environment-variables
https://github.com/Kong/charts/tree/main/charts/kong#the-env-section

While the standard kong.conf default is `auto`, we intentionally override this in all example deployment configuration, and it should be reasonably obvious how to change it, as those overrides are in user-facing configuration. Do we still think there's something to do here separately?

**Comment by mflendrich** [comment]
Closed as won't fix, per @rainest's explanation.
