### ISSUE TITLE
how to set proxy_connect_timeout for an ingress serving multiple services

### ISSUE THREAD

**Issue by Sam123ben** [Kong/kubernetes-ingress-controller#962]
### Summary

I did saw a few similar issues already in Dec 2019 but the resolution were not satisfactory. I have an ingress rule which serves multiple services with different paths in it. I am using the 2.0 Kong after we recently moved from Nginx Ingress controller.

Using the Nginx I used to set the timeout using Nginx annotations in the ingresses itself and that used to work without any issues but after we moved to Kong, the timeout setting is not working as per the docs suggested by Kong.

https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/guides/using-kongingress-resource.md
https://github.com/Kong/kubernetes-ingress-controller/blob/master/docs/references/custom-resources.md#kongingress

As default timeout value is 1 min for the reason our page timeout while a few customers still trying to match the speed and in the same it result in timeout for the form.

**Kong Ingress controller version**
2.0

**Kong or Kong Enterprise version**
NA

### Kubernetes version
1.18.8
$ **kc version --short**
Client Version: v1.19.0
Server Version: v1.18.8

### Environment

Cloudprovider (AKS)

### What happened
The timeout never took effect after I followed the wiki suggested by Kong to create a new **KongIngress** in the cluster. Basically I created the KongIngress user the kong namespace and then my ingress is in another dev namespace and annotated it hoping it will work. I tried the same with service too by annotating it as well but that didn't worked too.

### Expected behavior
It should take effect of the timeout and ensure it work without crashing the form after 1 min.

### Steps To Reproduce

1. Edit and save the **KongIngress.yaml**:

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: custom-kongingress
upstream:
  slots: 10
  hash_on: none
  hash_fallback: none
  healthchecks:
    threshold: 25
    active:
      concurrency: 10
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 0
        successes: 0
      http_path: "/"
      timeout: 1
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        interval: 0
        tcp_failures: 0
        timeouts: 0
    passive:
      healthy:
        http_statuses:
        - 200
        successes: 0
      unhealthy:
        http_failures: 0
        http_statuses:
        - 429
        - 503
        tcp_failures: 0
        timeouts: 0
proxy:
  protocol: https
  path: /
  connect_timeout: 600000
  retries: 3
  read_timeout: 600000
  write_timeout: 600000
route:
  methods:
  - POST
  - GET
  regex_priority: 0
  strip_path: false
  preserve_host: true
  protocols:
  - http
  - https

2. kubectl apply -f KongIngress.yaml -n kong

3. annotate the ingress with **"configuration.konghq.com: demo-customization"**

4. Expect it to work but it didn't

**Comment by rainest** [comment]
Modern versions of the controller use `override` annotations to bind KongIngress resources: https://docs.konghq.com/kubernetes-ingress-controller/1.0.x/references/annotations/#konghqcomoverride

There are still some lingering references to the old `configuration.konghq.com` annotation, which are further complicated by our recent migration from docs in the repository to docs.konghq.com. We're sorting those out; our apologies for any confusion in the meantime.

Using that `override` annotation (with both the Service and KongIngress in the same namespace) instead should sort this out--are you still seeing the setting not taking with it in place?

**Comment by Sam123ben** [comment]
> Modern versions of the controller use `override` annotations to bind KongIngress resources: https://docs.konghq.com/kubernetes-ingress-controller/1.0.x/references/annotations/#konghqcomoverride
> 
> There are still some lingering references to the old `configuration.konghq.com` annotation, which are further complicated by our recent migration from docs in the repository to docs.konghq.com. We're sorting those out; our apologies for any confusion in the meantime.
> 
> Using that `override` annotation (with both the Service and KongIngress in the same namespace) instead should sort this out--are you still seeing the setting not taking with it in place?

Thanks a lot for the update and it fixed it. Just 1 question though will the ** KongIngress** be in the same namespace where the ingress for my app is or that ** KongIngress** can be part of the kong namespace where the kong ingress controller is installed and running.

**Comment by rainest** [comment]
KongIngress resources should reside in the same namespace as the Ingress or Service resources they modify. That will usually be separate from the namespace that Kong is running in, unless you're creating them for Kong's own services (e.g. the admin API).

**Comment by Sam123ben** [comment]
> KongIngress resources should reside in the same namespace as the Ingress or Service resources they modify. That will usually be separate from the namespace that Kong is running in, unless you're creating them for Kong's own services (e.g. the admin API).

Got it thanks :)
