### ISSUE TITLE
Can kong api gateway communicate to cassandra cluster with in k3s

### ISSUE THREAD

**Issue by sandhyarme** [Kong/kubernetes-ingress-controller#967]
Hi All,

We have k3s cluster with postgres as datastore, also we have cassandra cluster deployed in k3s. We have deployed kong ingress with cassandra db using https://github.com/Kong/kubernetes-ingress-controller/blob/main/deploy/single/all-in-one-postgres.yaml
replaced postgres with cassandra as below in yaml file.

name: KONG_DATABASE
value: cassandra
- name: KONG_CASSANDRA_HOST
value: cassandra
- name: KONG_CASSANDRA_PASSWORD

kong_cassandra_host means system ip where cassandra installed or username ? since cassandra is deployed as cluster on 2 nodes so which node ip to provide…
there is no sample yaml file for kong with cassandra…

deployment.apps/ingress-kong and statefulset.apps/cassandra are not running due to which pod/kong-migrations and pod/ingress-kong pods are not running.
attached screenshot…

[root@kong ~]# kubectl get logs pod/ingress-kong-844c848f94-7ml6q -n kong
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. ‘kubectl get resource/<resource_name>’ instead of ‘kubectl get resource resource/<resource_name>’

Receiving 503 service unavailable error from accessing kong admin api…
curl -i $PROXY_IP

[root@kong ~]# kubectl get nodes -o wide
NAME           STATUS   ROLES    AGE   VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
kong.master    Ready    master   21d   v1.18.9+k3s1   15.213.142.139   <none>        CentOS Linux 7 (Core)   3.10.0-1127.19.1.el7.x86_64   docker://19.3.13
master.local   Ready    <none>   20d   v1.19.3+k3s2   15.213.141.56    <none>        CentOS Linux 7 (Core)   3.10.0-1127.19.1.el7.x86_64   docker://19.3.13
------------------------------------------------------------

[root@kong ~]# kubectl get all -n cass-operator -o wide
NAME                                READY   STATUS    RESTARTS   AGE   IP          NODE           NOMINATED NODE   READINESS GATES
pod/cass-operator-f68f44f8f-fqpht   1/1     Running   0          46h   10.42.1.6   master.local   <none>           <none>
pod/cluster1-dc1-default-sts-0      2/2     Running   0          33h   10.42.1.8   master.local   <none>           <none>
pod/cluster1-dc1-default-sts-1      2/2     Running   0          33h   10.42.0.9   kong.master    <none>           <none>

NAME                                          TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE   SELECTOR
service/cassandradatacenter-webhook-service   ClusterIP   10.43.12.73    <none>        443/TCP             46h   name=cass-operator
service/cass-operator-metrics                 ClusterIP   10.43.130.83   <none>        8383/TCP,8686/TCP   46h   name=cass-operator
service/cluster1-dc1-service                  ClusterIP   None           <none>        9042/TCP,8080/TCP   33h   app.kubernetes.io/managed-by=cassandra-operator,cassandra.datastax.com/cluster=cluster1,cassandra.datastax.com/datacenter=dc1
service/cluster1-seed-service                 ClusterIP   None           <none>        <none>              33h   cassandra.datastax.com/cluster=cluster1,cassandra.datastax.com/seed-node=true
service/cluster1-dc1-all-pods-service         ClusterIP   None           <none>        <none>              33h   app.kubernetes.io/managed-by=cassandra-operator,cassandra.datastax.com/cluster=cluster1,cassandra.datastax.com/datacenter=dc1

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS      IMAGES                         SELECTOR
deployment.apps/cass-operator   1/1     1            1           46h   cass-operator   datastax/cass-operator:1.1.0   name=cass-operator

NAME                                      DESIRED   CURRENT   READY   AGE   CONTAINERS      IMAGES                         SELECTOR
replicaset.apps/cass-operator-f68f44f8f   1         1         1       46h   cass-operator   datastax/cass-operator:1.1.0   name=cass-operator,pod-template-hash=f68f44f8f

NAME                                        READY   AGE   CONTAINERS                       IMAGES
statefulset.apps/cluster1-dc1-default-sts   2/2     33h   cassandra,server-system-logger   datastax/cassandra-mgmtapi-3_11_6:v0.1.0,busybox
---------------------------------------------------------

<img width="943" alt="KongNamespace" src="https://user-images.githubusercontent.com/48059350/100639044-b6178500-335a-11eb-8973-f286feaba0f4.PNG">

**Comment by sandhyarme** [comment]
[KongIngress-Cassandra.txt](https://github.com/Kong/kubernetes-ingress-controller/files/5617426/KongIngress-Cassandra.txt)
yaml file used to deploy kong ingress

**Comment by hbagdi** [comment]
Kong+Cassandra is deprecated and is set to be removed shortly. Please either use Kong with Postgres or Kong in DB-less mode.

**Comment by rainest** [comment]
Closing this as Cassandra-backed controller-managed instances are no longer supported, which is why we do not provide example configuration for them. If you are using an older version where Cassandra is supported, Kong failing to start while no Cassandra instances are online is expected; you'd need to resolve whatever issue is preventing Cassandra from starting for Kong to start.
