### ISSUE TITLE
kong and 302 redirects

### ISSUE THREAD

**Issue by huangkaiyan10** [Kong/kubernetes-ingress-controller#980]
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-springbootzipkin
  namespace: test
  annotations:
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /springbootzipkin
        backend:
          serviceName: springbootzipkin
          servicePort: 3000

--------------------

I test it with:

wget http://${GATEWAY_URL}/springbootzipkin
--2018-12-21 12:56:30--  http://10.109.22.156/springbootzipkin
Connecting to 10.109.22.156:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: ./zipkin/ [following]
--2018-12-21 12:56:31--  http://10.109.22.156/zipkin/
Reusing existing connection to 10.109.22.156:80.
HTTP request sent, awaiting response... 404 Not Found
2018-12-21 12:56:31 ERROR 404: Not Found.

**Comment by mflendrich** [comment]
@huangkaiyan10,

The 302 redirect tells the user agent (here: wget) to make another request to the specified location.

It appears that you have defined an Ingress path for `/springbootzipkin` but not for `/zipkin/`. The ingress backend makes a redirect to `/zipkin/` for which Kong does not have a route defined.

This is most likely misconfiguration of your application - it makes redirects to an (absolute) URL outside of the context path `/springbootzipkin`. The best way to fix this would be to configure redirects in your application as relative.

If the backend is zipkin, this might be helpful: https://github.com/openzipkin/zipkin/issues/1452

HTH,
Michal
